### ISSUE TITLE
Ryad Ability break game

### ISSUE THREAD

**Issue by Nate0026** [Sandrem/FlyCasual#1002]
whenever you use Countess Ryads ability the game breaks

**Comment by rune-b** [comment]
It works fine for me. How does it break the game for you? Do you get an error message?

The interface for the ability is a bit strange though. Would have been better with a simple yes/no question I think.

**Comment by Sandrem** [comment]
In local mode or in multipayer? Do you get red error message, or only game is stopped?

**Comment by Nate0026** [comment]
It is in multiplayer online. Anytime I used Ryad's ability or did a white 4 k-turn I would get a red error message. Then I couldn't do anything else after exiting out of the error. It happened for me every time. I will do it again and send you a SC of the message

**Comment by andrelpgoncalves** [comment]
Do you some evidence of the problem?

**Comment by Sandrem** [comment]
Closed due to network mode rework

**Comment by jpltanis** [comment]
Sandrem, Ryad, during internet mode cause the game to hang again. It doesn't crash or anything. The game appears to be stuck in a loop, waiting for something....
