### ISSUE TITLE
Blinded Pilot not preventing attack

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#1010]
I just had a game where Kylo Ren took a damage from a T-70 and showed him the dark side. I chose Blinded Pilot, and the turn after i triggered the ability. The X-Wing lost its shield from my crit correctly, and "Blinded Pilot" even popped up over the ship!
But right after that, the ship can normally fire at my Tie Defender, Blinded Pilot not having any effect.

**Comment by bravodingo** [comment]
I'd suggest retitling this to "Kylo Condition Blinded Pilot crit doesn't prevent attack," only because Blinded Pilot definitely works when drawn in normal critical hit situations (the latter happened to me and AI in different games, worked correctly).  Likely a coding issue with the condition(?).

**Comment by Sandrem** [comment]
I checked situation in currect version - cannot reproduce this bug.
