### ISSUE TITLE
Network Game Locking Up Repeatedly

### ISSUE THREAD

**Issue by starfuryth** [Sandrem/FlyCasual#1013]
Having a fairly consistent problem with network games locking up (program doesn't crash) after many turns. I've played maybe 6-8 games so far with my daughter, and out of those 2/3 have locked up before we can finish the game.

Both computers are on the same LAN, my computer (Win10 PC) is hardwired into the router, hers (Macbook Pro) is on wireless, both have internet access.  Everything seems to work great, but after a while the game locks after an action/movement/etc and doesn't allow the next ship/player to take a turn. Neither players listed at the top of the screen have the green bar to indicate whose turn it is.

**Comment by ScottKarch** [comment]
AI games working great..    Just tried 3 games in a row with my son via LAN and had similar issues.   I'll see if we can repliate the issue about the green bar showing who's turn it is and report back.  If you have anything else to look for, let me know and I'll try it.

**Comment by Sandrem** [comment]
Closed due to network mode rework
