### ISSUE TITLE
Bugs with Ghost-docked Phantom

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#1017]
Hello there!

I made an AI squad based on a friend's list and it includes a Ghost with a docked Phantom. When I destroy the Ghost, the game allows me to choose the Phantom's movement and a free action but, no matter which movement I choose, the Phantom never shows up on the table. When the next round starts, the Phantom moves and selects actions, but neither acquires targets nor can be targeted at the Combat phase.

Then, I had the idea to play with my friend's list and see if the bug happens to the player as well, and it did. I can select the movements at the ship's title on the left and can choose the actions, then I selected barrel roll for testing and the range 1 ruler and the ship's base showed up! Yet, I couldn't target or be targeted by anyone at the Combat phase. BUT, at the moment where I was typing this, the Phantom showed up by itself and the TIE's started firing at me and I was able to fire back at them!

Any ideas on what caused this issue?

![phantom bug 1](https://user-images.githubusercontent.com/1640572/41731854-e31f0796-7555-11e8-8702-2a94b714399f.PNG)
![phantom bug 2](https://user-images.githubusercontent.com/1640572/41731856-e349fadc-7555-11e8-9768-9d6819a56fbd.PNG)
![phantom bug 3](https://user-images.githubusercontent.com/1640572/41731857-e383b1d2-7555-11e8-8344-a1fe3f1ab619.PNG)
![phantom bug 4](https://user-images.githubusercontent.com/1640572/41731859-e4d66d18-7555-11e8-8aab-35fb27c930af.PNG)
![phantom bug 5](https://user-images.githubusercontent.com/1640572/41732953-dbf33674-7558-11e8-80e9-5b5948fe520f.PNG)
![phantom bug 6](https://user-images.githubusercontent.com/1640572/41732954-dc2075f8-7558-11e8-9d5e-c1c7674411df.PNG)
![phantom bug 7](https://user-images.githubusercontent.com/1640572/41732956-dc529a06-7558-11e8-8487-75a30fcb6298.PNG)
![phantom bug 8](https://user-images.githubusercontent.com/1640572/41732957-dc8346a6-7558-11e8-8832-cbe6f47dac03.PNG)
![phantom bug 9](https://user-images.githubusercontent.com/1640572/41732958-dcf87570-7558-11e8-88d7-4a111c0cffa7.PNG)
![phantom bug 10](https://user-images.githubusercontent.com/1640572/41733198-87465178-7559-11e8-88ab-c04011259921.PNG)
![phantom bug 11](https://user-images.githubusercontent.com/1640572/41733199-876f7f1c-7559-11e8-9385-4878cc340ddd.PNG)

**Comment by Sandrem** [comment]
Some bugs with emergency eject are fixed.
