### ISSUE TITLE
Error when Selecting Ship for Optimized Prototype Condition

### ISSUE THREAD

**Issue by Juanflaco** [Sandrem/FlyCasual#1018]
Receiving NullReferenceException when selecting ship for Director Krennic's Optimized Prototype condition (in this case selecting the Inquisitor).
![optimized_prototype error](https://user-images.githubusercontent.com/38587032/41821331-341446e6-779c-11e8-98cd-fc4e8167d6b8.jpg)

Thanks for taking a look!

**Comment by Sandrem** [comment]
Fixed in dev-version. Please, wait for release of new version.

**Comment by Juanflaco** [comment]
Thanks. I hope the patreon is going well for you. I'm sure the move to 2.0 has introduced a ton of new challenges.
