### ISSUE TITLE
V1:  Doing a red manuever causes ship to lose action, even if the stress is removed

### ISSUE THREAD

**Issue by AbsoluteDisgrace** [Sandrem/FlyCasual#1023]
Example:  Hobbie with Targeting Astromech.  If you do a K-Turn, then use the Targeting Astromech to achieve a lock, hobbie removes the stress.  This is done prior to the "Action" step and he should get an action.

**Comment by Sandrem** [comment]
Already fixed in dev-version. Fix will be released in the nearest update.
