### ISSUE TITLE
Null reference on target lock for AI K4

### ISSUE THREAD

**Issue by JeffCookHAN** [Sandrem/FlyCasual#1026]
Setup a game with some K4 droids on AI Scurrgs and on round 3 or 4 after activation of one of the AI Scurrgs this error threw. imgs attached.
![k4 ai error 1](https://user-images.githubusercontent.com/29730639/41872695-fe066c3c-78c2-11e8-863d-3cfb74f89507.jpg)
![k4 ai error 2](https://user-images.githubusercontent.com/29730639/41872696-fe2134b8-78c2-11e8-9916-3ade13d249d4.jpg)

**Comment by Sandrem** [comment]
Fixed
