### ISSUE TITLE
Cannot apply Optimized Prototype to Pure Sabaac

### ISSUE THREAD

**Issue by Jester238** [Sandrem/FlyCasual#1027]
When selecting a a ship to receive Optimized Prototype at the beginning of the game, I cannot apply it to Pure Sabaac.

![image](https://user-images.githubusercontent.com/40012724/41885629-a39813aa-78ad-11e8-9286-8d1ceee0c942.png)

**Comment by Sandrem** [comment]
Alredy fixed in dev-version. Please, wait for release of new update.
