### ISSUE TITLE
"Whisper" causes error after moving

### ISSUE THREAD

**Issue by CJPT** [Sandrem/FlyCasual#1029]
![image](https://user-images.githubusercontent.com/28097007/42083295-5f53bb04-7b82-11e8-965c-69599c3d0a79.png)

Tested with and without 'Optimised Prototype' assigned - error occurs immediately after Whisper moves.

**Comment by JeffCookHAN** [comment]
Same behaviour immediately after whisper moves, heres the start of the script error:
![whisper error](https://user-images.githubusercontent.com/29730639/42104409-be93ceac-7bcc-11e8-8732-c412529c7696.jpg)

**Comment by AbsoluteDisgrace** [comment]
It happens on the action step. If you use advanced sensors, you get the error as well.

**Comment by Sandrem** [comment]
Fixed
