### ISSUE TITLE
AI rolls more than once when landing on Asteroid

### ISSUE THREAD

**Issue by Charliewking** [Sandrem/FlyCasual#1030]
When playing AI, the opponent rolls for damage from landing on an obstacle more than once in some cases. In some cases it rolls until it no longer has any hull and shield points left.

**Comment by AbsoluteDisgrace** [comment]
Had it happen to my player ship. Got 4 asteroid triggers.

**Comment by bravodingo** [comment]
Happens on occasion with AI, also; tonight it happened against AI Scurrgs.

**Comment by Sandrem** [comment]
Fixed.
