### ISSUE TITLE
0.5.1 2E Concordia Faceoff Incorrectly Triggers

### ISSUE THREAD

**Issue by LawstDragon** [Sandrem/FlyCasual#1032]
Concordia Faceoff ability triggers if ANY opponent is in range 1 arc, instead of just the attacker.

**Comment by Sandrem** [comment]
Cannot reproduce.
Code checks "range of current attack is 1".

Please, try to reproduce and provide screenshot.

**Comment by Sandrem** [comment]
Still cannot reproduce. Closed.
