### ISSUE TITLE
game froze when phantom shuttle emergency ejected from ghost

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1038]
it was my opponents ship.  got the red code splash and game hung

**Comment by Sandrem** [comment]
Please, next time take a screenshot with red text - it has useful information about reason of the bug, and this saves my time. Also, on screenshot I can see situation and used cards - sometimes bug is caused by specific upgrade, for example.

**Comment by Sandrem** [comment]
Seems that bug is related to this: https://github.com/Sandrem/FlyCasual/issues/688

**Comment by Sandrem** [comment]
Some bugs with emergency eject are fixed. If you will encounter bug again - please, provide screenshot.

**Comment by VexingVision** [comment]
Emergency deployment of the Nashtah Pup resulted in a game freeze and this red text:

![image](https://user-images.githubusercontent.com/28895989/62410421-62215280-b5e5-11e9-937f-9d2937aa6f75.png)

**Comment by YuriFMelo** [comment]
My game is crash when the Nashtah up emergency deploy, version 1.0.1
![Nashtah pup](https://user-images.githubusercontent.com/64886969/81142498-36514580-8f46-11ea-8596-b51d38780437.jpg)
