### ISSUE TITLE
0.5.1 1E hitting AI with tractor beam sometimes causes multiple triggers

### ISSUE THREAD

**Issue by JeffCookHAN** [Sandrem/FlyCasual#1039]
Promts for which trigger to resolve first. First resolves normally, second hangs if any maneuver is chosen, regardless of # order of triggers.

**Comment by Brother-Andy** [comment]
+ second hangs if Skip was hit instead of maneuver.

TIE-D with Maarek and Tractor Beam with two hits and one crit.

**Comment by JeffCookHAN** [comment]
Mine also with TIE-D but with Col. Vessery

**Comment by Sandrem** [comment]
Fixed
