### ISSUE TITLE
0.5.1 Enemy ships never get stressed

### ISSUE THREAD

**Issue by h3170n** [Sandrem/FlyCasual#1043]
Enemy ships never get stress tokens after performing red maneuvers. U-wing two tubes bro, for example, stays still for multiple rounds WHILE performing focus actions.

Congrats on the app, though. I use the apk version.

**Comment by Sandrem** [comment]
AI uses rules of "Heroes of the Aturi Cluster" AI. Instead of stress, AI ships just skip action. (Also few another changes in rules).

Not a bug.
