### ISSUE TITLE
0.5.1 1E Vader crew only display a 1 damage icon to the carrying ship

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#1045]
I put Darth Vader on two different ships to confirm (RAC and Vizier, didn't test any others) that his card text will only deal 1 damage (instead of 2) to the ship carrying him.  It does correctly deal 1 damage to the target/hit ship.

**Comment by kyledsimpson** [comment]
After looking at this again, Vader does actually deal 2 damage to the ship - but the damage icon that pops up only shows 1 damage.  So I'll change the bug title now.

**Comment by Sandrem** [comment]
Fixed
