### ISSUE TITLE
0.5.1 1E Agent Kallus crashes the game during setup phase

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#1049]
I tested with Agent Kallus on two different ships (TIE bomber and Lambda shuttle) and two different AI opponent squads.  I completely reloaded the game between tests just to make sure.  I get this same error https://ibb.co/jVaGsJ

This error output happens immediately after I pick from one of the choices in the menu at the bottom.

If you need more info let me know.  Thanks

**Comment by Sandrem** [comment]
Fixed
