### ISSUE TITLE
Snap Shot - Should not trigger outside of primary arc

### ISSUE THREAD

**Issue by bravodingo** [Sandrem/FlyCasual#1053]
This is more of a bug than a problem.  Knowledgeable players should simply 'Skip' the trigger when it occurs.

Example:  Ezra (Sheathepeade) with Snap Shot should only trigger when an enemy ship completes a maneuver into Range 1 of him...but as a secondary weapon, it can only be used out of the primary (front-facing) arc.  The UI will prompt user to use Snap Shot (to include selecting a target), and it will allow Snap Shot to fire at enemies who have maneuvered into Range 1 of the rear-facing arc...which is not allowed per the rules of secondary weapons.

**Comment by Sandrem** [comment]
Thank you for help in testing.
You can participate in testing of dev-versions of code.
Here is our workspace, you are welcome: https://join.slack.com/t/flycasualgame/shared_invite/enQtMzY5OTgyMjAzODcyLWFmZjcxNjhiYjA5MDZmYjEwNWJmMmY3MzA3YjRkMjE4MDkzODEzZmY5NjYyZmRlMDAzM2JjNmMzN2VjYTEzMDM

**Comment by bravodingo** [comment]
Cool.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sandrem** [comment]
Fixed
