### ISSUE TITLE
Pulsed Ray Shield - Ion Removal post-maneuver (Bug)

### ISSUE THREAD

**Issue by bravodingo** [Sandrem/FlyCasual#1056]
UI prompts multiple ionization removal trigger options.

![pulsed ray shield 1](https://user-images.githubusercontent.com/40216640/42405516-61b3cbda-8165-11e8-9eeb-93df13d80fa5.png)

Not a game-breaker.  Could be related to asteroid multi-roll bug.  Selecting all the options creates no additional issue/freeze.

**Comment by Sandrem** [comment]
Already fixed yesterday.
