### ISSUE TITLE
0.5.2 - Tractor Beam hangs the game

### ISSUE THREAD

**Issue by Brother-Andy** [Sandrem/FlyCasual#1057]
Vessery with TB.
After scurrg had moved (by TB effect) game immediately hanged.

![2018-07-08](https://user-images.githubusercontent.com/14282170/42418518-d34479d4-82aa-11e8-9833-02cbbb02d97f.png)

**Comment by Sandrem** [comment]
Error says something about bomb, not about tractor beam.
Do you remember your last actions with bombs?

**Comment by Brother-Andy** [comment]
During activation phase I had dropped proximity mines and scurrg landed on the token. Then same scurrg was moved with TB during combat phase.

**Comment by Sandrem** [comment]
Thank you, I will try to reproduce.

**Comment by Sandrem** [comment]
Was fixed
