### ISSUE TITLE
0.5.2 - Tractor Beam moves ship out of the game board

### ISSUE THREAD

**Issue by Brother-Andy** [Sandrem/FlyCasual#1058]
Vessery shoots with TB at Lowhhrick. Got a hit.
I try to move Lowhhrick with left barrel roll, but ship cannot be placed out of game board(error message appeared).
After error message the game hangs - I cannot make a Vessery's second attack with primary or select other ship to make attack etc.

Workaround: say in the console "triggers finish".

![2018-07-08 1](https://user-images.githubusercontent.com/14282170/42418994-a723affa-82b4-11e8-806d-ee74933072ee.png)
![2018-07-08 2](https://user-images.githubusercontent.com/14282170/42418995-a74206e4-82b4-11e8-9d11-ce9902896358.png)

Then Vessery shoots at Lowhhrick with primary and destroys it.
Immediately console error was caugth.

![2018-07-08 3](https://user-images.githubusercontent.com/14282170/42419044-b88d8616-82b5-11e8-93b9-6e6342cbbc7e.png)

**Comment by Sandrem** [comment]
Fixed
