### ISSUE TITLE
0.5.2. Setup Map Zoom/Scaling (2D vs 3D)

### ISSUE THREAD

**Issue by bravodingo** [Sandrem/FlyCasual#1059]
Edit:  This is definitely related to restarting [or starting] a game when the previous instance was ended in 2D mode.  It can be fixed by switching to 3D mode, **and then** either choosing to restart, or exiting to the main menu and starting a new game.

This appears to be completely random, but when a game is started, prior to obstacle placement, the board is either extremely zoomed-in [in 3D mode], or rectangular and glitchy [in 2D mode].  A restart via the escape menu inconsistently fixes the error.

Not sure if this is related to the new Hoth 3D map, but this does happen with other game boards, i.e. plain stars.

**Comment by bravodingo** [comment]
This can be recreated when the game is restarted from 2D mode.

**Comment by Sandrem** [comment]
Was fixed in 0.6.1
