### ISSUE TITLE
Krennic and Benthic 

### ISSUE THREAD

**Issue by Jek1138** [Sandrem/FlyCasual#1064]
Had issues in an online game. I was unable to select a ship for Krennic's Optimized Prototype condition during the place forces step. There was a phase for it but I there was no prompt and I could not select a valid ship (Soontir Fel). I did have a skip button and once pressed I was able to place a ship in the play area. I game played fine until Fel's first shot, then error console popped up and game crashed. I did not get a screenshot and have not tried to replicate yet. 

Next, I was unable to use Benthic Two Tubes' ability. This could have been an issue with also having Jan Ors on board (I did not use Jan's ability to flip the focus to evade). After prompted to use Jan's ability (selected no) there was a phase where I all I could do was skip, I assume this is where his ability was supposed to be. I was able to complete the game without any crashing. 

I know this is not a lot of helpful troubleshooting information.

**Comment by Sandrem** [comment]
Please, next time when you will encounter problem - open console (CTRL + ~) and attach screenshot, this can be useful.

**Comment by Jek1138** [comment]
Both Krennic and Benthic work in a local/AI game. The prompt does not appear in a Network game. Will post console screenshot of network game when I get the chance.

**Comment by Sandrem** [comment]
Still cannot reproduce / no new reports.
Closed.
