### ISSUE TITLE
AI Brobots can still do red maneuvers (S-loops) when stressed

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1065]
I have the AI brobots doing s-loops when stressed, and double stressed by Rebel Captive, and Flechette Cannons. They shouldn't be able to do that, right?

BTW, thanks for this awesome sim. 

I'd also love to see Ruthlessness ept for X-wing 1.0  :)

**Comment by Sandrem** [comment]
In 0.5.2, when you start battle vs AI, you will see information about rules of AI. (It uses rules of HotAC AI, it has differences in few things, like stress).
I added that information because I got a lot reports of this "bug".

Not a bug, closed.

**Comment by TNG-Wing** [comment]
Sorry, I didn't realize.

Thanks!
