### ISSUE TITLE
Interenet Game starts with no obstacles

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1066]
I apologize if I should know the answer to this, but when I started an internet game, and an online opponent joined, after deciding to take initiative, there are no obstacles to select. We could not proceed with the game.

Thanks in advance!

![capture](https://user-images.githubusercontent.com/26996014/42530100-25bc679a-8435-11e8-8e8c-10df1d45b8f5.JPG)

**Comment by Sandrem** [comment]
Closed due to network mode rework
