### ISSUE TITLE
Game freezes when AI quickdraw fires first shot of the game.

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1069]
Not sure why, but it happens consistently after quitting to desktop, and restarting the game.

![capture3](https://user-images.githubusercontent.com/26996014/42662038-ef363eec-85e4-11e8-925b-09c86b5d6776.JPG)

**My List:**
{"name":"nu cap quickdraw (stress)","faction":"imperial","points":100,"version":"0.3.0","pilots":[{"name":"nusquadronpilot","points":27,"ship":"alphaclassstarwing","upgrades":{"title":["xg1assaultconfiguration"],"mod":["advslam"],"cannon":["manglercannon","flechettecannon"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}},{"name":"quickdraw","points":39,"ship":"tiesffighter","upgrades":{"title":["specialopstraining"],"mod":["lightweightframe"],"system":["firecontrolsystem"],"tech":["patternanalyzer"],"ept":["expertise"]},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}},{"name":"captainferoph","points":34,"ship":"tiereaper","upgrades":{"title":["advailerons"],"mod":["lightweightframe"],"crew":["rebelcaptive","directorkrennic"],"ept":["adaptability"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}}],"description":"Nu Squadron Pilot + Xg-1 Assault Configuration + Advanced SLAM + Mangler Cannon + Flechette Cannon
\"QuickDraw\" + Special Ops Training + Lightweight Frame + Fire-Control System + Pattern Analyzer + Expertise
Captain Feroph + Advanced Ailerons + Lightweight Frame + Rebel Captive + Director Krennic + Adaptability (+1)"}

**AI List:**
{"name":"frank's Palp list","faction":"imperial","points":100,"version":"0.3.0","pilots":[{"name":"majorvermeil","points":34,"ship":"tiereaper","upgrades":{"title":["advailerons"],"crew":["emperorpalpatine"],"ept":["adaptability"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}},{"name":"quickdraw","points":35,"ship":"tiesffighter","upgrades":{"title":["specialopstraining"],"mod":["lightweightframe"],"system":["firecontrolsystem"],"tech":["patternanalyzer"]},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}},{"name":"theinquisitor","points":31,"ship":"tieadvprototype","upgrades":{"title":["tiev1"],"mod":["autothrusters"],"ept":["pushthelimit"]},"vendor":{"Sandrem.FlyCasual":{"skin":"White"}}}],"description":"Major Vermeil + Advanced Ailerons + Emperor Palpatine + Adaptability (+1)
\"QuickDraw\" + Special Ops Training + Lightweight Frame + Fire-Control System + Pattern Analyzer
The Inquisitor + TIE/v1 + Autothrusters + Push The Limit"}

**Comment by Sandrem** [comment]
Was fixed
