### ISSUE TITLE
0.5.2 Mobile Crash On Barrel Roll

### ISSUE THREAD

**Issue by Jartis9** [Sandrem/FlyCasual#1071]
Every time I try to execute a barrel roll on mobile, red text floods the console and the app closes out. The text is too small to read on my phone, and I can't take a screenshot because it lags the whole system. Have had it happen with Vader, Luke, and a basic TIE. Direction didn't seem to matter, and neither did whether it was successful or not (would have landed on an asteroid, etc), and I couldn't reproduce the error on Windows. Sorry I couldn't provide the error message, I tried to be as detailed as I could.

**Comment by RiffGit** [comment]
![screenshot_20180805-152421](https://user-images.githubusercontent.com/36906206/43686832-c47b3616-98c3-11e8-920c-8ef3069e9691.png)
Android version 0.5.3 HF1

**Comment by Sandrem** [comment]
Closed due to mobile & network mode rework
