### ISSUE TITLE
Request for LAN connections NOT connected to internet.

### ISSUE THREAD

**Issue by ScottKarch** [Sandrem/FlyCasual#1077]
I'm taking my boys on a road trip and they were hoping to play  head to head over a wifi connection in the car.  I have a tiny airport express and they can both join, but trying to create or look for games fails because it can't find the hosting server/service.

I'm sure this is an edge case.... but I'd like to put in the request.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
