### ISSUE TITLE
Second Edition Concordia Faceoff Does Not Change Focus result

### ISSUE THREAD

**Issue by jtg15** [Sandrem/FlyCasual#1081]
When using the Concordia Faceoff ship ability, it does not change a focus result (die roll was 2 evades + focus).

**Comment by Sandrem** [comment]
Second Edition?

**Comment by jtg15** [comment]
Yes, second edition.

**Comment by rune-b** [comment]
I am not able to reproduce this.  Was able to change a focus to a hit with Concordia Faceoff in SE

**Comment by Sandrem** [comment]
Still cannot reproduce, no any new reports of the same bug.
