### ISSUE TITLE
Sometimes Turn gets stuck on AI Vader (Second Edition)

### ISSUE THREAD

**Issue by jtg15** [Sandrem/FlyCasual#1082]
When playing against the Vader + 4 Crack Swarm sometimes the game gets stuck on AI Vader's turn, doesn't seem to be a way to get the game to move forward so it requires a restart. Not sure the conditions that trigger this.

**Comment by jtg15** [comment]
Ok will do.

**Comment by notmattlythgoe** [comment]
I've run into this before and it seems to have to  do with Vader choosing a second target for Cluster Missiles.

**Comment by Sandrem** [comment]
Will be fixed in 0.6.1

Please, if you will encounter this bug in just released 0.6.0 - locate replay-file and send it to me.

**Comment by Sandrem** [comment]
Will be fixed in 0.6.2 in few days

**Comment by TNG-Wing** [comment]
This happens in 0.6.1 with Boba Fett too. Cluster Missiles stuck on trying to select a second target.

**Comment by Sandrem** [comment]
Cluster Missiles were fixed
