### ISSUE TITLE
(2E) TIE Interceptor doesn't have maneuver 3.F.R

### ISSUE THREAD

**Issue by Galaxy613** [Sandrem/FlyCasual#1109]
I just moved my last X Wing and it was the Saber Sqd. Ace turn to move.

![image](https://user-images.githubusercontent.com/411932/43493550-8a74f21a-94fc-11e8-995d-6becaf38b123.png)

**Comment by rune-b** [comment]
This is because the HotAC maneuver table for the Interceptor has a speed 3 K-turn, while the SE interceptor does not. All HotAC tables need to be updated for lost and gained maneuvers in SE

**Comment by rune-b** [comment]
This is most critical for ships that have lost a maneuver in SE:

- A-Wing
- Auzituck
- G-1A
- Jumpmaster
- Khiraxz
- Quadjumper
- Scurrg
- TIE Int
- TIE Striker
- VCX-100
- YT-1300

**Comment by Sandrem** [comment]
Fixed
