### ISSUE TITLE
0.5.3: Unable to place ships lower than initiative 3 when facing a random AI squad and having that squad be the Maarek squad

### ISSUE THREAD

**Issue by esteebestee7** [Sandrem/FlyCasual#1110]
When playing as a squad that would place ships before initiative 3 (or at initiative 3 if I have initiative), I am unable to place ships when facing the Maarek squad after selecting a random AI opponent.  This does not occur if I am playing a squad with a minimum initiative of 4.  The opponent will start placing in this case and my ships can be placed as normal at their initiative values.

This occurs regardless which squad or upgrades I'm using (as long as at least one ship in the squad needs to be placed before the opponent's first ship). The bases still flash like they should, but clicking them to place them gives no response.  This only occurs when facing the Maarek squad and no other squad.  This also occurs regardless if I click "Random" for obstacle placement or if I place them myself.

**Comment by rune-b** [comment]
I get the same problem. Might be related to Krennic

**Comment by Sandrem** [comment]
Fixed
