### ISSUE TITLE
Support for initiative 0 activations

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1120]
Currently SE Corran Horn is implemented as activating at the end of the combat phase, but actually he should be activating at initiative 0. This does not matter as long as he is the only one activating at initiative 0, but this might not always be the case. If Torkil Mux is in play you could get two ships attacking at initative 0, and then the player should be able to choose which one goes first, not the order of the triggers.

Also there might be other abilities in the future that will trigger extra activations at certain initiatives

**Comment by pakelly** [comment]
Note, as of the most recent release build, it looks like Torkil Mux has been added, but is never prompted to use his power. Presumably, this ticket is a prerequisite for that.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
