### ISSUE TITLE
0.6.0 android crash on barrel roll, any ship

### ISSUE THREAD

**Issue by RiffGit** [Sandrem/FlyCasual#1125]
![screenshot_20180805-152421](https://user-images.githubusercontent.com/36906206/43688284-b57d784e-98dd-11e8-9ba1-194f8622c10e.png)
Has always done this in second edition.

**Comment by RiffGit** [comment]
![screenshot_20180828-230735](https://user-images.githubusercontent.com/36906206/44753830-5eed2f00-ab17-11e8-9693-51966747e544.png)
Still crashing in 6.0.0

**Comment by savagerose** [comment]
I've got a fix for this (and for a first edition barrel roll glitch as well) working, should be able to wrap up a pull request tomorrow. :) Just want to test it a bit more.
