### ISSUE TITLE
Dash moving causes crash

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#1131]
Playing against AI, Dash did 2 bank, as soon as movement completed game froze and console appeared.
This does not happen when Dash is player controlled.
![dash](https://user-images.githubusercontent.com/33504209/43710115-09e7c9fa-99b2-11e8-8dcc-df6d9d7bac98.jpg)

**Comment by Sandrem** [comment]
Still don't have steps to reproduce. Cannot fix without new information.
