### ISSUE TITLE
Selfless ability issues

### ISSUE THREAD

**Issue by vladamex** [Sandrem/FlyCasual#1137]
Scenario: 1-1 combat between an imperial ship (player) and the rebel ship with Selfless ability (AI). Imperial ship hits the rebel ship for 2 damage. 

Two things are wrong: 
- Selfless triggers even if the "Selfless carrier" is the attacked ship (this shouldn't happen)
- When this false trigger happens, it allows the AI to dump 1 damage back to the attacker (!!)

End result is that both ships suffered one damage each (!). 

I don't have the logs, but may be able to repro the issue if needed. Let me know.

**Comment by bitsai** [comment]
Just tested this in the newest release (0.9.2), flying Anakin (Aethersprite) against a Rebel Y-wing w/ Selfless.  Was not able to reproduce the issue, closing.
