### ISSUE TITLE
A-Wing Title Error

### ISSUE THREAD

**Issue by bofusbaylor** [Sandrem/FlyCasual#1143]
![second elite pilot talent a-wing error](https://user-images.githubusercontent.com/42309265/43998327-57239b96-9dc1-11e8-9b5c-bc75902a7e70.JPG)

When using the A-Wing title Test Pilot, I get this error message when entering the catalogue to pick the second Elite Pilot Talent. After this error the game is no longer able to be interacted with.

**Comment by rune-b** [comment]
I don't get this error. Maybe it is related to a specific combination of pilots/upgrades. Do you remember which A-Wing pilot and which talents you used?

![image](https://user-images.githubusercontent.com/11047987/44357853-7a22c380-a4b3-11e8-9b0e-0499f081bf8a.png)

**Comment by Sandrem** [comment]
Still cannot reproduce, no any new reports of the same bug.
