### ISSUE TITLE
0.5.3_HF1 SE - Error during creation of squadron

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#1146]
This occasionally happens when playing a random AI opponent.  I am not trying to build a customized squad opponent, so I think there might be a bug in one of the default opponent squads.  

Right after clicking the "RANDOM" button to generate the opponent's squad:
https://ibb.co/fFGnwU

If I click "RANDOM" again it will create a squad and allow me to play.  I couldn't find a way to get anything useful from the debug console.

Thanks

**Comment by Sandrem** [comment]
Was fixed
