### ISSUE TITLE
0.5.3_HF1 SE - Unable to place ship during Setup phase against one AI squad

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#1147]
Playing against the AI squad of Maarek/Feroph/BlackSquadrons and it is impossible to place my ships.  The next available ship is flashing as if highlighted but I can't do anything with it - it won't move at all.  Debug console doesn't have any red text either.

I can reproduce this with multiple squads that I've built in each faction.

I can't reproduce this with other opponent squads in my limited testing.  So, I can place the Planetary Sentinels against the Boba/Joy/Zealot squad, and no trouble with Wedge/Luke/Dutch, and no trouble with Vader/Swarm.

https://ibb.co/mXAfGU
https://ibb.co/cm0pbU

**Comment by TNG-Wing** [comment]
I have the same problem using Lothal Rebel and some T-65s

**Comment by rune-b** [comment]
Duplicate of #1110

**Comment by Sandrem** [comment]
Fixed
