### ISSUE TITLE
Phantom cloak issue

### ISSUE THREAD

**Issue by JacenSolo** [Sandrem/FlyCasual#1148]
When you try to decloak, if you pick a decloak that does not work (i.e. on a ship or asteroid) you get an error message and cannot choose another location. There is no way to move on and have to restart the game.

The mobile issue has the same problem, but you can only decloak to the right, you cannot choose a different movement option.
![capture issue phantom](https://user-images.githubusercontent.com/42398548/44130766-a98bb580-a014-11e8-9066-4aca9628d73c.PNG)

Thank you, this program is amazing otherwise and has gotten me to spend hundreds on the actual game!

**Comment by Sandrem** [comment]
Fixed

**Comment by JacenSolo** [comment]
Awesome!
