### ISSUE TITLE
Feature Request: Move popups to the right so they don't overlap the action buttons

### ISSUE THREAD

**Issue by notmattlythgoe** [Sandrem/FlyCasual#1165]
When playing and a series of popups shows up they overlap the buttons, meaning you have to wait until they go away to proceed. Would be nice if they were off to the side instead.

**Comment by Sandrem** [comment]
In plans

**Comment by Elavion** [comment]
Even shrinking them slightly would help a lot. Also, adding a bit of transparency would help with them obstructing actual dice results.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
