### ISSUE TITLE
"Change assigned maneuver" doesn't work (Countess Ryad, Slave I etc)

### ISSUE THREAD

**Issue by Mallevolent** [Sandrem/FlyCasual#1175]
After Countess Ryad is activated and you get the choice of transforming your straight maneuver into a k-turn the game stops and no movement is made (doesn't matter if you go for  your original maneuver or the k-turn alternative).

Took a screenshot of the console.

![flycasual2ndryad](https://user-images.githubusercontent.com/42551599/44799695-d9b85780-abb4-11e8-9273-a90b6879de46.png)

**Comment by Mallevolent** [comment]
Tried Countess Ryad in 1st Ed mode. Didn't get that to work there either.
Am I missing a step here?

**Comment by RedRaspberry** [comment]
Same issue

**Comment by Sandrem** [comment]
Fixed, release of update is planned for Today.

**Comment by RedRaspberry** [comment]
Update works great, thank you @Sandrem 
It also fixed many other issues that were annoying
Thanks!
