### ISSUE TITLE
Can't skip if no ship is in range or arc 2nd Ed

### ISSUE THREAD

**Issue by Mallevolent** [Sandrem/FlyCasual#1176]
After chosing a ship to attack with and then get the Out of Range or Out of Arc message pressing the Skip button (to move on to another ship) doesn't work.

![flycasual2ndnotarget](https://user-images.githubusercontent.com/42551599/44801694-0753cf80-abba-11e8-952c-30da57b10b89.png)

**Comment by Sandrem** [comment]
Fixed in dev branch.
Update 0.6.1 will be released soon.
