### ISSUE TITLE
Stops responding at turn 1

### ISSUE THREAD

**Issue by marcne** [Sandrem/FlyCasual#1179]
In a Mac the game stops at round one. It does not frezee as the music continues playing etc.

it happens with different ships/abilities. See the videos in the links
https://www.dropbox.com/s/aa5e09jun8odjyp/IMG_3166.MOV?dl=0
https://www.dropbox.com/s/ft0ogqdqu4ctrsa/IMG_3167.MOV?dl=0

Thanks for such a great game.

Best,

**Comment by Sandrem** [comment]
Thank you.
I just fixed it in dev branch, I will release 0.6.1 with this bugfix soon.
