### ISSUE TITLE
Skip doesn't work in some cases

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1180]
> ST-321
> Corran Horn
> Snap Shot
> R3 Astromech (2nd TL)

**Comment by jychuah** [comment]
Also occurs when attempting to make an attack but there is no valid target. Attack cannot be skipped.

**Comment by Sandrem** [comment]
@jychuah This part of bug I fixed few hours ago

**Comment by jychuah** [comment]
OK I'll test off of origin/development

**Comment by RedRaspberry** [comment]
@Sandrem Any idea how long this fix will take to get into a general release?

**Comment by Sandrem** [comment]
@RedRaspberry I plan to release update tomorrow.

**Comment by Sandrem** [comment]
Fixed.
