### ISSUE TITLE
Whisper's failed decloak barell roll freezes game

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1187]
I'm not sure if this was fixed in the latest version (0.6), but in v 0.5.3hf, if Whisper tries to decloak and all three options are obstructed, it freezed the game. You can't do anything after that. 

I will try on 0.6 but because my list includes 2 Reapers, the advance aileron pre-boost freezes the game from the 1st turn.

Thanks for looking into this!  :)

**Comment by Neodammerung69** [comment]
This happens to me on the APK. Barrel rolls are imposible in android.

**Comment by TNG-Wing** [comment]
This is still an issue in v 0.6.4.1

Whenever Whisper's decloack fails, the entire game hangs. This was with another list (Whisper, Omicron Pilot, Vermier).

Thanks!

**Comment by Sandrem** [comment]
Fixed

**Comment by Lord-Eye** [comment]
Had this issue with three consecutive games today.  Phantom fails a decloak due to an obstacle and the game freezes.  I'll chock it up to a designed feature to force me to fly better, but it'd be nice if I could not have to scrap a game.
