### ISSUE TITLE
2.0 Biggs ability

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#1195]
His ability says "may" so I should have the option of using his ability or not. Biggs ability shouldn't trigger automatically every time the conditions are met.

**Comment by jasoncohn** [comment]
I've been playing against the AI on a PC.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by rune-b** [comment]
Thanks, I tried the same now and got the same bug. This does not happen when playing against another human

**Comment by rune-b** [comment]
The problem is that the decision to use Biggs is given to the wrong player, so the AI gets to choose. I will fix
