### ISSUE TITLE
Having some issue with re-rolls

### ISSUE THREAD

**Issue by jonholio** [Sandrem/FlyCasual#1196]
Specifically with Wedge, push it to the limit, r5-k6, engine upgrade.  Null reference exception.  Restarted a couple of times, similar results

R5-K6's ability is registed
<color=yellow><b>OnTokenIsSpent</b></color>
R5-K6's ability is fired
<color=aqua>Command is generated: SyncDiceResults</color>
<color=aqua>Command is received: SyncDiceResults</color>
<color=aqua><b>Command is executed: SyncDiceResults</b></color>
<color=aqua>Command is generated: ConfirmDiceCheck</color>
<color=aqua>Command is received: ConfirmDiceCheck</color>
<color=aqua><b>Command is executed: ConfirmDiceCheck</b></color>
<color=yellow><b>OnAbilityDirect</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
<color=yellow><b>OnBeforeTokenIsAssigned</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
<color=yellow><b>OnTokenIsAssigned</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
<color=yellow><b>OnBeforeTokenIsAssigned</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
<color=yellow><b>OnTokenIsAssigned</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
<color=yellow><b>OnTargetLockIsAcquired</b></color>
<b>Callback, stack level is 1: OnTokenIsSpent</b>
R5-K6's ability is finished
<color=yellow>OnTokenIsSpent is resolved again</color>
<b>Callback, stack is empty
</b>
<color=aqua>Command is generated: SyncDiceRerollSelected</color>
<color=aqua>Command is received: SyncDiceRerollSelected</color>
<color=aqua><b>Command is executed: SyncDiceRerollSelected</b></color>
<color=red><b>
NullReferenceException

Die.TurnOnDiceOverlay ()
Die.ToggleSelected (Boolean isSelected)
DiceRerollManager.SyncDiceRerollSelected (System.Collections.Generic.List`1 selectedDice)
GameCommands.SyncDiceRerollSelectedCommand.Execute ()
GameCommands.GameCommand.TryExecute ()
GameController.SendCommand (GameCommands.GameCommand command)
GameController.SendCommand (GameCommandTypes commandType, System.Type subPhase, System.String parameters)
Players.GenericPlayer.SyncDiceRerollSelected ()
GameModes.LocalGame.StartDiceRerollExecution ()
DiceRerollManager.ConfirmRerollButtonIsPressed ()
UnityEngine.Events.InvokableCall.Invoke ()
UnityEngine.Events.UnityEvent.Invoke ()
UnityEngine.UI.Button.Press ()
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
UnityEngine.EventSystems.EventSystem:Update()

**Comment by Sandrem** [comment]
Was fixed
