### ISSUE TITLE
Crash when promted for abilty to resolve

### ISSUE THREAD

**Issue by Chaotix** [Sandrem/FlyCasual#1197]
[Flycasual.htm.txt](https://github.com/Sandrem/FlyCasual/files/2341980/Flycasual.htm.txt)
![flycasual](https://user-images.githubusercontent.com/219529/44941346-57fd3100-ad50-11e8-8b0f-3b863a3e56be.png)

**Comment by bitsai** [comment]
Tested in latest release (0.9.2) flying Guri & Palob against an AI Rebel A-wing, triggered both abilities in the same turn multiple times in different order, could not reproduce the crash.
