### ISSUE TITLE
2.0 Bosk gunner freezes game when triggered

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1198]
I have Bosk gunner on Boba Fett's Firespray and it consisently freezes the game whenever Bosk is triggered to do another shot after the first shot misses.

**Comment by Sandrem** [comment]
Fixed

**Comment by TNG-Wing** [comment]
Thank you!

**Comment by TNG-Wing** [comment]
Do these fixes appear in the next version, or should we re-download and install 0.6.1 again? 

Thanks again, this is an amazing simulator!

**Comment by Neodammerung69** [comment]
Same question 🙋

**Comment by Sandrem** [comment]
In the next version
