### ISSUE TITLE
SE: AI does not attack

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1205]
Against the AI, the TIEs in the screenshot does not attack my X-wings. Have restarted multiple times, happens every time

![image](https://user-images.githubusercontent.com/11047987/45001283-255f6c80-afcc-11e8-9a6c-8819ebf1ba2e.png)

**Comment by rune-b** [comment]
One theory is that the first TIE that activates doesn't have a shot, and when skipping the attack somehow causes the rest of the TIEs to skip

![image](https://user-images.githubusercontent.com/11047987/45001346-91da6b80-afcc-11e8-8192-f7e8a435280e.png)

**Comment by oidafuxmichi** [comment]
![20180905001845_1](https://user-images.githubusercontent.com/42675302/45060855-22cf4680-b0a2-11e8-8df6-9885b3f673a3.jpg)
This happens quite often to me: It's AI's turn and nothing happens. And the skip/next button is gone.
How to open the **console** and skip?
