### ISSUE TITLE
Howlrunner's ability causes a crash in 2nd edition 6.1

### ISSUE THREAD

**Issue by StrongHammerTom** [Sandrem/FlyCasual#1206]
![error with a pilot skill boosted ship that has juke attempting to reroll via howlrunner](https://user-images.githubusercontent.com/41028289/45062744-44c8c900-b0a2-11e8-8d57-2ade9a78c1eb.png)

The ship taking the shoot had Juke equipped, but I don't think that's what causing the crash. If you want though, I can recreate the action that caused the crash with out Juke and see if it's any different?

**Comment by StrongHammerTom** [comment]
I looked more into this and it seems in 6.1 howlrunner's ability causes a crash no matter what.

**Comment by Sandrem** [comment]
Fixed
