### ISSUE TITLE
2.0 Simultaneous Fire Rule

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#1207]
I'm playing against the AI on a PC. When the simultaneous fire rule triggers, the AI ship stays on the board until it can perform an attack even without any hull. You can see the TIE fighter in the screenshot below has no hull yet remains on the board.
![image](https://user-images.githubusercontent.com/39539057/45065332-94010080-b086-11e8-9f06-ac41c79cee14.png)

**Comment by Sandrem** [comment]
Fixed
