### ISSUE TITLE
1.0 Squad Limits to 7 ships

### ISSUE THREAD

**Issue by mdublade** [Sandrem/FlyCasual#1211]
Even when flying just TIEs or Z-95s, squad builder only allows 7 ships even if enough points for an 8th ship.

**Comment by rune-b** [comment]
I have no problem building a first edition squad with 8 Z-95s. Are you playing on PC, Mac or Android?

![image](https://user-images.githubusercontent.com/11047987/45114764-27513900-b14e-11e8-809d-61b27c57c8c2.png)

**Comment by Sandrem** [comment]
"Add ship" button is hidden when cost of squad is 87+ (because there is no ship with cost 13 or less)

**Comment by rune-b** [comment]
Huh? A Z-95 cost less than 13

**Comment by rune-b** [comment]
Was able to reproduce the bug, should have been able to add another Bandit Squadron here:

![image](https://user-images.githubusercontent.com/11047987/45116584-79e12400-b153-11e8-97b9-054f761b4962.png)

**Comment by Sandrem** [comment]
Yes, 12 is the cheapest ship.
Maybe button is disabled for 88, but active for 87?

**Comment by rune-b** [comment]
It seems MinShipCost is set to 14 for FE and 23 for SE. Should be 12 in both cases
