### ISSUE TITLE
No title (no dock) for Sheathepide or Attack Shuttle to dock with Ghost

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1214]
Can't dock the shuttle(s) on the Ghost and get the abilities of Rear Arc, etc., that come with having it docked.

Thanks!!

**Comment by Sandrem** [comment]
Missing content, in plans.
Not a bug, closed.

**Comment by TNG-Wing** [comment]
Not sure if this was addressed in 0.6.2, but I don't see title cards for the Ghost, or the Attack Shuttle. Is the fix in a later version?

Thanks so much for all the great work!

**Comment by Sandrem** [comment]
These cards will be added later.

**Comment by TNG-Wing** [comment]
Thank you!

**Comment by TNG-Wing** [comment]
Just checking: Can we dock an Attack Shuttle on a Ghost to get the bonus arc/attack yet?

Thanks!

**Comment by Sandrem** [comment]
In current build - no.
It is already added in development version (0.9.0), release will be in few days.

**Comment by TNG-Wing** [comment]
Can't wait! Thank you!
