### ISSUE TITLE
Null reference exception when rolling attack dice

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1218]
https://www.reddit.com/r/XWingTMG/comments/9e9oih/getting_this_bug_when_rolling_attack_dice_in_fly/

![image](https://user-images.githubusercontent.com/11047987/45267562-2f231d00-b46f-11e8-938b-6039134583c8.png)

**Comment by rune-b** [comment]
From the reddit post:

I believe it was an unupgraded x-wing that was attacking. We were having issues before with other ships. The error message only happened on the person playing imperials (we were in the same room), but both games froze. We played multiple games with different combinations of ships.

**Comment by Sandrem** [comment]
Fixed
