### ISSUE TITLE
1.0 Countdown costs 44 on pc, and Quickdraw issue

### ISSUE THREAD

**Issue by Neodammerung69** [Sandrem/FlyCasual#1223]
I was building a squadron and Countdown (tie striker) costs 44 (it's actually 20) on first edition x-wing. Also, program crashes every time Quickdraw's ability to shoot when loosing a shield asks me to select a ship to attack. And, playing against computer, imperial AI won't attack my imperial squadron.

**Comment by Sandrem** [comment]
Fixed
