### ISSUE TITLE
Activating out of order and Cluster Missiles fire with focus then lock on second shot.

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#1227]
I've just tried my third Hotseat game of the day on my Mac. Every game has had an issue. At the start of the game, I selected the Rebel list to be First Player. However, at I5, Redline is moving and shooting first. In this game, Redline activated and moved and took a Focus token. Redline's ability did not trigger to give him a lock. During Engagement, Redline shot before Luke. When Redline engaged against Wedge, it did not ask me for the weapon to use and just rolled two dice and hit. It then asked me to select the second Cluster Missile target but would not let me select anything or skip past locking the game.

![screen shot 2018-09-11 at 12 04 33 pm](https://user-images.githubusercontent.com/38188214/45375655-3d7e4f80-b5bb-11e8-8bff-47fae6741112.png)

**Comment by Sandrem** [comment]
Fixed
