### ISSUE TITLE
Coordinate locked game

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#1228]
4th game and 4th issue. Palob coordinated a Focus to Fenn Rau. Fenn got the Focus and Palob got stressed and the game locked. 

![screen shot 2018-09-11 at 12 35 35 pm](https://user-images.githubusercontent.com/38188214/45377178-702a4700-b5bf-11e8-9a79-32bcbdd45fef.png)

**Comment by jychuah** [comment]
Issue appears for all red coordinate actions. I'm having difficulty tracing the specific event sequence, so this may be a core code issue.

**Comment by Sandrem** [comment]
Cannot reproduce in 0.7.2
