### ISSUE TITLE
Starviper Virago title not adding system or illicit slots

### ISSUE THREAD

**Issue by rloos289** [Sandrem/FlyCasual#1229]
Pretty self explanatory, see screenshot
<img width="1440" alt="screen shot 2018-09-11 at 6 56 10 pm" src="https://user-images.githubusercontent.com/19877994/45397358-86062f00-b5f4-11e8-9c71-bbf0ffa92cfd.png">

Also, when attempting to load a squad from a previous version where the Starviper uses the system slot I get the following error in the console after pressing "next player"
<img width="1438" alt="screen shot 2018-09-11 at 6 57 43 pm" src="https://user-images.githubusercontent.com/19877994/45397405-b2ba4680-b5f4-11e8-8b97-63f96b6fce12.png">

Further information, it actually won't add the Virago title at all without getting an error. Looks like its something going wrong in the `IsAllowedForSquadBuilderPostCheck` function on `Assets/Scripts/Model/Upgrades/Titles/Virago.cs`

**Comment by Neodammerung69** [comment]
Second that

**Comment by Sandrem** [comment]
Fixed
