### ISSUE TITLE
Destroyed ships not removed from the game (remain in the game with 0 health)

### ISSUE THREAD

**Issue by vladamex** [Sandrem/FlyCasual#1233]
This is not due to "simultaneous attack rules". Happened to me several times with different ships/lists, using the latest (0.6.1) bits

Replay file and screenshot attached

![killed ships not removed](https://user-images.githubusercontent.com/13235833/45509228-4297f600-b797-11e8-8f79-a4408108d515.png)

[Killed ships not removed replay.zip](https://github.com/Sandrem/FlyCasual/files/2380617/Killed.ships.not.removed.replay.zip)

**Comment by Sandrem** [comment]
Fixed
