### ISSUE TITLE
0.6.2 SE - TIE Phantom is able to gain more than one cloak token

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#1234]
Here's how to reproduce:
Start the round with 1 cloak token, decloak and gain an evade token, choose cloak for my action.  Then if I finish combat with the evade and cloak tokens, TIE Phantom ability allows me to change the evade token into a second cloak token.  Agility is now +4 (6 total).  Next turn I can decloak twice, which means two extra decloaking moves before my dial move.

**Comment by Neodammerung69** [comment]
Sounds insanely good! I'll try it before it gets fixed! XD

**Comment by Sandrem** [comment]
Fixed
