### ISSUE TITLE
"Whisper" failed decloak froze game SE 0.6.2

### ISSUE THREAD

**Issue by Neodammerung69** [Sandrem/FlyCasual#1236]
A failed attempt to decloak, that would've landed on a tie punisher's base, froze the game beyond restart or recovery. Maybe the simulator crashed for another issue with my computer, however, before it went as in the screenshot, I couldn't select another option for decloak, nor any actions or movements or systems of any kind. 
![image](https://user-images.githubusercontent.com/43158903/45566472-5cc7e780-b81c-11e8-9447-2a29dd524897.png)

**Comment by Sandrem** [comment]
Fixed
