### ISSUE TITLE
0.6.2 Console appeared but wont go away

### ISSUE THREAD

**Issue by Arkayus1** [Sandrem/FlyCasual#1237]
it popped some errors up, but i can continue playing, it just wont go away. is there a hotkey for it? i tried tilde but it didnt work
![stuck](https://user-images.githubusercontent.com/17815152/45586880-72f5a680-b8f5-11e8-8806-f3780b492d07.png)

**Comment by Sandrem** [comment]
CTRL + ~
Thank you for screenshot with text, it is needed for me to find and fix this bug.

**Comment by Arkayus1** [comment]
Is there any way to disable the console?

**Comment by Arkayus1** [comment]
Thanks!

**Comment by Sandrem** [comment]
Don't have steps to reproduce, cannot fix without new information.
