### ISSUE TITLE
Advanced Sensors

### ISSUE THREAD

**Issue by Senzorezo** [Sandrem/FlyCasual#1241]
Hi,

the upgrade ADVANCED SENSORS does not allow a second action in the same activation.
So it is impossible to DOUBLE-ACTION when using this upgrades.

Thanks a lots for your work !

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1177
Will be fixed as part of that issue. Closed.
