### ISSUE TITLE
Duchess freezes game when you click to use her ability.

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#1243]
Duchess freezes the game when you click to use her ability. Also, it locked the game when Duchess was destroyed while making a banked advanced aileron maneuver with the loose stabilizer crit.

**Comment by kosteva** [comment]
The "freeze" i get when I used Duchess' ability is that she stays Highlighted, like I *should* be able to select her, and complete her dialed manuever - instead, i get "This ship has already executed his maneuver", and no way to exit this state, short of restarting, or exiting to menu or desktop

**Comment by drail14me** [comment]
Same freeze I got. I’m downloading the update now and will test......if my slow internet will download it.

**Comment by drail14me** [comment]
I'm still getting the same freeze with Duchess when I click to use her ability.

**Comment by Sandrem** [comment]
Fixed
