### ISSUE TITLE
Simultaneous fire freezes game in Hotseat.

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1244]
After a ship (Major Vermeil) is destroyed, and it is about to return simultaneous fire, everything stops. Vermeil is not able to fire back and the game stops.
![fc](https://user-images.githubusercontent.com/26996014/45709221-572e1280-bb38-11e8-8670-103b7b3fc635.JPG)

**Comment by bitsai** [comment]
Just tested this in the newest release (0.9.2) using Obi-wan & Mace against Major Vermeil, with the Jedi moving + shooting first.  Mace dealt the killing blow on Vermeil, who was able to return fire (and use his ability) without issues.  Closing.
