### ISSUE TITLE
Exception when using Lieutenant Karsabi ability

### ISSUE THREAD

**Issue by jonholio** [Sandrem/FlyCasual#1245]
Exception when using this ability.  Steps to reproduce: Set manoeuvre, choose slam, choose manoeuvre, use ability > Yes.
0.6.2

<color=red><b>
NullReferenceException: Object reference not set to an instance of an object

Triggers.FinishTrigger ()
SubPhases.DecisionSubPhase.ConfirmDecision ()
Triggers.DoCallBack ()
Triggers.ResolveTriggers (TriggerTypes triggerType, System.Action callBack)
Ship.GenericShip.CallOnTokenIsAssigned (Tokens.GenericToken token, System.Action callback)
Ship.TokensManager.FinalizeAssignToken (System.Action callback)
Ship.TokensManager+<AssignToken>c__AnonStorey4.<>m__0 ()
Triggers.DoCallBack ()
Triggers.ResolveTriggers (TriggerTypes triggerType, System.Action callBack)
Ship.GenericShip.CallBeforeAssignToken (Tokens.GenericToken token, System.Action callback)
Ship.TokensManager.AssignToken (Tokens.GenericToken token, System.Action callBack, Char letter)
Ship.TokensManager.AssignToken (System.Type tokenType, System.Action callback)
Abilities.LieutenantKarsabiAbility.<UseAbility>m__0 ()
Triggers.DoCallBack ()
Triggers.ResolveTriggers (TriggerTypes triggerType, System.Action callBack)
Ship.TokensManager.RemoveToken (Tokens.GenericToken tokenToRemove, System.Action callback)
Ship.TokensManager.RemoveToken (System.Type type, System.Action callback, Char letter)
Abilities.LieutenantKarsabiAbility.UseAbility (System.Object sender, System.EventArgs e)
SubPhases.Decision.ExecuteDecision (System.Object sender, System.EventArgs e)
SubPhases.DecisionSubPhase.ExecuteDecision (System.String decisionName)
GameCommands.DecisionCommand.Execute ()
GameCommands.GameCommand.TryExecute ()
GameController.SendCommand (GameCommands.GameCommand command)
GameModes.LocalGame.ExecuteCommand (GameCommands.GameCommand command)
SubPhases.DecisionSubPhase.DecisionButtonWasPressed (SubPhases.Decision decision, UnityEngine.GameObject button)
SubPhases.DecisionSubPhase+<Initialize>c__AnonStorey4.<>m__0 (UnityEngine.EventSystems.BaseEventData data)
UnityEngine.Events.InvokableCall`1[UnityEngine.EventSystems.BaseEventData].Invoke (UnityEngine.EventSystems.BaseEventData args0)
UnityEngine.Events.UnityEvent`1[T0].Invoke (.T0 arg0)
UnityEngine.EventSystems.EventTrigger.Execute (EventTriggerType id, UnityEngine.EventSystems.BaseEventData eventData)
UnityEngine.EventSystems.EventTrigger.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData)
UnityEngine.EventSystems.ExecuteEvents.Execute (IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData)
UnityEngine.EventSystems.ExecuteEvents.Execute[IPointerClickHandler] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.EventFunction`1 functor)
UnityEngine.EventSystems.EventSystem:Update()
</b></color>

Possibly related, on encountering this error again I carried on and completed an attack round.  When it was the AIs turn there was no way to progress.  AI could not perform combat steps:

AI is going to perform attack
Syndicate Thug(4) is selected as attacker
<color=aqua>Command is generated: CombatActivation</color>
<color=yellow><b>OnCombatActivation</b></color>
<b>Callback, stack is empty
</b>
Ship doesn't have Target Lock on enemy
Ship selected nearest target Maarek Stele(1)
<color=yellow><b>Ship attacks target
</b></color>
<color=aqua>Command is generated: DeclareAttack</color>
<color=aqua>Command is received: DeclareAttack</color>
<color=aqua><b>Command is executed: DeclareAttack</b></color>
<color=aqua>Command is generated: PressSkip</color>
<color=aqua>Command is received: PressSkip</color>
<color=aqua>PressSkip command is skipped: SubPhases.CombatSubPhase is not ready for commands</color>
<color=aqua>PressSkip command is skipped: SubPhases.CombatSubPhase is not ready for commands</color>
<color=aqua>PressSkip command is skipped: SubPhases.CombatSubPhase is not ready for commands</color>
<color=aqua>Command is generated: SquadsSync</color>
<color=aqua>Command is received: SquadsSync</color>
<color=aqua>SquadsSync command is skipped: subphase is SubPhases.CombatSubPhase instead of </color>
<color=aqua><b>Command is executed: SquadsSync</b></color>
<color=red><b>
NullReferenceException: Object reference not set to an instance of an object

SubPhases.CombatSubPhase.SkipButton ()
UI.SkipButtonEffect ()
GameCommands.PressSkipCommand.Execute ()
Roster.PrepareSquadrons ()
Roster.Initialize ()
GameManagerScript.Start ()
</b></color>

**Comment by Sandrem** [comment]
Fixed
