### ISSUE TITLE
Red Text at squadbuilder 0.6.2

### ISSUE THREAD

**Issue by CaptainJaguarShark** [Sandrem/FlyCasual#1247]
I was letting the cards load in as I had not yet played with 0.6.2. As I was waiting, this popped up in console.

NullReferenceException

ShipPanelSquadBuilderShowTextVersionofcard()
ShipPanelSquadBuilder+<LoadtooltipImage>c__iterator0.MoveNext ()
UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

![image](https://user-images.githubusercontent.com/2208847/45900605-dd9b5c00-bda5-11e8-9b82-20e77d8626a7.png)

I was able to build a squad and play an entire game without issue after receiving this error.

**Comment by Sandrem** [comment]
Fixed
