### ISSUE TITLE
Using vader crew sometimes causes a crash

### ISSUE THREAD

**Issue by notmattlythgoe** [Sandrem/FlyCasual#1250]
![image](https://user-images.githubusercontent.com/7905254/45989817-35a6bc80-c04b-11e8-8dba-b181c6c11c84.png)

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/2413578/LastReplay.zip)

**Comment by drail14me** [comment]
Had this same issue when used against Dutch Vander. I did not get a screen shot.

**Comment by jasoncohn** [comment]
I had the same issue, but it only happened when the enemy didn't have any green tokens and was forced to take a damage. If they had a green token to discard, it was fine.

**Comment by drail14me** [comment]
Just had it happen twice when using Vader crew against Vader pilot. Vader pilot did not have a green token either time. Game showed the shield come off Vader then the game frose. 
![screen shot 2018-10-15 at 10 33 43 am](https://user-images.githubusercontent.com/38188214/46961727-06da9f80-d067-11e8-94f3-86ab7d6c6095.png)

**Comment by Sandrem** [comment]
I cannot reproduce this bug, but I made some fixes in the code.
Problem must be solved.
