### ISSUE TITLE
b-wing and squad leader

### ISSUE THREAD

**Issue by freddias** [Sandrem/FlyCasual#1257]
wen i use coordinate from squad leader the ability goes off and the game freezes

**Comment by Fretless24** [comment]
![screenshot 2018-11-30 09 19 04](https://user-images.githubusercontent.com/44586200/49295963-09614f00-f485-11e8-8435-57e14fcb9871.png)
Here is an example of this that is happening to me with B-Wings and red coordinate (squad Leader)

**Comment by Sandrem** [comment]
Cannot reproduce in 0.7.2
