### ISSUE TITLE
Asteroids gets stuck during placement, same issue with placing after decloak

### ISSUE THREAD

**Issue by Mallevolent** [Sandrem/FlyCasual#1258]
I've never had a problem with this in earlier editions. But now in the place obstacles phase. When I grab an asteroid and move it to the mat it sometimes gets stuck.
I have noticed that if I move the mouse pointer very slowly the asteroid follows along nicely, but if I move faster it gets stuck.
The same thing happens when I decloak a ship. The template and ship base turns up. But doesn't really want to move. I  have noticed that I can get it to change sides if I move the mouse pointer far away on the side where I want it to go.
Really odd.
I have tried several things. Changed maps to see if the one I normally use is giving me a hard time for some odd reason.
Tried changing graphics options.

If needed I will post a video, just tell me how :)

**Comment by pakelly** [comment]
(on Windows) After an asteroid gets "stuck" the user can "pick the asteroid up again" by mousing over it. 

As a work around, it is easier to place asteroids by panning across the map, without moving the mouse.

**Comment by Sandrem** [comment]
Fixed
