### ISSUE TITLE
DeathRain Point Issue

### ISSUE THREAD

**Issue by SilverTurtle23** [Sandrem/FlyCasual#1259]
Hey team, love this game! Just wanted to drop you a head's up about a bug I just discovered.
The Tie Punisher Deathrain card registers at 42 points instead of the 26 shown on the card.

Keep up the good work.
Thanks
-Christian

**Comment by Neodammerung69** [comment]
on First Edition, right? I had the same issue.

**Comment by SilverTurtle23** [comment]
Yep...

**Comment by Sandrem** [comment]
Fixed
