### ISSUE TITLE
Suggestion: Make the dice roll animation optional

### ISSUE THREAD

**Issue by Mallevolent** [Sandrem/FlyCasual#1267]
I don't know if I'm posting this in the right place, but here goes.
Just a suggestion of making the dice roll animation an option. Because sometimes dice manages to hang on to each other so you'll have to wait (not a long wait, but still) a sec for the results to show.
I would prefer just to see the results and move on. But maybe thats just me :)

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
