### ISSUE TITLE
"Moldy Crow" title should extend range of pilot abilities requiring "in arc"

### ISSUE THREAD

**Issue by pakelly** [Sandrem/FlyCasual#1271]
This was just fixed for Jan Ors, per the patch notes, but it should be true for all pilot abilities.

When the Moldy Crow title is equipped to a HWK, all pilot abilities that depend on a ship being "in arc" should work in the forward firing arc granted by the title (e.g. Kyle Katarn, Roark Garnet).

**Comment by Shredss** [comment]
This should also include Scum hwk pilots Torkil + Palob.

**Comment by pakelly** [comment]
In my testing it looked like Palob was working.

Mux, not so much, but his ability seemed to fail in all situations. I believe there is not yet support for initiative 0.

**Comment by Sandrem** [comment]
Now abilities of all HWK-290 pilots check any firing arc (not only mobile arc), also abilities are fixed to work at range 0.
