### ISSUE TITLE
Multiple Bugs in single game

### ISSUE THREAD

**Issue by patrickpatrickxwing** [Sandrem/FlyCasual#1274]
Tried to tractor beam a medium ship but nothing happened when it took two tractor beams.

When stressed and if have adv sensors equipped it will tell me I cannot perform actions, execute my maneuver, then the game skip my action step.  This is after doing a blue maneuver and clearing my stress.

Have not tested other ai ships with bombs, only K wings:  AI does not drop any sort of bombs during the systems phase.

Jake Farrel will let me use his ability after using vectored thrusters when it should not.

Barrage rockets are letting kwings reroll defense dice on defense when inside the bulls eye firing arc.

Director Krennic not able to go onto defender stating it cannot go on a ship with three or more shields.  That requirement is gone in 2.0.  That was part of the 1.0 ruling. 

Internet version only:
rerolling dice causes game to stop working
Director krennic does not work on the ship he assigns prototype to.  No option to spend focus hit or crit.

**Comment by Sandrem** [comment]
1) Tractor Beam and Medium ship - Will check
2) Adv. Sensors - fixed
3) AI doesn't know how to drop bombs, will be change some day, but not in the nearest plans
4) Jake Farrel - Will check
5) Barrage Rockets - Will check
6) Director Krennic - fixed
7) Multiplayer reroll - Will check
8) Multiplayer Prototype condition - Will check

Thank you for reports.
