### ISSUE TITLE
Captain Oicunn's Abilty doesnt work

### ISSUE THREAD

**Issue by Shredss** [Sandrem/FlyCasual#1276]
Captain Oicunn is suppose to be able to attack at range 0, but it doenst work. I think the rule for touching ships is overriding his ability, since it checks for range 0, but then comes up with ship is touching can attack.

**Comment by Sandrem** [comment]
Fixed

**Comment by Wolfshead009** [comment]
I have version 0.7.1 and just had this issue occur today. Target at Range 0 and could not attack.

**Comment by kosikutioner** [comment]
> I have version 0.7.1 and just had this issue occur today. Target at Range 0 and could not attack.

I also had this issue, two or three times in a game today.

**Comment by Sandrem** [comment]
Fixed
