### ISSUE TITLE
Rexler Brath's Ability doesn't work

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#1283]
As written. I expressly tested it with high hull enemy ships, but even while juke is active, his ability won't let me expose cards.

**Comment by ctsdistrict** [comment]
I think it may auto-expose a ?random damage card.

**Comment by Sandrem** [comment]
Yes, it auto-exposes a random damage card.
If ship had damage cards, then you hit it, but no "Faceup damage card" message was shown - inform me. I cannot reproduce any problems.
