### ISSUE TITLE
HLC works once (or twice), then never again.

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#1284]
Just had a game where i equipped Rexler Brath with a HLC amd Proton Rockets.

HLC worked at least once during the game, (not sure if it was twice) but then never again even when in perfect Bullseye at R2-3. I noticed it didn't work anymore after i spend my charge on the PRockets. Maybe it had to do with that, but not sure.

**Comment by Sandrem** [comment]
I cannot reproduce. Please, next time provide screenshot, where conditions are met, but HLC is not availalble.
