### ISSUE TITLE
Second Edition Darth Vader Crew

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#1288]
I put Darth Vader crew on a Tie Reaper. Against the AI, in the game pictured, I jammed Wedge with Vermeil, then used Vader to do a damage. When I tried to select Whisper to attack I got that error message. It only seems to happen after using Vader to do damage. I'm using a PC with Windows 10.
![image](https://user-images.githubusercontent.com/39539057/47262093-a60af700-d4ac-11e8-8ba5-0ae4d1fac346.png)

**Comment by Sandrem** [comment]
I cannot reproduce this bug, but I made some fixes in the code.
Problem must be solved.

**Comment by notmattlythgoe** [comment]
![image](https://user-images.githubusercontent.com/7905254/47467560-ffcd3300-d7c4-11e8-97a3-277284f00172.png)
