### ISSUE TITLE
Advanced sensors prevents action after clearing stress

### ISSUE THREAD

**Issue by Spqanx** [Sandrem/FlyCasual#1294]
when advanced sensors is equipped, it triggers before movement, and recognizes that the ship is stressed. it then prevents a stress check for an action after the ship clears it, and it seems that it considers the failure to perform an action during advanced sensor's trigger as a failed action altogether.  this prevents the player from performing an action after clearing the stress.

**Comment by Sandrem** [comment]
Already fixed. Update wI'll be released soon.
