### ISSUE TITLE
Proton Torpedos + Captain Jonus

### ISSUE THREAD

**Issue by merlinus12** [Sandrem/FlyCasual#1297]
When firing Proton Torpedos in range of Captain Jonus with a Focus and Target Lock, you cannot use Jonus' reroll unless you first spend the Proton Torpedo bonus.  It is always better to be able to use Jonus' reroll before applying that bonus.

**Comment by bitsai** [comment]
Just tested in newest release (0.9.2), you can now apply Captain Jonus' ability before applying the Proton Torpedo bonus.
