### ISSUE TITLE
0.6.5: Advanced Targeting Computer should not be optional

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1302]
The effect should be applied automatically since it is not a choice

![image](https://user-images.githubusercontent.com/11047987/47588707-507c9180-d967-11e8-8dd4-380544db8e30.png)

**Comment by Sandrem** [comment]
Ability was changed according to reported bug https://github.com/Sandrem/FlyCasual/issues/1282
Are there any FAQ/rulings for such cases?

**Comment by rune-b** [comment]
I don't know. Maybe I'm wrong then. I haven't seen any FAQs yet

**Comment by Sandrem** [comment]
I will ask on forums/reddit a bit later.

**Comment by Sandrem** [comment]
I got answer: https://www.reddit.com/r/XWingTMG/comments/c5f3jy/got_a_question_ask_it_here/etx79os/
Everything is correct now.
