### ISSUE TITLE
0.6.5: Dice mod buttons are placed incorrectly

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1303]
See screenshot. Third button has an extra space, and the fourth is outside the box, below the OK button

![image](https://user-images.githubusercontent.com/11047987/47588781-90437900-d967-11e8-94ce-9b229680f28d.png)

**Comment by Sandrem** [comment]
Is this initial position of buttons, or did you use some abilities (like reroll -> select + confirm -> return to this list of buttons)?

**Comment by rune-b** [comment]
Hmm, I don't remember. Will try again

**Comment by rune-b** [comment]
It's the initial position. Looks like the spacing between the buttons is increasing: 0, 1 and 2 spaces between buttons

Reproduced with lone vader vs. HWK

![image](https://user-images.githubusercontent.com/11047987/47589373-3a6fd080-d969-11e8-80db-38f8aa77d713.png)

**Comment by rune-b** [comment]
In the shot above there should also have been a Force button which is off screen I guess

**Comment by rune-b** [comment]
Reproduced with two different resolutions:
1280x720
1920x1080

**Comment by Sandrem** [comment]
![image](https://user-images.githubusercontent.com/6347443/47621921-12b66f00-db07-11e8-8870-098ebaed4240.png)

Fixed
