### ISSUE TITLE
Servomotor S-Foils [closed] causes fatal error

### ISSUE THREAD

**Issue by pakelly** [Sandrem/FlyCasual#1304]
Seen in SE, vs AI,

New in 0.6.5

If a ship equipped with "Servomotor S-Foils [closed]" is in a squad, a fatal error will occur.

"Servomotor S-Foils [open]" seems unaffected.

![image](https://user-images.githubusercontent.com/4307452/47588696-3cfc0700-d924-11e8-91a5-3c9790508ce8.png)

**Comment by pakelly** [comment]
Changing S-Foils from Open to Closed and vice versa within the match seems to work fine.

**Comment by JeffSkyrunner** [comment]
Referring to #1308 I've tried opening wings of both ships while building squad, but it doesn't work.

**Comment by Sandrem** [comment]
Same problem with configuration upgrade of U-Wing.

**Comment by Sandrem** [comment]
Fixed
