### ISSUE TITLE
Echo and an odd AI error

### ISSUE THREAD

**Issue by synthetix808** [Sandrem/FlyCasual#1305]
First off, thank you for adding Echo. A fave of mine. However, I noticed when using the evade token d given by Stygium during defense, it doesn't actually spend it and hangs around til end phase. Allowing you to spend it to recloak, which then shouldn't be available. 

I also hit an odd AI timing thing where it was its turn to fire (Ywing with an Ion turret) and the game locked up on its turn. had to ESC to get out. image of error console; https://imgur.com/a/RhTvDMg

**Comment by Sandrem** [comment]
Fixed
