### ISSUE TITLE
Crashing with a specific sqad

### ISSUE THREAD

**Issue by JeffSkyrunner** [Sandrem/FlyCasual#1308]
The squad in the attached txt crashes while beginning a game vs AI (logs attached).
I've tried it both with PC (Windows 10) and Android Tablet (Samsung S2).

![crash](https://user-images.githubusercontent.com/7967042/47614838-8aa07d00-daa6-11e8-8e51-c667c0b3a61f.png)
[XWS Squad.txt](https://github.com/Sandrem/FlyCasual/files/2522694/XWS.Squad.txt)

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/1304
