### ISSUE TITLE
Squad Leader on A-wing Green Squadron crash

### ISSUE THREAD

**Issue by Fretless24** [Sandrem/FlyCasual#1312]
When selecting the red action Coordinate (from EPT Squad Leader) the program allows me to coordinate just fine. But because the A-wing has Vectored Thrusters the next prompt asks if I want to perform a free boost action. Since I just did a red action (coordinate) the program won't let me perform the boost (which is correct) however I can't continue to the next ships activate stage (ie, there is no "NEXT" icon on the bottom of the screen as normal). It's probably just a black hole kind of thing that just cycles and doesn't let me continue. 

Thanks!

**Comment by Sandrem** [comment]
Fixed
