### ISSUE TITLE
Barrel roll should allow other valid positions

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1316]
When you barrel roll, if the selection you make (front, middle, back) overlaps a ship/obstacle, the action automatically fails.
Ideally, I think it should take you back to select other positions (or fail if all positions fail).
But functionally, it would probably be fine to just auto-select the closest position.

**Comment by freddias** [comment]
if im not mistaken thats not a bug, wen you do a barrelroll you have to declare the positioning, if you fail it for what ever reason you fail the action

**Comment by ctsdistrict** [comment]
You havr to declare left or right, but still get to choose your position after declaring. The only exceptions are Echo and Starvipers, which have to declare a bank direction also but can still choose between the three positions.

**Comment by ctsdistrict** [comment]
![screenshot_20181030-154230_drive](https://user-images.githubusercontent.com/7253995/47755498-b6189880-dc5b-11e8-9283-bfe984b26b46.jpg)

**Comment by Sandrem** [comment]
Fixed
