### ISSUE TITLE
0-0-0 does not work

### ISSUE THREAD

**Issue by krumok** [Sandrem/FlyCasual#1317]
At the start of engagement phase correctly ask to choose a ship at range 0-1, but after choosing the ship, one shield is removed from ship with 0-0-0!!!

I have 0-0-0 on a yv666, 
![screenshot_2018-10-30-22-09-53-921_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/47751338-c0ee2000-dc91-11e8-8bfc-e2032d2303de.png)
![screenshot_2018-10-30-22-10-37-773_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/47751339-c186b680-dc91-11e8-8fb2-c4ba4d36bc96.png)

In the screen attached, the modal at the start of engagement i have tapped on the tie phantom and then the yv666 lose a shield

**Comment by tampermagnitude** [comment]
Is that not Darth Vader triggering? As the YV-666 doesn't have any tokens it's an auto damage.

**Comment by Sandrem** [comment]
You selected Whisper, AI decided to get Stress token.
Then Darth Vader (Crew) is activated (Force token is spend) - as YV-666 doesn't have a green token, it received auto-damage.

Thank you for screenshot.

Not a bug.
