### ISSUE TITLE
Game Crash - Corran Horn

### ISSUE THREAD

**Issue by neadcb** [Sandrem/FlyCasual#1319]
Flew single ship builds: (Self v AI and AI v AI)
Whisper (Juke, Collision Detector, Vader, Hull Upgrade)
vs
Corran Horn (Marksmanship, Advanced Sensors, R4)

Game crashes on Corran's turn.
Has repeated three times. 
Not sure if Corran issue or Advanced Sensor issue.

![image](https://user-images.githubusercontent.com/10949555/47764615-f5fb7200-dc93-11e8-9507-95ef37450b16.png)

**Comment by Sandrem** [comment]
Fixed
