### ISSUE TITLE
Turret attacks from Primary Weapon Arc

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#1320]
![screenshot 2018-10-31 at 13 33 49](https://user-images.githubusercontent.com/31852858/47791482-ba06f200-dd11-11e8-8d3c-c0e8d379f0a3.png)
As you can see, the Y-Wing Ionised a B-Wing that wasn't in the turret, which, as you can see, is pointed towards the bottom of the screen.

**Comment by Sandrem** [comment]
Fixed in 0.7.0
