### ISSUE TITLE
AI Cluster Missiles "Target Not Legal"

### ISSUE THREAD

**Issue by jychuah** [Sandrem/FlyCasual#1321]
It appears that the Cluster Missiles target lock requirement exemption is not being applied to AI. This affects the Vader AI squadron and puts the game in a weird state. Vader fires cluster missiles, then when the second cluster missile shot happens an error message "AI: Target Not Legal" pops up.

**Comment by falconett** [comment]
I'm getting this as well when just trying to use cluster missiles myself. I can't get the second attack off... says "Wrong condition" and then "Target not legal" when it is clearly in arc and within range 1 of the first target.

**Comment by wavemanns** [comment]
I am getting the same issue

**Comment by renatoj** [comment]
I am getting the same issue[2]

**Comment by Sandrem** [comment]
Fixed
