### ISSUE TITLE
No red maneuvers while stressed

### ISSUE THREAD

**Issue by Hinny** [Sandrem/FlyCasual#1329]
In some cases it is tactically sound to dial in a red maneuver even when stressed. For instance, when Cassian Andor pilot is part of your squad, or if you have Hera as crew or Contraband Cybernetics. Not being able to choose red maneuvers is not part of the rule set. A suggestion is to remove the restriction that prevents you to dial in red maneuvers altogether. If you think that it is too harsh you can add a warning pop-up if you choose a red maneuver while stressed, or use red glow or some other visual effects to note that you should be careful.

**Comment by Sandrem** [comment]
No one reads "Controls" tab =)
Hold CTRL when you assign a maneuver to a ship to see window with all maneuvers

I plan to change this UI, too many players have the same issue.

**Comment by Hinny** [comment]
Heh, yeah I missed that section in the controlls...

Btw is there a way to assign red maneuvers to stressed ships on devices with touch screen?
