### ISSUE TITLE
Darth Vader double stressed, doing K Turns and removing both stress after the K Turn

### ISSUE THREAD

**Issue by Archangelspiv** [Sandrem/FlyCasual#1332]
Hey, 
Title says it all. Not sure if it's been covered in another issue.

I love your simulator, i hope you keep up the great work.

**Comment by rune-b** [comment]
Was Vader played by a human or the AI?

**Comment by Archangelspiv** [comment]
Vader was being played by the AI.

**Comment by Sandrem** [comment]
New AI is added, HotAC AI will be removed from the game soon.
Closed.
