### ISSUE TITLE
Improvement: Ability to Save lists

### ISSUE THREAD

**Issue by Archangelspiv** [Sandrem/FlyCasual#1336]
Hi,
If this is already a feature, can someone tell me how to do it? 
I want to get the AI to fight some lists I have made but it is a pain trying to remember them or re input them every time.

I love the App and it has been so helpful so far.

**Comment by Sandrem** [comment]
No one reads "Controls" in main menu...
Click on "My Squadron" or "Squadron of AI" on top of squad builder to open menu.
