### ISSUE TITLE
4K Turn not producing Stress on Y-wing and Tie Advanced X1

### ISSUE THREAD

**Issue by SailorJoeV** [Sandrem/FlyCasual#1343]
In my dinking around, I've noticed that the 4K turn does not always stress the AI ship, specifically the Y-Wing and Tie/ADX1.

**Comment by Sandrem** [comment]
AI uses rules of HotAC AI - only skips an action after red maneuver, no stress is assigned.
Not a bug.

**Comment by SailorJoeV** [comment]
Shouldn’t it have a stress token assigned?  I mean forever 4ks on a Y wing
seems kind of silly.

-Joe

**Comment by Sandrem** [comment]
AI is stupid.
There are two ways to handle this:
A) Left AI as is, and battles will be too easy - no challenge and no fun.
B) Give some advantages to AI by rules - so challenge appears and players have fun.
Way "B" is chosen.

If you want to have challenge and fun, but to keep correct rules for an opponent too - play againth a real opponent.
