### ISSUE TITLE
Error when AI Lando (Scum) shoots

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1348]
Whenever AI Lando shoots at my ships I get this error:

![image](https://user-images.githubusercontent.com/11047987/49757130-e96b3000-fcbb-11e8-9332-66315084c2c3.png)

**Comment by Sandrem** [comment]
No similar bug reports from another users. I cannot reproduce this bug too.
(Maybe was fixed by another changes?)
Closed.

**Comment by rune-b** [comment]
I can't reproduce it either anymore
