### ISSUE TITLE
Jake Farrell's ability

### ISSUE THREAD

**Issue by Mitsein55** [Sandrem/FlyCasual#1350]
Jake's ability does not work - when you select a different friendly ship to perform the focus action, it says "free actions cannot be performed." In addition, a friendly ship should be able to perform a free focus action after Jake does a red boost action. He should be able to pass out two focus tokens by barrel rolling then boosting.

**Comment by rune-b** [comment]
@Sandrem I made some fixes and now it seems to work correctly when giving actions to other ships. But I'm getting some other errors now when he selects himself for the second time. And it is a bit confusing which trigger is which when it triggers multiple times in the same turn

My changes:
https://github.com/rune-b/FlyCasual/commit/4777689bf4f2de64aa733f15573cead9505c27e7

**Comment by Mitsein55** [comment]
Thanks, you rule!

**Comment by drdov** [comment]
per the rules, jake cannot choose himself for the second focus action because he gets a stress token from the red boost, so if he hands out two it has to be barrel-->(self or friend), red boost-->friend

**Comment by Sandrem** [comment]
Fixed: https://github.com/Sandrem/FlyCasual/pull/1503
