### ISSUE TITLE
Immediate Game Crash

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#1359]
![screenshot 2018-12-17 at 19 29 25](https://user-images.githubusercontent.com/31852858/50110474-43c33e00-0232-11e9-8725-9dcab65a7276.png)
![screenshot 2018-12-17 at 19 29 55](https://user-images.githubusercontent.com/31852858/50110475-445bd480-0232-11e9-85e5-5d463f4574c8.png)

Game crashed upon attempting to load random opponent with version 0.7.0 with pictured squad twice.

**Comment by Sandrem** [comment]
Seems that bug is caused by Stealth Divice. Try to avoid it until the next update with bugfixes.

**Comment by Damo1701** [comment]
![screenshot 2018-12-17 at 19 51 42](https://user-images.githubusercontent.com/31852858/50111692-3b203700-0235-11e9-89f7-234af617b18e.png)

Not Stealth Device :( or is now something different, perhaps Zeb?

**Comment by Sandrem** [comment]
Please, show me your list in these cases.
Seems that one of ships has wrong list of maneuvers, and this causes the crash.

**Comment by Damo1701** [comment]
Was exactly the same list as above, just without Stealth Device.

**Comment by Sandrem** [comment]
Thank you.

**Comment by Sandrem** [comment]
Both problems are fixed

**Comment by Damo1701** [comment]
![screenshot 2018-12-18 at 21 16 47](https://user-images.githubusercontent.com/31852858/50183628-8fe1b180-030a-11e9-80f2-7e15d7ff36b4.png)
![screenshot 2018-12-18 at 21 16 57](https://user-images.githubusercontent.com/31852858/50183629-8fe1b180-030a-11e9-94cf-e06642ca1c22.png)
![screenshot 2018-12-18 at 21 17 38](https://user-images.githubusercontent.com/31852858/50183642-953efc00-030a-11e9-9544-71cd087398d0.png)
![screenshot 2018-12-18 at 21 17 52](https://user-images.githubusercontent.com/31852858/50183643-953efc00-030a-11e9-9506-680bbf166681.png)
![screenshot 2018-12-18 at 21 18 06](https://user-images.githubusercontent.com/31852858/50183644-953efc00-030a-11e9-8793-beb9ccfc5298.png)
![screenshot 2018-12-18 at 21 18 24](https://user-images.githubusercontent.com/31852858/50183645-953efc00-030a-11e9-9c3f-7f06096da7e6.png)

Unfortunately, it's still happening on loading with Zeb...  Sorry.

**Comment by Sandrem** [comment]
Because update with this fix is not released yet.
Will be released ~tomorrow. You will see a notification in main menu that new version is available.
