### ISSUE TITLE
7.0 bugs

### ISSUE THREAD

**Issue by patrickpatrickxwing** [Sandrem/FlyCasual#1362]
Noticed bugs during online play:

When the game notices an error the command line will open and doesn't close, even after inputting the close command.

Touch screens cause an issue with the game:  mouse wont work, you can place ships outside the range 1 setup, causes other players screen to error out or lock up.

internet matches crashes a lot and the game does not remain open or let the player who dropped rejoin.

At the end of every turn the Tie SF prompt: arc front or back.  Even if it is for the AI and nothing happens when you choose either option.

When the game crashes you lose any saved squadrons.

Veteran turret gunner gives two options after shooting with a #1 or #2.  Both options let you pick a target out of either arc in the resistance bomber.  

After burners triggers even if you go through a rock.

**Comment by Sandrem** [comment]
(waiting for description)
(text of error in console, screenshots and used squad lists can help too)

**Comment by patrickpatrickxwing** [comment]
> (waiting for description)
> (text of error in console, screenshots and used squad lists can help too)

It posted before I input anything in the notes, lol

**Comment by Sandrem** [comment]
Thank you for this report. I will check them, some of them will be fixed soon.

**Comment by Sandrem** [comment]
What device do you use? And what version of OS?

**Comment by patrickpatrickxwing** [comment]
Windows 10 on desktop and windows 10 on lenovo yoga

**Comment by rune-b** [comment]
> After burners triggers even if you go through a rock.

This is correct behavior as far as I can see. Why should it not trigger?
