### ISSUE TITLE
0.7.0 - cannot place asteroids and ships against AI

### ISSUE THREAD

**Issue by Vindigo19** [Sandrem/FlyCasual#1364]
At the start of the game with AI I cannot place asteroids (only random). Then I cannot place ships. Additionaly camera is not moving when I try to move the view by mouse (it works on keyboard).

**Comment by Sandrem** [comment]
This can be related to new mobile devices camera controls.
What device do you use (PC/model of mobile device)? Does it have a touchscreen? What version of OS is installed?

**Comment by Vindigo19** [comment]
Win 10 Lenovo Yoga 3 14 (2015) Yes it has touchscreen, but I use it as normal PC.

**Comment by ctsdistrict** [comment]
I'm also having similar issues. I can't place rocks or ships on Android. (No keyboard or mouse, touchscreen only)

**Comment by dellis83** [comment]
I have the same issue on a surface pro 2 (using in PC mode not tablet).

**Comment by Sandrem** [comment]
Touch controls are temporary turned of in "0.7.0 Hotfix 1"
