### ISSUE TITLE
Crash before tabletop shown (v0.7.0)

### ISSUE THREAD

**Issue by nunatak-jb** [Sandrem/FlyCasual#1373]
I have tried another squad (with any U-Wings) but this one does not even make it to the (virtual) table.

![image](https://user-images.githubusercontent.com/24399618/50193998-5bbcbf80-030f-11e9-8423-62259e034aa2.png)

Here is the XWS:
{"name":"Autosave","faction":"rebel","points":199,"version":"0.3.0","pilots":[{"name":"herasyndulla","points":82,"ship":"vcx100","upgrades":{"crew":["niennunb"],"ept":["marksmanship"]},"vendor":{"Sandrem.FlyCasual":{"skin":"VCX-100"}}},{"name":"dutchvander","points":54,"ship":"ywing","upgrades":{"torpedo":["protontorpedoes"],"amd":["r3astromech"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Yellow"}}},{"name":"janors","points":63,"ship":"hwk290","upgrades":{"title":["moldycrow"],"mod":["stealthdevice"],"crew":["jynerso"],"ept":["trickshot"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Brown"}}}],"description":"Hera Syndulla (VCX-100 Light Freighter) + Nien Nunb + Marksmanship
\"Dutch\" Vander + Proton Torpedoes + R3 Astromech
Jan Ors + Moldy Crow + Stealth Device + Jyn Erso + Trick Shot"}

**Comment by Sandrem** [comment]
Stealth Device has a bug. Avoid it for now.
Bug is fixed in development branch, update will be released soon.
