### ISSUE TITLE
Quadjumper Spacetug Tractor Array crashing program in 0.7.0

### ISSUE THREAD

**Issue by wavemanns** [Sandrem/FlyCasual#1376]
![quadjumper](https://user-images.githubusercontent.com/6612122/50207841-110a6a00-0346-11e9-8a36-60c5b5f188de.JPG)

**Comment by synthetix808** [comment]
Had the same issue with this. Adding just in case different cause.
<img width="1680" alt="screen shot 2018-12-19 at 1 02 37 am" src="https://user-images.githubusercontent.com/32894716/50210308-a26be300-032a-11e9-953e-8eea3f11b212.png">

**Comment by Sandrem** [comment]
Fixed
