### ISSUE TITLE
Collision Detector and decloaking

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#1377]
![screenshot 2018-12-19 at 09 32 07](https://user-images.githubusercontent.com/31852858/50211790-65770f00-0371-11e9-9799-4f7e99edef34.png)

"Whisper" ability is adding a Focus token not an Evade after performing an attack that hits.

![screenshot 2018-12-19 at 09 33 12](https://user-images.githubusercontent.com/31852858/50211814-7aec3900-0371-11e9-9232-081c1b42bca7.png)

Charges for Collision Detector are not being used when decloaking over asteroids, not even the prompt appears any more, nor is there a damage roll.

**Comment by Sandrem** [comment]
"Whisper" ability is fixed.
