### ISSUE TITLE
Yt1300 scum can equip rebel title

### ISSUE THREAD

**Issue by krumok** [Sandrem/FlyCasual#1378]
Yt1300 scum can equip rebel title, and no scum title available

![screenshot_2018-12-19-22-10-36-869_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/50248537-a277eb80-03db-11e9-8ff3-1bd77a21caf7.png)

**Comment by Sandrem** [comment]
Fixed.
Extra upgrade slots on Scum Falcon are fixed too.
