### ISSUE TITLE
Open S-Foils crashes game

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#1389]
Open S-Foils crashes game. I started a game with S-Foils closed on a T-65. When I clicked "Open", game crashed. I rebooted and started a new game. When I placed my ship I selected "Open" for S-Foils and the game crashed.

![screen shot 2018-12-20 at 5 08 17 pm](https://user-images.githubusercontent.com/38188214/50315925-36989000-047a-11e9-8a72-00cf41dd4249.png)

**Comment by Sandrem** [comment]
Fixed, 0.7.1 will be released in the end of this week.
