### ISSUE TITLE
IG88B cannon ability

### ISSUE THREAD

**Issue by synthetix808** [Sandrem/FlyCasual#1391]
When IG88B (or any of the other IG88s with the 2000 title) has the option to use a cannon for a second shot after a missed first, it seems to be varied on whether or not it defaults to a cannon shot. It will occasionally try to default to primary weapon, which will of course not be a valid shot. The only way to escape out of this scenario is to then skip that IG88s turn. In the image attached, I have Major Vyndor within arc and range(2 or 3) to attack with Tractor Beam (cannon range 1-3), yet it is defaulting to a primary attack.
<img width="1680" alt="screen shot 2018-12-21 at 2 08 53 am" src="https://user-images.githubusercontent.com/32894716/50338835-7b4c1780-04ca-11e9-8557-99f1ee26823e.png">

**Comment by Sandrem** [comment]
Tractor Beam had range 1-2 in the code, fixed.
