### ISSUE TITLE
7.1 dial issues

### ISSUE THREAD

**Issue by xLlokiix** [Sandrem/FlyCasual#1401]
Dials not working in 7.1 apk. When clicking on ship it disappears immediately. Clicking on list, bottom of list dials are half off the screen.

**Comment by Sandrem** [comment]
Dial are hidden when camera's position is changed. Seems that your device change camera's position a bit after you touch a ship. I will think how to improve UI for such cases...

**Comment by Sandrem** [comment]
Was fixed
