### ISSUE TITLE
Ion Bug

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#1402]
Ion Cannon or Ion Turret auto Ionise rather than just after the damage.

Rules state Ion is only issued after the first damage for remaining hits.

**Comment by wavemanns** [comment]
I am finding this is not a consistent bug however. On the very odd occasion they work correctly.

**Comment by drdov** [comment]
I saw it in my games today -- only got one damage through but they got ionized -- it was ion turret on norra shooting thane and ten numb -- both got buzzed with one damage

**Comment by Akrythael** [comment]
Can confirm this. 1 hit/crit should only deal a damage but it applies an ion token regardless. Works correctly for more than 1 hit/crit.

**Comment by Zipline20** [comment]
Also it seems like turrets are benefiting from range bonuses as well.

**Comment by drdov** [comment]
Turrets and cannons do get normal range bonuses/penalties in 2.0

**Comment by Zipline20** [comment]
Ah, my mistake.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sandrem** [comment]
Fixed
