### ISSUE TITLE
There is no innate way to differentiate between two identical upgrades when they trigger at the same time.

### ISSUE THREAD

**Issue by Elavion** [Sandrem/FlyCasual#1404]
For example, in a list with multiple electronic baffles, if there are two ships with the same red tokens on them. While the baffles are numbered in the popup, they don't specify which is which (the order seems to be based on the order of ships in the builder, which gets even more counter-intuitive since the in-game GUI shows them in Initiative order instead).

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
