### ISSUE TITLE
Shara Bey: Pilot ability triggering on other pilots in squad

### ISSUE THREAD

**Issue by Mechian** [Sandrem/FlyCasual#1409]
**Description:** Shara Bey ARC-170 is not properly triggering on her. But when other ships are active.

**Expected behaviour:** While you defend or perform a primary attack, you may spend 1 lock you have on the enemy ship to add 1 focus result to your dice results.

**Actual behaviour:** When other ship from your squad attacks its LOCK action is replaced by SHARA BEY option but still working as LOCK option. This appears even in case when there is no lock assigned to the ship.
SHARA BEY ability is not triggering on herself.  

**Steps to reproduce:** Use the squad from the picture and attack with Jan Ors.
![bug shara bey](https://user-images.githubusercontent.com/38667373/50458268-07928a80-0962-11e9-83a2-981472e33a94.jpg)

**Comment by rune-b** [comment]
Thanks for the detailed bug description. I suspect you have done this before :)

It seems Second Editin Shara is still using the First Edition ability

**Comment by Mechian** [comment]
Hi Rune-b. :) Now I checked how was her ability working in first edition and it is exactly it! :) 
_Yes, :) I was working in QA team and as Project manager for SW company. :)_ 
_I would like to help with coding but don't know how to start :( .....as beginner_

**Comment by rune-b** [comment]
as beginner to coding in general, or beginner to Unity/C#?

**Comment by Mechian** [comment]
As beginner to coding in general. :(
