### ISSUE TITLE
Duchess dial incorrect

### ISSUE THREAD

**Issue by Furryrodian** [Sandrem/FlyCasual#1410]
Only Duchess of all the striker pilots is missing blue 1 banks and blue 1 forward. It seems like she has them until something triggers in the game and they become white the rest of the game.

**Comment by rune-b** [comment]
After using Duchess' ability to avoid using the ailerons, 1 banks and 1 forward where white the next turn

After answering No to using her ability, I'm unable to continue the game:

![image](https://user-images.githubusercontent.com/11047987/50530002-d351d200-0af9-11e9-87c0-d309891c2437.png)

**Comment by Sandrem** [comment]
Fixed
