### ISSUE TITLE
Player2 ships don't get stress tokens after red maneuvers

### ISSUE THREAD

**Issue by Mechian** [Sandrem/FlyCasual#1411]
### Description
There are no stress tokens on card of enemy ship after it finishes red maneuver. It seems like regression with the latest release. Seems like solved in past many times. 
### Actual behaviour
When Player 2 = AI finishes its red manueuver it seems like it has did red maneuver since no action done by enemy ship but at the same time there is no stress token on ships card
### Expected behaviour
When Player 2 = AI finishes its red maneuver it looses its action and stress token should appear on its card.
### Steps to reproduce
1.  pick a lists from prtscrn
2.  wait for movement of **Fenn Rau**. In my case it moved in first round red4 straight and didnt get STRESS.

![bug - no stress](https://user-images.githubusercontent.com/38667373/50527952-d9d94d00-0aeb-11e9-8a0a-44af991726ae.jpg)

_Thank you for your work. BR, Marek_

**Comment by rune-b** [comment]
This is a feature of the HotAC AI system that Fly Casual uses. AI ships do not get stress from red maneuvers. While against the rules of standard X-Wing, this helps the AI a bit, which is needed as it is very simplistic.

This is mentioned in the info text that is displayed when you start the game, unless you have clicked "Don't show again"

**Comment by Mechian** [comment]
Ahh, I see now. I'm sorry for extra work with the ticket.
