### ISSUE TITLE
Random crashes during engement phase (2.0)

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#1413]
I've had this happen twice in two games. After attack dice are rolled game hangs. First time was a gun runner at range 2, this time was a Z-95 at range one.
Please let me know if more info required.
![shooting](https://user-images.githubusercontent.com/33504209/50544434-1615c600-0c30-11e9-8539-9ef2027ffdde.jpg)

**Comment by jpltanis** [comment]
In internet game, this happens a lot for me, too.  Never able to finish a battle w/o the program hanging or crashing. Love this program though.  The best X-Wing sim out there.

**Comment by smauel76** [comment]
New 0.7.1 seems to happen often.  I just played two games and both froze and failed.  You can type Close into the command line to make the Red system text go away but the game is non-responsive and has to be restarted.

**Comment by DarwinW13** [comment]
This happens every game for me now in version 0.7.5 and 0.7.6 on Mac, about 20 minutes into game. Never had it happen in 0.7.4

**Comment by bitsai** [comment]
Haven't seen these crashes in Engagement in quite some time, closing.
