### ISSUE TITLE
Freeze during AI action phase

### ISSUE THREAD

**Issue by Fretless24** [Sandrem/FlyCasual#1417]
Bug when AI tries to finalize Joy Rekoff's action it seems. Happened twice. 

![screenshot 2019-01-05 09 16 51](https://user-images.githubusercontent.com/44586200/50725402-12b88980-10cb-11e9-87e9-8643a21283c0.png)

**Comment by bitsai** [comment]
I've played against this AI squad *many* times in the last couple of weeks, never saw a crash with Joy Rekkoff's ability, closing.
