### ISSUE TITLE
UI clutter

### ISSUE THREAD

**Issue by McLaine** [Sandrem/FlyCasual#1421]
Any chance of making the UI scale to screen Rez?

Maybe giving us control of UI scale in main settings?

Relocate the game messages so they don't overlap the dice results and ability buttons?

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
Will be done soon.

**Comment by McLaine** [comment]
Cool man.

Keep up the great work!
