### ISSUE TITLE
2.0 Han Solo Rebel Pilot ability

### ISSUE THREAD

**Issue by McLaine** [Sandrem/FlyCasual#1422]
Should force re-roll of all dice that can be re-rolled I believe.

**Comment by McLaine** [comment]
Yup, at the moment, it's behaving like a standard target lock without focus (selects only blanks and eyes)

**Comment by McLaine** [comment]
Actually, I checked. There's a FAQ in the RR that shows Han doesn't ignore the golden rule, (cannot re-roll a dice that has already been re-rolled). His ability only affects re-roll attempts that are resolved after Him, these re-rolls can get around the golden rule by ignoring any re-roll status that was bestowed by Han.

Phew. Sorry, was just trying to be clear.

**Comment by ctsdistrict** [comment]
No surprise that it's not intuitive. "For the purposes of other effects" doesn't mean "for the purpose of this effect"... Sigh...

**Comment by Sandrem** [comment]
Thank you, fixed.
