### ISSUE TITLE
Barrel Roll before movement can cause off-the-board position

### ISSUE THREAD

**Issue by McLaine** [Sandrem/FlyCasual#1423]
If I set my ship up to the limit of the back edge of the board, and then barrel roll centre, before move (SR). The game has me flying off the board.

Also, You only need declare the direction of the barrel roll. You then get to try all 3 positions at the other side, particularly if one doesn't fit. Only if all 3 possible positions don't fit is the action a fail.

**Comment by kosikutioner** [comment]
Had the same happen to me.

**Comment by Sandrem** [comment]
Second part is fixed.

**Comment by McLaine** [comment]
Cool man.

Am eagerly awaiting a new release, and can't wait until internet play is stable. I know how hard that is, so I wish you all the luck.

**Comment by bitsai** [comment]
Just tested this again in the newest release (0.9.2) with Anakin in an Aethersprite with Supernatural Reflexes.  With the recently-introduced new barrel roll system, it is no longer possible to barrel yourself off the board (whether the BR is before movement, after movement, or done with Fine-Tuned Controls).  Fixed!
