### ISSUE TITLE
Can place Asteroids within range 1 of board edge

### ISSUE THREAD

**Issue by TimothyArrh** [Sandrem/FlyCasual#1424]
![asteroids](https://user-images.githubusercontent.com/46433987/50748391-feb88780-1284-11e9-8831-18b61c00c7b5.png)

you seem to be able to place asteroids anywhere during setup (see attahced picture)

**Comment by mikethetike** [comment]
Managed to reproduce. Looks like this is because the OffTheBoard colliders are disabled

**Comment by Mechian** [comment]
Hi, already reported here: #1405
= duplicity

**Comment by Sandrem** [comment]
Fixed
