### ISSUE TITLE
crash on resolving two damage cards at start of engagement

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1425]
Norra had 2 damage cards for start of engagement -- one where she rolls hte die to see if she gets 1 damage, and the other was become ionized.  Got the red code of death then it asked me to pick one but it was dead by then responsiveness wise

**Comment by Sandrem** [comment]
I can reproduce. If ship is destroyed by Console Fire die roll, it is removed from the board but still can attack - and will cause a crash.

**Comment by Sandrem** [comment]
Fixed
