### ISSUE TITLE
Can there be a hard out 'skip' command that's always available to get around stuck games?

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1431]

**Comment by drdov** [comment]
A lot of the bugs seem to be the game getting stuck with no next prompts available to get the game going again -- can there be a forced 'skip' command to help break out of these stuck situations?

**Comment by Sandrem** [comment]
Game is in development. I don't have any full-time testers for this project.
So, quality of the game depends on bug reports from players.
If I will add "continue" button, players will just use this button and almost will not report bugs - I want to avoid this situation. I need to know about bugs, not just skip them.

I will add something similar only when the game will be finished (~version 1.0)

**Comment by drdov** [comment]
What about this?  If you offer a 'force skip button' there is a popup that requires the beta tester to enter why they forced a skip!  this way you get the bugs and more complete games/opportunity to find more bugs?

**Comment by Sandrem** [comment]
I need a way to get a text from that popup window. For example, to have own server that stores such reports. This is not an easy task.
