### ISSUE TITLE
IG-88A pilot skill is not copied to other ship in squad when IG-2000 in place

### ISSUE THREAD

**Issue by Mechian** [Sandrem/FlyCasual#1433]
### Description
Army: Scum 
Player 1
Ships: Aggressor (IG-88A) + Firespray (Boba Fett)
Upgrades: On picture

When Aggressors are combined in squad with other non-aggressor ships, there is way how to copy IG-88 droid pilot ability to another ship (pilot) in squad. It is necessary to use on these ships IG-2000 upgrade and crew upgrade IG-88D.

**Issue is that the ability of IG-88A is not copied to second ship. In this case Boba Fett doesnt have option to transfer one calculate token to another ship. Pilot skill is not activated on Boba. In this case when two ships are able to transfer calculate token, there should be option to select which ship will start with calculate token transfer and then followed on screen selection to which ship.** 

### Expected behaviour
When there are proper upgrades (IG-2000 and IG-88D Crew upgrade) in place, both Boba and IG-88A should be able to use pilot skill of IG-88A: _At the start of the Engagement Phase, you may choose 1 friendly ship with  on its action bar at range 1-3. If you do, transfer 1 of your calculate tokens to it._ 

### Actual behaviour
Only IG-88A is able to use it pilot ability (transfer calculate tokens)
Boba Fett doesn't have the pilot ability of IG-88A even with proper upgrades on both sides. No option of calculate token transfer is shown at the start of engagement phase for Boba. 

### Testing / Use case
Testing with other IG-88 pilots not done. But there might be the same problem. 

![bug - ig88a](https://user-images.githubusercontent.com/38667373/50930923-8b1fa180-1461-11e9-946c-9d5f07788ed4.jpg)

Thank you for your work!
Marek K

**Comment by Sandrem** [comment]
Thank you for detailed report.
Fixed.
