### ISSUE TITLE
bug after first AI attack

### ISSUE THREAD

**Issue by fouga37** [Sandrem/FlyCasual#1441]
<img width="960" alt="1 set" src="https://user-images.githubusercontent.com/46595540/51029117-bc998980-1595-11e9-9f6f-9f449bc20455.png">
<img width="960" alt="2 after first ai attack" src="https://user-images.githubusercontent.com/46595540/51029141-ccb16900-1595-11e9-8b0d-e10306397ebe.png">

**Comment by bitsai** [comment]
Tried to reproduce in latest release (0.9.2), gave AI the same Rebels list as shown in the screenshot.  Played out the entire battle, with Han shooting in range 1 of obstacles multiple times, but wasn't able to reproduce the crash.  Closing.
