### ISSUE TITLE
Blackout Ability Not working with Trickshot

### ISSUE THREAD

**Issue by smauel76** [Sandrem/FlyCasual#1443]
So I had an obstructed shot with Blackout which should cause the defender to roll two less dice, in this case Luke in a T-65.  It allowed Luke to roll both his defense dice.  Also Trickshot did not work which should have let me roll one extra dice, but it only let me roll the standard three for the Silencer.  Kinda sucked as I planned the squad around that ability and had Luke dead to rights.  Should have been a huge round, but it ended up where Luke rolled two natty evades and took no hits.  Good to know that the build can pay off in real play, but would love to see it pay off in the Fly Casual as well.  I attached a screen shot so you could see what I was looking at.
![screenshot](https://user-images.githubusercontent.com/46506358/51065057-76115280-15c8-11e9-935f-0e8b6ddbfb01.jpg)

Thanks for all the hard work, the game is pretty fantastic!

**Comment by smauel76** [comment]
Sorry, said it was Luke, but the screenshot proves it was Wedge.

**Comment by Sandrem** [comment]
As I see from screenshot, attack was not obstructed:
![image](https://user-images.githubusercontent.com/6347443/52091257-7c3d9200-25bc-11e9-815d-a410b7cbb4c9.png)
Also, when attack is obstructed, defender rolls +1 die, but X-Wing rolled 2 dice - so, seems, that I am right.
