### ISSUE TITLE
duchess barrel roll on turn one = no options to continue

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1444]

**Comment by drdov** [comment]
she boosts 1 with aeilerons, then 3 fwd, then barrel roll, then stuck

**Comment by Sandrem** [comment]
Cannot reproduce. Maybe problem is in another upgrade/pilot from that battle.

Please, next time provide screenshot (I want to see rosters and positions of ships).
Also you can attack screenshot with opened console (CTRL + ~)
