### ISSUE TITLE
Moldy Crow keeps more than 2 Focus 

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1449]
The 2.0 title caps at keeping 2 focus tokens at the end of the turn.

**Comment by rune-b** [comment]
I cannot reproduce this. When I tried the SE Moldy Crow now, it correctly discarded down to 2 focus tokens at the end of the turn

**Comment by ctsdistrict** [comment]
I've seen it on an opposing Palob, and I've done it with Kyle. I'll do some more testing.

**Comment by rune-b** [comment]
If you get the bug again, it would be helpful to know which pilot and upgrades you used

**Comment by Sandrem** [comment]
Still cannot reproduce
