### ISSUE TITLE
U-Wing Agility incorrect

### ISSUE THREAD

**Issue by dandudeguy** [Sandrem/FlyCasual#1450]
I see this was marked as fixed, but I just encountered it this morning, so maybe it is not a consistent bug?

**Comment by Sandrem** [comment]
It is fixed in development version, update is not released yet.
Please, wait few days =)

**Comment by dandudeguy** [comment]
I gotcha. I am very new to GitHub and the programming world. But I made an account just to report bugs. But it is great! It sure helps test out lists for all the times between playing with real people. 

Thanks!
