### ISSUE TITLE
Kyle can't give focus token outside range 3 with Jyn as crew

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#1453]
With Jyn Erso as crew with Kyle Katarn + Moldy Crow, Kyle cannot give a focus token to a friendly ship in arc but outside range 3. This should not affect giving a focus token, it should just prevent Jyn's ability from triggering. Ability works normally without Jyn.

**Comment by ctsdistrict** [comment]
![image](https://user-images.githubusercontent.com/7253995/51435282-6aa9d100-1c31-11e9-91af-4fcb6b22feff.png)

**Comment by NerdimusPrime** [comment]
Huh. Thanks. it sure seemed like Kyle’s ability was working outside range 3. My bad.
