### ISSUE TITLE
stall on target lock 

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#1470]
i shot with han -- asked to use han said no, asked to use tl i picked a die and said ok......................................................... die may or not have been rolled but my dice just sat there with no prompt to continue

**Comment by bitsai** [comment]
Tested this in new release (0.9.2), using Han against an AI Vulture droid fighter.  Skipped Han's ability, used Target Lock to re-roll a single die, and did not encounter the described error.  Closing.
