### ISSUE TITLE
Crash on Selecting Target Lock On A Ship With TL Already On

### ISSUE THREAD

**Issue by Tomcattwo** [Sandrem/FlyCasual#1471]
Version: 0.7.1 Platform Windows 7/64bit
Flying Y-Wing (Vander) and T-65 (Wedge) vs TIE/Int (Turr Phenir). Used Vander to get a lock, give a lock to Wedge and then attempted a 2nd lock on Turr using R3 AstroMech. Program crashed when 2nd lock requested. Screenshot attached.

![bugrep_190126_win7_071](https://user-images.githubusercontent.com/46911396/51791772-36c13500-2176-11e9-89da-3d9ce74af743.jpg)
Regards,
Tomcattwo

**Comment by Tomcattwo** [comment]
Upon further review, the target lock call was appropriately handled. The crash appears to have happened because of a call for the TIE Interceptor to conduct maneuver 5.F.R. Log shows "Ship TIE Interceptor doesn't have maneuver 5.F.R." then threw a "KeyNotFoundException: The given key was not present in the dictionary."

Here's the rest of the debug:


![bugrep_190126_win7_071_2](https://user-images.githubusercontent.com/46911396/51791886-1db98380-2178-11e9-9fd7-32d6531d956f.jpg)

Regards,
Tomcattwo

**Comment by rune-b** [comment]
Thanks. The TIE Interceptor lost the 5K maneuver in second edition, so the problem might be that the AI is still trying to use that maneuver

**Comment by Tomcattwo** [comment]
Yep, that's the most likely reason. Likely also same reason for bugrep I
put into the FFG forum in your thread. My Interceptor battles all ended in
crashes.

Superb work on this, BTW. Puts my solo AI to shame :)

R/
Tomcattwo

**Comment by Sandrem** [comment]
Thank you, fixed.
