### ISSUE TITLE
Ionized ships able to perform maneuvers

### ISSUE THREAD

**Issue by ibarshai** [Sandrem/FlyCasual#1474]
Just downloaded and ran the Windows version.

E-Wing with Gavin fired ion torpedo at X-Wing with Wedge, landed 2 hits. 1 damage and ionization effect were shown but Wedge performed a 4 k-turn next turn.

Y-Wing with Dutch landed 2 hits with ion turret on Luke in X-Wing. Same thing - 1 damage and ion effect was shown, but Luke did a 3 right turn next round.

My Y-Wing was also ionized by Luke and that all worked correctly.

**Comment by Sandrem** [comment]
Who controlled ionized ship? Human or AI? If AI - what AI, Aggressor or HotAC.
Please, next time attach screenshots.

**Comment by ibarshai** [comment]
The ionized ships that still maneuvered were controlled by the Aggressor AI.
The ionized ships that were controlled by human acted to ionized tokens correctly.

I played another quick game to reproduce the issue and take some screenshots: [https://imgur.com/a/s2mE4In](https://imgur.com/a/s2mE4In)

**Comment by Sandrem** [comment]
Fixed
