### ISSUE TITLE
Target is not legal

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#1476]
![image](https://user-images.githubusercontent.com/47178393/51979261-f838bc80-248c-11e9-9872-3ca1fed5c473.png)

Target is not legal. Don't have a clue why... Y-Wing has been able to attack me just after at initiative 2. AI Aggressor controlling the Y-Wing.

**Comment by Sandrem** [comment]
Not a bug:
![outsidearc](https://user-images.githubusercontent.com/6347443/51996862-46b27f00-24be-11e9-849c-2767ed9e3742.jpg)

I plan to make description of such situation more detailed.
