### ISSUE TITLE
Dash Rendar takes damage from obstacles from Stunned Pilot

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1478]
Also, his ships title hasn't been added yet. Can't say I blame you though because I would have no idea how to code that.

**Comment by Sandrem** [comment]
Just landed on obstacle, no roll for damage was asked, I got a chance to perform action to rotate arc too.
![image](https://user-images.githubusercontent.com/6347443/52095199-dcd3cb80-25ca-11e9-9db1-5425ab95dcfe.png)
Can you reproduce this bug?

**Comment by Zipline20** [comment]
I’ll do my best. I’m in fly casual right now. I’ll take some screenhots.


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sandrem** [comment]
Screenshot where I can see position of ship on obstacle can be useful.

**Comment by Zipline20** [comment]
Sounds good. Also, a ui issue I noticed is the notifications pop up on my screen cover most of the [OK] button so I’m forced to wait for them to go away. Would it be possible to either shrink the notifications, or place them somewhere else? Loving the app btw! I spent all day at work thinking of lists that I wanted to try.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Zipline20** [comment]
Also, I think that dash may have had the stunned pilot critical card. Is there a way you can check if he takes damage with that particular crit? Iirc, even with the crit, he shouldn’t take damage.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by Sandrem** [comment]
Yes, I plan to move notifications in the left-bottom corner.

Thank you for details, problem is really in Stunned Pilot crit:
![image](https://user-images.githubusercontent.com/6347443/52095894-8c11a200-25cd-11e9-8668-28b9664ca4af.png)

**Comment by Zipline20** [comment]
Awesome!!!! Thanks for the fast response! Hope you’re having a great day! :D

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by ctsdistrict** [comment]
https://community.fantasyflightgames.com/topic/277390-x-wing-official-rulings/?do=findComment&comment=3491330

Based on the official ruling, Dash should still take damage from the crit if he hits an obstacle.
"Ignores the effects of obstacles" does not ignore the effect of the crit.

**Comment by Zipline20** [comment]
Sounds good! Sorry about that!

On Thu, Jan 31, 2019, 11:53 PM ctsdistrict <notifications@github.com<mailto:notifications@github.com> wrote:

https://community.fantasyflightgames.com/topic/277390-x-wing-official-rulings/?do=findComment&comment=3491330

Based on the official ruling, Dash should still take damage from the crit if he hits an obstacle.
"Ignores the effects of obstacles" does not ignore the effect of the crit.

**Comment by bitsai** [comment]
From the official ruling linked above, seems current behavior is correct.
