### ISSUE TITLE
Leia Crew

### ISSUE THREAD

**Issue by rashktah** [Sandrem/FlyCasual#1480]
Hi!

When I want to use Leia crew in the real game, I can rotate my dials any way I want. In Fly Casual, when a ship is stressed, only those maneuvers are displayed that the ship can execute at this time, which is before I can activate Leia. So stressed ships cannot choose red maneuvers in Fly Casual.

This way Leia is way nerfed in Fly Casual, because I can't dial in K-Turns when my ships are stressed, even if those K-turns would be white when I can activate her at the start of the Activation phase.

Please change... ;-)

Thanks and keep up the great work!

(It would also be awesome if you could add Rebel C3PO crew to Fly Casual, thanks!)

**Comment by Sandrem** [comment]
Hi.
No one reads "Controls" in main menu. =)
You can assign red maneuvers to a stressed ship, if you hold CTRL button when click on it.
But I plan to change this UI, because this is impossible on youch-screen-only devices.
