### ISSUE TITLE
New AI appears to ignore ion tokens.

### ISSUE THREAD

**Issue by ferildurza** [Sandrem/FlyCasual#1482]
Playing against the Luke, Wedge, Gold Squadron AI, on a critical hit the Luke was applied the Disabled Power Regulator critical. Instead of taking a 1 forward maneuver as expected when ionized he ignored the ion token and made a 4 forward. Thinking it might have been a hiccup I went another turn and when he engaged he received a second ion token and then performed a talon roll.

**Comment by Sandrem** [comment]
Fixed
