### ISSUE TITLE
Program crashed: Fatal error in gc, too much in the heap

### ISSUE THREAD

**Issue by Tomcattwo** [Sandrem/FlyCasual#1486]
7.0.2 on Win 7. Could not get a screen shot - Program crashed: Fatal error in gc, too much in the heap,
This was late during a fight between 4 Y wings equipped with ion turrets and veteran turret gunners vs a Vader/Howl/Iden + 2 Academy Pilots swarm, and occurred as I was attempting an ion cannon shot at range 1 vs Iden.
R/
Tomcattwo

**Comment by Sandrem** [comment]
Whan is amount of RAM on your device?
Was this the first battle after you launched the game, or you played few battles in a row?
How often do you encounter this problem?

**Comment by Tomcattwo** [comment]
Whan is amount of RAM on your device?  16 GB


Was this the first battle after you launched the game, or you played few
battles in a row? 1st battle IIRC

How often do you encounter this problem? This was the first and only time,
though I haven't played much on that computer since the crash.

Thanks for your dedicated and superb work.
R/
Tomcattwo

**Comment by Sandrem** [comment]
No similar bugs from another users and I still cannot reproduce by myself.
Closed.
