### ISSUE TITLE
Cluster Missiles not allowing a second shot on ship that fulfills conditions

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1487]
![image](https://user-images.githubusercontent.com/27784255/52159265-fd4d6580-265e-11e9-8022-48bf04d4ef38.png)

When I select the ship that fulfills the condition, it loops back to the choice of selecting a target to perform second cluster missile shot with. Also, Jake Farrell cannot give a focus to anyone other than himself without failing the action, and opening the console window.

Keep up the great work! Let me know if there is anything I can do to help.

**Comment by Sandrem** [comment]
Fixed
