### ISSUE TITLE
Rebel Han Solo pilot (and Lando crew)

### ISSUE THREAD

**Issue by rashktah** [Sandrem/FlyCasual#1488]
I belive the Rebel Han Pilot should be able to re-roll Lando crew dice when at range for his pilot ability to be active. As far as I know this is not possible in Fly Casual.

Furthermore, Rebel Han Solo pilot allows for selective re-rolls on his dice in Fly Casual, while his rule on the card says to re-roll ALL dice if the ability is active and activated.

Thanks and keep up the great work!!!

**Comment by Mitsein5** [comment]
This is true for any die roll that Han makes while in range 1 of an asteroid - R2-D2 crew, various critical hits that require you to roll, and flying over debris, for example.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
