### ISSUE TITLE
Target not legal

### ISSUE THREAD

**Issue by ferildurza** [Sandrem/FlyCasual#1489]
![target not legal](https://user-images.githubusercontent.com/47256865/52164995-ff8fde00-26b7-11e9-9e75-b2fa85d9c3ea.jpg)

I am not sure as to why, when Jan Ors is attacking that Tie Fighter, it gives a target not legal. The Tie is for sure in arc and Jan has no modifiers as far as I can tell as to why she would be unable to attack that ship. The VCX-100 is bumping the targeted tie and Wedge is bumping the neighboring tie.

Thanks!!!

**Comment by rune-b** [comment]
Here's a similar situation. Slinker is not allowed to shoot at Boba Fett:

![image](https://user-images.githubusercontent.com/11047987/52168532-b5e0db00-272b-11e9-9cbf-b3bbe0754428.png)

**Comment by rune-b** [comment]
Probably related to #1484

**Comment by rune-b** [comment]
Another Target not legal example:

![screenshot_20190207-164359](https://user-images.githubusercontent.com/11047987/52423383-463a6980-2af8-11e9-9321-e3785463b8f1.png)

**Comment by Sandrem** [comment]
Hm... About last screenshot: maybe, line of shot is obstructed by already destrroyed ship. I will check.

**Comment by rune-b** [comment]
Quite possible. Soontir was destroyed by luke just before. I think he was overlapping that asteroid, just in front of the alpha

**Comment by rune-b** [comment]
Replay
[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/2841633/LastReplay.replay.zip)

**Comment by Sandrem** [comment]
Fixed
