### ISSUE TITLE
Leia card not complete

### ISSUE THREAD

**Issue by Spqanx** [Sandrem/FlyCasual#1490]
Using leia crew does not allow the user to perform/choose red manuvers while stressed as "using" leia does not occur until the begining of activation, and red manuvers are prevented when stressed in current edition. A stressed red manuver should become a white forward 2. This would allow leia to activate to it's full use.

**Comment by Zipline20** [comment]
Maybe it would be better for leia to trigger at the beginning of choosing manuevers? I ran into this issue as well.

**Comment by ctsdistrict** [comment]
On PC, there is a key combination that will show the "illegal" maneuvers.

**Comment by rashktah** [comment]
Yeah, you can hold CTRL while klicking on the stressed ship to display ALL available movement options, including red maneuvers.

**Comment by Sandrem** [comment]
UI is changed
