### ISSUE TITLE
Console Window Displaying mid game

### ISSUE THREAD

**Issue by pakirby1** [Sandrem/FlyCasual#1492]
<img width="1220" alt="screen shot 2019-02-03 at 4 25 54 am" src="https://user-images.githubusercontent.com/5995377/52176758-fb24fd00-276b-11e9-8ffb-e440bfd8c001.png">

On mac version latest as of 2019-02-03.  Not sure how or why console displayed but I had to look at the fine print

**Comment by Sandrem** [comment]
I need to know what squads were used. Seems that bug is related to some free action of some card.
