### ISSUE TITLE
Resistance Chewbacca's ability not triggering on himself

### ISSUE THREAD

**Issue by darkflop** [Sandrem/FlyCasual#1495]
When Resistance Chewbacca is destroyed, he should get a free action followed by a bonus attack (as per the Rules Ref: "_If an effect triggers after a ship is destroyed, the effect resolves immediately before the ship is removed._" and "_A ship is friendly to itself and can affect itself with any of its abilities that affect friendly ships, unless those abilities explicitly refer to “other” friendly ships._"). That is currently not happening.

Console screenshot attached.

![screen shot 2019-02-03 at 16 56 20](https://user-images.githubusercontent.com/9279493/52179152-f0ec1880-27d6-11e9-816d-c2fca3460ef4.png)

**Comment by Sandrem** [comment]
Fixed
