### ISSUE TITLE
Bullseye-arc not calculated correctly for T-70

### ISSUE THREAD

**Issue by cm5089** [Sandrem/FlyCasual#1498]
![bullseye-arc-bug](https://user-images.githubusercontent.com/560275/52183281-3f60dd80-27fe-11e9-9b78-37aee2fc4538.png)

The bullseye arc for the T-70 (Nien Nunb) in the attached image has not been calculated correctly - it should be rolling 3 dice for having S-Foils closed but having the defender in the bullseye arc.

**Comment by cm5089** [comment]
After running this list a couple more times I found that range 1 calculated correctly (4 dice).  I only remember this happening against the U-Wing, although I cannot be certain of this.

**Comment by Sandrem** [comment]
Fixed
