### ISSUE TITLE
Boba shot ship that bumped him

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1499]
0.7.2 android

I bumped Boba with an interceptor, and still he was able to shoot it from his rear arc

I have a replay, but can't figure out how to upload here when on my phone...

**Comment by rune-b** [comment]
Replay:

[boba_range_0_shot.replay.zip](https://github.com/Sandrem/FlyCasual/files/2833554/boba_range_0_shot.replay.zip)

**Comment by bitsai** [comment]
Tested by slamming Soontir Fel into the back of Boba in a Hotseat game, Boba couldn't shoot Soontir from his rear arc, closing for now.
