### ISSUE TITLE
"Punishing One" crashes application on start

### ISSUE THREAD

**Issue by Chaotix** [Sandrem/FlyCasual#1500]
This specific list will crash the game after picking a random AI opponent:

https://imgur.com/a/y639RZr

{"name":"Lando Dengar Fang","faction":"scum","points":200,"version":"0.3.0","pilots":[{"name":"dengar","points":77,"ship":"jumpmaster5000","upgrades":{"title":["punishingone"],"illicit":["contrabandcybernetics"],"ept":["experthandling"]},"vendor":{"Sandrem.FlyCasual":{"skin":"JumpMaster 5000"}}},{"name":"landocalrissian","points":79,"ship":"customizedyt1300lightfreighter","upgrades":{"crew":["perceptivecopilot"],"gunner":["hansolo"],"illicit":["contrabandcybernetics"],"ept":["lonewolf"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Default"}}},{"name":"zealousrecruit","points":44,"ship":"protectoratestarfighter","upgrades":{},"vendor":{"Sandrem.FlyCasual":{"skin":"Protectorate Starfighter"}}}],"description":"Dengar + Punishing One + Contraband Cybernetics + Expert Handling
Lando Calrissian (Customized YT-1300 Light Freighter) + Perceptive Copilot + Han Solo + Contraband Cybernetics + Lone Wolf
Zealous Recruit"}

**Comment by xcschultzx** [comment]
Seems to crash with any Jumpmaster for me

**Comment by rune-b** [comment]
The problem is with the Punishing One title

**Comment by Sandrem** [comment]
Fixed
