### ISSUE TITLE
Replay doesn't work on Android 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1505]
Crashes after obstacle setup

![screenshot_20190204-092449](https://user-images.githubusercontent.com/11047987/52286738-0db85580-2969-11e9-8c28-8312ed76f053.png)

**Comment by Sandrem** [comment]
New controls on mobile devices doesn't write correct replay information.

**Comment by rune-b** [comment]
Ok. Is it pointless to submit replays from mobile then, or do you still get something out of them?

**Comment by Sandrem** [comment]
Attach them anyway, maybe I will find a way to read them correctly, or I will need only last few entries.

**Comment by Sandrem** [comment]
Fixed
