### ISSUE TITLE
AI stuck on edge of map

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1512]
Captain Feroph ended up close to the edge, and then just kept doing stop maneuvers the following turns. 

This could probably be avoided if the AI would not consider a stop maneuver in the first place when predicting two turns ahead

![screenshot_20190206-092333](https://user-images.githubusercontent.com/11047987/52353784-81249a80-2a2f-11e9-95c0-ded36fc52ba7.png)

**Comment by Sandrem** [comment]
Fixed as proposed.
