### ISSUE TITLE
2.0 Hard stop maneuver considered range 0 of a ship that was destroyed previously

### ISSUE THREAD

**Issue by nickell-andrew** [Sandrem/FlyCasual#1513]
After destroying a ship at range 0 of a U-wing. I dialed in a hard stop. After executing the hard stop with no ships adjacent or close to me, the game showed the "collision" notification and did not allow me to perform an action.

**Comment by Sandrem** [comment]
Thank you.
Collisions were updated only after a ship changed position. Now they are updated when a ship is destroyed too.
Fixed.
