### ISSUE TITLE
Serissu ability doesn't work on herself (Range 0)

### ISSUE THREAD

**Issue by MaxTeranous** [Sandrem/FlyCasual#1521]
Serissu's ability is range 0-1 on the card so should allow herself to use the defensive reroll - but the option doesn't come up when she's shot at. Screenshot example attached - no option for reroll.

![serissu bug](https://user-images.githubusercontent.com/36989470/52473353-78e27180-2b8d-11e9-9a38-83e31f504878.png)

**Comment by Sandrem** [comment]
Fixed
