### ISSUE TITLE
0.7.3 Swarm Manager (Ctrl-A) crashes game

### ISSUE THREAD

**Issue by xcschultzx** [Sandrem/FlyCasual#1524]
Started a few games on PC of new 0.7.3 and Ctrl-A causes a crash screen on the first turn

**Comment by Sandrem** [comment]
Try to write "close" to console and continue the game.

**Comment by xcschultzx** [comment]
Yep, works fine after closing the console

**Comment by Sandrem** [comment]
Fixed
