### ISSUE TITLE
Gunners crash the game

### ISSUE THREAD

**Issue by Alarith** [Sandrem/FlyCasual#1527]
The game currently crashes on me when using either veteran gunner or tail gunner. I assume it's relate to having a second attack in a round. I had this issue with tail gunner on the ARC and Veteran gunner on VCX and Y-Wing.

**Comment by Sandrem** [comment]
Please, attach screenshots. Red text in console and squad lists can be useful for me.

**Comment by Alarith** [comment]
![image](https://user-images.githubusercontent.com/47458728/52507386-aeb94180-2bf1-11e9-8864-c79fd75d2aeb.png)
Veteran Gunner 1

**Comment by Alarith** [comment]
![image](https://user-images.githubusercontent.com/47458728/52507435-cd1f3d00-2bf1-11e9-8d58-a3f98f16ddd2.png)
Veteran Gunner 2

**Comment by Alarith** [comment]
![image](https://user-images.githubusercontent.com/47458728/52507965-5edb7a00-2bf3-11e9-995e-047a88aff969.png)
Tail Gunner 1

**Comment by Alarith** [comment]
![image](https://user-images.githubusercontent.com/47458728/52508011-7b77b200-2bf3-11e9-9fa7-411e718c7cd2.png)
Tail Gunner 2

**Comment by Alarith** [comment]
![image](https://user-images.githubusercontent.com/47458728/52508122-c42f6b00-2bf3-11e9-8f58-ec38d0e74ecb.png)
Tail Gunner 3

**Comment by Alarith** [comment]
Is there a logfile where I can paste you the complete error messages, or are the screenshots good enough?

**Comment by Sandrem** [comment]
Thank you. This is enough - seems that it is easy to reproduce.
I will release hotfix ~tomorrow.

Also you can use "copy" command in console to copy all console log into clipboard (then CTRL+V into txt-file).
Also you can provide "LastReplay.replay" file from "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual_ X-Wing TMG Simulator\Second Edition\Replays\"

**Comment by Alarith** [comment]
Awesome. Thank you for the fast reply. And you did an amazing thing with this tool!

**Comment by Sandrem** [comment]
Only for AI, fixed.
