### ISSUE TITLE
AI not using bombs

### ISSUE THREAD

**Issue by Alarith** [Sandrem/FlyCasual#1528]
I tried various games with bombers but the AI never seems to use bombs.
Even a simple Algorithm like.
If you are in an enemies ship firing arc and its in range 1 or 2, drop a bomb 60 % of the time.
If you are in the enemies bull's eye and its is in range 1 or 2, drop a bomb 80 % of the time.
Can probably be refined if we put more thought into it, but better than dropping no bombs at all :).

I like this project a lot. Did probably 50+ games with it. Playing vs my Son, vs AI and letting AI vs AI show me which list is better :)

**Comment by Sandrem** [comment]
New AI can predict positions of enemy ships and remembers positions of own ships. I plan to use this data to decide to use bombs or not. I will do this later.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
