### ISSUE TITLE
Black One + Pattern Analyzer: can't take ion instead of weapons disabled

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1529]
(Nien with Pattern analyzer)

https://sb-cdn.fantasyflightgames.com/card_images/en/3e9870bff7f61acc12970c254eaeca89.png

**Comment by darkflop** [comment]
I observed the same behaviour last night. Did a SLAM Tallon Roll with Nien and didn't get the prompt.

![screenshot 2019-02-08 at 23 16 49](https://user-images.githubusercontent.com/9279493/52520239-c29f8a80-2c67-11e9-8480-fe4d6819099a.png)
![screenshot 2019-02-08 at 23 17 06](https://user-images.githubusercontent.com/9279493/52520241-c7643e80-2c67-11e9-9006-e707ff9a5cbf.png)
![screenshot 2019-02-08 at 23 17 54](https://user-images.githubusercontent.com/9279493/52520244-ce8b4c80-2c67-11e9-9a3e-f73869b69b15.png)
![screenshot 2019-02-08 at 23 18 16](https://user-images.githubusercontent.com/9279493/52520246-d21ed380-2c67-11e9-97af-a5174b5951eb.png)

**Comment by Sandrem** [comment]
Problem is in Pattern analyzer.

**Comment by Sandrem** [comment]
FE Pattern analyzer requires full rework, it is hidden now
