### ISSUE TITLE
Newest version, unable to fire at tie fighter although it is in arc.

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1533]
![image](https://user-images.githubusercontent.com/27784255/52517565-5aff2600-2bfa-11e9-8294-3d08d12382d3.png)

**Comment by Sandrem** [comment]
Not in arc
![image](https://user-images.githubusercontent.com/6347443/52583448-51630180-2e38-11e9-8f99-0338c30498f6.png)
