### ISSUE TITLE
Jake Farrel crash

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1534]
Game crashes when Jake Farrel tries to give himself a focus action after first doing an evade followed by a red boost action.

Scroll bar in the console doesn't work, so can't see the start of the stack trace

![image](https://user-images.githubusercontent.com/11047987/52522747-b88e8380-2c89-11e9-81f6-06d01c615bb3.png)

**Comment by rune-b** [comment]
A reddit user also reported some bugs with Jake that I wasn't able to reproduce:
https://www.reddit.com/r/XWingTMG/comments/aoh7la/fly_casual_version_073/eg36gdc/

**Comment by Sandrem** [comment]
Fixed.
