### ISSUE TITLE
Wave 3: NullReferenceException when Darth Maul shoots

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1537]
Happens everytime I attack with Darth Maul

![image](https://user-images.githubusercontent.com/11047987/52526043-31ee9c00-2cb3-11e9-8ac8-01ff6ad10ff0.png)

**Stack trace**

NullReferenceException: Object reference not set to an instance of an object
Ship.GenericShip.AnimatePrimaryWeapon () (at Assets/Scripts/View/Ship/GenericShip.cs:456)
SubPhases.DiceRollCombatSubPhase.ShowAttackAnimationAndSound () (at Assets/Scripts/Model/Phases/SubPhases/Temporary/DiceRollCombatSubPhase.cs:62)
SubPhases.DiceRollCombatSubPhase.Initialize () (at Assets/Scripts/Model/Phases/SubPhases/Temporary/DiceRollCombatSubPhase.cs:40)
SubPhases.DiceRollCombatSubPhase.Start () (at Assets/Scripts/Model/Phases/SubPhases/Temporary/DiceRollCombatSubPhase.cs:29)
Phases.StartTemporarySubPhaseOld (System.String name, System.Type subPhaseType, System.Action callBack) (at Assets/Scripts/Model/Phases/Phases.cs:90)
Combat.AttackDiceRoll () (at Assets/Scripts/Model/Combat/Combat.cs:246)
Triggers.DoCallBack () (at Assets/Scripts/Model/Tools/Triggers.cs:314)
Triggers.ResolveTriggers (TriggerTypes triggerType, System.Action callBack) (at Assets/Scripts/Model/Tools/Triggers.cs:243)
Combat.ShotStart () (at Assets/Scripts/Model/Combat/Combat.cs:240)
Triggers.DoCallBack () (at Assets/Scripts/Model/Tools/Triggers.cs:314)
Triggers.ResolveTriggers (TriggerTypes triggerType, System.Action callBack) (at Assets/Scripts/Model/Tools/Triggers.cs:243)
Combat.CallAttackStart () (at Assets/Scripts/Model/Combat/Combat.cs:230)
Combat.StartAttack () (at Assets/Scripts/Model/Combat/Combat.cs:214)
Ship.PrimaryWeaponClass.PayAttackCost (System.Action callBack) (at Assets/Scripts/Model/Content/Core/Ship/ShipWeapon.cs:66)
Combat.PayAttackCost () (at Assets/Scripts/Model/Combat/Combat.cs:204)
BoardTools.ShotInfo.GetResults () (at Assets/Scripts/Model/Board/Info/ShotInfo.cs:225)
BoardTools.ShotInfo.UpdateColisionDetection () (at Assets/Scripts/Model/Board/Info/ShotInfo.cs:200)
ShipMovementScript.UpdateSubscribedFuncs () (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:50)
ShipMovementScript.Update () (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:31)

**Comment by Sandrem** [comment]
Seems that ship's model prefab has wrong animation of shot (GameObect of shot origin is missing/inactive).

**Comment by Sandrem** [comment]
I fixed prefab, please, test.
