### ISSUE TITLE
Rebel Lando can only focus when ionized

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1540]
When ionized, Lando selects himself for his ability, but the only action that shows is focus.
(Lando's ability is not during the perform action step, so all actions should be available.)

**Comment by Alarith** [comment]
This is in relation to the Pilot Lando, not the Crew card, which would be affected by being ionized.

**Comment by ctsdistrict** [comment]
Yes, thanks. I should have said Pilot Lando.

**Comment by Alarith** [comment]
@Sandrem I think in here:
`protected`` override void PerformFreeAction(object sender, System.EventArgs e)
        {
            List<GenericAction> actions = TargetShip.GetAvailableActions();

            TargetShip.AskPerformFreeAction(
                actions,
                delegate {
                    Selection.ThisShip = HostShip;
                    Phases.CurrentSubPhase.Resume();
                    Triggers.FinishTrigger();
                });
        }
```
The List<GenericAction> actions = TargetShip.GetAvailableActions(); only returns Focus, when he is ionized.
