### ISSUE TITLE
Rebel Lando can boost off of a rock and still get his action

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1541]
With engine upgrade. Lando does a blue maneuver and hits a rock, rolls damage. He selects himself and boosts off of the rock (same result if his maneuver hits the rock, but his final position is not on the rock). Then he is given the normal perform action step choices.

If he chooses a different action besides boost, he skips his perform action step as expected.

**Comment by stavrjim** [comment]
Unless this has been erataed in a different way, Lando should actually be able to do that. Overlapping a rock means you skip the perform action step. His ability is not part of that step.

**Comment by ctsdistrict** [comment]
Sorry, to clarify. He uses his ability to boost, then ALSO gets his perform action step, which he should skip because he hit the rock.

**Comment by Sandrem** [comment]
Boost movement collision data overwrites regular movement, so for "should skip action step?" data from boost is used.

**Comment by Sandrem** [comment]
Fixed
