### ISSUE TITLE
ShipPanelSquadBuilder null exception after game starts

### ISSUE THREAD

**Issue by savagerose** [Sandrem/FlyCasual#1544]
On the iOS build of v0.7.2, when I click through the squad builder really quickly for testing purposes I get the attached error after the game starts.

For testing, I was just adding one un-upgraded ship like an Alpha-class to my list, then quickly selecting random for the enemy list.

![image](https://user-images.githubusercontent.com/12475386/52537663-36f52f00-2d37-11e9-8c52-06652cc1a2b8.png)

**Comment by savagerose** [comment]
@jtg15 FYI :)

**Comment by Sandrem** [comment]
I got similar errors in old versions, when image for UI element was downloaded, but UI element was already destroyed (another page in Main Menu / or Battle scene is started)

**Comment by Sandrem** [comment]
Last line of method is changed to
if (this.gameObject != null) this.gameObject.SetActive(true);

**Comment by savagerose** [comment]
Hmm, just ran in to the same issue on v0.7.4 -- I guess there's something else that's (also) null then?
![image from ios](https://user-images.githubusercontent.com/12475386/52830406-a56f1f80-309e-11e9-8a61-b83b357e7ad0.png)

**Comment by Sandrem** [comment]
Fixed. (Maybe)
