### ISSUE TITLE
Error - Ionization and/or jam?

### ISSUE THREAD

**Issue by sthej** [Sandrem/FlyCasual#1545]
I ionized an AI XWing with ion missiles, then jammed him with my Lambda. When it was his turn during activation, it glitched out. Attached are images of the error block.

![image](https://user-images.githubusercontent.com/47505730/52538402-6e5fdd80-2d2f-11e9-861e-f39065980cb4.png)

![image](https://user-images.githubusercontent.com/47505730/52538424-ac5d0180-2d2f-11e9-890b-f0d79713e791.png)
![image](https://user-images.githubusercontent.com/47505730/52538431-cc8cc080-2d2f-11e9-83ee-c0ac9beb3dd0.png)
![image](https://user-images.githubusercontent.com/47505730/52538442-e3331780-2d2f-11e9-83b8-8246a131fc7d.png)

**Comment by Sandrem** [comment]
Fixed by Azrapse
