### ISSUE TITLE
Crash on CombatSubPhase

### ISSUE THREAD

**Issue by Chaotix** [Sandrem/FlyCasual#1546]
Game crashed in the following manner using the following list:

https://imgur.com/a/VfQG8Ui

{"name":"2x b17s, 2x awings","faction":"resistance","points":200,"version":"0.3.0","pilots":[{"name":"cobaltsquadronbomber","points":66,"ship":"mg100starfortress","upgrades":{"bomb":["seismiccharges","protonbombs"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Cobalt"}}},{"name":"cobaltsquadronbomber","points":66,"ship":"mg100starfortress","upgrades":{"bomb":["seismiccharges","protonbombs"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Cobalt"}}},{"name":"greensquadronexpert","points":34,"ship":"rz2awing","upgrades":{},"vendor":{"Sandrem.FlyCasual":{"skin":"Blue"}}},{"name":"greensquadronexpert","points":34,"ship":"rz2awing","upgrades":{},"vendor":{"Sandrem.FlyCasual":{"skin":"Blue"}}}],"description":"Cobalt Squadron Bomber + Seismic Charges + Proton Bombs
Cobalt Squadron Bomber + Seismic Charges + Proton Bombs
Green Squadron Expert
Green Squadron Expert"}

**Comment by bitsai** [comment]
I think this is identical to #1639
