### ISSUE TITLE
Veteran turret gunner 

### ISSUE THREAD

**Issue by SpuriusOne** [Sandrem/FlyCasual#1547]
Veteran turret gunner does not allow follow up shot if turret arc is set in the primary arc. 

Y-wing with dorsal turret and veteran turret gunner makes a primary shot. A prompt comes up for turret attack but then it says that you must select arc that hasn't been used already.

**Comment by xcschultzx** [comment]
Strange.  Works for me.  You have to select dorsal turret for the follow up shot.  I run 4x VTG goons and drea and I've never had a problem.  If you let the AI run that same squad, it'll crash during a VTG shot sometimes but I can't consistently get it to happen.

**Comment by SpuriusOne** [comment]
I tried this again and yes, the y-wing and dorsal turret is working
properly now. The resistance bomber with turret arc set back/front still
gives the error.

**Comment by Sandrem** [comment]
Bug wuth VTG and Resistance Bomber is fixed in dev-branch, hotfix will be released soon.
