### ISSUE TITLE
Jam tokens and Koiogran turns

### ISSUE THREAD

**Issue by ferildurza** [Sandrem/FlyCasual#1552]
I am not sure if this is in line with error #1545 but I figured I would submit anyways but I jammed an enemy and when they executed a Koiogran turn the game crashed when it attempted to assign it a stress token.
![jam token issue](https://user-images.githubusercontent.com/47256865/52609649-33e36700-2e3b-11e9-8feb-5dd1a3b26742.png)

**Comment by Sandrem** [comment]
Yes, the same problem, fixed. Update will be released tomorrow.
