### ISSUE TITLE
Tarkin Crew does not work

### ISSUE THREAD

**Issue by Furryrodian** [Sandrem/FlyCasual#1553]
Tarkin crew is worded "During the System Phase, you may spend 2 (charge). If you do, each friendly ship may acquire a lock on a ship that you have locked."
When the Tarkin ability triggers nothing happens, and no ships gain a lock. This ability should operate independently of a ship have range or a Lock action. I haven't tested whether it only works with ships that have range/lock action, I've only tried it when combined with Col. Jendon and some TIE fighters.

**Comment by ctsdistrict** [comment]
Actually, the range requirement still needs to be met (RRG p12) . See also Dutch's wording which ignores the range requirement.

**Comment by rune-b** [comment]
I've played multiple games with Tarkin today, and not had any problems

ctsdistrict is correct, the range requirement for target locks still needs to be met for each individual friendly ship

**Comment by Furryrodian** [comment]
My bad, seems like I was understanding it wrong then! Sorry for the false
flag.

**Comment by rune-b** [comment]
no worries :)
