### ISSUE TITLE
Bossk ability does not trigger

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#1554]
Tried the build with Bossk and greedo. I consistently got a crit through, but it did not trigger the turn a crit to two hits after hit results have been cancelled.

**Comment by dandudeguy** [comment]
Same here. Version 7.4

**Comment by krumok** [comment]
Yes confirmed, bossk does not trigger. Version 0.7.4

**Comment by Unclebaby** [comment]
Same here v0.7.6.

**Comment by Sandrem** [comment]
Fixed
