### ISSUE TITLE
Greedo

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#1555]
Greedo ability is "While you perform an attack, you may spend 1 charge to change 1 hit result to a crit result.
While you defend, if your charge is active, the attacker may change 1  hit result to a crit result."

At the moment, if you are attacked before you shoot, your opponent scores the crit and it spends the charge. This is incorrect, the opponent cannot spend your charges.

**Comment by jtg15** [comment]
Fixed, thanks.

**Comment by Sandrem** [comment]
Fixed by jtg15
