### ISSUE TITLE
Ailerons Maneuver off the board crash

### ISSUE THREAD

**Issue by belk** [Sandrem/FlyCasual#1556]
Using Advanced Ailerons to fly your ship off the board crashes the game.
Local game vs AI
![ailerons-off-board-crash](https://user-images.githubusercontent.com/549101/52659025-71430580-2eca-11e9-9f6c-846e4990a5b7.PNG)
![ailerons-off-board-crash-2](https://user-images.githubusercontent.com/549101/52659031-73a55f80-2eca-11e9-8891-b306f330cfe7.PNG)

**Comment by Nitroxylin** [comment]
Still present as of 0.9.11, but looks like this:
![pt6](https://user-images.githubusercontent.com/30575527/60819800-e6c8ae80-a1a8-11e9-99dc-3d56ee4570ce.jpg)
![pt7](https://user-images.githubusercontent.com/30575527/60819812-ea5c3580-a1a8-11e9-9411-4f8296239e8a.jpg)
