### ISSUE TITLE
Maneuver skipped by deselecting ship during Ailerons selection

### ISSUE THREAD

**Issue by belk** [Sandrem/FlyCasual#1557]
Selecting a ship for Ailerons, then selecting another ship, will skip the ship's aileron maneuver and it's standard maneuver phase.

Reproduced on Android and Windows.  v0.7.3

**Error: This ship has already executed his maneuver** 
_('his' maneuver? what if it were Guri? nvm, androids don't have feelings. error msg gendering as intended. =P)_
![image](https://user-images.githubusercontent.com/549101/52660903-b9fcbd80-2ece-11e9-88e3-4c756d99cd9b.png)

**Comment by Sandrem** [comment]
Oh, sorry, in my native language a single word is used for both "his" and "its" =)

**Comment by bitsai** [comment]
Yup, this is still possible, as long as you have another ship with the same initiative as the ship w/ Adaptive Ailerons.

**Comment by Sandrem** [comment]
Maneuvers assignment UI is shown in current subphase (so, all interactions with another ships is not blocked).
We need to show this UI with start of own empty subphase. But this change must be tested in a number of abilities that change maneuver of ship.

**Comment by bitsai** [comment]
I think I will punt on this for now, since it sounds like a fair amount of work for a bug that is relatively low impact/easy to avoid.

**Comment by Sandrem** [comment]
Fixed
