### ISSUE TITLE
LT Tavson's ability has no skip option

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#1560]
If LT Tavson takes damage and his ability triggers, there is no option to skip.  This is important because you don't always want to burn his charges.  If you do the subphase finish route in the console, you can't shoot for the rest of the game.

<img width="1680" alt="screen shot 2019-02-12 at 21 34 46" src="https://user-images.githubusercontent.com/47582934/52682698-4da1ae80-2f0e-11e9-9ea1-f7c908d4855f.png">

**Comment by Sandrem** [comment]
Thank you for screenshot

**Comment by bitsai** [comment]
Re-tested in latest development branch, confirmed that Tavson's ability can now be skipped, closing.
