### ISSUE TITLE
Interface: Scrolling Messages

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1563]
Thanks again for this fantastic simulator!

I was wondering if there is any way to move the scrolling messages to a different part of the screen so they are not blocking the control buttons. 

Could the messages be in a moveable window, where we can refer back to them later (a scrolling log of messages)? 

Currently the messages scroll by too quickly to read sometimes, and there are so many blocking the controls that we have to wait for them to fade out before we can continue playing. (And then sometimes you can't remember what they said.)

Thanks so much!

**Comment by Naerytar** [comment]
Agreed. They're in a really bad position right now, constantly overlapping the OK button, which you have to click all the time.

![messages1](https://user-images.githubusercontent.com/47616307/52754376-9afb4a00-2ffa-11e9-9447-579b23303513.jpg)

A quick solution would be to move them to the top of the screen. They would only overlap the player names, which is a far less vital part of the UI.

![messages2](https://user-images.githubusercontent.com/47616307/52754377-9afb4a00-2ffa-11e9-8969-d97e4d5ed107.jpg)

**Comment by TNG-Wing** [comment]
Perhaps a window with a scrolling log (very helpful in case you missed a message) over to the bottom left side. And maybe use a smaller font so the entire window takes up less space.

It would also be nice if the dice window didn't block the middle of the screen. It would be really nice to see the beautiful animations of the ships attacking and defending than just reading about it.

**Comment by bitsai** [comment]
I believe this was implemented as of 0.8.2 (https://github.com/Sandrem/FlyCasual/releases/tag/0.8.2) :)

**Comment by Sandrem** [comment]
Yes, this is done.

**Comment by TNG-Wing** [comment]
Thanks very much!
