### ISSUE TITLE
0.7.4 Game crashes when trying to assign a move to Nym

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#1564]
Not sure why this happens:
0.7.4 Game crashes when trying to assign a move to Nym

![image](https://user-images.githubusercontent.com/26996014/52735904-76ad5800-2f7d-11e9-8900-8a40612bad61.png)

**Comment by rune-b** [comment]
This is a strange one. Do you remember which maneuver it was? Has it happened more than once?

I tried flying around a bit with Nym, but I didn't get this error

**Comment by TNG-Wing** [comment]
I'm sorry, I don't remember. I will try again and make  note

**Comment by Sandrem** [comment]
Still cannot reproduce.
