### ISSUE TITLE
You can look at the opponents dials by clicking on them

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1566]
0.7.4 android

**Comment by rune-b** [comment]
![screenshot_20190214-084021](https://user-images.githubusercontent.com/11047987/52772368-9ce3fe00-3038-11e9-9c7c-c5a2e3551698.png)

**Comment by Zipline20** [comment]
Confirmed issue is present on Windows, instead of clicking, you mouse over, and the maneuvers disappeared after the planning phase was completed.

**Comment by rune-b** [comment]
You can only look at the opponents dials when the AI is active. When you are the active player you can look at your own. So my guess is that the code that allows you to look at your own dials has a bug where it allows the active player instead of the human player
