### ISSUE TITLE
AI Vader runs himself off the board 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1568]
See screenshot. Next turn he leaves the board

![screenshot_20190214-171214](https://user-images.githubusercontent.com/11047987/52800705-a1320a80-307c-11e9-8b6b-757e126544f8.png)

**Comment by rune-b** [comment]
Replay

[vader_offboard.replay.zip](https://github.com/Sandrem/FlyCasual/files/2865875/vader_offboard.replay.zip)

**Comment by Sandrem** [comment]
Still cannot reproduce, no similar reports.
