### ISSUE TITLE
R5 Astromech does not give option to repair Structural Damage Face Up Card

### ISSUE THREAD

**Issue by wavemanns** [Sandrem/FlyCasual#1569]
Title pretty much sums it up.

**Comment by rune-b** [comment]
Hi
Do you remember if you had multiple face up cards at the time, or just the one?

**Comment by wavemanns** [comment]
Has not allowed either for me.

**Comment by rune-b** [comment]
I had no problems repairing structural damage with an R5 now (generic Y-Wing). Do you remember what pilot/upgrades you used?

![image](https://user-images.githubusercontent.com/11047987/53045825-e5634780-348e-11e9-8637-f1a026408383.png)

![image](https://user-images.githubusercontent.com/11047987/53045839-f14f0980-348e-11e9-8b29-8f75bfd56943.png)

![image](https://user-images.githubusercontent.com/11047987/53045870-01ff7f80-348f-11e9-8fe6-5eb832028941.png)

**Comment by wavemanns** [comment]
I will try to recreate tomorrow.

**Comment by Sandrem** [comment]
Still cannot reproduce.
