### ISSUE TITLE
Command/Debug When Offline

### ISSUE THREAD

**Issue by vans11** [Sandrem/FlyCasual#1572]
When no internet connection available, when loading squad pilot cards, upgrades and every element in game spawns the command window. The main error is: InvalidOperarionException: Cannot resolve destination host
UnityEngine.Networking.DownloadHandler.GetCheckedDownloader[DownloadHandlerTexture] (UnityEngine.Networking.UnityWeebRequest www) ...

Win10 x64 in Airplane Mode

It works fine and can load a few ships, but I have to type ‘close’ after every exception thrown, which basically makes the game unplayable offline.

Two solutions, make the command window not massive when an error is thrown (half the screen at the moment). And then allow the player to download all the assets locally??

**Comment by rune-b** [comment]
I get the same when offline on android, 0.7.4

![screenshot_20190215-081959](https://user-images.githubusercontent.com/11047987/52840815-bbaac900-30fa-11e9-8492-67be037417de.png)

**Comment by rune-b** [comment]
Suggested solution:
When offline we should just show a placeholder image for missing cards. Just a simple card shaped rectangle with the card name

**Comment by Sandrem** [comment]
Fixed
