### ISSUE TITLE
Fly Casual 7.3 and 7.4 Constantly Crashing

### ISSUE THREAD

**Issue by Diemilkweed** [Sandrem/FlyCasual#1575]
When I first downloaded, I played about 6-8 games and then crashed out of the program.

Next time it was 2 games.

Then got 1 game a few times.

Now, I can get nothing.  For a while I could load squads, then it would crash when I tried to start the game.

Now it won't even do that.

Getting this on my screen:

Anybody got any clues?

On windows 10, 64 bit.
![crashing casual](https://user-images.githubusercontent.com/27865650/52833216-d012a580-30a9-11e9-91c2-d96248109382.png)

**Comment by Sandrem** [comment]
Thank you for screenshot with red text of error.
If you will encounter another problems, please, provide screenshots and desctiption too.

**Comment by Sandrem** [comment]
Fixed. New version will be released tomorrow.

**Comment by Diemilkweed** [comment]
Had problems with 7.5, said so in a thread on reddit.  Someone suggested
updating video drivers and direct x.  Did the drivers.  Game worked
perfectly.

Thanks for this project.  It's most awesome to get a chance ot test
something out a little to see if the interactions / spacing work like you
think they will.  The animations are cool, the squad builder is much easier
to use then the official ffg one.

Keep up the awesome.
