### ISSUE TITLE
Pattern Analyzer not functioning correctly.

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1577]
I am able to trigger Pattern Analyzers effect even if I do not fully complete a red maneuver as stated on the card. For context, I was using PA on nien.

**Comment by cm5089** [comment]
Do you mean that pattern analyser can still be triggered after a collision with a ship? I have had that as well.
Although I think if the ship lands on an obstacle PA should trigger. Niens ability would also allow a boost or barrel roll-> focus, his ability should remove the stress but he should not then get a main action, even if he rolled off the rock. It is probably worth checking this edge case.

**Comment by cm5089** [comment]
Sorry T-70 has focus -> barrel roll not BR -> focus

**Comment by Zipline20** [comment]
So, I would bump another ship, but PA would still trigger. I haven't tested it with obstacles yet.

**Comment by ctsdistrict** [comment]
"Fully executed" means you did not bump another ship. (pattern analyzer shouldn't work) 
This is different from landing on an asteroid. (pattern analyzer should work)

**Comment by rune-b** [comment]
Confirmed. It triggers even if you bump a ship
