### ISSUE TITLE
Constant DownloadHandler Error on PC behind proxy

### ISSUE THREAD

**Issue by The-DataDoctor** [Sandrem/FlyCasual#1578]
I don't know if the proxy I have my machine behind is the issue but the DownloadHandler error shown in the screenshot keeps coming up after every click.
Having a "stay offline"-parameter for start which really causes the program to not "dial out" would be great!

![flycasual_error](https://user-images.githubusercontent.com/47658775/52846048-e9970a00-3108-11e9-8036-31853a52b82f.png)

**Comment by rune-b** [comment]
Is this a new problem for you, or has it been like this always?

**Comment by rune-b** [comment]
related to #1572

**Comment by The-DataDoctor** [comment]
It was always like that on that proxied machine (never tried with an earlier version)

**Comment by Sandrem** [comment]
Fixed.
Version 0.7.5 will be released tomorrow.
