### ISSUE TITLE
Slave 1 Title Doesn't Allow Changing Turn Maneuvers, Only Banks

### ISSUE THREAD

**Issue by phoenixcon** [Sandrem/FlyCasual#1580]
When selecting a turn maneuver with Boba Fett equipped with Slave 1 title, you don't get the prompt to change to the other direction when activating. If you select a bank maneuver, you do get the prompt. 

<img width="1372" alt="boba fett slave 1 after turning" src="https://user-images.githubusercontent.com/24230466/52872111-4991ae80-3111-11e9-8a7f-d8ba2d9409ef.png">
<img width="797" alt="boba fett slave 1 turn" src="https://user-images.githubusercontent.com/24230466/52872112-4991ae80-3111-11e9-83d8-c47d6ffd475c.png">
<img width="842" alt="slave 1 title" src="https://user-images.githubusercontent.com/24230466/52872113-4991ae80-3111-11e9-9aee-70a080f7d698.png">

**Comment by rune-b** [comment]
Thanks. Seems the ability for the title has just been copy/pasted from first edition Boba Fett (Empire).
