### ISSUE TITLE
Missing gunner slot on yv666

### ISSUE THREAD

**Issue by krumok** [Sandrem/FlyCasual#1581]
Missing gunner slot on yv666

**Comment by Zipline20** [comment]
I'm not sure if this is correct. I just checked, and a Gunner is present on all the pilots for the hounds tooth.

**Comment by rune-b** [comment]
Krumok: Are you sure you had selected Second Edition?

**Comment by krumok** [comment]
Sorry, just updated to last version, was an issue of previous version.
Now it's ok
