### ISSUE TITLE
Phasma does not use Major Stridan's ability

### ISSUE THREAD

**Issue by xcschultzx** [Sandrem/FlyCasual#1584]
Phasma should stress range 0-3 on Major Stridan.  It only stresses at 0-1 as it would on any other ship.

**Comment by Sandrem** [comment]
I had the same issue first. Then I READ the text:

While you coordinate or resolve the effect of one of your upgrades, you may treat FRIENDLY ships at range 2-3 as being at range 0 or range 1.

Not a bug.
