### ISSUE TITLE
How are dice results generated?

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#1590]
I can't be the only one who finds the game almost unplayable at times because of unrealistic dice results. The dice results are usually very predictably lopsided in favor of the AI. Even statistically average results every time would be acceptable. The games tend to get very boring after a while.

**Comment by Sandrem** [comment]
Dice results are generated randomly, in the same way both for human and AI.
I cannot fix player's luck or conspiracy theories, sorry.

**Comment by Sandrem** [comment]
If anyone knows basics of programming, then good luck in attempts to find favor for AI:

https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/View/Board/Dice/Die.cs

public void RandomizeRotation()
    {
              SetInitialRotation(new Vector3(Random.Range(0, 360), Random.Range(0, 360), Random.Range(0, 360)));
    }

public void SetInitialRotation(Vector3 rotationAngles)
    {
        if (Model == null) Model = SpawnDice(Type);
        Model.transform.Find("Dice").transform.eulerAngles = new Vector3(rotationAngles.x, rotationAngles.y, rotationAngles.z);
    }

**Comment by jasoncohn** [comment]
Thanks for answering the question. Maybe next time you can just answer the question without being an asshole.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
