### ISSUE TITLE
AI Darth Vader doesn't use his ability

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1592]
He always just focuses. He should always target lock too, to get to use his ship ability. Maybe this is a general problem with abilities that grants extra actions?

The other advanced pilots should also usually prioritze target lock over focus

**Comment by Sandrem** [comment]
Note: At the moment AI ships don't take TL at all.

**Comment by rune-b** [comment]
Oh. I have been shot with torpedoes by the AI, but maybe only with abilities that don't require TL

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/issues/1592
