### ISSUE TITLE
Improve AI Vader + Mini Swarm squadron

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1593]
This squadron is only 186 points after the points update. And Sense is not really any use on AI Vader currently

Suggestion:
Replace Sense with Hate
Replace one Black Squadron Ace with Howlrunner
New total: 197pts

**Comment by bitsai** [comment]
Took a stab at this in https://github.com/Sandrem/FlyCasual/pull/1696, since I was already poking around the random AI squads.
