### ISSUE TITLE
Quickdraw and SF Gunner bonus attack

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#1595]
I had Quickdraw with SF gunner, turret facing rear.  I fired at I6 (front only, skipped rear bonus attack).  Later in the turn I took damage and was able to shoot from the front as a "revenge shot" after losing a shield and then SF gunner triggered, granting me a rear shot for a total of three attacks.  In a later game I tried this again, got three shots, but it crashed the game when I attempted to take a fourth shot.  QD should only be able to take two shots max regardless (revenge shot OR SF gunner front/back), as all ships are now limited to one attack and one bonus attack per round.  You legally can't do the quadruple attack like in 1E.    

I haven't done any coding in years, and have almost no game design experience, but do I have a small suggestion.  Each ship should have a boolean value for having taken a bonus attack which sets to false at the start of the round.  If they take a bonus attack, it flips to true, and any further attempts to bonus attack are skipped (it's like a charge that the player never sees).  Their regular attack should not be affected by this check, so they are capped at two attacks per round assuming they have a way to trigger bonus attacks.  This way you've baked bonus attacks into the design of the game.

**Comment by Sandrem** [comment]
Was fixed
