### ISSUE TITLE
Crash on Android when trying to select ARC-Pilot

### ISSUE THREAD

**Issue by Alarith** [Sandrem/FlyCasual#1596]
When trying to select a rebel ARC pilot, the system shows Miranda and then crashes.
I was not able to get the stack trace I'll try again later. This was on a Fire tablet.

**Comment by rune-b** [comment]
Was this in the squad builder or after the game had started?
Do you remember which ARC pilot?

**Comment by Alarith** [comment]
In the squad builder.

**Comment by rune-b** [comment]
OK. I have no  such problem on my android phone. Does it work for pilots other than the ARCs?

If you can get a screen shot of the error message that would be very helpful

**Comment by Sandrem** [comment]
Seems that your device couldn't download image of a pilot - that caused the crash.
Will be fixed in 0.7.5
