### ISSUE TITLE
Ello Asty's pilot ability doesn't trigger

### ISSUE THREAD

**Issue by rkukuchka** [Sandrem/FlyCasual#1597]
During planning stages, talon roll is displayed as white, but when actually executed it leaves Ello stressed

**Comment by rkukuchka** [comment]
Hrmm, not 100% reproducible. Let me try to get repro steps

**Comment by Sandrem** [comment]
Maybe bacause ability says "if you have 2 or fewer stress tokens, treat that maneuver as white.", but you have 3 stress tokens?

**Comment by bitsai** [comment]
Re-tested this in latest development branch, still couldn't reproduce, closing for now.
