### ISSUE TITLE
Range message doesn't show range inside arc

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1598]
0.7.4 android 

Cartel Spacer is not able to shoot TIE at range 3

![screenshot_20190218-163747](https://user-images.githubusercontent.com/11047987/53027930-272bc800-3466-11e9-8a6e-243b75bd3620.png)

**Comment by Sandrem** [comment]
Seems that range between ships is 3, but range inside arc is 4.

**Comment by rune-b** [comment]
I don't see how that can be. They are facing each other

**Comment by Sandrem** [comment]
![image](https://user-images.githubusercontent.com/6347443/53257261-5f374300-36d2-11e9-9b48-52ad1a1f5288.png)

**Comment by rune-b** [comment]
Hmm, you are right. But that means that the range message doesn't show attack range then? So the message could say range 2 but in arc range could be 3,giving the defender range bonus. Could be confusing

**Comment by bitsai** [comment]
Moving this to Requested Features wiki (https://github.com/Sandrem/FlyCasual/wiki/Requested-Features).
