### ISSUE TITLE
AI doesn't use Adaptive Ailerons

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1600]
When playing against the Captain Feroph squad, he never uses Adaptive Ailerons, even if it is mandatory to use. Probably applies to all ships with this ability

**Comment by Sandrem** [comment]
AI cannot plan such extra maneuvers at the moment.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
