### ISSUE TITLE
Unable to add R4 astromechs on ARC-170

### ISSUE THREAD

**Issue by havfal** [Sandrem/FlyCasual#1607]
In squad builder I am unable to add R4 astromech on ARC-170 pilots (none of them) on macOS 10.14, flyCasual 0.7.4.

<img width="1280" alt="skjermbilde 2019-02-22 kl 19 54 32" src="https://user-images.githubusercontent.com/47900210/53264602-4b90da00-36dc-11e9-851f-e331bbe4c4c1.png">

**Comment by Sandrem** [comment]
![image](https://user-images.githubusercontent.com/6347443/53264769-19d04100-36e5-11e9-945f-b12f79e90e52.png)
This upgrade cannot be installed on medium-size ships.

Not a bug, closed.
