### ISSUE TITLE
Unable to trigger Corran Horn i0

### ISSUE THREAD

**Issue by havfal** [Sandrem/FlyCasual#1608]
During play I was unable to trigger Corrans i0 shot. I did fire on the same ship at Corrans i5.

<img width="1280" alt="skjermbilde 2019-02-22 kl 21 20 02" src="https://user-images.githubusercontent.com/47900210/53269936-813cbf80-36ea-11e9-9b52-fd9e930bd1c6.png">

**Comment by Sandrem** [comment]
Because target is not in bullseye arc.

![image](https://user-images.githubusercontent.com/6347443/53270130-85b9a600-36f3-11e9-9e5f-c44a9f05f069.png)

Not a bug, closed.
