### ISSUE TITLE
AI Lt. Kestal: Unable to Proceed After Defense Die Roll

### ISSUE THREAD

**Issue by Tomcattwo** [Sandrem/FlyCasual#1612]
Fly Casual Ver 0.7.5, Android. apk on Samsung Galaxy tab 3 tablet.

Turn 2, after AI Aggressor (LT Kestal) shot at Y-Wing  (Gold Sqdn pilot to the right of U-Wing) and Y-Wing rolled defense dice, never got the prompt for Focus or OK, so could not proceed with the game. Could still move the playmat.

Screenshot link on Google drive:

https://drive.google.com/file/d/1Kn1x8r9Rn2DOHtubip6Re8xttqp9YZ-3/view?usp=drivesdk

R/
Tomcattwo

**Comment by rune-b** [comment]
I suspect Kestals ability is the cause of the problem, since it affects the defense dice

**Comment by rune-b** [comment]
Reproduced with AI Kestal against single Gold Squadron. Kestal cancelled my defense dice and the the game was stuck

![image](https://user-images.githubusercontent.com/11047987/53302829-14006a00-3863-11e9-9323-8fb86d5652ce.png)

**Comment by rune-b** [comment]
Message in the Unity console:


GameController:SendCommand(GameCommandTypes, Type, String) (at Assets/Scripts/Model/GameController/GameController.cs:45)
Players.GenericAiPlayer:PerformActionFromList(List`1) (at Assets/Scripts/Model/Players/GenericAiPlayer.cs:462)
Players.GenericAiPlayer:TakeDecision() (at Assets/Scripts/Model/Players/GenericAiPlayer.cs:416)
SubPhases.DecisionSubPhase:StartIsFinished() (at Assets/Scripts/Model/Phases/SubPhases/Temporary/DecisionSubPhase.cs:110)
SubPhases.ActionDecisonSubPhase:PrepareDecision(Action) (at Assets/Scripts/Model/Phases/SubPhases/ActionSubphase.cs:114)
SubPhases.DecisionSubPhase:Start() (at Assets/Scripts/Model/Phases/SubPhases/Temporary/DecisionSubPhase.cs:92)
Phases:StartTemporarySubPhaseOld(String, Type, Action) (at Assets/Scripts/Model/Phases/Phases.cs:90)
SubPhases.ActionSubPhase:StartActionDecisionSubphase(Object, EventArgs) (at Assets/Scripts/Model/Phases/SubPhases/ActionSubphase.cs:50)
Trigger:Fire() (at Assets/Scripts/Model/Tools/Triggers.cs:118)
Triggers:FireTrigger(Trigger) (at Assets/Scripts/Model/Tools/Triggers.cs:258)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:238)
PhaseEvents:CallOnActionSubPhaseTrigger() (at Assets/Scripts/Model/Phases/PhaseEvents.cs:167)
SubPhases.ActionSubPhase:Initialize() (at Assets/Scripts/Model/Phases/SubPhases/ActionSubphase.cs:45)
ShipMovementScript:FinishMovementAndStartActionDecision() (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:203)
<LaunchMovement>c__AnonStorey0:<>m__0() (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:212)
<LaunchMovementPrepared>c__AnonStorey1:<>m__0() (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:230)
Triggers:DoCallBack() (at Assets/Scripts/Model/Tools/Triggers.cs:322)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:248)
Triggers:FinishTrigger() (at Assets/Scripts/Model/Tools/Triggers.cs:279)
Triggers:DoCallBack() (at Assets/Scripts/Model/Tools/Triggers.cs:322)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:248)
Ship.GenericShip:FinishPosition(Action) (at Assets/Scripts/Model/Content/Core/Ship/GenericShipMovement.cs:198)
Ship.<CallFinishMovement>c__AnonStorey12:<>m__0() (at Assets/Scripts/Model/Content/Core/Ship/GenericShipMovement.cs:189)
Triggers:DoCallBack() (at Assets/Scripts/Model/Tools/Triggers.cs:322)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:248)
Ship.GenericShip:CallFinishMovement(Action) (at Assets/Scripts/Model/Content/Core/Ship/GenericShipMovement.cs:185)
Ship.<CallExecuteMoving>c__AnonStorey11:<>m__0() (at Assets/Scripts/Model/Content/Core/Ship/GenericShipMovement.cs:145)
Triggers:DoCallBack() (at Assets/Scripts/Model/Tools/Triggers.cs:322)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:248)
Triggers:FinishTrigger() (at Assets/Scripts/Model/Tools/Triggers.cs:279)
RulesList.StressRule:CheckStress(Object, EventArgs) (at Assets/Scripts/Model/Rules/RulesList/StressRule.cs:61)
Trigger:Fire() (at Assets/Scripts/Model/Tools/Triggers.cs:118)
Triggers:FireTrigger(Trigger) (at Assets/Scripts/Model/Tools/Triggers.cs:258)
Triggers:ResolveTriggers(TriggerTypes, Action) (at Assets/Scripts/Model/Tools/Triggers.cs:238)
Ship.GenericShip:CallExecuteMoving(Action) (at Assets/Scripts/Model/Content/Core/Ship/GenericShipMovement.cs:143)
Movement.GenericMovement:FinishManeuverExecution() (at Assets/Scripts/Model/Movement/MovementTypes/GenericMovement.cs:175)
Movement.GenericMovement:ManeuverEndRotation(Action) (at Assets/Scripts/Model/Movement/MovementTypes/GenericMovement.cs:180)
Movement.GenericMovement:FinishMovement() (at Assets/Scripts/Model/Movement/MovementTypes/GenericMovement.cs:168)
Movement.NonStraightMovement:CheckFinish() (at Assets/Scripts/Model/Movement/MovementTypes/Movement/NonStraightMovement.cs:84)
Movement.GenericMovement:UpdateMovementExecution() (at Assets/Scripts/Model/Movement/MovementTypes/GenericMovement.cs:143)
Movement.NonStraightMovement:UpdateMovementExecution() (at Assets/Scripts/Model/Movement/MovementTypes/Movement/NonStraightMovement.cs:75)
ShipMovementScript:UpdateMovement() (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:39)
ShipMovementScript:Update() (at Assets/Scripts/Model/Movement/ShipMovementScript.cs:30)
