### ISSUE TITLE
Range 1, cannot fire

### ISSUE THREAD

**Issue by Zipline20** [Sandrem/FlyCasual#1613]
![image](https://user-images.githubusercontent.com/27784255/53296495-4f505980-37cd-11e9-84bf-3e26cf51b4f4.png)

**Comment by Sandrem** [comment]
Seems that target is not in arc.

![image](https://user-images.githubusercontent.com/6347443/53297438-7cc9f100-3827-11e9-9e38-58a4f88253ba.png)

**Comment by Zipline20** [comment]
Woops! My bad!

On Sun, Feb 24, 2019, 2:29 AM Sandrem <notifications@github.com<mailto:notifications@github.com>> wrote:

Seems that target is not in arc.

[image]<https://user-images.githubusercontent.com/6347443/53297438-7cc9f100-3827-11e9-9e38-58a4f88253ba.png>
