### ISSUE TITLE
Practically impossible to do swarm tactics chaining 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1617]
No way to know which trigger belongs to which ship

![screenshot_20190225-080458](https://user-images.githubusercontent.com/11047987/53319999-84939f00-38d4-11e9-8a82-3fd7d9fc4e3a.png)

**Comment by rune-b** [comment]
A couple of ideas on how to solve it:

- Always show ship ID next to pilot name (I assume the number on the trigger is the ship ID)
- Color code each trigger, and mark each corresponding ship panel with the same color
- Allow mouse over / touch press and hold on trigger to highlight which ship it belongs to
- Change to two step process: First select trigger which highlights the ship. Then press confirm or select different trigger

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features

**Comment by drdov** [comment]
plus one -- i hit this today
