### ISSUE TITLE
FE Veteran Instincts Bug 

### ISSUE THREAD

**Issue by BenSimi** [Sandrem/FlyCasual#1618]
I´m not into 2.0 but love your FE !! 

Concerning 7.5.0 FE Windows X:

* After choosing Veteran Instincts,  game crashes. Happens with every ship. 
![vetbug1](https://user-images.githubusercontent.com/47971915/53327526-430cef00-38e8-11e9-800a-856ed08d9b10.PNG)

*Dash Rendar equipped with Outrider Title / Heavy Laser Cannon can fire at Range 1 w/Heavy laser Cannon

**Comment by rune-b** [comment]
Thanks for reporting. Not many people are playing FE these days, so these bugs tend to slip under the radar a bit...

**Comment by Sandrem** [comment]
Fixed
