### ISSUE TITLE
Stop maneuver should always count as fully executed 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1619]
Case: 4-LOM bumps another ship. Next turn does red stop maneuver while being bumped. He should still get his free calculate for fully executing a red maneuver, but he doesn't. 

Rules p6

 A ship that executes a stationary maneuver always fully executes the 
maneuver.

![screenshot_20190225-190300](https://user-images.githubusercontent.com/11047987/53358442-a1f65680-3930-11e9-88e8-70d6c0e33e43.png)

**Comment by Sandrem** [comment]
Fixed
