### ISSUE TITLE
Princess Leia continuously active

### ISSUE THREAD

**Issue by McLaine** [Sandrem/FlyCasual#1622]
It seems that when I trigger Leia, her effect remains active for subsequent turns.

Tried her in a list with some U-wings and was able to do white stop maneuvers on consequtive turns.

**Comment by Sandrem** [comment]
I don't see how this is possible - ability is turned off in the end of the round.
If you will encounter the same problem again, or even will find steps to reproduce - please, inform me.

**Comment by McLaine** [comment]
I've just tried it again, and I also cannot reproduce. Apologies.

**Comment by jesse-troy** [comment]
This just happened to me as well. I came to report it and there was already this issue. It happened two or three games in a row.

**Comment by Sandrem** [comment]
Still cannot reproduce.
