### ISSUE TITLE
Intimidate + Outmaneuver on Arvel Crynyd only reduces defense by 1.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1626]
Had Arvel on the back-right arc of an X-Wing, with a collision, with Intimidate + Outmaneuver.  The X-Wing still rolled one defense die when they should have rolled no defense dice.

**Comment by bitsai** [comment]
@DejaFu (cc @Sandrem ) how were you able to get Arvel to fire on a bumped ship?  In my games so far, whenever I select Arvel and then try to select an enemy ship at range 0, I always get the error "This enemy ship cannot be selected".

For reference, this is in version 0.7.6, and I've only tested against ships with lower IN than Arvel (I find it easier to bump this way).

**Comment by DejaFu** [comment]
I don't remember.  And it makes me think that possibly the X-Wing jumped ahead of me and was Luke or Wedge, the ships were close enough to look like they bumped, and I wasn't paying too much attention.  And then when the attack roll showed one die rolled, I thought there was an issue.  I have since tried other cases and had no trouble.  As for Arvel bumping, he can bump with a boost, and he can fire at range 0 on a target.

**Comment by Sandrem** [comment]
@bitsai I don't see any bug reports about problems with Arvel and attacks at range 0.
If problem is present - please, create issue.

I changed how target of shot is chosen in 0.7.6. Maybe this bug was not present in 0.7.5

**Comment by bitsai** [comment]
@DejaFu @Sandrem thank you both for the detailed responses.  I've done some more testing based on the info you shared, and will create a new issue.  Thank you!

**Comment by bitsai** [comment]
@DejaFu @Sandrem did some testing just now (using latest `development` branch): when Arvel (with Intimidation + Outmaneuver) bumped an X-wing from the back, the X-wing rolled 0 green dice as you would expect.

**Comment by bitsai** [comment]
Re-tested this in latest development branch using Arvel (w/ Intimidation + Outmaneuver) to bump a TIE/ln fighter from the back, the TIE rolled 1 green die (3 - 2) as expected when shot by Arvel, closing.
