### ISSUE TITLE
Jek Porkins ignores asteroid collision if he rolls to remove stress from his ship.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1627]
Had a Jek Porkins keep passing over an asteroid, doing K-turns.  The damage die was only ever rolled once per run and he would focus afterwards.  It should have rolled once for his ability and once for the asteroid, and, having run over an asteroid, he should not have been able to take an action.

**Comment by bitsai** [comment]
Just tested this again in the latest release (0.9.2), was not able to reproduce.  When I K-turned Porkins over a rock, his ability triggered (and I took a damage when a hit result was rolled), my action was skipped as expected, then the UI for rolling asteroid damage came up (see screenshot), a hit result was rolled again and I took another damage (resolved after the screenshot was taken).

<img width="1280" alt="Screen Shot 2019-07-12 at 4 02 11 PM" src="https://user-images.githubusercontent.com/260863/61162779-2bad5780-a4bf-11e9-9b4f-b47b065aa1b9.png">
