### ISSUE TITLE
Rolling enough evades should stop resource checks (feature)

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1628]
Right now, if Han Solo is near an asteroid, has the Millennium Falcon upgrade, and has a focus token, even if he rolls one evade (the most he can roll) against an attack, the user has to go through two skip options to finish the defense.  It would be nice if, when all the dice show evades or if all the attacks have been evaded, it skipped all other requests to use defensive resources.

**Comment by Sandrem** [comment]
Sometimes you want to allow opponent to hit you - and try to reroll evade into blank. (For example. to get 1 damage, but avoid to get "when you missed - attack again" shot)

I don't plan to skip decisions that can be useful in rare cases.
