### ISSUE TITLE
A scroll bar would be helpful for loading squads.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1629]
It would be very helpful if the squad loading screen had a scroll bar.  Using the mouse wheel to scroll is very slow.

**Comment by rune-b** [comment]
I think that we should speed up the mouse wheel scrolling in general. At least for me, its almost too slow to be usable. Especially in the console window

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
Also you can try to drag this screen (as using touch controls in mobile devices).
