### ISSUE TITLE
Out of arc targets not being options (feature)

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1631]
It would be helpful if out of arc and out of range targets were not given as possible targets for attacks.   And if no targets are in range, it would speed up combat if that attacker's actual attack was skipped, with a message stating no targets were in range or in arc.

**Comment by Sandrem** [comment]
Players can use this time-window to measure range to all enemy ship. This information can be useful for further decision making.

I will not add this feature.

**Comment by DejaFu** [comment]
Then how about a compromise where it gives you a message that no enemies are in range or no enemies are in arc, and then also has the skip button for skipping the step.  Then they know the system doesn't see any valid targets, but they can do the measurements still.

**Comment by Sandrem** [comment]
Yes, this idea is OK

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
