### ISSUE TITLE
Add saved squads to the random squad used (feature)

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1632]
It would be cool if the squads a user saved was then available as a random squad.  Maybe it would be even better if you could mark saved squads as useable for the random squads, so that squads that aren't effective could be left unmarked while you work on them.

**Comment by Sandrem** [comment]
I like idea with "use in random squads" checkbox.

**Comment by Sandrem** [comment]
Moved to https://trello.com/b/3MI9gxVw/fly-casual
