### ISSUE TITLE
Joy Rekoff was able to shoot while overlapping asteroid

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1634]
Only the plastic base was overlapping, not the cardboard token. Not sure it it matters 

0.7.5 android 

![screenshot_20190301-085653](https://user-images.githubusercontent.com/11047987/53658808-29f29e00-3c5a-11e9-8d4a-9d2d53ae38f3.png)

**Comment by rune-b** [comment]
Sorry, I forgot to save the replay. Maybe we should store more than just the last replay?

Then again, it was an android replay and they are still broken I think

**Comment by DifferentialityDevelopment** [comment]
Kan second this with Cpt. Seevor on PC just now with 0.8.2, he was able to shoot of Asteroids.
He should only be able to freely move over asteroids but not shoot off them.

**Comment by bitsai** [comment]
It's really hard to try to reproduce with AI, so I did a Hotseat game w/ Joy & Seevor.  Neither were able to shoot while overlapping asteroids (see screenshots below).  Closing this for now, but please feel free to re-open if this pops up again!

<img width="1280" alt="Screen Shot 2019-07-12 at 3 50 52 PM" src="https://user-images.githubusercontent.com/260863/61162365-1a634b80-a4bd-11e9-9395-5781e7936f2b.png">

<img width="1280" alt="Screen Shot 2019-07-12 at 3 51 00 PM" src="https://user-images.githubusercontent.com/260863/61162376-23541d00-a4bd-11e9-9331-fb15e04f181a.png">
