### ISSUE TITLE
[0.7.6] Freeze when ship has Console Fire + Disabled Power Regulator

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#1639]
Reached this point in a game, and it won't continue. Hopefully the log will give you some information. If it helps, the Y-wing currently has Stunned Pilot, Console Fire, and Disabled Power Regulator applied.

![screenshot 2019-03-04 15 07 11](https://user-images.githubusercontent.com/1558951/53759928-7246d180-3e8f-11e9-90af-e4da46383fe7.png)

**Comment by Sandrem** [comment]
Yes, seems this is crit-related. Thank you.

**Comment by NerdimusPrime** [comment]
You're welcome. I was just now able to continue by using the "subphase finish" console command.

**Comment by bitsai** [comment]
I found a few other issues that appear to be related, and the common cause seems to be an ionized ship that also has the Console Fire crit, updating title accordingly.
