### ISSUE TITLE
Swarm tactics applied to whole squad and doesn't proceed to next phase.

### ISSUE THREAD

**Issue by dankwc2000** [Sandrem/FlyCasual#164]

**Comment by Sandrem** [comment]
Fixed is stable 0.1.2
Same problem can appear in all other abilities that require to select another ship.

**Comment by Sandrem** [comment]
Squad Leader is fixed too.

**Comment by Sandrem** [comment]
Garven Dreis is fixed too

**Comment by Sandrem** [comment]
Dutch Vander works fine enough (only minor warning during debug, will be cleaned later)

**Comment by Sandrem** [comment]
Build in reddit post is reuploaded with all fixes.
