### ISSUE TITLE
Novice technician crash

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1640]
0.7.6
Lok Revenant with nov. Tech.

**Comment by rune-b** [comment]
![screenshot_20190305-165943](https://user-images.githubusercontent.com/11047987/53818376-43505e80-3f68-11e9-810b-4857ff90abca.png)

**Comment by rune-b** [comment]
Tested a bit more. Seems to only crash if a hit is not rolled.

**Comment by Sandrem** [comment]
Fixed
