### ISSUE TITLE
Guri not gaining his focus while enemy at range 0

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#1643]
Guri didn't gain his Focus while Vader was at range 0 from him at the start of the Engagement Phase (turn 2).

I used the Always option on turn 1 and it worked with an enemy at range 1.

EDIT: Can confirm it always works correctly at range 1.

![guri](https://user-images.githubusercontent.com/47178393/53916123-a376fb80-4061-11e9-8aca-3328d1a0354c.png)

**Comment by rune-b** [comment]
Good catch! Guri's ability has not been changed since First Edition. I will fix
