### ISSUE TITLE
[0.7.6] Arvel Crynyd cannot select targets at range 0

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1645]
One of Arvel's abilities is being able to fire primary weapons at range 0.  It appears that this is not working in **0.7.6**.  Steps I used to reproduce:

- set up a 1-on-1 fight between Arvel Crynyd (Rebel A-wing pilot) and Empire TIE Fighter
- set up asteroids to the sides and Arvel directly across from the TIE Fighter, so there's an open lane between the two ships
- 1st turn: select straight-4
- 2nd turn: select straight-2
- 3rd turn: assuming the TIE Fighter has also moved straight, a straight-2 and then a boost should get the two ships to bump
- select Arvel, then try to select TIE Fighter as target; should get the error "This enemy ship cannot be selected"

I downloaded **0.7.5** and did the same steps, and was able to fire on the TIE Fighter at range 0.  So I think this issue is specific to **0.7.6**.

**Comment by bitsai** [comment]
@Sandrem FWIW, I think I have an idea why this is happening.

- I believe the error message is shown by the `AnotherShipCanBeSelected` method due to `FilterTargets(anotherShip)` returning false: https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Phases/SubPhases/Temporary/SelectShipSubPhase.cs#L200
- I think the `FilterTargets` method being used in this case is `FilterAttackTargets`, set here: https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Phases/SubPhases/Temporary/SelectTargetForAttackSubPhase.cs#L20
- finally, `FilterAttackTargets` is returning false when an enemy ship at range 0 is selected due to the check on `minRange` (https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Phases/SubPhases/Temporary/SelectTargetForAttackSubPhase.cs#L39), which is currently hard-coded to 1 (https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Phases/SubPhases/Temporary/SelectShipSubPhase.cs#L25)

Even if this is correct, unfortunately I don't know the codebase well enough yet to create a patch correctly.  But hopefully this will help narrow things down somewhat.

**Comment by rune-b** [comment]
Same problem for me
![Screenshot_20190314-230951](https://user-images.githubusercontent.com/11047987/54412938-95c21580-46f4-11e9-8828-267ff0aba049.png)

**Comment by Sandrem** [comment]
@bitsai Thank you for investigation.
I changed minRange to 0
