### ISSUE TITLE
Liea not working

### ISSUE THREAD

**Issue by Croste** [Sandrem/FlyCasual#1650]
Liea crew didn't seem to work for entire squad.

**Comment by Sandrem** [comment]
Steps to reproduce? Or screenshot at least?

**Comment by Croste** [comment]
It maybe operator error. I haven't been able to reproduce it. It was from the first game I played. Haven't seen it act up since I have logged a couple hours in on the game.Thanks for the speedy response. Amazing program. Very user friendly.

Sent from Yahoo Mail on Android 
 
  On Fri, Mar 8, 2019 at 6:19 AM, Sandrem<notifications@github.com> wrote:   
Steps to reproduce? Or screenshot at least?

**Comment by Sandrem** [comment]
Still cannot reproduce
