### ISSUE TITLE
Reload action no reloading

### ISSUE THREAD

**Issue by the8bitzchez** [Sandrem/FlyCasual#1651]
Was flying with the starfortress and when I used the reload action to reload my proximity mines or siesmic charges it told me there was no valid target. Love the software, keep up the good work!

**Comment by ctsdistrict** [comment]
Proximity mines don't allow reloading. Might be relevant. 
![image](https://user-images.githubusercontent.com/7253995/54076479-51082b80-4269-11e9-892f-1c7beaa07b18.png)

**Comment by rune-b** [comment]
I just tried this, and had no problems reloading seismic charges on a Star Fortress. Proximity Mines would not reload, as it should be
