### ISSUE TITLE
Make Rattled Condition Limited

### ISSUE THREAD

**Issue by Benjaminecrosby** [Sandrem/FlyCasual#1653]
The Rattled Condition is stacking and causing multiple Critical hits.  This is a Unique card and should only be present on 1 ship - 1 instance at a time.

**Comment by bitsai** [comment]
Right now it looks like all Conditions in the game are Limited, not just Rattled.

**Comment by bitsai** [comment]
Actually, after looking more closely, it looks like it's only Rattled that needs to be updated.  The other Conditions in the game are either not re-assignable or already handle uniqueness (Kylo Ren's I'll Show You the Dark Side, Captain Rex's Suppressive Fire).

So really this just boils down to updating Rattled to emulate either I'll Show You the Dark Side or Suppressive Fire.
