### ISSUE TITLE
Lock action should allow selection of friendly ships and obstacles.

### ISSUE THREAD

**Issue by ggrabarz** [Sandrem/FlyCasual#1659]
In second edition while performing the [Lock Action](https://xwing-miniatures-second-edition.fandom.com/wiki/Lock) you are forced to choose any object in range 0-3, including friendly ships and obstacles. You cannot choose to voluntary fail the action if there's something in range (to trigger [Composure ](https://xwing-miniatures-second-edition.fandom.com/wiki/Composure)for example). Additionality sometimes you want to lock friendly ships to use upgrades like [M9-G8](https://xwing-miniatures-second-edition.fandom.com/wiki/M9-G8) (to allow the die reroll on their attack) or [Qi'ra](https://xwing-miniatures-second-edition.fandom.com/wiki/Qi'ra) to ignore locked obstacles.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
