### ISSUE TITLE
Arvel Crynyd not able to attack at range 0

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1666]
![Screenshot_20190314-230951](https://user-images.githubusercontent.com/11047987/54395020-dd25b300-46ae-11e9-803c-af717ee51b89.png)
0.7.6 android

**Comment by bitsai** [comment]
@rune-b I filed https://github.com/Sandrem/FlyCasual/issues/1645 to report the same issue; I love Arvel!

**Comment by rune-b** [comment]
Ah. I'll close this one then
