### ISSUE TITLE
Sunny Bounder ability doesn't work on re-rolls as intended

### ISSUE THREAD

**Issue by Unclebaby** [Sandrem/FlyCasual#1667]
This doesn't always work.

It only triggers on a natural roll - not re-rolls.

(Lovely work, by the way!)

Edit: v0.7.6

**Comment by rune-b** [comment]
@Sandrem I don't understand this one. When I debug, all the code seems to be working fine, and AddAvailableDiceModification is called after re-rolls too, but no modification appears in the UI.
