### ISSUE TITLE
Resistance Chewbacca's Ability Broken

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#1670]
Chewie's ability (resistance) has thrown several bugs at me in the span of a few games.  In previous releases the only problem was that his ability didn't trigger when he died.  

Currently, if another friendly ship dies, it will be stuck on the board, no bonus attack will trigger, and the game crashed when crits were dealt.  If Chewie dies, you can't select him to start the bonus attack, and have to "subphase finish" in the console.  The falcon will remain on the table into the next turn.

I suspect that since FC now does the "keep everything on the board until that particular initiative level is done" interpretation of the rules that something went amiss in the process of removing the destroyed ship.  Perhaps the game is trying to take the bonus attack when the ship is removed from the board and not when it is initially destroyed?  I'm speculating here, but that's the change I've seen to the main game that would affect this otherwise mostly functional ship.

**Comment by SleepyJedi** [comment]
Ran into this issue as well, but after a friendly ship was destroyed, got a bunch of what I presume is crash code
![Crash](https://user-images.githubusercontent.com/26986510/56101266-f51f6b00-5ed6-11e9-9bd8-f58d8ab574a0.png)

**Comment by Spraggle** [comment]
I've had this issue happen every time I kill Chewie - I try to go for him first. I've also had it crash when I'm trying to go for an A wing that's near by. I've been playing on Android, so it's difficult to get the error logs.

**Comment by DejaFu** [comment]
If it helps, here's an image I just got.  Probably for the same bug.
![Chewbacca destroyed bug](https://user-images.githubusercontent.com/48073298/58523978-c2c68600-8183-11e9-907a-1b85870fd968.png)

**Comment by Sandrem** [comment]
Fixed
