### ISSUE TITLE
Hound's Tooth: docked ship doesn't have a texture

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1672]
![Clipboard01](https://user-images.githubusercontent.com/30575527/54492894-818c3d00-48db-11e9-98a3-1bdf4e8369c0.jpg)

**Comment by rune-b** [comment]
I get the same. However, when the docked ship undocked the texture appeared

**Comment by Unclebaby** [comment]
I get this too in v.76.

**Comment by Sandrem** [comment]
Fixed
