### ISSUE TITLE
Nashtah Pup might be copying the wrong carrier statistics

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1673]
During a game against AI, my YV-666 piloted by Bossk got destroyed; the emergency Nashtah Pup had an initiative of 0, but also rolled 4 attack dice against Luke at distance 1.

EDIT: Also didn't copy Moralo Eval's ability and charges.

**Comment by rune-b** [comment]
The Nashtah Pup currently starts with N'dru Suhlak's ability (copy/paste bug I guess), so that probably explains the extra attack dice 

The ability doesn't seem to work at all

**Comment by Sandrem** [comment]
Fixed.
If problem will be still present in 0.8.0 - please, inform me.
