### ISSUE TITLE
Howl Runner not triggering

### ISSUE THREAD

**Issue by Croste** [Sandrem/FlyCasual#1678]
Howl Runner should trigger for her own rolls and is not.
Playing on my Android. Haven't test on my computer or taken screen shots. Just something I noticed.
Still amazing game.

**Comment by rune-b** [comment]
Are you playing with First or Second edition rules?

**Comment by rune-b** [comment]
It triggered for me now at least. Which version of FlyCasual are you using? 

![Screenshot_20190318-171603](https://user-images.githubusercontent.com/11047987/54545236-929f8180-49a1-11e9-8d65-a1905f12e655.png)

**Comment by Croste** [comment]
Second. 

Sent from Yahoo Mail on Android 
 
  On Mon, Mar 18, 2019 at 5:10 AM, rune-b<notifications@github.com> wrote:   
Are you playing with First or Second edition rules?

**Comment by Croste** [comment]
Version 0.7.6
Galaxy S6

**Comment by Croste** [comment]
Howl is working on my S6. It seems when I load a new list into the game, something in the squad doesn't work the first time I play it. Or I'm just not noticing it working when I play it for the first time. Weird.

**Comment by Sandrem** [comment]
I don't have reports from another players about problems with Howlrunner.
Please, next time, is something is wrong, take a screenshot. Maybe, range was above 1, or special weapon was used etc...

I close this issue.
