### ISSUE TITLE
possible Error Line in AI Attack Decision

### ISSUE THREAD

**Issue by mahenning** [Sandrem/FlyCasual#1683]
https://github.com/Sandrem/FlyCasual/blob/2e844e009a243f793400a54cabc56d6e0968efc3/Assets/Scripts/Model/Ai/Aggressor/TargetingSubSystem/TargetingSubSystem.cs#L92

This float is always 0. Maybe potentialHits - potentialEvades?

**Comment by Sandrem** [comment]
Thank you, changed to "potentialHits - potentialEvades"
