### ISSUE TITLE
[0.7.6] RZ-2 A-Wing unable to fire Proton Rockets when turret is facing backwards

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1685]
Was flying an RZ-2 A-Wing with Proton Rockets, had an enemy ship in bullseye arc within range 2, but was unable to select it as a target for Proton Rockets, likely due to the RZ-2 turret facing backwards at the time.  AFAIK, this should have been a valid target for Proton Rockets.

<img width="1280" alt="Screen Shot 2019-03-20 at 3 50 56 PM" src="https://user-images.githubusercontent.com/260863/54724406-4894d800-4b28-11e9-8b9b-4dc601084fc3.png">

**Comment by rune-b** [comment]
I get the same problem. It works with concussion missiles, so its probably something wrong with proton rockets

**Comment by bitsai** [comment]
@rune-b you're right, it looks like the issue is specific to Proton Rockets (I tried Cluster Missiles, they were also unaffected).  The definition for Proton Rockets doesn't contain any custom code, so I suspect the issue is around bullseye arc for special weapons.  Will keep looking and see if I find anything useful.

**Comment by rune-b** [comment]
YT-1300 has same problem

![Screenshot_20190323-201613](https://user-images.githubusercontent.com/11047987/54870597-0d550c00-4da9-11e9-9d0c-3b849d02d41d.png)

**Comment by rune-b** [comment]
You are right, this is not a proton rockets specific issue. I put a Heavy Laser Cannon on a RZ-2 A-Wing and got the same problem

![image](https://user-images.githubusercontent.com/11047987/54871245-69239300-4db1-11e9-80ca-b68d45af633d.png)

**Comment by bitsai** [comment]
@rune-b @Sandrem think I found the root cause (https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Board/Info/ShotInfoArc.cs#L110-L111, added in https://github.com/Sandrem/FlyCasual/pull/1140).  It looks like that check was added to prevent the AI mistakenly thinking there was a shot available in bullseye arc when there is no forward-facing arc.

I implemented a small fix that makes an exception for bullseye arc weapons (such as Proton Rockets and Heavy Laser Cannons) in https://github.com/Sandrem/FlyCasual/pull/1689 and verified it using the RZ-2 + Proton Rockets.  Let me know what you think!

**Comment by Sandrem** [comment]
@bitsai You are right, thank you for fix.
