### ISSUE TITLE
Ship abilities should have different name than pilot ability

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1687]
Currently they have the same name as the pilot ability which is confusing, especially if they trigger at the same time:

![image](https://user-images.githubusercontent.com/11047987/54788321-e5da3400-4c2e-11e9-8a03-b80b8ff0f23e.png)

Ship abilities should instead use the ability name from the card.

**Comment by Sandrem** [comment]
I set custom name in "FineTunedControlsAbility" class.
This should be done for all ship abilities too.

**Comment by bitsai** [comment]
@Sandrem I can tackle this one; can you assign it to me?

**Comment by Sandrem** [comment]
@bitsai OK, do this task.

**Comment by bitsai** [comment]
@rune-b I think this should be good to go now!
