### ISSUE TITLE
Game gets stuck "Trying to flip critical card"

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#169]
I had a game that I had to terminate since it would not progress after a critical hit. See screen shot below.
The console was flooded with MissingReferenceExceptions

Unfortunately I don't know how to reproduce this bug :(

![stuck](https://user-images.githubusercontent.com/11047987/29744696-c15634a4-8aaa-11e7-9924-f62ffd4e7708.png)

**Comment by Sandrem** [comment]
I already have encountered this critical bug few times, I will check it tomorrow.

**Comment by Sandrem** [comment]
Was reproduced when AI tries to flip "Damaged Sensor Array" crit -> infinite loop.
Fixed in "stable-0.1.2"
But additional testing is required.

Tips: in "DebugManager" class flag "DebugAllDamageIsCrits" can be set to true.  Available critical hit cards can be chosen in "CriticalHitsDeck" class.
