### ISSUE TITLE
Afterburners might be stress-dependent

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1691]
In a game using Dalan Oberos (Starviper) with Afterburners, their trigger selected after a 3-speed S-Loop did not offer the action and cut straight to Dalan's trigger window.

**Comment by rune-b** [comment]
Works for me. Has this happened more than once? Did you have any other upgrades on him?

![Screenshot_20190325-183819](https://user-images.githubusercontent.com/11047987/54941565-72396f00-4f2d-11e9-86c7-bcf444210fb7.png)

**Comment by rune-b** [comment]
And are you sure you had charges left on the afterburners

**Comment by Nitroxylin** [comment]
No charges were spent during the combat at all.
Other upgrades: Outmaneuver, PTorps, Virago, AdvSensors, Stealth Device.
The prompt asking to choose between Afterburners and Dalan's ability appeared, but selecting Afterburners did nothing and cut to Dalan's rotation.
Will try to reproduce.

**Comment by rune-b** [comment]
And you didn't use advanced sensors?

**Comment by Nitroxylin** [comment]
This might be the answer.
Tried to reproduce the bug, did not succeed at it.

**Comment by rune-b** [comment]
I think the trigger for afterburners will show even if you are not allowed to do an auction

**Comment by rune-b** [comment]
Shall we close this issue then, and assume it was due to advanced sensors?
