### ISSUE TITLE
TIE Aggressor doesn't have modification slot

### ISSUE THREAD

**Issue by pixelante** [Sandrem/FlyCasual#1693]
Note: concerning AI, is it possible to have different levels of AI, seems like the AI always takes the hardest lists and tailored to counter your squad.

Errors:
Ion Maneuver should only remove one Ion token.
TIE Aggressor is allowed modification upgrade, but unable to take it in squad builder.
TIE Punisher is allowed to take Skilled Bombardier Gunner upgrade, but this option is not in squad builder.

**Comment by Sandrem** [comment]
1) AI takes random squad from a list, it doesn't know what squad do you use.
2) Ion Maneuver
Rules: After the ship finishes this activation, it removes all of its ion tokens.
https://xwing-miniatures-second-edition.fandom.com/wiki/Ionized
3) TIE Aggressor slots - confirm, I will fix this
4) Game is in development, Skilled Bombardier is one of cards that are not ready yet. Please, don't report missing cards.

**Comment by pixelante** [comment]
Sorry, mate seems to have misread the rule and said only one ion token is removed, I have confirmed this through the rulebook now.
