### ISSUE TITLE
XWS import from YASB fails

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1694]
0.7.6
Reported on reddit

Reproduced by making a squad in YASB with a single B-wing and pasting the json

![Screenshot_20190327-174542](https://user-images.githubusercontent.com/11047987/55095445-734ad780-50b8-11e9-8f86-a315a00b64fe.png)

**Comment by rune-b** [comment]
https://www.reddit.com/r/XWingTMG/comments/b664c1/fly_casual_yasb_xws/

**Comment by Sandrem** [comment]
Seems that game still uses FE names of ships.
![image](https://user-images.githubusercontent.com/6347443/55276654-dded5480-52fe-11e9-8094-4f0746fbcef9.png)

**Comment by Unclebaby** [comment]
I see this fail too with every iOS app exporter that I use.

v0.8.0  OSX

**Comment by Sandrem** [comment]
XWS support will be fixed in v1.0
I don't plan to fix support of this format earlier, because players can lose a lot of saved squads due to changes in format.
