### ISSUE TITLE
AI sometimes ignores asteroid collisions

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1695]
I don't have a good screenshot of this, and it doesn't happen 100% of the time, but this setup should reproduce it at least once:

- use 3 TIE fighters as the opposition
- put each of your 3 asteroids directly in front of each TIE fighter
- wait for them to fly over it

Whenever I do this, at least 1 TIE fighter flies over its asteroid without triggering a damage die roll.

Possibly related:

https://github.com/Sandrem/FlyCasual/issues/1634
https://github.com/Sandrem/FlyCasual/issues/1627
https://github.com/Sandrem/FlyCasual/issues/1535

**Comment by bitsai** [comment]
P.S. I'm using the latest `development` branch.

**Comment by rune-b** [comment]
Reproduced on the latest dev branch with the method you described. The third TIE flew right over the asteroid without rolling

**Comment by rune-b** [comment]
Have you seen this in 0.7.6, or do you think that this is a new bug?

**Comment by bitsai** [comment]
@rune-b I downloaded and tested 0.7.6; I used the above setup 5 times and only saw a TIE fighter fly over an asteroid without a roll once.  It seems like the issue was present in 0.7.6, but became a lot more frequent in the current `development` branch.

**Comment by Sandrem** [comment]
Even player-controlled ships ignore asteroids in dev-branch.

**Comment by Sandrem** [comment]
Seems that new version of Unity has problems with tiny objects. I changed height of front collision detector object x100, seems not this works fine.
For testing: problem can be reproduced if player's (of AI's) ship moves through the obstacle and doesn't stats on it.
