### ISSUE TITLE
Ship/asteroid placement bugs in dev branch

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1698]
Example: I place here:

![image](https://user-images.githubusercontent.com/11047987/55186869-e4ad8780-5197-11e9-8e7d-3e3ff05d4aff.png)

Ship ends up here:

![image](https://user-images.githubusercontent.com/11047987/55186905-f7c05780-5197-11e9-87df-acaa3c6a17a5.png)

also 1 asteroid is missing, and three of them are at range < 1

that was with random asteroid placement. My guess is that one is hidden underneath another

with manual placement I'm not able to place at range < 1, but when I place it, the asteroid shifts a bit in the same way as ship placement

**Comment by rune-b** [comment]
It seems they are always shifted towards the center of the map

**Comment by Sandrem** [comment]
Fixed.
Strange behavior of save/load work of JSONs with float values.
I save "positionX = 4,77", but load "positionX = 4" and additional "positionX = 77".
Seems this bug appeared when I changed version of C# from 4.0 to newer.
