### ISSUE TITLE
Calibrated Laser Targeting

### ISSUE THREAD

**Issue by chrisrivers13** [Sandrem/FlyCasual#1701]
The calibrated laser target is getting charged at 10 points no matter the initiative of the pilot.  This is one of the variable cost upgrades.  v0.8.0

**Comment by StrongHammerTom** [comment]
The delta 7b config card has this problem too, they're all costed at 15 points regardless of pilot initiative.

**Comment by rune-b** [comment]
Thanks for reporting. This will be fixed in the next update
