### ISSUE TITLE
No Galactic Republic Arc-170

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#1704]
![Fly Casual Fault](https://user-images.githubusercontent.com/31852858/55286092-eee5a680-538e-11e9-8a0b-7d4de848dbfc.png)
The above happened in the windows release of the mst recent version after choosing Oddball, 2 veterans, and the I2 generic.

**Comment by rune-b** [comment]
Oddball is the problem. Any game with Oddball results in this error

![image](https://user-images.githubusercontent.com/11047987/55292312-6b0cd800-53e9-11e9-838d-dc6242490f21.png)

**Comment by rune-b** [comment]
Seems it is caused by Odd Ball's name being spelled wrong in the code
