### ISSUE TITLE
In-game mouse-over image sizing issue

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1705]
When hovering the mouse over pilots, ships, and upgrades, it seems like the images take on the dimensions of whatever you hover over first.  So if you hover over a pilot first, then everything uses the dimensions of pilot images.

In this game, I hovered over the pilot first, which looks fine:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 19 35 AM" src="https://user-images.githubusercontent.com/260863/55287367-b75e0680-535c-11e9-8727-4a3bcd9853b2.png">

Now upgrade cards also end up using those dimensions:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 19 44 AM" src="https://user-images.githubusercontent.com/260863/55287374-d2307b00-535c-11e9-88e0-50047bcf5e0d.png">

... and so do ship maneuver dials:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 19 49 AM" src="https://user-images.githubusercontent.com/260863/55287378-e2485a80-535c-11e9-81c6-9ef0a53f0089.png">

**Comment by bitsai** [comment]
In another game, I hovered over ship maneuver dials first, which look fine:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 33 24 AM" src="https://user-images.githubusercontent.com/260863/55287429-921dc800-535d-11e9-94b1-7872644bff36.png">

... but then upgrade cards became small:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 34 20 AM" src="https://user-images.githubusercontent.com/260863/55287440-a5309800-535d-11e9-83bc-1f8535be8146.png">

... and so did pilot cards:

<img width="1280" alt="Screen Shot 2019-03-31 at 2 34 25 AM" src="https://user-images.githubusercontent.com/260863/55287443-b11c5a00-535d-11e9-868a-69141d4cedc1.png">

**Comment by Sandrem** [comment]
> Upgrade-dependent dice-mod ability popups might be borked
https://imgur.com/wnRbSec

**Comment by Sandrem** [comment]
Fixed
