### ISSUE TITLE
Unable to readjust sounds, maneuver speed, etc.   

### ISSUE THREAD

**Issue by bravodingo** [Sandrem/FlyCasual#1706]
Under the options menu, I can no longer adjust maneuver speeds, sounds, etc.  If you click on a previously adjusted setting (I usually have maneuver speed set to a higher level), it will go to the default (v e r y s l o w) and you cannot readjust it.

**Comment by rune-b** [comment]
I get the same. 0.8.0 on android. Animations are now so slow that the game is practically unplayable

**Comment by bravodingo** [comment]
My bad; my issue was on PC (0.8.0), but I also have the issue on Android.

**Comment by vfl68** [comment]
I have the same problem with sound and animation settings with 0.8 on Linux.
Sounds goes to 0 when you try to adjust it and animation goes to 0.05. I edited the prefs file to get other values

**Comment by randy-ja** [comment]
same issue here using 0.8 on linux mint

**Comment by Unclebaby** [comment]
Same. 

OSX v0.8.0.

**Comment by airsik** [comment]
Yup same here as well, windows and on version 8

**Comment by rune-b** [comment]
Workaround for Android where manually editing the settings file doesn't work: 

1. Downgrade  to 0.7.6. 
2. Change the speed/volumes back
3. Install 0.8.0
4. Leave the settings alone...

**Comment by timdar** [comment]
Same issue here on 0.8.0.
After adjusting the Maneuver speed, I can no longer adjust it and the default button is greyed out.

**Comment by Unclebaby** [comment]
The fix (reinstalling 0.7.6, adjusting sliders, reinstalling 0.8.0, leaving
well alone) worked for OSX.

Thanks.

**Comment by randy-ja** [comment]
If you're comfortable editing XML You can also manually edit your prefs file.  You can find its location at this link => https://docs.unity3d.com/ScriptReference/PlayerPrefs.html .  All of the affected fields seem to be decimals between 0 and 1.

**Comment by hmhouk** [comment]
It's the same on Mac.

**Comment by Sandrem** [comment]
Fixed
