### ISSUE TITLE
Unable to use Veteran Instincts

### ISSUE THREAD

**Issue by Rakalakadingding** [Sandrem/FlyCasual#1707]
It seems I am unable to use Veteran Instincts on any pilots. The screenshot was taken from when I tried to attach Veteran Instincts to Darth Vader, nothing else involved. (On First Edition)

![image](https://user-images.githubusercontent.com/49123480/55290533-f65e7d00-5399-11e9-8ea7-58c734ec7399.png)

**Comment by rune-b** [comment]
Thanks for reporting! This bug has already been reported here: #1618, so I'm closing this one.
