### ISSUE TITLE
Error when using sense or Informant on ionized ship

### ISSUE THREAD

**Issue by ScarryHiggy** [Sandrem/FlyCasual#1712]
Seen this a few times, haven't been able to fully reproduce it as yet.

At time when using the sense command (most recently with Anakin) get a debug window and cannot continue.

This is running on macOS 10.14.3 in full screen mode

Happens after selecting target for sense
<img width="1211" alt="Screen Shot 2019-03-31 at 1 46 19 PM" src="https://user-images.githubusercontent.com/49127443/55292745-84e3f600-53bc-11e9-81b0-d5267754b88d.png">

**Comment by rune-b** [comment]
I'm guessing this is because Feroph is ionized and therefore doesn't have a dial to look at

**Comment by ScarryHiggy** [comment]
I will watch for the issue again knowing that information

**Comment by rune-b** [comment]
I got the same bug when using sense on an ionized Ywing

![Screenshot_20190403-010422](https://user-images.githubusercontent.com/11047987/55441871-9986e080-55ac-11e9-870f-fc1c6d10705f.png)

**Comment by rune-b** [comment]
Informant has the same problem

![Screenshot_20190403-084552](https://user-images.githubusercontent.com/11047987/55458409-38333180-55ed-11e9-9bc3-baa72224fe79.png)

**Comment by Sandrem** [comment]
Fixed
