### ISSUE TITLE
Darth Maul (Sith Infiltrator) does not spend force to attack again

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1714]
On performing a bonus attack, did not spend force charges and was able to spend them to modify eyes during that attack.
Was not able to attack again while at 0 force tho.

**Comment by rune-b** [comment]
The timing for spending the force for the extra attack is wrong. They are not spent until the attack is completed (allowing you to use them to modify the attack), but they should be spent before the attack starts
