### ISSUE TITLE
On Android version only, can not select obstacles for seismic charge to destroy

### ISSUE THREAD

**Issue by username2065** [Sandrem/FlyCasual#1722]

**Comment by rune-b** [comment]
I have the same problem on my android phone

**Comment by Monsoonexe** [comment]
Same bug here.  Galaxy S7 Edge.
I get the prompt to select a device to activate, but nothing on the screen is interactable.  The seismic charge tokens do have a red pulsing effect.

**Comment by bitsai** [comment]
I think this is the same issue as https://github.com/Sandrem/FlyCasual/issues/1526; a work-around from that issue:

```
Works if selected "controls: mouse"
```

**Comment by bitsai** [comment]
Closing since it's the same as #1526
