### ISSUE TITLE
Game crashes after utilizing Boba Fett Crew 

### ISSUE THREAD

**Issue by username2065** [Sandrem/FlyCasual#1723]

**Comment by rune-b** [comment]
![Screenshot_20190402-235603](https://user-images.githubusercontent.com/11047987/55438806-f8dff300-55a2-11e9-80b8-660ddf7972d1.png)

**Comment by theoriginalmoser** [comment]
Same thing when placing Boba on Desktop.

**Comment by Spyke114** [comment]
Had him in Bossk and the same thing happened.

**Comment by Pr0xim0** [comment]
Same with Boba Crew on Ketsu at Desktop

**Comment by Sandrem** [comment]
Fixed

**Comment by ZeroElement009** [comment]
I just tried using Boba Fett crew on Moralo Eval and the game keep crashing as described above.

**Comment by rune-b** [comment]
Yes, the fix will be out in the next release
