### ISSUE TITLE
0.8.0 Wedge performs focus after performing red maneuvers

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1729]
I have tested this multiple times.  He performs K-turns then focuses, or Tallon rolls and then focuses.  He has Servo-Motors, Afterburners, and Predator.

**Comment by Thorinblack1** [comment]
Having similar issues with someX wings.Think because of leia

**Comment by rune-b** [comment]
@DejaFu Did you also have Leia in your squad when this happened?

**Comment by DejaFu** [comment]
I did not.

**Comment by rune-b** [comment]
Was he controlled by you or the AI?

**Comment by DejaFu** [comment]
By the AI.  The AI was the Luke, Wedge, Dutch random team.

**Comment by rune-b** [comment]
I just got the same against the Luke, Wedge, Gold squad

Suspecting afterburners is involved, since it allows action while stressed

**Comment by Sandrem** [comment]
Maybe AI gets "choose an action" request, doesn't see any actions that can do (AI doesn't know how to do Boost) and instead to skip - decides to do default "Focus" action?

**Comment by rune-b** [comment]
Could be. I'm not able to reproduce this when I control Wedge

**Comment by rune-b** [comment]
![Screenshot_20190403-022450](https://user-images.githubusercontent.com/11047987/55444710-ffc53080-55b7-11e9-8e0c-b15cdc6e3cce.png)

![Screenshot_20190403-022456](https://user-images.githubusercontent.com/11047987/55444717-081d6b80-55b8-11e9-8600-72273242949a.png)

**Comment by Sandrem** [comment]
Fixed
