### ISSUE TITLE
Boba gets reroll from enemy ship that was removed.

### ISSUE THREAD

**Issue by lydhvin** [Sandrem/FlyCasual#1730]
I had Kyle Katarn at range 1 of Boba Fett. Kyle was destroyed and removed from the board, but when I shot Boba he still rerolled one die. None of my other ships were at range 0-1 of Boba.

**Comment by bravodingo** [comment]
Actually, ships aren't removed until the end of the initiative step...  Was the attacker (after Boba's kill shot) I-5?

**Comment by lydhvin** [comment]
Yes, that makes sense, I think it was Corran Horn that shot Boba. But I am pretty sure the HWK was not visible on the board when I shot at Boba, which changes the issue to the ship being visually removed before being actually removed. Could this be related to the other issue I reported where ships stayed on the board for a round after being reduced to zero hull?

**Comment by Sandrem** [comment]
Please, next time provide screenshot - I need more information to fix this bug.

**Comment by Sandrem** [comment]
I cannot reproduce this problem in 0.9.1-dev
