### ISSUE TITLE
Ships are not removed after being destroyed (by Corran Horn)

### ISSUE THREAD

**Issue by lydhvin** [Sandrem/FlyCasual#1731]
I had two instances of AI-controlled ships not being removed from the game after being reduced to zero hull. They both happened in the same game. The ships were Guri and a Binayre Pirate, I was flying Corran Horn. Both ships were assigned dials and moved the next round, then disappeared at the end of the round. I don't know if they engaged as the didn't have arc on me.

**Comment by Sandrem** [comment]
Please, next time provide screenshot - I need to know another ships/upgrades. Maybe, bug is caused by Simultaneous Attack Rule.

**Comment by Spyke114** [comment]
I had this same issue. I was running Corran Horn with Predator, R4, and FCS. Corran destroyed two ships at two different points in the game using his extra shot ability at i0 and both times those destroyed ships were assigned a dial, moved and didn't get removed until the next engagement.
I'm glad I didn't bump them, but still, that was a surprise to see.

**Comment by Sandrem** [comment]
Fixed

**Comment by DejaFu** [comment]
This issue is occurring again.
![Corran Horn target died, but didn't die](https://user-images.githubusercontent.com/48073298/62991017-469b2080-be0b-11e9-9587-7dfdc7915299.png)
