### ISSUE TITLE
iOS 0.8.0: Can't Select Maneuvers

### ISSUE THREAD

**Issue by hoarybat** [Sandrem/FlyCasual#1734]
In iOS 0.8.0 on an iPhone XS Max, the full interface is now displaying correctly. (Awesome!)

Unfortunately, I can't select a maneuver:

Tapping a ship selects the ship nicely. Tapping again opens the maneuver menu window. Tapping to choose a maneuver results in the maneuver menu closing without having selected the maneuver.

I've tried this on two installations, and both have this issue.

Apologies that I can't write a fix myself!

**Comment by Sandrem** [comment]
Fixed
