### ISSUE TITLE
Anakin and R4-P17 not using ability queue properly

### ISSUE THREAD

**Issue by skotothalamos** [Sandrem/FlyCasual#1736]
Anakin with R4-P17 should have an opportunity to stack both the pilot ability and the droid ability in whatever order the player wishes, allowing an R4-enabled barrel roll or boost to achieve the bullseye/range requirement to then successfully trigger Anakin's ability. The game does not currently allow for this.

**Comment by rune-b** [comment]
Thanks. Anakin's ability is currently not put in the ability queue if there is no enemy ship in range after the maneuver is completed. This was probably done to avoid unnecessary trigger choices in the UI, but as you say, in this case it is necessary. I will fix

**Comment by rune-b** [comment]
Cool combo, by the way :) These Jedi starfighters really have a lot of tricks up their sleeve!
