### ISSUE TITLE
Cannot add ship even if there are enough points left for a Droid 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1743]
![Screenshot_20190403-012658](https://user-images.githubusercontent.com/11047987/55442627-c092e180-55af-11e9-99a2-066e4d25b8f8.png)

**Comment by Sandrem** [comment]
It SE "Edition" class we need to set "minimun point cost" for new factions

**Comment by rune-b** [comment]
I don't really see the need to have this minimum point cost per faction. Can't we just allow the player to add ships as long as points are < 200, up to 8 ships?

**Comment by Sandrem** [comment]
Fixed
