### ISSUE TITLE
Jedi starfighter configuration points should scale with PS

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#1746]
STEPS
1- Create a new republic squad
2- Add two jedi (ie: Anakin and obi wan)
3- Try adding the configuration for them (clt OR 7b)

EXPECTED 
The point value scale with PS, so both pilots should have different points cost for the modifications

CURRENT
The points are the same for all the pilots

**Comment by rune-b** [comment]
Thanks for reporting. This is a known bug and will be fixed in the next update 😊
