### ISSUE TITLE
Adding the pilot "odd ball" does not allow the squad to load

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#1747]
STEPS
1- Create a new republic squad
2- Add "odd ball" as a pilot
3- Start playing with a random opponent

EXPECTED
The pilot loads with its stats

CURRENT 
The pilot does not load, or any of the squad. The game does not break it simply cannot be played since you have no ships

**Comment by rune-b** [comment]
Thanks for reporting. This is a known bug and will be fixed in the next update 😊
