### ISSUE TITLE
Torani Kulda cannot attack Feroph for some reason

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1751]
https://imgur.com/GdCtWTI

**Comment by Sandrem** [comment]
Cannot reproduce, need additional steps:

![image](https://user-images.githubusercontent.com/6347443/55693277-f7edfd80-59b6-11e9-99d1-a17a196b4b06.png)

**Comment by bitsai** [comment]
Appears to be the same issue as https://github.com/Sandrem/FlyCasual/issues/1758, which has the most details on the issue so far.
