### ISSUE TITLE
Sometimes ships are rotated 45 degrees after movement 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#1752]
I have seen this sporadically for a while, but have no idea of how to reproduce it

Possibly the presence of a previously destroyed ship might have something to do with it

**Comment by rune-b** [comment]
Here the fang was rotated after a 1-turn towards the xwing, causing the bases to overlap

![Screenshot_20190404-181009](https://user-images.githubusercontent.com/11047987/55572084-247bee00-5707-11e9-8e96-7a4aecdae476.png)

**Comment by Sandrem** [comment]
I can reproduce this often when movement speed is set to max value. Seems, some problem with calculation of position when frame rate is low or too few positions per movement.

**Comment by rune-b** [comment]
I had movement speed at about 3/4

**Comment by Sandrem** [comment]
Fixed
