### ISSUE TITLE
Black One title not triggering

### ISSUE THREAD

**Issue by Unclebaby** [Sandrem/FlyCasual#1753]
Equipped on Temmin Wexley.

The Slam works but there is no charge count and no option to discard the Disarm token.

**Comment by rune-b** [comment]
It works with generic T70 pilot, so the problem is probably related to Temmin's ability

**Comment by Unclebaby** [comment]
Possibly but not in using it.

I could manoeuvre-free boost-slam and not get the remove disarm option.

But if I did manoeuvre-slam I still didn’t get it.

**Comment by rune-b** [comment]
Yes
However, if you do a 1 speed maneuver which doesn't trigger Temmin's ability at all and then SLAM, then Black One ability works
