### ISSUE TITLE
Anakin ability not proccing after swoop ability

### ISSUE THREAD

**Issue by nickell-andrew** [Sandrem/FlyCasual#1757]
OS: Mac OSX
Version: 0.8.0

The timing window for Anakin's ability, Fine Tuned Controls and Swoop's ability are the same so the player should be able to resolve these abilities in any order.

Anakin should be able to perform a 3 bank ending close to Swoop.
At this point he can queue both his pilot ability, fine tuned controls and swoop's ability.
He can then choose to boost from swoops ability (gaining a stress), 
Use Anakin's ability assuming he meets the range/arc requirements to remove the stress.
At this point he can opt to use or not use fine tuned controls to reposition with a barrel roll and then take his regular action (provided he doesn't skip that for some reason like running over a rock/gas cloud).

Actual result:
Per #1735, Anakin's ability is only proccing on red maneuvers
When both swoop and Anakin conditions are met, both can be used, but you must resolve Anakin's ability first even when you select swoop's ability first (unclear if fixing 1735 will help with this)
Fine Tuned Controls is not offered.

**Comment by rune-b** [comment]
Thanks for the detailed bug report! It is likely that this is the same issue as #1735, but I will have to test it

**Comment by Sandrem** [comment]
Fixed
