### ISSUE TITLE
Ship cannot shoot at a valid target

### ISSUE THREAD

**Issue by nickell-andrew** [Sandrem/FlyCasual#1758]
OS: Mac OSX
Version: 0.8.0

Unsure of perfect reproduction: A bumped ship cannot shoot at a valid target even when it's not on a rock and the target is clearly in arc.

Witnessed this several times while flying 4 fang fighters against AI's 3 ship rebel list. When Fenn Rau was bumped with an enemy ship he would intermittently be unable to shoot other enemy ships in range/arc.

**Comment by Sandrem** [comment]
Please, next time provide screenshot from 2D-view. I got a lot of similar error reports where enemy ship is just out-of-art.

Cannot reproduce:
![image](https://user-images.githubusercontent.com/6347443/55691114-22ce5680-59a3-11e9-9831-574e6b994989.png)

**Comment by nickell-andrew** [comment]
https://photos.app.goo.gl/2Wru9rhAwgi5HBum9

**Comment by nickell-andrew** [comment]
![repro2](https://user-images.githubusercontent.com/10215285/55824695-3c61c200-5ab9-11e9-9f91-1709e0482301.png)

This may not be related to bumping. I had this happen in a subsequent trial with 0 bumps involved.

I'll try to reproduce on OSX later today.

**Comment by nickell-andrew** [comment]
Seems like #1751 might be related.

**Comment by rune-b** [comment]
Here's another example. Android 0.8.0

![Screenshot_20190410-171718](https://user-images.githubusercontent.com/11047987/55891762-69939a80-5bb5-11e9-9d04-c4ac23ccc37f.png)

**Comment by Sandrem** [comment]
Seems that I fixed this in 0.9.2
