### ISSUE TITLE
Decloaking Failure isnt handled correctly

### ISSUE THREAD

**Issue by nickell-andrew** [Sandrem/FlyCasual#1767]
Expected behavior: Player can try all 3 valid positions and choose one if valid, otherwise decloaking fails.

Actual behavior: Player decloaking and electing an invalid position automatically fails without allowing player to check other positions

**Comment by Sandrem** [comment]
> When player has multiple cloaked ships, 1 decloaking failure causes subsequent decloaks to be skipped

**Comment by Sandrem** [comment]
Notes for developers:
Failed decloak skips Systems Phase and another ships cannot activate any systems.
Decloak needs same handling of failed action as already present in Barrel Roll action.

**Comment by Sandrem** [comment]
Fixed
