### ISSUE TITLE
R5-D8 doesn't work at all

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1769]
![Clipboard02](https://user-images.githubusercontent.com/30575527/55687621-b5590080-5977-11e9-90da-515cf486cf43.jpg)

**Comment by rune-b** [comment]
I got the same problem with Wedge and R5-D8. Did you try the regular R5?

**Comment by Nitroxylin** [comment]
>Did you try the regular R5?
With other pilots, but not with Wedge. Gonna try.

**Comment by Sandrem** [comment]
R5-D8 had ability from FE R5 Astromech, fixed.
