### ISSUE TITLE
Moralo Eval pilot ability freezes the game (Desktop)

### ISSUE THREAD

**Issue by Enzayne** [Sandrem/FlyCasual#1771]
After leaving a table edge the YV-666 is placed in reserves as normal.
However, when deploying the ship on the following turn, the game produces an error log and the game is frozen in that mode. The only option is to quit to desktop to reset the issue.

**Comment by Senzorezo** [comment]
Hi.
I think i have the same error :

![image](https://user-images.githubusercontent.com/35725438/56861884-acbb7f00-69a5-11e9-839e-b48902fdf1b9.png)

**Comment by patrickpatrickxwing** [comment]
I was able to skip this step by typing in trigger finish and the game went to the next phase.  The bobafet prompt stayed till the next pop up.

**Comment by Sandrem** [comment]
Fixed

**Comment by stephenolmstead** [comment]
@Sandrem Just a note that I'm experiencing this same bug on the latest build. Can replicate on mobile (Android) and desktop (Mac). Moralo goes to reserve but when you try to replace its says you're overlapping another ship no matter where you pick.
