### ISSUE TITLE
Wolffe can always shoot an addititonal dice on the back

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#1772]
Wolffe should only be able to shoot from the back if he's recovering a charge afer spending it. Right now it always can shoot an additional dice from the back no matter what

**Comment by rune-b** [comment]
I just tried this, but did not get an extra die for the back arc when he didn't have a charge to recover

![image](https://user-images.githubusercontent.com/11047987/55829569-3e567000-5b0f-11e9-9b5a-20d01d33c539.png)

**Comment by Sandrem** [comment]
Cannot reproduce
