### ISSUE TITLE
Ketsu Onyos ability doesn't work at Range 0

### ISSUE THREAD

**Issue by simonvogel** [Sandrem/FlyCasual#1773]
This is still not solved for me.

Compare: https://github.com/Sandrem/FlyCasual/issues/1285

In addition, Maul crews seems to be missing?

**Comment by rune-b** [comment]
Lots of cards are missing, including Maul. That is not a bug, it just takes time to make all the cards

**Comment by rune-b** [comment]
Confirmed. It worked at range 1,but at range 0 the game gets stuck

![Screenshot_20190409-204059](https://user-images.githubusercontent.com/11047987/55826258-e831fe80-5b07-11e9-9bc5-3c052785e635.png)
