### ISSUE TITLE
Ketsu Onyo (Crew) doesn't seem to work

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1774]
Had Constable Zuvio with her on board; had enemy Luke tractored during the activation phase; had him in the firing arc at range 0-2; the ability's prompt to choose a ship didn't even appear.

**Comment by rune-b** [comment]
Just tried this, and it worked for me. Do you have a screenshot?

**Comment by rune-b** [comment]
Then, the turn after I was not prompted to use the ability

![Screenshot_20190409-202105](https://user-images.githubusercontent.com/11047987/55824916-22e66780-5b05-11e9-9b6f-8d6dbbae7617.png)

**Comment by rune-b** [comment]
Got it to trigger again, when the enemy was facing zuvio. I suspect Ketsu is checking the wrong ship's firing arc
![Screenshot_20190409-202600](https://user-images.githubusercontent.com/11047987/55825242-e36c4b00-5b05-11e9-87d7-47aec34d1ca8.png)
