### ISSUE TITLE
Can't adjust sound or animation speeds

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#1778]
When I click on the bar to adjust sound levels or animation speeds, the bar goes almost all the way down automatically but I can't adjust it back up. My sound effects are completely silent but even when I click on the bar to turn it up, nothing happens. I'm using Windows 10.

**Comment by bitsai** [comment]
Same as https://github.com/Sandrem/FlyCasual/issues/1706.  For what it's worth, a known work-around is to download and install an earlier version of the game (0.7.6), adjust the settings, then re-install 0.8.0.

**Comment by Sandrem** [comment]
Fixed
