### ISSUE TITLE
Unable to fire Proton Torpedoes [Bug] [Development version]

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#1779]
Luke and Corran teamed up with Jake Ferryl against the random Two-Tubes brothers, Luke, and a Y-Wing.  Luke and Corran both had Proton Torpedoes, but never got the option to fire them, regardless of range to the target.  Tried at range 1 (which should fail) and at range 2 (which never asked).

**Comment by bitsai** [comment]
Added a fix in https://github.com/Sandrem/FlyCasual/pull/1782
