### ISSUE TITLE
Unable to use Marksman and Greedo (Android version)

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1780]
I was using Bossk with Greedo and Marksman to try to help guarantee that I get some crits through but the game wouldn't allow me to use Marksman any of several times I actually had bullseye lined up.

Other crew/upgrades worked as they should have.

I have a screenshot if needed.

**Comment by rune-b** [comment]
I get the same behavior. 0.8.0 android

![Screenshot_20190411-085555](https://user-images.githubusercontent.com/11047987/55936809-a56f4400-5c37-11e9-8462-3952d86ce9fe.png)

**Comment by rune-b** [comment]
I suspect ut has to do with the 180 arc of the YV. I can't get marksmanship to work with the auzituck either. It worked on a Khiraxz

![Screenshot_20190411-090511](https://user-images.githubusercontent.com/11047987/55937384-23801a80-5c39-11e9-935f-e3d3b2aae6d0.png)

**Comment by Spyke114** [comment]
That's what I was assuming too since it was working on the Kimogila and other ships with V arcs.

**Comment by rune-b** [comment]
Predator doesn't work with the YV either. I think all bullseye abilities are broken for ships with full front arcs

![image](https://user-images.githubusercontent.com/11047987/55989106-d4240380-5ca5-11e9-82f7-d10b8c036b35.png)

**Comment by bitsai** [comment]
@rune-b you're right, the root issue was bullseye arc checks for ships w/ full front arcs!  added a fix (verified on my machine using Bossk) in https://github.com/Sandrem/FlyCasual/pull/1787
