### ISSUE TITLE
Dengar not getting his return shot in destruction. (Android version)

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1781]
As implied, a few games in a row now, Dengar has been shot down by someone in his front arc but didn't get a chance to return fire with his ability.

Also, R4-P8 was never allowed to trigger in spite of those conditions being met as well, but that's a different matter.

**Comment by bitsai** [comment]
Possibly the same as this one from a while back: https://github.com/Sandrem/FlyCasual/issues/795

**Comment by Spyke114** [comment]
Wow, that IS from a while ago! Should I make a separate thing for the Droid issue too?

**Comment by bitsai** [comment]
Oops, sorry I missed that part.  Yeah, I think that's a good idea!

**Comment by Sandrem** [comment]
Fixed
