### ISSUE TITLE
Torani Kulda with Cluster Missiles not getting bonus attack. (Android version)

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1783]
This one hurt. I had Torani with target locks on both people I was going to shoot at and one was in bullseye but I could only take the first shot when both targets were very likely within r1 of each other.

I'll test a bit more to see if it was just that time or just Torani, since I don't use the Clusters as much lately.
I've noticed another issue with Torani, but that's a different ticket.

**Comment by Spyke114** [comment]
So I tested this in self vs mode and confirmed that Torani is NOT getting bonus Cluster Missile attacks while other people are. Rhymer had no issues, at least.

**Comment by Spyke114** [comment]
Note: this was 0.8.0

**Comment by rune-b** [comment]
I get the same in 0.8.1. Second cluster attack does not work for Torani. Works fine with generic Kimoglia.

**Comment by Spyke114** [comment]
This issue has evolved somehow?
So I didn't get the cluster missile bonus attack when firing them on initial engagement, however, I then 4k turned and fired and missed with my primary the next turn and THIS prompted an option to fire Cluster Missiles even though I didn't have a lock. I got 3 attacks that round for Torani: Primary, Cluster 1, and Cluster 2 and Cluster 2 was vs the same target as the primary attack.
