### ISSUE TITLE
Lieutenant Sai's ability doesn't allow him to reinforce off of a friendly reinforce

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#1802]
![Clipboard04](https://user-images.githubusercontent.com/30575527/56098740-3120f300-5f0c-11e9-9d0d-291fe4b71153.jpg)

Lt. Sai coordinates R.A. Chiraneau to reinforce - Chiraneau reinforces - the subsequent action is attributed to Chiraneu again.
Other actions (focus, jam) chain as intended.

**Comment by bitsai** [comment]
Same as https://github.com/Sandrem/FlyCasual/issues/1954
