### ISSUE TITLE
You cannot rotate arc in the already chosen position

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1809]

**Comment by rune-b** [comment]
For ships with double turret arc we don't really need a decision at all since there is only one choice

**Comment by Sandrem** [comment]
But if you already attacked with one of turret arcs, than use Paige Tico to rotate arc and to shoot with VTG - it is important, in what sector non-used arc is pointing.

**Comment by Spyke114** [comment]
But VTG shouldn't proc off of a turret shot? Or do native turrets count as primary now too?

**Comment by Tipoise** [comment]
Actually, according to rules, to rotate an arc, you must choose an other direction. " If a ship rotates a double turret arc indicator, it must select the other two 
standard arcs it was not already selecting."

**Comment by Sandrem** [comment]
Fixed
