### ISSUE TITLE
"R5-D8: Try to Repair" action is available when ship is undamaged

### ISSUE THREAD

**Issue by Liquidlogic1** [Sandrem/FlyCasual#182]
The R5-D8 action shows as one of the possible actions even when the ship has full health and shields.  So far I've tested with the Y-Wing (Horton Salm).

**Comment by Sandrem** [comment]
Not a bug.
Actions are available as usual, even if they has no effect.

For example, ship has stress, Chopper as crew and this droid - ship can use Chopper to suffer damage and activate this droid to fix this damage (even if damage is not present at the moment of action activation).
