### ISSUE TITLE
Pilot ability: Oicunn

### ISSUE THREAD

**Issue by drummkid** [Sandrem/FlyCasual#1859]
Pilot ability is that he can shoot at range 0, not happening in game.

**Comment by rune-b** [comment]
Works for me. Do you remember which other upgrades you used on him?

**Comment by rune-b** [comment]
If it happens again, please take a screenshot

**Comment by drummkid** [comment]
Will do, may have just been my phone.

**Comment by Sandrem** [comment]
Cannot reproduce (maybe bug of older version).
