### ISSUE TITLE
Fel card is incorrect.

### ISSUE THREAD

**Issue by karnophage** [Sandrem/FlyCasual#186]
After selecting Fel as an Interceptor pilot, then hovering over his pilot card, it shows the incorrect card (Alpha squad pilot).

![image](https://user-images.githubusercontent.com/9065745/29864146-6b6de6b6-8da4-11e7-8265-5eeef0fdf951.png)

**Comment by Sandrem** [comment]
This is already fixed in development branch, will be included in next version.
