### ISSUE TITLE
[0.8.1] Crash on Vader linked action Focus > Barrel Roll

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#1860]
<img width="2304" alt="FlyCasual-crash0 8 1" src="https://user-images.githubusercontent.com/1558951/56605355-f38a2d00-65d1-11e9-9bea-edc1f9d968e5.png">

**Comment by rune-b** [comment]
Just tried this with a lone Vader without any upgrades and the linked barrel roll worked fine. Has this happened more than once for you?

Maybe it has to do with a combination of other abilities you were using at the time

**Comment by rune-b** [comment]
Do you remember if you used afterburners on the same turn?

**Comment by NerdimusPrime** [comment]
It only happened the one time, and I don't remember if I used afterburners that turn, sorry.

**Comment by rune-b** [comment]
Ok. I can't see any other abilities in the ships in the screenshot that could interfere either. Let us know if it happens again

**Comment by NerdimusPrime** [comment]
Will do. Thanks.

**Comment by bitsai** [comment]
Re-tested this in latest development branch using Vader, performed Focus -> Barrel Roll both before and after using Afterburners, was not able to reproduce the error, closing for now.
