### ISSUE TITLE
[0.8.1] Crash under Mac OS 10.14.4

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#1861]
I had been playing a game in another desktop space, then switched away to work on something. After being idle in the background for about 10-15 minutes, the game crashed and Mac OS threw this error at me: https://pastebin.com/wmXUG4ik

**Comment by Sandrem** [comment]
I still don't have steps to reproduce and similar reports from another users - so I cannot find and fix this problem. Closed until I will get more details.
