### ISSUE TITLE
barrage rockets does not require bullseye arc to fire

### ISSUE THREAD

**Issue by Razgriz5** [Sandrem/FlyCasual#1871]
Barrage rockets can fire from the front arc, the bullseye arc only affects using the charges for rerolls

**Comment by Sandrem** [comment]
I just checked - my ship successfully attacked enemy ship with Barrage Rockets (enemy ship was in front arc, but not in bullseye arc).
Please, provide steps to reproduce, or screenshots.

**Comment by Sandrem** [comment]
Cannot reproduce
