### ISSUE TITLE
Crash on Tie S/F bump

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#1872]
Not sure what triggered this specific error, other than the AI Tie SF about to bump it's friend.
![Sad SF](https://user-images.githubusercontent.com/33504209/57383860-1d526f00-71e2-11e9-9815-43edd06928be.jpg)

**Comment by bitsai** [comment]
Played multiple hotseat games where I bumped my own TIE/sf's into each other, could not reproduce.
