### ISSUE TITLE
Missing upgrade

### ISSUE THREAD

**Issue by Tex-Wing** [Sandrem/FlyCasual#1873]
Resistance C3-PO crew upgrade is missing from the available options.

**Comment by Sandrem** [comment]
Game is in development, not all content is present.
Please, don't report missing content.

**Comment by Tex-Wing** [comment]
Gotcha.  Apologies.  I'm loving the game, and you've done an amazing job on it.  I was building my list and just noticed the card missing.  Thanks for the follow up.
