### ISSUE TITLE
Corran horn gets weapons disabled even when skipping his bonus attack.

### ISSUE THREAD

**Issue by haukurv** [Sandrem/FlyCasual#1875]
Could be related to issue #1180 
In the first round Corran perfoms his maneuver, then a lock action and finally skips the attack as there are no targets in range. At the end of round I only press the skip button for his bonus attack, but he still gets the weapons disabled token at the start of next round.
I can get a screenshot of this if required, but kinda don't see the point as these steps are all that is required to duplicate :-)

**Comment by starjoe4** [comment]
I also have this issue (renders Corran unusable basically)

**Comment by rune-b** [comment]
Thanks for reporting. I get the same behavior

**Comment by randy-ja** [comment]
Same issue here, I'm on version 0.8.2

**Comment by bitsai** [comment]
@Sandrem oddly, it looks like CorranHornBaseAbility (which is the base class for SE CorranHornAbility) already checks `HostShip.IsAttackPerformed` before assigning the disarm token: https://github.com/Sandrem/FlyCasual/blob/development/Assets/Scripts/Model/Content/FirstEdition/Pilots/EWing/CorranHorn.cs#L62

... so I'm not sure what's going on here.
