### ISSUE TITLE
Greyed options (Skins, Internet, Obstacles)

### ISSUE THREAD

**Issue by kikuyug** [Sandrem/FlyCasual#1878]
Hi,
Maybe the answer is simple but I realized that some options were greyed in the latest versions of the game.
Skins cannot be accessed, as well as the Internet play mode.. I was wondering if this was simply due to the fact that these features are still in development or if there was something I was doing wrong (some settings before launching the game?).

Thanks!

**Comment by Nitroxylin** [comment]
The "still in dev" guess of yours is correct.
