### ISSUE TITLE
The skip button needs a confirm if ships have not yet shot

### ISSUE THREAD

**Issue by Spar7icus** [Sandrem/FlyCasual#1882]
The skip button needs a confirm if ships have not yet shot as it is far too easy to miss out on shots as it is the same button as skipping actions or skipping using modifications, i have just played 2 games and skipped about 7 ships shooting just because of this

**Comment by nickell-andrew** [comment]
Hey @Spar7icus. Do you know me?

**Comment by rune-b** [comment]
Agreed. This has happened to me too many times

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
