### ISSUE TITLE
Code screen Veteran instincts on Whisper v1.0 

### ISSUE THREAD

**Issue by Neodammerung69** [Sandrem/FlyCasual#1883]
Selecting Veteran instincts on Whisper v1.0 triggers a red-letters code screen that won't go away. 
![Screenshot_20190513-114417](https://user-images.githubusercontent.com/43158903/57639205-0068c380-7575-11e9-9b1a-56e62c3a6312.jpg)

**Comment by rune-b** [comment]
Hi
This has already been reported. Closing this as it is a duplicate of #1618
