### ISSUE TITLE
delta-7 ship ability not triggering if landed on a rock

### ISSUE THREAD

**Issue by Spar7icus** [Sandrem/FlyCasual#1884]
delta-7 ship ability not triggering if landed on a rock, rock only stops action step not other actions, also Mace Windu's pilot ability must occur you cannot choose not to regain the extra force

**Comment by nickell-andrew** [comment]
@Spar7icus it's probably better to file the Mace Windu issue as a second bug.

**Comment by rune-b** [comment]
I don't understand what you mean about Mace Windu. There is no choice whether or not to use the ability. Can you give some more details?

**Comment by rune-b** [comment]
I am also able to use the delta7 ability while on a rock. Example:

![image](https://user-images.githubusercontent.com/11047987/57806865-53eb3500-7760-11e9-8a5e-fbda2971ae23.png)

**Comment by Sandrem** [comment]
Cannot reproduce
