### ISSUE TITLE
Internet play

### ISSUE THREAD

**Issue by nbm757** [Sandrem/FlyCasual#1885]
When will internet play be available again? It was nice on the earlier additions and not having it is a major drawback.

**Comment by Sandrem** [comment]
With current level of support from community - I don't have enough free time to develop both offline and online mode. So no online mode for ~ half of year, until I finish offline mode first.
By the way, if each person who ask about online mode, was asking this as my Patreon supporter, then I would have enough resources to keep online mode active =)
