### ISSUE TITLE
Game hangs on crit options

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#1886]
One of the silencers below took two crits from Vader and Duchess (I6 and 5).  Console fire didn't trigger when it came time for it to attack (I4).  Instead, I got this prompt at the end of the next round (or the start of the round after that).  Neither button worked, and subphase finish gave me some error saying this couldn't be skipped.

![crit error](https://user-images.githubusercontent.com/47582934/57900372-43889800-77fc-11e9-811f-09cb27a91408.png)

**Comment by bitsai** [comment]
I think this is identical to https://github.com/Sandrem/FlyCasual/issues/1639
