### ISSUE TITLE
Target that just did a barrel roll not valid target

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#1887]
![arc error](https://user-images.githubusercontent.com/47582934/57912164-54013880-7825-11e9-946b-139f164799d0.png)

The silencer being target just executed a BR and isn't a valid target for Horton despite clearly being in arc.  I've previously seen cases of an attempted post-BR shot that were a little too close to call and so never reported a bug, but this one is pretty obvious.  It reminds me of the bug the phantom had after decloaking quite a while ago.

**Comment by bitsai** [comment]
Appears to be the same issue as https://github.com/Sandrem/FlyCasual/issues/1758, which has the most details on the issue so far.
