### ISSUE TITLE
Daredevil & Vectored Thrusters

### ISSUE THREAD

**Issue by Brion1990** [Sandrem/FlyCasual#1889]
Daredevil triggering when it shouldn't thru RZ-1's Vectored Thrusters. Daredevil states _"While you perform a 'white boost action', you may treat it as red to use the 1 turn left or 1 turn right template instead."_ whereas Vectored Thrusters states that _"After you perform an action, you may perform a red boost action."_ Since the VT boost action starts out as Red, it conflicts with DDs requirement that it starts as White boost that becomes a Red boost action when used.

**Comment by Sandrem** [comment]
Fixed by bitsai
