### ISSUE TITLE
Sunny Bounder only works once.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1896]
I rolled two hits, added a third as normal. Then I used a lock to reroll a hit and got another hit result which should have added a 4th hit, but I didn't get the option.

Sunny's ability says "After you roll -or reroll- dice", if all results are the same then you add a matching result but it doesn't mention a limit.

**Comment by Spyke114** [comment]
Further testing reveals it's simply any time Sunny uses a lock they don't get their effect in the app even though they should. This is regardless of whether they've used it once in the turn or not.

**Comment by bitsai** [comment]
Same as https://github.com/Sandrem/FlyCasual/issues/1667
