### ISSUE TITLE
Captain Jostero's ability only procs once.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1900]
Specifically: say an enemy ship takes damage from a rock and either you don't have arc or you don't want to shoot that ship because a second, better target is going to be available on a bomb detonation that you placed or something.
Joestero gets the option to shoot the first time, but not the second or any after the first of the turn where you hit "Skip".

**Comment by p0lda** [comment]
> Specifically: say an enemy ship takes damage from a rock and either you don't have arc or you don't want to shoot that ship because a second, better target is going to be available on a bomb detonation that you placed or something.
> Joestero gets the option to shoot the first time, but not the second or any after the first of the turn where you hit "Skip".

Each ship can only perform a single "Bonus" attack in a round. Any additional attacks performed outside of your usual engagement time are considered "Bonus" attacks (revenge shot from Dengar, Han Solo gunner ini 7 shot, Veteran Turret Gunner, Quickdraw after losing a shield etc.)

**Comment by Spyke114** [comment]
I'm aware that each ship can only perform one bonus attack per turn, but
the fact that I'm forced to skip the first opportunity for one reason and
then never get to take the one shot on better windows later shouldn't be
how this works since I didn't 'perform a bonus attack' that first time.
