### ISSUE TITLE
Target not legal

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#1908]
Hi, I have had this issue before - where target appears in range and in arc but does not resolve as legal when there's an ally in between.  I confirmed it's range 3 after taking this screenshot.

![Illegal target message](https://user-images.githubusercontent.com/47924192/58635591-41264380-82bc-11e9-9f21-57ded46f7e50.JPG)

**Comment by japandian** [comment]
![Screen Shot 2019-05-30 at 2 17 06 PM](https://user-images.githubusercontent.com/50967633/58658321-e30e5600-82e5-11e9-849a-5c645a25b253.png)

+1 for this, also with the Firespray

**Comment by bitsai** [comment]
Appears to be the same issue as https://github.com/Sandrem/FlyCasual/issues/1758, which has the most details on the issue so far.
