### ISSUE TITLE
Manaroo's ability condition seems to be inversed

### ISSUE THREAD

**Issue by baranidlo** [Sandrem/FlyCasual#1913]
Based on my testing, the ability prompt for Manaroo seems to be displayed only if there is no friendly ship in range 0-1.
And if there is a friendly ship at range 0-1, no prompt is displayed to use Manaroo's ability.

Manaroo at range 2:
![manaroo-range-2](https://user-images.githubusercontent.com/6356856/58758365-d0c92d80-851a-11e9-9e25-c9c776139b92.png)

Manaroo at range 1:
![manaroo-range-1](https://user-images.githubusercontent.com/6356856/58758368-d32b8780-851a-11e9-84b3-fc88be5a7cbc.png)

**Comment by baranidlo** [comment]
Tested version is 0.8.2 on Windows

**Comment by baranidlo** [comment]
After some more testing, it seems that Manaroo's condition occasionally triggers correctly.
But most of the time it's as described in the issue.

**Comment by bitsai** [comment]
I think I can fix this one.

**Comment by baranidlo** [comment]
Awesome, thanks :)
