### ISSUE TITLE
Bump handling doesn't work in case of repeated bump over more turns

### ISSUE THREAD

**Issue by baranidlo** [Sandrem/FlyCasual#1915]
Turn X: multiple ships bump each other on the board. The bumps are handled correctly (losing actions, not being able to fire at bumped ship at range 0).

Turn X+1: ships from previous turn all dial slow maveuvers (e.g. 1 forward) and bump each other again - each the same ship as before.
Now bump handling won't work correctly - ship which bumps is able to take action, and also fire into the bumped ship at range 0.

Tested version: 0.8.2 on Windows.

**Comment by bitsai** [comment]
Tested using a hotseat game in release 0.9.2, bumped 2 ARC-170's into each other and then kept dialing in 1-straight's for both.  For 3 turns in a row, neither got actions nor shots.  Looks like this has been fixed, or need additional steps to reproduce.
