### ISSUE TITLE
[DEVELOPMENT] AI Agile Gunner asks human player to choose arc rotation

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1916]
While playing against an AI Y-wing w/ Ion Cannon Turret + Agile Gunner, at the end of the round Agile Gunner allowed me to pick the turret rotation for the AI ship:

<img width="1280" alt="Screen Shot 2019-06-02 at 7 33 45 PM" src="https://user-images.githubusercontent.com/260863/58770780-23800500-856e-11e9-8d23-2336096d59de.png">

**Comment by Sandrem** [comment]
Seems that owner of subphase is not set (by default, owner of End Step is not set = Player 1)
