### ISSUE TITLE
Corran's Pilot Ability

### ISSUE THREAD

**Issue by AxisofeviI** [Sandrem/FlyCasual#1923]
Corran gains a weapons disabled token regardless of whether he used his ability that turn or not.

Also if Corran kills a ship, that ship stays until the next combat phase. This allows the dead ship to set a move, move, action, bump ships, or drop bombs after death.

Edit: Windows 10, version 0.8.2

**Comment by bitsai** [comment]
FYI, the Disarm token issue was first reported in https://github.com/Sandrem/FlyCasual/issues/1875 (and I have a proposed fix in https://github.com/Sandrem/FlyCasual/pull/1928)

Dead ship issue was first reported in https://github.com/Sandrem/FlyCasual/issues/1731

**Comment by Sandrem** [comment]
Issue with weapons disabled token is fixed.
Issue with ship that is not removed - Duplicate of #1731

Closed.
