### ISSUE TITLE
Dutchess ability poor wording

### ISSUE THREAD

**Issue by AxisofeviI** [Sandrem/FlyCasual#1924]
Dutchess (TIE Striker) is prompted "Use "Dutchess"'s ability" before moving. If you are unstressed this works properly and if you select yes it will skip AA. If you are stressed however selecting yes still skips AA. Dutchess's ability's second part is to be allowed to perform AA when stressed, not to skip it. The prompt should be reworded to "Skip Advanced Ailerlons" so that it is clear no matter if Dutchess is stressed or not.

Windows 10, release 0.8.2

**Comment by bitsai** [comment]
Wording change implemented in https://github.com/Sandrem/FlyCasual/commit/d52a66c3e000b234005f72cb2917bed6f875c0c9#diff-117a05ccfede48e6256e38880cc3f6a3R103

(verified by flying Duchess in a quick test game)
