### ISSUE TITLE
[DEVELOPMENT] New Barrel Roll UI allows overlapping other ships

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1935]
In the lower left hand side of this screenshot, you can see Braylen parked snugly on top of Cassian:

<img width="1280" alt="Screen Shot 2019-06-17 at 11 18 30 PM" src="https://user-images.githubusercontent.com/260863/59658225-e0ba5180-9157-11e9-93a3-c597476e0327.png">

**Comment by Sandrem** [comment]
Fixed
