### ISSUE TITLE
[DEVELOPMENT] New Barrel Roll UI doesn't allow skipping, even if all 3 positions are invalid

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1936]
When none of the 3 possible positions for barrel rolling are valid, the UI doesn't allow skipping, resulting in the game not being able to be advanced:

<img width="1280" alt="Screen Shot 2019-06-19 at 9 52 04 PM" src="https://user-images.githubusercontent.com/260863/59819424-a3330100-92dc-11e9-986f-972b8480f9d5.png">

**Comment by Sandrem** [comment]
Did you try "Forward"? As I see, that position can be valid.

**Comment by bitsai** [comment]
@Sandrem I did try the Forward position; it's really close, but the UI rejected it as invalid as well.

**Comment by Sandrem** [comment]
Fixed

**Comment by Baledin** [comment]
I can start a new bug but this appears to be an issue again in the latest build. Had a close match that had to be called because I couldn't cancel/invalidate the Barrel Roll: Select Position window.
