### ISSUE TITLE
[0.9.0] B-wing that fails *red* barrel roll gains 2 stress instead of 1

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1937]
Can be reproduced by flying Braylen Stramm & Cassian Andor next to each other, then having Braylen do the Focus -> red Barrel Roll linked action, and attempt to barrel roll into Cassian:

<img width="1280" alt="Screen Shot 2019-06-21 at 8 54 09 AM" src="https://user-images.githubusercontent.com/260863/59937522-7f200e80-9407-11e9-87ed-a0a96a324ac8.png">

**Comment by Sandrem** [comment]
Fixed
