### ISSUE TITLE
[0.9.0] After failed barrel roll, UI doesn't advance to next *friendly* ship to be activated

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1938]
After a barrel roll (red or white) is failed, if the next ship in activation order is a friendly ship, the UI stays on the current ship (that just failed a barrel roll) instead of advancing to that friendly ship.  In this game, Braylen just failed a red barrel roll, and the next ship to be activated should be Luke, but the UI stays on Braylen: 

<img width="1280" alt="Screen Shot 2019-06-21 at 8 54 22 AM" src="https://user-images.githubusercontent.com/260863/59937501-70d1f280-9407-11e9-9840-baedd4a3220c.png">

Interestingly, things work fine if the next ship in activation order is an enemy ship.  This issue only occurs if the next ship in activation order is a friendly ship.

**Comment by Sandrem** [comment]
Fixed
