### ISSUE TITLE
App will not install on Android 

### ISSUE THREAD

**Issue by ctsdistrict** [Sandrem/FlyCasual#1941]
Samsung Galaxy S7
Android 8.0.0

"App not installed" 

I even uninstalled the old version. Still the same error.

**Comment by Sandrem** [comment]
I just downloaded and installed it (it just took a lot of time).
I don't know... myabe, you need more free space. App is big.

**Comment by Sandrem** [comment]
Same problem, seems that more of free space helps: https://i.imgur.com/4YCceXD.png

**Comment by ctsdistrict** [comment]
Cleared another ~1gb and it worked now. Thanks.
