### ISSUE TITLE
[0.9.0] Cluster Missiles don't allow a second target if the first was destroyed

### ISSUE THREAD

**Issue by phillipmk** [Sandrem/FlyCasual#1942]
The first major issue is that the "console fire" and "wounded pilot crit" crit causes the screen to lock up when the die is rolled...not sure which one triggered it, but it has happened twice...not sure if both crits were on the same target the first time (I didn't take notes before quitting out). I've also noticed that sometimes cluster missiles don't let you choose a second target if the first one was destroyed (it was definitely in range 1). 
![Screenshot 2019-06-21 21 06 12](https://user-images.githubusercontent.com/52016497/59957741-52044800-9469-11e9-8d57-9c63ec254a54.png)

**Comment by phillipmk** [comment]
Another issue with the separatists is that it locks up after the first round giving the messages "this ship cannot be selected" and "only three ships may be selected" but no ships can, and I'm
![Screenshot 2019-06-21 21 24 42](https://user-images.githubusercontent.com/52016497/59957852-4a45a300-946b-11e9-9b85-69082ae2e9bb.png)
 not even sure what is triggering it. I used the same republic list in other scenarios, so it isn't anything on them.

**Comment by phillipmk** [comment]
I also find that you cannot fire on available targets when you have collided with another target (unless I am missing something). It has happened a few times, but I screencapped this one:
![Screenshot 2019-06-21 21 51 01](https://user-images.githubusercontent.com/52016497/59958072-dc02df80-946e-11e9-9681-68595a0750e0.png)
I should be able to target wedge (Luke is obv. out of arc), right?

**Comment by bitsai** [comment]
Issue from the 2nd comment appears to be due to Kraken: https://github.com/Sandrem/FlyCasual/issues/1795

Issue from the 3rd comment appears to be same as an oft-reported older issue: https://github.com/Sandrem/FlyCasual/issues/1758

(I'll come back and check the 2 issues reported in the 1st comment when I can)

@phillipmk if you can, please open 1 issue for each bug, it makes things much easier to track/manage, thank you :)

**Comment by bitsai** [comment]
The 2 issues from the 1st comment turned out to be tricky to reproduce; for now, I've updated the issue title to highlight them.

**Comment by bitsai** [comment]
First issue from 1st comment appears to be same as https://github.com/Sandrem/FlyCasual/issues/1639

**Comment by Sandrem** [comment]
Fixed
