### ISSUE TITLE
[0.9.0] Decloak over obstacle causes crash

### ISSUE THREAD

**Issue by illick** [Sandrem/FlyCasual#1943]
Decloaking whisper (presumably any phantom) without an acceptable solution in one direction brings up console and won't advance to next action. 

<img width="821" alt="Screen Shot 2019-06-21 at 8 27 27 PM" src="https://user-images.githubusercontent.com/20822020/59958434-e5d31580-9463-11e9-950a-c039e582c0a2.png">
<img width="821" alt="Screen Shot 2019-06-21 at 8 31 40 PM" src="https://user-images.githubusercontent.com/20822020/59958435-e5d31580-9463-11e9-8172-79d79b066267.png">

**Comment by ghost-dad** [comment]
Slightly different instanxe: when trying for an intentionally failed decloak (to keep the token through cloaking devices obligatory  decloak) the decloak direction stated overlaid on top of the menus, with the skip button able to straight up skip turn phases when one should not be able to (e.g. without committing dials).

**Comment by Sandrem** [comment]
Fixed
