### ISSUE TITLE
Debris giving Critical Damage (ver 0.9.0)

### ISSUE THREAD

**Issue by japandian** [Sandrem/FlyCasual#1944]
First, fantastic update!  I noticed a bug when I flew over debris.  The attack die rolled a critical hit and instead of taking the normal damage, I received a Crit.

**Comment by Spyke114** [comment]
That's not an issue, that's what debris does normally. Asteroids give proper damage for the roll but debris only gives damage on a crit, which results in a crit.

**Comment by japandian** [comment]
Apologies. I suppose that changed from 1.0.

**Comment by Spyke114** [comment]
No worries, mate. As a neat tip: flying over debris doesn't make you skip your action step like rocks and gas do; it only gives you stress. So if you have some way to take actions while stressed or to remove the stress before the action, then you can still do an action after.
Also, you can shoot from on top of debris, so it's a bit friendlier than rocks if you don't get the crit from it.
