### ISSUE TITLE
ShadowCaster Title Effect (ver 0.9.0)

### ISSUE THREAD

**Issue by japandian** [Sandrem/FlyCasual#1945]
The tractor effect of the ShadowCaster title locks the screen.  You make your selection of which way to barrel roll/boost, and the selection screen stays up.  The game continues through the next attack and then you cannot accept the die results and are stuck, needing to exit the match.  Thanks!

**Comment by bitsai** [comment]
I think this is covered by https://github.com/Sandrem/FlyCasual/issues/1955
