### ISSUE TITLE
[0.90] Bombing bugs

### ISSUE THREAD

**Issue by ghost-dad** [Sandrem/FlyCasual#1947]
1. When dropping or launching a device with a straight template other than 1 forward, the token is placed rotated by 90 degrees. 
2. Constable Zuvio's ability launches the device with a 5 forward template, as if using trajectory simulator.
3. Not unique to this version, but still a notable omission: when dropping a proximity mine on several ships at once, the player does not get a choice of which ship to target (instead the program chooses it based on an unclear priority).

**Comment by Sandrem** [comment]
1) Fixed
2) Fixed
3) Duplicate: https://github.com/Sandrem/FlyCasual/issues/555

Please, next time create separate issues for separate problems, even if they are related.
