### ISSUE TITLE
Norra Wexley and C-3PO

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1951]
> Quick possible bug: not sure C-3PO is interacting properly with the pilot ability of Norra Wexley (ARC-170): Threepio seems to be counting Norra's free Range 1 evade as a rolled evade. Meanwhile, rolling one evade after guessing one doesn't give a free one.

Source: https://www.reddit.com/r/XWingTMG/comments/c3d0w1/fly_casual_version_090/errsex1/

**Comment by bitsai** [comment]
Same as https://github.com/Sandrem/FlyCasual/issues/1901
