### ISSUE TITLE
Moff Jerjerrod gives a lot of stress tokens if boost is failed

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1952]
Source: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/54/?tab=comments#comment-3725484

**Comment by Sandrem** [comment]
> jerjerrod gives infinite stress tokens when you turn into an obstacle with his boost
also if you do the boost with the ship jerjerrod is in first, the other ships won't get to boost. it's as if game treats it as resolved.

Source: Discord, aaannntttzzz#1528

**Comment by bitsai** [comment]
Maybe fixed by https://github.com/Sandrem/FlyCasual/commit/7872938f0a25ca1b38d553f250079e4e6e499eb8?

**Comment by Sandrem** [comment]
I fixed second part of bug-report, "if you do the boost with the ship jerjerrod is in first, the other ships won't get to boost". First part, "jerjerrod gives infinite stress tokens when you turn into an obstacle with his boost", is not fixed yet.

**Comment by bitsai** [comment]
Oops, my bad.  Got a bit too excited :)

**Comment by Sandrem** [comment]
Fixed
