### ISSUE TITLE
Moldy Crow title is not allowing the HWK-290 to retain two focus tokens

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1953]
Source: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/?do=findComment&comment=3725575

**Comment by rune-b** [comment]
Works for me 
![Screenshot_20190624-085108](https://user-images.githubusercontent.com/11047987/59997501-8b9da480-965d-11e9-9f6a-a82b7a7578a4.png)

**Comment by Sandrem** [comment]
Cannot reproduce
