### ISSUE TITLE
Lt. Sai coordinating a reinforce gives both reinforce tokens to target

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1954]
> I found a bug with Sai and a Decimator (patrol leader) where coordinating a reinforce﻿ caused both reinforce tokens to be given﻿ to the Patrol leader after Sai's ability triggered. Sai had the title, in case that helps ﻿reproduce.﻿﻿﻿﻿

https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/?do=findComment&comment=3725653

> I had noticed this before the new release as well so it’s not because of new code. It only happens with the reinforce action and does whether she has the title or not and whether it’s a decimator or a Lambda

**Comment by rune-b** [comment]
Reproduced with Sai and Patrol Leader.

My guess is it has to do with the decision to choose fore or aft reinforce 

![Screenshot_20190624-171912](https://user-images.githubusercontent.com/11047987/60031073-61230a00-96a4-11e9-8d8a-9f062efe2b89.png)
