### ISSUE TITLE
Qi'ra obstacle selection issues

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1956]
> Qi'ra would not allow me to lock an obstacle

Source: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/?do=findComment&comment=3725707

**Comment by rune-b** [comment]
I can not select an obstacle to lock when using touch mode on my phone. Works when using mouse mode. Don't we have a similar bug with seismic charges?

But after locking using mouse mode there is no visual indication of which obstacle is locked

**Comment by Sandrem** [comment]
Fixed
