### ISSUE TITLE
Dengar's charge

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1958]
> Maybe I missed where to do it but I cant seem to spend Dengars charge﻿ for his ability.

Source: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/?do=findComment&comment=3726272

**Comment by rune-b** [comment]
Works for me

![Screenshot_20190624-083243](https://user-images.githubusercontent.com/11047987/59996481-bc300f00-965a-11e9-9021-1146253975c2.png)

**Comment by rune-b** [comment]
Crew Dengar also seems to work 
![Screenshot_20190624-083630](https://user-images.githubusercontent.com/11047987/59996663-3fe9fb80-965b-11e9-90fa-c0e5a19bfa3a.png)

**Comment by Sandrem** [comment]
Cannot reproduce
