### ISSUE TITLE
Outrider didn't trigger to remove red token after moving through obstacle

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1960]
> Outrider didn't trigger for the red token removal after moving through an obstacle. It works when overlapping an obstacle though (Dash had a stress before moving and has just fully executed a 1 right turn).

![image](https://user-images.githubusercontent.com/6347443/59984842-018e1580-9636-11e9-9c5b-9c3301abbdee.png)

Source: Discord, Akrythael#4676

**Comment by rune-b** [comment]
I also get this bug. Maybe related to Dash's ability
