### ISSUE TITLE
Zeb crew

### ISSUE THREAD

**Issue by Sethsquatch1** [Sandrem/FlyCasual#1962]
Flew a game last night and had Norra with zeb crew and intimidation. (one of my favorites irl)
And it said the ship I was touching wasn't a valid target. I appreciate this game so much, thanks for all the hard work!

**Comment by Sandrem** [comment]
Please, next time provide screenshots too.

**Comment by bitsai** [comment]
Same as https://github.com/Sandrem/FlyCasual/issues/1519, closing this one in favor of the older issue (which has screenshots from multiple instances of the issue attached).
