### ISSUE TITLE
Sabine Wren (Crew) causes crash

### ISSUE THREAD

**Issue by SleepyJedi** [Sandrem/FlyCasual#1963]
After bombs detonated and tokens were assigned for Sabine, it crashed. Attached screenshot.
![Untitled](https://user-images.githubusercontent.com/26986510/60047281-2ad29400-967e-11e9-951c-b97d0325aa11.jpg)

**Comment by bitsai** [comment]
Possibly related: https://github.com/Sandrem/FlyCasual/issues/1055

**Comment by Sandrem** [comment]
Bug can be reproduced if ship is destroyed by bomb.
Fixed.
