### ISSUE TITLE
Emon's 3 straight bomb placement... isn't.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1964]
![Screenshot_20190624-151737_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/60049060-7cd5e280-969b-11e9-8b52-5c2a06ebb3a5.jpg)

As can be seen in the screenshot, every time Emon drops a Seismic or a Proton bomb using the 3 straight template, it gets placed with the wrong facing.

From observation, the center of the bomb and the center of the template are lined up, it's just the facing that's incorrect somehow and it's always rotated the same way relative to the ship/template.

Mobile version, 0.9.0. I have not tried this with mines nor Connor nets yet, so I'm unsure if those are similarly effected.

**Comment by Spyke114** [comment]
Oops! I hadn't realized that Ghost-dad had already pretty much reported this issue. My bad.

**Comment by bitsai** [comment]
As mentioned by @Spyke114 (nice catch!), this was previously reported in https://github.com/Sandrem/FlyCasual/issues/1947
