### ISSUE TITLE
Qi'ra not functioning at 100% yet.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#1965]
So I've noticed a few issues with Qi'ra and their interactions with obstacles.
What works:
+ Properly ignores damage and harmful effects of locked bad stuff when running over them.
+ Trick Shot still being applied correctly over locked stuff.

What does not work:
- Enemy ships are still getting an extra dice for the 'obstructed' shot. 99% sure they don't get that when Qi'ra has the rocks locked.

? Cannot boost over obstacles I have locked. This may actually be correct though.

**Comment by Sandrem** [comment]
Fixed
