### ISSUE TITLE
Escape Craft will not deploy

### ISSUE THREAD

**Issue by ChrisStricker** [Sandrem/FlyCasual#1968]
The AI player hit an obstacle with a modified yt-1300 (1 hull left) and docked escape craft (2 hull left).  The yt-1300 lost its last hull and the escape craft deployed.  The game brought up the movement dial for the escape craft and let me select the maneuver (should have been the AI's selection), but the base appeared within the border of the yt-1300's base.

At that point, you could only quit the game.

**Comment by Sandrem** [comment]
Fixed
