### ISSUE TITLE
Torkil Mux missing in V1

### ISSUE THREAD

**Issue by lexsan82** [Sandrem/FlyCasual#1969]
Torkil Mux pilot is missing in V1

**Comment by Sandrem** [comment]
Do you mean "in Wave 1 of Second Edition" or "in First Edition" ?

**Comment by bitsai** [comment]
I saw a Torkil Mux pilot file for SE, but not FE, so will assume this is for FE (until notified otherwise).

**Comment by Sandrem** [comment]
I see this pilot in squad builder in SE mode of Fly Casual.
If this is bug report for FE - then this is known problem. FE mode doesn't have all cards, and priority of them is VERY low. (Only 2% of matches are started in FE mode). Will be added later (maybe...)

Please, don't report missing content. (Exception - missing cards from SE Wave 1, in 0.9.0 we added all cards from this wave).
