### ISSUE TITLE
Ten Numb

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#1971]
> When I used Ten Numbʻs ability (Rebel B-Wing) game provided an error.
> Mac build, my OS is Mojave 10.14.4.

Source: https://www.reddit.com/r/XWingTMG/comments/c3d0w1/fly_casual_version_090/es1tkg9/

**Comment by Sandrem** [comment]
https://i.imgur.com/9qRzQrQ.jpg

**Comment by rune-b** [comment]
I did not getting any errors when using his ability. Screenshot is too blurry to make out which other upgrades were in use

**Comment by bitsai** [comment]
Re-tested this in latest development branch, still was not able to reproduce the error, closing for now.
