### ISSUE TITLE
Feedback Array & Static Discharge Vanes Error

### ISSUE THREAD

**Issue by angelraptor** [Sandrem/FlyCasual#1972]
When I activate static discharge veins after using feedback array, I get this big error.

![image](https://user-images.githubusercontent.com/52229138/60150552-2a81e800-97a7-11e9-9306-3601990c11e7.png)

**Comment by rune-b** [comment]
Works for me

![Screenshot_20190626-084308](https://user-images.githubusercontent.com/11047987/60157238-963b7380-97ee-11e9-8263-a9150319136a.png)

**Comment by rune-b** [comment]
I see captain Jostero was in play. I suspect his ability might be involved since it would trigger off feedback array

**Comment by angelraptor** [comment]
Yeah you're right - I forgot to mention this. It could probably be an error with him. 

In addition, after trying it again I noticed that only the Z-95 took damage. The surrounding ships didn't take any damage. The error may have stopped the sequence of events from happening though.

**Comment by rune-b** [comment]
Do you remember which other upgrades you had on Jostero?

Did he get his free attack before the error appeared?

**Comment by angelraptor** [comment]
He had Cluster Missiles, a shield/hull upgrade, and contraband cybernetics. He didn't use his free attack yet.

**Comment by rune-b** [comment]
Reproduced with naked Jostero and binayre with feedback array and static discharge vanes vs one tie/sf
