### ISSUE TITLE
Seismic Charges detonation cannot select Rigged Cargo Chute Debris Clouds

### ISSUE THREAD

**Issue by zanstarstrike** [Sandrem/FlyCasual#1977]
As title describes, when dropping a debris cloud via the Rigged Cargo Chute upgrade, when a seismic charge detonates I am unable to choose that token (but can choose other asteroids) - literally nothing happens when I click on that token, no error message given or any other signal.

Playing on PC Windows

**Comment by rune-b** [comment]
I got the same behavior on andoid. 0.9.2

**Comment by mirsimko** [comment]
I still get this issue under Linux. Seismic charge cannot detonate loose cargo.

**Comment by rune-b** [comment]
@mirsimko Hi. Are you able to detonate other obstacles? Are you using touch or mouse controls? (There is a known bug with seismic charges and touch controls)
