### ISSUE TITLE
Emon: straight-3 proximity mine token misaligned

### ISSUE THREAD

**Issue by zanstarstrike** [Sandrem/FlyCasual#1978]
When I drop a proximity mine with Emon doing a 3-straight drop, the token is rotated 90 degrees to the left for some reason - not even lining up the nub guides on the token to fit onto the 3 straight template

![3 straight example](https://user-images.githubusercontent.com/52281874/60265541-5036fa80-9929-11e9-9176-cc58d8764936.gif)

**Comment by bitsai** [comment]
Covered by https://github.com/Sandrem/FlyCasual/issues/1947
