### ISSUE TITLE
Multiple ships at range 0 cannot be declared as attackers

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#1988]
![image](https://user-images.githubusercontent.com/20516751/60341820-09d8ae80-99b0-11e9-9ac6-03a05a8841f7.png)
seems there is some kind of bug in this example, captain cardinal cannot attack the tie fighter even though it should be able to. The only explanation i could see is that all the ships are touching and they are inheriting the status?

**Comment by bitsai** [comment]
Thanks for the report!  This is a known issue that is being investigated: https://github.com/Sandrem/FlyCasual/issues/1758
