### ISSUE TITLE
[0.9.1] T-65/T-70 s-foils crash

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1989]
(from FFG forums)

To reproduce, give the AI either a T-60 w/ servomotor s-foils or T-70 w/ integrated s-foils.  When that X-wing is activated the following occurs:

<img width="1280" alt="Screen Shot 2019-06-28 at 8 42 49 AM" src="https://user-images.githubusercontent.com/260863/60354471-20b3dc80-9981-11e9-837f-dd5b10b3c3c7.png">

<img width="1280" alt="Screen Shot 2019-06-28 at 8 42 59 AM" src="https://user-images.githubusercontent.com/260863/60354492-2c9f9e80-9981-11e9-819e-b4ba61dcf490.png">

**Comment by Sandrem** [comment]
Fixed
