### ISSUE TITLE
[0.9.1] Resistance Transport Pod crash (after moving?)

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1990]
From [FFG forums](https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/56/?tab=comments#comment-3730280): ```Plus getting an error with the transport Pods```

![RosePodError thumb jpg ebc74dcb37eb6c79333b9bd4c89f42e3](https://user-images.githubusercontent.com/260863/60354749-c49d8800-9981-11e9-832e-6aa6db404d7d.jpg)

**Comment by bitsai** [comment]
Haven't figured out how to reproduce this yet...

**Comment by Sandrem** [comment]
I don't know to reproduce bug, but highly likely that this bug is caused by the same reason as another reported bugs. I close it as fixed.
