### ISSUE TITLE
[0.9.1] Contraband Cybernetics crash

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1991]
From [FFG forums](https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/56/?tab=comments#comment-3730406): ```Contraband Cybernetics seems unhappy whether you choose to trigger it or not.```

**Comment by bitsai** [comment]
Screenshot from FFG forums:

![pN0bJwn](https://user-images.githubusercontent.com/260863/60362222-36330180-9995-11e9-9c59-afb5acc07fd6.png)

**Comment by bitsai** [comment]
From the new stack trace, I think it's related/identical to https://github.com/Sandrem/FlyCasual/issues/1989

**Comment by Sandrem** [comment]
Same reason, as with S-Foils, fixed.
