### ISSUE TITLE
[0.9.1] Crash when N-1 Ani's ability is skipped

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1992]
From [FFG forums](https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/56/?tab=comments#comment-3730459): ```When I don't use Anakin Ability I've got this.```

Stack trace is more readable if you choose a 2-straight maneuver for Ani.  Attaching my own screenshot to show top of the stack trace.

<img width="1280" alt="Screen Shot 2019-06-28 at 9 26 53 AM" src="https://user-images.githubusercontent.com/260863/60356901-0f6dce80-9987-11e9-9310-221539221e2d.png">

**Comment by Sandrem** [comment]
Same problem as with S-Foils, fixed
