### ISSUE TITLE
Crash Log

### ISSUE THREAD

**Issue by BlueFalconX250** [Sandrem/FlyCasual#1993]
Got some bugs when I tried to set dials on a list. Screenshots here of the top of the error section. 

![Screen Shot 2019-06-28 at 11 06 49 AM](https://user-images.githubusercontent.com/35779761/60359080-303d2080-9995-11e9-97b9-62a209daadfe.png)
![Screen Shot 2019-06-28 at 11 06 37 AM](https://user-images.githubusercontent.com/35779761/60359081-303d2080-9995-11e9-8182-ce798a75071a.png)

**Comment by bitsai** [comment]
I think this is the same as https://github.com/Sandrem/FlyCasual/issues/1989
