### ISSUE TITLE
[0.9.1] Electro-Proton Bomb slots issues

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1996]
From Reddit: ```The Electro-Proton bomb is taking 2 Device Slots + a Mod slot instead of Device + Mod. However, if you have 2 Device slots, fill one, then fill the other with EP-bomb, the upgrades work correctly.```

While testing (I was able to reproduce the issue using a Separatist Bomber), I also found that if the EPB is removed by clicking on it, the Mod slot stays gone.  The Mod slot only comes back if all upgrades are cleared using the CLEAR button at the top.

**Comment by Sandrem** [comment]
Same problem as with Palpatine, fixed
