### ISSUE TITLE
[0.9.1] IG-88D crash when s-looping

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1997]
From FFG forums: ```IG-88D's ability causes a game crash if I just do the 3 S-loop.```

Reproduced (by doing a 3 S-loop, then picking "No changes" when IG-88D's ability triggered):

<img width="1280" alt="Screen Shot 2019-06-28 at 1 18 11 PM" src="https://user-images.githubusercontent.com/260863/60369072-5a97d980-99a7-11e9-8574-c07029d03668.png">

**Comment by Sandrem** [comment]
Same problems as with S-foils, fixed
