### ISSUE TITLE
[0.9.1] Resistance Transport Pod crash (when shooting)

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#1998]
When my BB-8 Transport Pod fired on a TIE fighter this happened:

<img width="1280" alt="Screen Shot 2019-06-28 at 1 28 39 PM" src="https://user-images.githubusercontent.com/260863/60369932-0510fc00-99aa-11e9-95db-2f9b65275dd9.png">

**Comment by Sandrem** [comment]
Fixed
