### ISSUE TITLE
[0.9.1] R.A.C. missing crew - after adding Palpatine

### ISSUE THREAD

**Issue by neadcb** [Sandrem/FlyCasual#2000]
Decimator RAC missing new crew slot if you add Palpatine first.  If you remove Palpatine, only two crew slots are freed up.

**Comment by neadcb** [comment]
Also, in my game the AI was set up with four T70 Blue Squadron Rookie pilots and there was a system error.  Manuevers were chosen, but ships never moved due to errors popping up.  Will replicate and get screen shot.

**Comment by neadcb** [comment]
[Move_error.zip](https://github.com/Sandrem/FlyCasual/files/3341376/Move_error.zip)
8 screen shots.  Tried to get all of error messages from when Blues selected move to when I started my move.

**Comment by bitsai** [comment]
Thanks for the screenshots!  Based on those, the error w/ the T-70's is due to the s-foils, a known issue being tracked here: https://github.com/Sandrem/FlyCasual/issues/1989

**Comment by Sandrem** [comment]
Fixed
