### ISSUE TITLE
[0.9.1.1] Contraband Cybernetics unusable after recharging (with Jabba)

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#2002]
From FFG forums:

`Contraband Cybernetics no longer throws an error but it only works once. If you recharge it with Jabba the Hutt it doesn't work on any subsequent turns - you are not asked if you want to use it, you are told you have illegally selected a red manoeuvre and you can't perform actions.`

**Comment by Sandrem** [comment]
Fixed
