### ISSUE TITLE
Tie Phantom Decloak Fail Freezes Game

### ISSUE THREAD

**Issue by Lord-Eye** [Sandrem/FlyCasual#2005]
Phantom fails a decloak due to an obstacle and the game freezes.  I'll chock it up to a designed feature to force me to fly better, but it'd be nice if I could not have to scrap a game.  Using version 0.9.1.1

**Comment by djogopatrao** [comment]
also occurs on 0.9.2

**Comment by singebete** [comment]
Happens in 0.9.2 no matter the cause for decloak fail. Let 2 games that failed 1 was due to bumping a ship and other due to going off the board.

**Comment by Sandrem** [comment]
Fixed

**Comment by Lord-Eye** [comment]
Version 9.2, tie phantoms still lock up the game if a decloak fails

**Comment by Sandrem** [comment]
@Lord-Eye Because fix is in dev-version, that will be released as 0.9.3

**Comment by djogopatrao** [comment]
fixed a long time ago
