### ISSUE TITLE
Failed barrel roll (from Ketsu tractor beam) crashed game

### ISSUE THREAD

**Issue by FTFup** [Sandrem/FlyCasual#2006]
Ketsu with shadow caster title killed shot down Captain Feroph and gave the second tractor token. When asked if i wanted to barrel roll, i selected Right but that overlapped another ship causing it to fail. Brought up red control text and did not let me select another ship to shoot or move on from this step. 
I was able to use Subphase back which then let me select my second ship to fire. game proceeded normally after that. 
![ketsu error](https://user-images.githubusercontent.com/52437093/60480721-40ccef80-9c50-11e9-8d7c-4962dd588cb0.jpg)

**Comment by Sandrem** [comment]
Fixed
