### ISSUE TITLE
[DEVELOPMENT] ShowTextVersionOfCard NullReferenceException when AI places Luke X-wing

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#2009]
In an AI game (using latest development branch), as soon as AI places Luke's T-65 X-wing, the following crash occurs:

<img width="1280" alt="Screen Shot 2019-07-02 at 8 06 29 PM" src="https://user-images.githubusercontent.com/260863/60560574-2c96fa00-9d05-11e9-9b9a-c7097f188874.png">

**Comment by Sandrem** [comment]
Seems that also you are offline, without cached image of S-Foils.

**Comment by bitsai** [comment]
@Sandrem that's strange; this is on my laptop, which is where I'm typing this as we speak, so internet connectivity is confirmed.  I also verified that images for both open and closed s-foils are available in the game squad builder.  Also confirmed that the following T-65 s-foil image URL's are loading correctly on my machine:

https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_108.png
https://sb-cdn.fantasyflightgames.com/card_images/Card_Upgrade_108b.png

I'm not sure why the game wouldn't be able to re-fetch s-foil images on this laptop.

**Comment by Sandrem** [comment]
Thank you for quick answer. I see, maybe there is another reason.

**Comment by Sandrem** [comment]
I cannot reproduce (internet is on)
![image](https://user-images.githubusercontent.com/6347443/60562806-c4c2cc80-9d61-11e9-8cb4-697fbc446ae1.png)

**Comment by Sandrem** [comment]
I deleted all cached images, internet is on - now I can to reproduce.

**Comment by Sandrem** [comment]
Fixed

**Comment by bitsai** [comment]
Thanks!
