### ISSUE TITLE
Fearless: needs to check forward (not firing) arc

### ISSUE THREAD

**Issue by Dotswarlock** [Sandrem/FlyCasual#2015]
I encountered the following problem with a ship equipped with Fearless having a faceoff with a Falcon at range 1: Fearless did not activate.

The reason (I think): the code must be checking for a "forward firing arc", which the falcon does not have because of its turret.  However, the upgrade card has the following conditions:
- Perform a "forward arc" primary attack
- The attack is range 1
- You are the the defender's "forward arc" (not to be confused with forward firing arc)

Thanks for all your hard work!

**Comment by Sandrem** [comment]
You are right, will be fixed in next update.
