### ISSUE TITLE
Fine Tuned Controls boost over prox mine

### ISSUE THREAD

**Issue by kevinlpedersen** [Sandrem/FlyCasual#2023]
When using the Jedi's ship ability 'fine tuned controls' to do a boost action when sitting on a proximity mine, the game crashes.
<img width="1251" alt="Screenshot 2019-07-07 at 16 49 47" src="https://user-images.githubusercontent.com/482149/60770064-46ef2000-a0d7-11e9-98ca-b9954196af32.png">

**Comment by rune-b** [comment]
I also get this. The Jedi boosts off the mine, rolls for damage and then i crashes

0.9.2 Android

**Comment by Sandrem** [comment]
Fixed
