### ISSUE TITLE
Firesprays Treat Their (Red) 4K as White

### ISSUE THREAD

**Issue by hoarybat** [Sandrem/FlyCasual#2027]
This feels new to 0.9.1.1.

Firespray dial shows 4Ks as red, correctly.
When executing the 4K, the game treats them as white (doesn't incur stress and allows an action).

**Comment by bitsai** [comment]
Tried this out using a Bounty Hunter but wasn't able to reproduce.  Dialed in a 4K on my first turn, and got the stress (and didn't get an action) as expected (see screenshot).  Can you try to reproduce it again, and if you can, include a screenshot and specific steps to reproduce the problem?

<img width="1280" alt="Screen Shot 2019-07-07 at 6 20 39 PM" src="https://user-images.githubusercontent.com/260863/60776917-37c29f00-a0e4-11e9-8290-0cf67feb41c9.png">

**Comment by hoarybat** [comment]
Weird. This was at my parents house a couple of hours ago, on a Mac running 0.9.1.1. I was able to reproduce it twice. I just got home and can't reproduce this bug on my computer, which is also a Mac running 0.9.1.1. I'll take screenshots, etc., the next time I'm at their place.

**Comment by Sandrem** [comment]
In the most of cases, bugs are caused not by ship itself, but by upgrade or abilities of another ships. So, please, always provide screenshot - we need to see squadlist.

**Comment by hoarybat** [comment]
So, I spent an hour trying to reproduce on two separate machines. I couldn't. I remember that the loadout that caused this issue was not something I use normally. I couldn't remember what it was exactly, and have spent the last hour trying different permutations. I swear on my entire ship collection that this was an issue I saw multiple times last week, but I can't make it happen again. :-\

**Comment by bitsai** [comment]
Thank you for taking the time to look into it!  We really appreciate it.  One possibility is that perhaps Boba had Contraband Cybernetics equipped at the time, which may have been what allowed him to take an action even after doing a 4K?

I'm gonna optimistically close this for now, but if you see this again please feel free to re-open.
