### ISSUE TITLE
CLT does not always trigger

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2033]
Sometimes Calibrated Laser Targeting will not trigger, even though the enemy is clearly in bullseye. Possibly this is because closest part of the enemy ship is not in bullseye, but not 100% sure.

**Comment by bitsai** [comment]
My guess is that this was caused by a known, hard-to-reproduce issue that sometimes affects other bulls-eye abilities (#1677) and shooting in general (#1758), and is being looked into.
