### ISSUE TITLE
Anakin (N-1) cannot use ability when stressed

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2034]
If N-1 Anakin is stressed when he tries to use his ability to do a barrel roll (not an action), the game considers it an action and fails it.
As it is not an action, it should not be failed when stressed.

**Comment by ootinni** [comment]
![image](https://user-images.githubusercontent.com/52763171/61008312-12919300-a367-11e9-8492-9506283a1eb7.png)

**Comment by Sandrem** [comment]
Thank you for screenshot of console text.

For developers: seems that HostShip for this action is not set, and some check cannot access ship that tries to do Barrel Rool,
