### ISSUE TITLE
Failed FTC Barrel Roll loses normal Perform Action Step

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2035]
When an Aethersprite tries and fails a FTC maneuver (e.g. blocked barrel roll), it will also lose its Perform Action step

**Comment by ootinni** [comment]
![image](https://user-images.githubusercontent.com/52763171/61008984-14f4ec80-a369-11e9-95a1-392bc32627ca.png)
![image](https://user-images.githubusercontent.com/52763171/61008999-21794500-a369-11e9-89be-2d86c8b8f287.png)
![image](https://user-images.githubusercontent.com/52763171/61009016-30f88e00-a369-11e9-9882-b588e99afc3e.png)

**Comment by bitsai** [comment]
@Sandrem I have been looking at the actions-related code for the last couple of hours and still haven't been able to figure out what's causing this.

What I'm currently stuck on is that the code for both Fine-Tuned Controls and N-1 Anakin's ability uses `HostShip.AskPerformFreeAction`, but when failing a barrel roll using Anakin's ability, you still get your regular action, unlike Fine-Tuned Controls.

if you have time, could you take a look at this one?

**Comment by bitsai** [comment]
Just realized that a failed FTC boost doesn't have the same issue, the problem is specific to FTC barrel rolls only.
