### ISSUE TITLE
Skipping plo koon transfer after agreeing to do it is not working

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#2039]
Plo koon
- when asked if share a token, say yes
- after that when on the select token menu, click skip

EXpected: the game resumes
Current: The screen stays frozen as selecting the ship to transfer

**Comment by bitsai** [comment]
Reproduced; console logs after performing the steps described above:

<img width="1280" alt="Screen Shot 2019-07-11 at 10 05 08 AM" src="https://user-images.githubusercontent.com/260863/61070513-c294e980-a3c3-11e9-8943-f17d4a7d42c8.png">
