### ISSUE TITLE
Deploying Z-95 from Hound's Tooth causes crash

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#2041]
After my Hound's Tooth was destroyed, the docked Z-95 should have deployed, but it caused a crash instead.

<img width="2292" alt="DeployDockedError" src="https://user-images.githubusercontent.com/1558951/61070845-98502580-a3dd-11e9-8f25-f152fe00fbcf.png">

**Comment by Minivanman** [comment]
Not working for me either.  Causes a crash every time.

**Comment by rune-b** [comment]
I get the same. Tested with Trandoshan Slaver with title + pup

![image](https://user-images.githubusercontent.com/11047987/61188768-509ef780-a684-11e9-9bf6-c5bbbb6fe36a.png)

**Comment by Sandrem** [comment]
Fixed
