### ISSUE TITLE
[0.9.1.1] Darth Sidious' coordination asks twice for a benefit

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2048]
![pt8](https://user-images.githubusercontent.com/30575527/61110797-ce021680-a490-11e9-8a1e-d22d3f483e2b.jpg)

Upon using a coordinate action provided by Sidious on a precise hunter (the one at the bottom of the roster), the "get 1 focus or 1 force?" prompt happened twice and yielded results both times.

**Comment by bitsai** [comment]
@Nitroxylin sorry, do you mind trying to reproduce this again and share the steps needed to do so?  I tested using Darth Maul (carrying Darth Sidious) and a Precise Hunter (like your screenshot), but haven't had any luck so far.  The screenshot proves the issue definitely happened, I would just like to be able to reproduce the issue to be confident that any fixes I try are actually working.

While testing, I also found that Darth Sidious doesn't give a Stress to the coordinated ship like he's supposed to; will fix later today.

**Comment by Nitroxylin** [comment]
Trying to reproduce. I think I'm close.

![pt10](https://user-images.githubusercontent.com/30575527/61134213-cf9b0100-a4c7-11e9-8047-701644b90c2b.jpg)

Steps:
 - try to coordinate the hunter while he's stressed (and fail)
 - during the next turn, perform an incomplete blue maneuver with the hunter
 - on Maul's activation, coordinate the hunter; after resolving the coordinated action prompt, this happens
 - both triggers give a benefit; neither adds stress

**Comment by bitsai** [comment]
Thanks for the detailed steps for this and #2052!  They allowed me to reproduce both issues perfectly.

A small re-working of the code for this card should fix both issues (and the lack of stress), it will just take me some time to implement and then test the changes.  Not 100% sure if it will be part of the upcoming 0.9.1.2 release, but if not, it should definitely make it into the next one.  Thanks again for catching these and for the detailed info!
