### ISSUE TITLE
[0.9.1.1] Darth Maul can use secondary weapons on his second attack

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2050]
Tested on Darth Maul with a heavy laser cannon; the second attack can be made with it, despite the ability stating a bonus _primary_ attack.

**Comment by bitsai** [comment]
Just FYI, we're only on release 0.9.1.1, haven't reached 0.9.11 just yet :)

**Comment by bitsai** [comment]
@Nitroxylin could you try to reproduce it again, and provide the exact steps needed to reproduce?  I tried to reproduce the issue using Darth Maul's ability with an HLC, but as shown in the screenshot, the game correctly prevented me from doing so:

<img width="1280" alt="Screen Shot 2019-07-12 at 4 07 28 AM" src="https://user-images.githubusercontent.com/260863/61124212-2fa78e00-a45b-11e9-9dd1-3b20acc0e6a7.png">

**Comment by Nitroxylin** [comment]
Same. TBH, I haven't tried actually _attempting to fire_ the HLC; why the prompt is even there?

**Comment by Sandrem** [comment]
Not a bug, closed.
I will think about changes in this UI.
