### ISSUE TITLE
Biggs ability never triggers?

### ISSUE THREAD

**Issue by Razgriz5** [Sandrem/FlyCasual#2054]
I had wedge and luke alongside biggs. Wedge and Luke were targeted, and Biggs ability never got triggered. Also, I had angled deflectors on biggs and when he was targeted, the reinforce action effects never took place

**Comment by bitsai** [comment]
Hi!  To help us track things, please file separate issues for each problem; I went ahead and created #2056 for the Angled Deflectors problem.

For the problem w/ Biggs' ability, can you reproduce it and if so, could you provide the exact steps needed to do so?  I did a quick test, and his ability triggered as expected (see screenshot below, which I took just after AI Wedge successfully attacked my Luke).  Please note that in Second Edition, Biggs' ability only triggers when an ally is about to take damage, and only if Biggs himself is also in the attacker's arc: https://xwing-miniatures-second-edition.fandom.com/wiki/Biggs_Darklighter

<img width="1280" alt="Screen Shot 2019-07-12 at 3 27 57 PM" src="https://user-images.githubusercontent.com/260863/61161753-226dbc00-a4ba-11e9-86e9-83945c821927.png">

**Comment by bitsai** [comment]
I'm gonna optimistically close this for now, but please feel free to re-open (if you can, screenshots would be tremendously helpful) if you see this again!
