### ISSUE TITLE
Angled Deflectors not working?

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#2056]
From #2054: `Also, I had angled deflectors on biggs and when he was targeted, the reinforce action effects never took place`

**Comment by bitsai** [comment]
@Razgriz5 I just tested Biggs w/ Angled Deflectors vs. AI Wedge, and Angled Deflectors worked as expected.  Can you try to reproduce the problem and share the steps needed to do so?

Please note that Reinforce only cancels a hit/crit result if there are 2 or more uncancelled hit/crit results; if there's exactly 1 uncancelled hit/crit result, it will go right through.

**Comment by bitsai** [comment]
I'm gonna optimistically close this for now, but please feel free to re-open (if you can, screenshots would be tremendously helpful) if you see this again!

**Comment by Razgriz5** [comment]
Sorry! I was away most of the weekend and didn't have a chance to play.
I'll try and recreate the situation again
Ryan Sickles
RMMA LLC
856-589-5551
