### ISSUE TITLE
[0.9.2] Attack and defense dice rolled at same time

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2060]
![pt11](https://user-images.githubusercontent.com/30575527/61175015-216b8600-a5b1-11e9-914f-64f4bacef6fd.jpg)

**Comment by Nitroxylin** [comment]
*And* after that, the attacked ship still got to roll its defense dice *in addition* to those already in the batch.

**Comment by bitsai** [comment]
@Nitroxylin weird!  Is there a way to reliably reproduce the issue?

**Comment by Nitroxylin** [comment]
Not that I know of right now.

**Comment by bitsai** [comment]
Tried a few test games using Cova Nell vs. Black Squadron Ace (both using the same upgrades as shown in the screenshot), no luck reproducing so far.

**Comment by Nitroxylin** [comment]
After analyzing that occurrence, I can say that the intruding batch of defense dice was rolled once and happened to be present in all following rolls that game. These dice followed the physical engine (and were pushed and/or rolled by the newly rolled dice falling onto them).

**Comment by Sandrem** [comment]
This bug happened a long ago in previous versions when some dice-related abilities had wrong flow of code (finish of ability in wrong place, or start of new ability without waiting to resolve first ability). As result, "hide dice" part of code was called in wrong time.
So, I suspect that one of abilities from squadlist was caused this.

**Comment by bitsai** [comment]
I've played against the Vader + Howlrunner + friends AI list from the screenshot multiple times without running into this issue yet, so I think it's probably an ability in the Resistance squad that caused this.

@Nitroxylin if you have time, can you try some more games with that Resistance squad and see if this pops up again?

**Comment by bitsai** [comment]
Given our lack of luck in reproducing this so far, I'm going to (optimistically) close this for now.  If you ever see it pop up again, please feel free to re-open!  The more details we can gather (more screenshots, steps to reproduce, etc.), the more likely it is that we can track this down.
