### ISSUE TITLE
SE Darth Vader (crew) won't allow use when bumped

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2062]
Have a 2.0 decimator with Vader (crew) and I'm bumped on a ship with my arc to the left-right (side arc). I am not allowed to use vader on the bumped enemy ship, which should be allowed.

![cant-select](https://user-images.githubusercontent.com/39878663/61175841-89709b00-a5b6-11e9-9888-dabd61e98532.png)

**Comment by bitsai** [comment]
I was able to reproduce this too (see screenshot).  Seems like it's something specific to the host ship being bumped from the side; the ability works correctly if the host ship is bumped in the front, and also if the target (and the turret) is on the side with no bump.

**Comment by bitsai** [comment]
... and now the ability works when bumped from the side.  I'm not really sure what's happening any more!

<img width="1280" alt="Screen Shot 2019-07-13 at 1 29 07 PM" src="https://user-images.githubusercontent.com/260863/61176253-8fdd2380-a572-11e9-958c-fe951d80b20a.png">

**Comment by pinosante** [comment]
Now it's getting more interesting: I now have a situation where it doesn't even trigger at range 1. I can't select the ship in the side arc (which should be possible). There is no bump...

![no-darth-vader](https://user-images.githubusercontent.com/39878663/61371470-0a6cb280-a895-11e9-8d28-f177091f1ed0.png)

**Comment by ggrabarz** [comment]
I stumbled on similar bug, only the bump was face-to-face TIE\ln on TIE Reaper with printed front primary attack arc weapon. Feroph was unable to use Vader (Crew) on bumped Howlrunner. 

![vader-crew-cannot-select-bumped-ship](https://user-images.githubusercontent.com/22742383/64053821-70cb3d00-cb84-11e9-8233-a8533455fa1c.png)

**Comment by bitsai** [comment]
Tracking this under bumping-related problems meta-issue (#2279).
