### ISSUE TITLE
Skip Systems phase if relevant charges are all spent

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2063]
See title, the game could/should check if you have no devices left to drop or actions to do in the device phase. If so, it could/should skip this phase to speed up play.

**Comment by bitsai** [comment]
The code does make a check and skips the Systems phase if a squad has no Systems phase triggers in the first place.  But I guess as a quality-of-life improvement, the check could be expanded to skip the Systems phase if a squad brought devices, but all charges have been spent.

**Comment by Sandrem** [comment]
Done
