### ISSUE TITLE
IG-88's abilities are no longer shared.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#2069]
Tried a game with IG-88A, IG-88B, and a Tug with IG-88D.  None of the IG-88's had the abilities they should have been granted from the others.  Apparently, this issue had existed before and was resolved, but it is back in 9.2.0.

**Comment by Nitroxylin** [comment]
Did your IG-88 A and B have the IG-2000 title card?

**Comment by DejaFu** [comment]
Hahahaha!  You're right!  I forgot it! :D
