### ISSUE TITLE
Biggs out of arc but forces me to fire at him

### ISSUE THREAD

**Issue by Conzar** [Sandrem/FlyCasual#207]
Greetings, 
  There is a bug with biggs.  My #1 pilot is attacking and is out of arc of #7 biggs.  I am trying to attack #8 but it says I cannot b/c of biggs.  But if I try to attack biggs, it says biggs is out of arc.

See:
* http://imgur.com/a/zuIJn
* http://imgur.com/a/kGiKv

**Comment by Sandrem** [comment]
Fixed.
(FYI: New version will be released of Friday)
