### ISSUE TITLE
[0.9.2] Dynamic Camera annoying if certain abilities are in effect

### ISSUE THREAD

**Issue by Nitroxylin** [Sandrem/FlyCasual#2070]
Proven by attempting to place a bomb as per Finch's and Paige's ability combo after firing. Can't place the bomb in a place you don't see!

**Comment by bitsai** [comment]
Just FYI, as mentioned in the release notes, you can disable the new dynamic camera by going to Options -> Extra from the main menu (I turned it off to speed things up after the first couple of games).

**Comment by Sandrem** [comment]
Thank you. If you will see more abilities, that require to turn off cinematographic camera to use them correctly - inform us. We will disable cinematographic camera for those abilities.

**Comment by cm5089** [comment]
#2082 - raised before I saw this, Network Calculate is practically unusable with the dynamic camera. How about just making it return to the previous view after the animation?

**Comment by ootinni** [comment]
Had a similar issue recently - when using Obi-Wan's ability (do you want to spend 1 Force to regain your Focus token), either on Obi-Wan or on a nearby friendly ship, it would be helpful to be able to see enemy ship arcs.
Not game breaking, but slightly inconvenient. I tried tapping 2D/3D view but you can't scroll the map while you have an active screen prompt (includes Obi-Wan ability, dice rolls, selecting movement..) - I will add this as a separate issue

**Comment by VexingVision** [comment]
The fixed camera is a huge issue for ships with multiple attacks - like a Y-Wing with a Turret and the gunner crew. The first shot locks the camera on the target, making it very, very difficult to aim the second shot, even if you're going for the same target.

**Comment by Sandrem** [comment]
Following changes are done:
If ability requires to select a ship (or few ships) or place a bomb manually (Finch) - then Cinematic Camera is turned off until start of new attack.
If there are any additional situations when Cinematic Camera should be turned off - please, inform me.
