### ISSUE TITLE
Jostero's Bizarre Bonus Attacks

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2076]
So I've noticed a few weird bugs with Jostero that are solely beneficial to the player but still a weird issue.
First off, when his ability triggers, I've been able to use it to shoot at things that were better targets but that also weren't the correct target that triggered the ability to begin with.
I've ALSO noticed that I'll get a free focus action when his ability triggers if I hadn't taken the focus action already in the turn that the ability triggers.

**Comment by bitsai** [comment]
@Spyke114 looking at the code, it doesn't seem to try to limit you to attacking only the ship that triggered Jostero's ability right now.  in other words, right now we're on the honor system here :)

I didn't see any obvious culprits for why you might also get a free Focus action.  Can you try to reproduce the issue, and add screenshots and the steps for reproducing it?

**Comment by Spyke114** [comment]
Sure! I hadn't tested it very much yet, but I'll try to see what might cause it!

**Comment by Spyke114** [comment]
Okay, so I have a pretty good idea of what's going on to cause the free action, but still no idea why it happens.
What's actually going on is that Jostero ends up being given a free action for some reason by the opponent after the bonus shot trigger, even if that opponent was supposed to skip their action.
I'm not yet able to tell if it's only rocks that cause this or not since the game crashed on Jostero shooting in response to a Deadman's Switch damage, but it's not just a free focus that he gets; that's just what the AI was choosing for me.
When you control both players it gives player 2 the option for Jostero's action after the trigger window.

**Comment by bitsai** [comment]
Can you attach screenshots, or at least list out the ships and upgrades for Jostero's squad and the opposing squad?

**Comment by Spyke114** [comment]
How do I add screenshots? Or are those not needed right now?

**Comment by bitsai** [comment]
If you have the screenshot on a computer, it can be added here by opening this page in your browser and just dragging the screenshot into the text field while composing a comment.

**Comment by Spyke114** [comment]
![Screenshot_20190714-140346_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61187796-0b5ad580-a644-11e9-982a-73efad89f049.jpg)

Sorry, I was on my phone, but I switched to desktop mode and figured it out.

**Comment by bitsai** [comment]
Perfect, thanks!  This is a bizarre one indeed with a lot of oddities going on, but I'll do my best.  Will try to fix all of these (and #1900 too) in one go.

**Comment by Spyke114** [comment]
Noice! Thank you for your hard work!
