### ISSUE TITLE
SE Jam token decisions should belong to assigner instead of target

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#2085]
FFG Organized Play just released new rulings for the upcoming Paris System Open.  For Jam:

`
The player whose effect caused the ship to gain the jam token chooses which token to remove, either a green token or breaking a lock, and also specify which green token is removed or which lock is broken.
`

I don't think this is how Jam works at the moment, but I think I know what to do; thankfully Tractor tokens provide a great example of how to give the assigner the relevant decisions.

**Comment by bitsai** [comment]
Sources:

https://www.reddit.com/r/XWingTMG/comments/cdirh6/ffg_op_published_some_rulings_for_paris_sos/
https://www.facebook.com/events/275417006654790/permalink/387292352133921/

**Comment by Sandrem** [comment]
Also we need to check FE rules of the same situation.

**Comment by bitsai** [comment]
@Sandrem good point!  I don't have a copy of FE, but from this Wiki page (which has a screenshot of the FE Jam rule card), it looks like in FE it is the target that chooses:

"When a ship has both a jam token and a focus, evade, or blue target lock token, remove the jam token. Then **that** ship chooses and removes one of its focus, evade, or blue target lock tokens. A ship is "Jammed" if it has a jam token."

I'll be sure to implement both behaviors, based on `Edition.Current`.
