### ISSUE TITLE
"Copy" during squad building allows you to "clone" limited cards

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2088]
Using the "copy" feature in squad building you can make lists with 4x sabine crew or whatever limited card you like.

**Comment by bitsai** [comment]
Yes, technically you can have multiple copies of cards while squad building, but the game will catch and block this when you try to continue (by clicking the "Next Player" or "Start" button).

**Comment by pinosante** [comment]
I think it would be preferred to have the program automatically remove the copies of the card which are illegal, much like yasb 2.0 does. This would be a "feature" I guess.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
