### ISSUE TITLE
Ship Ionized by Disabled Power Regulator still able to choose other maneuvers

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2090]
My VT-49 Decimator in 2.0 had a disabled power regulator and at some point it was at 3 ion. The game correctly stated that my ship was ioned that I could only select a 1-forward move. But somehow, I was able to click on the ship and choose another maneuver. Next turn I was at 4 ion and could repeat it.

**Comment by pinosante** [comment]
Ok, so I have been able to reproduce it. This is how you get around it: when you click another ship during the dial phase, you can select a maneuver from the maneuver-popup-window. But instead of clicking the maneuver, you click on the ship which is ioned. You get the warning for not being able to select a maneuver, but the maneuver-popup-window switched to the new selected ship. And now you can select a move for an ioned ship.

**Comment by Sandrem** [comment]
Fixed
