### ISSUE TITLE
Moff Jerjerrod's ability triggers at the start of the System Phase

### ISSUE THREAD

**Issue by iheartjoo** [Sandrem/FlyCasual#2091]
The text on the card indicates that his ability can be used during the System Phase. Forcing it to happen at the start of the phase reduces the synergy you can get from this card.

**Comment by bitsai** [comment]
@Sandrem what do you suggest as the appropriate fix?  Is it simply changing Jerjerrod to use `HostShip.OnSystemsAbilityActivation` like other System Phase abilities (such as Sense)?

I found the following cards currently also trigger at the start of the System Phase (despite the card text saying "During the System Phase ...", just like Jerjerrod).  Once the necessary fix is determined, I can apply it to them as well.

- Cassian Andor (crew)
- Grand Moff Tarkin
- Informant's Listening Device

**Comment by Sandrem** [comment]
@bitsai Yes, if ability says "during", then this should be done using "HostShip.OnSystemsAbilityActivation" (you must click on ship to activate it's ability, like SE bombs)

Also pay attention: current code creates "System" step if any ship has listener to this event.
To avoid creation of this step if ability cannot be triggered (for example, no charges for it), I used new event OnSystemsAbilityActivationGenerateListeners to subscribe only when ability can be triggered.
At the moment this is done only for SE bombs in this commit:
https://github.com/Sandrem/FlyCasual/commit/ca78c6fb9cfc19860035a377ffef46a14b357d52
