### ISSUE TITLE
Battle Meditation not allowing coordinate

### ISSUE THREAD

**Issue by Razgriz5** [Sandrem/FlyCasual#2092]
Coordinate did not allow targeting bravo flight officer?
![Screenshot (34)](https://user-images.githubusercontent.com/44179089/61324560-b7d1be80-a7e0-11e9-9c3d-7b54f467b410.png)

**Comment by Sandrem** [comment]
Is that ship bumped into you? (I don't see any taken tokens on his panel)
Coordinate says "Choose another friendly ship at range 1–2."

**Comment by Razgriz5** [comment]
It is not. I also tried again from the initial fly out (no bumping and it did not let me coordinate both ships.

**Comment by bitsai** [comment]
Can you try it without Passive Sensors?  As per the card text, when the Passive Sensors charge is inactive that ship cannot be coordinated.

https://xwing-miniatures-second-edition.fandom.com/wiki/Passive_Sensors

**Comment by bitsai** [comment]
Flew the same list, and when I did not spend the Passive Sensors charges, I was able to use Battle Meditation to coordinate Focus actions to both ships:

<img width="1280" alt="Screen Shot 2019-07-16 at 3 45 50 PM" src="https://user-images.githubusercontent.com/260863/61335150-56f6b600-a7e1-11e9-8349-957c1cd174fb.png">

<img width="1280" alt="Screen Shot 2019-07-16 at 3 46 00 PM" src="https://user-images.githubusercontent.com/260863/61335155-59f1a680-a7e1-11e9-8c9a-950fa7a5c071.png">

<img width="1280" alt="Screen Shot 2019-07-16 at 3 46 08 PM" src="https://user-images.githubusercontent.com/260863/61335159-5eb65a80-a7e1-11e9-976b-0f1a96b02c71.png">

<img width="1280" alt="Screen Shot 2019-07-16 at 3 46 42 PM" src="https://user-images.githubusercontent.com/260863/61335171-6675ff00-a7e1-11e9-8423-7438f46dcabb.png">

<img width="1280" alt="Screen Shot 2019-07-16 at 3 46 51 PM" src="https://user-images.githubusercontent.com/260863/61335177-6d9d0d00-a7e1-11e9-80d4-9fa63729aa42.png">

<img width="1280" alt="Screen Shot 2019-07-16 at 3 47 04 PM" src="https://user-images.githubusercontent.com/260863/61335186-7392ee00-a7e1-11e9-869a-add2cb39bfe3.png">

**Comment by Sandrem** [comment]
Seems that this is behavior of Passive Sensors. Thank you for screenshots, otherwise we could spend a lot more time to understand why coordinate didn't work.

Closed.
