### ISSUE TITLE
Game stopped but I don't know why....

### ISSUE THREAD

**Issue by drail14me** [Sandrem/FlyCasual#2094]
Game stopped when it was time for I1 units to shoot. It wasn't frozen, just wouldn't do anything. 

![Screen Shot 2019-07-16 at 6 08 33 PM](https://user-images.githubusercontent.com/38188214/61336169-e908b980-a7f5-11e9-93d6-9f93725b16d9.png)

**Comment by Sandrem** [comment]
Please, next time in similar situation - open console (CTRL + ~) and make screenshot. There can be useful information about last steps of the game.

**Comment by Sandrem** [comment]
But I can see reason from current screenshot - "Kraken" upgrade has a bug that causes stop of the game if it is used by AI (this already fixed in dev-version).
Please, don't use Kraken and Supreme Leader Snoke in AI squads until release of the next update.
