### ISSUE TITLE
[0.9.2] Crash after proton bomb destroys ship

### ISSUE THREAD

**Issue by NerdimusPrime** [Sandrem/FlyCasual#2097]
This happened two games in a row, different AI list in each game. Sabine was crew on the HWK with the bombs, if that matters. Sorry for two pics, but the entire message didn't fit on one.

<img width="2560" alt="FlyCasual_Crash_1_of_2" src="https://user-images.githubusercontent.com/1558951/61396068-df825e80-a894-11e9-9975-9bf2bdef0f9f.png">

<img width="2560" alt="FlyCasual_Crash_2_of_2" src="https://user-images.githubusercontent.com/1558951/61396091-ec06b700-a894-11e9-89fa-13f69b56411b.png">

**Comment by Sandrem** [comment]
Fixed in dev-build

**Comment by NerdimusPrime** [comment]
Sorry for the duplicate issue. I skimmed the open/closed issues list but must have missed it.
