### ISSUE TITLE
Deploy ships only within green area, scroll map while prompt is up

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2105]
Two quality of life issues (neither are serious, just inconvenient):

1) When deploying ships on android, it is possible to drag them outside of the green area, so you get the error message "cannot deploy". On previous versions and on current Windows version the ship will stop moving if you drag it outside the green area. Would be nice if that could happen on Android too (to help with my fat fingers)

2) On Andoird, when system prompts are up (e.g. setting dials, rolling dice, asking about using abilities), you can't scroll the map. Can be inconvenient when trying to decide how to modify dice rolls or fire abilities.

**Comment by DaveSpringer** [comment]
I believe that this is a touch interface issue, not limited to Android. I can reproduce on a generic Windows machine with touch enabled.

**Comment by Sandrem** [comment]
Done
