### ISSUE TITLE
New AI setting up ships off the playmat

### ISSUE THREAD

**Issue by EL-BASTIDO** [Sandrem/FlyCasual#2106]
Whilst playing a game Vs the AI (which was using the Admiral Sloane Shuttle and seven Academy Pilots list), it deployed two of the ships slightly off the playmat.  

This caused all sorts of issues during the first round with how the ships moved, although they all managed to end the turn fully on the mat.  

![Setup1](https://user-images.githubusercontent.com/36958116/61456788-dbbb0e80-a95e-11e9-83d9-f51643660583.PNG)

**Comment by Sandrem** [comment]
Fixed
