### ISSUE TITLE
Boba Fett Crew

### ISSUE THREAD

**Issue by tamebullgames** [Sandrem/FlyCasual#2109]
Can't place a ship with Boba Fett crew without massive errors.

**Comment by Sandrem** [comment]
Screenshots? What OS do you use?

**Comment by Sandrem** [comment]
Nevermind, I found duplicate of this issue with required details.
Please, provide more details next time when you report a bug.

Closed as duplicate of https://github.com/Sandrem/FlyCasual/issues/1723
