### ISSUE TITLE
Bug with OS-1 Arsenal Loadout plus two-slot missiles

### ISSUE THREAD

**Issue by gausebeck** [Sandrem/FlyCasual#2113]
When I build a squadron containing an Alpha-class Star Wing with configuration OS-1 Arsenal Loadout and a two-slot missile (Barrage Rockets or Diamond-Boron Missiles), I can't successfully enter a game with the squadron.  When I start a game with the squadron I get the message `An error occurred during creation of squadron 'Autosave (Player 1)'` and my side has no ships.  If I later try to load the squadron from the Squad interface I get the message `An error occurred during the creation of squadron 'Autosave (Player 1).json'`.

**Comment by Sandrem** [comment]
Closed as duplicate of https://github.com/Sandrem/FlyCasual/issues/1742
