### ISSUE TITLE
1st Edition Push The Limit with TIE Advanced Prototype

### ISSUE THREAD

**Issue by JeffCookHAN** [Sandrem/FlyCasual#2117]
When executing an action with the TIE advanced with PtL, and error, throws each time. See attached images for use with the Inquisitor, [errorInquisitor.jpg] and with Baron of the Empire, [TIE_adv_Prototype_PtL_Error/jpg] in the second case it was possible to close the error console and continue the game, but the next round after the baron's standard action another error which prevented further progress. [TIE_adv_Prototype_PtL_Error2/jpg]
![errorInquisitor](https://user-images.githubusercontent.com/29730639/61653227-1d7aea80-acba-11e9-95cb-b4de5aefd767.jpg)
![TIE_adv_Prototype_PtL_Error](https://user-images.githubusercontent.com/29730639/61653228-1e138100-acba-11e9-83f7-310cbeb21796.jpg)
![TIE_adv_Prototype_PtL_Error2](https://user-images.githubusercontent.com/29730639/61653229-1e138100-acba-11e9-8ab9-79fc739f8a7d.jpg)

**Comment by Sandrem** [comment]
Bug in loading of image of card's image in UI - fixed in dev branch.
