### ISSUE TITLE
Endless Autopilot Drones

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2125]
I was just in a match using Han in the Scum Falcon with title and an Autopilot Drone. Several things happened that I wasn't expecting.
1- I started undocked and kept bumping until the charges were gone. I docked in the system phase where I lost the last charge.
The drone then exploded.
The drone is only supposed to blow if it's not docked after activation, so there's a thing. 
(I subtracted the damage from the drone's shields. If it's going to bug then I'm deducting it from it's own health)

2- I deployed the drone (which was no longer exploding, so at least it was only the once) the next turn. It survived by virtue of not being shot at but also didn't explode.
The next turn, Han was nowhere near the drone but had the option to deploy the drone again, and so I did.
The original disappeared from the board and Mr red text error window popped up to let me know it didn't like what I just did but it wasn't stopping the game yet. It was the drone's turn and it did the maneuver I dialed in during planning but from the selected guide of the Falcon (I chose rear). Turn progressed as normal otherwise, just obscured by code box.
I did the same thing next turn: deployed the drone again from Han.

Not sure if this was related, but the game *did* ask twice about docking: once for drone and once for Han. I said yes to both even though it was already docked when Han was asked.
(Game ended by Jostero Deadman's Switch soft lock)

**Comment by Spyke114** [comment]
![Screenshot_20190724-185201_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61835380-72993680-ae49-11e9-99e2-6c2d6d6c7e06.jpg)

If this helps I can take more.

**Comment by Spyke114** [comment]
![Screenshot_20190725-091252_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61879262-b713e900-aec0-11e9-8c54-c0ed74a1636d.jpg)
Another issue I've found is that the Falcon, in doing this, could use Escape Craft shields without the craft being docked

**Comment by Spyke114** [comment]
![Screenshot_20190725-091419_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61879375-eaef0e80-aec0-11e9-965a-1ebde66e4182.jpg)
![Screenshot_20190725-091428_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61879391-f0e4ef80-aec0-11e9-877e-674eb14d60f6.jpg)

**Comment by Sandrem** [comment]
Fixed
