### ISSUE TITLE
Skin selection crash?

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2126]
![Screenshot_20190725-123255_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61891828-8dff5280-aed8-11e9-9a6f-3fa33952600d.jpg)
![Screenshot_20190725-123306_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/61891836-935c9d00-aed8-11e9-8197-9549fca2d025.jpg)
I'm guessing this has to do with Asajj since she didn't load when the others did?

Literally all I did to cause this was build the squad and then hit skins. Not sure what's going on with it though.

**Comment by bitsai** [comment]
This is a weird one!  I tried to reproduce in the current development branch by building the same squad then hitting Skins, but didn't encounter the error.  Thought maybe it was a network issue, but it looks like ship skins are packaged with the game code, so that shouldn't be it.

Are you still seeing this issue?  Which version of the game are you using?  Which platform (Android, Windows, Mac, etc.)?

**Comment by Spyke114** [comment]
I'm on latest version using Android.
It still happens when I load my squad, which speaking of, I misspoke a bit in op. I didn't build it, I loaded it since I had already built it in previous versions.

I'll try building it from scratch instead soon and will close if a fresh build fixes it.

**Comment by Spyke114** [comment]
Fresh build works just fine. Closing issue as a mystery and hopefully just something caused by loading a list from before the points/equipment changes.

**Comment by bitsai** [comment]
Thank you for following up so quickly!

**Comment by Spyke114** [comment]
Would have been faster if I hadn't been playing a match with the list to see if it was worth trying irl again.

Also, sorry I didn't test further before opening this. ^^;

**Comment by bitsai** [comment]
No problem at all :)

**Comment by Sandrem** [comment]
I found way to reproduce this bug.
1) Create new skin.
2) Use this skin in squad
3) Delete new skin
4) Load squad with this skin and switch to Skins
