### ISSUE TITLE
AI Kraken

### ISSUE THREAD

**Issue by vans11** [Sandrem/FlyCasual#2135]
Played through a game in hotseat with Kraken working fine on Captain Sear. Then played the exact same squad in an AI vs AI game and I think Kraken is bugged. The AI does not select three ships to not lose one calculate token, which essentially stops the game. The user actually has control over selection but no way to confirm - which is a shame.

**Comment by Sandrem** [comment]
Was fixed in dev-version. New version will be released in few days.
