### ISSUE TITLE
WHERE IS THE SCORE?

### ISSUE THREAD

**Issue by vans11** [Sandrem/FlyCasual#2136]
Is it just me or is there no score shown in the game, or arbitrary time limit... These would be great additions please.

**Comment by rune-b** [comment]
Showing the score is planned I think.

Time limit is more difficult. What should the limit be? It plays so much faster than in real life that a 75 minute would be kind of pointless

**Comment by vans11** [comment]
Good point, so maybe a turn limit that scales with number of ships on the board. It would imagine that given the number of games online (GSP etc) that it would be fairly straightforward to do some data capture looking at squad size and number of turns played... unfortunately number of turns is not included in ListFortress. How about just the ability for a player to set either a turn limit, say 1-10? and a time limit anywhere from 15 mins to 75 mins, capture the data on how many turns and how long the games take and squad size (a file that players can submit for analytics) and then might get an idea from that?

**Comment by Sandrem** [comment]
In plans. Closed.
