### ISSUE TITLE
Heroic works when rolling a single die 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2137]
Should only trigger if there are 2+ results

Example:
AI using heroic on a single defense result 

![Screenshot_20190728-002719](https://user-images.githubusercontent.com/11047987/62000041-aa64e000-b0ce-11e9-8ede-155a7b4d0224.png)

**Comment by bitsai** [comment]
Is this in release 0.9.2 or the current development branch?  It *should* have been fixed in the current dev branch by an earlier PR (https://github.com/Sandrem/FlyCasual/pull/2075), but I may have missed something.

**Comment by rune-b** [comment]
It was 0.9.2 😊
