### ISSUE TITLE
"Genius" crashes game.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2143]
So this shouldn't be allowed to begin with, which is likely the issue, but if you try dropping a mine device with Genius' effect it causes that command window thing to pop up full of red text.

This event occurs with proximity mines and Connor nets, neither of which should be an option to drop according to "Genius'" ability.

As a side note, the ability confirmation window for "Genius" seems to be the 1.0 edition wording and could maybe be updated?

**Comment by rune-b** [comment]
I just dropped a Proximity Mine with "Genius" in a Lok Revenant and got no error. Do you remember which ship you were using?

**Comment by rune-b** [comment]
Anyway, I have changed it so only Bombs can be selected and updated the description

**Comment by Spyke114** [comment]
![Screenshot_20190730-093548_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/62134822-2ae23700-b2af-11e9-8427-e75e7997e7c2.jpg)
![Screenshot_20190730-094528_Fly Casual X-Wing TMG Simulator](https://user-images.githubusercontent.com/49449213/62134839-32a1db80-b2af-11e9-85e9-7abf0786ea53.jpg)
I was using Nym when I got the error. It doesn't seem to happen with Y Wings, but here's fresh shots of what I was using.

**Comment by rune-b** [comment]
OK. But since this only happens for devices that you shouldn't be able to drop anyways I'm going to assume that the problem will disappear now that I've restricted his ability to only Bombs :)

**Comment by Spyke114** [comment]
Seems fair to me! :P
That was about the fix I was expecting would be easiest too, so thanks again for your work on these!
