### ISSUE TITLE
Boba Crew crashes game on desktop

### ISSUE THREAD

**Issue by ZeroElement009** [Sandrem/FlyCasual#2145]
![image](https://user-images.githubusercontent.com/53500768/62177991-19cc1100-b315-11e9-81ca-e33e98fb9d26.png)

When I go to place a ship at range 0 of an obstacle the game crashes when using Boba Crew, The ship I have him on is Moralo Eval

**Comment by bitsai** [comment]
I'm happy to report that this is already fixed in the current development branch, and will be resolved in the upcoming release :)
