### ISSUE TITLE
Cloaking Device - failed forced decloak, froze game

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2148]
The cloaking device on my Quadjumper failed before the planning phase. I chose to decloak into an asteroid (in this case: Left 2) to stay cloaked, which correctly failed the action.

This has now frozen the game.

![image](https://user-images.githubusercontent.com/28895989/62312541-b7971b80-b48e-11e9-8007-811ab27aa17c.png)

**Comment by Sandrem** [comment]
Fixed in dev version, new update will be released soon.
