### ISSUE TITLE
Moff jerjerod should trigger at pilot initiative

### ISSUE THREAD

**Issue by Tipoise** [Sandrem/FlyCasual#2149]
Moff jerjerod ability should trigger when pilot initiative is reach during system phase. Espacially when running whisper and Rear Admiral Chiraneau with jerjerod. Since they are both initiative 5, and jerjerod ability and decloak have same timming window, we should be able to choose which ability trigger first. 
Currently jerjerod always trigger first

**Comment by bitsai** [comment]
Good news!  This has already been reported (#2091), and the fix (#2096) will be part of the next release.
