### ISSUE TITLE
In range 3, partially in arc but target not legal...

### ISSUE THREAD

**Issue by vans11** [Sandrem/FlyCasual#2150]
Having a problem attacking at (I think just) range 3 on boundaries of arcs... Get "Target not legal for the attacker" even though clearly in arc and in range...

![image](https://user-images.githubusercontent.com/47643747/62321836-807b3700-b49b-11e9-9e45-a136cecaa2d9.png)

![image](https://user-images.githubusercontent.com/47643747/62321853-8ffa8000-b49b-11e9-9eb8-10af5386952d.png)

**Comment by Sandrem** [comment]
Seems that size of range ruler object is a bit larger than in-game distance for range 3.
Thank you, I will check this.

**Comment by Sandrem** [comment]
Oh, I see real problem:
Range between ship is measured from base (including clear plastic).
But range of shot is measured from printed card with arc.

So sometimes range to ship is 3, but range in arc for shot is 4.

I plan to improve measurement/messages to avoid such misunderstanding.
