### ISSUE TITLE
Leia Crew

### ISSUE THREAD

**Issue by jakeLGND** [Sandrem/FlyCasual#2152]
Leia Crew is not present on the resistance transport.

**Comment by bitsai** [comment]
Hi!  This is a passion project that we all work on in our spare time.  As such, we aren't able to guarantee that every pilot, ship or upgrade are implemented as soon as they are released.  Leia crew is on our to-do list, and we'll get there as soon as we can (right now there are still Wave 3 content that hasn't been implemented yet).  In the meantime, please refrain from filing missing content as bugs.  Thanks for your patience and understanding!
