### ISSUE TITLE
Proximity Mine not always triggering when deployed under a ship

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2153]
Placing a Proximity mine under more than one ship (in this case of two factions) does not trigger it:

![image](https://user-images.githubusercontent.com/28895989/62418946-d1df1e00-b675-11e9-8f32-e700222f6556.png)

**Comment by rune-b** [comment]
Did you get any errors or did the game simply continue as if nothing happened?

**Comment by VexingVision** [comment]
The game continued normally, and the bomb triggered later when an opposing ship flew over it. (I can't remember if it was the same one that should have been originally triggered).

There were no error messages.

**Comment by VexingVision** [comment]
Apparently this is an issue with proximity mines not always triggering when deployed. They work most of the time, but just now this happened. Again, the game continued normally and the mine triggered normally at a later stage.

Earlier in the same game, a proximity mine placed under an opposing ship exploded immediately.

![image](https://user-images.githubusercontent.com/28895989/62686946-092b3300-b9c6-11e9-83b3-f307c4c39438.png)

**Comment by wavemanns** [comment]
Can confirm this is a very annoying issue especially when using the Hyena Class bombardment drone which can launch mines. I hit another ship but move so low in the initiative that I run over my own mine.

**Comment by rune-b** [comment]
I have tried to reproduce this, but with no success. Do you see any pattern to when it happens? How often does it happen to you?

**Comment by wavemanns** [comment]
It happens more with medium base ships but I would say 2 out of 10 times is
a rough estimate. I've not been able to see a rhyme nor reason for when it
happens correctly and when it fails. I will try and start doing more screen
shots.

**Comment by rune-b** [comment]
In both the screenshots above, the mine is overlapping two other objects. Either two different ships or a ship and an obstacle. Don't know if this is related, but do we know any cases where the mine didn't detonate and it was only overlapping a single ship?

**Comment by wavemanns** [comment]
Yes I have played at least 2 games where only 1 ship is overlapped.

**Comment by rune-b** [comment]
I did a bunch of tests yesterday with a Hyena bomber, but was never able to reproduce this bug. I put the mine under both small, large and medium ships. On ships that were overlapping asteroids and on multiple ships at the same time.

**Comment by VexingVision** [comment]
I have just had this happen:

Ketsu hits Darth Vader and tractors him onto the proxy mine, which does not trigger.

I have never seen a ship fly onto a mine and not trigger, so I'm wildly guessing that it's related to out-of-turn movement/placement.


![image](https://user-images.githubusercontent.com/28895989/69047863-7191a380-09fc-11ea-9c8c-554ee0943d0a.png)

**Comment by rune-b** [comment]
The tractor bug above is probably the same as #2314

**Comment by wavemanns** [comment]
I have 2 screen shots that show a couple more instances.

**Comment by Sandrem** [comment]
Collision detection of mines was fixed.
Tractor bug interaction will be fixed later.
