### ISSUE TITLE
Deathfire can't drop Proximity Mines upon death

### ISSUE THREAD

**Issue by SharpEdgeSoda** [Sandrem/FlyCasual#2156]
I've noticed as I tried desperately to run and drop proximity mines they can't be dropped by Deathfire upon death.

**Comment by bitsai** [comment]
Tried to reproduce this in an Obi-wan vs. Deathfire hot-seat game, but wasn't able to.  When Deathfire died, I got the option for his ability (see screenshot below), and then was able to drop one of his Proximity Mines.  In your game, did Proximity Mines still have charges left?

If you see the issue again, please add screenshots and/or steps we can use to reproduce the issue, those help us out a great deal :) Thanks!

<img width="1280" alt="Screen Shot 2019-08-05 at 6 18 39 PM" src="https://user-images.githubusercontent.com/260863/62504605-2ab1d200-b7ae-11e9-8d11-053ef7f6f3e8.png">
