### ISSUE TITLE
[Sabine crew] bomb kills ship, bombs left to detonate, game crashes

### ISSUE THREAD

**Issue by TVboy89** [Sandrem/FlyCasual#2157]
When I fly multiple bombs with Sabine crew, if a ship is destroyed by a bomb detonating and there are 2+ bombs left to detonate OR there is 1 bomb left but Sabine still has tokens left, the game will either freeze or red letter crash. The game no longer freezes when a ship dies and there is only one bomb left to go on the table (though it does lag) and Sabine crew is dead or inactive.

**Comment by bitsai** [comment]
Good news!  I tested both of the conditions you described (2+ bombs left to detonate when bomb destroys ship, 1 bomb left & Sabine has tokens when bomb destroys ship) in the latest development branch of the game (which contains fixes that will go out in the next release), and there were no crashes or freezes.  So everything should be ship-shape in the next release.

Thank you very much for the detailed report (that helped tremendously with the investigation), and please feel free to re-open this if you do see this in the next release of the game.
