### ISSUE TITLE
Reinforce doesn't work with Firesprays (Boba or Emon)

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2158]
You can take the action, get the token, but nothing happens when defending. It's as if you never took a reinforce, except you get a stress token and no other actions.

Thanks for all the great work, though! :)

**Comment by bitsai** [comment]
I tried to reproduce the issue using a Boba vs. Emon hot-seat game, but Reinforce worked as intended, as far as I can tell.

1. Boba shoots Emon from the front and rolls hit, hit, crit, crit:

<img width="1280" alt="Screen Shot 2019-08-05 at 5 36 55 PM" src="https://user-images.githubusercontent.com/260863/62503322-837e6c00-b7a8-11e9-88cb-1a41c46084b9.png">

2. Emon blanks out on defense:

<img width="1280" alt="Screen Shot 2019-08-05 at 5 37 07 PM" src="https://user-images.githubusercontent.com/260863/62503328-8e390100-b7a8-11e9-8ae2-69b033fdb686.png">

3. Emon was Reinforced in the front, so loses only 3 shields:

<img width="1280" alt="Screen Shot 2019-08-05 at 5 37 17 PM" src="https://user-images.githubusercontent.com/260863/62503352-a7da4880-b7a8-11e9-99a5-05c9a3b2a8c3.png">

Please keep in mind that in 2.0, Reinforce only kicks in if there are 2 or more uncancelled hit/crit results; if there is exactly 1 hit or crit result, that goes straight through.  Also, if the attacker is not in the reinforced arc, or inside both front + rear arcs (flanking), Reinforce won't kick in either.

If you see the issue again, please add screenshots and/or steps we can use to reproduce the issue, those help us out a great deal :)  Thanks!

**Comment by TNG-Wing** [comment]
I see what happened: I wasn't counting damage dealt after the reinforce kicked in. It would be great if you could show the effect of the reinforce when it takes place. Like show it adding an evade result and canceling out a hit/crit. That would make it more obvious and satisfying!

Thanks!
