### ISSUE TITLE
Feature: Make it easier to choose which bomb to detonate first

### ISSUE THREAD

**Issue by TVboy89** [Sandrem/FlyCasual#2159]
I know normally it doesn't really matter which bomb goes off first, but with Sabine crew it's important because of the ability to tractor someone from one bomb onto another. Currently it's very difficult to figure out which bomb # correlates to which bomb on the table, you have to remember what order the bombs were dropped in during the system phase and it gets more confusing when things like delayed fuses are added into it.

**Comment by bitsai** [comment]
Moving to Requested Features wiki (https://github.com/Sandrem/FlyCasual/wiki/Requested-Features).
