### ISSUE TITLE
Ved Foslo's Ability Is Implemented Incorrectly

### ISSUE THREAD

**Issue by elderling** [Sandrem/FlyCasual#2161]
Ved Foslo's ability reads "While you execute a maneuver, you may execute a maneuver of the same bearing and difficulty of a speed 1 higher or lower instead." It is currently implemented such that only maneuvers on the X1's dial may be selected. The ability has no such restriction. Ved should be able to do 1 white turns, 5 & 3 k-turns, and 2 talon rolls.

**Comment by bitsai** [comment]
Fixed by #2166
