### ISSUE TITLE
Unable to do bonus attack after skipping 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2167]
0.9.2 Android

Hera with veteran turret gunner, Ion turret and docked attack shuttle (zeb) 

After shooting with main weapon, two triggers show up

![Screenshot_20190809-175606](https://user-images.githubusercontent.com/11047987/62819375-baf86a00-bb54-11e9-9a0f-3f7186e75a5f.png)

I choose zeb first, but skip doing the attack. I am then not allowed to do the VTG bonus attack instead 
![Screenshot_20190809-175620](https://user-images.githubusercontent.com/11047987/62819381-d19ec100-bb54-11e9-8f0b-224e2712ae90.png)

![Screenshot_20190809-175625](https://user-images.githubusercontent.com/11047987/62819378-c9df1c80-bb54-11e9-9d3e-e7c364b9ca35.png)

**Comment by bitsai** [comment]
Version 0.9.3 was just released, do you mind re-testing to see if it's still happening in the new release?

**Comment by rune-b** [comment]
Will do, once the android build is available

**Comment by bitsai** [comment]
Actually, nevermind!  Tested this in 0.9.3 on my laptop and reproduced the issue thanks to your excellent description.  Looks like the problem is in the Attack Shuttle ship ability, working on a fix now.
