### ISSUE TITLE
0.9.3 Drop DRK template goes the opposite way from intended + measure from range to DRK visualisation would be good.

### ISSUE THREAD

**Issue by vans11** [Sandrem/FlyCasual#2170]
When using the DRK, launching works as expected, but when dropping left turn/bank goes right with respect to 'dropping' from rear guards. Thanks again for the great work on this though! Great to be able to get those ranges TLs.
Minor - but it would be good to have the range ruler measure from the closest object (own ship OR DRK) when visualising the range.

Thanks :D

**Comment by bitsai** [comment]
I think this is one of those things that depends on your perspective :)  Yes, if you are looking from the rear guards the current behavior seems weird.  But it makes more sense if you read the directions as relative to the ship's current heading.  So for example, think of "Turn 3 Left" as "use the 3-turn template and deploy to the left of the ship".

I believe this is consistent with the behavior for other abilities that allow dropping things using templates other than the 1-straight, and changing it up would arguably cause more confusion than it resolves.

W.r.t. range measurement from DRK, I think that'd be cool, but it's more of a feature request than bug, so I've moved it to the Requested Feature wiki (https://github.com/Sandrem/FlyCasual/wiki/Requested-Features).
