### ISSUE TITLE
OS-1 Not allowing re-rolls using target lock when disarmed.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#2171]
I had Luke targeted with a target lock on my Alpha class Star-Wing.  It has the OS-1 upgrade, and had a disarm token.  I fired a Proton Torpedo at him, and the only option I had was "Proton Torpedo" to convert one hit to a crit.  I was not given the option to re-roll any dice by spending the target lock.  The die roll was 3 focus results and one hit.

**Comment by DejaFu** [comment]
During that fight, the fourth proton torpedo I launched, at a Y-Wing where I was in their turret arc, I was given the option to re-roll using my Target Lock.  The rest of the time, I was not given the option.  On that fourth time, there were 3 choices (Focus, Target Lock, Proton Torpedo).  The other times, there was only Proton Torpedo as an option.  Maybe it's a mix up with Focus and Target Lock, where it only gives the Target Lock use option if you have a Focus token.

**Comment by SovietToaster14** [comment]
OS-1 states:
"While you have exactly 1 disarm token, you can still perform Torpedo and Missile attacks against targets you have locked. **_If you do, you cannot spend your lock during the attack_**."

While you have a weapons disabled token you cannot spend your target lock. Most players use Fire-Control System to reroll a single die during this step. While you do not have a weapons disabled token you may spend target locks freely.
