### ISSUE TITLE
Small inaccuracies in obstacle overlap check

### ISSUE THREAD

**Issue by tampermagnitude** [Sandrem/FlyCasual#2174]
I've seen this happen a few times now, AI ship will clearly overlap an obstacle but doesn't register it (ie no dice roll for damage, no stress for debris etc) and will still shoot if on a 'roid.

In the pasted example the Kihraxz landed on the debris after a t-roll and didn't take an extra stress or roll for damage (it had stunned pilot, which also didn't trigger.
![image](https://user-images.githubusercontent.com/10847084/62832919-0cc0f300-bc2e-11e9-8aac-88088b9463c5.png)

**Comment by Sandrem** [comment]
This can be caused not by all, but by some of obstacles.

**Comment by Sandrem** [comment]
Fixed
