### ISSUE TITLE
Sometimes deployed ship doesn't get to attack 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2175]
0.9.3

Haven't been able to reproduce consistently, but several times it has happened to me that a deployed attack shuttle didn't get to attack the round it deployed

![Screenshot_20190813-082006](https://user-images.githubusercontent.com/11047987/62919602-7a426000-bda3-11e9-8d5b-d2538c0c5f05.png)

**Comment by bitsai** [comment]
Have you been able to narrow down the conditions for reproducing this?  When this happened, was the shuttle deployed during the System Phase, or as an Emergency Deploy when the carrier ship got destroyed during the Engagement Phase?  If you're seeing this during the Engagement Phase, keep in mind the following from the rules reference:

"If a ship emergency deploys during the Engagement Phase, it can still engage during that phase at its initiative. **If its initiative has already occurred this round, it cannot engage this phase.**"

(emphasis mine)

**Comment by rune-b** [comment]
It was all regular deployments in the systems phase

Haven't played any docked ships lately, but will try again

**Comment by rune-b** [comment]
I can't reproduce this so I will close this for now
