### ISSUE TITLE
Game asks to use Kanan's ability even when he has no focus tokens

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2183]
0.9.3

![Screenshot_20190814-082123](https://user-images.githubusercontent.com/11047987/62999225-0d47cc80-be6e-11e9-9d9b-8d7e93c22e87.png)

**Comment by bitsai** [comment]
That's a typo; 2E Kanan pilot ability uses Force instead of Focus.  Already fixed in #2181.
