### ISSUE TITLE
Interceptor with Afterburners avoided asteroid effects

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2184]
I flew a TIE Interceptor on top of an asteroid and used Afterburners to boost away from it. The ship did not roll for damage and was able to do its regular action afterwards

**Comment by bitsai** [comment]
Same issue exists with Aethersprite's Fine-Tuned Controls ability.  I caused this with my changes in https://github.com/Sandrem/FlyCasual/pull/2142, while fixing the interaction between Collision Detector and repositioning (boost/barrel roll).  Trying to think of a clean fix...

**Comment by Sandrem** [comment]
@bitsai FYI. about events:
OnMovementExecuted - for abilities that say "when you perform a maneuver ..."
OnMovementFinished - for abilities that say "after you executed/finished a maneuver ..."
OnPositionFinish - when position of ship is changed (after movement or BR/boost). It is used, for example. to check "Is ship off the board? Does ship overlap obstacle?"
