### ISSUE TITLE
Anakin Skywalker can use Fine-Tuned controls to boost off a rock, without rolling damage for the rock.

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2190]

**Comment by pinosante** [comment]
After completing a maneuver which ended on a rock, I was able to immediately use fine-tuned controls, to boost off the rock.  This way I avoided rolling damage for the rock (which should happen).

**Comment by bitsai** [comment]
Fixed in development branch by #2187, will be fixed in next release.
