### ISSUE TITLE
AI ship warped off play area and left the game stuck

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2191]
0.9.3 android 

Interceptor did a 1 turn and bumped another ship. Then the miniature started rotating and then suddenly flew off the map to the right

![Screenshot_20190816-212639](https://user-images.githubusercontent.com/11047987/63193212-27033280-c06d-11e9-9e92-5d29bec1aaa4.png)

**Comment by rune-b** [comment]
Replay

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/3510900/LastReplay.replay.zip)

**Comment by rune-b** [comment]
I tried running the replay on my phone but it crashed

![Screenshot_20190817-003014](https://user-images.githubusercontent.com/11047987/63201611-4eb2c480-c086-11e9-9b7d-462e8637b1fd.png)

**Comment by Sandrem** [comment]
No similar bug reports. Seems, that this bug is not present anymore.
