### ISSUE TITLE
L337 crew card

### ISSUE THREAD

**Issue by SmokeParnell** [Sandrem/FlyCasual#2192]
L337's programming doesn't decrease the bank manuvers on the G1A Starfighter

**Comment by bitsai** [comment]
Tested using G1A w/ L337 crew card equipped, and it appears to be working as intended:

<img width="1280" alt="Screen Shot 2019-08-16 at 3 04 33 PM" src="https://user-images.githubusercontent.com/260863/63200793-6adb4500-c037-11e9-988c-66761a6f80dc.png">

Please keep in mind that the difficulty of bank maneuvers is only decreased if:

1. L337 crew card is flipped while defending, to the "L337's Programming" side
2. the ship has no shields left (as per the card text)
