### ISSUE TITLE
Squadron don't spawn when containing TA-175

### ISSUE THREAD

**Issue by Hratly** [Sandrem/FlyCasual#2196]
When TA 175 is in the squad, nothing shows up when creating a new game. An error said : an error occured when creating the squadron Autosave(Player1).json. When I remove him, everything is fine.

**Comment by Hratly** [comment]
The same thing happened with tv-94. Didin't try the other tactical relay

**Comment by bitsai** [comment]
Duplicate of #2172, fix will be included in next release.
