### ISSUE TITLE
Superweird extra 90 degree turns after not using adaptive ailerons with Duchess

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2197]
I know this is something which is very hard to reproduce. I'm just stating what happened and maybe some others have encountered this as well. I'll try to reproduce tomorrow from memory. This is what happened.

I had Duchess in the bottom left and she was at 45 degrees to the right (after a 1 bank in turn 1). I chose to NOT use the ailerons. I had dialed in a hard turn to the right. What happened, was that Duchess did two hard turns. right after eachother.

Later in the game this exact thing (doing another 1 hard extra) happened with another of my ships (can't remember which) and in the end, happened with Whisper.

It feels like the Aileron popup somehow caused this.

I'm sorry this is such a hard to reproduce bug, I'll try to reproduce when I get the chance.

**Comment by bitsai** [comment]
Thanks to your detailed breakdown, I was able to reproduce the issue by doing the following:

- dial in a 1-hard turn for Duchess
- when presented with the dialog for her ability, Skip the ability
- ship proceeds to do two consecutive 1-hard turns
