### ISSUE TITLE
AI firing while on an asteroid after tractor beam (V0.93)

### ISSUE THREAD

**Issue by Dotswarlock** [Sandrem/FlyCasual#2199]
This bug seems to be present on version 0.93.

Steps to reproduce: fire on an enemy ship with a tractor beam and land them on an asteroid.  When it is the enemy's turn to engage, it can still fire at you.  This was reproduced on 2 separate occasions.

Note 1: unsure if this is caused by the tractor beam or if the AI still fires if it naturally lands on an asteroid.  The tractor beam simply made it easier to reproduce.
Note 2: damage from the asteroid is applied as it should be, so everything else works fine.

Thanks for all your hard work!

**Comment by bitsai** [comment]
Hi, thanks for reporting this in detail.  This is the same as #2173, so I'm going to close this one.
