### ISSUE TITLE
Crash when canceling squad save

### ISSUE THREAD

**Issue by iheartjoo** [Sandrem/FlyCasual#2200]
100% Repro:
+ Launch app
+ New game
+ Vs. AI
+ Choose faction
+ Click "Squad" in upper left
+ Click "Save"
+ Click "Back" in lower left
+ NullReferenceException

**Comment by bitsai** [comment]
Screenshot of stack trace:

<img width="1280" alt="Screen Shot 2019-08-19 at 11 05 03 AM" src="https://user-images.githubusercontent.com/260863/63288325-41a5f900-c271-11e9-91b5-bbf6b4b3fff7.png">
