### ISSUE TITLE
Bumped and the game allowed me to shoot and take an action!

### ISSUE THREAD

**Issue by mishari27** [Sandrem/FlyCasual#2208]
enemy Academy Tie (10) moves in front of my T70 (4) and bumps.

My T70 moves 1 straight and bumps and does not move.

The game allowed me to take an action!
![fly casual bug](https://user-images.githubusercontent.com/54389008/63487662-cf255b00-c4b4-11e9-8b11-feb0df280af8.png)

**Comment by mishari27** [comment]
ok, happened in another game, but my T70 moved and bumped. and still took an action. might be a T70 thing?

**Comment by mishari27** [comment]
it even allowed the bumped ships to attack each other.

**Comment by rune-b** [comment]
I had the same bug now. AI Fang bumps my interceptor. Interceptor does a 1-turn and does not move at all because of the Fang blocking. Interceptor gets to do action and both ships shoot at each other

0.9.5 Android

**Comment by rune-b** [comment]
In both these cases it seems like bumping didn't work properly and the ship's bases actually overlapped a bit after movement is finished

**Comment by bitsai** [comment]
Tracking this under bumping-related problems meta-issue (#2279).
