### ISSUE TITLE
Chardaan Refit available to ships other than A-Wing

### ISSUE THREAD

**Issue by bwakefield27** [Sandrem/FlyCasual#221]
Showing as an available upgrade for Z-95.
![refit_for_z95](https://user-images.githubusercontent.com/31526285/30251969-f05faa60-962f-11e7-9522-7f2c20b1e7d4.png)

**Comment by Sandrem** [comment]
Known problem. List of already present upgrade slots is not regenerated when ship changed to another ship that has this upgrade slot too.
Will be fixed in "Upgrade-Slots-Rework" branch soon.

**Comment by bwakefield27** [comment]
This looks good now!

![z95_norefit](https://user-images.githubusercontent.com/31526285/30280264-ef4ec93a-96d4-11e7-8294-4ad8dd44629f.png)
