### ISSUE TITLE
Feature request: round counter + end of game after X rounds

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2211]
Love the game. Would it be possible to show a round counter somewhere on the screen, showing which round it is? Cherry on the pie would be to have an option in the settings menu which basically ends the game after X rounds. That would help practice for games with a maximum amount of rounds!

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
I cannot give any estimate for this feature. If this is important for you, you can ask this as supporter on Patreon (https://www.patreon.com/Sandrem).
