### ISSUE TITLE
Tractor beam not working as intended

### ISSUE THREAD

**Issue by Senzorezo** [Sandrem/FlyCasual#2212]
Hello.

First time I had this : 

I am at range 1, in the arc, and can't use tractor beam.

![image](https://user-images.githubusercontent.com/35725438/63598454-e13ff000-c5bf-11e9-9ca3-3e548825dcc7.png)

I must be able to make him do a 1-Boost on the asteroid.

Thank you for your work.

**Comment by Sandrem** [comment]
Seems this is because message shows general range between ships, but range to ship in arc is 2.
I plan to change messages to show both general range and range for arcs.
