### ISSUE TITLE
Cova/Leia interaction

### ISSUE THREAD

**Issue by Furryrodian** [Sandrem/FlyCasual#2217]
For Resistance, when you use Leia on Cova Nell and perform a red maneuver, Cova's ability does not trigger and she does not roll extra dice. The rulings I've seen indicate that her red maneuver is in fact revealed as red and then is treated as white, so she should still work even after having the difficulty reduced.

**Comment by bitsai** [comment]
I have an idea why this might be happening, will take a look.
