### ISSUE TITLE
Suggestion: range checker

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2221]
Would it be possible to add a button that allows you to check range to objects without actually selecting them for the current action and maybe also have it show the current arc?
It's not too bad eyeballing things, but I figure this could help in at least some decisions.

(Sorry if this is not the place for this)

**Comment by Sandrem** [comment]
Fow Windows - use right mouse button.
For mobile devices - in plans.

**Comment by Spyke114** [comment]
Thanks! Sorry to clutter then! ^^;
