### ISSUE TITLE
Unable to place a large ship rotated 45 degrees at setup.

### ISSUE THREAD

**Issue by mishari27** [Sandrem/FlyCasual#2223]
The rules allow for large bases to be placed diagonally and have a part of the base outside the setup area as long as it's touching the back edge. FC doesn't allow this as far as I can tell.
![jendon](https://user-images.githubusercontent.com/54389008/63669881-eda49280-c7e3-11e9-809e-82394f2439ae.jpg)

**Comment by Sandrem** [comment]
Known problem, support of this rule in the list of planned features.
