### ISSUE TITLE
AI: Ketsu Onyo, Shadowcaster

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2233]
The AI will always keep its arc behind. Ketsu's and the Caster's abilities proc only when the mobile arc points to the front, and it would be lovely to see the AI prioritizing this.

**Comment by Sandrem** [comment]
The game has > 600 cards of pilots / upgrades.
Special AI for one of two specific cards has very low priority.

Request is moved to list of possible AI improvements.
