### ISSUE TITLE
"Sinker" ability a confusing

### ISSUE THREAD

**Issue by sdcooney** [Sandrem/FlyCasual#2238]
First off, amazing work!  Love the game.  Playing it, I found a bug:

"Sinker" (Galatic Republic ARC-170 pilot) has a pilot ability that reads: "While a friendly ship at range 1-2 in your [front or rear firing arc] performs a primary attack, it may reroll 1 attack die."

After an attack, when the "Sinker" button appears, it has a secondary button "select blank results only." This is a it confusing because I initially thought I could not select a focus result.  Probably not a big priority (because the game functions correctly), but could you add a secondary button "select focus"?

**Comment by Sandrem** [comment]
Oh, I see. Button "Select only blanks and focuses" was shown only for cases, where at least 2 dice can be rerolled - I fixed this.
