### ISSUE TITLE
TIE Reapers` Adaptive Ailerons don't work on stop maneuver directly after deployment.

### ISSUE THREAD

**Issue by ggrabarz** [Sandrem/FlyCasual#2248]
0.9.4 Android 
All Reapers have stop maneuver selected, in Activation Phase the popup with 3 possible Ailerons directions shows before movement as usual, but choosing any doesn't trigger the manvouver.
![reaper-deployed-stop-alerions-1](https://user-images.githubusercontent.com/22742383/64054037-7aa17000-cb85-11e9-9a3f-edd22a656fb6.png)

The stressed ships stay put on second round: 
![reaper-deployed-stop-alerions-2](https://user-images.githubusercontent.com/22742383/64054065-a4f32d80-cb85-11e9-8a36-0c7190c5bf69.png)

**Comment by bitsai** [comment]
Same as #2197, fix will be included in next release.
