### ISSUE TITLE
9.5 crashes when Mannaroo attempts to send Calculate tokens.

### ISSUE THREAD

**Issue by Diemilkweed** [Sandrem/FlyCasual#2259]
IG88D crew on Manaroo.  Took calculate action.  When time came to pass stuff, chose the calculates.  Immediate crash.

**Comment by bitsai** [comment]
Was able to reproduce using the above steps:

<img width="1280" alt="Screen Shot 2019-09-02 at 11 29 23 AM" src="https://user-images.githubusercontent.com/260863/64130097-fc0b2500-cd74-11e9-97ec-9972bc6b4812.png">

<img width="1280" alt="Screen Shot 2019-09-02 at 11 29 15 AM" src="https://user-images.githubusercontent.com/260863/64130106-0af1d780-cd75-11e9-97cd-97861303d2d5.png">
