### ISSUE TITLE
Boost does not work together with Push The Limit and Darth Vader

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#226]
If you boost as your first action, you don't get the option to do Push the Limit, or use Vader's second action

Tested with Darth Vader with Engine Upgrade and Wedge with PTL and Engine Upgrade

**Comment by thordurk91** [comment]
Also doesn't work with A-Wing + PTL + Vectored thrusters. So seems to be an issue with EU returning the subphase. 

Also sidenote EU just seems really off. I am able to boost out of the map and ontop of other large ships and small ships can boost ontop of asteroids. 

Boost out of map, large ship
![image](https://user-images.githubusercontent.com/9085788/30502360-74fb4166-9a55-11e7-8238-127358386a3b.png)
Boost inside a large ship
![image](https://user-images.githubusercontent.com/9085788/30502385-8bc67ec4-9a55-11e7-916e-3ce88a4589b3.png)


Boost off map, small ship
![image](https://user-images.githubusercontent.com/9085788/30502684-c43c5228-9a56-11e7-93e5-2e3c0ac09bac.png)
Boost ontop of asteroids
![image](https://user-images.githubusercontent.com/9085788/30502708-ee5f6f86-9a56-11e7-9c8c-848d74ea290a.png)

It's also not possible to boost over another ship, i.e. the template overlaps but not the final position.

**Comment by Sandrem** [comment]
Seems that ship base collision detection is broken during adding of large ships. Thank you for details.
Did you see my messages about Slack workspace?

**Comment by rune-b** [comment]
Also, if you have push the limit on Soontir Fel and take boost as the second action you don't get the option to take Soontir's free focus token. I assume this is related to the same bug

**Comment by Sandrem** [comment]
Wrong callback calling of Boost action is fixed.
Extra call of callback in Push The Limit is fixed.
