### ISSUE TITLE
Nodin Chavdri card has wrong dimensions 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2262]
0.9.5 Android

![Screenshot_20190903-150309](https://user-images.githubusercontent.com/11047987/64176231-42d44a00-ce5d-11e9-9a27-c83d7926e3a8.png)

**Comment by bitsai** [comment]
Seems to affect pilots with `ImageUrl` from `https://sb-cdn.fantasyflightgames.com`; Ahsoka, Anakin, and Barriss Aethersprite pilots are also affected, among others.  Interestingly, pilots with `ImageUrl` from `https://images-cdn.fantasyflightgames.com` (such as the 104th Battalion Pilot) are not affected.

**Comment by bitsai** [comment]
I just remembered this is already on the list of 1.0 to-do's posted in Slack a couple days ago (I added the relevant ones to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features as well).
