### ISSUE TITLE
Using Optimized Prototype on Lt. Tavson freezes game

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2264]
Whenever I am given the choice to have Vader spend a result to remove a shield from an enemy ship, the game freezes.

Using Darth Vader, Major Vermeil, and Grand Inquisitor

![image](https://user-images.githubusercontent.com/26996014/64280152-694dc000-cf05-11e9-9209-8e3ef2615bdd.png)

**Comment by rune-b** [comment]
Tried this with Vader + Omicron pilot with Krennic, and did not get an error, so probably some other ability also being involved

**Comment by bitsai** [comment]
I was able to create *a* crash, although the stack trace isn't identical to the one from above.  Steps I took (see below for ships and upgrades used):

<img width="1280" alt="Screen Shot 2019-09-05 at 9 27 03 AM" src="https://user-images.githubusercontent.com/260863/64360682-c7d77480-cfbf-11e9-8da2-055e2257b348.png">

- Reinforce with Tavson
- target lock Tavson w/ Krennic carrier
- shoot Tavson w/ Optimized Prototype carrier
- spend result to remove shield from Tavson
- when Tavson's ability triggers, choose Focus action, which triggers the following error:

<img width="1280" alt="Screen Shot 2019-09-05 at 9 26 52 AM" src="https://user-images.githubusercontent.com/260863/64360727-e178bc00-cfbf-11e9-8c14-479b4610ca3a.png">
