### ISSUE TITLE
Rotate ship at setup

### ISSUE THREAD

**Issue by danielsunderland** [Sandrem/FlyCasual#2269]
This is more of a feature request than an issue, but it would be amazing if a player could rotate the ship as part of the initial setup. Even if it was in 45 degree increments, this would capture most setup scenarios. Most setups and openings that I play both with and against involve ships turned at either 90 or 45 degrees, and it would be awesome to practice playing with such openings.

**Comment by Sandrem** [comment]
Keys "Q"/"E". Or "CTRL+Q"/"CTRL+E" for better precision.

**Comment by bitsai** [comment]
On mobile, you can do the same by putting two fingers down on a ship then rotating them.
