### ISSUE TITLE
Weird overlap despite bump

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2273]
Serissu took a sharp right turn and bumped into the X-Wing overlapping it instead.

No error messages have been generated.

This is the most recent version.

![image](https://user-images.githubusercontent.com/28895989/64391864-a1aae680-d04a-11e9-8693-66e0cf19e852.png)

**Comment by VexingVision** [comment]
Serissu was not able to shoot at the ship she overlapped.

**Comment by rune-b** [comment]
Possibly related to #2208

**Comment by bitsai** [comment]
Tracking this under bumping-related problems meta-issue (#2279).
