### ISSUE TITLE
Crash on amilyn holdo

### ISSUE THREAD

**Issue by feaglor** [Sandrem/FlyCasual#2276]
Game crashes when i try to transfer a reinforce token (obtained via angled deflectors) to any ship

![Screenshot_2019-09-07-15-38-36-772_com sandrem flycasual](https://user-images.githubusercontent.com/55024010/64475774-68c45c00-d187-11e9-9999-c41403331d4e.png)

**Comment by bitsai** [comment]
Good news!  This is already fixed in the development branch (by #2260), and will be resolved in the next release.
