### ISSUE TITLE
AI ship warped off of map and blew up.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#2277]
Was playing Ahsoka (R2, Delta 7b), Obi-Wan (R2, Delta 7b), and Ric Olie (Juke, R2) against the 5 TIE Advanced x1 team.  I had only one enemy left.  They did a 2 turn to the right, ending in the middle of the map, facing the left of the map.  Then they suddenly warped at high speed off the left side of the map and blew up for being off the map.

**Comment by rune-b** [comment]
Sounds similar to #2191

Did your game finish normally or was it stuck?

**Comment by rune-b** [comment]
PC or mobile?

**Comment by DejaFu** [comment]
Game finished normally.  This is on the PC.

**Comment by bitsai** [comment]
I think this is the same issue as #2191 as well, going to close this one while keeping the other open for tracking purposes.
