### ISSUE TITLE
Range three reducing damage dealt?

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#2278]
Playing Ahsoka, Obi-Wan, and Ric Olie vs. Luke, Wedge, and Dutch (the AI random team).  Ahsoka rolled a two hit and one crit attack.  Luke rolled 3 dice defense, rolled 2 evades and a blank.  A comment came up saying something about range 3, and Luke took no damage.

**Comment by rune-b** [comment]
Did one of the other rebels have selfless perhaps?

**Comment by DejaFu** [comment]
Ah.  You are right.  Dutch had Selfless.
 - Donner

**Comment by bitsai** [comment]
Good catch, @rune-b !
