### ISSUE TITLE
Bumping-related issues

### ISSUE THREAD

**Issue by bitsai** [Sandrem/FlyCasual#2279]
Meta-issue for tracking problems related to bumping, to avoid clutter from multiple issues reporting different symptoms of the same underlying issue.

- Arvel can't attack at range 0 (#2275)
- ships overlapping after bumping (#2273)
- ships shooting and/or taking actions after bumping (#2208)
- can't use Vader (crew) on ship that bumped (#2062)

**Comment by Sandrem** [comment]
Fixed
