### ISSUE TITLE
Internet option not working?

### ISSUE THREAD

**Issue by Bondsie94** [Sandrem/FlyCasual#2283]
The internet option is grayed out on and unavailable to click and use. Is there something I need to do to enable it or something I'm missing?

**Comment by Sandrem** [comment]
With current level of support from community - I don't have enough free time to develop both offline and online mode. So I disabled online mode until I finish offline mode first.
By the way, if each person who ask about online mode, was asking this as my Patreon supporter, then I would have enough resources to keep online mode active =)
