### ISSUE TITLE
FTC didn't trigger after landing on a rock

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2284]
Slightly niche issue..
(1) Anakin performed a sloop that landed on a rock. 
(2) Used ability to remove stress. 
(3) Used R4-P17 to take a focus.
(4) Should have been able to use FTC to barrel roll off the rock.
Game allowed steps 2 and 3 but not 4. Also game didn't charge Anakin 1 force to use ability.

Android game log and a screenshot attached (two stresses are from a panicked pilot crit after all this movement has occurred)

**Comment by ootinni** [comment]
Oops, with attachments.
[LastReplay.txt](https://github.com/Sandrem/FlyCasual/files/3588259/LastReplay.txt)
![Screenshot_20190909-013221](https://user-images.githubusercontent.com/52763171/64497057-d87b3980-d2a2-11e9-9119-bdb45d896957.png)

**Comment by bitsai** [comment]
Thank you for the detailed info!  I'm happy to report that this has already been fixed in development (#2257), and will be resolved in the next release.
