### ISSUE TITLE
Nashtah Pup emergency deploys with a weapon disabled  token.

### ISSUE THREAD

**Issue by monkeysinc** [Sandrem/FlyCasual#2285]
Flying Bossk in the YV-666 with Nashtah Pup docked, when he dies in the engagement phase the pup emergency deployed correctly, but with a weapon disabled token. The rules say nothing about this, in fact it say the ship can still engage. 

> • If a ship emergency deploys during the Engagement Phase, it can still
engage during that phase at its initiative. If its initiative has already
occurred this round, it cannot engage this phase.

**Comment by monkeysinc** [comment]
It also deployed with 1 Hull and 2 Shield. It should deploy with 2 Hull 1 Shield, as emergency deploy causes him to suffer 1 critical damage. (This is different then first edition, where it is dealt a face up card)

**Comment by rune-b** [comment]
Thanks for reporting. I see that it currently also is allowed to do an action after which it should not in SE
