### ISSUE TITLE
AI Vader locks one ship but then shoots different ship

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2286]
See screenshot below. He should have locked the one he shot at.

![Screenshot_20190909-084940](https://user-images.githubusercontent.com/11047987/64523375-74855f00-d2fc-11e9-9a10-0a143a50876a.png)

**Comment by ggrabarz** [comment]
I think all Tie Advanced x1 pilots do this. There's a random squad of 5 of them with FCS i think and they all behave so.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Proposed-AI-improvements
