### ISSUE TITLE
Tractor tokens on friendly ships don't lose a defense die

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#2292]
I just played a game with Sun Fac and two other Natex fighters vs. Luke, Wedge, and Dutch.  No targets lost agility for defense if they were defending and had tractor tokens on them.

**Comment by bitsai** [comment]
Couldn't reproduce in current development branch; in the screenshot below, after tractoring himself, Sun Fac's agility was correctly reduced from 3 to 2 and rolled only 2 green dice when defending against a range-2 shot:

<img width="1280" alt="Screen Shot 2019-09-11 at 6 49 03 PM" src="https://user-images.githubusercontent.com/260863/64747880-34250d00-d4c5-11e9-95b6-46f2a0345e31.png">

Were you playing 0.9.5 or the current release branch?  Can you attach a screenshot?

**Comment by DejaFu** [comment]
9.5.  But I think I might be mistaken again.  I’ll try and measure twice and cut once next time to make sure not to waste time with false reports.  Sorry about that!
 - Donner

**Comment by bitsai** [comment]
No worries at all!  If it wasn't for everyone's vigilance bugs would never get caught :)
