### ISSUE TITLE
Large base not allowed to rotate at setup

### ISSUE THREAD

**Issue by danielsunderland** [Sandrem/FlyCasual#2293]
Flying Rebel Han Solo in the Falcon, I attempted to rotate the ship at setup. With the back of the ship touching the edge of the playing area, the front of the ship should be allowed to extend beyond range 1. However, the program isn't allowing that to happen.

Many thanks,
Dan.

**Comment by Sandrem** [comment]
Known problem, this rule will be implemented soon.
