### ISSUE TITLE
Han's pilot ability not rerolling for R2D2 crew

### ISSUE THREAD

**Issue by danielsunderland** [Sandrem/FlyCasual#2294]
Hi,

Rebel Han's pilot ability should also be allowed to be used when rolling with R2D2 crew to regen shield. However, at the moment, after rolling with R2D2 crew, the opportunity to use Han's ability isn't being offered. Note that Han's ability should also be offered with Lando crew, but not C3PO crew (I haven't checked these).

Thanks for all your work guys - 

Dan.

**Comment by Sandrem** [comment]
Known problem, at the moment dice modification is available only for combat.
