### ISSUE TITLE
AI Selfless priorities

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2295]
I was playing against the AI B-Wing Selfless squad, and it used Sefless to transfer a hit to a B-Wing with only one hull left, destroying it.

Also: Sometimes the Selfless decision popup shows for an instant when the AI is using it

**Comment by rune-b** [comment]
In a later turn the AI used selfless to take a crit away from a ship that would die from the attack anyway.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Proposed-AI-improvements
