### ISSUE TITLE
VTG not allowing double tap on Rebel Y Wing

### ISSUE THREAD

**Issue by Skele-Tor** [Sandrem/FlyCasual#2296]
Flying Rebel Y Wing with Dutch or Nora the Veteran Turret Gunner is not allowing shots from the front turret arc after engaging with the primary weapon.

I'm using 0.9.5 across all 3 platforms

**Comment by bitsai** [comment]
Tested using a hotseat game pitting Dutch vs. Norra (both with VTG + Ion Cannon Turret), couldn't reproduce; as per the screenshots below, both pilots were able to get bonus attacks from the front turret arcs after engaging with the primary weapon.

<img width="1280" alt="Screen Shot 2019-09-14 at 11 22 13 PM" src="https://user-images.githubusercontent.com/260863/64917551-c5ef7d00-d746-11e9-8930-795ca9f786c3.png">

<img width="1280" alt="Screen Shot 2019-09-14 at 11 22 43 PM" src="https://user-images.githubusercontent.com/260863/64917552-c8ea6d80-d746-11e9-95ce-a6b0b852dda8.png">

Can you try to reproduce the issue, and if so, share the steps needed and screenshots (which are extremely helpful)?  Also, please note that turrets generally only have max range 2, could that have been the thing that prevented VTG from triggering in your games?

**Comment by Skele-Tor** [comment]
Hello, you're right! on further play testing it does indeed work. I have seen an occurrence of it not though so i will endeavor to gather better evidence when this occurs again and re-open the ticket then.

Apologies for wasting your time.

**Comment by bitsai** [comment]
No problem, thank you for following up!
