### ISSUE TITLE
Surface Pro 6

### ISSUE THREAD

**Issue by BigAce303** [Sandrem/FlyCasual#2298]
Hello, I didn’t know if anyone else has the issue of stopping in the middle of a game and going white or black full screen and then shutting off. Is there a work around for this!?

**Comment by rune-b** [comment]
Hi
I haven't heard about anyone else having this problem. Does it happen often for you?

**Comment by bitsai** [comment]
@BigAce303 apologies, but I don't think any of the developers have a Surface Pro 6 (or if they do, they haven't been able to reproduce the issue).  Trying to make the program work on all platforms is almost impossible, and without being able to reproduce the issue there's not much we can do here.
