### ISSUE TITLE
Mining guild Tie barrel roll

### ISSUE THREAD

**Issue by Dotswarlock** [Sandrem/FlyCasual#2300]
Here is a bug that I found on the Mining guid Tie.  Its ability states that "while you move, you ignore asteroids".  Note that the ability says "move" and not manoeuver, so a barrel roll (a type of move according to the rules reference) should still be allowed to move in or out of an asteroid, whether it overlaps or not.

Thanks for all the hard work!

**Comment by Sandrem** [comment]
Fixed by Arahain
