### ISSUE TITLE
Autoblaster Canon not working

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2301]
Hi!

Again, thanks for this amazing simulator.

I am experiencing an issue with autoblasters. In 2.0 crits are uncancellable, but many times, they get cancelled by enemy evade results. In fact, my IG-88 killed Vader with 3 autoblaster crits (in Marksmanship bullseye arc) and Vader's 3 evades cancelled them all, leaving him alive for another turn.

It's hard to capture a screen shot of this, because results disappear so quickly on the screen (any way to control this with mouse clicks instead of letting them go automatically? Blink, and you miss what happened.)

Anyway, I hope this can be addressed. Thanks!

![image](https://user-images.githubusercontent.com/26996014/65068181-fc8ee880-d93c-11e9-8025-979cb21dc7e8.png)

**Comment by rune-b** [comment]
Hi
Are you sure IG-88 was not in Vader's firing arc?

Do you have the rest of the screen shot?

**Comment by TNG-Wing** [comment]
Oh! I must have missed that text about not being in the defender's firing arc! Never mind!Thanks!
null

**Comment by rune-b** [comment]
You're welcome :)

Closing this issue then
