### ISSUE TITLE
disarm tokens on plo koon doesn't let you spend force

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#2304]
when plo koon takes a disarm token he is not allowed to spend force on defense

**Comment by bitsai** [comment]
Couldn't reproduce; see below screenshot, where Plo pulled a Disarm token from Anakin but is still allowed to spend Force for defense.

<img width="1280" alt="Screen Shot 2019-10-01 at 8 17 07 AM" src="https://user-images.githubusercontent.com/260863/65975779-f9f3bf00-e423-11e9-8bbf-03de8643bdb7.png">

@aelithanar can you try to reproduce and attach a screenshot?  Please note that Plo's ability costs a Force; is it possible that after he pulled the Disarm token in your game, he didn't have any Force left?
