### ISSUE TITLE
Camera pans uncontrollably

### ISSUE THREAD

**Issue by TlTAN1** [Sandrem/FlyCasual#2306]
Just downloaded 0.9.6 and I can't control anything on screen because the game camera pans to the NW corner by default. This occurred with and without a normal mouse plugged in.

Excited to get into the new update soon!

**Comment by rune-b** [comment]
Hi. Is this on PC, Mac or Android?

Do you have a joystick or similar connected?

**Comment by TlTAN1** [comment]
This is on a PC with no exterior devices in use. I read that this happened to a few users in the older versions of the game but it didn’t seem like there was a cut and dry solution in those threads

**Comment by rune-b** [comment]
Does your computer have a touch screen? Have you tried switching between mouse and touch mode?

**Comment by TlTAN1** [comment]
No touch screen, just an MSI laptop. Switching between the two modes had seemingly no effect on the camera wanting to move. The game seems to function otherwise, fighting the camera with a down and to the right arrow combo stops it in the opposite corner but this is not a great solution

**Comment by TlTAN1** [comment]
I also tried installing previous builds of the game but the same issue persisted

**Comment by rune-b** [comment]
Hmm, that is strange. Have you tried restarting your computer?

**Comment by TlTAN1** [comment]
Just tried, no effect... Thank you for your assistance, I seem to be in the minority with this “bug”

**Comment by rune-b** [comment]
I'm out of ideas... But since it also happens after going back to the previous version I suspect this is an issue with your computer setup and not the game

**Comment by Sandrem** [comment]
This issue is isually caused by some drivers of another input devices, like gamepads.
Please, try to open console (CTRL + ~) and enter command "input axis". Does this help?

**Comment by TlTAN1** [comment]
I found the fix! Went into Device Manager, and under the Human Interface Devices, turned off a default joystick configuration the laptop had set to it. I guess under Unity, it is taking inputs for this controller even though it’s not connected to the laptop, but disabling it the camera panning stopped. 

Hope this helps anyone with the same issue.

**Comment by Sandrem** [comment]
@TlTAN1 Thank you, I will remember this way of fix - maybe it will help another users.
