### ISSUE TITLE
R2D2 Republic Y Wing Astromech/Talent Slot

### ISSUE THREAD

**Issue by Rolo2358** [Sandrem/FlyCasual#2307]
Missing/additional slots

**Comment by rune-b** [comment]
Which slots do you mean? It looks correct to me

**Comment by Rolo2358** [comment]
Has this been fixed recently?? Yeah that's right! Swear it wasn't the other day, my mistake!

**Comment by rune-b** [comment]
It was fixed in the release yesterday

**Comment by Rolo2358** [comment]
Ah brilliant!! Didn't see it in the change notes must have missed it
