### ISSUE TITLE
Ved Foslo Ability UI crash

### ISSUE THREAD

**Issue by Rolo2358** [Sandrem/FlyCasual#2308]
UI for Beds ability to change manuevers occasionally appears with no options, so you can make a choice and continue the game

**Comment by rune-b** [comment]
I assume we are talking about Ved Foslo

Can you give some more details about when this happens? A screenshot would be helpful

**Comment by rune-b** [comment]
I found it. When doing a 1 straight with Foslo it crashes, and the game completely freezes. No error messages 

![Screenshot_20190919-201027](https://user-images.githubusercontent.com/11047987/65269547-b478ed00-db19-11e9-90ea-79a8e7242357.png)

**Comment by rune-b** [comment]
Actually, it seems it isn't crashed. The UI is blocked while waiting for Foslo's maneuver to be selected, but the maneuver UI is just those small black lines visible on screen. I can restart the game from thecmenu.

![Screenshot_20190919-201347](https://user-images.githubusercontent.com/11047987/65269841-42ed6e80-db1a-11e9-91c1-172f3951d6d3.png)

**Comment by Sandrem** [comment]
Such UI is shown when there is no available maneuvers to show. (Only top/botton of menu, without content with buttons)
