### ISSUE TITLE
Instinctive Aim seems to consume target lock

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2309]
Used Instinctive Aim and was prompted when shooting Ion Torpedoes, "use target lock" vs "use force token".  I chose target lock, but then when the attack dice were rolled, was not able to spend the lock (wasn't an option) to reroll some dice.  Curiously the icon indicating target lock was still showing on both attacker (Luke) and defender (B-Wing with selfless, shield upgrade).

**Comment by bitsai** [comment]
Tried to reproduce this in a hotseat game, but was unable to do so.

Here I'm about to select the "Force token" option to pay the cost for Proton Torpedoes:

<img width="1280" alt="Screen Shot 2019-09-30 at 10 37 33 PM" src="https://user-images.githubusercontent.com/260863/65937200-f7697900-e3d3-11e9-9e8e-6e865330655e.png">

Just after paying a Force (Anakin now only has 1 Force left) to fire the PT, Target Lock shows up as an option to modify dice as usual:

<img width="1280" alt="Screen Shot 2019-09-30 at 10 37 49 PM" src="https://user-images.githubusercontent.com/260863/65937252-2b449e80-e3d4-11e9-8c58-dee142e7ef25.png">

@starjoe4 can you try to reproduce this, and if able to, attach a screenshot?  in your original game, maybe something (such as the Blinded Pilot crit) prevented the use of Target Lock when Luke shot?
