### ISSUE TITLE
Camara drift 

### ISSUE THREAD

**Issue by Aeropig** [Sandrem/FlyCasual#2312]
I am using Windows 10 Pro and I am having an issue running the game. When I enter the view of the game board the camera constantly drifts to the top right of the play area. It is impossible to play this way.

Is this a code issue that you know of, or am I doing something daft?

Thank you.

Tom

**Comment by rune-b** [comment]
You're not the only one. See #2306, hopefully it can help you

**Comment by Aeropig** [comment]
Thank you. That's worked perfectly. it was the joystick drivers for me as well. Thanks for taking the time to answer.
