### ISSUE TITLE
Replay with nantex doesn't work

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2313]
0.9.6 Android

When replaying a match with sun fac, the replay stopped on turn 1 when the Nantex ability triggered, showing the decision window.

**Comment by rune-b** [comment]
![Screenshot_20190922-083340](https://user-images.githubusercontent.com/11047987/65383317-1a30c900-dd14-11e9-81f2-f00595e79d11.png)

**Comment by rune-b** [comment]
[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/3639436/LastReplay.replay.zip)

**Comment by Sandrem** [comment]
Fixed
