### ISSUE TITLE
Petty Officer Thanisson Tractor Beam

### ISSUE THREAD

**Issue by CmdKestrel** [Sandrem/FlyCasual#2315]
Hi,

Using Petty Officer Thanissons ability to tractor an opponent on to an asteroid caused an error. Refer screenshot.

Could not continue the game afterward. Had to return to menu.

![Fly Casual Bug](https://user-images.githubusercontent.com/55654481/65386082-57c83d00-dd7a-11e9-8b46-d634a28ea17f.png)

**Comment by rune-b** [comment]
Tried to reproduce with Thanisson vs B-wing, but got no error.

![Screenshot_20190925-163857](https://user-images.githubusercontent.com/11047987/65611466-22f2fa80-dfb3-11e9-96f5-530507d0b579.png)

**Comment by CmdKestrel** [comment]
Guess I was just super lucky that day.

If I get any other bugs I will post error reports.

Cheers
CmdKestrel
________________________________
