### ISSUE TITLE
Closed s-foils are lowing the attack dice of snap shot

### ISSUE THREAD

**Issue by dherve10** [Sandrem/FlyCasual#2317]
Closed s-foils read that the primary attack is lowered by one, but snap shot is not a primary attack, and so should not be affected by closed s-foils.

**Comment by rune-b** [comment]
Which S-Foils? T65 or T70? Or both?

**Comment by dherve10** [comment]
I noticed it with the T-65, but it's probably worth checking the code for both. 

> 
> 
> Which S-Foils? T65 or T70? Or both?

**Comment by rune-b** [comment]
Confirmed. Got the same behavior with both T65 and T70
