### ISSUE TITLE
Stuck in Engagement phase after Berwert Kret shoots

### ISSUE THREAD

**Issue by p0lda** [Sandrem/FlyCasual#2318]
Hi, I have noticed a bug with Berwert Kret (the Initiative 5 Nantex pilot). 
When testing triple Nantex squads (Ini 4, 5 and 6) after I shoot with Berwert, the game gets stuck on forcing me to pick a ship to resolve his ability without the usual "Skip" option.
The ability cannot be resolved if there is no ship with Calculate action on it's bar and a lock on the defender Berwert just hit.

**Comment by rune-b** [comment]
Thanks for reporting. I will fix
