### ISSUE TITLE
Not in arc

### ISSUE THREAD

**Issue by Takko550** [Sandrem/FlyCasual#2321]
Target not legal despite in range and arc.

![notinarc](https://user-images.githubusercontent.com/55527581/65485731-392a8900-ded5-11e9-8166-8acb4f250d0b.png)

**Comment by ootinni** [comment]
Had a similar issue
![Screenshot_20200331-023736](https://user-images.githubusercontent.com/52763171/78197653-e16d6b80-747d-11ea-910f-caa937e0c8e4.png)

**Comment by Sandrem** [comment]
Some changes are done, we will see will it fix this or not.
