### ISSUE TITLE
Arvel not working with intimidation

### ISSUE THREAD

**Issue by zeebot9** [Sandrem/FlyCasual#2325]
When Arvel has intimidation and is at range 0 only one bonus is applied.

**Comment by bitsai** [comment]
Couldn't reproduce; in the screenshots below, you can see an extra attack die added for the range 1 bonus and the number of defense die reduced by Intimidation.

<img width="1280" alt="Screen Shot 2019-10-01 at 8 23 19 AM" src="https://user-images.githubusercontent.com/260863/65976545-1f34fd00-e425-11e9-9937-79992e277fac.png">

<img width="1280" alt="Screen Shot 2019-10-01 at 8 23 29 AM" src="https://user-images.githubusercontent.com/260863/65976554-21975700-e425-11e9-9e4d-6dd59671bdef.png">

@zeebot9 can you try to reproduce and attach screenshots of how many attack & defense dice were rolled?
