### ISSUE TITLE
stunned pilot crashes when last hit

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#2327]
I think the tie fighter has the crits console fire and stunned pilot (the one that you get a hit when you crash into other pilots) and it was its last hit. Hope it helps

![image](https://user-images.githubusercontent.com/20516751/66047394-fb0e1480-e527-11e9-8f1f-fa60bbac69b6.png)

**Comment by rune-b** [comment]
Stunned pilot only gives damage when you crash into obstacles. not other pilots. But its possible the TIE in your screenshot would also overlap that asteroid after bumping that ship

I have tried running a TIE with console fire and stunned pilot over an asteroid, but I didn't get this error

**Comment by Lordka79** [comment]
same problem with all the ship. impossible to play to casual

**Comment by Sandrem** [comment]
Still cannot reproduce.
