### ISSUE TITLE
Ship Cards not always showing.

### ISSUE THREAD

**Issue by allysiu** [Sandrem/FlyCasual#2329]
<img width="1024" alt="Screenshot 2019-10-04 11 50 20" src="https://user-images.githubusercontent.com/33953715/66202241-27976d00-e69d-11e9-8874-d027deef7d20.png">

Photo attached. happens among most ships of all factions.

**Comment by rune-b** [comment]
The images are downloaded from the internet. Did you have an internet connection when this happened?

**Comment by allysiu** [comment]
Yes I did. I’ll check again.

Kind Regards

Alistair Siu
Technical Project Manager
Barco E2/S3 Operator


________________________________

**Comment by allysiu** [comment]
Just checked I had my vpn on and that was causing some internet issues. All resolved now.

Kind Regards

Alistair Siu
Technical Project Manager
Barco E2/S3 Operator


________________________________

**Comment by rune-b** [comment]
Ok, good 😊
