### ISSUE TITLE
Admiral Holdo UI overlay does not disappear when ability finishes

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#2331]
If there are no tokens to transfer from the target to Holdo's ship the UI overlay box for transferring a token from the target remains on the screen after Holdo's ability finishes resolving and into subsequent rounds.

**Comment by rune-b** [comment]
Thanks for reporting. Seems there are multiple problems with Holdo

I tried using her ability when both ships had a focus token. Then I (correctly) got the message that no tokens could be transferred, so I had to click skip. But then Holdo's ship was still selected and there was no way to continue the gam

**Comment by rune-b** [comment]
However, I have not been able to reproduce the bug you were having. Do you have some more details about what you did when it happened? Are you able to reproduce it?

A screenshot would also be helpful

**Comment by HumbleBob** [comment]
Hey, there, rune-b, I went back in to try and reproduce the bug, but I was unable to; tried every combination of succeeding and failing to transfer tokens, I think.  Most I can say is I'm 100% sure I did get the bug my first time playing with Holdo on the first turn that ship engaged, and the second turn it froze up as described in the other issue report I submitted.  Sorry I can't be of more help.

**Comment by Sandrem** [comment]
Fixed
