### ISSUE TITLE
Game becomes unresponsive after ship with Admiral Holdo engages

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#2332]
The game will sometimes fail to move to the next ship to engage or fail to move to the end phase after a ship carrying Admiral Holdo resolves her ability and engages.

**Comment by rune-b** [comment]
Hi
Do you get any error messages when this happens?

**Comment by HumbleBob** [comment]
There's no error message when the hanging begins, but if you click on Holdo's ship, it will sometimes give an error message saying that the ship has already fired.
<img width="1440" alt="Screen Shot 2019-10-08 at 9 47 38 PM" src="https://user-images.githubusercontent.com/17327811/66445586-4b4c1180-ea15-11e9-9975-8f6cc3eefac3.png">

**Comment by Sandrem** [comment]
Fixed
