### ISSUE TITLE
Large base ships deploying

### ISSUE THREAD

**Issue by SneakyGitau** [Sandrem/FlyCasual#2333]
Hi, unable to rotate large base ships so they can face at angle and extend beyond range 1 during deployment 

rules reference - 

 During setup, a large ship’s base may extend outside of range 1 as long
as it fills the length of that area. A large ship cannot be placed with any
portion of its base outside the play area.

**Comment by Sandrem** [comment]
This is known problem, I plan to implement this feature in the nearest update.
