### ISSUE TITLE
ensnare on jammed ship crashes the application

### ISSUE THREAD

**Issue by aelithanar** [Sandrem/FlyCasual#2335]
Got this error when selecting the ship to transfer ensnare, i selected the red marked ship and it crashed, hope the screenshot helps
![image](https://user-images.githubusercontent.com/20516751/66325447-8f60e880-e927-11e9-9684-9b595935f409.png)

**Comment by rune-b** [comment]
Thanks for reporting. It seems there is a problem when a jammed ship gains a tractor token.
