### ISSUE TITLE
Inertial Dampener caused game to stop working on Boba Fett - Firespray

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2343]
After selecting inertial dampener, the console opened with a bunch of red text (apologies didn't screen grab).  then couldn't continue (couldn't pick other ship to continue activation).

**Comment by rune-b** [comment]
I also get this error. 0.9.6 Android

Reproduced with boba with inertial dampeners and Z95 with inertial dampeners. Used dampeners on the first turn with the Z95 and got this error:

![Screenshot_20191024-194321](https://user-images.githubusercontent.com/11047987/67511309-e50ef200-f696-11e9-8e0c-209761d645ad.png)

**Comment by Sandrem** [comment]
Fixed
