### ISSUE TITLE
Shadow caster title asteroid no damage

### ISSUE THREAD

**Issue by krumok** [Sandrem/FlyCasual#2348]
I shoot with Ketsu with the shadow caster title to a tie
I hit the tie, correctly was assigned a tractor and I force the tie over an asteroid with a 1 straight
but no dice was rolled for asteroid damage on the tie
![Screenshot_2019-10-24-22-58-33-715_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/67525471-1a293d80-f6b3-11e9-97df-577e0a26be9a.jpg)

**Comment by bitsai** [comment]
Same issue as reported in https://github.com/Sandrem/FlyCasual/issues/2314.
