### ISSUE TITLE
0 Stop not triggering Pattern Analyser when at range 0.

### ISSUE THREAD

**Issue by Spraggle** [Sandrem/FlyCasual#2349]
When playing Vennie with Pattern Analyser, if I zero stop, I don't get chance to activate pattern analyser. Is this a trigger that is missed by fly Casual, because the manoeuvre didn't move, so it never checks to see if PA should trigger?
 
It does work if I perform another red move, so I think it's just to do with what the PA checks for.

**Comment by rune-b** [comment]
I am not able to reproduce this. PA triggers for me on stop maneuvers:

![image](https://user-images.githubusercontent.com/11047987/67636492-82556a80-f8d1-11e9-8e1f-da0998cb9d68.png)


![image](https://user-images.githubusercontent.com/11047987/67636499-98fbc180-f8d1-11e9-89aa-64719f87cc46.png)

**Comment by rune-b** [comment]
Did you have any other upgrades on Vennie?

**Comment by Spraggle** [comment]
Hmmm... Yes, PA, Rey, Per Co and Stealth. However, having just tried to reproduce again, I've not managed it - I think it has something to do with range 0 now, but will go back and try to reproduce this again tonight.

**Comment by Spraggle** [comment]
Managed to reproduce. Vennie + 3A Vs 5x Cartel M.

I started the turn with two ships touching Vennie. Zero stop dialed in, and no pattern analyser trigger. I've got a screen shot of after one ship moved but hard to attach on phone.

**Comment by rune-b** [comment]
Confirmed. I get the same bug when at range 0 of an enemy

0.9.6 Android

**Comment by Spraggle** [comment]
![Screenshot_20191027-214636](https://user-images.githubusercontent.com/9283327/67675060-1547e080-f976-11e9-940e-5307a38ce334.png)
Glad to see that you reproduced the bug too - but here was my outcome, as promised :-)
 
Thanks for keeping on trying!

**Comment by rune-b** [comment]
Pattern Analyzer doesn't consider the stop maneuver to be fully executed if the ship is touching another ship. I will fix
