### ISSUE TITLE
Rear arc miscalculating on HWK

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2350]
![rear_arc_error](https://user-images.githubusercontent.com/47924192/67722066-93c07480-f9ae-11e9-9f3b-51d25a97156d.png)

When I attempt to choose the tie, it says the target is not a legal target for the attacker.  arc is pointing backward and it seems pretty clearly that the TIE is in arc.

**Comment by Sandrem** [comment]
Some changes are done, we will see will it fix this or not.
