### ISSUE TITLE
console fire not triggering when ships dont have shots

### ISSUE THREAD

**Issue by drdov** [Sandrem/FlyCasual#2353]
All ships engage, even when you dont have a shot.  This crit did not trigger on a ship for multiple turns when it didnt have shots

**Comment by rune-b** [comment]
I tried to reproduce this, but the crit did trigger for a TIE fighter with console fire which didn't have a shot:

![image](https://user-images.githubusercontent.com/11047987/68245324-08328d80-0017-11ea-81f4-454cba0f693d.png)

**Comment by rune-b** [comment]
Has this happened more than once for you? Do you remember what pilot it was, and what upgrades were equipped?

If this happens again, please take a screen shot of the situation

**Comment by Sandrem** [comment]
Still cannot reproduce
