### ISSUE TITLE
Ship got to edge of map... kept flying forever

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2356]
Sorry, clicked too quickly.

I couldn't tell if the ship would actually have fled, or if it was just failing to measure, but a Cartel Marauder tried to do a 4-K turn that I think would  have overlapped a Sith Infiltrator (Darth Maul), but it just kept gliding - stayed visible until maybe ten board widths away - and then the game was stuck, because the next ship never continued.  The Cartel Marauder was an AI ship.  

I wasn't able to get a screenshot before the ship disappeared...

**Comment by rune-b** [comment]
Sounds like the same bug as #2191
