### ISSUE TITLE
Concordia Face-off - Incorrect Trigger

### ISSUE THREAD

**Issue by cm5089** [Sandrem/FlyCasual#2361]
A Natex with it's arc rotated to the left shot a Zealous Recruit Fang Fighter at range 1 using the turret arc.  This incorrectly triggered Concordia Face-off which should only activate in the front arc.

**Comment by rune-b** [comment]
Are you sure the Fang wasn't also in the Nantex's front arc at the time of attack?

It does not matter where the nantex's turret arc is rotated. The only thing that matters is if the Fang is in the nantex's front arc, regardless of where the shot is coming from

**Comment by haukurv** [comment]
I have noticed this too
![concordia_faceoff](https://user-images.githubusercontent.com/43995365/72418798-73b17d80-3773-11ea-8970-590719244dd3.jpg)
Concordia faceoff kicks in even when the enemy ship is not in the fangs front arc.

**Comment by haukurv** [comment]
Ehrm, sorry. it is suposed to do that... nevermind.

**Comment by Sandrem** [comment]
Still cannot reproduce.
