### ISSUE TITLE
AI doesn't get stress from red actions

### ISSUE THREAD

**Issue by cm5089** [Sandrem/FlyCasual#2362]
AI Firespray often uses reinforce - but doesn't take stress.

**Comment by rune-b** [comment]
Confirmed

![image](https://user-images.githubusercontent.com/11047987/68549387-a0ee5200-03f7-11ea-934c-b92df9159399.png)

**Comment by rune-b** [comment]
It seems this is a general problem with AI and red actions. There just aren't many cases where the AI will actually choose a red action, so it is not so noticable.

Reproduced with AI Quadjumper doing a red evade without getting stress:

![image](https://user-images.githubusercontent.com/11047987/68549802-7c48a900-03fc-11ea-97ba-cf2ff916516d.png)

**Comment by rune-b** [comment]
@Sandrem Seems this is done on purpose:

https://github.com/Sandrem/FlyCasual/blob/10329d187526d3ac4fdb890fb950a6e97ed9683b/Assets/Scripts/Model/Rules/RulesList/ActionsRule.cs#L31

**Comment by Sandrem** [comment]
This is special change of rules for AI. It is too complex to predict when execution of red action is more useful than bad effect of stress token.
Maybe, will be improved later - but not in the nearest future.
