### ISSUE TITLE
AI Tallon Roll breaks game (development branch)

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2363]
When the AI does a Tallon Roll, the player is asked to chose final position. After choosing, the game will not continue

![image](https://user-images.githubusercontent.com/11047987/68550467-4955e380-0403-11ea-9647-3eafff6a74bd.png)

**Comment by mishari27** [comment]
Thanks, however, I was only trying to get the new points update. it was my first time using Unity hub to build anything. I downloaded the development after Sandrem merged stuff 2 days ago.

Is there a way to only get the wave6 updates into the stable version?

**Comment by rune-b** [comment]
It is possible, but a bit complicated if you haven't used git before. Basically you have to check out an earlier version of the code and the merge the wave 6 updates yourself.

I recommend waiting for 0.9.7 instead

If you disable the point limit in the game, you can build the same squads in 0.9.6

**Comment by Sandrem** [comment]
Changes to Tallon Roll are reverted. This feature will be finished and released later.
