### ISSUE TITLE
Baze Malbus "Treat that action as red" effects stack for multiple stress

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#2365]
Airen Cracken and Advanced Slam allow a ship to take an action, treating that action as red.  If the ship that performs the action has Baze Malbus, it may treat a focus action as red to gain additional focus tokens.  When the player is presented with this option, they have already gained the stress from performing a "red" action, and when they choose "yes" for treating the focus action as red for Baze, the player gains a second stress when they should gain only the one for the single red action.

**Comment by rune-b** [comment]
Confirmed. He gets two stress but should only get one as I understand it

![Screenshot_20191111-083930](https://user-images.githubusercontent.com/11047987/68569727-248f5980-045f-11ea-89e9-8f5fa720fbec.png)

**Comment by rune-b** [comment]
Current Baze Malbus implementation doesn't actually treat the action as red, it just adds a stress token afterwards
