### ISSUE TITLE
iOS .ipa Not Installing with Impactor

### ISSUE THREAD

**Issue by hoarybat** [Sandrem/FlyCasual#2367]
The iOS .ipa file is not installing correctly for me anymore with Impactor. I've attached the screencap showing the error. I've never had problems installing the .ipa on my phone before.

- This is on an iPhone XS Max using iOS 13.2.2.
- Cydia Impactor is 0.9.52 (current version).
- Host computer is a late-2013 MacBook Pro using Mojave 10.14.6.
- XCode installed on my computer is version 11.2.1 (11B500).
- The Fly Casual version is 0.9.6.
- [I also tried Fly Casual version 0.9.2 and saw the same error.]

<img width="412" alt="Screen Shot 2019-11-16 at 2 05 19 PM" src="https://user-images.githubusercontent.com/48028648/68999856-767b1980-087b-11ea-97b5-af908f43f701.png">

**Comment by Senzorezo** [comment]
Hi. Same problem.
![image](https://user-images.githubusercontent.com/35725438/69484717-d4d56880-0e36-11ea-821b-02cd13e9eeaf.png)

- IPAD using IOS 13.2.3
- Impactor up to date (1559634320)
- FlyCasual 9.6

Thank you !

**Comment by rune-b** [comment]
This is a problem with Cydia and latest version of iOS. 

More details here:
https://www.idownloadblog.com/2019/11/19/saurik-cydia-impactor-xcode-7-3-error/

**Comment by rune-b** [comment]
I don't have an iOS device myself so I can't test this, but there seems to be a new alternative to Cydia that might work for you:

https://www.idownloadblog.com/2020/01/06/altdeploy-alternative-cydia-impactor/
