### ISSUE TITLE
Camera controls do not work after restart

### ISSUE THREAD

**Issue by ToshioMagic** [Sandrem/FlyCasual#2371]
During a match against AI where I know the eventual outcome I want to restart the match. When I press ESC and then click restart, the camera controls no longer work (middle click mouse button and awsd/arrow keys). I also cannot switch to 2D view. I click the button and nothing happens.

**Comment by rune-b** [comment]
That's strange. What kind of device are you playing on? Windows, mac, linux, Android or IOS?

**Comment by ToshioMagic** [comment]
64 bit Windows 10. Intel Core i7-8850H 2.6GHz. Every time without fail. This is the first time I have played it.

**Comment by rune-b** [comment]
Does it matter when you restart? Or is it the same if you do it on the AI's turn as on your own turn?

**Comment by ToshioMagic** [comment]
It happens regardless of whose turn it is.

**Comment by rune-b** [comment]
I have 64 bit Win 10 i7 laptop and this does not happen for me. 

Does the game otherwise work after restarting? Are you able to place ships and start the game?

Could it be related to a particular pilot or upgrade, or do you get the same problem with completely different lists?

Can you post a screen shot of your game after this has happened?

**Comment by ToshioMagic** [comment]
I will try and get you more information soon. Another note. If the game is over and it says "Player X wins" and I click restart on that menu, it works properly. No issues.

**Comment by ToshioMagic** [comment]
I can place ships and start the game. But it's pretty much useless since I can't see what I'm doing.

I get the same problem regardless of the list. I've tried about 10 diff lists, all imperial.

A screenshot won't really tell you anything as it looks exactly like a normal game.

**Comment by cosmo145** [comment]
I am having a similar issue where the camera moves up and to the left.  It's as if up and left are being held down on my keyboard.  was previously working fine.  Restarting game, computer, and re-downloading flycasual does not work.

**Comment by rune-b** [comment]
> I am having a similar issue where the camera moves up and to the left. It's as if up and left are being held down on my keyboard. was previously working fine. Restarting game, computer, and re-downloading flycasual does not work.

Several people have reported this in the past, and I think it was always caused by them having a joystick or other controller plugged in to the computer

**Comment by Sandrem** [comment]
Fixed
