### ISSUE TITLE
Proximity mine triggered after tractor array

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2372]
0.9.6 Android

My quadjumper moved over a proximity mine, but I prevented it from going off with Nym. Then it used the tractor array on an enemy ship, and then the proximity mine went off

![Screenshot_20191122-164806](https://user-images.githubusercontent.com/11047987/69440785-bc3b5480-0d49-11ea-8588-5287487f6683.png)
![Screenshot_20191122-164821](https://user-images.githubusercontent.com/11047987/69440800-c3626280-0d49-11ea-9611-6c5087fcc196.png)

**Comment by Sandrem** [comment]
Fixed
