### ISSUE TITLE
Tel Trevura

### ISSUE THREAD

**Issue by SmokeParnell** [Sandrem/FlyCasual#2373]
after ability goes off and re placed on the board,  it will not allow the ship to preform actions of any kind  nor will it allow the activation of R2 astromech

**Comment by rune-b** [comment]
Confirmed. After coming back Tel is not able to perform actions or activate R2. Tested on latest dev branch

**Comment by rune-b** [comment]
Also, AI ships will not shoot at it. It seems the ship is still considered destroyed by the game
