### ISSUE TITLE
Can't select obstacles

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2375]
During events that select obstacles, I get a prompt to select an obstacle but am unable to choose one. Tapping on them does not select them and nothing happens. I am forced to tap "skip" and fail the event.

Tested on Seismic Charges and Tobias Beckett crew.

**Comment by ootinni** [comment]
![Screenshot_20191125-011714](https://user-images.githubusercontent.com/52763171/69505867-fb250200-0f23-11ea-80d6-fb922dc422ff.png)

**Comment by rune-b** [comment]
Hi. I assume you are using a phone or other touch screen device

This is a known bug, and you can get around it by switching to mouse mode, select the obstacle, and then switch back to touch mode

**Comment by ootinni** [comment]
Yes, mobile device. Ok and thanks
