### ISSUE TITLE
Sol Sixxa with skilled bombardier

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2376]
With Sol Sixxa and skikled bombardier, there isn't enough room to show all the available options, so 3-speed options are not available

![Screenshot_20191125-011605](https://user-images.githubusercontent.com/52763171/69505864-ed6f7c80-0f23-11ea-8e90-1e0b44235aa8.png)

**Comment by rune-b** [comment]
Hi. I don't see how you should be able to use speed 3 templates. Skilled bombardier only allows you to increase it to 2

**Comment by ootinni** [comment]
Ah, yes you're right, sorry. Complete brain fail. Was confusing with Emon.
