### ISSUE TITLE
Miscalculated range

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2377]
Looks like range one, and Han was allowed to take his action after moving, but the X-Wing is not a valid target.
![Range miscalculation](https://user-images.githubusercontent.com/47924192/69563469-2d178200-0f7f-11ea-8c95-0f54c2f81a53.JPG)

**Comment by starjoe4** [comment]
To be more precise when clicking on the X-wing, the error "The target is not a legal target for the attacker" popped up.

**Comment by Sandrem** [comment]
Some changes are done, we will see will it fix this or not.
