### ISSUE TITLE
Han reroll ability doesn't work on Lando crew

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2378]
Rebel Han's ability to reroll all dice doesn't trigger after you roll for Lando crew ability

![Screenshot_20191128-010426](https://user-images.githubusercontent.com/52763171/69769678-ba282a00-117d-11ea-87fa-cdf3621f28e5.png)

**Comment by Sandrem** [comment]
Known problem - dice modifications are available only for combat dice rolls.
Implementation of this feature is in the nearest plans.
