### ISSUE TITLE
Barrel rolls animations aren't affected by the move animation speed slider

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2379]
I set my animation speeds to as fast as possible. (I was secretly hoping it would get rid of animations altogether, but that's neither here nor there) However, the barrel roll animation is still super slow, which is less than ideal when you're trying to play quick games

**Comment by boredompwndu** [comment]
also k-turn and talon roll animations seem to be unaffected by the move animation speed slider.

**Comment by Sandrem** [comment]
Fixed
