### ISSUE TITLE
Dice are rigged

### ISSUE THREAD

**Issue by ToshioMagic** [Sandrem/FlyCasual#2380]
I may sound tin foil hat here, but I've now played about 30 matches and I have to say that the dice are rigged in favor of the AI. Every single match the AI rolls an insanely higher than statistically average hits and evades. This has happened consistently over 30 matches. My dice on the other hand consistently blank out on defense and attack. Even with 4 dice!!! Is this some sort of compensation for the AI's poor action choices and limited ability?

**Comment by Sandrem** [comment]
Dice are fair - they are rolled in the same way for both human and AI.
This is common behavior - to ignore lucky results, and to remember when dice betrayed you.

More details here: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/60/?tab=comments#comment-3757043

I added "Stats" button to UI - you can see difference between rolled results and expected results.

**Comment by ToshioMagic** [comment]
So what you're telling me is.... I'm bad?! :,-(

I am looking at the stats. That's where I'm getting this data. The AI always has a higher hit/evade percentage than I do. Sometimes by 30%. Every match. I've been tracking it for the past 10 matches. So it sounds like I'm just statistically unlucky.

**Comment by ToshioMagic** [comment]
![image](https://user-images.githubusercontent.com/12516529/70328119-98433d00-1838-11ea-8756-f1f964f093d3.png)
A typical match. This one ended so fast due to the dice I could not get more data.

**Comment by ScottKarch** [comment]
That looks bad..  But you need to test thousands or 10's of thousands of
rolls to get a good idea of the rolls.  They should not be evenly
distributed, that's just not the way dice rolls work.    It's frustrating,
but you really need to see many many rolls to get an idea of the evenness
of the rolls.

**Comment by ToshioMagic** [comment]
Dice rerolls are definitely broken since they rely on dropping the dice in place and using the physics engine. Dice rerolls reroll as what they were originally a statistically improbably number of times.

**Comment by Sandrem** [comment]
> Dice rerolls

When a die is rerolled - it's starting rotation before that drop is randomized again. So previous result of die doesn't have any effect on new result of rerolled die.

Dice are fair.

**Comment by erfanilaghi** [comment]
It is a bit strange but I had the same feelings when I'm playing with different factions. It seems to me that dice roles for separatists and galactic republic are a little less accurate than the other factions.
I played multiple times as galactic republic and separatists against Rebel alliance and hit per dice roll of mine was less than a quarter and their hit per dice roll was more than half.
Does factions effect on dice roll by story line of star wars or some thing?
Or I'm blaming the game for losing?🤔🥲
