### ISSUE TITLE
FlyCasual won't open on macOS Catalina

### ISSUE THREAD

**Issue by mwhuss** [Sandrem/FlyCasual#2382]
When I try to open the macOS app on Catalina I get the error `The application "FlyCasual" can't be opened.` I suspect this is because the app isn't 64-bit.

**Comment by rune-b** [comment]
Did it work before you upgraded to Catalina?

**Comment by mwhuss** [comment]
I hadn’t tried before upgrading.

**Comment by rune-b** [comment]
OK. We will make sure to build for 64 bit for the next release, and hopefully that will help

**Comment by mwhuss** [comment]
Great! I'll keep an eye out and give it a try.

**Comment by ekename** [comment]
I have the same issue in Mojave so it may not be 64-bit related.

**Comment by jediknightusmc** [comment]
Also had this issue after Catalina upgrade, worked prior however.

**Comment by rune-b** [comment]
@ekename Has it worked for you before, on Mojave?

**Comment by ekename** [comment]
@rune-b I'm a first time user.  I was able to resolve my problem by using: chmod +x FlyCasual.app/Contents/MacOS/*

Works fine now.

**Comment by rune-b** [comment]
That's great!

@jediknightusmc @mwhuss Can you try ekename's solution above, to see if that also fixes the problem on Catalina?

**Comment by mwhuss** [comment]
Works for me after making it executable and right click+open since it's not signed by a valid developer account. Thanks!

**Comment by Nick-Saturday** [comment]
I was playing Fly Causal from time to time on my mac mini and on macbook air. It worked great.
After one of the updates last month FC does not work. I tried the newest and the oldest versions and the answer is always the same: _The application “FlyCasual.app” can’t be opened._

**Please explain step-by-step how you made it work on macs.**

When you write "chmod +x FlyCasual.app/Contents/MacOS/*" or "make it executable" I have no idea what you're saying :-(

**Comment by rune-b** [comment]
I don't have a Mac, but it seems they have tightened the security restrictions lately, to prevent people from running apps that doesn't come from the App Store. Maybe this article will help you:

https://support.apple.com/en-us/HT202491

**Comment by ekename** [comment]
@Nick-Saturday 

1. Open the Terminal

2. Use the change directory command (CD) to navigate to the folder where you have FlyCasual.app (for example - my FlyCasual folder is on the desktop so I'd type in: CD desktop/flycasual

3. Enter chmod +x FlyCasual.app/Contents/MacOS/* and hit return

You may need to open it initially with right click or command click.

Hopefully that works.

chmod is the command to change certain attributes of a file, in this case to make it executable which just means it'll run when you double click it.

**Comment by mmauschbaugh** [comment]
@ekename I am having the same problem and tried to follow your steps to make FC work on my MacBook pro but I keep getting : /usr/bin/CD: line 4: cd: desktop/flycasual: No such file or directory

When I try to use the CD command I have FlyCasual on my desktop just like your example. Any thoughts or help?

**Comment by mwhuss** [comment]
Try using `cd ~/Desktop/flycasual`
