### ISSUE TITLE
Big Base ships can't deploy at 45°

### ISSUE THREAD

**Issue by LucasMaida** [Sandrem/FlyCasual#2385]
Hi, Sorry if this is not the place, or if it's already reported. 

When playing Big base ships you can't set it up at 45° because it's outside the range 1 limit from the edges. However this deployment is legal by the rules, they state that you can deploy like this as long as the base touches the edge of the board.

Thanks!

**Comment by rune-b** [comment]
Hi
This is the right place to report this :) 

Proper deployment of large ships is not implemented yet, but is in the planned feature list
https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
