### ISSUE TITLE
Deathfire's ability causes crash

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2386]
Android 0.9.6

When using Deathfire's ability to perform an attack an error occurs after rolling the dice
![Screenshot_20191211-194923](https://user-images.githubusercontent.com/11047987/70650614-b8fffe00-1c4f-11ea-8a1c-e465ba479b10.png)

![Screenshot_20191211-194938](https://user-images.githubusercontent.com/11047987/70650628-bdc4b200-1c4f-11ea-9a74-e78ac2e3945a.png)

**Comment by rune-b** [comment]
It doesn't crash when using his ability to drop a bomb, only when performing an attack

**Comment by PeopleProductionDev** [comment]
I came here to confirm the same bug.
![Screen Shot 2020-06-11 at 4 14 15 PM](https://user-images.githubusercontent.com/62079521/84444425-fcd3c000-abfe-11ea-8087-fd4236b8f5fb.png)

**Comment by Sandrem** [comment]
Fixed by Arahain
