### ISSUE TITLE
Paige Tico, rotating arc 180 needs to be an option.

### ISSUE THREAD

**Issue by wavemanns** [Sandrem/FlyCasual#2390]
On the star fortress if your turret is set front-rear, you need to be able to rotate it rear-front with Paige Tico if you have veteran turret gunner as a second gunner. Obviously same issue if you have it set left-right, it needs to have the option to rotate to right-left.

**Comment by nix-7** [comment]
This would violate the rules of rotating;
Rules reference - rotate;
If a ship rotates a double turret arc indicator, it must select the other two
standard arcs it was not already selecting.
