### ISSUE TITLE
Translation in French

### ISSUE THREAD

**Issue by gwenaelforestier** [Sandrem/FlyCasual#2393]
Hello
i m ok for translate your software in french

if you send me 1 list of text
i translate it, in french 

if you are ok > write me an E-mail
gwenael.forestier@gmail.com  > subject : "TRANSLATE Star Wars X Wings FlyCasual"

**Comment by Lordka79** [comment]
slt j ai deja essayer de trouver cette liste hors j ai rien trouver

**Comment by Sandrem** [comment]
Thank you. In the nearest two months I don't plan to support anothe languages, but this featue maybe will be added later. I will contact you when development of this feature will be stared.
