### ISSUE TITLE
Crash on Foresight attack

### ISSUE THREAD

**Issue by only-one-suchy** [Sandrem/FlyCasual#2396]
Game on Linux crashesh when using Foresight attack on VCX-100 Light Freighter with docked attack shuttle.
[Player.log](https://github.com/Sandrem/FlyCasual/files/4011308/Player.log)

**Comment by rune-b** [comment]
Thanks for reporting. I get the same bug. Its the attak shuttle ability that doesn't work with Foresight.

**Comment by rune-b** [comment]
Snap shot works, so its probably something wrong with Foresight
