### ISSUE TITLE
game wont load

### ISSUE THREAD

**Issue by redwingsrox5** [Sandrem/FlyCasual#2403]
tried downloading the game, clicked on the flycasual run icon.  Error pops up saying it can't find UnityPlayer.dll  dunno why this is because that file is right below the run icon.

**Comment by rune-b** [comment]
Hi
Did you try to run it directly from the zip-file? You need to copy the files to a folder on your disk first

**Comment by redwingsrox5** [comment]
I’ll try again.  I extracted everything from the download spot to a folder and got the same error.  You saying copy the whole folder into another folder on a C drive or something?

**Comment by rune-b** [comment]
As long as you have extracted it to a folder it should work. What version of windows are you using?

**Comment by redwingsrox5** [comment]
I’ll post it when I get home.  I believe windows 10.  I extracted it into another windows folder from my download folder.  The file then shows an X wing icon which changed from the download folder, but same error.

**Comment by rune-b** [comment]
It is possible this could be caused by an antivirus program. You could try disabling your antivirus temporarily and see if it helps (just remember to turn it back on afterwards :) )

If not, it would help to see a screenshot of the entire error message

**Comment by xsacul** [comment]
Did it work for you?  Im having the same issue.

**Comment by redwingsrox5** [comment]
I loaded it on a tablet and it worked
