### ISSUE TITLE
Cassian getting free white stops

### ISSUE THREAD

**Issue by zeebot9** [Sandrem/FlyCasual#2408]
https://raithos.github.io/?f=Rebel%20Alliance&d=v8ZsZ200Z32XWWW46WW140Y5X132WWWW142Y73XWWWWWWY72XWWWW&sn=Unnamed%20Squadron&obs=

Using this list. Cassians stops are not stressing him and he is getting his action. I am NOT using Leia on these turns. I think each time it happened he may have be coordinated an action first.

**Comment by zeebot9** [comment]
Wedge just got a white K-turn as well. AP5 coordinated Cassian and then wedge did a Kturn and it was white.

**Comment by zeebot9** [comment]
AP5 Coordinated Bray and then Brays red move was a white also

**Comment by zeebot9** [comment]
That time it happened to Cas but I had not done a Coordinate with AP5. Again just want to confirm Leia was not used during any of these.

**Comment by Sandrem** [comment]
I played few matches with this list - and I cannot reproduce this bug.

If you can reproduce it, please, next time provide replay (path: "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual\Second Edition\Replays")
