### ISSUE TITLE
Enhancement: TIE SF Gunner shot priority

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#2409]
The AI flying TIE SFs will typically take the best available shot first, even if it's in the ship's rear arc.  By doing so, it forgoes its opportunity for a bonus attack.  Ideally, it would take its best forward arc shot followed by its best rear arc shot.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Proposed-AI-improvements
