### ISSUE TITLE
IOS Installation

### ISSUE THREAD

**Issue by vine90** [Sandrem/FlyCasual#2410]
Cant seem to get it running on my IOS devices, can get it onto the device via apple configurator but it wont run, its unable to install on xcode and imazing. Is there another way to install?

**Comment by Sandrem** [comment]
App is provided as unsigned IPA file. To install it - tou need to use Cydia Impactor and to sign it by your personal key (you need to generate it first, if you don't have it). Try to search tutorials in Google/Youtube for more detailed instructions.
