### ISSUE TITLE
Crash when restarting game

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2424]
Latest dev branch. Windows.

When I restart the game from the menu, in the middle of Vectored Thrusters ability, the game crashes

How to reproduce:

![image](https://user-images.githubusercontent.com/11047987/72206749-d401a000-3491-11ea-812b-1d3a92cbb62b.png)
![image](https://user-images.githubusercontent.com/11047987/72206757-e085f880-3491-11ea-9026-202509cbc26e.png)
![image](https://user-images.githubusercontent.com/11047987/72206759-e4197f80-3491-11ea-8189-92f4397155ca.png)

**Comment by Sandrem** [comment]
Cannot reproduce in current dev-branch.
