### ISSUE TITLE
Spare parts cannister can't be equipped by Jumpmaster.

### ISSUE THREAD

**Issue by haukurv** [Sandrem/FlyCasual#2431]
I equip Jumpmaster with the Punishing One title and then with an astromech.
The option to equip Spare parts cannister does not show up in modifications.
The same is true with the Scurrg, where you can also add astromech by title.

**Comment by rune-b** [comment]
Thanks for reporting. I get the same behavior. 

0.9.6 Android

**Comment by rune-b** [comment]
Similar bug: #2510
