### ISSUE TITLE
VT-49 Decimator cannot perform the reload action

### ISSUE THREAD

**Issue by heydude6** [Sandrem/FlyCasual#2432]
I don't mean the reload action is glitched. It's just that in the menu when you're choosing actions, reload does not show up as an option. Probably just an oversight.

EDIT: I decided to add it back in myself. First time using Github. Is the code in my pull request any good?

**Comment by rune-b** [comment]
Hi
The pull request is good, but the decimator doesn't have the reload action... Are you maybe confusing it with rotate? 

![Decimator_Patrol](https://user-images.githubusercontent.com/11047987/72501972-9063b900-3838-11ea-82d6-6e495660c333.png)

**Comment by heydude6** [comment]
Dear God! You're completely right! I got to the two icons completely confused! I'm so sorry for bothering you like this.
