### ISSUE TITLE
Now there were 6...

### ISSUE THREAD

**Issue by seagie** [Sandrem/FlyCasual#2435]
Playing against 8 AI tie fighters, 2 games in a row they lined up in a corner right on the edge and the two on the edge of the board flew off the edge turn 1. Now there were 6.

**Comment by rune-b** [comment]
That has never happened to me. Did they set up facing the edge, or did they turn off the board? 

Did you play against a random AI squad, or one you made yourself? If so, do you remember which pilots?

Where did you set up your own ships? Right across from the AI or elsewhere? 

If this happens to you again, it would be helpful if you could take a screenshot of the entire board in 2d mode

**Comment by seagie** [comment]
As far as I could tell/remember they setup facing down field and executed a straight maneuver that was judged to be off the board. It was a random AI squad, 8 Empire TIEs, 7 Academy and I think Iden.  I was setup opposite corner both times.
I replayed it cause it was so strange, and the same setup happened, with the same fly off the board scenario.
Was playing on Android.
Will screenshot if I see it again.

**Comment by rune-b** [comment]
Could you continue playing after this happened, or did the game get stuck?

**Comment by seagie** [comment]
Could continue playing. game just treated the ships as destroyed.

**Comment by Sandrem** [comment]
Still cannot reproduce.
