### ISSUE TITLE
Auto Configuration Equip

### ISSUE THREAD

**Issue by seagie** [Sandrem/FlyCasual#2436]
Example: when selecting ships for a squad, X-Wings don't auto equip 0 pt S-Foil configuration.

**Comment by rune-b** [comment]
Hi. I agree that this would be nice

**Comment by seagie** [comment]
Ya. Definitely on the low priority side of things, but it has happened a few time now I have started a game without S-foils and it is annoying.
BTW, thanks for such an awesome product!

**Comment by rune-b** [comment]
The candidates for auto equip are, as far as I can see:

S-Foils for the T-65 and T-70
Pivot Wing for the U-Wing

Anyone else?

**Comment by seagie** [comment]
Thanks!
