### ISSUE TITLE
In development build. AI talon rolls give choice then no OK button.

### ISSUE THREAD

**Issue by mishari27** [Sandrem/FlyCasual#2441]
I got the development build to get the new wave6 points. The during play when the AI ship talon rolled, it asks me to give the best position from forward, center or backwards, but no way to accept the choice. and the game can't continue.

![image](https://user-images.githubusercontent.com/54389008/72870646-c4881f80-3cf9-11ea-9392-c9d7febccba4.png)

**Comment by rune-b** [comment]
Hi. This is a known bug in the development branch. The workaround is to only play against AI ships without tallon roll

**Comment by Sandrem** [comment]
Known issue.

IMPORTANT:
I changed format of squads to be compatible with popular squad builders (correct XWS 2.0).
If you used development branch - please, before using of v0.9.7, delete folder "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual\Second Edition\RandomAiSquadrons" to avoid errors during loading of random AI squads.
