### ISSUE TITLE
Errors during import/export of squadrons in XWS format

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#2445]
If you cannot export/import squadron in XWS format between Fly Casual and any another app that supports XWS format - please, report this here, with your list and name of another app.

**Comment by Sandrem** [comment]
There is a bug with all cross-faction cards with same name. (For example, Resistance Leia is missing)

**Comment by Sandrem** [comment]
https://i.imgur.com/XAlQqfP.png

**Comment by BowTiesRKool** [comment]
I'm having an issue, but think it's related to the above.  I failed an import, but then tried to manually make the squad and noticed that C-3PO isn't found in the Resistance crew list.  Presumable due to above issue with cross-function cards with the same name.

**Comment by Sandrem** [comment]
All bugs are fixed
