### ISSUE TITLE
Mac will not open Fly Casual.

### ISSUE THREAD

**Issue by Damo1701** [Sandrem/FlyCasual#2446]
![Screenshot 2020-01-23 at 13 22 21](https://user-images.githubusercontent.com/31852858/72988026-6c2d4c80-3de3-11ea-98b6-d310f8486be0.png)
![Screenshot 2020-01-23 at 13 22 54](https://user-images.githubusercontent.com/31852858/72988090-89621b00-3de3-11ea-903a-c328eca4bf2a.png)

Just tried to run the new version of Fly Casual and my MacBook wouldn't open it.  I could play previous versions by allowing the game to run in the security settings.  I don't have that option this time.

**Comment by Sandrem** [comment]
I don't have MacOS to check this behavior.

I googled for few solutions:
https://support.apple.com/en-us/HT202491
https://www.fireebok.com/resource/how-to-fix-that-app-can-not-open-on-macos-catalina.html
https://jimmytechsupport.com/macos-catalina-tip-what-to-do-when-an-app-cant-be-opened-because-apple-cannot-check-it-for-malicious-software/

Please, try them and tell about result.

**Comment by Damo1701** [comment]
Unfortunately, I don't get those particular error messages, just the one shown in the screen shot.

However, it might be down to this notarisation system Apple have just implemented, meaning that software for Macs may need to be submitted for notarisation, which is different from it being submitted to the Mac App Store, it's just where Apple scans it to ensure it isn't malicious, and adds a code to allow the Mac OS to run it.

Although, the articles don't say whether it's a feature that Apple charges the software developer for.

**Comment by Damo1701** [comment]
![Screenshot 2020-01-23 at 13 41 29](https://user-images.githubusercontent.com/31852858/72989401-18703280-3de6-11ea-8987-bd7f01435ad3.png)

As you can see, there is no option to bypass the OS-lock the articles suggested, which was all I had to do with the previous Fly Casual builds, must just be an issue with the new version perhaps?

**Comment by Sandrem** [comment]
Thank you, I will check how I can approve my app.

**Comment by Damo1701** [comment]
If it helps, as I do have a Mac (but zero coding experience) I can trial any Fly Casual on the Mac Environment for you, if you would like?

**Comment by fzikowsky** [comment]
I checked it on my mac and i cant open it.

> 23.01.2020, 14:58:34 com.apple.xpc.launchd[1]: Could not find and/or execute program specified by service: 13: Permission denied: /private/var/folders/l2/rgx5wtqd4xd1_z59h86wh3krcb1zmq/T/AppTranslocation/F781A8FB-0C9C-46CA-9315-DCC47BC380FA/d/FlyCasual.app/Contents/MacOS/Fly Casual
23.01.2020, 14:58:34 com.apple.xpc.launchd[1]: Service exited with abnormal code: 78

**Comment by oliver-phet** [comment]
This worked for me: https://superuser.com/questions/898124/the-application-someapp-app-can-t-be-opened

**Comment by mwhuss** [comment]
Same issue as https://github.com/Sandrem/FlyCasual/issues/2382, see the steps there.

**Comment by Damo1701** [comment]
Just an FYI for whomever does programming, as I can't open any version of Fly Casual since the update for some reason now.

"After extensive trial-and-error, and a lot of fruitless Googling, I found the solution required modifying the executable status of the "inner" application file. This line: 
chmod +x SomeApp.app/Contents/MacOS/*

Fixed the problem in all cases that I observed. The +x flags a file as executable, and the only file in the /Contents/MacOS/ directory is a binary representing the actual file that should be executed when you double-click the application (a .app file is really just a folder).

Hope this helps someone else!"

**Comment by Damo1701** [comment]
> Same issue as #2382, see the steps there.

![Screenshot 2020-01-23 at 17 39 47](https://user-images.githubusercontent.com/31852858/73008936-782b0580-3e07-11ea-8042-4b2985bdc428.png)

Still no luck I'm afraid, unless I'm doing something wrong.  Fiddling with any type of coding has never gone well for me, I just can't get my head around it.

**Comment by Sandrem** [comment]
deichernc from Reddit:
> The chmod +x worked. Needed to be done on the single 'Fly Casual' file in the FlyCasual.app package contents folder (open a New Terminal in FlyCasual.app/Contents/MacOS/Fly Casual). Then the normal Ctrl+click - Open works as usual.

**Comment by Damo1701** [comment]
Phew, I think I've got it now, it eventually triggered the "Open Anyway" in the settings.
Thanks for the help guys.

**Comment by jfcamera** [comment]
I'm getting the same issue and not quite understanding the solution. Can someone explain what I need to alter to make this work? Thank you.

**Comment by Damo1701** [comment]
> I'm getting the same issue and not quite understanding the solution. Can someone explain what I need to alter to make this work? Thank you.

Create a folder on your desktop with the Fly Casual App in it.
![Screenshot 2020-01-24 at 11 57 20](https://user-images.githubusercontent.com/31852858/73067629-20d97380-3ea1-11ea-9642-5dc0965b4c35.png)

Navigate to Utilities, Terminal.

![Screenshot 2020-01-24 at 11 57 43](https://user-images.githubusercontent.com/31852858/73067649-2d5dcc00-3ea1-11ea-97bd-6a26cbe13b1f.png)
![Screenshot 2020-01-24 at 11 57 51](https://user-images.githubusercontent.com/31852858/73067650-2d5dcc00-3ea1-11ea-82ae-42b94533affd.png)

Type the following into Terminal:
![Screenshot 2020-01-24 at 11 58 36](https://user-images.githubusercontent.com/31852858/73067684-40709c00-3ea1-11ea-971b-ecde6b160201.png)

You should see the following:
![Screenshot 2020-01-24 at 11 59 03](https://user-images.githubusercontent.com/31852858/73067701-49616d80-3ea1-11ea-8a32-8448c2d577e5.png)

Then type:
![Screenshot 2020-01-24 at 11 59 31](https://user-images.githubusercontent.com/31852858/73067754-685fff80-3ea1-11ea-986d-385defcf7629.png)

Once you have:
![Screenshot 2020-01-24 at 11 59 58](https://user-images.githubusercontent.com/31852858/73067769-70b83a80-3ea1-11ea-8093-6a58bc7a72d8.png)

Press enter, and Fly Casual should work, it did for me.

**Comment by jfcamera** [comment]
Awesome thank you!

**Comment by ekulnesro** [comment]
I was having this problem with earlier versions as well, but I stumbled upon a thread (unfortunately I couldn't find it again) that mentioned that opening the .zip with MacOS's default unzipper was causing this issue. Ever since then I've been using the Unarchiver tool to unzip, and haven't had an issue in getting the "Open Anyway" prompt. Hope this works for some of you as well.

**Comment by hmhouk** [comment]
None of these things have worked for me. I have tried three different ways to get it to run, but none of them work. This is what keeps coming up...
![Screen Shot 2020-03-21 at 2 21 20 PM](https://user-images.githubusercontent.com/47408269/77236814-3e644a00-6b7f-11ea-8e03-f746a14b3f95.png)

**Comment by hmhouk** [comment]
Nevermind. I fixed it by adding the line /Applications in front of /FlyCasual.app.
