### ISSUE TITLE
macOS: Game no longer opens to the display options screen

### ISSUE THREAD

**Issue by mwhuss** [Sandrem/FlyCasual#2449]
Usually when I launch the game on macOS I get a window that lets me pick a resolution and if I want to run in windowed mode or not. This no longer launches for me and any combination of control/option/command + click doesn't launch it either.

I also tried changing the following key in `DefaultPreferences.plist` with no success.

```
<key>Screenmanager Is Fullscreen mode</key>
<string>False</string>
```

**Comment by NeydTheHarlequin** [comment]
Having the same issue on Linux

**Comment by goudsmit** [comment]
Work around for macOS:
`open -a /Applications/FlyCasual.app --args -screen-fullscreen 0 -screen-height 800 -screen-width 1000`

**Comment by TNG-Wing** [comment]
Having same issue on Windows 10

**Comment by ebicher** [comment]
Here is the command I used to open it in a window on Ubuntu 18.04. 

./FlyCasual.x86_64 --args -screen-fullscreen 0 -screen-height 800 -screen-width 1000

**Comment by Sandrem** [comment]
Video Options were added.
