### ISSUE TITLE
Can't reroll dice with Advanced Slam + Target Lock

### ISSUE THREAD

**Issue by jonronix5** [Sandrem/FlyCasual#2450]
Using the Imperial Alpha-Class Star Wing, I build it so that it has Advanced Slam, Advanced Photon Torpedoes, and the OS-1 Arsenal Loadout. When I am close enough to an enemy ship, I move, Slam, and Target Lock. All of that is successful. After the enemy moves and is in Range 1, I use the Torpedoes. The attack works fine, but I can't use Target Lock to reroll my dice. The Advanced Photon Torpedoes function to convert a hit to a crit does work.

**Comment by Spyke114** [comment]
That's actually functioning correctly. OS-1 load out allows you to shoot ordinance while disarmed (which you normally can't do), but at the trade-off of not being able to spend a lock during that attack.

**Comment by Sandrem** [comment]
Not a bug. Closed.
