### ISSUE TITLE
Moralo Eval abilty to leave and return to map. cannot rotate ship to face correct direction

### ISSUE THREAD

**Issue by Sheeno8585** [Sandrem/FlyCasual#2451]
This could just be me.  but when I fly Moralo off board and return him next turn i cannot change his direction to face back onto the board.

**Comment by rune-b** [comment]
I can rotate him with the Q and E keys just as when placing the ship during setup

Are you playing on a computer or phone/tablet?

**Comment by rune-b** [comment]
Though it would be nice if the was rotated automatically to match the edge he's entering from

**Comment by Sandrem** [comment]
Fixed by rune-b
