### ISSUE TITLE
Dengar not getting bonus attack in retaliation.

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2455]
Dengar's ability allows him to shoot back against opponents in front of him with any weapon pointed that way, torpedoes and cannons included. However, I had his primary pointed sideways with Autoblaster cannon equipped and was not getting the option to return fire when shot at.
![Screenshot_20200124-130252_Fly Casual](https://user-images.githubusercontent.com/49449213/73096801-aa923c80-3eb3-11ea-8990-8dd054cc7d57.jpg)

**Comment by Sandrem** [comment]
Works correctly in current version.
