### ISSUE TITLE
AI uses Human's Saw Gerrera (Pilot) ability

### ISSUE THREAD

**Issue by thomedwards** [Sandrem/FlyCasual#2456]
When an AI ship that does not have Saw Gerrera (Pilot) in its crew, but Saw is in the Human/opposing crew, the AI ships use Saw's ability (re-roll one die if damaged).

Have not checked to see if Human can use the ability if Saw is not in own crew but is in AI/enemy crew.

**Comment by Sandrem** [comment]
Fixed
