### ISSUE TITLE
Del Meeko's ability triggered by opponent

### ISSUE THREAD

**Issue by otuv** [Sandrem/FlyCasual#2457]
While a _friendly_ ship at range 0-2 defends against a damaged attacker, the defender may reroll 1 defense die.

The ability itself is correct but is here seen used by the AI who does not have Del Meeko on the team.

![Screenshot from 2020-01-24 23-33-47](https://user-images.githubusercontent.com/16488095/73109284-06d07d00-3f03-11ea-9bbf-e44652a5fdf5.png)

**Comment by Sandrem** [comment]
Fixed
