### ISSUE TITLE
Serissu ability being used by scum opponent

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2458]
Hi - just running the latest version of Fly Casual (grabbed it about two hours ago) and noticed that when I have Serissu vs a scum AI, the scum AI is using Serissu's ability.

**Comment by AntipodeanOrk** [comment]
Amend that - it is when Serissu is present against ANY AI - and they use the ability at any range!

**Comment by Sandrem** [comment]
Fixed
