### ISSUE TITLE
AI opponent can use opposing player's abilities 

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#2462]
I have Drea in my scum squad. Every generic TIE/FO in the AI's squad can use the ability to reroll an attack die, regardless of arc.

**Comment by rune-b** [comment]
AI can use Serissu's ability too. Seems there is a general problem with opponent's abilities in 0.9.7

![Screenshot_20200126-203745](https://user-images.githubusercontent.com/11047987/73140685-f1cb2980-407b-11ea-85a7-4b2c87a244ca.png)

**Comment by rune-b** [comment]
According to a comment on reddit, the same happens with Saw's ability

**Comment by rune-b** [comment]
See also:

#2458
#2457
#2456

**Comment by wavemanns** [comment]
Can confirm it happens to me with Serissu as well, I have been using this ship heavily and today was the first time I actually noticed the scroll text in the bottom right where it says "AI uses Serissu's ability" and it answered my questions as to why my opponent has been getting rerolls like candy all week.

**Comment by mingodave42** [comment]
Encountered this today: the Aggressor (6x Blue Recruit RZ-2 with Heroic) uses my Drea Renthal's ability. This should be restricted to friendly ships.

My list:
Ketsu + Shadow Caster + Tactical Scrambler + Informant
Drea + Dorsal Turret + Hotshot Gunner + Snapshot
Mining Guild Surveyor + Crack Shot
Spice Runner + Deadman's Switch

**Comment by Sandrem** [comment]
Fixed
