### ISSUE TITLE
Moralo Eval loses if in reserves when all friendlies destroyed

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#2463]
Even if he has hull and charges left, if Moralo Eval leaves the board and goes into reserves, the game ends if the YV666 is the last ship.

**Comment by rune-b** [comment]
Confirmed

![Screenshot_20200129-163655](https://user-images.githubusercontent.com/11047987/73371197-9e442000-42b5-11ea-9227-3894448d77cb.png)

**Comment by Sandrem** [comment]
Fixed
