### ISSUE TITLE
Jan Ors ability doesn't work with Snap Shot arc

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2464]
0.9.7

Jan Ors equipped with snap shot should be able to use her ability on a friendly ship in her front arc, even if the turret is pointing elsewhere. But it does not work 

![Screenshot_20200127-163457](https://user-images.githubusercontent.com/11047987/73188650-7d4bc580-4123-11ea-8e14-0163882f3157.png)

**Comment by M1ntyPunch** [comment]
My understanding is that "in arc" abilities don't work with most secondary (upgrade) weapons, the only exception is a turret (ex. Drea). Snap shot (and foresight) are non turret secondary weapons, and therefore don't contribute to the ship's arc (where "primary" arcs and turret arcs do).

**Comment by Sandrem** [comment]
Snap Shot allows to shoot from front sector, but doesn't give ship new arc.
Not a bug.

**Comment by rune-b** [comment]
But it does give the ship a new arc. It is clearly printed on the card. Its just like any other secondary weapon

**Comment by Sandrem** [comment]
https://xwing-miniatures-second-edition.fandom.com/wiki/Snap_Shot

See in comments discussion that is started by "Does snapshot count as being an arc for effects such as rebel hawks?"

**Comment by rune-b** [comment]
Hmm. Interesting. Is that a new ruling from FFG?
