### ISSUE TITLE
AI Processing Time

### ISSUE THREAD

**Issue by iincarna** [Sandrem/FlyCasual#2468]
The AI dial-selection time is very long. It's much longer than it was in previous versions

**Comment by rune-b** [comment]
I have the same experience on my Android phone.

What device do you play on?

**Comment by iincarna** [comment]
I play on a windows 10 PC.
This update is the only one where this lengthy dial-selection is onerous.

**Comment by BusterHigh** [comment]
Having the same issue on both Android phone and Windows 10 PC. Significantly longer on the Android.

**Comment by Sandrem** [comment]
I tested maneuver planning of AI-controlled 8 TIE Fighters vs player's 1 X-Wing with lowest framerate.

0.9.8: ~100 seconds
dev-branch: ~14 seconds

AI-controlled 8 TIE Fighters vs AI-controlled 8 TIE Fighters
0.9.8: 247 seconds
dev-branch: 65 seconds

AI-controlled 3 X-Wing vs 3 player's X-Wing
0.9.8: ~23 seconds
dev-branch: ~7 seconds

**Comment by rune-b** [comment]
Test on my low-end Android phone with quality set to Fast. 
1 X-Wing vs. 8 AI TIEs. AI Maneuver planning, turn 1

dev-build received on Slack last Friday: 55s
0.9.6: 51s

So it seems the latest changes have gotten performance back to where it was 👍

**Comment by rune-b** [comment]
Same test on 0.9.8:
96s
