### ISSUE TITLE
Couldn't find your email. Apologies for the issue ticket.

### ISSUE THREAD

**Issue by ToshioMagic** [Sandrem/FlyCasual#2473]
I do CAD if you need help with models. What format do you need them in? Here is sample of my work:

![image](https://user-images.githubusercontent.com/12516529/73478270-cbe7a280-4363-11ea-8857-420fb476fe6c.png)
![image](https://user-images.githubusercontent.com/12516529/73478294-d43fdd80-4363-11ea-9d35-ad2e718cfc26.png)
![image](https://user-images.githubusercontent.com/12516529/73478331-e4f05380-4363-11ea-8df2-8c95dc25cad0.png)
![image](https://user-images.githubusercontent.com/12516529/73478349-ecaff800-4363-11ea-8ba1-fdec84b37974.png)

**Comment by Sandrem** [comment]
Hi.
We have Slack workspace for developers, you are welcome: https://join.slack.com/t/flycasualgame/shared_invite/enQtOTE4NTI2NzQ2ODE5LTI4YTdmNTFhMjFkNDllODBmYTRiNmQxZTZiMDc4YmI5ZWI0OTQzODBlN2JmN2RkYWQ0YTU3ZGZmMDczZWVhMGM
Or contact me using my e-mail: oogoeroo@gmail.com

We use ".obj" format for models.
Examples: https://github.com/Sandrem/FlyCasual/tree/development/Assets/ImportedAssets/Tabletop%20Simulator/Ships
