### ISSUE TITLE
Informant being skipped crashes the game

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2474]
When informant is not called during the setup phase, the game crashes at the first system phase. (Because listening device points to null)

**Comment by boredompwndu** [comment]
![image](https://user-images.githubusercontent.com/8730661/73502215-3addef00-4396-11ea-8d67-9f9300610c2e.png)


![image](https://user-images.githubusercontent.com/8730661/73502226-4204fd00-4396-11ea-9052-3c9f1f2cc0c8.png)

**Comment by boredompwndu** [comment]
wait, informant is skippable. Can we do a check to see if listening device doesn't point to null before attempt to check listening device?

**Comment by boredompwndu** [comment]
From
Assets/Scripts/Model/Content/SecondEdition/Upgrades/Crew/Informant.cs


            if (new BoardTools.DistanceInfo(HostShip, TargetShip).Range < 3)
            {
                Messages.ShowInfo("Listening Device: " + TargetShip.PilotInfo.PilotName + " flips dial faceup");
                Roster.ToggleManeuverVisibility(TargetShip, true);
                TargetShip.AlwaysShowAssignedManeuver = true;
            }

**Comment by rune-b** [comment]
A null check there would solve the crash issue, yes. But Informant is not optional to use, so I will just remove the skip button
