### ISSUE TITLE
Dials are changing to the wrong dial for the ship

### ISSUE THREAD

**Issue by pakirby1** [Sandrem/FlyCasual#2477]
I was playing Soontir and it replaced my dial with another ships dial.  The dial was not the same dial as another ship in the current game.  Please fix.

**Comment by rune-b** [comment]
Has this happened more than once for you? Do you have any more details about the game? It is difficult to fix this error if we don't know how to make it appear.

If it happens again, please take a screen shot

**Comment by pakirby1** [comment]
Not sure.  It just happened while I was playing.  I did notice that it displayed the last dial I set as if it was not set at the same time it displayed the wrong dial on the ship I selected.  So it displayed two dials at the same time briefly.

**Comment by Sandrem** [comment]
Still cannot reproduce.
