### ISSUE TITLE
Padme too strong

### ISSUE THREAD

**Issue by Spyke114** [Sandrem/FlyCasual#2480]
I just had a match where I was in Padme's arc and had a roll of 3 focuses and 2 hits. I used Saw crew effect to try to make that 2 hits and a crit but it caused me to lose a shield as normal and didn't change any of the focus results at all.

**Comment by rune-b** [comment]
Just tested this, and it worked as expected for me. I rolled two focus results, and when I used Saw only one of them were changed into crit

![image](https://user-images.githubusercontent.com/11047987/74941476-5e271780-53f3-11ea-9bcf-b02e0628594f.png)

![image](https://user-images.githubusercontent.com/11047987/74941512-7139e780-53f3-11ea-9f20-93cadab80ebd.png)

**Comment by Sandrem** [comment]
Still cannot reproduce.
