### ISSUE TITLE
B-Wing Foils cause crash

### ISSUE THREAD

**Issue by iincarna** [Sandrem/FlyCasual#2481]
if you destroy your target and then click on a different (invalid) ship for your second attack the game will crash

**Comment by rune-b** [comment]
Thanks for reporting
This happens even if the first ship isn't destroyed 

![Screenshot_20200202-201332](https://user-images.githubusercontent.com/11047987/73613740-d078b900-45f8-11ea-91f7-9791a3acf13d.png)
