### ISSUE TITLE
R4 Astromech doesn't seem to work

### ISSUE THREAD

**Issue by iincarna** [Sandrem/FlyCasual#2482]
R4 Astromech on resistance ships does not reduce the difficulty of maneuvers

**Comment by rune-b** [comment]
Strange. Is doesn't work for scum or rebels either. Pretty sure it has worked before

![Screenshot_20200202-195755](https://user-images.githubusercontent.com/11047987/73613509-ca81d880-45f6-11ea-8e28-cea75dce5fc1.png)
![Screenshot_20200202-195801](https://user-images.githubusercontent.com/11047987/73613512-d372aa00-45f6-11ea-8732-0c1ef80e6998.png)

**Comment by rune-b** [comment]
Similar abilities like Nien Nunb and L3-37 works as they're supposed to
