### ISSUE TITLE
1 ship frozen at activation

### ISSUE THREAD

**Issue by wimplo-from-krypton** [Sandrem/FlyCasual#2484]
1 ship on my squad remained frozen at activation unable to flip dial while the game proceeded to the next phase and went on with combat.  The very next activation it went on as normal but I missed a round with that ship.

Sorry no screenshots

**Comment by rune-b** [comment]
That is strange. Do you remember which ship it was and which upgrades it had?

**Comment by wimplo-from-krypton** [comment]
I don't remember, it was one of my many squads I was testing.  It was a 3 ship squad and the one that froze was either medium or large base.

Sorry...

**Comment by Sandrem** [comment]
Still cannot reproduce.
