### ISSUE TITLE
No more prompt at start of game for which monitor to use

### ISSUE THREAD

**Issue by wimplo-from-krypton** [Sandrem/FlyCasual#2485]
Before the newest version release every time I double clicked on the icon to play I would receive a prompt on how I wanted the graphics and which monitor to play on...  now the game just starts on the primary "main" screen.

Was a useful prompt on my 4 screen setup.

**Comment by RockoTDF** [comment]
Having the same problem. To add to this, I've tried clearing FC off of my computer and reinstalling to no avail.  Right now graphics are rendering in potato mode and I'd like to get them looking decent.

**Comment by Sandrem** [comment]
Monitor selection is added to "Video" options in v1.0
