### ISSUE TITLE
Fifth Brother Pilot Possible?

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2488]
This is only a request. Sorry if I'm posting in the wrong place.

Would LOVE to get a Tie Advanced v1 Fifth Brother Pilot in the game.

Thanks!

**Comment by rune-b** [comment]
Hi
All missing cards are on the todo list, and will get there eventually, but it is time consuming work, and FFG just keep releasing more and more of those darned things... :)

 It is not necessary to report these as bugs.

**Comment by TNG-Wing** [comment]
I understand. Thank you for all the great work, time, and sacrifice you all do to bring a great experience to us all. I was just really excited about that one pilot, but I'm grateful for all you've already done.

Thanks again!
