### ISSUE TITLE
Enemy AI uses my serissu ability because the attacker is range 1 of serissu

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2490]
![image](https://user-images.githubusercontent.com/8730661/73703284-683fdb00-46bd-11ea-9e09-7caac177f06e.png)

**Comment by boredompwndu** [comment]
I originally misunderstood the bug. Everyone gets serissu's reroll everywhere, regardless of location or team.

**Comment by ShivanReaper** [comment]
It is also happening with Del Meko's ability

**Comment by Sandrem** [comment]
Fixed
