### ISSUE TITLE
Serissu's ability can be used on 0 dice

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2491]
![image](https://user-images.githubusercontent.com/8730661/73704645-b525b080-46c1-11ea-9bb0-51a00791faa3.png)
Miraculously this doesn't crash the game

**Comment by boredompwndu** [comment]
Bleh. mashed the screenshot key too much, I swear the dice tray had 0 dice because the ship had a structural damage

**Comment by Sandrem** [comment]
Fixed
