### ISSUE TITLE
Ship killed by critical effect hangs game

### ISSUE THREAD

**Issue by azuredarkness** [Sandrem/FlyCasual#250]
If ship is killed by critical effect not while dealing damage - I think it was Stunned Pilot (After you execute a maneuver that causes you to overlap either another ship or obstacle token, suffer 1 damage) or maybe Console Fire (At the start of each combat phase, roll 1 attack die. On a Hit result, suffer 1 damage), the game would not proceed. The engine keeps looking for a ship of piloting skill X, and can't find it (since it's dead).
There's no way to proceed except to (rage) quit.

**Comment by Sandrem** [comment]
Problem was caused by "Stunned Pilot" crit. "Console Fire" works normally.
Fixed.
