### ISSUE TITLE
AI target priorities

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2500]
The AI should prioritize potential killing shots higher

Here the AI chooses to shoot at an undamaged YT-1300 instead of a Fireball with 1 hull left
![image](https://user-images.githubusercontent.com/11047987/74060667-c1c04680-49ea-11ea-8620-0e0cc74b5927.png)

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Proposed-AI-improvements
