### ISSUE TITLE
Can't place Jumpmaster at 45 degree angle at setup

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2501]
I get a "Place the ship in the highlighted area" error.

**Comment by Zhaph** [comment]
Same issue a Decimator, assume all large based ships will fail if placed at an angle, although this is an allowed state if the base is as far back as it can be.

It might actually be allowed if placed correctly, but it's very hard to get precise placement on a phone when the ship centre jumps to the touch point.

**Comment by pinosante** [comment]
> It might actually be allowed if placed correctly, but it's very hard to get precise placement on a phone when the ship centre jumps to the touch point.
It's not possible to do so, neither on a desktop. Placing a ship at an angle doesn't work. Wherever you try to put it.

**Comment by zeebot9** [comment]
How do you rotate ships to place them? I can only place facing forwards.

**Comment by Sandrem** [comment]
Known issue, this rule will be added later.
