### ISSUE TITLE
Dengar's Pilot ability only works if mobile arc is forwards. 

### ISSUE THREAD

**Issue by BenFett** [Sandrem/FlyCasual#2504]
My dual arc torpedo Dengar is very very sad.

**Comment by VexingVision** [comment]
This is the correct behaviour. Dengar's ability only works if it triggers in his front arc.

Dengar's turret arc does not have to be lined up to the front to trigger this, but the triggering ship needs to be inside his firing arc to trigger his bonus attack.

**Comment by BenFett** [comment]
Correct, the enemy ship has to be in the front arc to activate his ability.

Currently in the game his turret arc has to be forwards for his ability to trigger though. I tested with Torps and Cannons and the ability never triggered unless Dengar's arc was pointed forwards.

**Comment by rune-b** [comment]
Thanks for reporting. I will fix
