### ISSUE TITLE
Daredevil does a hard boost through other ship

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#2507]
![daredevil error](https://user-images.githubusercontent.com/47582934/74129144-ea7b4400-4b82-11ea-8b50-7b1be0d8ea1e.png)

See attached photo and title, I did a hard red with Vonreg (daredevil equipped) and this happened.  I have seen hard red boosts fail before, so I suspect that in this case the program checked for a normal soft white boost, said it would clear, and then executed the red boost that overlapped.

**Comment by rune-b** [comment]
I am not able to reproduce this. Has it happened more than once for you?

I have seen various bugs of ships physically overlapping each other in the past, and assume this is part of the same problem.

**Comment by RockoTDF** [comment]
> I am not able to reproduce this. Has it happened more than once for you?
> 
> I have seen various bugs of ships physically overlapping each other in the past, and assume this is part of the same problem.

I just did it again with no issues.  Just two Vonregs on a mat with no rocks, had them fly close, and had the one do the 1 Hard turn daredevil boost over the other one.  This is not a case of issues I saw in the past where ships were able to boost onto ships who had decloaked/boosted/BRed into their position (which was fixed).

**Comment by rune-b** [comment]
I was able to get this slight overlap with two Vonregs, but it doesn't seem to happen every time

![image](https://user-images.githubusercontent.com/11047987/75112092-c6b70400-5640-11ea-956a-2c3bb947fa72.png)

**Comment by Sandrem** [comment]
Fixed
