### ISSUE TITLE
Mouse edge panning

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2509]
Thanks again for all the great work.

Is there any way to switch off the mouse control that causes the entire screen to pan when the pointer nears the edge of the screen? It's so sensitive that when I try to click on the NEXT button, the whole screen pan. This also happens at all the other buttons and hover-over text near any screen edge.

It wasn't so much of an issue until 0.9.7.0, when we could only go full screen (a nice option which I hope can return.)

Thanks again, so appreciate all the work you all do!
:)

**Comment by Sandrem** [comment]
I changed zone from 5 pixels to 1 pixel. I think this will help.

**Comment by TNG-Wing** [comment]
Awesome, thank you!
