### ISSUE TITLE
Star Wing Double Missile Slot Upgrade Issue

### ISSUE THREAD

**Issue by M1ntyPunch** [Sandrem/FlyCasual#2510]
When creating the list, using the Star Wing Arsenal Loadout grants a second missile slot. However, neither of the double missile options (barrage rockets and diamond boron missiles) appear. Additionally, when attempting to use the feature where any upgrade can be placed on any ship to circumvent the above issue and put barrage rockets on the Star Wing, the game got very upset (red code window appeared). Though it allowed me to start a game, in which the autosave malfunctioned and I had no ships.

Other possibly relevant detail: I was using the mobile version.

I enjoy your work; hopefully this issue is easily resolved.

**Comment by rune-b** [comment]
Strange. It works for me

![image](https://user-images.githubusercontent.com/11047987/75818030-7a826700-5d98-11ea-9ce2-530220e45db1.png)

**Comment by M1ntyPunch** [comment]
This is going to sound super fake, but a couple of days ago it started working as intended. I had just assumed that it was found and fixed (despite not downloading a new version, that's on me). I didn't think to come back here to say it fixed itself (also my bad). 

However, I still want thank you for checking that it worked on your end.
