### ISSUE TITLE
Serissu's ability is working on all ships at all ranges 

### ISSUE THREAD

**Issue by Lofty1979** [Sandrem/FlyCasual#2511]
Since the update, every ship on the board is getting re-rolls if I take Serissu, which is kind of frustrating.

**Comment by sqb1978** [comment]
Confirmed. In PC version for sure.

**Comment by Lofty1979** [comment]
Also in the mobile version

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sandrem** [comment]
Fixed
