### ISSUE TITLE
Jumpmaster with Ion Cannon, shooting from mobile side arc, ionizes enemy ship

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2513]
This shouldn't happen. The Ion Cannon can only shoot from the front. The mobile turret should not ionize ships. I was shooting at R1, with the mobile turret to the left, and had 3 reds, doing 1 damage and handing an ion token.

**Comment by rune-b** [comment]
I can't reproduce this. If I shoot with the mobile turret no Ion tokens are assigned. Do you remember which Jumpmaster pilot you used and any other upgrades it had? 

If this happens again, please take a screen shot of the situation

**Comment by Sandrem** [comment]
Still cannot reproduce.
