### ISSUE TITLE
Leia pilot can't equip Instinctive Aim force ability

### ISSUE THREAD

**Issue by danielsunderland** [Sandrem/FlyCasual#2515]
Leia pilot can't equip Instinctive Aim force ability

**Comment by rune-b** [comment]
Confirmed. Thanks for reporting!

**Comment by rune-b** [comment]
It is restricted to small base ships for some reason. Probably copy/paste error

**Comment by danielsunderland** [comment]
Great work guys 👍


-------- Original message --------
