### ISSUE TITLE
Serrisu's ability is working on Opponent's ships.

### ISSUE THREAD

**Issue by mmauschbaugh** [Sandrem/FlyCasual#2516]
playing 9.7.1 serrisu fenn and boba list. my serrisu's ability is being used against me by the AI to reroll it's defense dice, not just friendly ships. Also Serrisu's ability isn't limited to range 0-1 of itself.

**Comment by TNG-Wing** [comment]
Yes, this was a surprise to me too when I saw it happen.

**Comment by Sandrem** [comment]
Fixed
