### ISSUE TITLE
Direct Hit adds its ability to all other crits in the roll

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2517]
This one is a bit hard to properly hunt down. A ship suffers multiple uncancelled critical damage. (this happens regardless of whether regular damage was also suffered during this timing window.

Here's what's happening vs what should happen for some damage deals I've seen.

Damaged Engine then direct hit. 3 damage suffered. This is normal.
Direct hit, then damaged engine. 4 damaged suffered, only 3 should have been.

Fuel Leak then direct hit. 4 damaged is suffered. This is correct
Direct Hit into Fuel Leak. 4 damaged is suffered, should be 3.

A ship with a hull breach suffers 4 uncancelled hits / crits (hull breach makes them all crits)
Direct hit + (another crit from that direct hit) Direct Hit a second time + (its direct hit bonus crit) + 4 more critical damages I think.

**Comment by RockoTDF** [comment]
I've had ships die quicker than I thought sometimes recently by having an extra crit added, but wasn't able to nail down the pattern.  This must be it.

**Comment by Sandrem** [comment]
Thank you fore detailed report.
Fixed.
