### ISSUE TITLE
Checking range with Arvel

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#2524]
Every so often I find that I can't shoot at range 0 with Arvel. See image for example. The game checks range and states that the enemy is at range 0 in bullseye arc but not in my front arc. This is the usual error when I can't fire at range 0 with him. 
![image](https://user-images.githubusercontent.com/61330588/75065391-c7bc2a00-54b6-11ea-8b4b-7af868c9cc72.png)

**Comment by rune-b** [comment]
In this picture, Arvels base is actually inside the Nantex'. I suspect this is what is causing the range computation to be wrong. The shortest distance in the front arc is probably calculated to be a negative number

**Comment by Sandrem** [comment]
Fixed
