### ISSUE TITLE
Heroes of the Resistance?

### ISSUE THREAD

**Issue by iceride** [Sandrem/FlyCasual#2525]
Cannot find Milennium Falcon title from HotR.
Also, Smuggling Compartment upgrade seems to add Crew slot instead of Illicit slot.
Rey cannot seem to equip Elit Pilot Talents.

**Comment by rune-b** [comment]
Thanks for reporting. Unfortunately, First Edition bugs don't get a very high priority these days, but at least these were simple to fix
