### ISSUE TITLE
Doesn't check for Bullseye arc when bowtie turret arc is in the side arcs

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#2531]
![image](https://user-images.githubusercontent.com/61330588/75631752-7ea95b80-5bc3-11ea-867d-a4532b4ac574.png)

Trying to use Barrage Rockets on a K-Wing, I'm unable to use the secondary re-roll ability because the game states that the defender was not in my bullseye arc when the arc is rotated in the left/right direction.

**Comment by Sandrem** [comment]
Fixed
