### ISSUE TITLE
Can't Open on Mac OS

### ISSUE THREAD

**Issue by BobaStory** [Sandrem/FlyCasual#2536]
I download it and have it on my finder, but I followed the instructions on the help guide and it still didn't work

Did I do something wrong?  I put in chmod +x* and pressed enter
if you could help, big thanks I am a HUGE fan of x wing

**Comment by socantre** [comment]
There should be a space between the "+x" and the "*" in that command. If you have further trouble search the internet for how to enable the 'execute' permission on files and that might help you troubleshoot. Enabling the 'execute' permission bit is all the command "chmod +x *" is doing.

**Comment by BobaStory** [comment]
Works wonderfully now. Thanks!
:) 👍
