### ISSUE TITLE
Windows Vista

### ISSUE THREAD

**Issue by FaireePrincess** [Sandrem/FlyCasual#2541]
Is there any way that you can make this compatible with Vista? Pleeeease?

**Comment by rune-b** [comment]
It is made with Unity, and Unity only officially supports Windows 7 and 10.

Do you get any error messages?

**Comment by FaireePrincess** [comment]
Thanks for getting back to me. 
Yeah, won’t run. Says something about 32 or 64 window something. Sorry, can’t give you the exact error right now. Laptop is at home. I can send it to you later?

**Comment by FaireePrincess** [comment]
Hi, this is the error: 



Sent from my iPhone

Begin forwarded message:

> From: Suretha du Plessis <surethadp@gmail.com>
> Date: 09 March 2020 at 14:12:04 SAST
> To: Sandrem/FlyCasual <reply@reply.github.com>
> Subject: Re: [Sandrem/FlyCasual] Windows Vista (#2541)
> 
> Thanks for getting back to me. 
> Yeah, won’t run. Says something about 32 or 64 window something. Sorry, can’t give you the exact error right now. Laptop is at home. I can send it to you later? 
> 
> Sent from my iPhone
>

**Comment by rune-b** [comment]
I can't see any error message. Was it an image? Not sure if images work when you reply by email

Anyway, I don't think it is possible to get it to work in Windows Vista unfortunately. Though it might be possible to run the Android version in an emulator if there is such a thing available for Vista

**Comment by Sandrem** [comment]
As mentioned above, we only support platforms, that are supported by Unity3D engine.
So no support of Vista.
