### ISSUE TITLE
resolution roblem

### ISSUE THREAD

**Issue by SmokeParnell** [Sandrem/FlyCasual#2542]
my resolution has dropped down to the lowest setting and every time I try to change it back the command screen pops up.  (since 9.7.1)    i thought maybe it would correct itself in the new version, but sadly it has not.  I don't know what to do.
![x wing issue](https://user-images.githubusercontent.com/54188810/76688066-7a376680-65f7-11ea-927f-82e55ef9b479.jpg)

**Comment by Senzorezo** [comment]
Maybe same problem. 
After a Teamviewer session, trying to get back to my native resolution (1920x1200) : 

![image](https://user-images.githubusercontent.com/35725438/76692815-c87e5100-665b-11ea-9718-edba14889cb2.png)

Thank you !

**Comment by Sandrem** [comment]
Fixes are done in v1.0
Please, inform me, if you will have problems after release of v1.0
