### ISSUE TITLE
Amilyn Holdo and Cloak token

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2543]
With the Fireball, Resistance faction gained access to the cloaking device.
The crew Amilyn Holdo should be able to trade cloak token, and the game doesn't allow it.

Thx!

**Comment by Immelman51** [comment]
Holda can't exchange any blue token (blue lock tokens) neither.

**Comment by rune-b** [comment]
But that is correct behavior, since blue target lock tokens doesn't exist in Second Edition

**Comment by Immelman51** [comment]
that's right!
