### ISSUE TITLE
Sunny Bounder's ability crashes

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2547]
0.9.8

When used:

![image](https://user-images.githubusercontent.com/11047987/76701041-ad442d80-66bd-11ea-9839-086770b3fc37.png)

**Comment by wavemanns** [comment]
Same issue screen shot:

![image](https://user-images.githubusercontent.com/6612122/76793429-cc1cef80-67a3-11ea-8636-a333a83db60b.png)

**Comment by Sandrem** [comment]
Fixed
