### ISSUE TITLE
Inertial Dampeners crashes

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2549]
0.9.8

If you use Inertial Dampeners it crashes with a message that the ship doesn't have maneuver 0.S.S (possibly works for ships that have a stop maneuver)

![image](https://user-images.githubusercontent.com/11047987/76701131-a1a53680-66be-11ea-8bba-c90d00b3038b.png)

**Comment by Sandrem** [comment]
Fixed
