### ISSUE TITLE
Marauder title crash

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2551]
0.9.8

When using the re-roll from the Marauder title on a Firespray it fails:

![image](https://user-images.githubusercontent.com/11047987/76701334-981cce00-66c0-11ea-8868-00bf91b1c70e.png)

**Comment by bc-net** [comment]
![image](https://user-images.githubusercontent.com/64039869/79792144-cc6d5500-8324-11ea-9b71-414e1bb544dc.png)

Marauder title is still bugged?

**Comment by Sandrem** [comment]
Version with fix is not released yet.
