### ISSUE TITLE
Barrel Roll with TIE/fo allows ship to be placed off board and removed from game instead of failing

### ISSUE THREAD

**Issue by iincarna** [Sandrem/FlyCasual#2556]
Placement: TIE/fo facing opposite side with back to edge of board.
Turn 1: hard turn 2 then barrel roll towards your board edge
Turn 2: bank 3 towards inside of board. Barrel roll towards your side of board. Set the ship's placement to the back of the guides which will put one corner off the board.

Instead of failing, or not being allowed to set the placement to the back, the TIE/fo (or possibly other ships I haven't tested) will be removed from the board.

**Comment by Sandrem** [comment]
Invisible small ship base for barrel roll was a bit smaller than real small ship base - so Fly Casual predicted that barrel roll in this position is allowed - but after barrel roll checks said that ship is off the board.

Thank you, fixed.
