### ISSUE TITLE
Reloading Bombs

### ISSUE THREAD

**Issue by Shadowy90** [Sandrem/FlyCasual#2568]
When Flying Y-Wings and doing the Reload Action, it doesn't register that my bombs can be reloaded.

**Comment by Sandrem** [comment]
Cannot reproduce.
Seems that you used bombs with "This card's charges cannot be recovered."

Please, next time provide screenshots.

**Comment by Shadowy90** [comment]
Sorry I wasn't specific but I tried using proximity mines.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Sandrem** [comment]
Yes, charges of Proximity Mines cannot be restored by Reload Action according to rules written on that upgrade.
