### ISSUE TITLE
Sabine Wren (Lancer Persuit Craft) causes crash when using ability

### ISSUE THREAD

**Issue by tempest6677** [Sandrem/FlyCasual#2569]
Sabine wren causes crash immediately upon using it while defending.

I am able to reproduce the issue while I have Maul as crew.
![image](https://user-images.githubusercontent.com/33158870/77284828-d8fe7f00-6c8c-11ea-8790-4f23040a8ccf.png)

As well as while focused with perceptive copilot, or without any tokens at all:
![image](https://user-images.githubusercontent.com/33158870/77286342-42cc5800-6c90-11ea-854e-849a380c7782.png)

It occurs if my turret is in the front arc and outside front arc.

**Comment by Sandrem** [comment]
Fixed
