### ISSUE TITLE
Vennie's ability causes breakdown

### ISSUE THREAD

**Issue by Yuleooze** [Sandrem/FlyCasual#2574]
If you click to use her ability, game immediately crashes. ;(

**Comment by ootinni** [comment]
Got the same site error :(

Screenshot of crash attached
![Screenshot_20200402-004655](https://user-images.githubusercontent.com/52763171/78197553-98b5b280-747d-11ea-8b41-5b010df36647.png)

**Comment by Perribrus** [comment]
Same here. After I rerolled and used focus against her.
![Skjermbilde 2020-04-17 kl  21 19 22](https://user-images.githubusercontent.com/63073617/79606228-8e3c1f80-80f1-11ea-8e33-152628770085.png)

**Comment by Sandrem** [comment]
Fixed
