### ISSUE TITLE
Game crashes after Boba attacks

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2576]
This happened twice with my Boba Asajj list. After Boba rolls attack dice, the game crashes. The drop down log appears, and I typed "close" to dismiss it, but the game stops there.

![image](https://user-images.githubusercontent.com/26996014/77810996-b685b080-7054-11ea-8fff-f5ddee70c28c.png)

**Comment by TNG-Wing** [comment]
This has happened many more times with different Boba Fett lists. Love the work you've all done and really appreciate it. Hope this report is helpful to you.

I have captured the screenshot with the error codes below:

![image](https://user-images.githubusercontent.com/26996014/77861712-73018280-71cb-11ea-91fd-c70aa9253742.png)

**Comment by Sandrem** [comment]
Fixed
