### ISSUE TITLE
Cant move camera during obstacle setup and first turn

### ISSUE THREAD

**Issue by daviddolan** [Sandrem/FlyCasual#2582]
I'm having this weird problem when doing a vs AI game on the windows version of the game in which I do not get control of the camera during obstacle setup. When the match starts I'm in mouse mode and 3D.

This is cuasing a major problem as my ship details are over the top of where the obstabcles are so I am unable to select them to place them down manually.

When the game/match loads in I'm in mouse mode and 3D.

I've tried retarting the match but it does not change anything.

If I randomly place the obstacles I do not get camera control during the deployment or first turn but oncethe 2nd starts I seem to get control again.

**Comment by rune-b** [comment]
possibly related to #2371 ?

**Comment by Sandrem** [comment]
Fixed
