### ISSUE TITLE
Ionized Ved Folso

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#2583]
![image](https://user-images.githubusercontent.com/61330588/78042122-9a795c00-733f-11ea-9c79-304be0eeb162.png)
Stressed and ionized Ved Folso and when the menu pulls up to proc for his ability (it allows to go a bearing 1 speed higher), I just get this weird menu without any way to resolve it.

**Comment by Sandrem** [comment]
Fixed
