### ISSUE TITLE
Some card's images do not load.

### ISSUE THREAD

**Issue by Arkayus1** [Sandrem/FlyCasual#2584]
For instance, no 1.0 bomb cards load, only displaying a white background with the card name in the default font. i have deleted the cards in appdata/locallow/sandrem/fly casual/first edition, but the cards still dont load.
![send to fly casual dev](https://user-images.githubusercontent.com/17815152/78136251-34620700-741b-11ea-914e-9c3bbde77851.png)
sorry if im being a pain.

**Comment by rune-b** [comment]
Hi
Are you sure your network connection is OK? The cards are downloaded from the internet

What device/OS are you using?

**Comment by Arkayus1** [comment]
my network connection is fine afaik, should be enough to download them. 
im on a windows 10 laptop.

**Comment by Arkayus1** [comment]
oops forgot to say, im on the latest version, 9,8.0.

**Comment by Sandrem** [comment]
Cannot reproduce. Something is wrong in your environment.
