### ISSUE TITLE
Bullseye for Predator did not trigger

### ISSUE THREAD

**Issue by ootinni** [Sandrem/FlyCasual#2585]
Check for bullseye to trigger Predator 

![Screenshot_20200331-014714](https://user-images.githubusercontent.com/52763171/78197702-082ba200-747e-11ea-9237-e026d9bb8a6c.png)
did not work

**Comment by Sandrem** [comment]
I cannot reproduce this bug.

Please, next time when you can reproduce it - send me replay file (path: "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual\Second Edition\Replays")
