### ISSUE TITLE
Can't install on Windows

### ISSUE THREAD

**Issue by Whitmantisolarus** [Sandrem/FlyCasual#2587]
Tried three times; consistent issue is it says the unityplayer.dll is not found; however it's right in the main folder with the executable.  Should I move that elsewhere manually?

**Comment by Sandrem** [comment]
Seems that you forgot to unpack zip-archive and tried to run exe-file from archive instead.

Follow instructions here:
https://www.youtube.com/watch?v=5cSa7EHm5vo

**Comment by Sandrem** [comment]
If this don't help, then I googled for another possible fixes: https://coding.fm/unityplayer-dll/

**Comment by Whitmantisolarus** [comment]
Brilliant!  Thank you!!
