### ISSUE TITLE
Thanks for the game and some Bugs to report

### ISSUE THREAD

**Issue by jsquinchev** [Sandrem/FlyCasual#2588]
First of all, thank you, really really a lot of thanks for such an amazing free programm, when I find a job be sure you will get my humble contribution to your Patreon.

I have been playing your amazing simulator last weeks, and I would like to report a fee bugs in hope of improvement in the next realeases.
1. Static pilot ability seems to crash the game
2. Vennie pilot ability seems to crash the game
3. Captain phasma crew ability doesn't seem to work, I never get to see my opponents ships get the stress token
4. Cluster missiles bonus attack, doesnt seem to work to range 0-1 of the defender but of the attacker
5.Kaz's fireball title is missing the part where you can perform actions on damage cards while ionized.
6. R1-J5 astromech card seems to lack the ability to perform actions on damage cards while you have 2 or fewer stress tokens.

Finally thanks again for such great game, and I hope to see in not so distant releases the missing bombs and mines, maybe one day online play.

**Comment by quall3** [comment]
I have additional infi in the vennie crash, i hope this is usefuln see attached sreenshot
![Screenshot_20200412-100155](https://user-images.githubusercontent.com/18752631/79063922-25921480-7ca5-11ea-90f3-2eaac85b1c3b.png)

**Comment by jsquinchev** [comment]
Info of the craash using pilot ability of static
![imagen](https://user-images.githubusercontent.com/63166916/79075164-adcce580-7cb6-11ea-972d-e9a533f020fe.png)

**Comment by jsquinchev** [comment]
Info of the craash using pilot ability of "Static" part 2

![imagen](https://user-images.githubusercontent.com/63166916/79075190-e240a180-7cb6-11ea-9a29-4a345d4bb137.png)

**Comment by jsquinchev** [comment]
By the way I am kind a newbie to the game, and "Cluster Missiles" works fine, it was mine who misunderstood the description in the card. Also "Captain Phasma" crew ability seems to work now, maybe Imisjudged the range the first time.

**Comment by Sandrem** [comment]
Status:
1-2: fixed
3-4: Cannot reproduce
5-6: I will create separate issues.

Please, next time, for each bug - create separate issue.
