### ISSUE TITLE
Kath Scarlett not taking stress when taking the reinforce action

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#2591]
As said, Kath in the Firespray, takes reinforce and does not get the stress token
![image](https://user-images.githubusercontent.com/26796723/78673040-7a1a4600-78d9-11ea-8642-2b01c49af857.png)

**Comment by Sandrem** [comment]
Current AI performs red actions as white. (It is complex to write AI that knows when it should use red actions and when no).
I will think how to avoid such misunderstanding.
