### ISSUE TITLE
Game crashing on Android

### ISSUE THREAD

**Issue by Talanos** [Sandrem/FlyCasual#2593]
The app is crashing on Android (Pixel phone, Kindle Fire) at random places.  It's nearly impossible to complete a game.

**Comment by rune-b** [comment]
Hi. Do you get an error message? Can you take a screenshot of the game when it has crashed?

**Comment by Talanos** [comment]
Unfortunately no. It kicks me back to he home screen on both devices. I have uninstalled and deleted the app and reinstalled it with no luck.

**Comment by rune-b** [comment]
That's strange. Is it a specific list you are playing or does it happen with any list?

**Comment by Sandrem** [comment]
This can be caused if your device doesn't have enough free RAM (or another resources to run the game).
Anyway, this issue is not related to the code of the game (otherwise you would see console with red text) - so we cannot fix it.

**Comment by Talanos** [comment]
Ok, thanks for looking into it!
