### ISSUE TITLE
A wing linked rotate turret red ability does not cause ship to become stressed

### ISSUE THREAD

**Issue by 4dren0** [Sandrem/FlyCasual#2599]

**Comment by rune-b** [comment]
I get stressed when I rotate the turret on a generic A-wing

Has this happened for you more than once? Is it with a specific pilot, or any pilot?

**Comment by Sandrem** [comment]
@rune-b Seems that all "performs red action a white" bugs are related to AI-controlled ships. (AI designed tp perform red actions as white). I will think what to do to avoid misunderstanding.

**Comment by Sandrem** [comment]
I updated AI. It will not perform red actions anymore.
But still it will have exception for red rotate arc action - it still will perform it without getting stressed. Without this exception - AI-controlled ships with turrets will be too stupid. I will remove this exception and update AI for these ships later.
