### ISSUE TITLE
Silencer Pilot "Rush" needs FAQ implementation

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#2600]
Presently in FC, Rush looses an engagement if he becomes damaged between Initiative 6  and Initiative 2. FFG has addressed this in the FAQ.
![image](https://user-images.githubusercontent.com/60325223/79141955-9f8ed000-7d6f-11ea-98b3-718ef20a9e87.png)
Taken from Rules Reference 1.1.0 (Jan 2020). 
https://images-cdn.fantasyflightgames.com/filer_public/67/8a/678a909e-bd3b-4c21-9978-4218a253d07d/b_swzrulesreference_v110_-compressed.pdf

**Comment by Sandrem** [comment]
Done
