### ISSUE TITLE
Resolution issue

### ISSUE THREAD

**Issue by Brion1990** [Sandrem/FlyCasual#2603]
No idea what happened but the resolution suddenly dropped from 2160x1440 to 1440x1440 mid-game. Attempted to fix in the options menu but got the following error message, 

<img width="721" alt="Screenshot 2020-04-14 192053" src="https://user-images.githubusercontent.com/37163057/79283958-6184cf80-7e87-11ea-9615-0ab9c42266f1.png">

This occurs regardless of whether the full-screen option is selected. Issue did not resolve when game was restarted or re-downloaded. Could not resolve issue via command prompt in the same manner as before. I'm on Window 10

**Comment by wilcornish** [comment]
Also experiencing this on MacOS

**Comment by Sandrem** [comment]
Fixes are done in v1.0
Please, inform me, if you will have problems after release of v1.0
