### ISSUE TITLE
Ships Bump, One is removed from play area

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#2604]
During this game, LT Tavson did a soft one turn (center of board, facing the SJ engineer in the center of the pic) and they bumped.  The game said Tavson had flown off the board and removed him from play.  He was nowhere near the edge.  Not sure how this happened.  There was nothing strange in the command line, either.

![tavson off board](https://user-images.githubusercontent.com/47582934/79292633-4f963300-7e6d-11ea-86a7-c5f6c5eb524d.png)

**Comment by Sandrem** [comment]
Fixed in dev build.
