### ISSUE TITLE
Game breaks on using Marauder ability

### ISSUE THREAD

**Issue by socantre** [Sandrem/FlyCasual#2607]
Version 0.9.8
Squad:
Boba Fett+Marauder+Perceptive Copilot+Proton Bombs+Veteran Tail Gunner+Delayed Fuses
Emon Azzameen+Adrasta+Trick Shot+Qi'ra+Proton Bombs+Proximity Mines

Default obstacles, randomly placed

Ships positioned directly across from a swarm of 8 ties.

First move: both K-turn
Engagement phase: Boba Fett rear arc primary attack on enemy, use Marauder reroll ability

Result: console opens with red error text. Game unable to continue.

**Comment by Sandrem** [comment]
fixed by rune-b in dev build.
