### ISSUE TITLE
collision on reverse bank maneuvers needs an adult

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2614]
![image](https://user-images.githubusercontent.com/8730661/80142385-0d5da780-8579-11ea-8e9a-5ba34b3bba1d.png)

The game correctly determined this was a collision, but I suspect tried to move backwards along the reverse template to find a position that was okay. (as opposed to moving forwards from the ending position

**Comment by Sandrem** [comment]
Fixed in "1.0 Hotfix 1"
