### ISSUE TITLE
Resistance Sympathizers ate Arvel

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#2618]
Two Resistance Sympathizers have somehow merged in my game, when I tried to boost into one with Arvel, he just disappeared and never reappeared. I have maneuver speed all the way up, maybe that caused them to collide and fuse? Really one of the funnier bugs I've seen

![Faclon fusion](https://user-images.githubusercontent.com/61330588/80247481-1a8f9a80-863c-11ea-8434-3c638b56ea3e.png)

**Comment by Sandrem** [comment]
Fixed in hotfix
