### ISSUE TITLE
Collisions overlapping instead of bumping

### ISSUE THREAD

**Issue by mephiston-x** [Sandrem/FlyCasual#2619]
Set any 2 ships marks manuvers so that their post manuver positions so they will 'bump'
Happens in Windows & Android
New to Version 1.0
![Screenshot_20200424-125848_Fly Casual](https://user-images.githubusercontent.com/41198666/80247893-16f41780-862c-11ea-8aa4-b58804c6fe47.jpg)
![Screenshot_20200424-125905_Fly Casual](https://user-images.githubusercontent.com/41198666/80247895-178cae00-862c-11ea-91b5-f730cc365562.jpg)

**Comment by Sandrem** [comment]
Fixed in hotfix
