### ISSUE TITLE
Windows - Launching game gives black screen

### ISSUE THREAD

**Issue by Talanos** [Sandrem/FlyCasual#2626]
Not sure if my laptop just sucks or if there's something I'm missing. Installed Windows version. When launching the game, the Unity logo appears and fades out, then I'm left with just a black screen with the game music playing. 

I'm running Windows 7 Home Premium.

Thanks.

**Comment by Sandrem** [comment]
Something is wrong with your environment.
Check your antivirus, video card drivers etc...

**Comment by rune-b** [comment]
Here are some discussions about a similar problem in other Unity games, maybe it can help you

https://forum.unity.com/threads/black-screen-in-unity-games-games-i-play-not-games-im-a-developer-of.518722/

**Comment by Talanos** [comment]
I updated my video drivers and am able to get into the game.

**Comment by rune-b** [comment]
That's great news 👍
