### ISSUE TITLE
Linux Crash on Game load since 1.0

### ISSUE THREAD

**Issue by Grande-Rojo** [Sandrem/FlyCasual#2635]
Running on Pixelbook in Linux since 0.9.8 with no issues.  Now since 1.0 (including 1.0.1) game menus, list builder and everything else works fine, but when go to start the game, Unity throws an error and everything freezes.  Rolled back to 0.9.8 and everything works fine again.  Tried a couple different video settings to see if there was any effect, but nothing seemed to change the outcome.  Same issue on 1.0, 1.0 Hotfix, and 1.0.1

**Comment by rune-b** [comment]
Hi
Can you post the error message you are getting?

**Comment by Grande-Rojo** [comment]
Is there a log somewhere that captures it, the console that pops up doesn't seem to allow copy/paste and the error is LONG?  If not I'll send a screen shot.

**Comment by rune-b** [comment]
A screen shot is fine

**Comment by Grande-Rojo** [comment]
![Screenshot 2020-04-26 at 3 31 23 PM](https://user-images.githubusercontent.com/64370198/80317661-134ec500-87d3-11ea-843f-e4da465471e2.png)


See attached

**Comment by rune-b** [comment]
Thanks. What linux distro are you using?

**Comment by Grande-Rojo** [comment]
Crostini, which is Debian Stretch.

**Comment by Sandrem** [comment]
Please, try to delete folder "Customizable" and try again.

**Comment by Grande-Rojo** [comment]
That got it guys!  Seems to work just fine now.  Is there anything else I can do to help you guys get root cause?

**Comment by otuv** [comment]
The same seems to be a problems for all squads including a ship with a name including "X-".
Tried wings A,B,U,X-65,X-70,Y. But stuff like YT-2400 works fine.

**Comment by Sandrem** [comment]
I don't have any ideas why Linux doesn't like some names in file path of external files.
To avoid this bug, I will not add "Customizable" folder to "Linux.zip" archive in next updated.
If anyone will want to try again - take this folder from "Windows.zip" archive.
