### ISSUE TITLE
Deuterium Power Cells

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#2636]
I've come across two potential problems with DPCs in this release:

1. Not getting the prompt for regen in the systems phase.
2. If you use DPCs other ability when using the TIE/BA's ability, you get a stress token and are then unable to take the lock or do a BR.  This doesn't feel right - isn't the point of this card so that you can take a stress instead of deplete/strain? I could be wrong about this if you're supposed to get the token before doing the action.

**Comment by Sandrem** [comment]
1) Thank you, fixed.
2) Card is working as written. First you gain stress token, then you cannot do actions because you are stressed. It should be worded "perform an action, then gain Strain or Deplete token" to work correctly with Stress token replacement.
