### ISSUE TITLE
Saw Guerrera re roll

### ISSUE THREAD

**Issue by chacho6v** [Sandrem/FlyCasual#2638]
Hi! 
The oponent ships use the abbility from my Saw Guerrera ship 
So I have been receiving lot of damage with that
I know the card says "While a damaged friendly ship at range 0-3 performs an attack, it may reroll 1 attack die." 
So the opponent is not suppose to gain the re roll

Best!

**Comment by Sandrem** [comment]
Thank you, fixed.
