### ISSUE TITLE
Feature request: Loading prebuild squads from URL/URI

### ISSUE THREAD

**Issue by alberttwong** [Sandrem/FlyCasual#2639]
If I were to sponsor this feature, how much would this cost?  I also see this as an area that you can potentially monetize.  

As a user, I want to be able to load prebuilt squads so that I can focus on playing popular lists without taking the time to search, research and create the squad.

**Comment by Sandrem** [comment]
At the moment squad builder supports import of squads in XWS format - this format is supported by a lot of squad builders, including YASB 2.0

From which urls do you want to load squads?

**Comment by alberttwong** [comment]
That's the thing.. I don't know of a site that lists a bunch of lists in XWS.   Hence the monetization.

**Comment by Sandrem** [comment]
I know one such site: https://meta.listfortress.com/ship_combos?

It supports export to XWS format, for example: https://meta.listfortress.com/ship_combos/2964? (Export button)

I just checked - some squads cannot be imported (seems that there is a bug in Fly Casual importer, I will check this later)

I think that I can load popular squads from this site and load them to Fly Casual as proposed squadlists - but this is a lot of work. So I can do this, if you will support me with $60 donation.

Or just use "Export" button from that site and import them to Fly Casual (I will fix importer in the next update).

**Comment by alberttwong** [comment]
Tell me where to send the money.

**Comment by Sandrem** [comment]
https://www.patreon.com/Sandrem
