### ISSUE TITLE
Still have an overlap issue

### ISSUE THREAD

**Issue by mephiston-x** [Sandrem/FlyCasual#2640]
Exists in v 1.01, couldn't find another report this time :D 
I think it had to do with a 2nd bump for the AI
![image](https://user-images.githubusercontent.com/41198666/80410380-b8c37080-8887-11ea-81ca-10071901fa88.png)

**Comment by Sandrem** [comment]
Thank you, I will check.

**Comment by Sandrem** [comment]
One more question: How often do you see this bug?

**Comment by boredompwndu** [comment]
![image](https://user-images.githubusercontent.com/8730661/80425741-487e1480-88b2-11ea-806c-17685468e7fc.png)

Not OP, but I just found this 1 straight from AI controlled Padme. Granted this is in 1.0 hotfix not 1.0.1

Second time I've had egregious bump faults in the 1.x versions in maybe 7 games

**Comment by mephiston-x** [comment]
This was the first for this version but that's not saying much, had to do software dev that I get paid for.

**Comment by Sandrem** [comment]
Fixed
