### ISSUE TITLE
AI controlled quadjumper does not treat evade action as red

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2645]
![image](https://user-images.githubusercontent.com/8730661/80672777-a27e0600-8a7b-11ea-9d76-d6f6be618f94.png)

I'm not entirely sure that AI controlled ships actually recognize difficulty of non-linked actions. I have anecdotal evidence of AI controlled aethersprites evading but not spending force to do so.

**Comment by boredompwndu** [comment]
version 1.0 hotfix 1

**Comment by Sandrem** [comment]
Fixed
