### ISSUE TITLE
Manager opening and causing game to be unplayable

### ISSUE THREAD

**Issue by Talhoffer** [Sandrem/FlyCasual#2647]
First of all thank you for this game! It's been a life saver during the lock down.
I recently downloaded 1.0.1 and have had a few instances where the manager opens blocking the top half of the screen and preventing me from activating ships in that area.
This has happened when Torani activates his bullseye effect, with Sunny Bounder's  card effect and just now after Anikan in the Naboo starfighter did his neat trick. 
Thanks.

**Comment by enosjr123** [comment]
This also happens with Dengar Gunner.  And now with strain or deplete from tie Barons
