### ISSUE TITLE
Resolution error in video settings 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2649]
1.0.1 Android

![Screenshot_20200501-095742](https://user-images.githubusercontent.com/11047987/80792737-8a9aa500-8b95-11ea-821a-0e3a71fd359f.png)

**Comment by krumok** [comment]
Same error on Xiaomi Mi Pad 3 (1536 x 2048 pixels, 4:3 ratio)
![Screenshot_2020-05-01-21-48-53-268_com sandrem flycasual](https://user-images.githubusercontent.com/12997440/80837013-3a9ffa80-8bf6-11ea-9885-beaa947888a5.jpg)

**Comment by Sandrem** [comment]
Fixed
