### ISSUE TITLE
Lt Bastian T-70 abilities doesn't have the right timing.

### ISSUE THREAD

**Issue by Sergovan1** [Sandrem/FlyCasual#2650]
Lt Bastian ability is: "After a ship is dealt a damage card you may acquire a lock on it."  This is being represented as after HE deals a damage card then he acquires a lock. 

It may be for game flow reasons to not have every damage card window call for his ability to fire (which would be annoying) but you could have it that when he selects a target that was damaged into hull on this _round_ of firing, he acquires the lock. 

With how he is now he loses his interplay with his squad mates.

**Comment by Sandrem** [comment]
I just checked - when **another squad-mate** attacked an enemy ship at range 2 from Lt Bastian and dealt damage card to it - ability of Lt Bastian was activated and asked to lock on that enemy ship.

As I see, everything works fine.

If I understood your bug report in wrong way - please, inform me.
