### ISSUE TITLE
Wexley T-70 doing failed boost into Composure focus misses his perform action step.

### ISSUE THREAD

**Issue by Sergovan1** [Sandrem/FlyCasual#2651]
Wexley gets the free boost after a 2-3-4 maneuver, which he can choose to fail to get a free focus action from composure. However, he still would have his perform action step after that combination. That is what is missing.

**Comment by isachade** [comment]
It's working as it should. The card was errata'd.

https://xwing-miniatures-second-edition.fandom.com/wiki/Composure

**Comment by Sandrem** [comment]
Not a bug, closed.
