### ISSUE TITLE
Rebel Han pilot ability doesn't trigger after rolling dice for Lando crew

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#2655]
![image](https://user-images.githubusercontent.com/61330588/81434089-9c4ef000-9133-11ea-925b-ba284c138855.png)
Within range one of an obstacle, rolled dice per Lando's ability. Han should be given the option to reroll if he wants.

**Comment by Sandrem** [comment]
Dice modifications for non-combat dice are not available yet. Will be added later.
