### ISSUE TITLE
Kylo IWSYTDS crashed and opened code

### ISSUE THREAD

**Issue by Wurms2** [Sandrem/FlyCasual#2656]
Worked fine in previous games. This particular instance Kylo was behind a debris cloud.
<img width="1300" alt="Screen Shot 2020-05-09 at 3 06 23 PM" src="https://user-images.githubusercontent.com/65094280/81486136-a510f600-9207-11ea-85b5-aac317bb099a.png">

**Comment by Sandrem** [comment]
Fixed
