### ISSUE TITLE
GUI pans to top left corner during setup

### ISSUE THREAD

**Issue by MandaloreOne** [Sandrem/FlyCasual#2657]
The GUI pans to the top left corner during Player vs. AI setup, preventing placement of obstacles and game start. This occurs regardless of a squad using all 100 points or less. In 3D mode, rotating the view works, but the camera/view continues to pan.
![Setup-Issue](https://user-images.githubusercontent.com/65136418/81511221-c0eac980-92e5-11ea-84a1-677f7ff2e5d9.png)
Windows 7, 1980x1080 display, NVIDIA graphics card; 3DConnexion spaceball disconnected.
Issue also noticed with prior, pre-release 0.9.8 version.

**Comment by Sandrem** [comment]
Fixed
