### ISSUE TITLE
Thinks I'm on an asteroid when I'm not (after Talon Roll)

### ISSUE THREAD

**Issue by artintey** [Sandrem/FlyCasual#2658]
When I did a Talon Roll (Nien Nunb), the center position landed on an asteroid, but the backwards position was not on the asteroid. After selecting the backwards position, it still thought I was on the asteroid and didn't give me an action and did not let me attack. Screenshot attached of the final position.
![FC_Asteroid](https://user-images.githubusercontent.com/60230402/81871328-6d1df180-952c-11ea-9dcb-95f53c31dd37.jpg)

**Comment by Sandrem** [comment]
Fixed
