### ISSUE TITLE
Vader's lock ability not functioning

### ISSUE THREAD

**Issue by utahmanalex** [Sandrem/FlyCasual#2661]
With Vaders "ADVANCED TARGETING COMPUTER" you are suppose to get an additional attack die when you attack a defender you have a lock on. This has not been happening for me when I use him and instead it just rolls the basic amount of dice and then allows me to change 1 hit to a crit.

**Comment by Sandrem** [comment]
I just checked - everything worked fine.

Please, report bugs with screenshots.
Maybe you attacked ship without lock, or you had damage card with "roll -1 dice", or some another effect was active...
