### ISSUE TITLE
Treacherous consistently crashes the game

### ISSUE THREAD

**Issue by JoelSpringle** [Sandrem/FlyCasual#2667]
I've been flying 5 bellyrubs with treacherous a bit lately.  I can never finish a game because it crashes at some point when Treacherous is used.  In this particular game, it was the 3rd use.  It often happens on the very first one.

![image](https://user-images.githubusercontent.com/65818951/82738595-9eee3f80-9d06-11ea-8154-335315f1947d.png)

**Comment by Sandrem** [comment]
Treacherous was allowed to use when it didn't have charges - and error occurred when game tried to use charge.
Fixed.
