### ISSUE TITLE
1.2 Crashed after r1 activation

### ISSUE THREAD

**Issue by JoelSpringle** [Sandrem/FlyCasual#2672]
No idea why.  After Von Reg moved, crash.  Not sure if he even got his action.

![image](https://user-images.githubusercontent.com/65818951/82768524-9cbadc80-9dfd-11ea-8299-3b8fd93bcb4b.png)

**Comment by JoelSpringle** [comment]
Did it afain.  Thought maybe it was an issue with squads already saved v new ones.  So deleted all old and made new.

Happened again - but this time the report interface popped up.

![image](https://user-images.githubusercontent.com/65818951/82772597-a1878c80-9e0d-11ea-88cb-2281e53a095a.png)

**Comment by JonGrell** [comment]
Had a similar issue, Keeps on desyncing during round 2 on desktop.

In round 2 activation phase:
- Player 1 (who has initiative) Moves, Player 2 can see it as normal.
- Player 2 moves, Player 1 sees the dial revealed, but doesn't see any ships move. Player 2 sees the game move to the activation round, Player 1 sees the dial flipped back over (faction side up) and the ships still don't move.
If player 1 right-clicks on any of player 2's ship cards, seeing an "Error: Ship not found" message on the bottom
![image](https://user-images.githubusercontent.com/65965970/82917902-ec1f1b00-9f6b-11ea-875e-ea81685ef961.png)

No console message displayed

**Comment by Sandrem** [comment]
Fixed
