### ISSUE TITLE
1.2 Crash related to Discord Missiles

### ISSUE THREAD

**Issue by mbernhardt6** [Sandrem/FlyCasual#2673]
Discord missiles are on board. During planing phase when mousing over discord missiles (or possibly accidentally attempting to select them?) this error pops up.

![Fly Casual 5_25_2020 12_33_42 AM](https://user-images.githubusercontent.com/10909798/82778453-7ad25180-9e1f-11ea-9e27-d3d33375b132.png)

**Comment by Sandrem** [comment]
Fixed
