### ISSUE TITLE
AI-controlled TIE/BA ships cause crash

### ISSUE THREAD

**Issue by skiprayblastboat** [Sandrem/FlyCasual#2677]
Not sure what happened but I've attached the screen shot. 
![2020-05-25](https://user-images.githubusercontent.com/65918477/82837584-1f3fac80-9e8f-11ea-81b0-926e27a08228.png)

**Comment by Sandrem** [comment]
Please, don't use TIE/BA ship for AI squads - this cause bug.

**Comment by Sandrem** [comment]
Fixed
