### ISSUE TITLE
Bug after restart

### ISSUE THREAD

**Issue by FoxxGuthy** [Sandrem/FlyCasual#2680]
[Description.txt](https://github.com/Sandrem/FlyCasual/files/4683504/Description.txt)

![Screenshot](https://user-images.githubusercontent.com/11880211/82924487-69d22f00-9f4a-11ea-88ae-dc3401854cf0.jpg)

**Comment by LanikTnt** [comment]
Got the same bug, screenshot attached.
![FC_Bug](https://user-images.githubusercontent.com/33493097/83292107-29bfb600-a1af-11ea-87e5-b8836505d73c.png)

**Comment by Sandrem** [comment]
Fixed
