### ISSUE TITLE
Hotshot Gunner (Proton Rockets with Scum Falcon)

### ISSUE THREAD

**Issue by Scot1a** [Sandrem/FlyCasual#2682]
![image](https://user-images.githubusercontent.com/65984364/82957545-d2380500-9f78-11ea-892d-011344be193b.png)
[Replay.txt](https://github.com/Sandrem/FlyCasual/files/4685377/Replay.txt)

Attempted to use proton rockets on Han Solo scum Falcon.  Game crashed.

**Comment by Sandrem** [comment]
Fixed

**Comment by Scot1a** [comment]
![image](https://user-images.githubusercontent.com/65984364/83711441-cb4c6a80-a5e8-11ea-8abe-c3b45460bc4e.png)

Just tested, and had a crash from attempting to use Proton Rockets on the Scum Falcon again.  Screenshot attached.

It might be related, but i never see a bullseye report a range when I use the Scum Falcon.

**Comment by Sandrem** [comment]
In 1.2, if you are trying to attack using Proton Rockets with Hotshot Gunner equipped, and if your turret arc is not in front sector - game crashes. This is fixed in dev-branch, release will be ~ in the end of this week.

**Comment by Scot1a** [comment]
Apologies, I had a blonde moment and forgot the update had not been released since the fix.

Thanks for fixing this so quick, and this program is a fun way to practice!  Appreciate the work!
