### ISSUE TITLE
Mouse scroll forward and right not working on 1.2

### ISSUE THREAD

**Issue by lordmagnusen** [Sandrem/FlyCasual#2683]
I was using 1.0, and I could move the mouse to the edge of the screen to scroll, but now it only works backwards and to the left. WASD still works, but not the arrows (I saw that reported already). Thanks!

**Comment by grandpajive** [comment]
Same issue for me. Running fullscreen. 1920x1080, Windows 10. When it isn't fullscreen, it doesn't pan in any direction.

**Comment by Sandrem** [comment]
Fixed
