### ISSUE TITLE
DFS-311 equipped with Discord missiles discrepancy 

### ISSUE THREAD

**Issue by Brion1990** [Sandrem/FlyCasual#2685]
DFS-311 equipped with Discords missiles is allowed to both spend its calculate token to launch its buzz droid swarm And pass off the same calculate token it would've spent to friendly ships at range 0-3 despite the opportunity to do either occurs within the same timing window, i.e. "At the start of the engagement phase". Should only allow one or the other, Not both

**Comment by Sandrem** [comment]
Thank you, fixed
