### ISSUE TITLE
Manager opened on start up [bug]

### ISSUE THREAD

**Issue by Sergovan1** [Sandrem/FlyCasual#2687]
Manager opened as it was loading up squads for the table. Replay attached
[LastReplaydualdeci.replay 2.zip](https://github.com/Sandrem/FlyCasual/files/4691624/LastReplaydualdeci.replay.2.zip)

**Comment by Sergovan1** [comment]
Screenshot of another game with bug on startup. Was quick enough to catch some problem code.
![Screen Shot 2020-05-28 at 9 56 48 PM](https://user-images.githubusercontent.com/64314306/83212810-862ec100-a12e-11ea-91bc-6cd301a81dc7.png)

**Comment by Sandrem** [comment]
Fixed
