### ISSUE TITLE
NullReferenceException: Object Reference not set to an instance of an object

### ISSUE THREAD

**Issue by Ravellion** [Sandrem/FlyCasual#2692]
This occurred just after setting dials for 7 trade federation drones and 1 techno union bomber. DRK 1 probe droids were also in play.
[Droid dial set bug.zip](https://github.com/Sandrem/FlyCasual/files/4695383/Droid.dial.set.bug.zip)
![Screenshot (1)](https://user-images.githubusercontent.com/66069143/83139507-c8371300-a0ec-11ea-8851-2ab8ff46802a.png)

**Comment by mdublade** [comment]
Got similar error. Error occured while ship movement was being carried out. 
![fly casual error](https://user-images.githubusercontent.com/33258195/83342730-ccb42500-a2c0-11ea-84c9-731f9b24550f.jpg)

**Comment by Sandrem** [comment]
@mdublade these errors are not similar - it is not only first line, other lines are important too - these two screens are caused by very different bugs. (Calls of Roster.ShowDial and SubPhases.DecisionSubPhase.GenerateDecisionCommand)

Both bugs are fixed.
