### ISSUE TITLE
Null reference - Homing missile

### ISSUE THREAD

**Issue by otuv** [Sandrem/FlyCasual#2695]
![Skärmbild (15)](https://user-images.githubusercontent.com/16488095/83186963-a316c480-a12d-11ea-9f0a-6f2253f7850f.png)

Clean state - Firing a Homing missile which seems legit by all relevant rules..

**Comment by Sandrem** [comment]
Thank you, I will fix this as part of earlier reported issue: https://github.com/Sandrem/FlyCasual/issues/2668
