### ISSUE TITLE
The application “FlyCasual” can’t be opened.

### ISSUE THREAD

**Issue by kevinlpedersen** [Sandrem/FlyCasual#2700]
New version 1.2 cannot be opened on my macbook pro (Catalina 10.15.5). previous version worked fine

**Comment by rapscallion84** [comment]
Indeed, I'm getting the same with 1.2 on Catalina 10.15.2

**Comment by Sandrem** [comment]
Please, try this help information: https://github.com/Sandrem/FlyCasual/wiki/How-to-run-Fly-Casual-on-MacOS-Catalina
