### ISSUE TITLE
Network Calculations freezes resolution button

### ISSUE THREAD

**Issue by mcelrojb58** [Sandrem/FlyCasual#2702]
I am flying a 3 Vultures, 2 Hyenas, and a Bullebub, I use network calculations and accidentally select the Bullebub pilot (Wat Tambor). THe game sort of freezes and I cannot click ok or proceed any further. I am force to either return to the menu or restart. It has happened on three back-to-back games.

**Comment by Sandrem** [comment]
Fixed, you cannot select ship without Calculate token anymore.
