### ISSUE TITLE
Moralo cannot place ship

### ISSUE THREAD

**Issue by otuv** [Sandrem/FlyCasual#2703]
![Moralo](https://user-images.githubusercontent.com/16488095/83302844-50580e00-a1fc-11ea-9648-0645f7a35bdc.png)

Flew of. Placing to get back. Tried all directions.

**Comment by grandpajive** [comment]
Same here. Head Hunter was not docked in my situation

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/2663

**Comment by otuv** [comment]
![Screenshot from 2020-08-11 21-31-47](https://user-images.githubusercontent.com/16488095/89940789-5b76e380-dc1a-11ea-9601-7f58423688dd.png)

It seems that it remains in 1.4. Pretty sure it was in 1.3 as well but I never shot it.
