### ISSUE TITLE
FO TIE/BA Fine-Tuned Thrusters AI error

### ISSUE THREAD

**Issue by mdublade** [Sandrem/FlyCasual#2705]
This occurs when the AI ship is a FO TIE/BA Interceptor. When used by human player, no error. Same ship, at the Fine-Tuned Thrusters option, AI throws an error.
![fly casual error fo tie-ba 1](https://user-images.githubusercontent.com/33258195/83357019-c0b77a00-a337-11ea-8d2e-2176ba2f0238.jpg)
![fly casual error fo tie-ba 2](https://user-images.githubusercontent.com/33258195/83357021-c4e39780-a337-11ea-8a6d-fd333e53da28.jpg)

**Comment by Sandrem** [comment]
Fixed.
