### ISSUE TITLE
Jam Bug

### ISSUE THREAD

**Issue by Wurms2** [Sandrem/FlyCasual#2709]
Starkiller Upsilon used jam action and bug happened.
[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/4715253/LastReplay.replay.zip)
<img width="1642" alt="Screen Shot 2020-06-01 at 11 34 29 PM" src="https://user-images.githubusercontent.com/65094280/83488041-03c13c80-a461-11ea-872a-eab16750f638.png">

**Comment by Sandrem** [comment]
Lieutenant Rivas and Jam Token interaction is fixed
