### ISSUE TITLE
Jam and Target Lock Tokens

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2710]
Hi, the jam action/token allows players to remove blue target lock tokens. That should not be possible because they actually don't exist in the game. (I made the same mistake with Amilyn Holdo earlier).
Thank you

**Comment by Sandrem** [comment]
>> When a ship becomes jammed, the player whose effect caused the ship to gain the jam token chooses for the ship to either remove one of its green tokens or break one of its locks

"Break a lock" and "Remove blue Target Lock token" are the same effect - so it works correctly, just uses names from FE.

In the nearest future I don't plan to change how lock is shown in SE because it can cause a lot of bugs in card abilities that are the same for FE and SE.
