### ISSUE TITLE
Generic YV666 movement caused NRE crash.

### ISSUE THREAD

**Issue by jamesrhum** [Sandrem/FlyCasual#2711]
AI Ship appears to be doing a 2 turn right.
![fly_casual_bug](https://user-images.githubusercontent.com/66371287/83643831-70931e80-a5a8-11ea-9442-a9fb7806d0de.jpg)

[LastReplay.replay.txt](https://github.com/Sandrem/FlyCasual/files/4723700/LastReplay.replay.txt)

**Comment by Sandrem** [comment]
Thank you for replay

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2773
