### ISSUE TITLE
buzzdroids have a null dial card

### ISSUE THREAD

**Issue by boredompwndu** [Sandrem/FlyCasual#2715]
![image](https://user-images.githubusercontent.com/8730661/83701396-866c0800-a5d7-11ea-8d22-73096c69ae2d.png)

This appears on hover of the "remote" text. In normal ships, on hover this would be the ship name slot, and a window would appear with the dial (Which remotes don't have)

**Comment by Sandrem** [comment]
Fixed in dev branch
