### ISSUE TITLE
Autoblasters r1 bullseye - only 3 dice

### ISSUE THREAD

**Issue by jamesrhum** [Sandrem/FlyCasual#2722]
![fly_casual_autoblasters_missing_dice](https://user-images.githubusercontent.com/66371287/83868930-a01a6600-a723-11ea-92cd-4e408befa3c3.jpg)

Used autoblasters against a target at r1 in bulleye - only given 3 dice to roll.

**Comment by Sandrem** [comment]
Fixed in dev-branch
