### ISSUE TITLE
Error in Planning

### ISSUE THREAD

**Issue by stashravens** [Sandrem/FlyCasual#2726]
Going well, kicked off activation and got the crash message as you see here.

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4741123/LastReplay.zip)
![2020-06-06 19_04_03-Fly Casual](https://user-images.githubusercontent.com/66537609/83956110-857de500-a828-11ea-962c-a35dea69c7b6.png)

**Comment by Sandrem** [comment]
This bug appears when you hover over "Remote" label of "Buzz Droid Swarm" panel (it tries to show dial as tooltip, but remote doesn't have it)

Fixed in dev-branch.
