### ISSUE TITLE
Han Solo rebel alliance pilot ability

### ISSUE THREAD

**Issue by jsquinchev** [Sandrem/FlyCasual#2727]
Hello

It seems like Han Solo pilot ability of free rerolls when at range 0-1 of an obstacle seems to work only with attack and defense but not with other game related rolls as is intended to:
![imagen](https://user-images.githubusercontent.com/63166916/83956262-b7d81400-a821-11ea-9ed4-1cb36d20defa.png)

**Comment by Sandrem** [comment]
You are right. This is known issue, it is in list of planned features (https://github.com/Sandrem/FlyCasual/wiki/Planned-Features).
