### ISSUE TITLE
Game crash when Holo moves, right at the start of game

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2732]
Whisper moved, and then the AI was able to move Holo and the game crashed.
![gamecrash](https://user-images.githubusercontent.com/39878663/84019510-a73eaf80-a981-11ea-821f-09855c2b3010.png)
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4745311/LastReplay.zip)

**Comment by Sandrem** [comment]
Fixed in dev-branch.
