### ISSUE TITLE
Crash after RAC structural damage crit

### ISSUE THREAD

**Issue by donfonz** [Sandrem/FlyCasual#2733]
Fifth Brother did passive sensors -> lock on Rear Admiral Chiraneau.  The RAC took the auto damage and 5th bro spent two force to add crit.  Crit was structural damage and game crashed 

Edit: there is a crash after every time Fifth Brother uses his force ability to add crit after firing a homing missile (haven't tried it with his primary attack yet).  Three times in a row now verses varying lists

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668
