### ISSUE TITLE
Error: Null Reference Exception

### ISSUE THREAD

**Issue by MarkLiebold** [Sandrem/FlyCasual#2734]

**Comment by MarkLiebold** [comment]
Game crashed after a maneuver (see crash report). 
![fc_bugreport](https://user-images.githubusercontent.com/55192817/84076605-59a06200-a9d6-11ea-9a86-4786254ebc3a.JPG)
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4748382/LastReplay.zip)

**Comment by Sandrem** [comment]
Fixed
