### ISSUE TITLE
Late game freeze on multiplayer network game

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2739]
It was time to select a ship to perform its maneuver, but the whole game froze. Couldn't select or do anything from this point on. Not sure what happened. Too bad, it was an exciting game taking place. :)

Thanks!

![FC Crash](https://user-images.githubusercontent.com/26996014/84191143-e84fc600-aa4c-11ea-97d4-ada1e73021ab.JPG)

**Comment by lordmagnusen** [comment]
Yes, I've had this happen, but I will take a screen shot next time.

**Comment by Sandrem** [comment]
Fixed
