### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by BlakeAGarcia** [Sandrem/FlyCasual#2741]
![Screenshot (1)](https://user-images.githubusercontent.com/52983269/84334082-0d306000-ab57-11ea-92da-200800fa93cb.png)

Selected Vulture to attack with and error occured.

**Comment by Sandrem** [comment]
Caused if you hover cursor over "Remote" label of Buzz Droids - it tries to show dial, but they don't have it.

Fixed in dev-branch.
