### ISSUE TITLE
Scum Falcon does not recognize Lando's escape craft pilot ability when docked.

### ISSUE THREAD

**Issue by Prototypeperson** [Sandrem/FlyCasual#2745]
When using the scum Falcon, and I have the escape craft docked, with Lando as the pilot (of the escape craft), the game does not allow use of Lando's re-roll ability, as it should.

**Comment by Sandrem** [comment]
Please, next time provide screenshot.
Sometimes players just forget that ship is stressed or where no blanks to reroll.

**Comment by Sandrem** [comment]
I see that wrong name of ability is shown, name of the host-ship. Like "Freighter Captain". I fixed this.
