### ISSUE TITLE
Crashed after Kraken

### ISSUE THREAD

**Issue by Diemilkweed** [Sandrem/FlyCasual#2749]
I just assigned two ships using Kraken, and was about to move the screen to make sure I knew which two ships it was keeping tokens - and it died

![image](https://user-images.githubusercontent.com/27865650/84556760-bcee0500-acf2-11ea-987b-332562cda595.png)

**Comment by Sandrem** [comment]
Bug is caused by hovering mouse over "remote" label of Buzz Droids - it tries to show dial, but they don't have it.

Fixed in dev-branch.
