### ISSUE TITLE
Local network multiplayer issues

### ISSUE THREAD

**Issue by lordmagnusen** [Sandrem/FlyCasual#2751]
Gonna post this on Github too, but I'm having issues doing online multiplayer on a local network (playing with my son). First, unless both players have the same mods on, and possible the same battle mat, the joining player (JP) will not see the host player's (HP) ships; and once JP places his ships, it actually places HP's ships on JP's side. If we ever get to move them, JP moves HP's ships.

Once I figured out (by eliminating possibilities) the thing about mods and battle mat, we managed to get playing... but it always freezes at a certain point, earlier or later. One player makes his moves, actions or attacks, and the other doesn't see it, and that's it. I've had this happen occasionally in online games over the internet, but on my local network, it's every single match.

Adding screenshots, probably won't be of much help. Thanks for the awesome work!

![screenshot1](https://user-images.githubusercontent.com/65992460/84613882-da5dd300-ae9a-11ea-8689-14ca77a7c9a6.jpg)
![screenshot2](https://user-images.githubusercontent.com/65992460/84613893-dd58c380-ae9a-11ea-83ef-7ef882ee0bda.jpg)
![screenshot3](https://user-images.githubusercontent.com/65992460/84613898-de89f080-ae9a-11ea-8bf1-ab9c020e24f1.jpg)

**Comment by lordmagnusen** [comment]
Incidentally, we just managed to play by having my son use a VPN to connect to the game as if he was outside of the local network. That's something!

**Comment by Sandrem** [comment]
Thank you for report. Issues are super-strange, I will check =)

**Comment by lordmagnusen** [comment]
Thanks!

**Comment by Sandrem** [comment]
Some fixes are done.
