### ISSUE TITLE
Error during AI vs. AI match

### ISSUE THREAD

**Issue by ProfesorDino** [Sandrem/FlyCasual#2752]
![image](https://user-images.githubusercontent.com/45677534/84613822-a2569000-ae9a-11ea-9ee8-f705f77c96a8.png)

**Comment by Sandrem** [comment]
Please, next time provide full screenshot - I need to know what lists were used (a lot of bugs are caused by some combination of pilots/upgrades)

**Comment by Sandrem** [comment]
If attack was performed using Heavy Laser Cannon - then I think that I fixed this bug.
