### ISSUE TITLE
NRE during AI ship movement

### ISSUE THREAD

**Issue by jamesrhum** [Sandrem/FlyCasual#2756]
Ship appears to be doing a 1 bank.
![fly_casual_bug_1_bank](https://user-images.githubusercontent.com/66371287/84885984-b31a2800-b08b-11ea-82d2-03128f32c232.jpg)

[LastReplay.replay.txt](https://github.com/Sandrem/FlyCasual/files/4791809/LastReplay.replay.txt)

**Comment by Sandrem** [comment]
Thank you for replay file

Same issue as in https://github.com/Sandrem/FlyCasual/issues/2773
