### ISSUE TITLE
Moralo Eval unable to be placed from reserve

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2757]
Fly Moralo Eval off the table into reserve, but when trying to place at beginning of system phase, get the message that cannot place as overlaps another ship:
![image](https://user-images.githubusercontent.com/36247564/84937506-346eca80-b11f-11ea-946b-dae37ca7f15f.png)

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2663
