### ISSUE TITLE
Thane Kyrell Error

### ISSUE THREAD

**Issue by TheVaasty** [Sandrem/FlyCasual#2764]
I used Thane Kyrell's ability and this error popped up: 
![obrázok](https://user-images.githubusercontent.com/67193160/85202036-f8488f00-b303-11ea-9cea-5f1ec99c3d44.png)

Here's the replay file:
[Replay_Error.zip](https://github.com/Sandrem/FlyCasual/files/4807877/Replay_Error.zip)

Thanks!

**Comment by Sandrem** [comment]
Fixed
