### ISSUE TITLE
Bug Nantex?

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2765]
Hi. I don't know why it crashed. I skipped my turn with darth Maul, then the foe's nantex should have played  but it crashed.
![image](https://user-images.githubusercontent.com/31988939/85271057-8ba3d080-b47a-11ea-8907-d6bf6a99eebd.png)

Here's the replay file.

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4812384/LastReplay.zip)

Thx!

**Comment by Sandrem** [comment]
Fixed
