### ISSUE TITLE
Lists won't generate

### ISSUE THREAD

**Issue by corranhorn25** [Sandrem/FlyCasual#277]
<img width="1392" alt="screen shot 2017-10-13 at 9 38 07 pm" src="https://user-images.githubusercontent.com/32785660/31571820-830c412c-b05f-11e7-9122-9811449f1898.png">
on mac, tried generating that list several times, even with restart. Always renders with one ship on board only.

**Comment by Sandrem** [comment]
Got this bug once on Windows too (not all ships where present after start of battle)

**Comment by corranhorn25** [comment]
Love this game though. Been fun playing it so no worries. Keep at it.

**Comment by Sandrem** [comment]
Cannot reproduce anymore, seems that bug is fixed with another related bugs.
