### ISSUE TITLE
AI activated ship for movement during wrong step of the game

### ISSUE THREAD

**Issue by ftimurs** [Sandrem/FlyCasual#2773]
![image](https://user-images.githubusercontent.com/11545213/85579874-3f3acb00-b609-11ea-9c82-51ae04339356.png)

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4826174/LastReplay.zip)

**Comment by Sandrem** [comment]
Thank you for replay.

---
Important information for bugfixing:
AI called command "ActivateAndMove" during "MovementExecutionSubPhase" instead of "ActivationSubPhase".
Previous AI ship performed red maneuver (maybe important?)

**Comment by Sandrem** [comment]
Fixed
