### ISSUE TITLE
Error in combat phase (Biggs Darklighter?)

### ISSUE THREAD

**Issue by elsapo70** [Sandrem/FlyCasual#2776]
The rror message appears as soon as the opponent attacks.
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4830275/LastReplay.zip)

**Comment by Sandrem** [comment]
First Edition, "Partisan Title" mod must be turned on.

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2413
