### ISSUE TITLE
At start of game, can setup the Lambda Shuttle over the board edge

### ISSUE THREAD

**Issue by pinosante** [Sandrem/FlyCasual#2779]
I pressed q to turn it 90 degrees. And then was able to position it outside the board edge. After first move, he is removed from the board (because outside the board range)

![image](https://user-images.githubusercontent.com/39878663/85899387-3eb75580-b7fe-11ea-95b4-ca8615b1ab2a.png)

**Comment by Sandrem** [comment]
Fixed
