### ISSUE TITLE
Autoblasters+Marksmanship not working

### ISSUE THREAD

**Issue by Korran12** [Sandrem/FlyCasual#2780]
![Screenshot_20200626_192021_com sandrem flycasual](https://user-images.githubusercontent.com/67489605/85910193-36055600-b7e3-11ea-9bff-6bebb9a34487.jpg)
Hello i want to report that autoblasters+Marksmanship its not working on Dengar. I had a range 1 in bullseye to Rose and the autoblasters didn't add the bonus die and after throwing dice it didn't let me change one to critical with Marksmanship.

Note: that crit dengar has its a damaged engine.

**Comment by Sandrem** [comment]
Fixed in dev-branch.
