### ISSUE TITLE
Wedge k-turn - double blocked - game crashed

### ISSUE THREAD

**Issue by Full-Throtttle** [Sandrem/FlyCasual#2789]
I finished my moves.  AI took over and tried to do a k-turn with Wedge.  Two ships were in front causing a bump.  Then it crashed.

![image](https://user-images.githubusercontent.com/67638243/86123372-4a8e6a80-bad1-11ea-9f47-3f2e2a630fca.png)
![image](https://user-images.githubusercontent.com/67638243/86123739-ea4bf880-bad1-11ea-8853-dbfa0e3ce6df.png)

I can't upload the replay file.  Not sure why.  Filetype doesn't seem to be allowed.

**Comment by rune-b** [comment]
That's a strange error.

Yes, github doesn't like the replay file type for some reason. You can zip it and then upload it. Or open it in notepad and paste the contents here.

**Comment by Sandrem** [comment]
Still cannot reproduce
