### ISSUE TITLE
Echo declock with Collision Detector and the game thinking every decloak was over an obstacle

### ISSUE THREAD

**Issue by enosjr123** [Sandrem/FlyCasual#2791]
I used Echo to decloak over a rock,  used a charge and after that every time I decloaked it kept giving me a debris request to use the charge, even when there was no obstacle.   I did it to me several times, I which Echo lost his ability window becuase the game believed that I was constantly going over a obstacle.

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3136
