### ISSUE TITLE
Game doesn't allow any action (PC)

### ISSUE THREAD

**Issue by elsapo70** [Sandrem/FlyCasual#2795]
While moving squad, juist after one ship movement, it's not possible to move the other ships anymore. It happens many times, with different ships/upgrades.

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4870084/LastReplay.zip)

**Comment by rune-b** [comment]
Hi
Unfortunately that replay doesn't work for me. I get an "error during squad creation" or something like that.

Does it happen consistently, or does it sometimes work, even with the exact same squad that didn't work earlier?

**Comment by Sandrem** [comment]
Fixed
