### ISSUE TITLE
Tie Reaper Bug Multiplayer PC

### ISSUE THREAD

**Issue by lecypher2319** [Sandrem/FlyCasual#2796]
Online play, If squad has a tie reaper in it, the game will not allow the other player to take their turn after moving.
The Tie Reaper will move on my computer and take an action, but will not move on the other persons computer and if there are multiple ships after reaper, example Initiative 3 reaper and also have 2 initiative 4 ships, anything once it gets to the reaper don't move or do anything on other persons computer.
Other squads work fine if they don't have a reaper in them

**Comment by Sandrem** [comment]
Fixed
