### ISSUE TITLE
Homing Missile fired at AI causes game crash

### ISSUE THREAD

**Issue by desertowl1026** [Sandrem/FlyCasual#2797]
<img width="1440" alt="Untitled" src="https://user-images.githubusercontent.com/67872473/86538271-ef31f300-bea9-11ea-8b5e-ea4b9dbaf056.png">
I fired homing missiles at Mace Windu; he accepted the automatic damage but then the game crashed.

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2668
