### ISSUE TITLE
Out of arc attacks information causes misunderstanding

### ISSUE THREAD

**Issue by Strikewolf** [Sandrem/FlyCasual#280]
When attempting to select an enemy during combat, the game throws an "Outside of Firing arc" error despite the attacking ship having a Twin Laser Turret equipped.

**Comment by Sandrem** [comment]
At the moment "Out of arc" message just indicates position of enemy. But because of red color of message - many players think that this is error that means "Cannot attack because out of arc".
Information about range and in/out of arc will be changed later.

**Comment by Sandrem** [comment]
New way to check distance/arc is added in 0.3.2
