### ISSUE TITLE
BUG restarting a match

### ISSUE THREAD

**Issue by jsquinchev** [Sandrem/FlyCasual#2800]
![imagen](https://user-images.githubusercontent.com/63166916/86624221-8ff6e000-bf88-11ea-8400-2ffc42e8c2f9.png)

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4880520/LastReplay.zip)

I put the replay file inside the .ZIP because, it din't allow me to put the original file extension

Although I can still play the restarted game

**Comment by Sandrem** [comment]
Fixed in dev-branch
