### ISSUE TITLE
"Focus Dice Modification Not Found"

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2802]
Hi,  
Unfortunately, the error message disappeared before I got a screenshot.  It popped up even though I did have a focus, and it changed one eyeball green to an evade, and cancelled one of the attacker's hits, but then the game basically froze.  The OK button was still present but clicking it did nothing.  Ships involved were the StarViper (attacker) and Tie Bomber (defender) if that helps.

**Comment by hdg204** [comment]
![image](https://user-images.githubusercontent.com/36624710/87225602-43dfdd00-c386-11ea-8afa-4f2d98b36f0d.png)
Same issue, except it was Luke Skywalker in an X-Wing using the Force. Managed to screenshot the error as it popped up

**Comment by hdg204** [comment]
The issue is still present in the latest version. Happened with the advanced targeting computer

**Comment by hdg204** [comment]
![image](https://user-images.githubusercontent.com/36624710/87232041-de0a4a00-c3b3-11ea-90e0-1383e963933e.png)
Another screenshot of the similar error. Not sure if there's anything in common

**Comment by Sandrem** [comment]
Fixed
