### ISSUE TITLE
Homing missiles crash

### ISSUE THREAD

**Issue by ammonpm** [Sandrem/FlyCasual#2803]
Crashes every time I use homing missiles. 
![Screenshot_20200707-203145_Fly Casual](https://user-images.githubusercontent.com/12172713/86872393-1a2a6b80-c091-11ea-95dc-ec3fb15b4363.jpg)
![Screenshot_20200707-203157_Fly Casual](https://user-images.githubusercontent.com/12172713/86872401-1dbdf280-c091-11ea-953e-34f3a0421285.jpg)

**Comment by Sandrem** [comment]
Fixed in dev-branch
