### ISSUE TITLE
Homing Missiles Cause Game to Crash

### ISSUE THREAD

**Issue by B-Barry-B** [Sandrem/FlyCasual#2809]
When firing homing missiles the game crashes.   

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/4904344/LastReplay.replay.zip)
<img width="1435" alt="Screen Shot 2020-07-10 at 12 28 57 PM" src="https://user-images.githubusercontent.com/68121508/87177844-4c62e580-c2aa-11ea-8123-46c6f3480e6f.png">

**Comment by Sandrem** [comment]
Fixed in dev-build
