### ISSUE TITLE
"CollisionMeshData couldn't be created because the mesh has been marked as non-accessible"

### ISSUE THREAD

**Issue by Takko550** [Sandrem/FlyCasual#2811]
Attached LastReplay.

Error occured during placement of ships at beginning.

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4906992/LastReplay.zip)

**Comment by Sandrem** [comment]
What version of Fly Casual?

**Comment by grandpajive** [comment]
Same issue. 1.3. game is still playable.

**Comment by STONEHANDS33** [comment]
Same issue, 1.3. Popped up after nearly every input: placing astroids, placing ships after moving.

**Comment by grandpajive** [comment]
I was able to correct this issue by reselecting skins from my saved squads, then play. Issue didn't pop up at all.

**Comment by subhedgehog** [comment]
Added note: was flying against an AI Tie swarm, noticed that the error interrupted detection of overlapping obstacles (no roll for strain after landing on, passing through gas cloud).
Error triggered before placing each ship, as AI ship set a dial, as AI ship revealed a dial.

**Comment by clm133** [comment]
I've been able to reproduce the issue by using gas cloud obstacles. when not using gas cloud obstacles the game runs fine.

**Comment by Codyeed** [comment]
> I've been able to reproduce the issue by using gas cloud obstacles. when not using gas cloud obstacles the game runs fine.

This was the same issue for me! Thanks.

**Comment by ootinni** [comment]
Same problem, after laying final obstacle (bacon gas cloud)
![Screenshot_20200714-014610](https://user-images.githubusercontent.com/52763171/87368834-bd3e2200-c576-11ea-8656-978098139067.png)

**Comment by grandpajive** [comment]
I was able to use the bacon obstacle (only one). The newer gas clouds caused the error to pop up. 

So the answer is to use bacon for now ;)

**Comment by JohnnyTSpark** [comment]
Yes, same here: new gas clouds caused a consistent error for me, flying various squad combos in 1.3.

**Comment by Sandrem** [comment]
Fixed
