### ISSUE TITLE
Collision error

### ISSUE THREAD

**Issue by starjoe4** [Sandrem/FlyCasual#2815]
Happened while the drones were moving, also while their dials were being set by the AI.

![image](https://user-images.githubusercontent.com/47924192/87255274-48c09180-c457-11ea-97f4-cfaca8cc2b43.png)

**Comment by Sandrem** [comment]
Please, don't use gas clouds until release of new version.

Duplicate of https://github.com/Sandrem/FlyCasual/issues/2811
