### ISSUE TITLE
Crash throughout the game repeatedly

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#2817]
I keep getting this error after the game starts. It repeats almost every turn.

![image](https://user-images.githubusercontent.com/26996014/87357950-b8975080-c519-11ea-9998-c2974bf22a3e.png)

**Comment by Sandrem** [comment]
Please, don't use gas clouds until release of new version.

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/2811

**Comment by TNG-Wing** [comment]
OK, thanks!
