### ISSUE TITLE
Cannot attack while playing lan matches.

### ISSUE THREAD

**Issue by VapePanther** [Sandrem/FlyCasual#2818]
When attacking while playing over lan the attack dice are rolled but when pressing "OK" after the roll nothing happens.

**Comment by cutecaleb** [comment]
Concur.  I posted this on Reddit as well in the 1.3 announcement.  Further details and what we've tried:
Occurs during LAN online games but not during AI matches, happens regardless of who hosts game (3 computers all tried in various combinations of host/join)
1) Joining thru internal or external network works just fine.  Joining to remote online game via LogMeIn Hamachi <OR> ZeroTier works like a CHARM (g-r-e-a-t work on this, Sandrem!!) 
2) All in-game setup and listbuilding works fine, obstacles placed, ships deploy, both sets of dials set fine.  Turn 1 allows for all ships to move & action as expected.  
3) Upon any first engagement phase where dice are rolled (doesn't matter who it is between host/guest), dice are showed to roll... then freeze.  Buttons for focus/HanSolo ability/targetlock/etc APPEAR, but are NON-selectable.  "OK" button does not work.  Game must be exited to desktop or main menu, but **_ALWAYS_** freezes at attack

Things we have tried (all without any changes):
-- FULL, clean re-install that removes all preferences, folders, etc via uninstaller app
-- Restarts and cache clears
-- setting both lists to match/identical, including same playmat selection, etc (noted in another post as a possible solution)
-- tried both thru Hamachi and ZeroTier w multiple internal vs external IPs (always connects and joins fine!)
-- flying around the board for several turns before attack (vs straight fast joust to shoot on turn 1), still freezes
-- played with port-forwarding/7777 options to play WITHOUT VPN services, but even that didn't work.  

All we could come up with was something dropping out during the engagement phase that breaks connections.  Clearly, packets of data for showing obstacle placement, connect/joining, ship placement, etc all WORK across the network during setup, activation, and systems phases.  

Happy to provide any extra info or screenshots as needed!  Able and willing to try and experiment w permutations if you have suggestions!!  And... KEEP UP THE GREAT WORK! 
Let us know if there's any way we can help :)

--Jas

**Comment by InfiniteWeekend** [comment]
Thanks @cutecaleb for catching [my other post on this topic](https://github.com/Sandrem/FlyCasual/issues/2822). 
This is the same issue I'm experiencing in the link above.

**Comment by banjoface** [comment]
Similar issue here. Tried to play with a friend over Hamachi. Movement worked fine. Then we rolled the dice and couldn't resolve any additional actions. It first happened with the Lando card. We restarted a fresh game and same issue happened during combat. Dice rolled but there was no option to continue after that.

**Comment by Sandrem** [comment]
Fixed

**Comment by cutecaleb** [comment]
That's fantastic.  GREAT work, Sandrem!!
--Jas
