### ISSUE TITLE
Prox Mines

### ISSUE THREAD

**Issue by Slump138** [Sandrem/FlyCasual#2819]
![error prox mines](https://user-images.githubusercontent.com/68388143/87686512-90defd00-c752-11ea-9db1-627ed91aa87b.png)

the AI ran over my prox mines and this error came up

**Comment by rune-b** [comment]
The error seems to be related to the tractor token. But how did the E-Wing get a tractor token in this situation?

**Comment by Sandrem** [comment]
Fixed
