### ISSUE TITLE
Help Getting Started Adding Ships

### ISSUE THREAD

**Issue by Conzar** [Sandrem/FlyCasual#282]
Greetings,
  I would like to help with adding new ships.  Note, I never programmed in C# or unity before but an proficient in Java and C.

Anyways, here is my first go at adding a TIE Fighter (EpsilonLeader).  
https://github.com/Conzar/FlyCasual/blob/TIE_FO_EpsilonLeaderPilot/Assets/Scripts/Model/Ships/TIE%20FO/EpsilonLeader.cs

**Questions**
* Where do I add the ship template (cardboard that goes on the plastic template in the game)?
* How do I debug?  (There is a problem with my code at the start of combat that causes the game to lockup.  Is there a log I can write to or print statements to help me find the problem?)

**Comment by Sandrem** [comment]
Hi. We have slack worspace for content developers, you are welcome:
https://join.slack.com/t/flycasualgame/shared_invite/MjM4MDM4ODYzMDQwLTE1MDQ5Nzc2MDItMzI5NmY2M2QxMQ

**Comment by Sandrem** [comment]
About Epsilon Leader:
1) You don't need to add Tech slot to pilot - it is already added in code of the ship. Use this only to add Elite slot if required.
2) You can do more simple: "Ship.GenericShip EpsilonLeader = this".;
3) Ability is activated on the start of Combat Phase, but you use Combat.Attacker - this variable is used suring combat when attacker and defender where declared, this is wrong. Use "this.Owner.ships" instead.
But as for first attempt - good woork =)

**Comment by Sandrem** [comment]
For cardboard image I use images from TTS X-Wing module. If you don't have TTS in your steam library, you can use my archive with cached images of X-Wing module: https://www.dropbox.com/s/38tb6gatkkh0uyo/TTS_XWing_Images.zip?dl=0
Note that you need not only image, but also to create material and set it's Abledo as your image.

**Comment by Sandrem** [comment]
Visual Studio has debugger for Unity.
Also you can use "Debug.Log(value)" for console output (best way), "Messages.ShowInfo(value)" to show popup message, "UI.AddTestLogEntry(value)" to add record in in-game log window.

See you in Slack workspace! =)

**Comment by Conzar** [comment]
Thank you, I have added the changes [here](https://github.com/Conzar/FlyCasual/blob/TIE_FO_EpsilonLeaderPilot/Assets/Scripts/Model/Ships/TIE%20FO/EpsilonLeader.cs).  Thank you!

**Comment by Conzar** [comment]
All good.  Closing this issue.
