### ISSUE TITLE
AI Corran Horn crash

### ISSUE THREAD

**Issue by m-0day** [Sandrem/FlyCasual#2820]
not sure if leebo regaining a calculate is crashing fly cas or it's another issue.
![Annotation 2020-07-16 112030](https://user-images.githubusercontent.com/50684178/87689804-a6562600-c756-11ea-9c10-1193e77005af.png)

**Comment by m-0day** [comment]
duh, I can't read. it has to do with corran horn's bullseye arc.
P.S. I have yet to see the AI choose to acquire a lock outside of range 3 with any unit. This would be a nice upgrade to the AI if it did that as well.

**Comment by rune-b** [comment]
Confirmed. I got the same. Playing a single Corran against a single AI Corran. No problems with my ship, but the second time the AI was in range, but not in bullseye, it crashed:

![image](https://user-images.githubusercontent.com/11047987/92409990-ddd3c400-f142-11ea-9914-d32ebf4cefea.png)

![image](https://user-images.githubusercontent.com/11047987/92410013-fba12900-f142-11ea-89b7-c2a412fb6b31.png)
