### ISSUE TITLE
Obstacle "Mesh" error

### ISSUE THREAD

**Issue by Sergovan1** [Sandrem/FlyCasual#2821]
While laying down obstacles, I had the following error:

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/4935191/LastReplay.replay.zip)

**Comment by JohnnyTSpark** [comment]
yep, me too: just had that same issue. Rebel and Imperial squad, no new upgrades or ships, Rebels with two gas clouds and debris, Imperials with three default asteroids. 
<img width="2560" alt="Screenshot 2020-07-20 at 23 13 11" src="https://user-images.githubusercontent.com/50407085/87991764-c67f3f80-cade-11ea-98ec-56dbf3b282f5.png">

**Comment by Vieja** [comment]
Hi, i getting this error constantly while playing versus AI as well as online.
![image](https://user-images.githubusercontent.com/35605153/88487282-f36e9f00-cf83-11ea-8aac-01bbf8b6f4bb.png)

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4978231/LastReplay.zip)

**Comment by Sandrem** [comment]
Fixed
