### ISSUE TITLE
Multiplayer: After Rolling Attack Dice 'OK' or 'Focus' does not progress game or close window

### ISSUE THREAD

**Issue by InfiniteWeekend** [Sandrem/FlyCasual#2822]
Hi there! First off, we're very excited about Multiplayer. Great work so far. 
When we get to the first combat in every scenario (tested 5 times) and red dice are rolled the window does not accept the 'OK' command or 'Focus' command. Thereby - the game becomes locked and we must close to desktop and start over. 
We've retried in a variety of scenarios, but in any case no matter who initiates combat the game is locked at first red dice throw. 
I'll try again and add screenshots later if I can. 

Game Setup: 
- Using Hamachi VPN
- One Macbook Pro 2016 vs Macbook Air 2015 (MacOS Build 1.3 on both)

**Comment by cutecaleb** [comment]
Hi InfiniteWeekend!
Just wanted to add a note here also -- 2 of us had noticed this same thing, but it was posted in the "Cannot attack in LAN game" thread.  Sounds very similar, including setup w macs that I was describing!  --Jas

**Comment by JohnnyTSpark** [comment]
Same issue here, consistently: two MacBook Pros running latest build Catalina, 1.3 of FC, Online game connecting over Hamachi VPN. Tried both 'complex' squads (uniques, lots of upgrades) and stock ships (basic pilots, no ship shenanigans, no upgrades). Consistently sticks after attack dice rolled (on first attack: active player can't press Okay, defending player sees attack dice pool). All other features work in the background (change view, Stats, ID number display, scrolling etc).

**Comment by InfiniteWeekend** [comment]
> Same issue here, consistently: two MacBook Pros running latest build Catalina, 1.3 of FC, Online game connecting over Hamachi VPN. Tried both 'complex' squads (uniques, lots of upgrades) and stock ships (basic pilots, no ship shenanigans, no upgrades). Consistently sticks after attack dice rolled (on first attack: active player can't press Okay, defending player sees attack dice pool). All other features work in the background (change view, Stats, ID number display, scrolling etc).

Exactly! Thanks for posting! 
We tried 5 different squads and alternating who fires first, same issue each time.

**Comment by Sandrem** [comment]
Fixed
