### ISSUE TITLE
Every game I play is doing this. 

### ISSUE THREAD

**Issue by Cannibal-Soup** [Sandrem/FlyCasual#2823]
![Screenshot_20200718-114106_Fly Casual](https://user-images.githubusercontent.com/68479348/87859771-78a2e580-c8ec-11ea-9af6-2bcdce3d3135.jpg)

This has been happening in every single game I've tried to play in recent days. No idea what's wrong, just that I have to keep pounding 'close' over and over every turn. I took a screenshot to help those technically proficient to figure it out. It has been very frustrating.

**Comment by Cannibal-Soup** [comment]
Here it is again.
![Screenshot_20200718-195504_Fly Casual](https://user-images.githubusercontent.com/68479348/87865994-b3c70800-c930-11ea-8260-542fc06a3e69.jpg)

**Comment by TychoCelchu505** [comment]
![Annotation 2020-07-20 140404](https://user-images.githubusercontent.com/41827692/87970748-2c91a580-ca92-11ea-8e07-6ed6339515af.png)
