### ISSUE TITLE
crash on setting 1st dial

### ISSUE THREAD

**Issue by Grande-Rojo** [Sandrem/FlyCasual#2826]
![image](https://user-images.githubusercontent.com/64370198/88205302-8de48080-cc1a-11ea-80c3-0e56db4dccbb.png)

Just upgraded to 1.3

Setting 1st dial every game, get this crash.  Still gathering occurrences, but initially seems to be just when YT-2400 is present again... other lists work ok without Yt-2400

**Comment by Grande-Rojo** [comment]
More YT-2400 weirdness, tried different pilots (this time space fringer) and when you are selecting dials, the selection you make is not always the one that appears next to the card.  Seems to be something consistent with YT-2400 as a platform.

**Comment by Sandrem** [comment]
Fixed
