### ISSUE TITLE
Overlapped and landed on top of other ship.

### ISSUE THREAD

**Issue by mishari27** [Sandrem/FlyCasual#2828]
My Plo koon went 2 forward and ended up on top of the Tie, the Tie had done a 4-k.

![flycasualbug](https://user-images.githubusercontent.com/54389008/88207669-ce62ef00-cc58-11ea-8885-d3bf780470cb.jpg)

**Comment by wavemanns** [comment]
I am getting this issue as well. 
![ship_overlap_ex](https://user-images.githubusercontent.com/6612122/89212966-c715dc80-d59a-11ea-8966-696752b09a3c.png)

**Comment by Sandrem** [comment]
Some fixes are done. If this bug will be present in 1.8+, please inform me.
