### ISSUE TITLE
Biggs prevents attack of TIE/SF

### ISSUE THREAD

**Issue by jxforema** [Sandrem/FlyCasual#283]
Tie/SF can set target, but won't actually make an attack

**Comment by Sandrem** [comment]
Please, next time attach screenshot.
What arc was used gor attack (forward-facing arc or rear-facing arc)? What distance was to the enemy? What weapon was used (primary of secondary)? Was there Biggs Darklighter on the table?

**Comment by jxforema** [comment]
I'll be sure to get a shot next time


All attacks were primary weapons

All attacks were in forward arc

All attacks were range one or two

Biggs was on the table, but not in primary or secondary arc of all four TIE/sf



________________________________

**Comment by Sandrem** [comment]
Thank you for information, specially about presence of Biggs - I had few similar bugs with him before (even he is not in arc).

**Comment by Sandrem** [comment]
Fixed
