### ISSUE TITLE
Bug upsilon shot

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2831]
Hello, Here's a bug to report.

[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/4976485/LastReplay.zip)
![screenshotbug](https://user-images.githubusercontent.com/31988939/88466388-0c1b7e00-cecc-11ea-89f5-b4c989d6517b.png)

**Comment by rune-b** [comment]
This is the same bug as #2832, so I'm closing this one
