### ISSUE TITLE
Obi-wan, spend a force gain a force. UI becomes non-responsive

### ISSUE THREAD

**Issue by TS7415** [Sandrem/FlyCasual#2842]
In my example the V-19 rolled a hit and a focus. I clicked to spend a focus to get 2 hits. Out of habit I immediately clicked the OK button to proceed with combat. 

This glitch can be replicated by doing those exact steps, i had it happen 2x in a row.

*Thanks so much for this awesome app I use it on my phone and computer and love it so much
![Screenshot_20200731-161210_Fly Casual](https://user-images.githubusercontent.com/69057211/89074132-d225fe00-d349-11ea-9a97-1630870a6a60.jpg)

**Comment by Sandrem** [comment]
Fixed
