### ISSUE TITLE
Some random AI squadrons doesn't work 

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2843]
I wasn't quick enough to screenshot all the errors I saw, so there is at least one more squad with this problem. If I remember correctly the error message mentioned "tieadvanced" 

![Screenshot_20200731-214918](https://user-images.githubusercontent.com/11047987/89074280-6a3cdb00-d37c-11ea-8fed-973d039e44b1.png)
![Screenshot_20200731-214824](https://user-images.githubusercontent.com/11047987/89074289-6e68f880-d37c-11ea-9bb6-332435a587c1.png)

**Comment by Sandrem** [comment]
Fixed
