### ISSUE TITLE
Crashes every match while picking maneuvers

### ISSUE THREAD

**Issue by donfonz** [Sandrem/FlyCasual#2849]
No issue during 1.3 (which I am now stuck playing), but with 1.4 the game will become unresponsive while selecting maneuvers.  Sometimes I can make it through one round of selecting maneuvers before it happens but usually not.  I've tried uninstall/reinstall and restarting PC.  After selecting a maneuver, it gets stuck in a state where the maneuvers menu disappears but I am unable to select new ships' maneuvers and there is no "Next" option either.

**Comment by Arahain** [comment]
- Did you or the opponent fly specific ships / Pilots/ upgrades or does the error occur every game with any kind of ship? If didn't do so already, could you make a clean test with something like basic tie vs basic x-wing and check if you are still stuck?
- What platform are you playing the game on? 
- I assume there was no kind of error message, the game was just refusing to progress to the next phase?

**Comment by Sandrem** [comment]
Fixed
