### ISSUE TITLE
L33t programming

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#2850]
Once scum crew L33t is flipped it needs to reduce the difficulty of bank maneuvers. This did not work on Dengar. (Android, 1.4 hot fix 1)

**Comment by rune-b** [comment]
It worked for me just now. Remember that it only works if the ship has no shields left

![image](https://user-images.githubusercontent.com/11047987/91097213-91c35280-e65f-11ea-9281-d83d8b9e03f0.png)
