### ISSUE TITLE
Agility lowered instead of increased at range 3

### ISSUE THREAD

**Issue by Furryrodian** [Sandrem/FlyCasual#2852]
![bug report](https://user-images.githubusercontent.com/38586632/89185323-0ecf4080-d568-11ea-9d1e-a31bd6286e28.png)

See the range 3 attack in the attached photo. I have seen this a couple times now but haven't been able to confirm it until now. My Zizi took a shot at range 3 from the AI Jedi and instead of gaining an extra die he lost a die.

**Comment by baronklutz** [comment]
It spent a force for predictive shot, meaning that you can't roll more defence dice than they rolled hits or crits

**Comment by Furryrodian** [comment]
Yup! My bad, I was reading it as Foresight.
