### ISSUE TITLE
Rush changing from I2 to I6 essentially stops FC

### ISSUE THREAD

**Issue by LanikTnt** [Sandrem/FlyCasual#2854]
Was able to see this issue a few times today.  On the turn where you damage "Rush" when he is playing as AI, you receive a message that his enagagement has been delayed.  But he doesn't pick a target or fire.  The game just stops.  It doesn't throw an error, there's just no way to move the game state forward.  You cannot even Skip Turn out of it.  Only real recourse is to Restart the game and play until he's damaged again (or the game is over).

**Comment by Sandrem** [comment]
Fixed
