### ISSUE TITLE
Republic Y-Wings that fail maneuver can overlap

### ISSUE THREAD

**Issue by LuslecZVG** [Sandrem/FlyCasual#2855]
I've only managed it twice, but the consistent parts are one Y banking in, the other should bump doing a straight, but overlaps and still allows for an action.
![RepublicYOverlap](https://user-images.githubusercontent.com/69182970/89252777-bc823400-d5e8-11ea-999d-7542247eca8d.jpg)

**Comment by Sandrem** [comment]
Fixed
