### ISSUE TITLE
Error when loading CIS squad from Popular list

### ISSUE THREAD

**Issue by JohnnyTSpark** [Sandrem/FlyCasual#2856]
1.4 hotfix 1 version threw up a problem with named pilot error, with attached error message. Mac OS X 10.15.6. The error came up as soon as I pressed Load against the CIS squad.
![Screenshot 2020-08-04 at 23 01 30](https://user-images.githubusercontent.com/50407085/89349846-ccf8e400-d6a6-11ea-9772-2a0523eda3bc.png)

**Comment by rune-b** [comment]
Hi. Do you remember which squad this was?

**Comment by JohnnyTSpark** [comment]
I'm pretty sure it was the Sear swarm option: I'm still getting an error, as per the attached.
![Screenshot 2020-08-10 at 09 23 24](https://user-images.githubusercontent.com/50407085/89763876-536c5600-daeb-11ea-8e6d-c933f4708842.jpg)

**Comment by rune-b** [comment]
I don't know how to reproduce that first error, but I also get the second error on loading the Sear Swarm

![image](https://user-images.githubusercontent.com/11047987/91223873-94867c00-e721-11ea-9bf6-1a5aab48d588.png)

**Comment by Sandrem** [comment]
Fixed
