### ISSUE TITLE
Large ship lost defense die while having 1 tractor token

### ISSUE THREAD

**Issue by FTFup** [Sandrem/FlyCasual#2858]
(hopefully screen shot works)
Maul which received a tractor token from a friendly Sun Fac with Ensnare got shot by the i3 M3A with HLC at range 2. Maul's defense was decreased by 1 due to tractor token. 
Screen shot from test game. Maul+Sun vs random starvipers. range 3 shot and Maul has 1 tractor token; should have total of 2 green dice, only given 1. 
The alerts did say range 3 +1 dice, but did not flash the "tractored -1 defense die" like expected. 
thanks! 
![image](https://user-images.githubusercontent.com/52437093/89487410-f9763400-d76a-11ea-924a-9b7a47a6f6a5.png)

**Comment by VexingVision** [comment]
This is the correct behaviour.

While a large ship requires three tractor tokens to be forcibly barrel-rolled or boosted, any amount of tractor tokens on a ship will reduce the ship's defense dice by one.

**Comment by Sandrem** [comment]
Correct behavior, closed.

**Comment by FTFup** [comment]
I thought this was changed at the same time as the 3 tractor tokens to move
a large based ship. I very well could be wrong, but in rules reference for
tractored, a large base ship isn't 'tractored' until it has 3. And the
defense reduction only affects ships which are 'tractored' based on the
last couple bullets in the screen shot.

We could easily be missing something though, but the several people I
checked with had the same interpretation.

Thanks

**Comment by VexingVision** [comment]
I had been wrong - it has been changed in September 2019. @FTFup's interpretation is now correct - a ship will only lose a defense die once it has been "tractored", which means having reached 1 tractor token for a small ship, 2 tractor tokens for a medium ship or 3 tractor tokens for a large ship, regardless of whether the tractored ship has been moved or not by the tractor effect.

Single tractor tokens no longer affect larger ships.


This was new to me as well, thanks so much for pointing it out before I make a fool out of myself at the next tourney, seeing that I loved playing around with tractor tokens.

**Comment by Sandrem** [comment]
I will check

**Comment by FTFup** [comment]
No worries, glad to help!!

Thanks!

**Comment by Sandrem** [comment]
Fixed
