### ISSUE TITLE
3d/2d Switch doesn't work and obi wan's ability freezes the game

### ISSUE THREAD

**Issue by archer881** [Sandrem/FlyCasual#2861]
Usually on windows, (with game in windowed mode) at start of the game vs ai, i can't switch from 3d to 2d mode and it's useless to continue clickin' on the key. After a random period of time it switches alone.   
I also discovered a bug where i had in my team plo koon and obi wan, i took an attack and i had to choose with plo if using force or focus to change dice and suddenly appeared the message of obi's power and the game bugged. I couldn't click any of the 2 messages on the screen but i could click "stats" or press esc to main menu, so i restarted and the game blocked in the loadin page.

**Comment by archer881** [comment]
sorry i left a problem i always have and it's not situational. With mouse, if i want to choose a maneuver, i have to click it very soft and fast because it always gives me a faster maneuver as if i continue pressing the left click.

**Comment by archer881** [comment]
ok i replicated the second bug! when the obi wan power message appears, if u click another button like focus, force or ok, it freezes.

**Comment by rune-b** [comment]
I tried reproducing that Obi-Wan bug, but it worked for me. Can you post a screenshot of the game when the bug has occurred?

**Comment by archer881** [comment]
![screen](https://user-images.githubusercontent.com/23039620/89889383-d071fb00-dbd1-11ea-8aec-e994785dab40.JPG)
in this screen the game is partially freezed. i can open main menu and scroll the map but all the buttons don't work

**Comment by Baladas89** [comment]
The issue with Obi Wan's ability happens to me a lot. I tried (and failed) to play Republic twice tonight, both games ended early because I forgot Obi Wan was nearby after spending a focus and clicked "OK" before answering the popup on his ability. This is on Android.

**Comment by Sandrem** [comment]
Fixed
