### ISSUE TITLE
Thane ability freezing game

### ISSUE THREAD

**Issue by Europa4** [Sandrem/FlyCasual#2864]
![image](https://user-images.githubusercontent.com/41763327/89707846-1462c700-d96a-11ea-920a-1f32f51ff63d.png)
Using Thane's ability sometimes freezes causes the window to become non-responsive. Buttons still highlight as you mouseover but don't seem to do anything on click. Seems to only happen when the enemy has only one damage card.

**Comment by rune-b** [comment]
I just tried this, but it worked for me. Against a ship with 1 face down damage card. I clicked the OK button in the lower right corner and the ability was completed. But I think it is a bit un-intuitive which button you are supposed to click in this picture...

**Comment by rune-b** [comment]
But the round after, when the ship had 2 damage cards, I did get this bug. Was not able to click anything

![image](https://user-images.githubusercontent.com/11047987/92408540-0efdc580-f13e-11ea-8816-6f07ffd2ff33.png)

**Comment by Sandrem** [comment]
Fixed
