### ISSUE TITLE
Online Multiplayer: After failing an action, next ship to move cannot. "This ship has already executed their maneuver" 

### ISSUE THREAD

**Issue by justinkid01** [Sandrem/FlyCasual#2870]
I don't have a screenshot, but I have tested it several times with the same result:

In online multiplayer, after failing an action with any ship (I've tested barrel roll, boost, and target lock) when you try to move the next ship, a red message appears on the bottom of the screen with text along the lines of "This ship has already executed their maneuver." After receiving this message, you will not be able to move the ship no matter how many times you click it, effectively ending the game. You cannot continue playing until that ship has performed its maneuver, which you are unable to.

Additional Details:
My friend and I connected via IP address and played several games with each one freezing after any ship failed an action (as described above. We tested Scum, Rebel Alliance, and Galactic Empire). After we noticed this pattern, we played another game only this time we made sure not to fail any actions, and completed the game without issue.

**Comment by JeffSkyrunner** [comment]
Confirmed, happened to me 100% of the times.

**Comment by JeffSkyrunner** [comment]
btw, it happens also if you try to target a ship outside your firing arc or too distant

**Comment by Sandrem** [comment]
Fixed
