### ISSUE TITLE
Online Multiplayer: Game stops at Random Points

### ISSUE THREAD

**Issue by Ember369** [Sandrem/FlyCasual#2875]
I've been playing online with a friend locally (which I realise is pretty experimental), though for some reason the game seems to break after playing for a few turns.

I realise that this is pretty similar to **PR#2870**, but the "This ship has already executed their manoeuvre" message doesn't show up at all, so I considered this to be a separate issue.

It can happen during any point of the game (manoeuvre, action, attack, etc.), though always occurs on **my computer**, not my friend's. Could this be linked to a MacOS Catalina issue (my friend's on Catalina, though I'm on Mojave)?

The issue is pretty reproducible by the way: it happens pretty much every game. We're both using the '**1.4 Hotfix**', by the way.

For example, in the below image, the player with the VT-49 had just chosen their template from the manoeuvre dial, though there was no 'Next' button present to continue the game.
![Online Stops](https://user-images.githubusercontent.com/59035469/90474034-bbfca800-e167-11ea-9783-3c0dd2f434cc.png)

I've attached my LastReplay.replay just in case if it helps.

[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/5088474/LastReplay.replay.zip)

**Comment by rune-b** [comment]
Hi
Are you hosting the game and your friend joining, or the other way around?

**Comment by Ember369** [comment]
It seems to occur regardless of who hosts the game.

**Comment by baloo887** [comment]
I'm facing the same issue. At some random point, typically after two/three rounds, the game freezes. This happens more often during the "perform action" step, when you have to click a button.
We also noticed that, if this happens in the "move ship" phase, the ship position Is different between the two players.

**Comment by Sandrem** [comment]
Some fixes are done.
