### ISSUE TITLE
Nashtah Pup issues

### ISSUE THREAD

**Issue by Cannibal-Soup** [Sandrem/FlyCasual#2877]
In one game, the AI had its Hound's Tooth blow up, but the Pup didn't have a maneuver dialed in, so the game locked up. 

In another game, it just gave me the wall of red text. 
![Screenshot_20200818-132508_Fly Casual](https://user-images.githubusercontent.com/68479348/90562368-e7c36200-e156-11ea-9544-0b84be7a953c.jpg)
![Screenshot_20200818-130352_Fly Casual](https://user-images.githubusercontent.com/68479348/90562371-e85bf880-e156-11ea-93bc-9cb025e5e4bf.jpg)

**Comment by Sandrem** [comment]
Issue with Deathfire, fixed
