### ISSUE TITLE
Bomb Loadout Upgrade Adds Multiple Bombs

### ISSUE THREAD

**Issue by tcorrigan** [Sandrem/FlyCasual#288]
In version 0.2.0 adding a the Bomb Loadout upgrade adds multiple bombs to Y-Wings.

![image](https://user-images.githubusercontent.com/391144/31852319-46ec75fe-b63b-11e7-8533-d7670310cf6b.png)

![image](https://user-images.githubusercontent.com/391144/31852325-6b3fb4a2-b63b-11e7-9218-79fd95c1f69e.png)

**Comment by Sandrem** [comment]
Fixed
