### ISSUE TITLE
Ship glitched off the board

### ISSUE THREAD

**Issue by dvomoreira** [Sandrem/FlyCasual#2880]
In a match, as a ship should fit the ruler after a q-turn, it flew off the board, never ending the maneuver. 

![Screenshot_20200821-034526_Fly Casual](https://user-images.githubusercontent.com/60307366/90861192-bcf92980-e361-11ea-81c2-0a6fbe5868d1.jpg)

**Comment by Sandrem** [comment]
Some fixes are done.
