### ISSUE TITLE
Falcon AI disregards borders

### ISSUE THREAD

**Issue by VexingVision** [Sandrem/FlyCasual#2882]
This happened in a few matches already - the Falcon tends to disregard borders in its flying and planning. There was nothing forced, no tractors or ion tokens.

In retrospect, I think I've seen a Hound's Tooth doing this as well - it might be related to large ship AI.

![image](https://user-images.githubusercontent.com/28895989/90965260-e089b480-e4c6-11ea-9b51-4d1fcea1544c.png)

**Comment by Sandrem** [comment]
Some fixes are done
