### ISSUE TITLE
Quinn Jast (M3-A Interceptor) Pilot Ability

### ISSUE THREAD

**Issue by SlayerOfTheStars** [Sandrem/FlyCasual#2887]
Wording on pilot ability should allow recovery of charge on any upgrade type. However, I noticed that after taking damage with Stealth Device, at start of engagement I was not given option to recover charge on Stealth Device.  Tested this with other non-weapon upgrades such as Afterburners and Crack Shot, and experienced same issue.  Other potentially problematic cards not tested are Elusive, and Lone Wolf (would only come up if triggered while defending from Snap Shot / Foresight before engagement phase).

**Comment by rune-b** [comment]
You are correct. It currently only allows recovery of a charge on a weapon. I will fix this.
