### ISSUE TITLE
Ship setup breaks if clicking too fast during asteroid setup

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2897]
Steps to reproduce:
1. When placing asteroids click the "Random" button several times as fast as you can
2. After asteroids placement is complete you are not able to place any ships on the board.

Also, after this has happened, Restart game doesn't work. It goes to the loading screen and then hangs

**Comment by Sandrem** [comment]
Seems that we need to hide the button after first click.

**Comment by Sandrem** [comment]
Fixed
