### ISSUE TITLE
Treacherous causing crash.

### ISSUE THREAD

**Issue by baronklutz** [Sandrem/FlyCasual#2899]
When an attack is measured through a ship onto one with treacherous the game crashes. Will post later with screenshot.

**Comment by baronklutz** [comment]
![image](https://user-images.githubusercontent.com/52109920/91864032-aeffae80-ec67-11ea-885c-5799d8a999d0.png)

**Comment by Immelman51** [comment]
It happened for me to.

**Comment by rune-b** [comment]
This has already been reported, so I'm closing this one.

Duplicate of #2832
