### ISSUE TITLE
"Player" and "Faction" drop-down fields cannot be clicked on name

### ISSUE THREAD

**Issue by FourTeeTwo** [Sandrem/FlyCasual#290]
Once you select a new game, if you click on the "Player" or "Faction" drop-down menus, clicking in the blank area opens the menu, but if you click on the text (like "Human" or "Rebels"), the menu does not register the click, preventing the menu from opening.

**Comment by Sandrem** [comment]
Thank you for information.
Drop-down menus are weird in Unity. (Also I didn't find way to set a tooltips for lines in expanded list of pilots/upgrades).
I plan to make new squadron builder in 0.4.0 (UI will be similar to http://armada.ryankingston.com/ )
So not critical bugs in current squadron builder are ignored.
