### ISSUE TITLE
Garven Dreis ability causing freeze

### ISSUE THREAD

**Issue by Mikeguinn** [Sandrem/FlyCasual#2900]
when using Garvens ability the game freezes the moment the prompt comes up to choose a friendly ship. I have tried this several times and against several different ai opponent lists to confirm and it always crashes at the same moment. running on windows 8.1 Note it is the arc 170 version of garven and it crashed on a defensive use of his ability. similar to the other post regarding this issue
list;
Lando Calrissian
-trick shot
-perceptive copilot
-jyn erso
-shield upgrade
-stealth device
-millenium falcon
-han solo
Garven Dreis
-debris gambit
-proton torpedoes
-perceptive copilot
-r3 astromech
-shield upgrade
-veteran tail gunner

200pt

**Comment by Mikeguinn** [comment]
Also, after running it again I have noticed that the freeze only happens if, after you spend your focus on defense, you hit the ''ok'' button on the dice results screen rather than immediately selecting a friendly ship to give the focus to. it looks like the bug can be worked around by simply avoiding the ''ok'' button until AFTER gifting the focus. but if you do mistakenly click ok, the screen becomes frozen, the cursor is still responsive to cursor position but you can no longer get out of the dice results screen and the ''ok'' option no longer responds

**Comment by rune-b** [comment]
I get the same. 

![image](https://user-images.githubusercontent.com/11047987/94296029-79966a00-ff62-11ea-8fc1-a152f415fba1.png)

**Comment by Sandrem** [comment]
Fixed
