### ISSUE TITLE
Snapshot on FO TIE/BA points incorrect

### ISSUE THREAD

**Issue by Zackwell2nd** [Sandrem/FlyCasual#2903]
Snapshot on FO TIE/BA points incorrect

Is showing as 8 rather than 7 (small ship base)

![2020-09-04 18_42_37-Fly Casual](https://user-images.githubusercontent.com/70754620/92231535-72d68300-eedf-11ea-8526-b016ca63b7d0.png)
![2020-09-04 18_43_02-Fly Casual](https://user-images.githubusercontent.com/70754620/92231553-7a962780-eedf-11ea-818e-5e21ca9b12a8.png)
![2020-09-04 18_43_28-Fly Casual](https://user-images.githubusercontent.com/70754620/92231566-808c0880-eedf-11ea-81b5-c5c47e828085.png)
![2020-09-04 18_44_01-YASB 2 0 - FO #02 - Opera](https://user-images.githubusercontent.com/70754620/92231571-87b31680-eedf-11ea-9189-56dd711a7136.png)

**Comment by rune-b** [comment]
Hi
Thanks for the detailed bug report. The point cost of Snap Shot has already been fixed in the next version of Fly Casual
