### ISSUE TITLE
Error while selecting movement

### ISSUE THREAD

**Issue by Jariksu** [Sandrem/FlyCasual#2914]
![Image1](https://user-images.githubusercontent.com/71085401/92747506-eddee400-f38c-11ea-8359-825f69f43bde.jpg)

Hello

Buttons in moving dials are not accurate. 4 forward is 3 forward. 1 straight is left bank.
This error pops up time to time.

**Comment by Jariksu** [comment]
Actually looks like my controller was messing with this.

**Comment by Sandrem** [comment]
Fixed in "1.6.1 Hotfix 1"
