### ISSUE TITLE
Import XWS Issues

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#2916]
1. Importing Landos Millennium Falcon "title":["landosmillenniumfalcon"] fails in Fly Casual. I have to remove one 'n' in Millennium to get it to import.

2. Importing any squad with Advanced Proton Torpedos {"torpedo":["advprotontorpedoes"] fails. I have to remove the line and add it. Exporting from Fly Casual lists it as "torpedo":["adv.protontorpedoes"].

**Comment by Sandrem** [comment]
Fixed
