### ISSUE TITLE
Add option to rotate ship after initial placement

### ISSUE THREAD

**Issue by FourTeeTwo** [Sandrem/FlyCasual#292]
It would be nice to be able to rotate a ship base after it has been placed on the board.

**Comment by Sandrem** [comment]
In current version you can rotate ship by using Q/E or CTRL+Q/E while it is not placed.
I had plans to allow change of position after ship is placed - but this requires additional step with "Next" button and in most cases it only slows down setup phase.

So this is not planned. Maybe I will add this option later, when all features with higher priority will be ready.
