### ISSUE TITLE
[Ignore, working as designed] Tie heavy doesn't snapshot from rear arc when turret is facing backwards

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#2929]
It does snapshot from front arc. The description states that it must perform special attacks from the turret position.

**Comment by baronklutz** [comment]
It performs cannon attacks from the turret arc, snap shot is always in the front arc (apart from one firespray pilot who can shoot it backwards).

**Comment by grandpajive** [comment]
Your are correct, I re read the card. Would've been nice though ;)
