### ISSUE TITLE
Ahsoka Gunner effect not triggering

### ISSUE THREAD

**Issue by Niels011** [Sandrem/FlyCasual#2931]
Hi,

Ahsoka gunner was not triggering in a game I played when the carrier bumped - The card effect should work even when bumped as it triggers after 'executing a maneuver' and doesn't require 'fully executing' a maneuver.

thanks for all you r fantastic work on this,
Niels

**Comment by rune-b** [comment]
Hi
I just tried this, and Ahsoka triggered as expected when I bumped another ship (see screenshot below). Are you sure you had a force charge when this happened? That is the only condition that is checked before displaying Ahsoka's trigger.

![image](https://user-images.githubusercontent.com/11047987/93818841-28813000-fc5b-11ea-9b1b-c9eb65cef368.png)

**Comment by Niels011** [comment]
Thanks! sorry I will try again - my Ahsoka was on a LAAT, will try that again

**Comment by rune-b** [comment]
No need to apologize 😊

If it happens again, it would be helpful if you could take a screenshot of the situation

**Comment by baronklutz** [comment]
did you bump into your own ship? As Ahsoka's effect is at range 1 - 3 (meaning that it cant be used on ships its touching).

**Comment by Niels011** [comment]
Ah yes - that is likely the reason! Thanks! No bug then,
best wishes,
Niels
