### ISSUE TITLE
3 missing avatars

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#2932]
<img width="50" alt="leia100x100" src="https://user-images.githubusercontent.com/60325223/93812195-1fb23f00-fc06-11ea-84f8-35da9d4dda5c.png">
<img width="50" alt="rey100x100" src="https://user-images.githubusercontent.com/60325223/93812198-204ad580-fc06-11ea-8dcb-40403ad9b904.png">
<img width="50" alt="lando100x100" src="https://user-images.githubusercontent.com/60325223/93812199-204ad580-fc06-11ea-9fe4-70e8c5394284.png">

Use them if you want.

**Comment by Sandrem** [comment]
Thank you, I will use them when I will rework UI of avatar selection
