### ISSUE TITLE
Version 1.5 cannot be executed anymore

### ISSUE THREAD

**Issue by elsapo70** [Sandrem/FlyCasual#2935]
The file FlyCasual.x86_64 is not recognized as an executable anymore.

**Comment by rune-b** [comment]
Hi
Did it work in version 1.4?
Which OS are you using?
Can you post a screenshot of the error message you're getting?

**Comment by Sandrem** [comment]
This is not a problem of code of Fly Casual.
Please, contact someone who has experience in Linux OS.
