### ISSUE TITLE
Plo was removing a Jam token from a Shadow Squadron Vet. Crash

### ISSUE THREAD

**Issue by Salohza42** [Sandrem/FlyCasual#2938]
![image](https://user-images.githubusercontent.com/71788459/94056626-d79a4480-fdde-11ea-9488-066261524603.png)
Plo was removing a Jam token from a Shadow Squadron Vet.
![LastReplay replay](https://user-images.githubusercontent.com/71788459/94057041-5becc780-fddf-11ea-8c86-e527f4385323.gif)

**Comment by Salohza42** [comment]
Evening all. This is my first bug report. Hope I did it right. Regards Nick

**Comment by rune-b** [comment]
Hi and thanks for reporting 😊

Both screenshot and replay, and a clear description of what happened, makes it much easier for us to look into 👍
