### ISSUE TITLE
Online mode lockup - Hera out of range

### ISSUE THREAD

**Issue by whoever003** [Sandrem/FlyCasual#2942]
during 1st round, engagement phase. Hera in the Ghost was first to attack. Selected the ship closest to me, but it was out of range 3. I got the red message telling me it was out of range 3 and gave me the option to skip. I pressed skip, but it did not move onto the next ship for its turn. the range ruler was still visible and I can still click on other enemy ships, but nothing else.

**Comment by Sandrem** [comment]
Some fixes are done.
