### ISSUE TITLE
Official ruling on gaining multiple tokens

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2947]
This is not how it is implemented in the game: 

Q: When a ship is instructed to gain two or more tokens from a single effect (such as Admiral Sloane), does this resolve as a single instance of gaining two or more tokens or as two or more separate instances of gaining one token?

A: It resolves as a single instance of gaining two or more tokens. Thus, if a ship is instructed to gain two or more tokens from a single effect like Admiral Sloane, this only triggers abilities that occur “after you gain a token” once.

https://community.fantasyflightgames.com/topic/277390-x-wing-official-rulings/page/2/

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
