### ISSUE TITLE
Tel Trevura is bugged after respawning

### ISSUE THREAD

**Issue by Azaghal1** [Sandrem/FlyCasual#2956]
After respawning with 1 hull, Tel Trevura can not perform actions, shoot, be shot at. Furthermore, he can still be target locked by enemy ships. Lastly, if he is destroyed by an Asteroid, he stays alive with 0 hull.

**Comment by grandpajive** [comment]
Same. I could coordinate to him to focus and stress rotate turret, though.

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3185
