### ISSUE TITLE
Veteran Turret Gunner Allowing Multiple Shots in same Arc from AI

### ISSUE THREAD

**Issue by smauel76** [Sandrem/FlyCasual#2958]
Just played a round against 4 Y-Wings with Ion Turrets and Veteran Turret Gunner.  The AI was able to fire two attacks from the same arc every round.  My understanding is that Veteran Turret Gunner only allows you to fire into a different arc you hadn't attacked that round, not into the same arc at the same ship you just attacked.   Seems like a bug that needs to get fixed unless the rules for that card got updated.

**Comment by baronklutz** [comment]
If the turret is facing forward then you can attack using the primary weapon and then the turret as vtg says a different turret arc.

**Comment by heferito** [comment]
That is the correct attack. One attack is from the primary attack arc and the second attack is from the turret attack arc.

**Comment by Sandrem** [comment]
Not a bug, closed.
