### ISSUE TITLE
Failing a boost action (be it a white, red boost or Daredevil turn boost) soft locks the game

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#2967]
![unknown (2)](https://user-images.githubusercontent.com/47178393/97779584-46598300-1b7f-11eb-9eee-9d7d3027bfd4.png)

Ric Olié tried a red Daredevil boost. Prevents from activating your remaining ships. Can confirm this happens when failing regular white or red boosts as well.

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3035
