### ISSUE TITLE
Nobs of the Rigged Cargo Chute token taken in count for obstacle overlap

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#2969]
![unknown (4)](https://user-images.githubusercontent.com/47178393/97779722-30988d80-1b80-11eb-9a6a-bd47be0d126a.png)

iirc, nobs shouldn't count

**Comment by baronklutz** [comment]
The whole template counts, even the nubs. It's the same when measuring range.

**Comment by Akrythael** [comment]
Right, just read the rules the again and only the ships guides don't count for range measurement or arc check.
