### ISSUE TITLE
interface

### ISSUE THREAD

**Issue by BonberJupar** [Sandrem/FlyCasual#2971]
Hello,

first of all, a great thank you for your work. I'm waiting for network functionnalities with impatience!

This post not to declare an issue, but to summit an interface improvement idea.
It would be great to have either an auto-hide functionnality either an option "arrow up"/"arrow down" on the two ships' list on left and right hand side.
When hiden, just firepower, agility, hull and shield info, when shown, the actual setup.
It would afford a larger vision of fight field...

Regards

Bonber

![image](https://user-images.githubusercontent.com/66266608/97782405-a6f1bb80-1b91-11eb-8be8-17bed11971eb.png)

**Comment by BonberJupar** [comment]
submit not summit

**Comment by Sandrem** [comment]
Moved to list of planned features: https://github.com/Sandrem/FlyCasual/wiki/Planned-Features
