### ISSUE TITLE
(1.6) Missing wave 7 content

### ISSUE THREAD

**Issue by AstroAnthro** [Sandrem/FlyCasual#2974]
Hi FC team,

Just a quick FYI, but the upgrade Suppressive Gunner is missing from the recent update. I know it's a card that's flown under the radar in the wider community a bit, but some of us do indeed use it heavily! Not sure if it's missing because of the technicalities in programming it, so sorry if this is a known missing piece! 

Cheers for all your awesome work!

**Comment by AstroAnthro** [comment]
Oh, I see another commenter pointed this out already in September! Should've searched first.... May just keep the thread open in case anyway as a patient and low pressure feature request :)

**Comment by Sandrem** [comment]
The game is in development. If you want to see release of content faster - please, consider Patreon support, in this case I could spent more time to add content.
