### ISSUE TITLE
2 out of 4 AI K-Wings flying off the map

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2975]
I played a game against the random K-Wing squad, and two of them flew off. They should prefer bumping enemy ships rather than putting themselves in positions they can't get out of

![Screenshot_20201101-100812](https://user-images.githubusercontent.com/11047987/97798919-d0125a80-1c2a-11eb-903b-ea214f8e5f11.png)

**Comment by rune-b** [comment]
The replay for this game doesn't work, see #2976

**Comment by Sandrem** [comment]
Some fixes are done
