### ISSUE TITLE
Replay crashes

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#2976]
Replaying a game against 4 AI K-Wings crashes on the AI's turn. The original game was completed without errors. 

![Screenshot_20201101-115246](https://user-images.githubusercontent.com/11047987/97800857-e9220800-1c38-11eb-893b-b6931da3337d.png)

**Comment by rune-b** [comment]
[LastReplay.replay (1).zip](https://github.com/Sandrem/FlyCasual/files/5470589/LastReplay.replay.1.zip)

**Comment by Sandrem** [comment]
I remember that replays chash after a ship hit an asteroid (something is wrong with dice roll)

**Comment by rune-b** [comment]
Yes, the die roll window was showing for a little while before the error appeared. It was empty

**Comment by Sandrem** [comment]
Fixed
