### ISSUE TITLE
Right click on a face down dial from an AI ship crashes the game during planning phase 100% repro

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#2977]
Title

![image](https://user-images.githubusercontent.com/47178393/97912213-cda82180-1d4c-11eb-8bd0-aa462f8c6e89.png)

**Comment by rune-b** [comment]
Confirmed, but only when "Show Maneuver Prediction" option is enabled

**Comment by rune-b** [comment]
Related to #2978

**Comment by Sandrem** [comment]
Fixed
