### ISSUE TITLE
Left click on a face down dial from AI ship with Preview maneuver option blocker

### ISSUE THREAD

**Issue by Akrythael** [Sandrem/FlyCasual#2978]
It shows the maneuver preview but prevents from choosing any ship to set the dial during planning phase. (I tried to select one of my ships for the screenshot)

![image](https://user-images.githubusercontent.com/47178393/97912452-21b30600-1d4d-11eb-87bb-beaa2104985a.png)

**Comment by Sandrem** [comment]
Fixed
