### ISSUE TITLE
Error when selecting a maneuver

### ISSUE THREAD

**Issue by Rexxios** [Sandrem/FlyCasual#2980]
[Player.log](https://github.com/Sandrem/FlyCasual/files/5503170/Player.log)

So far I have only tried selecting a maneuver for Empire ships, but when I select a maneuver during the planning phase, is gives an error (in Player.log), and soft locks the game.

**Comment by Sandrem** [comment]
I changed this part of code in "Version 1.6.1 Hotfix 1". If error will be still present - please, inform me.
