### ISSUE TITLE
Error and Freeze after defending with Poe

### ISSUE THREAD

**Issue by Korran12** [Sandrem/FlyCasual#2981]
![Captura de pantalla 2020-11-07 a la(s) 3 19 23 p  m](https://user-images.githubusercontent.com/67489605/98451617-19701780-210d-11eb-8520-592d21dc9834.png)
This happened after I defended with Poe, thought I should report it

**Comment by Sandrem** [comment]
Fixed in Version 1.6.1 Hotfix 1
