### ISSUE TITLE
Synced Laser Cannons - Error and Freeze

### ISSUE THREAD

**Issue by SlayerOfTheStars** [Sandrem/FlyCasual#2982]
![Capture](https://user-images.githubusercontent.com/40924222/98451883-f63e6b80-20fe-11eb-9195-e83cb6c6c4ef.png)
[LastReplay.replay.txt](https://github.com/Sandrem/FlyCasual/files/5505469/LastReplay.replay.txt)
Performed attack with Geonosian Prototype equipped with Synced Laser Cannons.  Selected enemy ship at range 3.  Geonosian Prototype was calculating, and enemy ship had 2 friendly locks.  Game errored and froze immediately after selecting target before rolling dice.

**Comment by Sandrem** [comment]
Fixed in Version 1.6.1 Hotfix 1
