### ISSUE TITLE
Error when using cannons

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#2984]
I see two threads with Synced Laser Cannons and autoblasters - I have had the same issue with ion cannon and tractor beams.

![image](https://user-images.githubusercontent.com/36247564/98454582-c69c6b80-21b1-11eb-9798-c9ee52f1c682.png)

**Comment by Sandrem** [comment]
Fixed in Version 1.6.1 Hotfix 1
