### ISSUE TITLE
Garvin Dreis Focus Generation

### ISSUE THREAD

**Issue by Translerbc** [Sandrem/FlyCasual#2986]
Focus Assignment for Garvin Dreis (x-wing or Arc-170) doesn't work, nothing can be selected and game has to be restarted.
![Screen Shot 2020-11-08 at 9 02 45 AM](https://user-images.githubusercontent.com/74147377/98470334-29860680-21a2-11eb-9485-072de56a16b3.png)

**Comment by rune-b** [comment]
Duplicate of #2900
