### ISSUE TITLE
Gredo gunner ability activates even without charge

### ISSUE THREAD

**Issue by sdmoebes** [Sandrem/FlyCasual#2987]
The Gredo gunner ability activates every attack/defense regardless of whether or not the charge has been spent.

**Comment by rune-b** [comment]
This does not happen for me. See screenshot below where A-wing attacks Scurrg with Greedo with spent charge, and the ability is not available

What other upgrades did you have on the ship?
Can you post a screenshot of the game when the charge has been spent and the ability is still available?

![image](https://user-images.githubusercontent.com/11047987/98730065-1474c780-239c-11eb-9684-cc54b43c40b3.png)

**Comment by Sandrem** [comment]
Still cannot find a way to reproduce, no similar reports.
Closed.

**Comment by Sandrem** [comment]
FYI: Opponent doesn't spend Charge when uses this ability. So, few enemy ships can use it in one turn, if Charge is not spent by you.
