### ISSUE TITLE
Palob/Moldy Crow loses focus tokens

### ISSUE THREAD

**Issue by sdmoebes** [Sandrem/FlyCasual#2988]
If Palob Godalhi (with Moldy Crow ship title) ever takes an evade action (using the debris gambit upgrade or by using its pilot ability to take one from an opponent), the game will force you to lose a focus token during the end phase (regardless of the Moldy Crow ability to keep up to two).  This issue continues until Palob completely expends all tokens.  The issue has been present in the last 5 version releases of Fly Casual.

**Comment by rune-b** [comment]
Hi
I tried this, but could not reproduce it. Using Palob with Moldy Crow and Debris Gambit, I was always able to keep focus tokens at the end of the turn, even if I had an evade token.

Are you playing 1st or 2nd edition btw?

**Comment by sdmoebes** [comment]
Hi,

I am using 2nd edition.  I have attached pictures of the sequence of events.  I made an attack while holding 3 focus and an evade.  Then...
1. I used a focus to change an eye to a hit.
2. My opponent evaded the hit and took the critical.
3. During the end phase Palob lost both the unused evade and one of the 2 unused focus tokens
4. In the next end phase, Palob lost his one remaining unused focus (no picture of this one)

Please see the attached pictures.  I have a Mac, so maybe that somehow contributes to the problem?

Steve

**Comment by rune-b** [comment]
OK, I will try to reproduce with those steps later

But I don't see any attached pictures. If you replied by email, I think that is the problem. It seems email attachments doesn't work, and that you have to add them via the web pages.

**Comment by grandpajive** [comment]
I've had that happen as well with Kyle Katarn. No matter what, Dace Bonearm loses his focuses at end phase, making him even more useless;)

**Comment by sdmoebes** [comment]
Here it is again with the pictures.  Prior to attacking, Palob had 3 focus tokens (2 stored + 1 from focus action) and 1 evade token that had been stolen from an opponent using Palob's ability.

1. I used a focus to change an eye to a hit.
![image](https://user-images.githubusercontent.com/64425204/98879217-fddd7780-2452-11eb-86cc-518681d4bea3.jpg)
2. My opponent evaded the hit and took the critical.
![image0](https://user-images.githubusercontent.com/64425204/98879232-059d1c00-2453-11eb-88ef-6f78ee63132f.jpeg)
3. During the end phase Palob lost both the unused evade and one of the 2 unused focus tokens
![image1](https://user-images.githubusercontent.com/64425204/98879237-0930a300-2453-11eb-8b7b-0ac1f6563151.jpeg)
4. In the next end phase, Palob lost his one remaining unused focus (no picture of this one)

**Comment by sdmoebes** [comment]
@rune-b Just wondering if this issue may get addressed.  I added pictures showing the issue and another users also stated that they have had the same issue.  Thanks.

**Comment by Sandrem** [comment]
I found a way to reproduce this bug - it happens when Moldy Crow has evade token. It is counted as "token to keep", but later is discarded because this is really not a focus token.

Fixed.
