### ISSUE TITLE
Game is soft locking

### ISSUE THREAD

**Issue by Immelman51** [Sandrem/FlyCasual#2991]
Hi,
I had the game soft locked a few times since the last update. After I shoot with a ship there's no skip button, and the camera doesn't move anymore. The command console is not popping. By pressing ESC, I do have the menu to get restart or get back to main menu, but when I click on either of them, the game gets stucked on a loading screen. Here's a screnshot of one of those soft locks. (it seems it's happening each time after I shot whith Bariss, but I'm not sure).

![Softlock](https://user-images.githubusercontent.com/31988939/98706949-c0f48080-237f-11eb-8700-467ab3dcef9f.png)

**Comment by Immelman51** [comment]
I had another one after Barriss attack with seventh fleet gunner. (maybe I used too many seventh fleet gunner during my attack, I'll test that).

**Comment by grandpajive** [comment]
Is there a way to make the console pop up to skip the trigger/action?

**Comment by Akrythael** [comment]
Had the issue as well.

After attacking with Ric Olié at range 1, using Fire Convergence from LAAT to reroll dice (skipped the use of Seventh Fleet Gunner), game is soft locked after opponent ship rolled the dice for defense (ship should be destroyed but is still there).

![image](https://user-images.githubusercontent.com/47178393/99186612-d982e300-2751-11eb-936a-055b142ffd3e.png)

**Comment by Sandrem** [comment]
Fixed
