### ISSUE TITLE
Unreleased ship attack error

### ISSUE THREAD

**Issue by bcvalor** [Sandrem/FlyCasual#2993]
I am testing the unreleased ships and I got this error after making an attack from Jango Fett to a T-70.  I wonder if this is an error with Douku crew? i chose not to use his ability, and after the opponent rolled dice, I received this error: 

![image](https://user-images.githubusercontent.com/60284913/98730244-dbfbcc00-2350-11eb-9d62-9c44bf5fe777.png)
![FlyCasualError](https://user-images.githubusercontent.com/60284913/98730338-fdf54e80-2350-11eb-9a04-abe323e68790.JPG)

**Comment by rune-b** [comment]
Thanks for reporting. This seems to be a bug with Weapons Systems Officer

**Comment by Sandrem** [comment]
Do you use "v1.6.1 Hotfix 1"?
There was one similar bug in "v1.6.1" that I fixed in "v1.6.1 Hotfix 1".

**Comment by bcvalor** [comment]
Yes the brand new one.  
I also tried another match with some minor changes and got an error after I tried to "Jango" my opponents die.  I am thinking the bugs lie with him.

**Comment by bcvalor** [comment]
Actually I did keep the Weapons System officer, so that may be correct.

**Comment by rune-b** [comment]
@Sandrem The bug is in Weapons Systems Officer, line 42. RequiresTokens can be null. See pull request

**Comment by bcvalor** [comment]
@rune-b Thanks I didnt notice that at first but I concur. Ill do one more test list with Jango and without WSO but I assume the results will allign.

**Comment by Sandrem** [comment]
Fixed
