### ISSUE TITLE
Underslung Blaster Cannon receives range 1 bonus despite Ordnance property

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#2998]
Attacks with Underslung Blaster Cannon are always with 3 attack dice with range 1 bonus.  Because of the Ordnance property, the attack should only ever be with 2 attack dice.

<img width="1440" alt="Screen Shot 2020-11-11 at 11 06 07 AM" src="https://user-images.githubusercontent.com/17327811/98837285-c8179f00-2410-11eb-8a7f-d45861aa9632.png">

**Comment by Sandrem** [comment]
Fixed
