### ISSUE TITLE
Using Composure causes game to softlock

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#2999]
After failing an action, a message pops up allowing you to perform a focus action. If AI has ships to move by init, it will. player owned ships will not work.

Tested Focus and Focus Linked Action cases: 

Focus-linked action:
I had initiative. 
Palob trying to boost into an asteroid (got Focus->Rotate Turret red), received a message stating no more actions were allowed (which is correct). AI Esege Tuketu Katarn moved, then I could not select any of my ships. Clicking on anything does nothing, and Esege stays highlighted, and doesn't perform an action. Game soft-locks, I can hit escape to restart, but then I have to force close the program. Maybe the logic thinks that Esege has no actions left for some reason due to init. 

![Composure_after_Palob_Failure](https://user-images.githubusercontent.com/6842889/98845440-52f99900-2413-11eb-8053-40b6ebd55c76.jpg)

Focus action:
Constable Zuvio attempted to use Spacetug Tractor Array as an action, and it failed. Got a pop-up asking to gain a focus. I said yes, and my other init 4 ship, Dalan Oberos was highlighted to perform his maneuver, but a message popped up stating 'This ship has already executed their maneuver'. I clicked on Zuvio for fun, same message came up. I clicked on my init 2 and 3 ships, and a message popped up stating 'This ship cannot be selected, the ship must be owned by Player1 and have a pilot skill of 4'. 

I'm wondering if the ShipID needs to be tacked on when these triggers/action sequences occur. I think because the two init 4 
ships are owned by the same player, the activation phase needs ship IDs attached for movement sequences in this circumstance. 

![composure_after_zuvio_tractor_failure](https://user-images.githubusercontent.com/6842889/98844449-efbb3700-2411-11eb-8bfd-35015b9a4b58.jpg)

Thank you for your hard work and great game. Never really tried using composure on a ship, but realized its probably a good idea on Zuvio if the tractor beam fails ;)

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3035
