### ISSUE TITLE
CONCUSSION BOMBS

### ISSUE THREAD

**Issue by d7knndy** [Sandrem/FlyCasual#3000]
Hello,
Concussion bombs aren't available after the 1.6.1 hotfix.

Thank you,
David

**Comment by Sandrem** [comment]
The game is in development. Not all content is available yet - development requires time.
If you want to see all content faster - consider support on Patreon.

**Comment by d7knndy** [comment]
Thanks for your response back. I do understand it takes time, just thought
that it would be part of the hot fix update. Maybe after covid restrictions
get lifted i will be able to support you through patreon but until then the
money is tight.

I do appreciate everything you are doing with Fly Casual, keep up the fine
work.

David

**Comment by Sandrem** [comment]
No, hotfix is needed only to fix critical bugs (v1.6.1 had crash every time when special weapon was used)
We track list of missing content and in updates we release cards that are finished at that moment. So there is no need to inform us about missing cards, they will be added, but just later.

**Comment by d7knndy** [comment]
No problem.

Thank you.
