### ISSUE TITLE
Strain gained with Finn's ability on defense is removed before taking effect

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#3001]
Strain gained with Finn's "add focus result" ability on defense is removed immediately after that same defense resolves.  This behavior isn't in accordance with the updated strain rules reference, which states:
"After a strained ship applies the effect to roll 1 fewer defense die this way, it removes 1 strain token."

<img width="1440" alt="Screen Shot 2020-11-11 at 1 59 05 PM" src="https://user-images.githubusercontent.com/17327811/98854688-e1c4e080-2428-11eb-9228-49b3acd6eeaa.png">
<img width="1435" alt="Screen Shot 2020-11-11 at 1 59 36 PM" src="https://user-images.githubusercontent.com/17327811/98854697-e4bfd100-2428-11eb-8b69-b334389bcd1a.png">

**Comment by Sandrem** [comment]
Fixed
