### ISSUE TITLE
AI ships overlapping each other

### ISSUE THREAD

**Issue by bames53** [Sandrem/FlyCasual#3002]
Version 1.6.1 Hotfix 1

This ship ran into its allies but still completed its maneuver and performed a focus action.

https://imgur.com/WahRFPQ

**Comment by Akrythael** [comment]
Can confirm this is still happening in 1.6.1 Hotfix 1 version.
![image](https://user-images.githubusercontent.com/47178393/99186586-958fde00-2751-11eb-945e-d588109bb4e9.png)

**Comment by Akrythael** [comment]
Still happening in 1.7, and can happen with the player's ships as well. (3 straight with the LAAT)

![image](https://user-images.githubusercontent.com/47178393/100667471-d8110780-335a-11eb-98f0-f73537e3ada5.png)

**Comment by Akrythael** [comment]
another 3 straight

![image](https://user-images.githubusercontent.com/47178393/100668396-24a91280-335c-11eb-9538-d719582d8daf.png)

and a bank 3

![image](https://user-images.githubusercontent.com/47178393/100668468-3f7b8700-335c-11eb-829b-21ac9a0f0ed7.png)

Same game than with the LAAT. Gonna send replay on discord.

**Comment by Sandrem** [comment]
Some fixes are done. If this bug will be present in 1.8+, please inform me.

**Comment by Akrythael** [comment]
> Some fixes are done. If this bug will be present in 1.8+, please inform me.

Sure! Will do ;)
