### ISSUE TITLE
Cluster Missiles and Targeting Synchronizer causing crashes 

### ISSUE THREAD

**Issue by KingmanHighborn** [Sandrem/FlyCasual#3004]
![image](https://user-images.githubusercontent.com/25874825/99207991-54b5ba80-278d-11eb-9060-b56de082fcf2.png)

![image](https://user-images.githubusercontent.com/25874825/99208120-a0686400-278d-11eb-8a27-65b9f49c1995.png)

Not sure how to get the replay file on here, but I take two target locks with Ello, and go to take a cluster missile shot with Zizi and it crashes right after the second missile is fired at the next eligible target. Not sure how else I can help. But thought you should know.

**Comment by Sandrem** [comment]
Fixed
