### ISSUE TITLE
Possible sollution for Garven Dreis?

### ISSUE THREAD

**Issue by Neotrail** [Sandrem/FlyCasual#3008]
Issue with Garven. 
When the dice box are up and you, as Garven use focus and have no eligible friendy in you fire arc.
Then you can't click skip button as the dice box's right column (where you click focus, target lock, evade and so on...) overlaps the button.

It doesn't matter if you fly his X-Wing or his ARC170, it's the same issue.

Possible sollution:
Move Skip button or reduce the size of the dice box's right column so that the skipbutton can be clicked.

![Garven](https://user-images.githubusercontent.com/74384552/99735097-471d6f00-2ac4-11eb-8497-6dfa2a7109d2.jpg)

**Comment by Sandrem** [comment]
Fixed
