### ISSUE TITLE
QI'RA Ability breaks game / Error code

### ISSUE THREAD

**Issue by DarkAngel1975** [Sandrem/FlyCasual#3013]
Using QI'RA on Scum Falcon.
Tried to use TL action upon rock and then the error message appears and the game basically stops working.
I have attached the screen shot of the error
Game version is 16.1 HotFix
Regards,

Tony
[FlyCasual QI'RA Error.docx](https://github.com/Sandrem/FlyCasual/files/5605139/FlyCasual.QI.RA.Error.docx)

**Comment by grandpajive** [comment]
I've found that issue also, had false transponder codes on paloob, qira on 4-lom. 4lom tried to TL an asteroid, and I received a crash, game proceeded but I could not TL an obstacle until false transponder codes was used by paloob.

**Comment by Sandrem** [comment]
Yes, jamming of asteroid causes this error.

Fixed.
