### ISSUE TITLE
Bug on Android with x-wing V1

### ISSUE THREAD

**Issue by pemeunier** [Sandrem/FlyCasual#3016]
![Screenshot_2020-11-29-20-38-35-203_com sandrem flycasual](https://user-images.githubusercontent.com/12517351/100551797-54d0b280-3283-11eb-96d1-2b473543525b.jpg)

Got this bug when choosing rebel ships and using V1 on Android.

Anyway, many thanks for this beautiful work :)

**Comment by Sandrem** [comment]
Fixed
