### ISSUE TITLE
Tie BA with out Talent

### ISSUE THREAD

**Issue by TroyBoy01** [Sandrem/FlyCasual#3018]
Hi

When I load the Tie ba it doesn't have an option to add a talent.
![Screenshot_20201130-115555](https://user-images.githubusercontent.com/66024386/100641248-36ab9680-3305-11eb-83bc-da5fca6bd639.png)
![Screenshot_20201130-120151](https://user-images.githubusercontent.com/66024386/100641291-432fef00-3305-11eb-9625-8d491d45dd0f.png)

**Comment by Sandrem** [comment]
Fixed
