### ISSUE TITLE
Yoda Missing from Eta

### ISSUE THREAD

**Issue by 8bitrebel** [Sandrem/FlyCasual#3020]
I was wondering how come Yoda was missing from the Eta-2 pilot list? Or is there another way to play as him? He should be after Jedi general at initiative 3?

![image](https://user-images.githubusercontent.com/75278272/100663377-2eaf1f00-3324-11eb-9988-fc99e2c9741b.png)

**Comment by Sandrem** [comment]
The game is in development.
If you want to see release of new content sooner - consider Patreon support: https://www.patreon.com/Sandrem
