### ISSUE TITLE
libretro port? :)

### ISSUE THREAD

**Issue by DartPower** [Sandrem/FlyCasual#3021]
Hi there, i have a idea, you want to port to libretro?
This is will be cool, really :)

Check this also please :)
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by Sandrem** [comment]
Hi. I am busy enough with current state of development, so I don't plan to spend time on additional tasks.
But if there is someone who wants to port it to libretro- I am glad to help.
