### ISSUE TITLE
Shaak Ti's ability on Handmaiden causes bug

### ISSUE THREAD

**Issue by pdelgado248** [Sandrem/FlyCasual#3023]
![image](https://user-images.githubusercontent.com/22975769/100755382-684b5d00-33ec-11eb-88e4-fdca5858ff5a.png)

A naboo handmaiden has both a focus and an evade token. At the end of the turn, Shaak Ti's ability asks wether to keep the focus, otherwise the evade will be kept. I choose not to keep the focus since I want to keep the evade and then this error occurs.

**Comment by Sandrem** [comment]
The same bug is reported on FFG forum too: https://community.fantasyflightgames.com/topic/267459-fly-casual-x-wing-simulator/page/84/?tab=comments#comment-4022481

**Comment by Sandrem** [comment]
Fixed
