### ISSUE TITLE
Eta-2 actis Obi-wan ability doesn't work when bumping other ship

### ISSUE THREAD

**Issue by pdelgado248** [Sandrem/FlyCasual#3024]

**Comment by FTFup** [comment]
came here to report the same thing. here's a replay which shows it. 

additionally, i think Obi caused a soft lock at the start of his shot. but maybe it was at the end of Oddball's shot which locked it for me. 

[Obi-ETA ability and crash.zip](https://github.com/Sandrem/FlyCasual/files/5625222/Obi-ETA.ability.and.crash.zip)

**Comment by Sandrem** [comment]
Fixed
