### ISSUE TITLE
Squads can't load AdvProtonTorpedoes in builder

### ISSUE THREAD

**Issue by SovietToaster14** [Sandrem/FlyCasual#3028]
Tried to load squads that included Advanced Proton Torpedoes.
Tested with both the _Unabomber_ and _Hatchetman_ squads from the Popular section.
Both result in: 

![BugUnabomber](https://user-images.githubusercontent.com/53511197/100839731-ccdbea00-34c8-11eb-8087-5e32d44af202.jpg)

![BugHatchetman](https://user-images.githubusercontent.com/53511197/100839723-ca799000-34c8-11eb-9b57-23a49a28f3ea.jpg)

**Comment by Sandrem** [comment]
Thank you, fixed.
