### ISSUE TITLE
Weapons System Officer points wrong / Rose Tico

### ISSUE THREAD

**Issue by LeoTheWookiee** [Sandrem/FlyCasual#3029]
Weapons System Officer should cost 7pts (not 1)
Also, please please fix Rose Tico crew so that she can remove an eyeball and not auto exclude a blank (for Heroic this matters)

Once again, thanks a lot for this amazing app!

**Comment by Sandrem** [comment]
Thank you, cost of Weapons Systems Officer is fixed.
Rose Tico's change of "remove a die" is a duplicate of existing issue https://github.com/Sandrem/FlyCasual/issues/2953
