### ISSUE TITLE
Crash on generation of random squad

### ISSUE THREAD

**Issue by samnilsson** [Sandrem/FlyCasual#3030]
Please find attached. I got this twice in a row after creating a scum team and choosing the random squad option. If might be my scum team, when I select the Scumbompers team I get the error. When I recreated the team in the second screenshot, it worked fine.
![image](https://user-images.githubusercontent.com/19578836/100961827-5e0a8b00-34e0-11eb-8c8d-060eb350b64d.png)
![image](https://user-images.githubusercontent.com/19578836/100962037-c48fa900-34e0-11eb-84b7-c5071109a7be.png)

So the difference between them is the issue. I might have done something wrong when I placed a bomb before setting the Firespray to have the _Adraste_ title, which adds the bomb slot.

**Comment by Sandrem** [comment]
Yes, bug was caused by issues with order of installation of upgrades.
I previously fixed this for one-slot upgrades, but bug was still present for two-slot upgrades, like Electro-Proton bombs.

Fixed.
