### ISSUE TITLE
Thermal detonators not yet implemented

### ISSUE THREAD

**Issue by whittaker007** [Sandrem/FlyCasual#3031]
Thermal Detonators are a bomb type released with Jango Fett's Slave I Expansion Pack and Nimbus-class V-Wing Expansion Pack:

https://xwing-miniatures-second-edition.fandom.com/wiki/Thermal_Detonators

**Comment by Sandrem** [comment]
The game is in development.
If you want to see release of new content sooner - consider Patreon support: https://www.patreon.com/Sandrem
