### ISSUE TITLE
Missing new Republic astromech R2-D2

### ISSUE THREAD

**Issue by TS7415** [Sandrem/FlyCasual#3038]
![R2-D2_republic_astromech](https://user-images.githubusercontent.com/69057211/101360824-2dbe4600-386c-11eb-9a95-623f658a317d.png)

This card is not available to republic ships

**Comment by Sandrem** [comment]
The game is in development.
If you want to see release of new content sooner - consider Patreon support: https://www.patreon.com/Sandrem
