### ISSUE TITLE
Deplete doesn't reduce attack dice used for secondary weapons

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#3053]
Pictured: Obi-wan with deplete token fires autoblasters at range-1 bullseye target for 4 attack dice.

If I am not imagining or forgetting things
2 (autoblaster base damage) + 1 (target in bullseye) + 1 (at range 1) - 1 (deplete token) = 3

I am making an inference that other secondary weapons may be affected, but I haven't tested that to be sure.

<img width="1440" alt="Screen Shot 2020-12-15 at 1 00 33 AM" src="https://user-images.githubusercontent.com/17327811/102177370-66b07900-3e71-11eb-97da-4131b837d62a.png">

**Comment by Sandrem** [comment]
Thank you, fixed
