### ISSUE TITLE
Can't change options

### ISSUE THREAD

**Issue by govem** [Sandrem/FlyCasual#3055]
First i was trying to change resolution (initially was 1900x1200), then it got stuck on 1344x1008. Also can't uncheck the fullscreen option.
As it got stuck, i tried changing other options, like some checkboxs on the Extra section. They got stuck as well, can't uncheck them.

I'm on MacOS Big Sur, FlyCasual 1.7

any workaround? some file or args i could use?

![ss1](https://user-images.githubusercontent.com/1394760/102408230-126ddc00-3fcc-11eb-9579-25e25eda2ce7.png)
![ss2](https://user-images.githubusercontent.com/1394760/102408235-139f0900-3fcc-11eb-9672-c4c0320b8ab3.png)

**Comment by Sandrem** [comment]
Fixed. If problem is still present - inform me.
