### ISSUE TITLE
Some Ghost / Sheathipede mechanics not working....

### ISSUE THREAD

**Issue by MarkusGWW** [Sandrem/FlyCasual#3058]
Hi there,
Thought I'd let you know that when I have Kallus in the Ghost with Zeb and Intimidation.... I haven't been able to fire even at Range 0 (though Zeb should allow me to do that).
In a similar vein, with a docked AP5 on the Ghost... tried to coordinate a stressed Jake Farrel... and it wouldn't let me (though AP5s ability should). 
Love the app though.

**Comment by grandpajive** [comment]
Zeb doesn't seem to work on any rebel ships. Tried with arc-170, vcx.

**Comment by Sandrem** [comment]
Closed as duplicate, will be fixed as parts of another issues
