### ISSUE TITLE
Eta Anakin does not remove locks despite paying force

### ISSUE THREAD

**Issue by Takko550** [Sandrem/FlyCasual#3059]
ETA Anakin is able to remove all red tokens with ability, except for locks.

Stress, strain, deplete were successfully removed, but not locks. Force paid but lock remained.
![Screenshot_20201219-231445_Fly Casual](https://user-images.githubusercontent.com/55527581/102692758-7274b480-4250-11eb-9251-ddc2cbc2c9e6.jpg)
![Screenshot_20201219-231502_Fly Casual](https://user-images.githubusercontent.com/55527581/102692760-74d70e80-4250-11eb-9f38-071bfed86016.jpg)

**Comment by Sandrem** [comment]
Fixed
