### ISSUE TITLE
MacOS Catalina Issue: FC won't start due to "damaged" program

### ISSUE THREAD

**Issue by RockoTDF** [Sandrem/FlyCasual#3060]
I followed the standard chmod +x * instructions, yet after attempting to run FlyCasual 1.7.1 MacOS reports that the file is damaged and won't let me start the application.  I've attempted with three different downloaded versions of the file, the second to check for corruption, and the third to see if I was doing something wrong with the chmod process.

**Comment by jonathangl** [comment]
on mac os big sur too
