### ISSUE TITLE
BTL-5B K-Wing ignored Ion token

### ISSUE THREAD

**Issue by Hat2000** [Sandrem/FlyCasual#3068]
Single player.  The #4 K-Wing made a right 1 90 and avoided an asteroid.  Since it had an Ion Token, it should have flew into it.
![BTL-5B-K-Wing-Ignores-Ion-Token](https://user-images.githubusercontent.com/76487139/102907620-90e6d580-4433-11eb-98e6-4a49fb14fa55.png)

**Comment by Sandrem** [comment]
Medium ship is ionized if it has 2 or more ion tokens.
Not a bug, closed.

**Comment by Hat2000** [comment]
Doh!  Sorry about that.
