### ISSUE TITLE
BTL-5B K-Wing flew thru asteroid.

### ISSUE THREAD

**Issue by Hat2000** [Sandrem/FlyCasual#3069]
Single Player.  The K-Wing flew thru an asteroid without having to roll for damage.  Also on this same game, the K-Wing shot thru an asteroid and my Tie/sa bomber didn't get the +1 defense dice.
![BTL-5B-K-Wing-Ignores-Asteroid](https://user-images.githubusercontent.com/76487139/102907957-ff2b9800-4433-11eb-801e-c604e70ad9e9.png)

**Comment by Sandrem** [comment]
Fixed
