### ISSUE TITLE
Unable to proceed post critical card ai reveal

### ISSUE THREAD

**Issue by bw-e33** [Sandrem/FlyCasual#3070]
Hello
Version 1,7,1 android
Locked on my DRK Probe droid accidentally with Infiltrator Maul.
Fired on V19 Torrent AI, rolled 1 focus, 1 hit, 1 crit
force modded the focus to a hit.
Crit card on Torrent revealed
No prompt to continue, stuck on crit card reveal screen.  Can access stats, and change controls, 
Please advise? 
It was locking on Vulture Calculates earlier as well, but don't remember all steps leading to it - same situation though where defense dice were revealed and couldn't move on.

(First post so unsure if I followed protocols correctly. Apologies.)

![Screenshot_20201222-133838](https://user-images.githubusercontent.com/76491715/102922193-9e17ba80-445b-11eb-9d68-a54db144ff27.png)

**Comment by Sandrem** [comment]
Fixed
