### ISSUE TITLE
Background image not working

### ISSUE THREAD

**Issue by Arc104** [Sandrem/FlyCasual#3071]
I recently installed 1.7.1 ( I had 1.6.1 installed previously) and the background is locked with an image of a greyish looking half-circle with blue sky. When I try to change the image in Options, nothing happens and it keeps the default grey messy background.
![grey](https://user-images.githubusercontent.com/66768214/102932610-9a416380-446e-11eb-85a5-3a571652557e.png)
![SlaveI](https://user-images.githubusercontent.com/66768214/102932624-a4636200-446e-11eb-8b86-33e1dd4afdcb.png)

**Comment by grandpajive** [comment]
Same here. If I go to the built in squad builder, and choose a different skin, the model of that ship is displayed on the background instead. 

Windows 10, upgraded from 1.7.

**Comment by Arc104** [comment]
Yep, I am also having the same problem you described as well.

**Comment by Korran12** [comment]
Same issue on Android 10

**Comment by rune-b** [comment]
I also have this problem on my Android

**Comment by KingmanHighborn** [comment]
Same issue here as well.

**Comment by otuv** [comment]
Also on Ubuntu 16.04

**Comment by Sandrem** [comment]
Fixed
