### ISSUE TITLE
Game Locking Up

### ISSUE THREAD

**Issue by chrisrivers13** [Sandrem/FlyCasual#3073]
The game goes unresponsive after selecting the AI player.  It hangs on the loading screen for the game itself.  No error messages.  This is the Windows version.

**Comment by SteveRansom** [comment]
Same issue, both Windows and Android. Almost guaranteed to happen on AI vs AI with full squads. Often happens after defense dice are rolled, but at other times too. No error codes thrown.
![image](https://user-images.githubusercontent.com/60325223/104251563-d9872280-5424-11eb-93ef-1c470ab58ff6.png)

**Comment by SteveRansom** [comment]
1.8.1 has resolved this for me.

**Comment by Sandrem** [comment]
Was fixed
