### ISSUE TITLE
Asajj Tractor token problem

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#3078]
I couldn't get a screen shot of this, but when I use Asajj Ventriss to give a tractor token to a Fang Fighter (Zealous Recruit) after my attack hits, when I barrel roll the Fang Fighter it rotates 90 degrees, enabling it to turn nd attack me at range one to finish me off! LOL.

But seriously, this happened twice.

My List: 
Asajj Ventris (Shadowcaster) with: 
000
Title

2 Skull Squdron Fang Fighters with Fearless
1 Cartel Spacer with HLC

AI squad:
Popular List: Om Nom Nom

Please fix this if you can! :) 

Thanks!

**Comment by charlieneo** [comment]
This is correct usage of the rule. When your ship gets move by tractor, you can rotate 90 degrees and gain a stress.

**Comment by Sandrem** [comment]
Not a bug, closed.

**Comment by TNG-Wing** [comment]
Oh wow, I didn't realize that. 

Thanks!
