### ISSUE TITLE
Ships literally overlapping inaread of bumping/touching

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#3080]
Hard to get a screen shot of this as one ship literally will end up sitting under the base of another. But this has happened a few times and the ship that was supposed to bump ended up physically under the base of another larger or medium ship.

Anyone see this? I will try to get a screen shot if I can, next time this happens.

**Comment by Sandrem** [comment]
Seems that is fixed in recent version. If it will be present again in v1.8+ - please, inform me.
