### ISSUE TITLE
Zeb Orrelios (crew) doesn't work

### ISSUE THREAD

**Issue by carlosaredo** [Sandrem/FlyCasual#3082]
![image](https://user-images.githubusercontent.com/20170800/103371987-2425a800-4ad1-11eb-95a6-b24f984ee631.jpg)

**Comment by leash246** [comment]
I can add to this, though I did not take screenshots.
I was using Norra (ARC-170) with Zeb (among other things). I could never attack at range 0 from my front arc, but at one point I had collisions on both front and back arcs, and the back arc DID let me attack. If that helps anything.

**Comment by rune-b** [comment]
related to #3109

**Comment by rune-b** [comment]
@Sandrem I think this has worked before. I see that the modified minRange that is returned from UpdateWeaponRange event is not used because the shotInfo.IsShotAvailable property is false. See Shipweapon.cs line 55

**Comment by grandpajive** [comment]
It definitely worked before. I think around 1.7 it stopped working

**Comment by Sandrem** [comment]
Will be fixed as part of this issue: https://github.com/Sandrem/FlyCasual/issues/3109
