### ISSUE TITLE
Need manual AI vs AI targeting function

### ISSUE THREAD

**Issue by Mancupcake** [Sandrem/FlyCasual#3084]
For list diagnostic purposes it would be immensely helpful if during AI vs AI games, there could be a manual action and targeting mode. Sometimes the game chooses incredibly ridiculous targets or spends tokens for erroneous things that drastically alter the game state. If we could let the AI fly, but the users shoot, that would be very useful.

**Comment by Sandrem** [comment]
Not in plans
