### ISSUE TITLE
Cannot spend target lock with cluster missiles

### ISSUE THREAD

**Issue by Mancupcake** [Sandrem/FlyCasual#3085]
Flying the Alpha Star wing with Arsenal Loadout, I should be able to still attack with munitions even if I'm disarmed. It allows the first attack, but won't allow me to spend my TL to reroll my dice, or allow me to make the second attack.
![fly](https://user-images.githubusercontent.com/77145685/104112379-fdbaf600-52a2-11eb-88fc-3bffc13507cf.jpg)

**Comment by baronklutz** [comment]
You were disarmed, os-1 only allows you to attack with munitions against targets you have locked but you can't spend the lock. I suggest that you swap clusters for proton torps/ concussion missiles and passive sensors for fire control systems. This will allow you to make full use of your ship and upgrades.

**Comment by Mancupcake** [comment]
Woops. Turns out I'm an idiot haha. 

Then the problem goes the other way and it did allow me to spend my lock and attack with cluster while piloting Major Vynder.

**Comment by Sandrem** [comment]
Not a bug, closed. If you have another bugs - create separate issue with new screenshot
