### ISSUE TITLE
Error when loading Squad saved before update

### ISSUE THREAD

**Issue by bentleybuilds** [Sandrem/FlyCasual#3090]
Running an updated version on Mac Catalina. Went to load this squad:
![Screen Shot 2021-01-13 at 10 13 54 AM](https://user-images.githubusercontent.com/62079521/104485784-29cac580-5588-11eb-8b56-a9ea28b03356.png)
and received this error:
![Screen Shot 2021-01-13 at 10 04 34 AM](https://user-images.githubusercontent.com/62079521/104485798-2e8f7980-5588-11eb-9e24-2b4d1adf874e.png)

My guess is it has to do with the fix to https://github.com/Sandrem/FlyCasual/issues/2916#issue-699544903

**Comment by Sandrem** [comment]
Few upgrades had wrong XWS-format names in older versions - this was fixed recently.
Saved squad lists with these upgrades are not valid anymore and should be re-created.
I the next update you will see message "Cannot install upgrade <name>" instead of this error.
