### ISSUE TITLE
Run FlyCasual 1.7.1 on MacOs Big Sur 11.1 - Not Running

### ISSUE THREAD

**Issue by ChriMaix** [Sandrem/FlyCasual#3092]
I wanted to upgrade to the new version 1.7.1 and downloaded the respective ZIP from github, unpacked it and copied the new app to the application folder (which overwrote the old version/app). Now, I wanted to start the new version but it tells me that I have not the necessary access rights and should change that. I tried this (since I am the only user of my Mac and the administrator), but I still get this message and cannot open FlyCasual.
Does anyone of you has an advice how I can get the app running on my Mac?

Looking forward to your advice.
Best regards
ChriMaix

**Comment by Sandrem** [comment]
Please, ask another Mac users - how do they run third-party apps. I don't use Mac, so I cannot help you with a piece of advise.
