### ISSUE TITLE
macOS file broken

### ISSUE THREAD

**Issue by Rambouze** [Sandrem/FlyCasual#3094]
error when I try to launch macOS file - file broken ....

**Comment by Rambouze** [comment]
(Mac mini M1) old version still working

**Comment by amoyag** [comment]
Same here.
MacBook Pro M1 FlyCasual 1.7.1 works perfect.

**Comment by JohnnyTSpark** [comment]
Same error here with 1.8, after running the Terminal command. This also happened with 1.7 (fixed by the hot fix).
![Screenshot 2021-01-19 at 09 34 49](https://user-images.githubusercontent.com/50407085/105015655-ae5e8d80-5a39-11eb-9fe2-f549d02c279e.png)

**Comment by Rambouze** [comment]
if someone  find a solution.... I'll take it ! ;)

**Comment by Rambouze** [comment]
for now we can play with parallel Desktop beta and Windows Arm beta but.... it's heavy solution...

**Comment by Sandrem** [comment]
Seems this is a problem with new versions of Unity3D.
I uploaded another build of MacOS (it is built in older version of Unity3D)
