### ISSUE TITLE
Boba Fett (Slave I) Ability

### ISSUE THREAD

**Issue by ploderup** [Sandrem/FlyCasual#3097]
Boba Fett's (Slave I) ability doesn't seem to work. It should allow Boba Fett to reroll one attack or defense die for each enemy ship at range one. However, when I was flying the Slave I against a droid swarm, I never had the opportunity to reroll.

**Comment by Sandrem** [comment]
![изображение](https://user-images.githubusercontent.com/6347443/105272638-732b9e00-5ba2-11eb-9788-b76a1506355c.png)

**Comment by Sandrem** [comment]
Just checked - ability works as expected.
Please, next time provide screenshots. Maybe you was at range 2 or used wrong pilot etc...
