### ISSUE TITLE
NullReferenceException

### ISSUE THREAD

**Issue by tmo7452** [Sandrem/FlyCasual#3098]
Landed a crit with Steele, selected "Fuel Leak", got this error.
![image](https://user-images.githubusercontent.com/9245957/105069650-3fd8fa00-5a50-11eb-9233-4aff8cbbe490.png)
Then another error after clicking "OK"
![image](https://user-images.githubusercontent.com/9245957/105069996-aeb65300-5a50-11eb-91c6-c24be56f66f4.png)
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/5837468/LastReplay.zip)
Haven't tried to reproduce or anything, the error just says to report it.

**Comment by Sandrem** [comment]
Steele doesn't work correctly in v1.8
Fixed, update with bugfixes will be released soon.
