### ISSUE TITLE
Zam with Dooku Crew

### ISSUE THREAD

**Issue by Wurms2** [Sandrem/FlyCasual#3099]
Had Zam with Dooku crew. Zam had You Should Thank Me condition chosen. Two xwings attacked her no problem (took lock on first one, not the second one). Then third one caused an error before it asked me about Dooku ability. Oh, that third Xwing was firing through another and Zam also had treachorous. So maybe combo of treachorous and Dooku caused it?
<img width="935" alt="Screen Shot 2021-01-19 at 9 29 07 AM" src="https://user-images.githubusercontent.com/65094280/105071187-1bbdee80-5a39-11eb-9243-7f11d2db452c.png">

**Comment by Sandrem** [comment]
Treachorous is fixed
