### ISSUE TITLE
Garven Dreis (x wing) attack doesn't allow resolution

### ISSUE THREAD

**Issue by Cerpintaxt9211** [Sandrem/FlyCasual#3100]
![image](https://user-images.githubusercontent.com/77691551/105074733-5f6f2300-5a4e-11eb-8471-8e9fedafdfc2.png)

The option to continue after defense dice are rolled is removed when Garven resolving Garven's attacks. I have recreated it, doesn't seem to matter if the ship tries to pass a focus or not.

**Comment by Cerpintaxt9211** [comment]
Not a problem in v 1.7.1 that I am running on an android device

**Comment by Sandrem** [comment]
Fixed
