### ISSUE TITLE
AI doen't know about restriction of Automated Target Priority

### ISSUE THREAD

**Issue by AlgernonFTW** [Sandrem/FlyCasual#3115]
Reporting 2 issues: 
1) Nimi Chireen card visual is broken - just a black text on a white card, and you can't look at Nimi's card as reference during a match.

2) Automated Target Priority: Game froze after AI attempted using ATP. Error message appeared at bottom of screen saying to choose a closer target, and then the game locked up.

**Comment by Sandrem** [comment]
Please, next time create separate issue for each bug.

**Comment by Sandrem** [comment]
1) Fixed

**Comment by Sandrem** [comment]
Fixed
