### ISSUE TITLE
failed action -> game over

### ISSUE THREAD

**Issue by CaptainCavemanDE** [Sandrem/FlyCasual#3116]
hello.

in "vs AI" mode, I can't reproduce this issue; however:

in "online mode" vs a buddy the game hangs after an action failed; example: I use an action to barrel-roll of the map. 
which is forbidden ofc.
action fails, and it doesn't jump to the next ship; instead it hangs. is this a known issue and being worked on, or sth new? 
you need a log that I can post?

I'm being pretty new to this - not to xwing and besides the error above really enjoy this. 
great work so far gents :)

**Comment by VexingVision** [comment]
Oooh might be linked to failing a mandatory decloak action with the ilicit cloaking device, which behaves the same way - when you fail the decloaknby selecting a direction that would bump you, the next ship doesn't get selected either.

This is in AI solo mode, not Network.

**Comment by CaptainCavemanDE** [comment]
the thing above seems different, as it resolves AS SHOULD in "VS AI" mode;
it also isn't there when playing in hotseat mode (aka - on the same pc) 

-the problem is there when playing networked.

still having great fun with this, despite the errors here and there ;)

**Comment by Sandrem** [comment]
Failed actions in online mode are fixed in v 1.8.2.1.
Failed decloak using illicit upgrade - will be fixed later.

**Comment by CaptainCavemanDE** [comment]
> Failed actions in online mode are fixed in v 1.8.2.1.
> Failed decloak using illicit upgrade - will be fixed later.

Yay! thx mate :)
