### ISSUE TITLE
Crashed after Combat Round in which Zam pilot was destroyed

### ISSUE THREAD

**Issue by bentleybuilds** [Sandrem/FlyCasual#3117]
Not sure if that is what triggered the crash, however the errors seem to mention bonus attack, so maybe it Zam's condition, maybe it was Jango's Veteran Tail Gunner
![Screen Shot 2021-01-28 at 3 43 10 PM](https://user-images.githubusercontent.com/22629601/106208218-466a1e80-6180-11eb-8828-002a5e0d7b5e.png)
[LastReplay.replay.zip](https://github.com/Sandrem/FlyCasual/files/5890408/LastReplay.replay.zip)

**Comment by Sandrem** [comment]
Fixed
