### ISSUE TITLE
Cards not being imported

### ISSUE THREAD

**Issue by JamesAshburner** [Sandrem/FlyCasual#3122]
Previously used cards are fine but new ones are not being imported. I cleared the data on an Android device to test and very few cards were available, the vast majority are white with the card name in text on them.

I believe from news on TTS that FFG have removed the cards from their website so I'm not sure if this is something you can work around but raising this as an issue for awareness.

**Comment by rune-b** [comment]
Yes, it is a known problem that FFG removed a lot of cards from their web site. It will be fixed in the next update
