### ISSUE TITLE
Thread Chasers do damage

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#3125]
Playing a match with Thread Chasers on enemy Trade Federation Drone, shot into Padme and dealt damage rather than giving locks.

**Comment by Sandrem** [comment]
Maybe you used primary weapons instead of this upgrade?

I cannot reproduce damage dealing with Thread Chasers
![изображение](https://user-images.githubusercontent.com/6347443/107842905-6a0fa480-6dcf-11eb-8f9e-0ce83af38a5b.png)

**Comment by YellowJacketPym** [comment]
It was fixed in the last patch

**Comment by JBFancourt** [comment]
I also had this happen... also permitted firing with no focus token/lock/calc

**Comment by Sandrem** [comment]
I found a way to reproduce.

**Comment by Sandrem** [comment]
Fixed
