### ISSUE TITLE
Rebel Scout promoted to initiative 7 somehow

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#3126]
Not sure when it happened during an AI vs AI match, can't see any reason why it would have happened either.
![image](https://user-images.githubusercontent.com/60325223/106795523-09ce7500-660f-11eb-8eef-2fff93849998.png)

**Comment by baronklutz** [comment]
It's the ability of the named hwk pilot

**Comment by SteveRansom** [comment]
Blush.
