### ISSUE TITLE
Card Images not showing

### ISSUE THREAD

**Issue by Faygul90** [Sandrem/FlyCasual#3127]
Hey apologies if this a really silly question but i have downloaded a few different versions and cant seem to get this working not sure if its just me but there seems to be a lot of images i cant get to show in the game. Not sure if its just me or what the fix is?

love the work by the way!

![image](https://user-images.githubusercontent.com/78535088/106874529-a0cf2600-6710-11eb-8ab5-8be42e6435af.png)

**Comment by Sandrem** [comment]
Fixed
