### ISSUE TITLE
Latest build - Kanan in HWK crashed on deployment

### ISSUE THREAD

**Issue by AntipodeanOrk** [Sandrem/FlyCasual#3128]
![image](https://user-images.githubusercontent.com/36247564/106948791-e246ec00-6777-11eb-8b6e-d958d05edb1d.png)

**Comment by Sandrem** [comment]
Something is wrong with your avatar. Try to change it in settings.

**Comment by AntipodeanOrk** [comment]
Interesting. I have no option to change the avatar details in the "options"
menu.

Andrew

**Comment by Sandrem** [comment]
Fixed, update will be released soon.
