### ISSUE TITLE
List with Zam froze when offering bonus attack

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#3129]
Something seems wrong with the way Zam works. She seems to accumulate too many charges every turn. Anyway, this happened during a game with 1.8.2: Thye game froze when it offered a bonus attack for Zam. 

![image](https://user-images.githubusercontent.com/26996014/106969321-77f26500-66ff-11eb-97e7-c87bd78722ed.png)

**Comment by TNG-Wing** [comment]
It happened again in a game (same list) against 4 Black Squadron Aces (T-70s). Offered at bonus attack to Zam, clicked yes, game fronze.

**Comment by TNG-Wing** [comment]
It happened again 
![image](https://user-images.githubusercontent.com/26996014/107443866-6d184580-6aee-11eb-9adc-8cad47bac68b.png)

**Comment by Sandrem** [comment]
Fixed
