### ISSUE TITLE
Bug report window when opening options

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#3132]
![image](https://user-images.githubusercontent.com/60325223/107085800-d5dd8600-67ad-11eb-9cb5-bca05bba6459.png)

**Comment by SteveRansom** [comment]
Second time 
![image](https://user-images.githubusercontent.com/60325223/107085885-f6a5db80-67ad-11eb-99b3-4a7486ba173e.png)

**Comment by Sandrem** [comment]
Try this workaround for Windows:
Open "regedit"
Navigate to "HKEY_CURRENT_USER\SOFTWARE\Sandrem\Fly Casual"
Delete entry "Avatar_RandomCharactersHere".

**Comment by Requiem** [comment]
I am getting this error on mac as well. Where is the avatar info stored on mac?

**Comment by Requiem** [comment]
> I am getting this error on mac as well. Where is the avatar info stored on mac?

An update for anyone on mac: I reinstalled 1.8.1 and changed my avatar (I picked the first on the list, a blank white square), and then reinstalled 1.8.2. Everything seems to working now, though I haven't tried an online match yet.

**Comment by Sandrem** [comment]
Fixed, update will be released soon.
