### ISSUE TITLE
crashed on buzzdroid destruction of enemy ship in same round that friendly ship was destroyed

### ISSUE THREAD

**Issue by bentleybuilds** [Sandrem/FlyCasual#3134]
[LastReplay.replay 2.zip](https://github.com/Sandrem/FlyCasual/files/5935338/LastReplay.replay.2.zip)

![image](https://user-images.githubusercontent.com/22629601/107089152-6078b200-67bb-11eb-80e1-fa0a0c2dbcbd.png)
 
errored after buzzdroid destroyed an enemy ship, then moved to next phase. I will try to reproduce.

**Comment by Sandrem** [comment]
Some fixes are done...
