### ISSUE TITLE
Palp, Coordinate

### ISSUE THREAD

**Issue by aderius** [Sandrem/FlyCasual#3135]
1. Palpatine's ability is inconsistent. Sometimes it triggers but does not change a dice result. 
2. Coordinate mostly works, but occasionally does not include eligible ships at range 2

**Comment by Sandrem** [comment]
Cannot reproduce.
I don't have enough information in which situations this happens. For example, maybe ship is outside Range 2.
Please, provide screenshots / replays.

Also, please, create separate issue for each bug next time.
