### ISSUE TITLE
Not being able to choose not to drop a bomb

### ISSUE THREAD

**Issue by chrisrivers13** [Sandrem/FlyCasual#3138]
During the game, the option to not drop a bomb with a ship that has bombs left does not exist.  To move on, I have to drop a bomb whether I want to or not.  This works fine at the beginning of the game, but at some point during the game it stops.

Squad I was using:

![image](https://user-images.githubusercontent.com/34896291/107134192-a9586580-68a4-11eb-9dfe-a3abebab96a7.png)

**Comment by baronklutz** [comment]
Concussion bombs have the unique effect where during the systems phase, if they have spent charges (i.e you dropped one last round) you have to drop/launch another one

**Comment by chrisrivers13** [comment]
> Concussion bombs have the unique effect where during the systems phase, if they have spent charges (i.e you dropped one last round) you have to drop/launch another one

I just had it do what I described even though I had all 3 charges of concussion bombs available.  I had not even dropped one yet.  I had dropped thermals, but no concussion.

**Comment by baronklutz** [comment]
Just tested this myself and get the same result.
Order of events are thus;
Turn 1: drop 2 thermal detonators and reload them.
Turn 2: forced to drop a bomb even if all charges are active.
My conclusion is that the game is getting confused between the two bombs somehow due to thermals having the ability to reload 2 charges at once.
I have also tested only dropping one thermal and that seems to work as intended.

**Comment by Sandrem** [comment]
Turn 1: dropped 2 thermal detonators and reload them.
Turn 2: I see "Skip" on Systems Phase, I see "None" option if ship with bombs is selected
![изображение](https://user-images.githubusercontent.com/6347443/107843143-4c433f00-6dd1-11eb-9bda-b4fe93e54add.png)

Please, check steps to reproduce, provide screenshots / replay

**Comment by baronklutz** [comment]
Found it. It seems if another ship is equiped with concussions when the game checks to see if a ship has to drop a bomb it checks all versions of concussion bombs rather that just the ship selected.
![Screenshot_20210213-122642](https://user-images.githubusercontent.com/52109920/107849967-c4702b80-6df6-11eb-91ba-b479cb07b1ab.png)
![Uploading Screenshot_20210213-122033.png…]()

**Comment by baronklutz** [comment]
![Screenshot_20210213-122024](https://user-images.githubusercontent.com/52109920/107849970-ccc86680-6df6-11eb-8555-ce533eb0cfe0.png)

**Comment by Sandrem** [comment]
Thank you! You helped me a lot!

**Comment by baronklutz** [comment]
Glad to be of assistance

**Comment by Sandrem** [comment]
Fixed
