### ISSUE TITLE
Crash on loading squad

### ISSUE THREAD

**Issue by dorkwis** [Sandrem/FlyCasual#3139]
![202102062314Crash](https://user-images.githubusercontent.com/49113563/107136512-eedf5780-68d1-11eb-969d-f851239564a0.JPG)

**Comment by Sandrem** [comment]
Try this workaround for Windows:
Open "regedit"
Navigate to "HKEY_CURRENT_USER\SOFTWARE\Sandrem\Fly Casual"
Delete entry "Avatar_RandomCharactersHere".

**Comment by Sandrem** [comment]
Fixed, update will be released soon.
