### ISSUE TITLE
Program Crash

### ISSUE THREAD

**Issue by ddpettin** [Sandrem/FlyCasual#3140]
<img width="1892" alt="2021-02-07_15-21-30" src="https://user-images.githubusercontent.com/78706561/107161185-488a6500-6958-11eb-8cdf-3c9519da8641.png">

**Comment by Sandrem** [comment]
Try this workaround for Windows:
Open "regedit"
Navigate to "HKEY_CURRENT_USER\SOFTWARE\Sandrem\Fly Casual"
Delete entry "Avatar_RandomCharactersHere".

**Comment by allysiu** [comment]
What about for Mac?

**Comment by Sandrem** [comment]
Fixed, update will be released soon.
