### ISSUE TITLE
Online Multiplayer - unable to place all obstacles.

### ISSUE THREAD

**Issue by JorgeArenas** [Sandrem/FlyCasual#3141]
I've tested a network game several time, and also through internet. Unable to place last 1-2 obstacles. Happens from client or host side. The clicking on the obstacle does not work. The first 4 usually work, but last two seems to get stuck or does not recognize a click on the obstacle so it can be placed.

**Comment by JorgeArenas** [comment]
Also this is with latest version 1.8.2

**Comment by Sandrem** [comment]
Fixed
