### ISSUE TITLE
Malarus + TL Interaction 

### ISSUE THREAD

**Issue by JBFancourt** [Sandrem/FlyCasual#3142]
Recently played Malarus (Xi Pilot), and noticed an error:

While Malarus is a MUST ability, it is still player controlled. Thus if I have a TL and am 0-2 to Malarus, I choose the order during the modify dice step.  

If I resolve my TL first, and there is no more remaining dice eligible to be rerolled by Malarus, then Malarus does not proc (just like if I didn’t roll any blanks). 

So if I have both I should still be given option: TL or Malarus. 

Thx!

**Comment by Sandrem** [comment]
Thank you, fixed.
