### ISSUE TITLE
 2 different SLAVE 1 Titles be on a list?

### ISSUE THREAD

**Issue by TNG-Wing** [Sandrem/FlyCasual#3143]
It's saying that there are too many with the same name but they are different cards

![image](https://user-images.githubusercontent.com/26996014/107449323-3810f080-6af8-11eb-8ce7-dce124527f58.png)

**Comment by baronklutz** [comment]
They may be different cards but the name is the same, meaning that you can only have one card of that name in a list. It's a bit like having vader in an x1 and as a crew, he can't be in two places at once.

**Comment by Sandrem** [comment]
Not a bug, closed.
