### ISSUE TITLE
Several System errors since latest update (1.8.2)

### ISSUE THREAD

**Issue by Full-Throtttle** [Sandrem/FlyCasual#3144]
![image](https://user-images.githubusercontent.com/67638243/107490992-7fdc5a00-6b82-11eb-98a1-6e61f911ae05.png)

Selected my own squad ok.  Chose "Random" AI squad - above error appeared.

The next error appeared when I selected a custom squad for the AI and tried to start the game.

![image](https://user-images.githubusercontent.com/67638243/107491533-33454e80-6b83-11eb-99ef-8ab10d07ac78.png)

When I tried to continue with the game, I was not able to select two of the obstacles and the game froze.

Strange one?   Is this something to do with the new save location for squads being corrupted perhaps?

**Comment by Sandrem** [comment]
Please, next time report errors as separate issues. It is hard to manage few bugs in one issue.

Second bug is fixed.

**Comment by Sandrem** [comment]
First bug is fixed
