### ISSUE TITLE
Bug with Zam Wessell bonus attack at the end of Engagement

### ISSUE THREAD

**Issue by thedoctorham** [Sandrem/FlyCasual#3145]
I was trying out Zam Wessell and wound up triggering the bonus attack at the end of the Engagement phase, which led to killing the ship I was shooting at.  However, I think because of the timing of when the attack happened, the ship stayed on the board until the start of the following Engagement phase, being assigned a dial and maneuvering, potentially getting in the way of my ship.  Once combat started on the new turn, the ship was immediately removed, however.

**Comment by Sandrem** [comment]
Fixed
