### ISSUE TITLE
Errors after last update - when loading new game, trying to restart games or return to main menu.

### ISSUE THREAD

**Issue by trindo2000** [Sandrem/FlyCasual#3146]
Hey. When I load a new game against AI, after squads are selected I get an error message but am able to play a game, although sometimes there are issues selecting obstacles to place. After the game if I select restart or return to menu then I get this message and it freezes. I've had a try at this workaround but don't have the "Avatar_RandomCharactersHere". entry. Thank you.

                                          Open "regedit"
                                          Navigate to "HKEY_CURRENT_USER\SOFTWARE\Sandrem\Fly Casual"
                                          Delete entry "Avatar_RandomCharactersHere".

![image](https://user-images.githubusercontent.com/78883115/107580579-af28b080-6bee-11eb-8b4e-c977a903c4c7.png)

**Comment by Sandrem** [comment]
Fixed, update will be released soon.
