### ISSUE TITLE
Berwer Kret pilot ability grants focus action instead of calculate action

### ISSUE THREAD

**Issue by subhedgehog** [Sandrem/FlyCasual#3150]
Triggering Berwer Kret's pilot ability grants a red focus action to the ships who are selected, instead of a red calculate action.

![berwer-1](https://user-images.githubusercontent.com/3179208/107816686-f798b900-6d29-11eb-8440-c01f0f99c97a.png)

![berwer-2](https://user-images.githubusercontent.com/3179208/107816700-fcf60380-6d29-11eb-9b62-089c588ff93b.png)

![berwer-3](https://user-images.githubusercontent.com/3179208/107816710-01222100-6d2a-11eb-81fc-60e7d43e46b4.png)

**Comment by Sandrem** [comment]
Thank you, fixed
