### ISSUE TITLE
"Attacker" and "defender" highlight colors reversed

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#3151]
The attacker should be highlighted in red because the attacker rolls red dice. The defender should be highlighted in green because the defender rolls green dice.
![image](https://user-images.githubusercontent.com/60325223/107825319-bb6c5500-6d37-11eb-94a3-f275d795ce07.png)

**Comment by Sandrem** [comment]
I will leave current colors, as "Green = friendly" and "Red = enemy".
