### ISSUE TITLE
Zam Wesell Game Freeze

### ISSUE THREAD

**Issue by abacouscous** [Sandrem/FlyCasual#3152]
Tonight, I had Jango Fett Fire Spray (Slave I), on a gas cloud, with Zam Wesell (2 charges active). A naked Skakoan Ace belbullab shot Jango, then I got a prompt to "remove a strain token or do "You'd Better Mean Business". I chose the latter, then it prompted asking me if I wanted to do a bonus attack against the attacker, but the dialog box would not move past "yes" or "no". The buttons did respond with the light-up, but I could not move from the choice.

**Comment by abacouscous** [comment]
![Wesell](https://user-images.githubusercontent.com/63937029/107844324-05852300-6d98-11eb-8f27-0aedd0371cb0.png)

**Comment by Sandrem** [comment]
Fixed

**Comment by TNG-Wing** [comment]
I just experienced this with v.1.8.3 Buttons all froze and game couldn't continue
![image](https://user-images.githubusercontent.com/26996014/108135834-ab24e480-706d-11eb-9bd5-1875cc944eac.png)
