### ISSUE TITLE
unable to start a game

### ISSUE THREAD

**Issue by kevinlpedersen** [Sandrem/FlyCasual#3153]
since I downloaded the 1.8.2 patch I'm getting many errors which I can just close, but this one in particular seems to hang the game when I try and start a new game. I'm running on a macbook pro.
![Screenshot 2021-02-13 at 11 57 03](https://user-images.githubusercontent.com/482149/107847336-59712580-6df3-11eb-9f55-3ea174782baf.png)

**Comment by Sandrem** [comment]
Fixed, new update will be released in few hours.
