### ISSUE TITLE
Error screen but game able to continue

### ISSUE THREAD

**Issue by stavrjim** [Sandrem/FlyCasual#3154]
4 auzitucks and 1 z95 with tracers
![image](https://user-images.githubusercontent.com/26796723/107851392-6eed4c00-6e01-11eb-930b-f9d60c2e1601.png)

**Comment by stavrjim** [comment]
Error popped up as soon as game started. PC version

**Comment by Sandrem** [comment]
Fixed, new version will be released soon.
