### ISSUE TITLE
Zam Wessell - Online bugs

### ISSUE THREAD

**Issue by aderius** [Sandrem/FlyCasual#3156]
Situation:
1. Player with Zam Wessell 
2. End of combat, 0 tokens on Zam
3. Still asks if you want to bonus attack
4. If you click yes, nothing happens and it also cannot be skipped

**Comment by aderius** [comment]
After my Tie fighter moved and took an action, it did not let the next player move his ship. No movements or actions could take place, and there was no skip option, so we had to quit the game. Is there a way to manually force a skip?

**Comment by Sandrem** [comment]
What version do you use? 1.8.2 or 1.8.2.1?

Also:
Please, create separate issue for each bug.
If the game is stopped without any error message, please, press "CTRL + ~" to open console and provide screenshot.

**Comment by TNG-Wing** [comment]
This happened in v. 1.8.3 just now:

![image](https://user-images.githubusercontent.com/26996014/108135949-e4f5eb00-706d-11eb-9382-bd0daccd7301.png)

**Comment by Sandrem** [comment]
Fixed
