### ISSUE TITLE
Able to use adaptive aerlions when stressed on Strikers

### ISSUE THREAD

**Issue by chrisrivers13** [Sandrem/FlyCasual#3157]
At least on Duchess, I still have the option to do the Aerlion maneuver even when stressed.  Not sure if it is a Striker wide issue.

**Comment by baronklutz** [comment]
That's her pilot ability, it lets you use them while stressed and not use them if you aren't.

**Comment by chrisrivers13** [comment]
Oops, sorry.  I must have been thinking about her/his 1.0 ability.
