### ISSUE TITLE
Latest Version not working

### ISSUE THREAD

**Issue by chrisrivers13** [Sandrem/FlyCasual#3158]
None of the options on the main menu will work  It also does not display the version #

**Comment by Sandrem** [comment]
What OS do you use?
Also, check antivirus/firewall/video drivers.

**Comment by chrisrivers13** [comment]
Windows 10.  I had no problem running the previous version and I have not changed anything since I installed that one.

**Comment by chrisrivers13** [comment]
Disabled firewall and anti-virus and no change.

**Comment by chrisrivers13** [comment]
Installed previous version 1.8.2 and it works fine
