### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by dansolo83** [Sandrem/FlyCasual#3161]
I am playing the game on android and it crashes everytime. Even with the new update. I even tried it on windows and the same thing happened. Is this just me or is it happening for others?.

**Comment by Sandrem** [comment]
Does it show window with red error text?

**Comment by dansolo83** [comment]
no it just shuts down all together

**Comment by Sandrem** [comment]
Seems that this is not problem of the code of Fly Casual, but of environment. Check antivirus, video drivers, free space... Maybe better hardware is needed... I can fix only errors where console with red text is shown.
