### ISSUE TITLE
Cluster Missles

### ISSUE THREAD

**Issue by MetzenJSR** [Sandrem/FlyCasual#3165]
Cluster Missiles aren't working properly. The card states:

> Attack (Action: Lock): Spend 1 Charge. After this attack, you may perform this attack as a bonus attack against a different target at range 0-1 of the defender, ignoring the Action: Lock requirement.

When I fire the cluster missiles, I'm only able to do the bonus attack if the second target is within range 1 of my ship (whereas it should be within range 0-1 of the ship I attacked first).

Here's a screenshot of what happened.  The A-Wing fired a cluster missile at the nearest (green) X-Wing only to be told there were no valid targets to attack with the bonus attack.

![Capture](https://user-images.githubusercontent.com/75662225/108002917-448cc180-6fae-11eb-9bfb-fea1ce6460f1.PNG)

Thanks for all the hard work on this! Overall, the game is fantastic!

**Comment by baronklutz** [comment]
It's possible that the second x-wing was at range 3 which would've prevented you from firing the missiles at it as they have a range of 1-2

**Comment by MetzenJSR** [comment]
You may be right.  This can probably be closed.
