### ISSUE TITLE
XWS Import - G4RG0R/VM

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3167]
Importing G4RG0R/VM (m3aintercepter) fails, the canonical name for XWS is {"id":"g4rgorvm","name":"g4rgorvm","points":28,"ship":"m3ainterceptor"}. modifying the import string from "g4rgorvm" to "g4rg0rvm" allows you to import.

Could you please change the import so poor ol' G4RG0R/VM can be imported?

Thank you!

**Comment by Sandrem** [comment]
Or course.
If you will see another issues with import - please, inform me.
I see a lot of automatic bug reports about failed import, but almost no opened issues about what exactly squads/cards cannot be imported.

**Comment by grandpajive** [comment]
Will do. Thanks again for the great program btw. Patreon donation coming
your way soon... Keep up the great work!

**Comment by Sandrem** [comment]
Fixed
