### ISSUE TITLE
Zeb crew not allowing attacks at r0

### ISSUE THREAD

**Issue by YellowJacketPym** [Sandrem/FlyCasual#3169]
![image](https://user-images.githubusercontent.com/61330588/108155644-438e8980-70ad-11eb-9dd8-f26f38fdcfa5.png)

**Comment by ClarenceR89** [comment]
Same issues as #3109 

Zeb Crew does not allow range 0 attacks

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3109
