### ISSUE TITLE
Zam Wesell (crew) locking up game

### ISSUE THREAD

**Issue by Steel-Hyena** [Sandrem/FlyCasual#3171]
I have Zam Wesell equipped on a YV-666, and when given the choice to use a free attack with "You'd Better Mean Business" I clicked "yes" and the game locked up on that decision.  I _think_ I didn't actually have enough energy on her to use it, maybe, but I'm not positive: it currently shows zero, but since I got shot at once already I feel there should be at least 1 charge.

**Comment by Grffiin** [comment]
I've been flying Zam on a Firespray a few times and I've gotten locked up under the same conditions. For me, I'm usually at 4 charges. On the first proc of You'd Better Mean Business, the firing goes off as intended. If he gets shot at again, I get the option of taking the shot (now at 2 charges). I click the fire button, and as reported above, the tokens get removed, but I get locked up at the "You'd Better Mean Business" prompt.

![image](https://user-images.githubusercontent.com/43751820/108584863-a6348f00-7312-11eb-8f72-8d5e5de41b2d.png)

**Comment by Sandrem** [comment]
Fixed
