### ISSUE TITLE
Han Solo Reroll + Lock

### ISSUE THREAD

**Issue by Karl4242** [Sandrem/FlyCasual#3172]
Had an issue with Han solo shooting at Jake Ferrel with a lock.  After using Han Solo's re-roll from the pilot ability, I am unable to spend a lock to re-roll additional dice

**Comment by Sandrem** [comment]
Cannot reproduce.

I roll attack dice...
Then, after this roll, choose to reroll all of them using Han's ability. Dice are rerolled. No more abilities in this window (maybe you think that reroll using Lock is here?). I click OK.
Then, modify dice step, I see "Lock" button and use it - I can choose and reroll dice. I click OK.
Defender rolls dice...
