### ISSUE TITLE
Got stuck in online multiplayer after damage dice roll on asteroid

### ISSUE THREAD

**Issue by JeffSkyrunner** [Sandrem/FlyCasual#3174]
How to reproduce:

Player 1: runs on an asteroid
Player 1: rolls die to check the damage
Player 2: hits "OK" button **before** Player 1
Player 1: hits "OK" button

At this point Player 2's screen with the die won't disappear and you cannot do anything else but quitting the game

**Comment by JeffSkyrunner** [comment]
Actually, the problem seems not to be related to whom hits "OK" first, but if Player 1 continues his actions **before** Player 2 has hit the "OK" button too

**Comment by JeffSkyrunner** [comment]
Ping 😄 

Any news on that? It's a game breaker...

**Comment by Sandrem** [comment]
Fixed
