### ISSUE TITLE
Sabine tractor over asteroid

### ISSUE THREAD

**Issue by MirageWolf** [Sandrem/FlyCasual#3175]
A concussion bomb detonated and I was gonna apply the tractor from sabine to a starviper and land it on an asteroid which trigger the bug. Also another thing I found was the simulator doesn't get the interaction between Esege Tuketu's ability and Garven's ability which allows Garven to spend a focus from Esege as his own triggering his ability and giving back the focus to Esege or any other ship whitin range.
![flycasual](https://user-images.githubusercontent.com/68522389/108611058-bac36680-73a8-11eb-92fa-5a8f4eb8d669.jpg)

**Comment by Sandrem** [comment]
Fixed
