### ISSUE TITLE
Cannot import Firespray with Slave 1-Separatist+Scum title

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3177]
XWS throws an error on import, doesn't know that "title":["slavei-swz82"] is the Slave 1 title from the Jango Fett firespray. Still lets you import the list, which is great, just have to manually select a title.

Example XWS:
{"description":"","faction":"separatistalliance","name":"Jango Zam hyp","pilots":[{"id":"zamwesell","name":"zamwesell","points":107,"ship":"firesprayclasspatrolcraft","upgrades":{"talent":["treacherous"],"crew":["countdooku"],"device":["thermaldetonators"],"illicit":["falsetranspondercodes"],"modification":["hullupgrade"],"title":["slavei-swz82"],"gunner":["bobafett-gunner"]}},{"id":"jangofett","name":"jangofett","points":91,"ship":"firesprayclasspatrolcraft","upgrades":{"talent":["treacherous"],"device":["thermaldetonators"],"illicit":["falsetranspondercodes"],"modification":["hullupgrade"]}}],"points":198,"vendor":{"yasb":{"builder":"Yet Another Squad Builder 2.0","builder_url":"https://raithos.github.io/","link":"https://raithos.github.io/?f=Separatist%20Alliance&d=v8ZhZ200Z428X228WWW218W339W369W164W370W334Y429X228WWWW339W369W164W&sn=Jango%20Zam%20hyp}},"version":"2.0.0","obstacles":["coreasteroid1","coreasteroid2","core2asteroid4"]}

**Comment by Sandrem** [comment]
Fixed
