### ISSUE TITLE
XWS Import Issue: Precision Ion Engines

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3182]
XWS Import fails for Precision Ion Engines (TIE/LN, Modified TIE/LN Fighter):
Example line:

{"id":"captainseevor","name":"captainseevor","points":34,"ship":"modifiedtielnfighter","upgrades":{"talent":["margsablclosure"],"modification":["precisionionengines"]}}

**Comment by Sandrem** [comment]
Fixed
