### ISSUE TITLE
Ahsoka Tano in A-wing (mod) only uses 1 force charge to trigger ability not 2

### ISSUE THREAD

**Issue by Korran12** [Sandrem/FlyCasual#3188]
![Captura de pantalla 2021-02-26 a la(s) 6 24 30 p  m](https://user-images.githubusercontent.com/67489605/109369136-ef2f9a80-7860-11eb-9f61-14492ea17128.png)
![Captura de pantalla 2021-02-26 a la(s) 6 25 30 p  m](https://user-images.githubusercontent.com/67489605/109369149-f3f44e80-7860-11eb-9481-7c9605521ad5.png)

**Comment by Sandrem** [comment]
Thank you, fixed
