### ISSUE TITLE
Major Rhymer range ability not working

### ISSUE THREAD

**Issue by AirborneEngineer** [Sandrem/FlyCasual#3196]
Major Rhymer, Empire Tie Bomber pilot, has the ability to fire missiles & torpedoes at one greater or lesser range than the printed weapons range to a minimum of range 0 & a maximum of range 3. I have been using him with Cluster Missiles & it will not allow him to fire missiles using his ability. Don't know if it is just Cluster Missile or if it is happening with other torpedoes & missiles.

**Comment by RobNyg87** [comment]
I've tried it with both Adv Proton Torps and Cluster Missiles with no luck. Seems like Rhymer's range ability is broken.

**Comment by Sandrem** [comment]
Fixed
