### ISSUE TITLE
Anakin Eta-2 doesn't remove target locks

### ISSUE THREAD

**Issue by SairFecht** [Sandrem/FlyCasual#3198]
When triggering Anakin's eta-2 ability on either himself or Obi-Wan the opportunity triggers and gives the choice of what red token to remove - if remove lock is selected the force cost is paid, but no lock is removed. 

Presumably if multiple enemies have locked Anakin then the player gets the choice of which lock to remove.

Cheers

**Comment by Sandrem** [comment]
Fixed
