### ISSUE TITLE
AI Punisher driving doughnuts like a boss

### ISSUE THREAD

**Issue by SteveRansom** [Sandrem/FlyCasual#3199]
AI vs AI, never seen anything like this before 🤣 

https://user-images.githubusercontent.com/60325223/110556105-b90cd900-80f2-11eb-9451-dcef304e6003.mp4

**Comment by Sandrem** [comment]
Thank you for fun video =)
But I still cannot reproduce - so I close issue until I will get additional information about steps to reproduce.
