### ISSUE TITLE
Zam bonus attack error

### ISSUE THREAD

**Issue by Wildkarrde10** [Sandrem/FlyCasual#3201]
after a few games with Zam Wessel, half the time the bonus attack with ZAM keeps stuck after spending charges.
There is no option for choosing a target and the skip button wont respond.

**Comment by Wildkarrde10** [comment]
> after a few games with Zam Wessel, half the time the bonus attack with ZAM keeps stuck after spending charges.
> There is no option for choosing a target and the skip button wont respond.

<img width="960" alt="ZAM Business" src="https://user-images.githubusercontent.com/80464041/110793248-b20dd400-8274-11eb-8187-318ebb09eddb.png">

**Comment by tinkerer93** [comment]
Can confirm, this issue is present in current version (1.8.5)

**Comment by Hamdamcwa** [comment]
still present in 1.8.6

**Comment by Sandrem** [comment]
Fixed
