### ISSUE TITLE
False Transponder Codes Ruling - Locking an obstacle does not spend FTC charge

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3203]
Text as written:
After you acquire a lock on an object or an object acquires a lock on you, if you have 1 charge active, lose 1  and jam that object, ignoring range restrictions. 

Because you cannot jam a non-ship obstacle (yet), you cannot fulfill the text on the card (IE Jam). At this time, only ships may be jammed. Jams (at this time) can only apply to ships.

GSP tournament broadcast, 3/13/2021. Referenced by FFG card developer Marshall Dee Yun.

This is important for any ships using Zam/Qira/Hondo. If 4Lom has Qira on board, and he wants to TL an obstacle, his charge is removed
![image](https://user-images.githubusercontent.com/6842889/111075689-38b1f380-84b7-11eb-9a47-75b8bd093c3a.png)
![image](https://user-images.githubusercontent.com/6842889/111075752-7151cd00-84b7-11eb-98a2-388c001f120a.png)
![FTC-JammedObject](https://user-images.githubusercontent.com/6842889/111075960-4320bd00-84b8-11eb-86a6-1c2126b311a7.png)

**Comment by Sandrem** [comment]
Thank you, fixed
