### ISSUE TITLE
Request: See “Random” Opponent 

### ISSUE THREAD

**Issue by JBFancourt** [Sandrem/FlyCasual#3205]
Please permit when selecting Random AI to battle, to view the list. 

It would be nice if you just played Howlrunner Swarm to be able to cycle the list without having to restart game. 

So Random Spawn can be clicked multiple times. 

Also, would be nice to have maybe a couple options: Aces, Beef, Swarm, etc...

Thanks!

**Comment by Sandrem** [comment]
Added to list of asked features.
