### ISSUE TITLE
1.8.6 - Pilots missing talents/BTL-A4 remove mod slot for Collaborators & Fugitives/Kanan cannot use Dark Side force.

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3212]
Thank you very much for the fast update with points, configurations, crew, etc. 

FFG/AMG updated their points list a day after the the initial release with these changes to available configuration slots:

Phoenix wing (A-wings):
Following pilots are missing a talent slot (they should all have 2)
Sabine Wren 
Wedge Antilles 
Derek Klivian 

Tie INT:
Nash Windrider has a talent slot.

Scum HWK:
Kanan Jarrus uses light-side force powers, not dark side. Would be able to use Patience, not Hate.

Scum BTL-A4 Y-Wing:
None of the Y-wing pilots from Fugitives and Collaborators have a modification slot available on their Y-Wings:
Leema Kai
Arliz Hadrassian
Padric
Amaxine Warrier
Jinata Security Officer

**Comment by Sandrem** [comment]
Missing talent slots are fixed, work in progress...

**Comment by Sandrem** [comment]
All is fixed
