### ISSUE TITLE
Can't find x-wing models

### ISSUE THREAD

**Issue by slighty26** [Sandrem/FlyCasual#3215]
![Screenshot 2021-03-26 2 29 22 PM](https://user-images.githubusercontent.com/81443678/112689835-6ba5a100-8e40-11eb-9f9e-35b25283cd00.png)
When an x-wing is selected it says It cant find the file directory
Edit: After some more playing around, it seems that it cant find the b-wing skins either
Edit 2: Yeah seems to just be with rebel ships

**Comment by Sandrem** [comment]
Please,  try to delete Customizable folder near executable file. And what OS do you use?  Linux?

**Comment by mcbratwin** [comment]
I have the same issue on Ubuntu.  Looks like it is a case issue.  folder is 'X-Wing' and it is looking for 'X-wing'. I renamed the folder with the correct case and it loaded an x-wing into the game just fine.
Cheers,
Mike

**Comment by Sandrem** [comment]
Fixed
