### ISSUE TITLE
Cluster Missiles can't fire a second time if the first target is destroyed by their attack.

### ISSUE THREAD

**Issue by DejaFu** [Sandrem/FlyCasual#3219]
I took out a target with Cluster Missiles, then when it asked me for the second attack, instead of showing Cluster Missiles, it showed my XX-23 S Thread Tracer missiles, so I couldn't fire the Cluster Missiles a second time (I couldn't select them).
![Cluster Missiles wrong missile option](https://user-images.githubusercontent.com/48073298/112769763-f7096880-8fdf-11eb-964a-2657c4fd4c85.png)
![Cluster Missiles wrong missile errors](https://user-images.githubusercontent.com/48073298/112769764-fa9cef80-8fdf-11eb-8651-bf3506d15942.png)

**Comment by baronklutz** [comment]
Looking at the screenshots it looks like the ship you are trying to shoot is at range 3 when cluster missiles have a range of 1-2

**Comment by DejaFu** [comment]
I see.  Maybe it could give an error with that message for the reason then.
