### ISSUE TITLE
Recommendation

### ISSUE THREAD

**Issue by obwoodlandj** [Sandrem/FlyCasual#3222]
Not an issue as much as a recommendation for the AI. Very few real players will just yolo over rocks like the AI does. It would be more realistic and helpful to new players to have the AI fly as close to a real human as possible. That said, I love FC and I appreciate all the work you do on it.

**Comment by Sandrem** [comment]
The AI will never fly as a real human - decisions are too complex. At least, it can shoot after such maneuvers - otherwise ships would leave combat and don't shoot for 1-3 rounds while they are returning.
