### ISSUE TITLE
Thread tracers and dice

### ISSUE THREAD

**Issue by Mackay001** [Sandrem/FlyCasual#3227]
1)  putting thread tracers on Hera, the game allows me to fire them with an evade instead of target lock or focus.
2) WTF IS UP WITH DICE???    I tried 4 games to test.   Hits, Crits, Evades are averaging +20% for the AI, and blanks are +20 - 40% for me.   I get a bad game, or occasion variance, but when the "Random" opponent seems to be a variable counter to what I run, and then proceeds to run perfect evade or paint for an entire game. it's making a guy say f*** it and go play a real game with someone else.

**Comment by Sandrem** [comment]
1) Known bug, duplicate
2) Dice work as in real life,  nothing to fix here.
