### ISSUE TITLE
Lyttan Dree pilot ability

### ISSUE THREAD

**Issue by majormajorminor** [Sandrem/FlyCasual#3228]
Excellent app, btw.

I might be the only person who has flown Lyttan, but his pilot ability seems to be triggering in his front and back arcs. I think it is supposed to only work in his side arcs.

**Comment by baronklutz** [comment]
It's supposed to trigger when they are in an opponents side arc, its a bit confusingly worded.

**Comment by majormajorminor** [comment]
It is! Thanks!

**Comment by Sandrem** [comment]
Seems that everything is working fine. If problem exists - please, provide screenshot next time.
