### ISSUE TITLE
Game crash on startup (mac OS version)

### ISSUE THREAD

**Issue by DaxSolo82** [Sandrem/FlyCasual#3236]
Hi, I just want to report that I haven't been able to start FC for about a week on Mac OS. I can't share any pic because FC didn't start at all, crashing instantly when I try to run it.
I played the 1.8.6. version without any problem since the download.
Is there any problem with the mac os version?

Ty
Davide

**Comment by Sandrem** [comment]
Fixed in the upcoming version
