### ISSUE TITLE
Hera A-wing Ability

### ISSUE THREAD

**Issue by obwoodlandj** [Sandrem/FlyCasual#3238]
It forces you to use her ability before dice are rolled and thats not accurate. It should be changed to be an option to choose after dice are rolled

**Comment by baronklutz** [comment]
Technically her ability can be used at any point when a friendly ship is attacking/defending, however I agree with you that the best time is probably after the dice have been rolled.

**Comment by Sandrem** [comment]
Hera's ability is updated (Errata is included)
