### ISSUE TITLE
Hera attack timing issues

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3240]
Current rules allow hera to pass an evade/focus/target lock while another ship performs or defends.

Garvin, armed with proton torpedoes, takes a focus. Hera locks someone in garvin's range. Currently how the game is coded, he cannot perform a protorps attack, he would has to lock first, perform the attack, then hope for some eyeballs so hera can pass a focus to him. He uses the focus, and gives it back to hera. 

Apparently her ability is enabled at any stage of "perform attack" or "defend".

Current unofficial (but tournament official) ruleset is here: https://docs.google.com/document/u/0/d/1cSNaoKAThwjDhjjixO7u-MZZ3l5xu-LgKnRohhTIkYk/mobilebasic

Not to pile on, but Arliz (y-wing scum), apparently can spend a focus while damaged and defending to change an eyeball to evade.. or if she is hiding behind a gas cloud and rolls eyeballs, she can then change one eyeball to blank, gaining her an auto evade.

Thank you for your time to update these strange interactions.
---
Hera was errata'd. Please close.

**Comment by grandpajive** [comment]
Working as intended. Hera was errata'd.

**Comment by Sandrem** [comment]
Hera's ability is updated (Errata is incuded)
