### ISSUE TITLE
Zeb Orrelios crew not working on Han Solo

### ISSUE THREAD

**Issue by Karl4242** [Sandrem/FlyCasual#3245]
Zeb crew on Han.  Still says, "not a valid target" when Han tries to shoot a range0 opponent in side arc.  possibly front/rear

**Comment by Karl4242** [comment]
now trying zeb on Hera (VCX) same issue.

**Comment by Sandrem** [comment]
Duplicate of https://github.com/Sandrem/FlyCasual/issues/3109
