### ISSUE TITLE
Kanan Jarrus vcx-100 cant use Evade received from Hera

### ISSUE THREAD

**Issue by JorgeArenas** [Sandrem/FlyCasual#3247]
Kanan Jarrus vcx-100 cant use Evade received from Hera's  AWing ability in. 
I've included Replay, but it crashes with null value when trying to play it back in beginning.
![Kana_vcx-100_EveadToken](https://user-images.githubusercontent.com/3461624/115065334-00d60b80-9ebc-11eb-8940-bc6cac385435.png)
[LastReplay.zip](https://github.com/Sandrem/FlyCasual/files/6327109/LastReplay.zip)

**Comment by baronklutz** [comment]
Evade tokens have been nerfed in second edition, they no longer add an evade result but rather change a dice result to an evade. If a ship has no dice to change, e.g. it has 0 agility, then it can't spend the token.

**Comment by Sandrem** [comment]
Not a bug, closed
