### ISSUE TITLE
Autoblasters unblockable crit effect seems to be active when in targeted ship's front arc if its primary turret arc is not facing forward

### ISSUE THREAD

**Issue by HumbleBob** [Sandrem/FlyCasual#3251]
Played a game with Anakin in Eta-2 with autoblasters against AI K-wing list.  At one point, Anakin was firing autoblasters against a K-wing at range 1 in its front arc (out of range for barrage rockets, which might be relevant).  The K-wing's turret arc was in the left-right position, i.e. Anakin was out of arc.  During the defense step, Anakin's crit had the lightning symbol indicating that it is unblockable.  The K-wing did not roll an evade, so I couldn't confirm that the game treated the crit as unblockable.

**Comment by Sandrem** [comment]
Thank you, fixed
