### ISSUE TITLE
Range check for attack not equal between ships

### ISSUE THREAD

**Issue by JorgeArenas** [Sandrem/FlyCasual#3261]
Online network play.
1st round. - one side was in 3 range for attack, but the other defender was unable to attack back in 3 range.
TalonBane Cobra attacked Emon Azzameen at 3 Range.
However Emon Azzameen was unable to attack TalonBane Cobra.

Replay attached

[LastReplay_20210507.zip](https://github.com/Sandrem/FlyCasual/files/6446415/LastReplay_20210507.zip)

**Comment by Sandrem** [comment]
Fixed
