### ISSUE TITLE
Seventh Fleet gunner

### ISSUE THREAD

**Issue by scooter8709** [Sandrem/FlyCasual#3264]
![Fly Casual 5_9_2021 3_15_50 PM](https://user-images.githubusercontent.com/83924651/117585740-98a0d100-b0d9-11eb-9b5e-c971b6369af2.png)

Seventh fleet locks the game, after declining to use 7fg dice are rolled for both attacker and defender. No error occurs, unable to continue game, have to exit game completely to restart.

**Comment by Sandrem** [comment]
Fixed
