### ISSUE TITLE
R2-D2 (Rebel crew)/Han Solo (Rebel pilot) interaction

### ISSUE THREAD

**Issue by Hallaore** [Sandrem/FlyCasual#3274]
Love the app.

I don't think R2 & Han are interacting correctly together. Artoo lets you roll one attack die to recover one shield; if you roll a hit, you flip a facedown damage card. Han's ability should let you re-roll that die if you're within 0-1 of an obstacle. Happened a few times, but wasn't able to screengrab due to the absence of the interaction (sorry).

**Comment by Hallaore** [comment]
Just had another play - it looks like this applies to Han with other dice-roll effects too e.g. damage cards like Wounded Pilot or Stunned Pilot etc.

**Comment by Sandrem** [comment]
Dice modification of non-combat rolls is in plans
