### ISSUE TITLE
R4-B11 not working properly.

### ISSUE THREAD

**Issue by Nannerpus90** [Sandrem/FlyCasual#3275]
When using R4-B11, it causes the attacker to reroll their dice instead of the defender. It should be that as the pilot with R4-B11 attacks, they can cause the defender to reroll defence dice by spending their red/orange tokens. And as Lando (escape craft) coordinates with Hondo, Lando becomes stressed for some reason.

**Comment by Sandrem** [comment]
Thank you, fixed
