### ISSUE TITLE
Tie Brute HLC cannon issue

### ISSUE THREAD

**Issue by DalleDC** [Sandrem/FlyCasual#3277]
The title of the tie brute says to treat the arc of the cannon as a turret. But a HLC cannon is the exception because it does not have the normal arc and only works in the bulls eye arc. So you are able to fly with your turret arc backwards and still have your HLC cannon pointing forwards.

**Comment by baronklutz** [comment]
When I tested it it was working as described, which is correct

**Comment by DalleDC** [comment]
I am testing it now, and it works, strange, I just played a list for 3 days at home on my own computer where I could not get it to work, but no issue then.

**Comment by Sandrem** [comment]
Cannot reproduce, closed
