### ISSUE TITLE
Dutch Vander-R3 Astromech Interaction

### ISSUE THREAD

**Issue by Earthworrm** [Sandrem/FlyCasual#3286]
There's an issue with which target lock Dutch Vander passes using his ability when he has more than one target lock.  When acquiring a second lock (either using R3's free lock, or its 'maintain two locks' ability) the oldest target lock is listed first (on the left), and the new one is listed second on his info card.
However, triggering Dutch's ability passes this oldest target lock, not the one just acquired.

In the example screenshot, Dutch had a lock on Wolffe from a previous turn.  That's target lock pair 'B.'  On this turn Dutch locked Barriss Offee, (lock pair 'C,' which became the second/right on Dutch's card).  I then triggered Dutch's ability (in the screen before this shot was taken), and selected the Gold Sqn. Veteran as the recipient of the lock.  This created lock pair 'D,' which connects Gold Sqn Veteran with Wolffe, not with Barriss Offee, who Dutch just locked.  Dutch's ability duplicated his lock 'B,' not lock 'D' which it should have.
![Dutch Vander Screenshot](https://user-images.githubusercontent.com/31047905/120083999-90590780-c081-11eb-9ef9-1d96056123ed.png)

**Comment by Sandrem** [comment]
Fixed
