### ISSUE TITLE
Fearsome Predator Condition

### ISSUE THREAD

**Issue by baronklutz** [Sandrem/FlyCasual#3288]
when assigning the fearful prey condition, only one copy of the condition should be assigned.
![image](https://user-images.githubusercontent.com/52109920/121378708-561e1e80-c93b-11eb-8f5f-ce597c298c65.png)

**Comment by baronklutz** [comment]
![Uploading image.png…]()

**Comment by Sandrem** [comment]
Thank you, fixed
