### ISSUE TITLE
Garven ability - you cannot select this friendly ship

### ISSUE THREAD

**Issue by jamesrhum** [Sandrem/FlyCasual#3289]
![Garven](https://user-images.githubusercontent.com/66371287/121773278-cebaf000-cb72-11eb-93ee-8cbb2c86b842.jpg)
In this picture the TIE fighter Garven shot at is at R2, so all of the friendly ships must be R3, none of them can receive the focus token that garven just spent.

**Comment by jamesrhum** [comment]
Reproduced again:
![Garven2](https://user-images.githubusercontent.com/66371287/122113407-fda6bf80-ce19-11eb-908b-d0a5b8afb5f6.jpg)

**Comment by Sandrem** [comment]
There is "Skip" button for case if no targets are in range. I will think about change to don't ask about ability if there is no targets in range.

**Comment by Sandrem** [comment]
Oh, I see - ability is Range 1-3 is v2.0, but was 1-2 in v1.0 - I will fix this. Thank you.
