### ISSUE TITLE
Contrail ability

### ISSUE THREAD

**Issue by SairFecht** [Sandrem/FlyCasual#3294]
Contrail's ability seems to trigger in circumstances when ships do not have matching bearings. 

e.g. I noticed the option to use contrail's eye-to-blank power when an enemy ship did a 2 bank and contrail did a 2 k-turn. 

There were a few other instances when this issue appeared, but without being able to check the dials it was hard to be certain. 

Cheers

**Comment by Sandrem** [comment]
Thank you, fixed
