### ISSUE TITLE
Nash Windrider - pilot ability trigger - causes time out

### ISSUE THREAD

**Issue by RCH-76** [Sandrem/FlyCasual#3296]
I have an Imperial Sqaudron with Nash Windrider (TIE/in), Gideon Hask (TIE/in), Iden Versio, Seyn Mara, and Del Meeko assigned to the AI. If Nash Windrider is destroyed before his turn in initiative (2), the turn order will not advance past the current initiative. I don't know if this problem also occurs if I play as the Empire instead of the AI. I've noticed this because Nash is my target priority so I go after him if I have the chance.

**Comment by Sandrem** [comment]
Fixed
