### ISSUE TITLE
Tractor tokens are decreasing agility on small ships per token

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3300]
![image](https://user-images.githubusercontent.com/6842889/125322716-afdf8300-e303-11eb-8a2e-ff3e7ad37a79.png)

Zuvio performed a spacetug tractor array on Sunny Bounder. Sunny now has 1 agility... she should still have 2 agility, but definitely should still have 2 tokens (for R4-B11 usage).

**Comment by grandpajive** [comment]
Also, the next round, Sunny's agility was not restored to "3".
![image](https://user-images.githubusercontent.com/6842889/125331976-4ca71e00-e30e-11eb-9591-4dd09d3f878f.png)

**Comment by Sandrem** [comment]
Fixed
