### ISSUE TITLE
Un able to install app in Android 

### ISSUE THREAD

**Issue by AgentKato** [Sandrem/FlyCasual#3304]
I can download the package but installation fails when it it almost.done. this happen in a Google 3 pixel

**Comment by Sandrem** [comment]
Please, check free space on your device. If you have previous version of the game - try to uninstall it first.

**Comment by AgentKato** [comment]
Thank you this worked great!!!!

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________
