### ISSUE TITLE
Ion bomb not dealing damage

### ISSUE THREAD

**Issue by keatonr06** [Sandrem/FlyCasual#3311]
Ion bombs seem to be applying 3 ion tokens, but not making victims suffer 1 damage.

**Comment by Sandrem** [comment]
Description of ion bomb effect ( https://xwing-miniatures-second-edition.fandom.com/wiki/Ion_Bombs )

At the end of the Activation Phase, this device detonates.
When this device detonates, each ship and remote at range 0-1 gains 3 ion tokens, and each remote at range 0-1 suffers 1 Hit damage. 

Please, provide source - where is said that ion bomb deals damage to ships too.

**Comment by keatonr06** [comment]
My mistake. I misread the ion bomb effect. I thought the second part said "remotes and ships suffer damage"
