### ISSUE TITLE
plasma torpedoes inflict criticals

### ISSUE THREAD

**Issue by keatonr06** [Sandrem/FlyCasual#3314]
I was able to inflict critical damage with a plasma torpedo. Crits should instead be converted into regular hits.

**Comment by baronklutz** [comment]
Plasma torpedoes can still deal crit damage, it's just that they get cancelled first so you tend to need multiple.

**Comment by keatonr06** [comment]
ohh...I thought they were like ion and don't do criticals. nvm then
