### ISSUE TITLE
Emergency Deploy caused crash

### ISSUE THREAD

**Issue by SleepyJedi** [Sandrem/FlyCasual#3316]
VCX-100 with docked Sheathipede shuttle was destroyed. When the emergency deploy should've occurred, got this error message.
![Fly Casual 8_12_2021 10_37_01 PM](https://user-images.githubusercontent.com/26986510/129310217-a44e97d1-73a5-45b4-8cab-52355bf646e2.png)

**Comment by Sandrem** [comment]
Fixed
