### ISSUE TITLE
Better UI for network games

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#332]

**Comment by thiagoBHS** [comment]
Hey, If you need I can help you with these problem. I'm a design especialized on UX/UI and I will be happy to help :D

**Comment by Sandrem** [comment]
I almost finished this feature. Post here your e-mail, I will contact you soon =)

**Comment by Sandrem** [comment]
Task is finished.
@thiagoBHS contact me on reddit or in any issue to discuss new UI.

**Comment by thiagoBHS** [comment]
thiago.b.hh@gmail.com here it is :)
