### ISSUE TITLE
Ships getting green dice that they should not

### ISSUE THREAD

**Issue by wavemanns** [Sandrem/FlyCasual#3329]
![EscalatingGreenDicePNG](https://user-images.githubusercontent.com/6612122/131458062-379a6d74-e1e2-4405-ab6b-0d768ec7c09f.PNG)
It is intermittent but I occasionally run into an issue where my opponents get way too many green dice. It is happening in this screen shot with  star killer base pilot but it happens to me much more when the opponent is flying scum aggressors. Happens more when I am not in the opponent's arc. Each shot adds a die. It may happen more when the ship in question has other ships at range 0 as is the case in this screen shot.

**Comment by Sandrem** [comment]
Did you use tractor tokens before this bug?

**Comment by wavemanns** [comment]
I didn't with the Shadowcaster Title ability, but the shadowcaster will
auto assign them on a hit when the conditions are met with Ketsu Onyo. So
not on this round because the caster bumped, but in a previous round yes.

**Comment by grandpajive** [comment]
Medium/large ships seem to increase agility if they are assigned 1 token (medium) or two tokens (large).

If a small ship receives more than one tractor token, the ships agility is reduced by one or more through the rest of the match.

3 agility decimators are scary. Rick ole with 0 agility is funny.

**Comment by Sandrem** [comment]
Fixed
