### ISSUE TITLE
Reinforce not working

### ISSUE THREAD

**Issue by woolliersquare** [Sandrem/FlyCasual#3332]
Reinforce does not reduce incoming damage, not even if your double reinforced

**Comment by Sandrem** [comment]
![изображение](https://user-images.githubusercontent.com/6347443/131866632-d1aa79b9-f15b-4373-8d81-eb2de86d52fe.png)

![изображение](https://user-images.githubusercontent.com/6347443/131866655-d03b2f1d-1035-450a-82d3-49e22b42fa3a.png)

**Comment by Sandrem** [comment]
Reinforce works correctly. Please, next time provide screenshot or replay.
Maybe, you had only 1 hit in dice pool white reinforced? Or you were flanked by attacker?

**Comment by woolliersquare** [comment]
>
