### ISSUE TITLE
Dash Rendar and Hera VCX get too little red die

### ISSUE THREAD

**Issue by woolliersquare** [Sandrem/FlyCasual#3333]
Dash Rendar and Hera Syndulla (VCX) only get 3 attack die when attacking, they should have 4 standard and they dont get +1 red die for being range 1

**Comment by Sandrem** [comment]
Attack of Dash Rendar, 4 dice
![изображение](https://user-images.githubusercontent.com/6347443/131865704-422a434b-eaa5-4e77-a8f1-05b92c41ccde.png)

**Comment by Sandrem** [comment]
Attack of Hera, 4 dice
![изображение](https://user-images.githubusercontent.com/6347443/131865798-53d371bc-3747-4dce-b5eb-2f9ebd840b67.png)
