### ISSUE TITLE
The child+zam/magva yarro 

### ISSUE THREAD

**Issue by grandpajive** [Sandrem/FlyCasual#3351]
Tried the child equipped on han solo (scum) with zam. After attacked, I get an option to gain a lock (you should thank me), I do, and can't continue. Have to force close the app.

Tried the child on Cassian (u wing) with the child and magva yarro crew. After I take damage, FC asks me to take a lock after suffering damage, game locks up, force close to continue.

**Comment by Sandrem** [comment]
Fixed
