### ISSUE TITLE
Incorrect pilots, upgrades slot and upgrade cost on TIE Whisper and TIE bomber FO

### ISSUE THREAD

**Issue by NightfallSky** [Sandrem/FlyCasual#3359]
Whisper:
- Pilots:
-- Missing generic pilot "Red Fury Zealot"
- Upgrade slots:
-- Wrath should only have 1 talent, not 2
-- All whispers should have 2 tech slots, not 1

TIE Bomber FO
- Pilots:
-- Missing generic pilot "Sienar-Jaemus test pilot"
- Upgrade slots:
-- Should have 2 payload slots, not 1
-- Should have 1 modification slot, not a configuration

Upgrades:
- Force:
-- "Brilliant evasion" should cost 2, not 1
-- "Hate should" cost 4, not 3

**Comment by Sandrem** [comment]
Thank you

**Comment by Sandrem** [comment]
Fixed by ersk
