### ISSUE TITLE
Error after movement through multiple bombs

### ISSUE THREAD

**Issue by QueenKoopa1** [Sandrem/FlyCasual#3366]
While playing the game I flew through a proximity mine, and then did a left bank with General Grievous piloting the Beluba Class Starfighter. Got this error. Also, was playing online. New ships (as of the last six months) were included in the rosters for both sides.

![FlyCasualError](https://user-images.githubusercontent.com/91765959/135698727-003dc99b-81df-4cc8-886e-75b4a8a2a556.png)

**Comment by Sandrem** [comment]
Fixed
