### ISSUE TITLE
IOS crashes on first launch of new version

### ISSUE THREAD

**Issue by bewareoftheklaw** [Sandrem/FlyCasual#3367]
![Screen Shot 2021-10-02 at 14 05 50](https://user-images.githubusercontent.com/78597450/135718088-0cdd93b2-eb81-47bc-a850-fe25e346ad4b.png)

**Comment by Sandrem** [comment]
No ideas, I create usual build for MacOS. Maybe there are some ways to fix this - but this is a question for advanced MacOS users (I don't use this OS).
Or wait for release of another version, maybe newer version of Unity3D engine will fix this.
