### ISSUE TITLE
Obstacles error report

### ISSUE THREAD

**Issue by Wurms2** [Sandrem/FlyCasual#3377]
I loaded my squads from XWS (link here: https://raithos.github.io/?f=Galactic%20Empire&d=v8ZsZ200Z186X38WWY186X38WWY186X38WWY465X128WWWY187X128W137W332WWW&sn=Goran%20Reapers&obs=core2asteroid1)

Said error when loading squad, but ship and upgrades looked all there, so I clicked on obstacles and got an error report (attached)
<img width="923" alt="Screen Shot 2021-10-22 at 3 57 19 PM" src="https://user-images.githubusercontent.com/65094280/138532288-8914dad8-d051-448b-a513-23b410addadd.png">

**Comment by Sandrem** [comment]
Only 1 obstacle was present in imported XWS.
I changed error handing, now the game will only show pop-up with warning and will use default list of obstacles.
