### ISSUE TITLE
TA-175 timing

### ISSUE THREAD

**Issue by SairFecht** [Sandrem/FlyCasual#3380]
Due to a rules change, and inclusion of comma in the wording, it seems that the timing of the TA-175 effect has moved from the removal of the ship to the specific instance after the ship is destroyed. 

https://ffg-forum-archive.entropicdreams.com/topic/304815-timing-on-destroyed-ship-has-changed/

**Comment by Sandrem** [comment]
Fixed: Timing is changed from "when removed from the table" to "when destroyed immediately"
