### ISSUE TITLE
Echo's shields

### ISSUE THREAD

**Issue by Jedi34** [Sandrem/FlyCasual#3381]
a shield lacks to Echo
![bug bouclers écho](https://user-images.githubusercontent.com/93074364/139474577-8f389fff-bee7-4eee-a33d-dd4520833b7f.png)

![bug bouclers écho 2](https://user-images.githubusercontent.com/93074364/139474800-85107e7d-4a89-475b-89a0-c55778b1c49c.png)

**Comment by grandpajive** [comment]
That's how angled deflectors work. Lose 1 shield.
