### ISSUE TITLE
Multiple Tractor Tokens each reduce agility. Only one agility is returned at end of round.

### ISSUE THREAD

**Issue by draconics212** [Sandrem/FlyCasual#3397]
I have noticed while playing with Tractor affects that stacking more than one token on a small base ship reduces that ship's agility by one for each token. During the end round, after Tractor tokens are removed, the affected ship's agility is increased by one instead of going back to the original value. 

For example, Darth Vader Defender with a Tractor Beam cannon hits Gavin Darklighter's E-Wing and applies two Tractor tokens. Gavin's agility for the rest of the round is now 1, and after removing tokens at the end of round his agility is increased to 2.

I have also been able to do this when using different sources of Tractor tokens. For example, Ketsu at range 1 + Ketsu's attack with Shadow Caster, Latts Razzi, Unkar, and Syck interceptor with Tractor Beam cannon.

Screenshots attached of poor, abused Rebels
![Tractor3](https://user-images.githubusercontent.com/94997918/143316745-e76a8bf7-eff8-4c4c-859d-a2ccddeeef81.jpg)
![Tractor2](https://user-images.githubusercontent.com/94997918/143316751-67857e36-d05c-4102-9821-4f0f9709beb6.jpg)
![Tractor1](https://user-images.githubusercontent.com/94997918/143316754-4b62c1e0-cfd1-4ee4-aa2b-2d1455f0d060.jpg)
.

**Comment by Sandrem** [comment]
Fixed in dev-build
