### ISSUE TITLE
Change dial after setting

### ISSUE THREAD

**Issue by ckdragons** [Sandrem/FlyCasual#3428]
Is there an option / key press that will allow me to change a dial after being set before leaving the Planning Phase? For example, I set ship #1 and then set ship #2, realizing that I want to make a change to ship #1 at that point.

**Comment by baronklutz** [comment]
I believe that up until you lock your dials in by pressing the next button in the bottom right corner, you can click on either the ship model or on the list on the side and it will bring up the set dial interface again.

**Comment by ckdragons** [comment]
You are correct. Sorry I didn't make the connection. Thank you.
