### ISSUE TITLE
Friendly bumping damage is bugged!

### ISSUE THREAD

**Issue by GoldSquadronBombadier418** [Sandrem/FlyCasual#3477]
According to 2.5 rules, whenever friendly ships bump, 1 attack die is rolled to determine damage. However I got multiple prompts, each with a single attack die (as seen in the attached image. 

![Fly Casual 19_06_2022 23_29_40](https://user-images.githubusercontent.com/107801283/174484464-56be33f0-56b2-44f7-b40f-6d949e0ff31a.png)

**Comment by grandpajive** [comment]
I've found after one or two games, close Fly Casual and reopen the game.

**Comment by Sandrem** [comment]
Fixed
