### ISSUE TITLE
Resize of GUI-Elements based on resolution

### ISSUE THREAD

**Issue by NachHause** [Sandrem/FlyCasual#357]
By now it seems like the menues are not scaling correctly when playing at the highest and lowest resolution.  
These images have been exported from the `non windowed` mode.  
(Monitor: 3840x2160)

3840x2160:  
![resolution_3840x2160](https://user-images.githubusercontent.com/34003527/33240732-2c220922-d2bb-11e7-9ef5-594901f1040b.jpg)

1920x1080:  
![resolution_1920x1080](https://user-images.githubusercontent.com/34003527/33240792-3a203106-d2bc-11e7-99d8-4492f174398b.jpg)

640x480:
![resolution_640x480](https://user-images.githubusercontent.com/34003527/33240800-67014dcc-d2bc-11e7-9dda-d71a9011b4a3.jpg)

**Comment by Sandrem** [comment]
Resize of UI is planned for 0.4.0
