### ISSUE TITLE
Sensory Jammer breaks the game

### ISSUE THREAD

**Issue by junkyhlm** [Sandrem/FlyCasual#360]
When a player uses the "Sensory Jammer" system upgrade the defending and attacking player cannot press anything so the game comes to a halt. 
![untitled](https://user-images.githubusercontent.com/813630/33243377-6fbe07b0-d2e5-11e7-9beb-4672d96674ca.jpg)

**Comment by Sandrem** [comment]
I will check soon.

**Comment by Sandrem** [comment]
Network-only problem. Will be fixed later.

**Comment by Sandrem** [comment]
Fixed
