### ISSUE TITLE
Agent Kallus decision is fired Exception

### ISSUE THREAD

**Issue by Ras-al-Raul** [Sandrem/FlyCasual#361]
Upon starting a a game with Agent Kallus on a Lambda shuttle, an exception occurs, which results in a game state that requires the game to be closed. Selecting the same two squads without Kallus starts normally.

![kallus-start](https://user-images.githubusercontent.com/34006976/33244874-0c383228-d2cd-11e7-8d98-96ba7aee9a94.PNG)

**Comment by Sandrem** [comment]
Fixed in development.
Will be released sonn in small update.
