### ISSUE TITLE
Suggestion: onscreen list of all hotkeys

### ISSUE THREAD

**Issue by FourTeeTwo** [Sandrem/FlyCasual#364]
It would be useful if you could press a key (like F1 for example) and a semi-transparent panel would show on screen showing all the hotkey/shortcuts in the game.

**Comment by Sandrem** [comment]
Good idea. Will be in one of next updates.

**Comment by Sandrem** [comment]
Moved to features list

**Comment by mwhuss** [comment]
Is there at least a page with the support keyboard/mouse commands?
