### ISSUE TITLE
Camera move too fast on Mac

### ISSUE THREAD

**Issue by FourTeeTwo** [Sandrem/FlyCasual#365]
When I right-click and move the mouse to move the camera on my Mac, the speed of the camera move is much too sensitive. It's not my mouse speed to blame, as that's set fairly low. My preference would be to have a key that could be pressed to engage camera mode (in addition to the right-click option). So when you press the "C" key for example and move the mouse, this moves the camera view.

**Comment by Sandrem** [comment]
But if I will add just another way to turn on this camera mode - this will not fix problem with too fast movement.
I don't have Mac to test this.

Can you make video that shows speed of movement? I can just adjust speed values for Mac.

**Comment by ajmath** [comment]
I wasn't able to reproduce this on a 2015 macbook pro.  Though, it would be more convenient for laptop play to have a hotkey for rotating the camera.

**Comment by Crashcart** [comment]
When I first got the game I had an issue with it on 4.1. I kinda quit playing with it for a bit. 4.2 seems just fine to me. I figured originally it was just me.
