### ISSUE TITLE
Download Forbidden

### ISSUE THREAD

**Issue by Fedaykin2520** [Sandrem/FlyCasual#369]
Please help! I have tried to download the Windows.zip several times and at different points during the download, it stops and says "forbidden". I have created an account and it is still happening. Troubleshooting says:
"This error means you don't have permission to download this file from the server.

To fix, go to the website where the file is hosted. Check if you need to sign in (or provide some other authentication). If you can't sign in, contact the website or server owner, or try finding the file on a different site."

This thing looks amazing and I'd love to give it a try. Any advice would be appreciated!

**Comment by Sandrem** [comment]
Hello. This is the first mention of such problem.
1) What web browser and antivirus software do you use? Maybe, some additional firewall?
2) Please, try to download this file using another browser, or with turned off antivirus, or form mobile device.
3) Link for the same file in my Dropbox - check it too.
https://www.dropbox.com/s/fq580m9wjrn3f7l/Windows.zip?dl=0

Inform me about results.
