### ISSUE TITLE
FCS incorrectly triggering for both players

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#374]
After shooting at an enemy ship which has Fire Control System I am asked if I would like to take a target lock. This ability should only be triggered for the enemy after it has taken its shot at me.

I have seen this issue in multiple games

![image](https://user-images.githubusercontent.com/34140446/33454257-346ef402-d610-11e7-8766-b08373f94888.png)

**Comment by Sandrem** [comment]
Thanks, I will check now.

**Comment by Sandrem** [comment]
Fixed in 0.3.1
