### ISSUE TITLE
Error when going offline

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#375]
This may be an expected behaviour rather than a bug but while trying to play on a long train journey with intermittent internet I have been getting null ref exceptions. I have seen these errors both on the menu page and during the game

Here is an example

![image](https://user-images.githubusercontent.com/34140446/33454391-a658da6a-d610-11e7-8011-4c1790cc25b8.png)

**Comment by Sandrem** [comment]
Error when trying to download a tooltip for pilot/upgrade card.
Fixed in 0.3.1
