### ISSUE TITLE
Windowed Mode - Infinite scroll when moving cursor out of play

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#377]
Steps to replicate:

Open game in windowed mode
Start new game
During play, move the cursor outside of the window
  - In game map continues to scroll in the direction of the cursor
  - This is annoying as you then have to scroll it back to the main map when you click back into the game
  (Causes me issues when trying to take screenshots for your bug reports :-) )

**Comment by Sandrem** [comment]
Fixed in development branch
