### ISSUE TITLE
AI - Ship flew out of play - still attacked?

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#378]
YT2400 - Dash Randar (HLC) (PS7) few out of the play area 
  - Ship was destroyed
  - Attack was still initiated against my PS 5 ship

Expected: Ships destroyed by flying off the board should not be able to attack

![image](https://user-images.githubusercontent.com/34140446/33491205-6e53405a-d6b1-11e7-89cd-5b224a24fc96.png)

**Comment by Sandrem** [comment]
Dash Rendar was controlled by AI, am I right?

**Comment by houseofcutler** [comment]
Yes, sorry I should have added that

**Comment by jmcnett010** [comment]
I can confirm this bug, it has happened to me at least twice

**Comment by Sandrem** [comment]
I can reproduce it, will be fixed this week.

**Comment by Sandrem** [comment]
Fixed, version 0.3.2 is ready for release.
