### ISSUE TITLE
Null Ref error when Range ruler overlaps obsticle?

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#380]
I have seen this error in a few different games, 

Steps taken:

Select Ship
Select Enemy Ship
Declare as target of attack
  - Range ruler applied
  - Error message displayed in console [ObstaclesFiringLineDetector]

If I try to click on the enemy ship again a notification says  "Your ship has already attacked"

I think last time I saw this error the end of the range rules was also over a rock. Will update this task if I see the error again

![image](https://user-images.githubusercontent.com/34140446/33492194-3f7c7564-d6b4-11e7-82e9-9e79a0ff3a6e.png)

** EDIT - Just seen this issue again - Same lists as last game.
  No Asteroids involved this time just threw an error when I targeted the other ship?

![image](https://user-images.githubusercontent.com/34140446/33492599-6ca1cc28-d6b5-11e7-98e8-6e3fad23c76b.png)

**Comment by Sandrem** [comment]
I cannot reproduce this bug.
Did you check in another battles? In another situations when Range ruler overlaps obstacles or another ships?

**Comment by Sandrem** [comment]
Still cannot reproduce, no another such reports. Maybe is not actual anymore.
