### ISSUE TITLE
Any time I try to play a game it does this:

### ISSUE THREAD

**Issue by bhfroh** [Sandrem/FlyCasual#382]
![image](https://user-images.githubusercontent.com/32801256/33519130-1c9c831a-d766-11e7-9a4f-139ad6ca8b79.png)

**Comment by Sandrem** [comment]
I cannot reproduce this bug.
I can provide you a test-build that can give more information about this bug.
Will you have time to test this again?

**Comment by Sandrem** [comment]
Seems that it is fixed now. Please, report this bug again if it will appear in 0.4.0.
