### ISSUE TITLE
Offering me to use opponents Howlrunner ability

### ISSUE THREAD

**Issue by bhfroh** [Sandrem/FlyCasual#383]
Flying 4 T-70s against Howlrunner and several TIE/FOs, if I am in R1 of Howlrunner, it will offer for me to use her ability

![image](https://user-images.githubusercontent.com/32801256/33519224-380aaa08-d768-11e7-9299-c93a1e3d7ed7.png)

**Comment by Sandrem** [comment]
Fixed in development
