### ISSUE TITLE
Target ship is not set while distance/arc is measured

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#384]
Look forward to improvements. Game freezes and needs ship data expanded. This is my latest experience
![capture](https://user-images.githubusercontent.com/34241206/33556858-35c9e148-d8ba-11e7-8a4c-f54ec4a4bfd5.jpg)

**Comment by Galaxy613** [comment]
I see that this was inside of combat. What happened right before the Null Pointer Exception?

**Comment by Sandrem** [comment]
Same problem with another player: https://user-images.githubusercontent.com/6347443/33388994-359aebe6-d53a-11e7-9f6d-46b9ca3e2bff.png

Also additional question: what mode/opponent where in this battle? AI, network or local opponent?

**Comment by Sandrem** [comment]
Same problem: https://github.com/Sandrem/FlyCasual/issues/387

**Comment by Sandrem** [comment]
Fixed in development branch
