### ISSUE TITLE
[Duplicate] Null Ref exception - ship.genericshipbase.getpoints when declaring attack

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#387]
First attack, first round of combat in Human vs AI game

(Human)- A-Wing Arvel Crynyd declare attack on (AI) Lambda Shuttle - Omnicron Group Pilot

A-Wing - Chadran refit, Expertise, A wing test pilot - Has a focus
Shuttle - No upgrades, Has a focus, is Target Locked by VCX-100 Kanan

![image](https://user-images.githubusercontent.com/34140446/33673415-8cc014f4-daa4-11e7-9b12-3a816724067d.png)

**Comment by Sandrem** [comment]
Same bug as https://github.com/Sandrem/FlyCasual/issues/384 but thanks for details.

**Comment by Sandrem** [comment]
Fixed in development branch
