### ISSUE TITLE
Incorrect out of arc scenario

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#388]
Human X-wings vs AI Tie Fighters

As you can see form this image the Tie Fighter is clearly within range and arc of the X-wing but the system says no.

please note - this turn the x-wing bumped another ship which was destroyed before i tried to use the x-wing to attack.

![image](https://user-images.githubusercontent.com/34140446/33719637-5323229e-db59-11e7-9795-3c8c514d1f03.png)

**Comment by Sandrem** [comment]
I used yellow line to extend arc-limits from the ship's base image. (Arc's angles are not 90 degrees, they are ~80+)
https://i.imgur.com/p3GdAmn.jpg
As you see, TIE is outside the arc, ruler shows nearest point outside the arc in this case.

Not a bug.

**Comment by houseofcutler** [comment]
Fair enough. In that case perhaps an enhancement idea would be to display
the range ruler in a way that matches up with the arc calculation?

**Comment by houseofcutler** [comment]
Or perhaps overlay the equivalent of the yellow line when notifying the
player that it is out of arc?

**Comment by Sandrem** [comment]
Yes, I have plans to show limits of arc for these cases - but this has very low priority and will not be present in nearest updates.
