### ISSUE TITLE
Enhancement: Barrel Roll and Boost direction selection

### ISSUE THREAD

**Issue by jbuckland** [Sandrem/FlyCasual#401]
Awesome work btw. I just found this project and was messing with it a bit and noticed this issue.

Need: According to the rules, barrel roll direction (left or right) and boost direction (left, right, or straight) needs to be declared before you see where the move would end up.

Possible Solution: After the user selects boost (or barrel roll), pop up another box to have them select their options, including a cancel option.

**Comment by Sandrem** [comment]
This is done intentionaly, to make UI more simple.
I plan to support real rule of planning, but later, not in nearest future.
