### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Arctitian** [Sandrem/FlyCasual#407]
Hey, couldn't find where else to submit this. Just had a crash in a generic B-wing + Auzituck vs 4 TIE battle. 

Love what you've done, it's really good. 

[Crash_2017-12-15_130112.zip](https://github.com/Sandrem/FlyCasual/files/1561669/Crash_2017-12-15_130112.zip)

**Comment by Sandrem** [comment]
What antivirus do you use? Seems that problem was due to real-time protection of antivirus. In this case I cannot help.

**Comment by Arctitian** [comment]
Just Windows Defender (10).

**Comment by Sandrem** [comment]
Oh, this is very strange.
Unfortunately, I don't have any idea how to prevent this bug in future - so I close this issue.
