### ISSUE TITLE
Swarm Tactics still triggers after death

### ISSUE THREAD

**Issue by BGolem** [Sandrem/FlyCasual#408]
![fly casual - post-death swarm tactics trigger](https://user-images.githubusercontent.com/34514233/34045950-395817cc-e179-11e7-953d-d84888058c07.png)

TIE Fighter #5 was destroyed in the previous round but was still included in the list of Swarm Tactics triggers. It happened again the next round after another TIE Fighter was destroyed after taking the screenshot- the same window with all five Swarm Tactics triggers despite only having three TIE Fighters left.

**Comment by Sandrem** [comment]
Fixed
