### ISSUE TITLE
Dropping bombs the round after using a bomb token locks you in activation phase

### ISSUE THREAD

**Issue by jmcnett010** [Sandrem/FlyCasual#410]
I was able to consistently reproduce this, using this loadout:
{"faction":"rebel","points":31,"version":"0.3.0","pilots":[{"name":"goldsquadronpilot","points":31,"ship":"ywing","upgrades":{"turret":["twinlaserturret"],"torpedo":["bombloadout","extramunitions"],"amd":["flightassistastromech"],"bomb":["clustermines"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Yellow"}}}]}

First turn, drop bombs using extra munitions.
Second turn, drop bombs again.

This gets you stuck in the activation phase with no ability to continue.

![no-continue-button](https://user-images.githubusercontent.com/6131204/34084792-6b648dea-e354-11e7-9d27-8c18dde4e00b.png)

**Comment by Sandrem** [comment]
What mode is it? Local or internet match?

**Comment by jmcnett010** [comment]
Local

On Dec 17, 2017 18:11, "Sandrem" <notifications@github.com> wrote:

What mode is it? Local or internet match?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Sandrem/FlyCasual/issues/410#issuecomment-352293632>,
or mute the thread

**Comment by Sandrem** [comment]
Fixed
