### ISSUE TITLE
Starting a 2nd game with extra munitions throws an error in the console

### ISSUE THREAD

**Issue by jmcnett010** [Sandrem/FlyCasual#411]
How to reproduce:

1. Start a game with a bomb loadout, extra munitions and cluster mines:
{"faction":"rebel","points":31,"version":"0.3.0","pilots":[{"name":"goldsquadronpilot","points":31,"ship":"ywing","upgrades":{"turret":["twinlaserturret"],"torpedo":["bombloadout","extramunitions"],"amd":["flightassistastromech"],"bomb":["clustermines"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Yellow"}}}]}

2. Press esc, go to main menu
3. Start a game with the same loadout

![2nd-game-same-session-bomb-issue](https://user-images.githubusercontent.com/6131204/34084850-4255b068-e355-11e7-8786-bdc8b8d6a68d.png)

**Comment by Sandrem** [comment]
What mode is it? Local or internet match?

**Comment by jmcnett010** [comment]
Local

**Comment by Sandrem** [comment]
Fixed
