### ISSUE TITLE
YT-2400 Heavy Laser Cannon Outrider measure distance from wrong point

### ISSUE THREAD

**Issue by freelancer212dsx** [Sandrem/FlyCasual#413]
I've noticed that this certain build combination,  Outrider YT-2400 with Heavy Laser Canon and Dash, almost always can shoot ships beyond range 3.  The range ruler that gets placed in the game even shows it being out of range.

**Comment by Sandrem** [comment]
Please, when you will get this problem again - make a screenshot when range ruler is shown and attach it here.

**Comment by freelancer212dsx** [comment]
Here is a screenshot of the arc not being measured correctly. 
![dashrendar360arcincorrectmeasure](https://user-images.githubusercontent.com/30575548/34144962-c6c9dd6c-e448-11e7-9a19-327c2f987040.JPG)

**Comment by Sandrem** [comment]
Distance/arc measurement will be rewritten n 0.5.0 - old bugs are not actual anymore.
