### ISSUE TITLE
Target Lock Option Persists After Norra Wexley's Ablity

### ISSUE THREAD

**Issue by freelancer212dsx** [Sandrem/FlyCasual#414]
Consider a player is flying Norra Wexley, and they have a target lock on an enemy ship.  After making an attack roll, the player uses "Norra Wexley's ability" in the battle menu.  The option for Target Lock will still be available.

The computer does know that the lock was spent, but the option still remains.

**Comment by Sandrem** [comment]
If you click button "Target lock" you will get message that you cannot use this effect because TL is already spent.
One day I plan to rework how buttons of dice modifications are shown, but for nearest few versions I plan to left this as is.
