### ISSUE TITLE
Howlrunner's ability can be used by opponent's ships

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#417]
Greetings, Sandrem!

Congratulations for the project! I'm loving it and can't wait to see it fully developed!

I was playing against an AI TIE Swarm and I noticed that, when I got close to the enemy squadron, I could use Howlrunner's ability to reroll 1 attack dice. So I made a custom game and controlled all ships in it. So you can check the print below as a proof: 2 A-Wings shooting at the Decimators and being able to reroll 1 attack dice thanks to Howlrunner, the traitor. Lol.

![Uploading Howlrunner Bug 1.PNG…]()

**Comment by Sandrem** [comment]
Hello. This bug is already fixed in upcoming 0.3.2 (release of new version is planned for the end of this month).
