### ISSUE TITLE
Kanan Jarrus ability shown twice

### ISSUE THREAD

**Issue by freelancer212dsx** [Sandrem/FlyCasual#418]
Even though only one ship has moved, Kanan Jarrus shows up twice.
![kananjarrusabilityshowntwice](https://user-images.githubusercontent.com/30575548/34183795-6221e132-e4d1-11e7-9905-25a6afe20118.jpg)

**Comment by freelancer212dsx** [comment]
Sometimes I am able to use his ability twice in a single turn, taking up to 4 actions.

**Comment by Sandrem** [comment]
Fixed
