### ISSUE TITLE
Rebel Ship Sabine's Tie Fighter Sabine Pilot Doestn't Have EPT Slot

### ISSUE THREAD

**Issue by freelancer212dsx** [Sandrem/FlyCasual#420]
Rebel Ship Sabine's Tie Fighter Sabine Pilot Doestn't Have EPT Slot
![sabinetiefighternoept](https://user-images.githubusercontent.com/30575548/34291211-08d984a0-e6b0-11e7-905d-a5265d1ff327.JPG)

**Comment by Sandrem** [comment]
Fixed
