### ISSUE TITLE
Skipping free action when using PTL brings up debugger

### ISSUE THREAD

**Issue by Tech55b** [Sandrem/FlyCasual#423]
Was playing with the inquisitor, had PTL equipped. after the first turn took the first action then decided to not take the second action from PTL to avoid stress. Skipped Free action and the dugger showed up.

Link to screenshot  https://i.imgur.com/ljPQcDr.jpg

**Comment by Sandrem** [comment]
Bug in TIE/v1 title, fixed.
Will be released in hotfix soon.
