### ISSUE TITLE
NULL reference error/crash for Target Lock on destroyed enemy

### ISSUE THREAD

**Issue by BrendonAF** [Sandrem/FlyCasual#424]
When playing a match with an Advanced Tie and Adv. Tie Prototype, I had set two target locks in the preparation phase on an enemy ship. Vader rolled ALL the dice and vaporized the scum. When my Prototype's turn came next, the debugging console opened up and only gave me the option to quit to menu or quit to desktop (after showing there was a NULL reference set to an object). 

Looks like the game doesn't fail out of the attack/targeting logic if the target happens to already be destroyed!

**Comment by Sandrem** [comment]
Bug of Advanced Targeting Computer (it tries to set "you can use this Target Lock as usual" after combat, but TL is removed because target was destroyed).
Fixed, will be released in hotfix soon.
