### ISSUE TITLE
Offline Issues - Uncancelled Crit Errors

### ISSUE THREAD

**Issue by BGolem** [Sandrem/FlyCasual#431]
![fly casual - offline issues](https://user-images.githubusercontent.com/34514233/34328166-0a415678-e88c-11e7-8306-9100b03d619e.png)

When playing offline (in the screenshot I had turned on airplane mode) the first uncancelled crit will cause the error message shown.

The pilot and upgrade card mouseover popups also don't work when offline, but that's not too much of a problem.

Using 0.3.2 Hotfix 1

**Comment by Sandrem** [comment]
Fixed in development version.
