### ISSUE TITLE
Nera Dantels and Extra Munitions Error

### ISSUE THREAD

**Issue by BGolem** [Sandrem/FlyCasual#436]
I get this error every time I start Nera Dantels with Extra Munitions, whether human-controlled or AI-controlled, even when that's all she has equipped. I've tried other ships with EM and Nera Dantels with other loadouts (both controlled by me or the AI) and as far as I can tell this is the only combo that gives this error.

This is in Versus AI mode in 0.3.2 Hotfix 1

![fly casual - nera dantels error](https://user-images.githubusercontent.com/34514233/34457896-4dc12cd8-ed74-11e7-9d3e-de91c3c5fc25.png)

**Comment by Sandrem** [comment]
Thanks. This bug is already fixed in development build.
