### ISSUE TITLE
The console opens with an error when you start a new game

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#437]
**Build**: 0.3.2 Hotfix 1
**Android**: 5.0.1
**Bug**: critical

**Steps:**

1. Start the game and press New Game.
2. Press the Versus AI.
3. Customizable (image 1):
  3.1 For both you choose the ARC-170 and Norra Wexley;
  3.2 For the enemy to select the Alpha-class Star Wing and Major Vynder.
4. Press Start.

**Actual result**: opens console with an error and the game stops (image 2). 

**Expected result**: game continues to run.

Additionally: re-was not played.

Image 1
![1](https://user-images.githubusercontent.com/34982133/34461640-65462b3e-ee40-11e7-9c83-f39774b98be7.JPG)
Image 2
![2](https://user-images.githubusercontent.com/34982133/34461641-759cef7c-ee40-11e7-8ef2-c3588178f00a.JPG)

**Comment by Sandrem** [comment]
Not present in squad builder of 0.4.0
