### ISSUE TITLE
Remember the location of the previous image

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#440]
**Build**: 0.3.2 Hotfix 1
**Windows**: 10 Professional
**Bug**: Minor

**Steps**:

1. In the settings window of the match we direct the mouse cursor on the ship. The image appears with a description (image 1).
2. Then we direct the mouse cursor on another ship and the image appears with a description (image 2)
 
**Actual result**: the image appears in place of the previous the image.

**Expected result**: the image appears near the mouse cursor.

Additionally: If you move the mouse cursor the image appears in the right place (image 3)

Image 1
![2](https://user-images.githubusercontent.com/34982133/34467317-1bf89d80-eeff-11e7-889d-d7f56dfa9ce7.JPG)

Image 2
![3](https://user-images.githubusercontent.com/34982133/34467330-69b3356c-eeff-11e7-99d1-360ae9ceb3cd.JPG)

Image 3
![4](https://user-images.githubusercontent.com/34982133/34467358-26f3ddac-ef00-11e7-8596-cbebcc18f45c.JPG)

**Comment by Sandrem** [comment]
Please, check - can this bug be reproduced in match?
(Squad builder will be replaced soon, so you can ignore it's bugs)

**Comment by djeknemesis2012** [comment]
Yes, it can. Now I will create new bug.

**Comment by Sandrem** [comment]
Closed due to plans of Squad Builder's complete rework.
