### ISSUE TITLE
Does not start the match with 58 points or more

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#443]
**Build:** 0.3.2 Hotfix 1
**Windows**: 10 Professional
**Bug:** Critical

**Steps**:
1. Press the Versus AI.
2. The player adds himself ships on 58 points or more (image 1).

**Actual result**: infinity loading the match (image 2).

**Expected result**: the match is loaded.

Image 1
![default](https://user-images.githubusercontent.com/34982133/34471750-dfc3bc42-ef61-11e7-8cc5-a34aaf9f2812.png)

Image 2
![default](https://user-images.githubusercontent.com/34982133/34471732-8a68492a-ef61-11e7-8a88-e56e075079f8.png)

**Comment by Sandrem** [comment]
Cannot start the game with two unique pilots in same team.
Already fixed in development build.
