### ISSUE TITLE
The sound of the destruction of the ship does not sound until the end

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#447]
**Build**: 0.3.2 Hotfix 1
**Windows**: 10 Professional
**Bug**: Minor

**Steps**:

1. Any ship sending outside the playing field. It will be destroyed (Image 1). 

**Actual result**: the sound of the destruction of the ship does **not sound** until the end.

**Expected result**: the sound of the destruction of the ship **sounds** until the end.

Additional: cannot be verified when one ship destroys the other because a menu appears and stops the game.

Image 1
![default](https://user-images.githubusercontent.com/34982133/34526246-f7dbcf16-f0b2-11e7-9d75-261c67863e9c.png)

**Comment by Sandrem** [comment]
Fixed, now ship is removed only after sound is played till the end.
