### ISSUE TITLE
The playing field covers the number on the ship

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#448]
**Build**: 0.3.2 Hotfix 1
**Windows**: 10 Professional
**Bug**: Minor

**Steps**:
1. During a match press Alt. The number appears above the ship (image 1).

**Actual result**: The number **behind** the playing field.

**Expected result**: The number **over** the playing field.

Image 1
![default](https://user-images.githubusercontent.com/34982133/34527723-8d321d5a-f0b7-11e7-97cb-30c623d33abf.png)

**Comment by Sandrem** [comment]
Won't fix - problems with Unity's renderer.
