### ISSUE TITLE
Autothusters Effect Triggered at Range 1 + Small Ships shooting Large Ships even when touching

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#449]
Hey there!

I've played double IG-2000 vs TIE Fighter swarm just for fun and then two weird things happened... 
First one is: the TIE Fighters could shoot my IG's even when they bumped me at the activation phase, but I couldn't shoot them back if I had bumped them, so shooting a small ship with a large ship works as intended.

The second thing I've noticed is that, the same attacks made at range 1 by the TIE Fighters touching my IG would allow me to use Autothrusters.

Maybe a bug related to the YT-2400 wrong measuring?

![at bug 2](https://user-images.githubusercontent.com/1640572/34532386-229bd108-f09d-11e7-838e-949fe0b2eec0.PNG)
![at bug 3](https://user-images.githubusercontent.com/1640572/34532387-22c3e670-f09d-11e7-90b9-ec45dad2f2ac.PNG)
![at bug 4](https://user-images.githubusercontent.com/1640572/34532388-22ef388e-f09d-11e7-9cbd-913e83f8e061.PNG)
![at bug 5](https://user-images.githubusercontent.com/1640572/34532389-2318a57a-f09d-11e7-90f8-f85751c5ab8b.PNG)
![at bug](https://user-images.githubusercontent.com/1640572/34532390-2364489a-f09d-11e7-962a-329abc285547.PNG)
![Uploading Distance Bug.PNG…]()

**Comment by Sandrem** [comment]
Seems that bug is caused when multiple ships are bumped.
Possible reason of autothrusters bug is unknown, I need to investigate.
Thanks =)

**Comment by Vazkman** [comment]
It is I who thank YOU, man, for doing so much for the X-Wing community and charging nothing at all, despite all the hard work. <3

**Comment by Sandrem** [comment]
Really I prefer thanks in form of Patreon support, but thanks for such good words too =)
As a bonus, you can take a look on new Squad Builder (work in progress, planned for 0.4.0): https://imgur.com/a/loWiC

**Comment by Vazkman** [comment]
Really cool, man! I'm a brazilian and currently unemployed, but when I start making money I'll support you at Patreon! Keep up the good work!

**Comment by Sandrem** [comment]
Few problems are fixed. Please, report again if one of these problem will be encountered in 0.4.0
