### ISSUE TITLE
Auzituck Obstruction Defense Bonus Bug

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#450]
Hey there! Just found a new issue...

I was playing with 4 Auzituck vs TIE Fighter swarm (as usual) and, several times, my Auzitucks received a bonus green dice for obstruction, although there were no asteroids on the way.

![obstruction bug](https://user-images.githubusercontent.com/1640572/34533717-99571028-f0a2-11e7-9556-5faa27be28b8.png)

**Comment by Sandrem** [comment]
Seems that bug is related to https://github.com/Sandrem/FlyCasual/issues/444
But here is visible wrong reason of extra die.
Thanks, this is very useful information.

**Comment by Sandrem** [comment]
Fixed
