### ISSUE TITLE
Endless Combat

### ISSUE THREAD

**Issue by BGolem** [Sandrem/FlyCasual#455]
![fly casual - endless combat phase](https://user-images.githubusercontent.com/34514233/34591587-7b9a7512-f173-11e7-96c0-6f4c1212946e.png)

I can keep attacking the closest X-wing with the two TIE Defenders on the right. Tokens are used up and the X-wing keeps losing damage but the combat phase doesn't end.

![fly casual - endless combat phase 2](https://user-images.githubusercontent.com/34514233/34591721-63606a96-f174-11e7-9c69-6fb9b61375ea.png)

Even after destroying the X-wing, I can still keep attacking over and over- don't have to alternate, I can keep attacking with the same Defender.

[Removed a section because I didn't notice they were firing at the same PS level]

**Comment by Sandrem** [comment]
Already fixed, will be in next update/
