### ISSUE TITLE
No launcher after download

### ISSUE THREAD

**Issue by henrygrant899** [Sandrem/FlyCasual#458]
just downloaded and there is no launcher for the game anywhere in the folder for it.
(great work btw)
cheers

**Comment by Sandrem** [comment]
Seems that this problem is caused by your antivirus.
Some free antiviruses (Avira, AVG) have false virus detection on EXE-file and move it to quarantine.
Try to update antivirus bases, or add exe-file to exceptions.

If you are not sure about file - tou can check it on virustotal.com
