### ISSUE TITLE
Single ship can shoot multiple times in one round

### ISSUE THREAD

**Issue by c0d3m0nk3y** [Sandrem/FlyCasual#461]
In this example against the AI, I have used the selected B-wing to fire at the selected TIE fighter three times already, and can continue to do so until the TIE is dead - each time I do have to roll dice.

![image](https://user-images.githubusercontent.com/321945/34742638-c5e06d20-f57e-11e7-8622-f6147328c158.png)

**Comment by Sandrem** [comment]
Known bug, already fixed in development build. Update will be soon.
