### ISSUE TITLE
Double-clicking a ship to attack throws double dice, then freezes the game

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#464]
Hey, it's me again!

Not on purpose, once I was playing and suddenly double the dice appeared on the attack, then the game froze after the defense step finished. So I tried to reproduce it: when you double-click a ship on the attack phase, it throws double the dice (but it just counts the normal dice number for the results); the rolled red dice remains on screen during the defense roll, and after it, the game doesn't go to the planning phase, but you can still press Esc and quit the match.

![double click 1](https://user-images.githubusercontent.com/1640572/34825289-04625be0-f6b9-11e7-83a3-d48e5b929f7d.png)
![double click 2](https://user-images.githubusercontent.com/1640572/34825290-0488dac2-f6b9-11e7-90bf-a3640a466a82.PNG)
![double click 3](https://user-images.githubusercontent.com/1640572/34825291-04ad19fa-f6b9-11e7-8242-72ed3f267bf3.PNG)

**Comment by Vazkman** [comment]
Checking the other issues, looks like #445.

**Comment by Sandrem** [comment]
> double-click a ship

Great! I finally have way to reproduce and fix. Thanks a lot! =)

**Comment by Sandrem** [comment]
Fixed in 0.4.0
