### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#465]
Too many attackdice crash . Like your game idea. There are many issues to fix. It's very frustrating. Hope you keep working on it. 
![image](https://user-images.githubusercontent.com/34241206/34909544-0cd3b210-f858-11e7-86a7-31e63dec2cd2.png)

**Comment by Sandrem** [comment]
Known bug: appears when during attack target ship is double-clicked (attack is launched twice, too many dice are shown, game is stopped).
Will be fixed soon. Meanwhile, select target for attack with only one click on it. =)
