### ISSUE TITLE
Swarm tactics when I don't have it?

### ISSUE THREAD

**Issue by Heilemann** [Sandrem/FlyCasual#468]
I'm playing a rebel list and I don't have swarm tactics on any of my ships, but the empire (AI) has Howlrunner with swarm tactics, but every round I'm asked to select a target for swarm tactics? Am I misunderstanding the rules, or is this a bug?

**Comment by Sandrem** [comment]
Bug. AI don't know how to handle abilities with "Select Ship" - so it asks human to select target for such ability. (Same is for Asajj Ventress, for example). I plan to fix this in one of the nearest versions.

I close this issue as known bug.
