### ISSUE TITLE
Start battle scene with prebuild squad

### ISSUE THREAD

**Issue by sirhaplo** [Sandrem/FlyCasual#474]
Hi Sandrem,
I open an issue because i cant find a way to contact you directly.
I would like to help writing down some new cards.
I started with Juke.

I didntfound a way to start / restart Battle scene with a prebuild Roster ( Omega leader / Juke / Comm relay ) to debug my card without restart every time from MainMenu.

Thank you 
I hope to help a bit in this absolute fantastic project

**Comment by sirhaplo** [comment]
Wow, this projects is so well maintained.
My compliments.

I will keep doing Juke to train me. So when it will be ready i can judge how well i did.
Or in case it will be still free i have a version.
I can work also on Omega Ace.

I will follow you on reddit.

**Comment by Sandrem** [comment]
Yes, you can take "Omega Ace" - this is good example of work with dice modifications. Mark it in the table.

**Comment by Sandrem** [comment]
I just added way to restart battle with same squad lists. This will help in testing =)
