### ISSUE TITLE
Movement screens remain

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#481]
I like version 4, nice job. Keep up the good work. New issue with movement screens in Local play.
![image](https://user-images.githubusercontent.com/34241206/35068574-4ac2d8e4-fb8c-11e7-9261-f6a491e80e0d.png)

**Comment by Sandrem** [comment]
Do you use recent nightly build (16.01.18) ?

**Comment by RJAGame** [comment]
Yes

**Comment by Sandrem** [comment]
Already fixed in development-version.
To avoid bug - just don't click on ship when maneuver selection window is already shown.

**Comment by RJAGame** [comment]
Yes. 160118
