### ISSUE TITLE
Token is displayed incorrectly

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#487]
Build: 0.4.0

Steps:

1. Choose a ship with one upgrade. 
2. In first turn choose a focus.

Actual result: token is displayed out of place.
Expected result: token is displayed in place.

![1](https://user-images.githubusercontent.com/34982133/35177149-70578ede-fd8e-11e7-86cc-942b84b569b7.jpg)

**Comment by rats3g** [comment]
I attempted to replicate this issue with the current development version using the same setup. 

Following the steps:

1. Choose a ship with one upgrade (Syndicate Thug Y-Wing, Ion Cannon Turret)
2. Choose a focus on first turn

I was unable to reproduce the issue with the focus token showing as in the expected image above.

**Comment by Sandrem** [comment]
Additional requrements: this is ship of second player and this is first activation in the activation phase.

**Comment by Sandrem** [comment]
Fixed by update of Unity to v2018.2.0b2
