### ISSUE TITLE
Two frame of the ship

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#488]
Build: 0.4.0

Steps:

1. Choose the ship.

Actual result: two frame of the ship under the table.
Expected result: one frame of the ship on the table.

![default](https://user-images.githubusercontent.com/34982133/35179218-eaa1ff9a-fda6-11e7-9dc5-6619633f204d.JPG)

**Comment by Sandrem** [comment]
Fixed
