### ISSUE TITLE
Bistan - the corners of the template

### ISSUE THREAD

**Issue by djeknemesis2012** [Sandrem/FlyCasual#492]
Build: 0.4.0

Steps:

1. Go into the window with upgrades.

Actual result: Bistan has white corners,
Expected result: Bistan has transparent corners.

![default](https://user-images.githubusercontent.com/34982133/35179339-799380be-fda9-11e7-85f9-831445c15e43.JPG)

**Comment by Sandrem** [comment]
Fixed
