### ISSUE TITLE
Infinite view scroll

### ISSUE THREAD

**Issue by DarkCanuck29** [Sandrem/FlyCasual#497]
Running on Windows 7. When a game starts the view continuously scrolls up and the the left. The game is unplayable due to this, as the table can never be focused on.

**Comment by Sandrem** [comment]
Is this problem both in window-mode and full screen-mode?

**Comment by DarkCanuck29** [comment]
Yes, it is.

**Comment by Sandrem** [comment]
Just a wild guess - do you have any gamepad/joystick connected to PC?
I had once similiar bug in Magic 2015 when Saitek X52 was connected - game used one of it's axis.

**Comment by DarkCanuck29** [comment]
I tried it both ways. Neither worked.

**Comment by Sandrem** [comment]
This person has similiar problem, reason was in mouse drivers.

> szymciu
> Its definitely a problem with 3D Connection SpacePilot: https://www.3dconnexion.pl/index.php?id=30

**Comment by Sandrem** [comment]
I added console commands to turn off some input: "input axis" and "input mouse".
Try them.
