### ISSUE TITLE
Tie/Sf Pilot

### ISSUE THREAD

**Issue by Kooza25** [Sandrem/FlyCasual#505]
Missing Quickdraw and Backdraft

**Comment by Sandrem** [comment]
Game is in development. Not all pilots/upgrades are present.
Not a bug. Please, don't report missing content.

**Comment by Kooza25** [comment]
Hey there, sorry for that you’re right. Didn’t know where to ask for additional content.

Loris Venegoni - Kooza

Portfolio & Store

Instagram | Facebook | Soundcloud

Il 21 gen 2018, 12:50 +0100, Sandrem <notifications@github.com>, ha scritto:

**Comment by Sandrem** [comment]
All existing pilots/upgrades will be added - this is only matter of time.
Some popular cards require more complex work, so they will be added later.

By the way, Backdraft is in development branch and will be added soon in hotfix-update =)
