### ISSUE TITLE
Hit bug with M12 Kimogila

### ISSUE THREAD

**Issue by synthetix808** [Sandrem/FlyCasual#506]
[flycasual_bug.txt](https://github.com/Sandrem/FlyCasual/files/1649727/flycasual_bug.txt)

![screen shot 2018-01-21 at 3 56 27 am](https://user-images.githubusercontent.com/32894716/35193971-ed7ef470-fe5f-11e7-9f49-d6b7f0273205.png)
![screen shot 2018-01-21 at 3 56 32 am](https://user-images.githubusercontent.com/32894716/35193972-eea59c5a-fe5f-11e7-8d29-f3af6329c308.png)

**Comment by Sandrem** [comment]
Thanks you, will be in hotfix soon.

**Comment by Sandrem** [comment]
Fixed
