### ISSUE TITLE
Dash Rendar Countermeasures Crash Game

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#511]
Here is the setup:  Two Tie Bombers use LRS to get two target locks.   
Next Turn,  Dash pops countermeasures and looses BOTH target locks.....and then game crashes.

-Thanks!

**Comment by Sandrem** [comment]
Still cannot reproduce.
If you will get same problem again - please, make a screenshot of condole with red text.

**Comment by Bismarcksea** [comment]
Screenshot of bug attached!
![dash error](https://user-images.githubusercontent.com/35663377/36455376-c49f7ac2-166d-11e8-951a-aa93cc756e84.JPG)

**Comment by Sandrem** [comment]
Countermeasures are fixed in development branch.
Release of new version is planned on Friday.
