### ISSUE TITLE
Y-Wing with TLT only wants to shoot out arc

### ISSUE THREAD

**Issue by Tingaleo** [Sandrem/FlyCasual#518]
Good morning!

Today, while flying 4 gold squadron Y-Wings with TLTs and Flight Assist Astromechs, I could not target ships outside of arc with TLT. Created a new game of hotseat with the each side having the same squadron and experienced the same situation for each side.

**Comment by Sandrem** [comment]
Flight-Assist Astromech: "You cannot attack ships outside your firing arc."
> TLTs and Flight Assist Astromechs, I could not target ships outside of arc with TLT. 

Are you sure that this a bug?

Or instead as in title - "Y-Wing with TLT only wants to shoot out arc" ?
This is opposite behavior and bug.

**Comment by Tingaleo** [comment]
No it's not, sorry I didn't pay full attention to the text on the card. Thanks for the quick reply and for making a great program! I'll go look for some actual bugs!

**Comment by Sandrem** [comment]
Have a nice day
