### ISSUE TITLE
Rey destroying a ship (or hitting with gunner) crashed my game

### ISSUE THREAD

**Issue by Werdna76** [Sandrem/FlyCasual#526]
Played Rey with Gunner and blew up a ship on second shot (after first missed) and game crashed to the red text overlay screen, whatever that's called.  I restarted and same situation... second shot with gunner blows up ship (Vader) and game crashes.  Not sure if it's Rey/YT-1300, Gunner, or what.   Up until then everything seemed good with abilities.

**Comment by Sandrem** [comment]
Gunner s bugged - already fixed in dev-branch, fix will be released soon.
