### ISSUE TITLE
Crash after second attack when using "Gunner" 

### ISSUE THREAD

**Issue by Wutex666** [Sandrem/FlyCasual#527]
Game crashed when VT-49 shooting for the second time using "Gunner" after the target rolled his defense dice.
![image](https://user-images.githubusercontent.com/34987285/35350987-e07d3bbe-013f-11e8-9109-f4568173aa8b.png)

**Comment by Sandrem** [comment]
Gunner is bugged. New version 0.4.1 has fix and will be released in a hour =)

**Comment by Wutex666** [comment]
Great! Amazing piece of software by the way!
