### ISSUE TITLE
Poe + bb8 + PTL

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#530]
> We noticed a strange behavior with Poe + bb8 + PTL: after revealing a green maneuver the game propose to take the free barrel roll thanks to Bb8. But immediately after the barrel roll or denied barrel roll, the game propose a free action. Then the ship does the maneuver then again propose to take another action. If the player does, the ship does not take a stress token from PTL. I think it is the wrong sequence of action and that the ship should take the stress token

**Comment by ChiefMoose** [comment]
Doesn't he get the stress, but then removes it because he's performing a green maneuver. If I'm understanding this correctly.

**Comment by Sandrem** [comment]
> Whoa! Insane combo. First time playing Poe so I was not sure. Thanks!

Closed
