### ISSUE TITLE
movement freeze

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#540]
using version 4.1 movement frozen.
![image](https://user-images.githubusercontent.com/34241206/35426890-129d5b2a-021b-11e8-8822-c152d4d8fbf7.png)

**Comment by Sandrem** [comment]
Still cannot reproduce. But I did some changes in this part.
If this bug will appear in 0.4.3 or later, please, also write what action you performed (or no action - bump, for example).
