### ISSUE TITLE
Camera view on Android App?

### ISSUE THREAD

**Issue by pablopc80** [Sandrem/FlyCasual#542]
Hello,

First of all, thank you very much for such and outstanding job. This is a great easy and fun app to stay in touch of the game when you don´t have the oportunity to play.

I would like to change the view on the Android version to a bottom angle in order to be more confortable to play. Is there any way to do so?

This is not a real Issue, I hope you don´t mind.

Thank you again

**Comment by Sandrem** [comment]
Current Android version is just a proof that game can be launched on Android too. It lacks adaptation for mobile device controls and optimization. In one of the next versions I will add button to switch view mode, it will be in left bottom corner.
