### ISSUE TITLE
AI Asajj is asking for target of her ability to the opponent player

### ISSUE THREAD

**Issue by Azrapse** [Sandrem/FlyCasual#544]
When the AI plays Asajj Ventress pilot (Lancer), at the beginning of combat phase, the game asks for a target to her ability to the human player. It highlights the wrong targets, and won't let you select one of your ships, for being friendly.

Instead, Asajj should offer that choice to her own player, the AI.

**Comment by Sandrem** [comment]
AI cannot handle step "select a ship" - this cause same problem in a number of abilities, not only Asajj.
Will be fixed in next update.

**Comment by Sandrem** [comment]
Fixed in development branch
