### ISSUE TITLE
PTL

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#545]
> Flying Sheathipede shuttle with Flight Assisted Astromech which gives a free action. Also using Push the Limit on him. After using the free action on a boost and then my regular action on a coordinate action I get a stress token, which shouldn't happen until I use the push the limit card for an additional action.

**Comment by Sandrem** [comment]
> Flying the IG-2000 with Push The Limit. The program throws up a console screen with red errors if I choose to skip using the PTL ability.

**Comment by rats3g** [comment]
Did some investigation into these issues. Upon testing, both issues appear to be resolved by #599.
