### ISSUE TITLE
Choosing "victim" with action bombs

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#555]
The game seems to choose by itself (when the player should) which ship under a mine token gets the damage.
(Was playing with cluster mines, if that helps)

**Comment by Sandrem** [comment]
In battle vs AI, or in battle "Human vs Human" ?

**Comment by Giledhil** [comment]
Human vs AI.


________________________________
De : Sandrem <notifications@github.com>
Envoyé : lundi 29 janvier 2018 12:08
À : Sandrem/FlyCasual
Cc : Giledhil; Author
Objet : Re: [Sandrem/FlyCasual] Choosing "victim" with action bombs (#555)


In battle vs AI, or in battle "Human vs Human" ?

**Comment by Sandrem** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/6347443/61187652-e46cc580-a67c-11e9-9e2a-848de4c1002b.png)
