### ISSUE TITLE
Gunner, IG-88B/D Interaction

### ISSUE THREAD

**Issue by the-gabbo** [Sandrem/FlyCasual#556]
YV-666 equipped with gunner, (Mangler)-cannon and IG-88D crew, IG-88B with title in play.
Observed behavoiur:
When YV-666 attacks and misses with first attack player can attack one more time.

Expected (correct) behaviour:
When YV-666 attacks and misses with first attack he triggers two times the "attack again trigger" (gunner and IG-88B). If the player choses to resolve the IG-88B trigger first and the gunner trigger last he can attack two more times and is allowed to hit with both attacks.

**Comment by Sandrem** [comment]
Tested in development branch - behavior is correct, two additional attacks that can hit.
Please, check this again later, when version 0.4.2 will be released.
