### ISSUE TITLE
Auzituck Gunship freezes game when tries to swerve from the board edge

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#557]
Hello again!

I was testing the IG-88 against 4 generic PS1 Auzituck Gunships. Everything was ok, until one of the Gunships got too close of the edge and, when trying to swerve, the game froze. At the first time, I managed to restart the game from the menu, but in the second try it happened again and the game crashed.

![auzituck swerve bug 1](https://user-images.githubusercontent.com/1640572/35519577-ca1ca796-04fb-11e8-8ed8-b516195e40f4.PNG)
![auzituck swerve bug 2](https://user-images.githubusercontent.com/1640572/35519578-ca58bf42-04fb-11e8-8e2b-618b5e561129.PNG)

**Comment by Sandrem** [comment]
I just fixed another bug with Swerve.
If you will encounter same problem in "0.4.2 Hotfix 1" or later - let me know.
