### ISSUE TITLE
0.4.2: Target Locks not being removed.

### ISSUE THREAD

**Issue by NickyDaB** [Sandrem/FlyCasual#563]
With the new token system. I think there is something funky with target lock removal. I've gotten into situations where there are a lot of extra red target locks on the board. My guess is that red target locks aren't properly removed when blue locks get removed. I think I'm able to reproduce when a ship is destroyed and other ships on the board have it target locked.

**Comment by NickyDaB** [comment]
I can't add labels to this issue?

**Comment by Sandrem** [comment]
I confirm this bug. Easy way to reproduce: battle 1-vs-1 against AI ship with TL action. He will assign TLs again and again - and all red TLs are left.

**Comment by Sandrem** [comment]
About labels - seems that you need to be in Collaborators to have access. (This also grants access for changing wiki and dirrect commiting without pull requests).

**Comment by Sandrem** [comment]
Fixed

**Comment by NickyDaB** [comment]
nice work
