### ISSUE TITLE
Wrong active player in multiplayer

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#577]
> If you host a game and your opponent has a Bombardier you may choose where to lay his mines. The same happens with the Scum ship with a bullseye firung arc (pilot Dalan Oberos (Kimogila)). You may choose for him where to put his target lock.

**Comment by zdravkotatic** [comment]
The ability of the pilot Asajj Wentress is also affected by this bug

**Comment by Sandrem** [comment]
Fixed in development branch
