### ISSUE TITLE
moldy crow multiple focus tokens in combat NULL exception

### ISSUE THREAD

**Issue by NickyDaB** [Sandrem/FlyCasual#583]
I found a bug. I was able to narrow it down to it being some issue with the "Moldy Crow" title on the HWK. 

**Description**
If the HWK with the moldy crow title goes into combat with multiple focus tokens. The game gets confused and crashes. I don't think the game logic knows how to handle having multiple focus tokens when it tryies to create the multiple option choices for the dice modification sub phase of of combat for the moldy crow.

I say this because I also tried with 1 focus token, and no bug occurred. NULL reference only happens if the moldy crow goes into combat with 2 or more focus tokens. 

**Reproduce:**
It took me some time to figure out, but once I narrowed it down, this bug is fairly easy to reproduce. Reproducible on all pilots for hwk while moldy crow is attached. Rebel and Scum.

**Comment by NickyDaB** [comment]
I think in this function:

**Scripts/View/Combat.Combat.cs**

```
    public static void ShowDiceModificationButtons()
    {
        Selection.ActiveShip = (AttackStep == CombatStep.Attack) ? Attacker : Defender;

        AvailableDecisions = new Dictionary<string, ActionsList.GenericAction>();
        Selection.ActiveShip.GenerateAvailableActionEffectsList();

        float offset = 0;
        Vector3 defaultPosition = GameObject.Find("UI/CombatDiceResultsPanel").transform.Find("DiceModificationsPanel").position;

        foreach (var actionEffect in Selection.ActiveShip.GetAvailableActionEffectsList())
        {
            AvailableDecisions.Add(actionEffect.Name, actionEffect);

            Vector3 position = defaultPosition + new Vector3(0, -offset, 0);
            CreateDiceModificationsButton(actionEffect, position);
            offset += 40;
        }

        ToggleConfirmDiceResultsButton(true);

        Button closeButton = GameObject.Find("UI/CombatDiceResultsPanel").transform.Find("DiceModificationsPanel/Confirm").GetComponent<Button>();
        closeButton.onClick.RemoveAllListeners();
        closeButton.onClick.AddListener(Combat.ConfirmDiceResults);

        GameObject.Find("UI/CombatDiceResultsPanel").gameObject.SetActive(true);
    }
```

I think the problem is that it creates multiple dictionary records with the name "focus".  We might be able to add a check here to see if a "focus" already exists, and if it does, then do not try to add a second focus. 

I will try on my branch to see if this can help the issue.

**Comment by Sandrem** [comment]
In previous version only 1 token object was present and had "count" variable inside.
In current version each token has own object.

Maybe it is even better to skip extra action effects not in dialog window, but in GenericShip class, where it generates list of available action effects from assigned tokens.

**Comment by Sandrem** [comment]
See GenericShipActions.cs -> GenerateAvailableActionEffectsList

**Comment by Sandrem** [comment]
I don't remeber a way to use two same dice modifications.
So, AddAvailableActionEffect can add deice modification to list only if there is no same type of dice modification inside this list.

I don't plan to fix this bug in the nearest week, so if you have free time - you can fix it by yourself, it seems to be simple.

**Comment by NickyDaB** [comment]
I'll work on it. I have a fix for the NULL exception on my branch. And I will look into making a function that only returns tokens that can be used during the dice modification sub phase of combat and only one of each token, as to avoid duplicates.

**Comment by NickyDaB** [comment]
I'll make a pull request with the updates within 24 hours.

**Comment by Sandrem** [comment]
Fixed. Thank you for help.
