### ISSUE TITLE
HLC is able to roll crits

### ISSUE THREAD

**Issue by NickyDaB** [Sandrem/FlyCasual#591]
on the card it says change crits to regular hits. In game, we leave crits alone. So therefore it is possible to roll crits with the heavy lazer cannon. 

Reproducible: 
Yes, about 1/8 chance per dice rolled while HLC is attached to ship. Try to reproduce with a Dash HLC build.

**Comment by Sandrem** [comment]
Ability was not assigned to UpgradeAbilities - fixed in "Bombs" branch.
