### ISSUE TITLE
PtL + BB8 issue

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#597]
When using BB8 + PtL, if you "skip" the PtL free action after the BB8 barrel roll, you aren't asked for using PtL after the regular action.

**Comment by rats3g** [comment]
The issue appears to be with the [CheckConditions](https://github.com/Sandrem/FlyCasual/blob/7381d384c171ea2f43e7c98cd22eaf60ab979105/Assets/Scripts/Model/Upgrades/Elite/PushTheLimit.cs#L31) function for PtL. 

`private void CheckConditions(GenericAction action)
        {
            if (!IsUsed)
            {
                //IsUsed = true;
                Host.OnActionDecisionSubphaseEnd += DoSecondAction;
            }
        }`

PtL is marked as used the first time the player is given the option to use it regardless of if the player actually chose to take the extra action.

**Comment by Sandrem** [comment]
@rats3g You are right. If you want to help in development, you can also fix this =)
Otherwise I will fix it next week.

**Comment by rats3g** [comment]
@Sandrem I'm taking a crack at it right now. Whether the PtL action is taken or skipped OnActionIsPerformed gets fired. This causes a circular loop of PtL action being offered, skipped, and then because the PtL action was "performed" (even though not actually taken) offered again.

**Comment by Sandrem** [comment]
1) See AddStressToken - token is assigned only if second action was really taken. If second action was skipped - no stress is assigned.
2) IsUsed must be checked in two places. In CheckConditions (as regular check). And in PerformPushAction (in case if new trigger is fired before old one is finished with "isUsed = true")

I hope these tips will help you =)

**Comment by Sandrem** [comment]
@rats3g (Notification in case if my previous comment doesn't have notification)

**Comment by rats3g** [comment]
@Sandrem Reverting IsUsed to false if the action was skipped ends up being the simplest solution currently. I'll do some more testing to make sure it doesn't break anything. Timings can be finicky. Probably want to take a look at how actions and free actions are triggered though. Would be better to be able to declare the result of an action (taken/skipped) only call OnActionIsPerformed based on that.

I noticed PtL is implemented using the obsoleted AttachToShip so I'll probably refactor PtL to use UpgradeAbilities.Add before putting up the PR.

Thanks for your help BTW :)

**Comment by Sandrem** [comment]
This part of code is old, I plan to refactor it somewhere in 0.4.3 or 0.5.1
For example, source of actions are not mentioned, so condition "from action bar" is not working at the moment.

If you want to participate in development, then we have Slack workspace (~20 developers), you are welcome: https://join.slack.com/t/flycasualgame/shared_invite/enQtMjk2OTY2Nzc4NDE3LTY0OGM0OTg0MjE5YTgxYzcwYjY0MzVhY2E2NjliNWVjMDAyYjA0NTA3NjQzMTYwYTgwNTk1YmIyMzY4ZGFjNTc

**Comment by Sandrem** [comment]
@rats3g I agree, event/trigger can be avoided if action is skipped - this fix is easy too. See what happens of if Skip button is pressed (method of active SubPhase) and what value is passed to method where event+trigger is called.  Seems that after this change flag "IsFreeActionSkipped" can be removed too.

Also see comment above =)

**Comment by rats3g** [comment]
I have a PR (#599) up for this issue.

**Comment by Sandrem** [comment]
@rats3g Thank you for help =)
Bug is fixed.
