### ISSUE TITLE
Combat will not move to next ship

### ISSUE THREAD

**Issue by Jon-Pin** [Sandrem/FlyCasual#600]
I have encountered this issue a few times when using Torani Kulda. After his attack, the combat does not move to the next ship, and keeps asking for "Player: 1, Pilots with Skill: 8". Whenever I try to click on another ship, it keeps telling me that "Ship Cannot Be Selected". The game will not move forward and needs to be quit to main menu.

**Comment by Sandrem** [comment]
Torani Kulda is controlled by player or AI?

**Comment by Jon-Pin** [comment]
Torani Kulda is controlled by player, versus AI opponent

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3
If you will encounter this bug in 0.4.3 or later again - inform me.
