### ISSUE TITLE
Range ruler not going away after firing

### ISSUE THREAD

**Issue by ScottKarch** [Sandrem/FlyCasual#602]
the range ruler stays visible after combat and into the next planning phase.  Assuming it should go away after your attack when you measured.
![range ruler](https://user-images.githubusercontent.com/19825797/36042540-c82de244-0d91-11e8-90c2-ee8ac25cc601.png)

**Comment by ScottKarch** [comment]
I may be able to help with graphics models or skins.  Let me know.   scott@karchfamily.com

**Comment by Sandrem** [comment]
This part of game will be rewritten in 0.5.0.
