### ISSUE TITLE
Starwing in Assault Config  cannot choose secondary weapons

### ISSUE THREAD

**Issue by IndyHan** [Sandrem/FlyCasual#610]
In this build I could not use any secondary weapons on the start wing.

{"name":"StarwingAggressors","faction":"imperial","points":100,"version":"0.3.0","pilots":[{"name":"majorvynder","points":39,"ship":"alphaclassstarwing","upgrades":{"title":["os1arsenalloadout"],"mod":["longrangescanners"],"torpedo":["extramunitions"],"missile":["clustermissiles","clustermissiles"],"ept":["saturationsalvo"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Alpha-class Star Wing"}}},{"name":"sienarspecialist","points":28,"ship":"tieaggressor","upgrades":{"mod":["engineupgrade"],"turret":["dorsalturret"],"missile":["clustermissiles"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}},{"name":"onyxsquadronescort","points":33,"ship":"tieaggressor","upgrades":{"mod":["engineupgrade"],"turret":["dorsalturret"],"missile":["clustermissiles","cruisemissiles"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}}],"description":"Major Vynder + Os-1 Arsenal Loadout + Long-Range Scanners + Extra Munitions + Cluster Missiles + Cluster Missiles + Saturation Salvo
Sienar Specialist + Engine Upgrade + Dorsal Turret + Cluster Missiles
Onyx Squadron Escort + Engine Upgrade + Dorsal Turret + Cluster Missiles + Cruise Missiles"}

I am go happy with this in general and I love the game so much. Thanks for doing such a great job.

**Comment by Sandrem** [comment]
I cannot reproduce this problem.
Please, next time make a screenshot. And check range and tokens.

**Comment by Sandrem** [comment]
Still cannot reproduce.
