### ISSUE TITLE
debug crash after a ship was destroyed..  

### ISSUE THREAD

**Issue by ScottKarch** [Sandrem/FlyCasual#611]
After a ship was destroyed, some red text came on the screen...      I was playing over the LAN with my son. 

![crash1](https://user-images.githubusercontent.com/19825797/36078458-2e1348a0-0f3c-11e8-8588-cf5a054c96d4.png)
![crash2](https://user-images.githubusercontent.com/19825797/36078459-2e206abc-0f3c-11e8-93ea-0592ff842062.png)

**Comment by ScottKarch** [comment]
but.. I have to say the game was working great up to that point..  multiple crews, ionization, tactician, lohrick AP5     Everything was working perfectly.  It goes so quickly it's incredible..  Whoever came up with the barrel roll animation   BRAVO!!!

**Comment by Sandrem** [comment]
This part of game was updated in 0.4.2
If this error will be present in 0.4.2 - please, report this issue again.
