### ISSUE TITLE
The dog (ARC)

### ISSUE THREAD

**Issue by Bartelectro** [Sandrem/FlyCasual#621]
The bow of fire of the dog, is bad since it only shoots by the main one and not by the auxiliary.

**Comment by Sandrem** [comment]
Please, clarify - what ship does have problem? I don't know the ship what is called "The dog".

**Comment by Bartelectro** [comment]
sorry,  es el YV-666, el arco auxiliar .

**Comment by Sandrem** [comment]
I cannot reproduce this problem.
Please, next time attach screenshot with problem.

**Comment by Sandrem** [comment]
This part will be rewritten in 0.5.0, old bugs are not actual anymore.
