### ISSUE TITLE
Model not removed

### ISSUE THREAD

**Issue by rats3g** [Sandrem/FlyCasual#626]
After being destroyed by the area damage of a Harpoon missile Kylo (TIE Silencer) was not removed from the board. He also still moves even though his shields and hull clearly show 0. After firing again, however, he was finally removed from the board.

![harpoonbug](https://user-images.githubusercontent.com/4007006/36284994-eae2f56e-1277-11e8-8562-6f1bce043907.png)

**Comment by Sandrem** [comment]
Fixed
