### ISSUE TITLE
Crash when resolving harpoon condition

### ISSUE THREAD

**Issue by rats3g** [Sandrem/FlyCasual#629]
Asajj had previously received the Harpoon condition. After selecting the resolve harpoon condition action and successfully rolling the resolve the game crashed. 
![image](https://user-images.githubusercontent.com/4007006/36330040-22ed7b64-1336-11e8-86bd-835ddc6841fc.png)
[harpoonconditionbug.txt](https://github.com/Sandrem/FlyCasual/files/1732882/harpoonconditionbug.txt)

**Comment by Sandrem** [comment]
Fixed
