### ISSUE TITLE
Quickdraw ability activated twice in turn

### ISSUE THREAD

**Issue by rats3g** [Sandrem/FlyCasual#630]
Steps:

1. Quickdraw fires at Dash
2. Poe fires at Quickdraw dealing two damage
3. Quickdraw's ability activates and fires again at Dash
4. Quickdraw's ability is still available and can fire again at Dash

After firing the third time the game crashed.

![quickdrawtripleattackbug](https://user-images.githubusercontent.com/4007006/36331021-2eb74a3e-133a-11e8-9b21-4f6d5a58af9e.png)
[quickdrawtripleshotcrash.txt](https://github.com/Sandrem/FlyCasual/files/1732936/quickdrawtripleshotcrash.txt)

**Comment by Sandrem** [comment]
Fixed
