### ISSUE TITLE
Crash when Harpoon effect activates

### ISSUE THREAD

**Issue by rats3g** [Sandrem/FlyCasual#633]
![harpoonbug](https://user-images.githubusercontent.com/4007006/36333545-7473c812-1345-11e8-9698-82ae37269ccd.png)
[harpoonexplosionbug.txt](https://github.com/Sandrem/FlyCasual/files/1733097/harpoonexplosionbug.txt)

**Comment by Sandrem** [comment]
VCX-100 tries to perform second attack, but is already destroyed - fixed
