### ISSUE TITLE
VCX / Ghost ... docked ship doesn't (allow to) undock after it's carrier has been destroyed.

### ISSUE THREAD

**Issue by OnlyOneD** [Sandrem/FlyCasual#636]
Not much else to say, rules (in the Ghost manual, 3rd 'page') says:
"If the carrier ship flees the battlefield, it and all its docked ships are destroyed. If the carrier ship is destroyed (but has NOT fled the battlefield), before it's removed from the play area, each docked ship receives 1 facedown Damage card and must immediately DEPLOY. Ships deployed in this fashion cannot attack until the following round."

Game asks for 'wanna deploy' every round, but not when shipped is destroyed...

Easy to reproduce: take a Ghost with an Attack Shuttle (didn't check Sheathipede yet) against a bunch of enemies and skip your shooting phases...

Saw it first in AI vs AI, but Player vs AI doesn't give option either ... it's not a may, but a must, the Hound/YV-666 probably has same lack of feature, although it says on *Hounds Tooth card: 
"YV-666 only. Title.

After you are destroyed, before you are removed from the play area, you may DEPLOY the /Nashtah Pup/ Pilot.

It cannot attack this round."
Haven't check the YV-666/ Hound though...

**Comment by Sandrem** [comment]
Fixed
