### ISSUE TITLE
4.1: Game crashes unexpectedly after resolving attack dice roll in online game

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#638]
I was not a host at both times the crash occured

![bug-ion-cannon](https://user-images.githubusercontent.com/35771439/36356132-b0affbda-14ed-11e8-90ce-5c1aea555a43.png)

![bug2](https://user-images.githubusercontent.com/35771439/36356134-c0d0b234-14ed-11e8-8985-94f8ad9db77a.png)

**Comment by Sandrem** [comment]
Second screenshot - I changed synchronization of order of cards in decks, so second bug is not actual anymore.

First screenshot has same error as in #566 - I will close this issue as a duplicate.
