### ISSUE TITLE
4.1: Online game crashes when Garvin Dreis (X-Wing) uses his ability in defence

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#639]
This crash occured to me twice in a row. My opponent had Garvin Dreis as a pilot. At both times the game crashed while he used focus at defending himself. It happend when his ability triggerd. While he was attacking however, there was no problem.

![bug](https://user-images.githubusercontent.com/35771439/36356199-9b55de52-14ee-11e8-9c79-70a460e94cd5.png)

**Comment by Sandrem** [comment]
Fixed
