### ISSUE TITLE
4.1: In online game while not being a host, dice reroll is buggy

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#640]
Occurs if you are not a host of the online game, and if you have a focus token and a possibility to reroll your dice. The dice is mostly being rerolled before you choose it, and then the choose options are there above the focus option. You need to press OK in order to be able to click on focus. I could make a screenshot if you need it...

**Comment by HooliganTron** [comment]
Can confirm this is an issue still.  Using Predator as a player that joined a game.  The buttons to choose what dice are to be rerolled are jarbled and before you can select them the dice are rerolled for you.

**Comment by Sandrem** [comment]
Fixed
