### ISSUE TITLE
0.4.1: Online game crash report - Barrel roll and cluster mines

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#644]
While executing a 3 bank right manuver, my TIE Defender got over a cluster mine token and sufferd damage. After that I barrel-rolled him. Directly after the barrel-roll animation the following crash occurred:

![image](https://user-images.githubusercontent.com/35771439/36385063-bf6a0c3e-1591-11e8-87eb-7644038cae13.png)

**Comment by Sandrem** [comment]
I made some fixes in Cluster Bombs + Extra Munitions interaction.
If this bug will be encountered in "0.4.2 Hotfix 1" - let me know.
