### ISSUE TITLE
0.4.1: Online game sometimes gets stuck after executing a movement and before offering the actions

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#647]
Here I did 3 bank right with falcon and after clicking no to rotate it got stuck without offering me the action bar:
![image](https://user-images.githubusercontent.com/35771439/36479702-e72e3ab4-1709-11e8-872c-ec9220c70e7e.png)

Here, I moved my TIE/fo fighter and it got stuck without offering me the action bar:
![image](https://user-images.githubusercontent.com/35771439/36479743-0dd41ed6-170a-11e8-9a1a-cf3e4294ba14.png)
It seems that here it could have been a problem if the TIE is overlapping the asteroid (distance = 0, but no overlap)

**Comment by Sandrem** [comment]
I changed how abilities "after you execute a maneuver" synchronized, so, I hope, this problem is fixed too.
(I will check how positions of ships are synchronized, maybe this causes desynchronization too)
