### ISSUE TITLE
ClusterMineCrash

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#650]
Beta4.2 Crash upon ClusterMine Detonation 
![image](https://user-images.githubusercontent.com/34241206/36566355-195e199a-17d8-11e8-90f4-38c2a3969fb1.png)

**Comment by Sandrem** [comment]
I made some fixes in Cluster Bombs + Extra Munitions interaction.
If this bug will be encountered in "0.4.2 Hotfix 1" - let me know.
