### ISSUE TITLE
win4.2 restart crash

### ISSUE THREAD

**Issue by RJAGame** [Sandrem/FlyCasual#651]
New Version4.2 crashes  with Restart. 
![image](https://user-images.githubusercontent.com/34241206/36616122-755cb782-1897-11e8-8c7f-873d3562b280.png)
![image](https://user-images.githubusercontent.com/34241206/36616160-9cb8a246-1897-11e8-8a05-3d87d0f4df63.png)

**Comment by Sandrem** [comment]
The same bug as in beta https://github.com/Sandrem/FlyCasual/issues/649

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3 anymore.
