### ISSUE TITLE
0.4.2 online: Game crash at setup forces

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#653]
![image](https://user-images.githubusercontent.com/35771439/36630355-6c57dbc0-1965-11e8-899e-c2ad96e5b4a6.png)

When you want to setup forces you move unintentionally enemy fighters or the enemy yours. Then the game crashes...

**Comment by Sandrem** [comment]
I am not sure, but seems that opponent used more old version of game - and this bug is because differences between versions.
I will add version validation starting "0.4.2 Hotfix 1". If you will see same bug again in "0.4.2 Hotfix 1" or later - inform me again.
