### ISSUE TITLE
AI: Can use Sensor Jammer while has TL from Omega LEader

### ISSUE THREAD

**Issue by ve2dcr** [Sandrem/FlyCasual#655]
When you use Sensor Jammer, the OK button is not visible and therefore you cannot continue.

**Comment by ve2dcr** [comment]
and AI can use Sensor Jammer against Omega Leader even when Omega Leader has a target lock

**Comment by Sandrem** [comment]
Fixed

**Comment by ve2dcr** [comment]
AI can still modified dice against Omega Leader!

**Comment by Sandrem** [comment]
I will check

**Comment by Sandrem** [comment]
Fixed
