### ISSUE TITLE
0.42 TLT firing two shot (four times total)

### ISSUE THREAD

**Issue by ve2dcr** [Sandrem/FlyCasual#656]
When you use the TLT, you sometime fire it twice (four shot total) (not counting the attack shuttle title)

**Comment by Sandrem** [comment]
I cannot reproduce this problem.
Please, next time provide video with problem or, at leasr screenshot - to see squad lists.
Maybe, Gunner was present...

**Comment by Sandrem** [comment]
Still cannot reproduce
