### ISSUE TITLE
Double-cloaked ships bug

### ISSUE THREAD

**Issue by BladeSplint** [Sandrem/FlyCasual#658]
After cloaking, phantoms are listed as having two separate cloaks (Decloak and Decloak #2) and are given the option to decloak twice sequentially. Advanced cloaking device sometimes does not result in a TIE Phantom cloaking.

https://imgur.com/a/gcNod

**Comment by Sandrem** [comment]
Cloak feature will be rewritten n 0.5.0 - old bugs are not actual anymore.
