### ISSUE TITLE
The Inquisitor is not removed when destroyed

### ISSUE THREAD

**Issue by Jon-Pin** [Sandrem/FlyCasual#659]
I have just played 2 games in a row against the AI, and in both games The Inquisitor was destroyed but not removed from the game. The ship continued to move, take actions and attack as normal. I even tried attacking it again to see if it would remove the ship, but it just kept going.

**Comment by Sandrem** [comment]
Please, next time post screenshot or squad lists too.
Do you remember how The Inquisitor was killed the first time? Simultaneous attack rule? Splash damage from harpoons? Mines? Another reason?

**Comment by Jon-Pin** [comment]
Hi Sandrem, it happened in a different game with a different ship as well. This time it was one of my ships that carried on after being destroyed.
I think it could possibly have something to do with the simultaneous attack rule? I only ever encounter the problem when there are ships of the same skill value on either side.
The screenshots are below.
![fly casual - screenshot](https://user-images.githubusercontent.com/36263374/36678919-e400d94c-1b09-11e8-9b86-22b21792de86.jpg)
![fly casual - screenshot 1](https://user-images.githubusercontent.com/36263374/36678929-eab09ad4-1b09-11e8-9efe-810a16b55100.jpg)

**Comment by Sandrem** [comment]
Thank you for information. Yes, I think that this is bug in simultaneous attack rule.
I plan to release hotfix in few days.

**Comment by Jon-Pin** [comment]
Ok. Just want to say that this is project is awesome by the way. Thanks!

**Comment by Sandrem** [comment]
Fixed in hotfix, update will be released soon.
