### ISSUE TITLE
Nu's not removed after simultaneous fire rule 

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#660]
All ships are PS 2.   The Tie Advanced had initiative.   Nu's were destroyed in a blaze of glorious fire and got to return fire that round.....but then they stayed at zero health until the game crashed.    Have duplicated this error twice.
Screenshot attached!
![nus bug](https://user-images.githubusercontent.com/35663377/36703468-c7bb793e-1b29-11e8-8c83-039c1f28ad42.JPG)

**Comment by Sandrem** [comment]
Bug of simultaneous fire rule, will be fixed in hotfix soon.

**Comment by Sandrem** [comment]
Fixed in hotfix, update will be released soon.
