### ISSUE TITLE
Crash using 3 specific ships - Asajj, Scurrg w Tactician, Kimogila

### ISSUE THREAD

**Issue by jasonukim** [Sandrem/FlyCasual#661]
Hi I get the following crash every time I try to play this squadron:

Asajj /w Razzi, 2x Glitterstim, Countermeasures
Karthak pirate Scurrg /w Tactician, Long-range Sensor
Generic pilot (3 PS) Kimogila /w Long-range Sensor 

I've tried this squad maybe 3-4 times and all of them crash. The below time was right after Asajj moved. 

I have a hunch that the crash has to do with the Kimogila with long-range sensors b/c I've been able to use Asajj and the Scurrg with the same loadouts in other squads with no issues.  

![bug](https://user-images.githubusercontent.com/22421295/36715461-5222d272-1b64-11e8-8cb8-fd0c1a1159fd.png)

**Comment by Sandrem** [comment]
Problem was in Asajj's ability. If you skip it - then you still see "Skip ability" button, but current subphase is "select order of triggers". Visible "Skip" button had wrong effect and caused bug if pressed again.

Fixed in hotfix.
