### ISSUE TITLE
0.42 Destroyed ships will not removed if they were destroyed by a ship with same pilot value.

### ISSUE THREAD

**Issue by FMJFirebird** [Sandrem/FlyCasual#664]
Next try: I'll know the "Simultaneous Attack Rule" from the basic XWing rules but in this case, the destroyed ship isn't removed from the game at the start of the next round.
I could reproduce this issue by using only jumpmaster contract scouts on both sides: After destroying an enemy jumpmaster, he could fight back, but will not removed after the combat phase. In attached screenshot, Vessery "destroyed" the IG-88c aggressor (both pilots got a value of 6 and the aggressor has 0 shields and 0 hull points) but the screenshot was taken at the beginning of the next planning phase. Looks like a missing "remove destroyed ships" action after combat phase...
![enemystay](https://user-images.githubusercontent.com/36896583/36756885-90c1ec46-1c10-11e8-98f9-08d85990f199.png)

**Comment by Sandrem** [comment]
Fixes. Hotfix will be released in a half of hour =)

**Comment by FMJFirebird** [comment]
Great! That was fast... *thumbup*

**Comment by Sandrem** [comment]
https://github.com/Sandrem/FlyCasual/releases/tag/0.4.2.1
