### ISSUE TITLE
0.4.2.1 Game Crash

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#665]
Boba attacked my Poe. I saw no defense dice throw, lost two shields on Poe and this crash occured:

![image](https://user-images.githubusercontent.com/35771439/36759895-2d920454-1c19-11e8-83da-285e856a07c4.png)

**Comment by Sandrem** [comment]
Did you host a room or joined room?

**Comment by zdravkotatic** [comment]
I think that this asteroid layout is there when you host the game. (It is a screenshot from my side of view). So I would say that I have hosted...

**Comment by zdravkotatic** [comment]
Here I was the host again in 0.4.2.h2

![image](https://user-images.githubusercontent.com/35771439/36805390-9909a5c6-1cbd-11e8-85ec-49e13af23af4.png)

**Comment by zdravkotatic** [comment]
In both games my squad list was the following:

{"name":"EX+X+","faction":"rebel","points":100,"version":"0.3.0","pilots":[{"name":"jesspava","points":26,"ship":"t70xwing","upgrades":{"mod":["integratedastromech"],"amd":["flightassistastromech"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Blue"}}},{"name":"poedameron","points":35,"ship":"t70xwing","upgrades":{"mod":["integratedastromech"],"amd":["r5p9"],"ept":["wired"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Black One"}}},{"name":"corranhorn","points":39,"ship":"ewing","upgrades":{"amd":["r2d2"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Green"}}}],"description":"Jess Pava + Integrated Astromech + Flight-Assist Astromech
Poe Dameron + Integrated Astromech + R5-P9 + Wired
Corran Horn + R2-D2"}

**Comment by Sandrem** [comment]
0.4.3.1 will have bugfixes for such situations.
I close old issues with such problems. If you will see such bugs again in 0.4.3.1 - report them again.
