### ISSUE TITLE
AI: Accuracy Corrector dice modification is activated even when better result is present

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#667]
Dunno if you can fix this one but I've noticed that the A.I will use Accuracy Corrector after it's either used a guidance chip for 3 hits, rolls 3 natural hits or when it rolls a natural hit and a crit......   It's like it just uses AC just to use it even though it hurts its attack.

**Comment by Sandrem** [comment]
Please, next time create correct name for issues. I am too busy for jokes =)

**Comment by Sandrem** [comment]
Fixed in "0.4.2 Hotfix 2", update will be released soon.
