### ISSUE TITLE
0.4.2 Garven Dreis Pilot ability Crashes Games

### ISSUE THREAD

**Issue by RiffGit** [Sandrem/FlyCasual#668]
![image](https://user-images.githubusercontent.com/36906206/36765362-b565435a-1c28-11e8-8e19-59190543200f.png)
On selecting the friendly to assign the focus token to this happens.

**Comment by sandro1337** [comment]
Same issue but only when the ability is used for the second time in the same turn
![garvensecondtokylekatarn](https://user-images.githubusercontent.com/37774975/37876022-6594865a-3047-11e8-8750-053a05b6e88b.png)

**Comment by Sandrem** [comment]
Fixed
