### ISSUE TITLE
Game Crash - unknown reason

### ISSUE THREAD

**Issue by HooliganTron** [Sandrem/FlyCasual#670]
Dengar finishes performing an attack on generic punisher and the game crashed.  I hosted as player 1.
![picture1](https://user-images.githubusercontent.com/36909386/36769514-47a7cfcc-1c0a-11e8-9328-18ed845d5c98.png)

**Comment by Sandrem** [comment]
Counter-attacks of Dengar and Quickdraw have bugs in "0.4.2 Hotfix 1".
Fixed, "0..4.2 Hotfix 2" will be released soon.
