### ISSUE TITLE
Game Hangs when AI would move off the map

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#671]
When AI makes a move that would take the ship off the map, the game just hangs and the ship wont execute the maneuver.   Should be easy to replicate doing an AI vs AI game with Tie Bombers or Punishers.   Duplicated the issue about 4 or 5 times in a row that way.

**Comment by OnlyOneD** [comment]
Was about to report same...easiest to reproduce with 8vs8 swarms in AI vs AI game mode. It seems to keep trying to find alternate routes, while every options will make it go off the board, and goes into an endless loop. The game doesn't really hang though, it's just very slowly, like when it's making decisions. One can still end game, hover over, click stuff etc.

![endless loop](https://user-images.githubusercontent.com/35881257/36779188-7975087a-1c6f-11e8-8715-38dc4a7a307c.jpg)

I used 8 z-95 vs 8 TIE-Fighters for testing.

**Comment by Sandrem** [comment]
Fixed in "0.4.2 Hotfix 2", update will be released soon.
