### ISSUE TITLE
0.4.2 TIE/D AI ships not taking follow up shot

### ISSUE THREAD

**Issue by Kelbesq** [Sandrem/FlyCasual#673]
When playing against a TIE Defender with the TIE/D title, the AI is not using it's follow up primary attack after it's cannon attack.   The UI is showing a message indicating that the follow up attack can occur, but it is not being performed.

I have only personally seen this with Colonel Vessery and an Ion Cannon, but I have not done extensive testing.

**Comment by Sandrem** [comment]
This is for all "additional attack" abilities, will be improved later.

**Comment by Sandrem** [comment]
I close this issue as not a bug. Support of second attack will be added for AI in one of next updates.
