### ISSUE TITLE
Turreted ships sometimes don't make primary weapon attack

### ISSUE THREAD

**Issue by macduffman** [Sandrem/FlyCasual#674]
First of all, awesome work! Now, I've noticed this issue when playing the AI with Miranda Doni or with a Y-Wing. If I load the AI's ship with a Twin Laser Turret, and the AI finds itself at range 1, it will (of course) not take the TLT shot, but it also does not take a primary weapon shot. See screenshot. We just finished combat. Kylo Ren is in arc and at range 1 of the Y-Wing to his right, but the AI did not take a shot.

I notice this maybe once every few games. Please let me know if there is further information I can provide. This project is fantastic!

![tlt](https://user-images.githubusercontent.com/36932602/36809010-c1f61a6a-1c94-11e8-9b10-1409012a8b34.jpg)

**Comment by Sandrem** [comment]
Thank you, I have enough information, I will check.

**Comment by Sandrem** [comment]
Was fixed
