### ISSUE TITLE
0.4.2.H2 Online: Harpooned! Splash damage crash

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#675]
In an online game, I was the host and have Harpooned enemy B-Wing. It went on purpose through an asteroid to my fighters in order to deal them splash damage. It got a crit on the asteroid and has lost his last hull on that asteroid. The B-Wing has exploded and the game crashed with the following crash:

![image](https://user-images.githubusercontent.com/35771439/36813256-40f08fa0-1cd4-11e8-9b95-996e3a533217.png)

On a game before the enemy had two B-wings next to each other. I Harpooned one of them and on the next turn hit the other one with a crit, but the first one triggerd his Harpooned! splash though he wasn't hit.

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3.1 - seems that this bug is fixed.
