### ISSUE TITLE
Fleeing the battlefield 4.2 H2

### ISSUE THREAD

**Issue by FlashBackJack** [Sandrem/FlyCasual#677]
Hi 

5 AI vs AI games 
3/5 large ships  Upsilon, decimator, ghost all move close to the edge 
next move they move outside the table boundary and return to the table 
they should flee and be counted as a loss 
in 1 game the decimator left the field 5 times and returned 

thanks

Great work 

FBJ

**Comment by zdravkotatic** [comment]
@FlashBackJack Are you aware that leaving the battlefield only counts if the base position after the movement is out of the field? So if you move with the turn template, the animation will show you flying out and back in and that would be legal. But if ship really had his base outside the field after executing a move, then it is a bug.

So, which one of these two cases was it?

**Comment by FlashBackJack** [comment]
Hey 
yep i know it has to be when the ship completes its movement phase
thats not the case here 
its not by much but they are over the line after movement phase 
i'll try and get a photo next time it happens 
FBJ

**Comment by Sandrem** [comment]
Cannot reproduce.
When you will encounter this bug again - please, provide screenshot.

**Comment by Sandrem** [comment]
Fleeing the battlefield will be updated in 0.5.0 - old bugs are not actual anymore.
