### ISSUE TITLE
0.4.2 Structural Damage Card reduces ships agility by 2

### ISSUE THREAD

**Issue by EL-BASTIDO** [Sandrem/FlyCasual#678]
Whilst playing versus AI, Corran Horn deals the Structural Damage card to Asajj Ventress.  This should reduce  her agility to one, but here it is reduced to zero. 
![capture](https://user-images.githubusercontent.com/36958116/36846092-25ad7712-1d51-11e8-931d-e6ebc6144747.PNG)

**Comment by Sandrem** [comment]
Fixed
