### ISSUE TITLE
R2D2 when landing on a rock

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#680]
Landing on a rock prevents the trigger of R2D2 when using a green manoeuver.

**Comment by Sandrem** [comment]
Cannot reproduce in current build.
When ship doesn't have a shield, has R2-D2, executes green maneuver and landed on asteroid - shield is restored.

Also:
> If a ship equipped with R2-D2 executes a green maneuver and its base or maneuver template overlaps an obstacle token or its base overlaps a ship equipped with Anti-Pursuit Lasers, that ship recovers 1 shield before rolling for damage. (X-Wing FAQ, Version 3.1.1, Updated 07/24/2015)

**Comment by Sandrem** [comment]
I close this issue. Please, check again after release of 0.4.3
