### ISSUE TITLE
"Restart" option makes the simulator crash

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#681]
Happened a few times today, seems to be quite often when the total number of ships reaches 7 or more.

**Comment by Sandrem** [comment]
Did you see opened console with red text?

**Comment by Giledhil** [comment]
![sans titre](https://user-images.githubusercontent.com/30911713/36848932-fd4dc1e8-1d62-11e8-943c-545000f122a7.jpg)

**Comment by Sandrem** [comment]
Thank you, it is hard to fix bugs without such information.
Please, always post screenshot with red text and squad lists/situation on the board - this can help a lot.

**Comment by Palandar** [comment]
Same issue. Here is the red text. 
![image](https://user-images.githubusercontent.com/36962263/36852830-cf145152-1d3a-11e8-8cfe-b3825817243f.png)

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3 anymore.
