### ISSUE TITLE
0.4.2.h2 online turn of Countess Ryad breaks the game

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#685]
I was the host, my opponent had Countes Ryad. He flew 5 straight and made the turn. The game crashed:
![image](https://user-images.githubusercontent.com/35771439/36858627-ea48938e-1d7b-11e8-95c4-e120554e8901.png)

**Comment by Sandrem** [comment]
Problem was in TIE/x7 title. Question about token was shown before ship's movement was finished on other device. So if owner pressed decision-button very fast - synchronization was failed.

Fixed!
