### ISSUE TITLE
Kylo Ren's I'll Show You the Dark Side assigning different cards

### ISSUE THREAD

**Issue by macduffman** [Sandrem/FlyCasual#687]
Thank you for giving us Kylo Ren. I've been trying him out and he's a lot of fun. Sometimes the damage card assigned by his pilot ability is not the one that I selected. Most of the time, it is another Pilot damage card. However, just now it assigned Direct Hit.

In the screen grab you can see that Kylo Ren has taken 1 damage. It was dealt by Han Solo. I'll Show You the Dark Side was assigned to Han Solo and I think I selected Stunned Pilot. Next, the Admiral hit Han with a crit. I'll Show You the Dark Side triggered, but it assigned Direct Hit, as you can see by my mouse hovering over the crit. No other crits have been dealt to Han Solo.

Please let me know if I can provide more information. Thank you for all your work.

![image](https://user-images.githubusercontent.com/36932602/36810080-c715e432-1c97-11e8-831b-54b61b0926ca.png)

**Comment by Sandrem** [comment]
Fixed
