### ISSUE TITLE
Ghost/Phantom undocking issue

### ISSUE THREAD

**Issue by Bismarcksea** [Sandrem/FlyCasual#688]
When the Ghost is destroyed, it undocks the phantom and then skipped to one of MY ships to make a movement/action while still in the combat phase.   
  I made the movement and action and then the game crashed
![ghost error](https://user-images.githubusercontent.com/35663377/36888434-70faacae-1dc3-11e8-934c-36f678923535.JPG)
.   Screenshot attached.

**Comment by Palandar** [comment]
I am not crashing or getting an error but when the phantom undocks I can not attack it until it attacks me.
