### ISSUE TITLE
Fenn Rau's ability (Sheathipede) - Internet game

### ISSUE THREAD

**Issue by EL-BASTIDO** [Sandrem/FlyCasual#689]
I'm really sorry as I forgot to take screenshots last night........

However, 3 games bugged out when Rebel Fenn Rau's ability triggered.  Sometimes I didn't have the option to select whether to use it or not and other times enemy ships missed their shooting oportunity before the game eventually crashed and forced a restart.

**Comment by EL-BASTIDO** [comment]
It should be relatively easy to recreate though. :-)

**Comment by Sandrem** [comment]
Seems that bug is related to https://github.com/Sandrem/FlyCasual/issues/693

**Comment by Sandrem** [comment]
Fixed
