### ISSUE TITLE
0.4.2.h2 Wrong active player in multiplayer: Fenn Rau pilot ability

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#693]
I was the host and could choose for oponnent's Fenn Rau in an online match

**Comment by zdravkotatic** [comment]
It seems that he choose it, but I had to press on the skip button. Afterwards in that game, the game crashed with the following message:

![image](https://user-images.githubusercontent.com/35771439/36913356-f863fc8c-1e49-11e8-839b-6d36732778c4.png)

**Comment by Sandrem** [comment]
Activation of ship was not synchronized between devices.

Fixed!
