### ISSUE TITLE
0.4.2.H2: Online game breaks while skipping attack 

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#695]
I was the host in the game. The following always leads to a game jam:

Bug reproduction requirements: 
- be a host in an online game
- take two pilots of the same pilot skill (in my case 2 Rho Veteran Alpha Wings)
- be in a combat phase in which you cannot make an attack
- in their (e.g. Rho Alpha Wing) combat phase select one of them
- measure the range to one enemy fighter with the right click
- see that you cant shoot but dont try to click with a left click on that enemy fighter (it would avoid the bug)
- press skip button twice

- the game should get jammed now

![image](https://user-images.githubusercontent.com/35771439/36933580-dc8741f8-1edb-11e8-892b-22eba0a393f5.png)

If you have some questions or cannot reproduce the issue feel free to contact me.

I am the opinion that this issue makes a lot of games jam and is hard for players to understand why it occurs. It seems to be connected with the new attack system in which you cannot deselect the attacker but must skip its attack.

**Comment by zdravkotatic** [comment]
Here I reproduced the bug by playing an online match against myself with two clients:

when the joining client comes to his turn he gets the following message and no skip button:

![image](https://user-images.githubusercontent.com/35771439/36933690-b2605976-1edd-11e8-9130-05ed134d03ed.png)

**Comment by Sandrem** [comment]
Thank you for detailed bug report.

When "Skip" button is pressed and no ships are selected - activation of all ships with current PS is skipped.
When ship is selected - only activation of selected ship is skipped.

Problem: second client doesn't got information that first client selected a ship.
So, first client skips only activation of first ship, but second client skips activation of all ships with current PS.

**Comment by Sandrem** [comment]
Fixed!
