### ISSUE TITLE
0.4.2.H2: Ship destroyed by Harpoon splash not removed

### ISSUE THREAD

**Issue by Kaleidoscopio** [Sandrem/FlyCasual#696]
My ship was harpooned and was destroyed by a shot, splash damage goes out, taking the last hull point of a Firespray.
Firespray stays on table.

**Comment by zdravkotatic** [comment]
Same here:
![image](https://user-images.githubusercontent.com/35771439/37116460-af326c0c-224e-11e8-9237-bb5b9a4b6484.png)

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3.1 - seems that this bug is fixed.
