### ISSUE TITLE
0.4.2.H2 online: "I...the dark side" ability breaks the game

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#705]
The first damage in game was the crit damage on the "... dark side"-ed ship. The game crashed in two games in row on that way.

![image](https://user-images.githubusercontent.com/35771439/37062333-67ab4eca-2196-11e8-8465-7e756dc6adbe.png)

**Comment by Kelbesq** [comment]
I've seen the same error output in a vs. AI game, so I don't think this is an online specific problem.

**Comment by zdravkotatic** [comment]
In 0.4.3:
![image](https://user-images.githubusercontent.com/35771439/38459910-37d2c416-3ab0-11e8-83e7-48561d3a50b1.png)

**Comment by Sandrem** [comment]
Fixed
