### ISSUE TITLE
Double crew upgrade takes 3 crew slots on decimator

### ISSUE THREAD

**Issue by Azrapse** [Sandrem/FlyCasual#708]
The Decimator has 3 crew slots.
Death Troopers should take 2 crew slots.
Equipping Death Troopers on a Decimator consumes all 3 crew slots.

**Comment by Jimmy5910** [comment]
Reproduced with Palpatine as well. Working on a fix currently.

**Comment by Jimmy5910** [comment]
Fixed in PR #715.
