### ISSUE TITLE
Significant amount of Upgrade cards images and texts not loading

### ISSUE THREAD

**Issue by Brion1990** [Sandrem/FlyCasual#710]
Just downloaded! Super fun and helped me learn inperson X-wing play for which i am super thankful!
The issue unfortunately is this, a bunch of cards in the pregame and in-game arenas do not load images and as such is near impossible to know which cards are being selected.

Pregame --- Images do not load, particularly Modification Cards (with the exception of "counter measures", as well as large percentages of Elite Talent Cards, some title cards (like ARC-170's Alliance Overhaul), and all but the Flechette Torpedoes, the first 3 Missile cards, and some crew and astromech cards. Appears to affect All ships. All affected cards show a stock image of a blurry red "?"

In-game --- Names of blank card selected in the pregame will appear but the images and text will not appear when cursor is hovered above each card name but rather show a miniature image of the "?".

![capture](https://user-images.githubusercontent.com/37163057/37127268-0bdf49fe-2243-11e8-8c6b-aa23e92b6b15.JPG)

**Comment by Sandrem** [comment]
I cannot reproduce this problem - maybe something is wrong with Internte connection of firewall/antivirus.

Try to delete all downloaded images in "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual_ X-Wing TMG Simulator\ImageCache" and launch the game again - it will re-download images.

**Comment by Brion1990** [comment]
It worked! Thank You so Much!
