### ISSUE TITLE
Request: Heroes of Aturi Cluster ??? 

### ISSUE THREAD

**Issue by mms99br** [Sandrem/FlyCasual#711]
If you have a way to include linked stories would be great. Aturi Cluster has the system, but can be any kind of linked stories and development (there are some spin offs like Defenders of Empire and Invasion of Aturi Cluster who are great as Aturi itself).

Keep going the awesome job !!!!!

**Comment by Sandrem** [comment]
At the moment game supports HotAC AI and ships with multiple abilities from different pilots.
I like the idea to support such campaigns, and it is possible even to play coop-multiplayer and store progress on server.

But this is a huge piece of work. I will do this only if I will have enough support of community and Patreon donations.

**Comment by mms99br** [comment]
Very nice !! Thanks for the answer and congrats for the work. I wish I can help, but is above my capacity :D
