### ISSUE TITLE
Jamming Beam costs 2 squad points, but should cost 1

### ISSUE THREAD

**Issue by Kelbesq** [Sandrem/FlyCasual#713]
The card has the right value, but when I add it to my squad, it costs 2 squad points instead of 1.

**Comment by OnlyOneD** [comment]
Seems to be already updated, costs 1 point in current/dev build.

FlyCasual/Assets/Scripts/Model/Upgrades/Cannon/JammingBeam.cs 
line 17: 			Cost = 1;
