### ISSUE TITLE
Thweek mimicking Vader with Adv Sensors

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#717]
When mimicking Vader's ability with Thweek and Adv Sensors, Thweek wan't use the second action when choosing to use them before movement.

**Comment by Azrapse** [comment]
It's working as intended.
Advanced sensors explicitly states that you can do a free action, but you must skip your Perform Action step.
And Vader says that in your Perform Action step you can do two actions.
So Vader should get to do the single free action granted by using Advanced Sensors, then skip the Perform Action step. So his pilot ability doesn't trigger.
