### ISSUE TITLE
Problem with simultaneous attack - ship not removed

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#718]
Today while playing a multiplayer game, one ship (Airen Craken here) was destroyed by another of same PS (Poe). The simulator poped up a "simultanous attack" text (although Cracken had already attacked, having initiative).
Then he was removed from the game on one player's computer (the one that had Cracken in his list, player 2) but not on the other.

Next planning phase, player 2 was able to set dials, but player 1 never got to set dials, since the simulator seems to be waiting for a dial to Cracken's ship.
![sans titre](https://user-images.githubusercontent.com/30911713/37256146-08296b70-2557-11e8-8047-df66703576af.png)

**Comment by Sandrem** [comment]
Fixed
