### ISSUE TITLE
Asajj & Glitterstim use

### ISSUE THREAD

**Issue by EL-BASTIDO** [Sandrem/FlyCasual#722]
Whilst playing a game versus the AI, Asajj Ventress had an opportunity to use Glitterstim.  She had two equipped and used both in the same round.  

Is there something that could be implemented so that only one instance is used per round? 
![glitterstim](https://user-images.githubusercontent.com/36958116/37404379-98f642e8-2789-11e8-99fa-a79f171f6f1a.PNG)

**Comment by Sandrem** [comment]
AI is improved.
Now Glitterstim is not used if another Glitterstim is already active for this ship.
