### ISSUE TITLE
"Red Ace" Ability not working after he looses and regenerates shields

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#730]
I have played an online match as player 2 with red ace and r2-d2. My red ace lost his shields and then regenerated 1 shield back with r2-d2. However, he didn't get evade tokens anymore when he lost his shields on following rounds...

**Comment by zdravkotatic** [comment]
public override void ActivateAbility()
        {
            //Resets ability on round end.
            Phases.OnRoundEnd += ClearAbilityUsed;
            HostShip.OnShieldLost += RegisterCanGetEvadeToken;
        }
        private void RegisterCanGetEvadeToken()
        {
            if (IsAbilityUsed || HostShip.Shields == 0)
            {
                return;
            }
            IsAbilityUsed = true;
            RegisterAbilityTrigger(TriggerTypes.OnShieldIsLost, AssignEvadeToken);
        }

I think that if you remove " || HostShip.Shields == 0" that it would do the trick as the ability is already set on HostShip.OnShieldLost and not on damage received

**Comment by Sandrem** [comment]
Thank you, I will check this.

**Comment by Sandrem** [comment]
" || HostShip.Shields == 0" is removed.
Now evade token is assigned even if attack removed only last shield that was left.
Bug is fixed.
