### ISSUE TITLE
Jamming Beam card has wrong point value

### ISSUE THREAD

**Issue by dakoris73** [Sandrem/FlyCasual#732]
When trying to add the Jamming Beam card, it is acting as a 2 point cost upgrade, yet the card shows its only a one point cost.  I've attached screenshot for review.
[Jamming Beam Card error.docx](https://github.com/Sandrem/FlyCasual/files/1821168/Jamming.Beam.Card.error.docx)

**Comment by Sandrem** [comment]
Fixed by @Azrapse
