### ISSUE TITLE
Simultaneous kill error

### ISSUE THREAD

**Issue by Association32** [Sandrem/FlyCasual#735]
Game makes errors on simultaneous kills.

Sometimes the ship remains in play and is impossible to kill

**Comment by Sandrem** [comment]
I cannot reproduce this bug in current build.

What version do you use?
Please, next time when you will encounter this problem - provvide screenshot.

**Comment by Association32** [comment]
I play version 0.4.2
IT is VS AI

Screenshot is here:)
Taken in the planning phase
Ray kills Howlrunner (both PS 8, Ray has initiative)
Howlrunner gets the option to fire back but is not removed after that.
![sim-kill](https://user-images.githubusercontent.com/19268675/38173031-90aa8612-35b7-11e8-9cd7-2cda3982df26.png)

**Comment by sirlee** [comment]
I am also experiencing this. It seems to happen a lot from Harpoon Splash Damage. Here is the absurd situation I ended up with in my last game: (Original Squal was 4 Tie Bombers with 2 Harpoons each)

![image](https://user-images.githubusercontent.com/37704036/38470208-cbf4e318-3b5f-11e8-926b-fec01a7d13e8.png)

**Comment by Sandrem** [comment]
Fixed
