### ISSUE TITLE
Destoyed ships keeps triggering OnShipIsDestroyed events

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#737]
After a ship is destroyed I still get OnShipIsDestroyed events for the ship (all destroyed ships it seems) after another ship has been shot at. I suspect a trigger on the destroyed ship is not cleaned up properly or something

How to reproduce:
Set breakpoint in method PerformShipDestruction() in GenericShipCombat.cs
Shoot down an enemy ship (breakpoint hits, take note of the id of the ship being destroyed)
Shoot at another ship. After the combat, the breakpoint hits again even if no ships was destroyed. Id matches the destroyed ship

**Comment by Sandrem** [comment]
Cannot reproduce, maybe something is already changed.
Please, check again. If you still can reproduce - ask to reopen this issue.

**Comment by rune-b** [comment]
Still happens for me. I just killed a TIE Fighter. PerformShipDestruction event triggers as expected. Next round I shoot at other TIE fighter and do damage without killing it. After combat the breakpoint in PerformShipDestruction breaks again and the id is of the previously destroyed ship

**Comment by Sandrem** [comment]
I will re-check

**Comment by rune-b** [comment]
It seems the Trigger "Destruction of ship #N" is still triggering even after the ship has been destroyed. Do triggers have to be manually de-registered?

**Comment by Sandrem** [comment]
They de-registered when Triggers.FinishTrigger is called.
Possible reason: event that registered original trigger still register it again and again.

**Comment by Sandrem** [comment]
Not actual - this part of code was rewritten a lot.
