### ISSUE TITLE
Test pilot "Blackout" cant die in an online game

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#739]
![image](https://user-images.githubusercontent.com/35771439/37618543-e2b4969c-2bb6-11e8-8d36-804fb8097174.png)

Two games in a row I was a host, and my opponent had Test pilot "Blackout". When I destroyed him in both games the game crashed like shown in this screenshot.

**Comment by Sandrem** [comment]
Strange, I thought that such problems are caused only by Harpoon Missiles. This is something new.
Seems that this is network mode problem, not related to a specific ship.

Did you have this problem again? In network mode only, or in local mode (vs AI, hotseat) too?

**Comment by Sandrem** [comment]
Fixed
