### ISSUE TITLE
Dengar and quickdraw - simultaneous fire

### ISSUE THREAD

**Issue by Chaotix** [Sandrem/FlyCasual#742]
Dengar killed Quickdraw, who could then fire using the simultaneous fire rule, but after combat and clicking the 'ok' button on the critical card that was assigned to quickdraw, it crashed (attached).  I also believe quickdraw had a retun fire opportunity due to her pilot ability, which was never resolved due to the crash.  Dengar also died in this exchange which may trigger return fire and a simultaneous fire rule as well (LOL).
![image](https://user-images.githubusercontent.com/219529/37637912-83ef582a-2bc7-11e8-882e-32ee1c2c2325.png)

**Comment by Sandrem** [comment]
Workaround is added. Will be changed in 0.5.0
