### ISSUE TITLE
Kylo Ren condition and "skip button"

### ISSUE THREAD

**Issue by Giledhil** [Sandrem/FlyCasual#745]
In multiplayer, both players seem to have the "Skip" button for the "dark side" condition.

**Comment by Sandrem** [comment]
I cannot reproduce this.
Is Kylo pilot or crew?
If you can reproduce bug, please, attach screenshot, where another player see "Skip" button while Kylo's owner makes decisions.

**Comment by Giledhil** [comment]
It was Kylo pilot.


________________________________
De : Sandrem <notifications@github.com>
Envoyé : mercredi 4 avril 2018 11:17
À : Sandrem/FlyCasual
Cc : Giledhil; Author
Objet : Re: [Sandrem/FlyCasual] Kylo Ren condition and "skip button" (#745)


I cannot reproduce this.
Is Kylo pilot or crew?
If you can reproduce bug, please, attach screenshot, where another player see "Skip" button while Kylo's owner makes decisions.

**Comment by Sandrem** [comment]
Cannot reproduce in 0.4.3.1
If you will encounter this bug again - please, report with screenshot.
