### ISSUE TITLE
If the tractored ship dies because of obstacle damage, the game raises an exception

### ISSUE THREAD

**Issue by jamorbal** [Sandrem/FlyCasual#748]
Tractor beam with Defender title doesn't work as expected. 
-After rolling for tractor beam, it doesn't allow to take a second attack with the primary weapon.
-After tractor beam ability resolution, if the tractored ship dies because of obstacle damage, the game raises an exception. ( Console Red Message )

Config Tested: Vessery + Veteran Instincts + Tie x/1 + Tractor Beam + MK II

**Comment by Sandrem** [comment]
I can attack with primary weapon after Tractor Beam attack.
Are you sure that you used TIE/D title? Maybe you used TIE/x7 instead - it doesn't grant second attack.

I will check exception after death from obstacle damage.

**Comment by jamorbal** [comment]
With the other title, cannon slot is gone.
I gonna try it once again, maybe I skipped the second attack by mistake. 

Thank you! 

Enviado desde mi iPhone

**Comment by Sandrem** [comment]
> After tractor beam ability resolution, if the tractored ship dies because of obstacle damage, the game raises an exception. ( Console Red Message )

I reproduced this situation, but ship destruction was performed without any problems.

Maybe some additional requirements are needed.
Please, when you encounter a bug, make a screenshot - red text in console and squad lists are important information. Without this information I can spend a lot of time but don't find what ship/effects combination is needed to reproduce this bug.

I close this issue. If you will encouter this bug again - inform and attach screenshot.
