### ISSUE TITLE
Ryad's ability broken

### ISSUE THREAD

**Issue by goldfinger0014** [Sandrem/FlyCasual#749]
When I use Ryad's ability to K turn off a straight, the game treats it as a red K turn, doesn't let me perform any actions, and stresses her.

**Comment by pappnase99** [comment]
In Ryad's ability it says:
`string key = HostShip.AssignedManeuver.Speed + ".F.R";`

Whatever '.F.R' actually means, on the Defender these have `ManeuverColor.None` set except for one, something must be wrong here i guess?

**Comment by Sandrem** [comment]
Game uses 5-symbol codes for all maneuvers.

For example,
4.F.S means Speed-4. Forward, Straight
4.F.R means Speed-4, Forward, Rotate180

So code changes type of movement to K-turn, but leaves speed the same.

**Comment by Sandrem** [comment]
@goldfinger0014 I cannot reproduce the problem.
Can you reproduce it again? Maybe some additional requirements are needed, like some faceup crit that is assigned?

**Comment by Sandrem** [comment]
Still cannot reproduce.
