### ISSUE TITLE
R5-K6 dice throw breaks the game

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#750]
It was an online game, and I was the host. Opponent had R5-K6

![image](https://user-images.githubusercontent.com/35771439/37799673-b29bd666-2e20-11e8-920a-e34b46f4f29a.png)

**Comment by zdravkotatic** [comment]
Here once more:
![image](https://user-images.githubusercontent.com/35771439/37850377-2919fa10-2edb-11e8-8f05-8e6fce898ff8.png)

**Comment by Sandrem** [comment]
Seems that bug is network-only. (Sync of dice results)

**Comment by Sandrem** [comment]
Some fixes for R5-K6 where done. I cannot reproduce this bug - maybe it is fixed too.
If you will encounter same bug again in 0.4.3 or later - inform me.
