### ISSUE TITLE
Harpoon Condition

### ISSUE THREAD

**Issue by jamorbal** [Sandrem/FlyCasual#751]
Harpoon condition splashes to harpooner ( beyond range 1 ).
When a ship is dead by harpoon condition ( extra damage because a crit result ), such ship remains in play with hulk = 0 and shields = 0.

For reload action:
Configuration:
Alpha Strike with 2 harpoons missiles and extra munition. 
When reload, the game is completely freeze. This issue could arises because of the problem with the harpoon condition.

**Comment by jamorbal** [comment]
Nice, thanks for your effort 

Enviado desde mi iPhone

**Comment by Sandrem** [comment]
Fixed
