### ISSUE TITLE
0.4.2 H2 : Bots does not stress when using red maneuvers

### ISSUE THREAD

**Issue by sandro1337** [Sandrem/FlyCasual#752]
In almost any situation and with every ships, bot's ships does not stress after using a red maneuvers. In this example, the bwing 2 and 4 made a 4 straight red and did not get stress. Is also the case with k-turn or s-loop or t-roll.

![botdoesnotstress](https://user-images.githubusercontent.com/37774975/37876146-c234b92e-3048-11e8-9b16-dad59d1e4c9b.png)

**Comment by Sandrem** [comment]
AI uses rules of HotAC AI - they don't get stress, instead skip action.

Not a bug.
