### ISSUE TITLE
barrel roll

### ISSUE THREAD

**Issue by doji2008** [Sandrem/FlyCasual#753]
![screenshot_2018-03-25-22-41-58](https://user-images.githubusercontent.com/37707411/37888859-6be0a480-307e-11e8-9d82-2aae6cc4ddcf.jpg)

Everytime my opponent does a barrel roll.  the barrel roll adjustment appears on my screen.  at that point i am unable to click on an action because it appears behind the barrel roll adjustment.  I am unable to click on any begining of combat abilityies example gliterstem.  Iam also unable to confirm attack or defence dice forcing me to quit.

I amd not sure if this a bug, i have been in games and barrel rolled and my opponents appear to still be able to take actions. 

I have tried multiple different lists and it always happens the first time they barrel roll.

**Comment by doji2008** [comment]
Iwas using an android app this time, but also have that problem playing from a pc or on a tablet.

**Comment by doji2008** [comment]
![screenshot_2018-03-25-22-57-36](https://user-images.githubusercontent.com/37707411/37889167-00730f7e-3080-11e8-9652-5091e96fa693.jpg)

the lovely red text finaly appeared

**Comment by Sandrem** [comment]
This "barrel roll adjustment" window is for mobile devices only. Seems that this is bug only in cross-latform network multiplayer.

**Comment by doji2008** [comment]
Thank you.

**Comment by Sandrem** [comment]
Closed due to network mode rework
