### ISSUE TITLE
Adaptability not working

### ISSUE THREAD

**Issue by Jon-Pin** [Sandrem/FlyCasual#757]
Hi Sandrem,

I am playing on the 0.4.3 test build, and the Adaptability upgrade does not seem to be working.

![screenshot](https://user-images.githubusercontent.com/36263374/38138379-80c6f690-3422-11e8-808c-c526c8075b10.jpg)

**Comment by Sandrem** [comment]
AI only. Seems that AI doesn't fire trigger "After ship is placed".

**Comment by Tech55b** [comment]
Also seems to be on player controlled ships too.

Had Adaptability on Captain Nym Ps8 increased to PS9, the game is waiting for PS8 ship to finish set up.

![xwing-adaptability](https://user-images.githubusercontent.com/34559222/38170986-a50b0548-35d3-11e8-98db-915913afe989.jpg)

**Comment by Tech55b** [comment]
Also just did a restart and tested it using the -1 Adaptability and it worked fine.

**Comment by Sandrem** [comment]
Both bugs are fixed.
