### ISSUE TITLE
Quickdraw revenge shot skipped, then QD destroyed

### ISSUE THREAD

**Issue by JoshAddington** [Sandrem/FlyCasual#764]
![screen shot 2018-04-02 at 10 23 17 pm](https://user-images.githubusercontent.com/7219131/38226414-96395458-36c7-11e8-9aea-cccb7e65bf06.png)

Playing Fenn and Thweek against Quickdraw.

 - QD first shot at Fenn, taking him to 1 hull.
 - Thweek shot at QD (having shadowed QD's PS) and removed his first shields.
 - The text came up saying that QD would get his retaliatory shot, but that didn't happen.
 - Fenn then shot at QD and killed him.
 - QD was removed from the board and the error appeared.

**Comment by Sandrem** [comment]
Workaround is added. Will be changed in 0.5.0
