### ISSUE TITLE
Fenn Rau Sheath Ability [Bug]

### ISSUE THREAD

**Issue by Stankham** [Sandrem/FlyCasual#766]
I went to trigger a range one of Fenn Rau's Sheath ability against a Thweak. I chose to activate Fenn's ability. Then I was given the option to select the enemy Thweak's weapon. I selected his primary weapon instead of the equipped proton torpedoes. Then it crashed. 
![fenn rau sheath bug 4 4 18](https://user-images.githubusercontent.com/38088768/38340501-d0d36db2-3841-11e8-804b-80dc6bf2222f.png)

**Comment by Sandrem** [comment]
I already fixed similiar bug of Combat Activation.
0.4.3 with this fix will be released in few days.
