### ISSUE TITLE
Nym problem

### ISSUE THREAD

**Issue by Hellvomit** [Sandrem/FlyCasual#767]
{"name":"Poe & Nym","faction":"rebel","points":100,"version":"0.3.0","pilots":[{"name":"poedameron","points":36,"ship":"t70xwing","upgrades":{"title":["blackone"],"amd":["bb8"],"tech":["weaponsguidance"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Black One"}}},{"name":"captainnym","points":64,"ship":"scurrgh6bomber","upgrades":{"title":["havoc"],"mod":["shieldupgrade"],"turret":["twinlaserturret"],"torpedo":["protontorpedoes"],"missile":["harpoonmissiles"],"bomb":["protonbombs","protonbombs"],"ept":["expertise"],"system":["trajectorysimulator"],"samd":["unhingedastromech"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Captain Nym (Rebel)"}}}],"description":"Poe Dameron + Black One + BB-8 + Weapons Guidance
Captain Nym (Scurrg H-6 Bomber) + Havoc + Shield Upgrade + Twin Laser Turret + Proton Torpedoes + Harpoon Missiles + Proton Bombs + Proton Bombs + Expertise + Trajectory Simulator + Unhinged Astromech"}

issue after moving 1st round

**Comment by Sandrem** [comment]
I cannot start match with this squad in 0.4.3
Unique astromech must be installed to Nym (Havoc title restriction)

**Comment by Hellvomit** [comment]
Made the changes for Genius too, will retry tonight to send a snap shot of
error

**Comment by Sandrem** [comment]
I plan to release 0.4.3 tomorrow.
I recommend you to wait and test situation in the updated version.
