### ISSUE TITLE
Critical hits being cancelled before hits - 0.4.3

### ISSUE THREAD

**Issue by EL-BASTIDO** [Sandrem/FlyCasual#770]
Whilst playing a few games vs the AI, all critical hit damage was cancelled before standard hits.  This happened in both games played.  
Sorry, I have no supporting screenshots.....

**Comment by Sandrem** [comment]
I don't have enough information.
What squads were used? Maybe Scurrgs with autoblaster turrets? (crits are cancelled before hits).

**Comment by EL-BASTIDO** [comment]
Yes - both times against Scurggs. However, crits against the Scurggs were also cancelled before hits.

**Comment by Sandrem** [comment]
Thank you, I have enough information to check this bug. =)

**Comment by Sandrem** [comment]
Fixed in "0.4.3 hotfix 1" branch
