### ISSUE TITLE
Crits being Cancelled before Hits - Autoblaster 0.4.3

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#771]
I don't know if the previous person was using Autoblasters or not, but I had both Bossk and Kath Scarlet with Autoblasters and after they shot them once, the game kept allowing Crits to be Cancelled instead of Hits. I checked in the code for Autoblaster, and found the bolded portion, which sets CancelCritsFIrst to true, but then never changes it back afterward.

```
private void RegisterAutoblasterEffect()
        {
            **Combat.DiceRollAttack.CancelCritsFirst = true;**
            if ((Combat.ChosenWeapon is UpgradesList.Autoblaster) ||
                (Combat.ChosenWeapon is UpgradesList.AutoblasterTurret))
            {
                foreach (Die die in Combat.DiceRollAttack.DiceList)
                {
                    if (die.Side == DieSide.Success)
                    {
                        die.IsUncancelable = true;
                    }
                }
            }
}
```

**Comment by Sandrem** [comment]
Fixed in "0.4.3 hotfix 1" branch
