### ISSUE TITLE
Console Fire Bug

### ISSUE THREAD

**Issue by Stankham** [Sandrem/FlyCasual#772]
I am having an issue where a Console Fire roll is happening at the beginning of a game right after the first round of activations. I had an enemy ship during an AI game (this game was right before the game I am informing you of) that had a Console Fire crit keep rolling even after the ship with the Console Fire crit was destroyed.
![console fire bug](https://user-images.githubusercontent.com/38088768/38431821-8bc20bfe-3993-11e8-8889-3480a21e0057.png)

**Comment by Sandrem** [comment]
Fixed in "0.4.3 hotfix 1" branch
