### ISSUE TITLE
AI Player 2 no stress for red maneuvers?

### ISSUE THREAD

**Issue by mdublade** [Sandrem/FlyCasual#777]
Notice and confirmed this with 3 games using different ships - when the AI Player 2 ship does a Red Maneuver, it does not get a stress token. First noticed this when I saw basic TIE Fighters do back-to-back K-turns. And later watched Lambda shuttles sit and not move for 3 turns, and no stress. This by design or an issue?

**Comment by Sandrem** [comment]
Game uses "Heroes of Aturi Cluster" AI rules. If AI executes red maneuver - it just skips action, no Stress token is assigned.
Not a bug.
