### ISSUE TITLE
Intensity Bug

### ISSUE THREAD

**Issue by ryuneke** [Sandrem/FlyCasual#781]
Choosing Site of Intensity is opening console.
![intensity bug](https://user-images.githubusercontent.com/38154863/38453498-0ee06f62-3a57-11e8-92fd-5390566ffee9.png)

**Comment by Sandrem** [comment]
Thank you.

Same bug as with Adaptability, seems that this problem is for all Dual Upgrades.
I close this issue as duplicate.
