### ISSUE TITLE
0.4.3 Pivot Wing block game

### ISSUE THREAD

**Issue by sandro1337** [Sandrem/FlyCasual#783]
Pivot Wing on U-wing makes the game freeze at setup phase
![pivotwing](https://user-images.githubusercontent.com/37774975/38457064-11f77ae4-3a8c-11e8-9dc6-de228522c59b.png)

**Comment by Sandrem** [comment]
Common problem of all Dual Upgrades.
Already fixed in dev-branch, will be in hotfix ~ on Monday
