### ISSUE TITLE
0.4.3 Pulse ray shield trigger even after death

### ISSUE THREAD

**Issue by sandro1337** [Sandrem/FlyCasual#784]
When a ship with pulse ray shield is destroyed, the trigger for activating the ability remains at the end phase. Keep coming every turn if no is select, no effect observed if yes is select

**Comment by sandro1337** [comment]
In local mode, after being destroyed by an attack, any ship who had pulse ray shield will ask for it's activation. 

In this game, a M3-A interceptor with pulse ray shield got destroy during the previous turn, at the end phase, I still got the promt for the shield. If yes is selected the game promt the normal "shield restored" and "ship ionized" but doesn't seem to have any effet (the ship beeing effectively gone), if no is selected, the promt keep coming every end phase (cumulating with other pulse ray shield promt that may occur)
![pulse1](https://user-images.githubusercontent.com/37774975/38457698-695cc2f0-3a94-11e8-8a05-c52a74ac0a3e.png)

**Comment by Sandrem** [comment]
Thank you for the information

**Comment by Sandrem** [comment]
Fixed in dev-bracnh
