### ISSUE TITLE
Cluster Mines not triggering consistently

### ISSUE THREAD

**Issue by iantheace** [Sandrem/FlyCasual#786]
Bombs do not always trigger when an enemy ship's base is overlapping them (see picture).

![bombbug](https://user-images.githubusercontent.com/11569450/38460530-997ff9ec-3ab3-11e8-98dc-345e39c78a88.png)

**Comment by iantheace** [comment]
Another example
![bombsnotworking](https://user-images.githubusercontent.com/11569450/38460699-1a7dad48-3ab7-11e8-83ad-d7f8b48c6dd5.png)

**Comment by bitsai** [comment]
Just tested in newest release (0.9.2) using Proximity Mines (SE), which uses the same underlying code for collision detection as Cluster Mines.  Was not able to reproduce the problem shown in the screenshots.
