### ISSUE TITLE
Constant Harpoon Trigger issues

### ISSUE THREAD

**Issue by iantheace** [Sandrem/FlyCasual#787]
Hi,

I am unsure how exactly this happens, but I am intermittently getting issues with the harpoon condition going off turns after the ship which was harpooned was killed. For example, I killed a ship in the opening engagement, moved away, and 2 ships which wouldn't have even been in range of the original, took harpoon damage.

I know this is vague, I will see if I can make exact steps to recreate if you cannot see anything obvious.

**Comment by Sandrem** [comment]
Fixed
