### ISSUE TITLE
Harpoons Trigger when a ship dies from the original shot

### ISSUE THREAD

**Issue by iantheace** [Sandrem/FlyCasual#788]
Hi,

Basically if you shoot a ship with 3 hull, with a harpoon missile and kill it outright, the harpoon condition still triggers, the rules for harpoons are that the attacks is fully resolved before applying the harpoon condition, as such, when a ship is killed outright it should not trigger.

Note you also get this when you shoot a ship and kill it with harpoons that's already been harpooned, in that 2 harpoon effects trigger.

**Comment by jamorbal** [comment]
Also, I think I've found something weird with the Harpoon condition.
For instance: I shot two harpoons to an Y Wing ( it survive ), and then other ship hits to my Quick Draft, an I shoot once again to the first Y Wing, and I destroy it. The two conditions splashes, and affect to other Y Wing at range 1 from the target. In the next round, I shot to the Y Wing which received two damage from the harpoon condition during the previous round, and then a dialog appears asking for which harpoon effect resolve, even without critical result. And this splashes damage to all ships within range 1. It seems like the "harpoon condition" were "inherited" by such ship.

**Comment by Sandrem** [comment]
Fixed
