### ISSUE TITLE
Coordinate + Adv sensor strange behavior

### ISSUE THREAD

**Issue by sandro1337** [Sandrem/FlyCasual#797]
When coordinate is used with advance sensor (with the upsilon class shuttle), the ship selected can perform one action (doesn't matter which one is choosed) and then move (don't think the move always match the one normally planned). 
The shuttle is left with an unresolved manoeuver and in case the ship selected has a greater pilot skill, he will activate normally at his turn, making it his second activation. 

Experimented and reproduce on versus mode with any ship the shuttle tries to coordinate (in this game, soontir fel is prompt to activated after the bug and the shuttle still has his manoeuver on hold)
![coordinateadv](https://user-images.githubusercontent.com/37774975/38517418-434e4f5a-3c3a-11e8-9ef5-d4cb693093e8.png)

**Comment by Sandrem** [comment]
Was fixed
