### ISSUE TITLE
0.4.3.1 Network: Kylo Ren (Crew) breaks the game in first round if no valid target at range 1-3

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#798]
I was the host in the network game. My Decimator had Kylo Ren as a crew member. I used Kylo Ren ability but had no opponent at range 1-3. Pressing the skip button breaked the game.

**Comment by zdravkotatic** [comment]
My squad:
{"name":"Kylo Bug","faction":"imperial","points":99,"version":"0.3.0","pilots":[{"name":"rearadmiralchiraneau","points":55,"ship":"vt49decimator","upgrades":{"crew":["kyloren","rebelcaptive","systemsofficer"],"ept":["calculation"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}},{"name":"patrolleader","points":44,"ship":"vt49decimator","upgrades":{"crew":["systemsofficer","deathtroopers"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}}],"description":"Rear Admiral Chiraneau + Kylo Ren + Rebel Captive + Systems Officer + Calculation
Patrol Leader + Systems Officer + Death Troopers"}

**Comment by Sandrem** [comment]
Fixed
