### ISSUE TITLE
0.4.3.1 vs AI: "I'll show you ..." breaks the game 

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#799]
While dealing crit over shields:
![image](https://user-images.githubusercontent.com/35771439/38521476-19a1367a-3c46-11e8-9d81-b2ab6c6e32df.png)

My squad:
{"name":"Kylo Bug","faction":"imperial","points":99,"version":"0.3.0","pilots":[{"name":"rearadmiralchiraneau","points":55,"ship":"vt49decimator","upgrades":{"crew":["kyloren","rebelcaptive","systemsofficer"],"ept":["calculation"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}},{"name":"patrolleader","points":44,"ship":"vt49decimator","upgrades":{"crew":["systemsofficer","deathtroopers"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Gray"}}}],"description":"Rear Admiral Chiraneau + Kylo Ren + Rebel Captive + Systems Officer + Calculation
Patrol Leader + Systems Officer + Death Troopers"}

**Comment by Conzar** [comment]
Confirmed

**Comment by Sandrem** [comment]
Fixed
