### ISSUE TITLE
Pattern analyzer: Focus tokens disappear in the combat phase

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#800]
I was using the following squad:

{"name":"TIEfo","faction":"imperial","points":100,"version":"0.3.0","pilots":[{"name":"omegaace","points":29,"ship":"tiefofighter","upgrades":{"mod":["stealthdevice"],"tech":["advoptics"],"ept":["opportunist"]},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}},{"name":"epsilonleader","points":24,"ship":"tiefofighter","upgrades":{"mod":["stealthdevice"],"tech":["patternanalyzer"]},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}},{"name":"zetaleader","points":29,"ship":"tiefofighter","upgrades":{"mod":["stealthdevice"],"tech":["advoptics"],"ept":["expose"]},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}},{"name":"zetaace","points":18,"ship":"tiefofighter","upgrades":{},"vendor":{"Sandrem.FlyCasual":{"skin":"First Order"}}}],"description":"\"Omega Ace\" + Stealth Device + Advanced Optics + Opportunist
\"Epsilon Leader\" + Stealth Device + Pattern Analyzer
\"Zeta Leader\" + Stealth Device + Advanced Optics + Expose
\"Zeta Ace\""}

after flying took Focus on each of them. They disappeared in the combat phase. I have used the ability of Pattern analyzer

**Comment by zdravkotatic** [comment]
It is possible that the ability of Epsilon Leader removes the focuses instead of stress tokens...

**Comment by zdravkotatic** [comment]
I have made some tests and come to conclusion that the pattern analyzer is irrelevant at this bug. It is the ability of Epsilon Leader that removes focuses instead of stress tokens

**Comment by zdravkotatic** [comment]
It is very easy to fix:

  private void UseEpsilonLeaderAbility(object sender, System.EventArgs e)
        {
            List<GenericToken> tokensToRemove = new List<GenericToken>();

            Vector2 range = new Vector2(1, 1);
            foreach(GenericShip friendlyShip in Board.BoardManager.GetShipsAtRange(HostShip, range, Team.Type.Friendly))
            {
                GenericToken focusToken = friendlyShip.Tokens.GetToken(typeof(FocusToken));
                if (focusToken != null)
                {
                    tokensToRemove.Add(focusToken);
                }
            }

            Actions.RemoveTokens(tokensToRemove, Triggers.FinishTrigger);

Just change focusToken with stressToken

**Comment by Sandrem** [comment]
Thank you for the new information, I plan to release "0.4.4 Hotifx 2" tomorrow, I will try to fix this bug in this update too.

**Comment by Sandrem** [comment]
Fixed
