### ISSUE TITLE
 0.4.3.1 - 'Chopper' crew dealing face up damage cards

### ISSUE THREAD

**Issue by bcutlerGC** [Sandrem/FlyCasual#802]
Issue seen when using Chopper Crew on Wullffwarro (Auzituck Gunship) 

Card Text
You may perform actions even while you are stressed.
After you perform an action while you are stressed, suffer 1 damage.

After shields are gone when performing actions while stressed face up damage cards are being assigned.
This should just be regular damage

**Comment by Sandrem** [comment]
Thank you for the information, I can reproduce this bug.

**Comment by Sandrem** [comment]
Fixed
