### ISSUE TITLE
0.4.3.1 - Rage incorrectly triggers damage from 'Chopper' crew

### ISSUE THREAD

**Issue by bcutlerGC** [Sandrem/FlyCasual#803]
Issue seen when using Rage and 'Chopper' combination on Wullffwarro (Auzituck Gunship)

Perform white or green move (no stress)
Select 'Rage' as action
  - Rage condition assigned
  - Focus Assigned
  - First Stress assigned
  - Second Stress assigned
  - Damage from Chopper is assigned

As the ship was not stressed before triggering rage this should not have triggered the chopper damage.

FYI - I can confirm that rage appears to be working without an issue on ship that DO NOT have chopper crew.

![image](https://user-images.githubusercontent.com/37866837/38619030-245e796c-3d93-11e8-9491-5134b4d1cb5c.png)

![image](https://user-images.githubusercontent.com/37866837/38619023-1ea675f6-3d93-11e8-82c0-89234ce190e4.png)

**Comment by Sandrem** [comment]
Thank you for such detailed bug report =)

**Comment by bcutlerGC** [comment]
Least I can do after you made such a great X-wing game. Also my day job is test manager for a software company so I should be able to log a decent bug ;-) Would like to do wider testing on this for you but between work and my 16 month old son i never get the time

**Comment by Sandrem** [comment]
Fixed
