### ISSUE TITLE
Network Crash - Target Lock fail 0.4.3.1

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#806]
![flycasual 2 1 1](https://user-images.githubusercontent.com/38116924/38656365-9a99584e-3ddf-11e8-91d4-3135deed669a.png)
![flycasual 2 1 2](https://user-images.githubusercontent.com/38116924/38656366-9ab52a38-3ddf-11e8-8fe0-facdb97b440d.png)
![flycasual 2 1 3](https://user-images.githubusercontent.com/38116924/38656367-9ac5336a-3ddf-11e8-9172-57da53aac73b.png)
Friend and I were testing network games via a tablet and a phone on same wifi.

4x Storm Squad TIE Advanced w/Title & Adv Target Computer v. Marrek Stele TIE Def, Countess Ryad TIE Def, and Siener TIE Aggressor.

Issue: Marrek Stele tried to Target Lock (or check range to target lock) after second round of movement, and after the distance failed, I received no warning that it failed. The game simply did nothing and the "SKIP" button appeared. I tried to re-click on my targets, but nothing happened. After clicking "SKIP" is when it crashed.

**Comment by doji2008** [comment]
![image](https://user-images.githubusercontent.com/37707411/38658754-432cf948-3ddb-11e8-97b7-2a4a91befd69.png)
Not sure if it is the same but I got the same error trying to target lock quick draw with torani.

On a side note I have seen red text everytime I have targetlock, I was always able to close the text and continue.  This time I also had the skip button appear and was unable to close the command prompt or click skip to continue.

**Comment by Sandrem** [comment]
Fixed
