### ISSUE TITLE
place pilot skill 0

### ISSUE THREAD

**Issue by doji2008** [Sandrem/FlyCasual#807]
![image](https://user-images.githubusercontent.com/37707411/38657723-a19db68e-3dd6-11e8-82ee-07483d3d8433.png)

I was in the middle of a game with someone, then It flashed to a set upscreen vs a new opponent and ask for player one to place the pilot skill 0 pilot.

Which is kinda of funny because the game had just froze and I was trying to get a screen shot of a different bug.  I had 2 pre combot ability dalan and a gliterstem.  I told it to skip dalan and it asked if I wanted to gliterstem but the yes or no box was not there and there was no way for me to use or skip.

**Comment by Sandrem** [comment]
This problem is caused by the first bug with Dalan/Glitterstim.
Please, if you will see that bug again - provide a screenshot with opened console ("CTRL + Q" to open).
