### ISSUE TITLE
Autoblasters not allowing canceling die at range 3 Rear Fire Arc - 0.4.3.1

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#808]
No picture this time as no error/crash occured.

It was the late portion of a game. Kath Scarlet's Firespray (enemy ship) had used Autoblasters from the front Arc (and intended), but when she attacked using her Rear Fire Arc, I was not allowed to cancel regular hits (it showed the lightning bolt icon on them). It went away too quickly to screen capture.

I was not able to quickly double check as the ship ran off the board afterward.

**Comment by Sandrem** [comment]
Same problem as was with Autoblaster Turret.

**Comment by Sandrem** [comment]
Seems that this bug was fixed.
Please, next time provide screenshots too.
