### ISSUE TITLE
Moving table

### ISSUE THREAD

**Issue by Tigger1980** [Sandrem/FlyCasual#809]
Hi, great simulator. but at my home desktop and workdesktop (windows10) the table keeps moving so you cant realy see the table. might have something to do with de 3D-connexion driver of my "spacemouse" since that is the first thing I can come up with both desktops have in common. laptop without this driver running windows10 has no problems . Or it might be a dual monitor issue... I have 2 monitors on both desktops

**Comment by Sandrem** [comment]
This is problem with driver.

Open game's console ("CTRL"+"~") and try to enter commands:
input axis
or
input mouse

**Comment by Tigger1980** [comment]
Tnx that did the trick. After the commands the camera movement can't de done by AWSD anymore, but the mouse at the edge of the screen pans the screen. Tnx for your fast solution, keep up the development of this sim; it's very nice.
