### ISSUE TITLE
advanced sensors / failed target lock

### ISSUE THREAD

**Issue by tron999** [Sandrem/FlyCasual#811]
Playing as kylo w/advanced sensors in an online match tonight. I tried for a target lock, and was not in range. It did not drop me back to the action menu. I had to skip twice, and then it moved my dial move. Then it was stuck on waiting for my pilot skill 9 (kylo) movement. had to drop the game. This behavior happened twice in successive online games.

**Comment by bravodingo** [comment]
This is for most failed actions (1.0), where if I fail an action, ie illegal barrel roll, the only option is to Skip. The same applies for Pushing the Limit; any "illegal" action, to include a TL out of range, surrenders the entire action phase for that ship.

**Comment by Sandrem** [comment]
I just fixed this bug ("First Edition: if action is failed, another action cannot be taken instead")
