### ISSUE TITLE
Wullffwarro pilot ability not triggering

### ISSUE THREAD

**Issue by Kakioz** [Sandrem/FlyCasual#814]
Loving the app, fantastic work.

Have been flying Wullffwarro today, both in my own squad and the AI squad. Despite regularly dropping him down to no shields and and 1+ damage, the additional dice this is meant to provide never seems to materialise.

Edit: Running the most recent version, 0.4.3.1. Let me know if you need more data

**Comment by Sandrem** [comment]
Cannot reproduce.
Please, provide me screenshot where Wullffwarro throws only 3 dice when ability must be active.
Maybe some additional conditions are needed, or ship really had full hull / crit "reduce attack by 1"...

**Comment by Kakioz** [comment]
Have just played a few games with Wullffwarro in the new 0.4.4 hotfix, and haven't had that problem.
