### ISSUE TITLE
Had trouble with RACLo

### ISSUE THREAD

**Issue by BlueFalconX250** [Sandrem/FlyCasual#815]
Screenshots of the redtext included. 

![screen shot 2018-04-13 at 2 02 44 pm](https://user-images.githubusercontent.com/35779761/38753286-86fc3802-3f23-11e8-8061-e36cd6bc33a4.png)
![screen shot 2018-04-13 at 2 02 54 pm](https://user-images.githubusercontent.com/35779761/38753284-86e29cd0-3f23-11e8-87ca-1a63aa4eeb0a.png)

**Comment by Sandrem** [comment]
Thank you for information and screenshots.
Bug of "Kylo Ren (crew)". I close this issue as duplicate (is already reported).
