### ISSUE TITLE
Black One title doesn't work with VI

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#816]
Snap Wexley with Veteran instincts should be able to equip the Black One title

**Comment by qasur** [comment]
Veteran Instincts (and Adaptability) do not kick in until after the ship is deployed. The Pilot Skill of the Character is printed until on the table.

**Comment by rune-b** [comment]
really? I see there is a FAQ entry for Adaptability that says this, but I don't see anything like this for Veteran Instincts

**Comment by sheepeatingtaz** [comment]
Adaptability is in place forces, VI is not. VI is just "Increase your pilot
skill by 2" therefore works fine with snap to allow him to take the title.

**Comment by Sandrem** [comment]
Yes, this is a bug. Ability of VI must work in squad builder.

**Comment by Sandrem** [comment]
Fixed
