### ISSUE TITLE
Critical Hit effect triggers after starting a new game

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#817]
I played a game where one of the ships got console fire. Then I exited to main menu and started a new game. At the start of the first combat phase I got a console fire die roll, and then the game crashes because the ship that originally had the console fire doesn't exist anymore

![image](https://user-images.githubusercontent.com/11047987/38754653-0117f68c-3f63-11e8-97d1-b1c49c7a5a65.png)

**Comment by Sandrem** [comment]
Fixed
