### ISSUE TITLE
Barrel Roll/Decloaking off the board causing game to crash.

### ISSUE THREAD

**Issue by Stankham** [Sandrem/FlyCasual#821]
Whenever someone chooses a barrel roll or decloak that causes them to not complete because it would put them off of the game board causes the game to crash.

**Comment by Sandrem** [comment]
What mode did you play? Vs AI or online multiplayer?

**Comment by Stankham** [comment]
Online multiplayer

**Comment by Sandrem** [comment]
Fixed
