### ISSUE TITLE
VI and Adaptability with A-Wing Test Pilot result in an incorrect Pilot Skill value

### ISSUE THREAD

**Issue by kyledsimpson** [Sandrem/FlyCasual#822]
Found on 0.4.3.1 - to reproduce:
An A-wing (I use Green Squadron Pilot in this example) with the Title upgrade A-Wing Test Pilot means that ship can then equip VI and Adaptability.
During Setup Phase the game shows them as PS5.
Once the ship is placed, you're asked to choose +1 or -1 for Adaptability.
If you choose +1 the ship's final PS becomes PS4.  The correct value should be PS6.
If you choose -1 the ship's final PS becomes PS2.  The correct values should be PS4.
This isn't a display bug either because the ships will actually play by the value of the PS shown, either PS2 or PS4.

**Comment by Sandrem** [comment]
Thank you for the information.

**Comment by Sandrem** [comment]
Fixed
