### ISSUE TITLE
Advanced Sensors + Squad Leader + Advanced SLAM causes strange behavior

### ISSUE THREAD

**Issue by jychuah** [Sandrem/FlyCasual#823]
I have Advanced Sensors and Squad Leader on Backdraft and Advanced Slam on Major Vynder. When I use Advanced Sensors + Squad Leader on Backdraft to target Major Vynder and make him use the SLAM action, I get one of two behaviors - either an extra SLAM movement or all of a sudden he just flies off the board instantaneously (very fast animation) and is destroyed. If there is a way for me to submit logs I will gladly do so.

**Comment by Sandrem** [comment]
Thank you for detailed information, I can reproduce this bug.

**Comment by Sandrem** [comment]
According to FE rules, "A ship cannot perform SLAM as a free action."
This rule works correctly, so this situation is not possible anymore.
