### ISSUE TITLE
Tractor Beam: Boost/BR is "may".

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#827]
> In the table top game Tractor beam gives you the option to move your opponent, or leave him where he (because it is a "may") is and reduce their agility. Currently, Fly Casual doesn't give you the choice to leave the ship where it is.

**Comment by qasur** [comment]
I've been using Tractor Beam in all of my TIE Defenders list over last few days. While there is not "may" option, you can just click "SKIP" and it will move to the next step as though it was a may option.
