### ISSUE TITLE
Harpoons problem?

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#828]
> Playing against AI, shot an enemy that wasn't harpooned with primary weapon, enemy was at 1 hull left, triggered non-existant harpoon splash damage which led to this glitch:
https://imgur.com/a/9dZQ6
Pumped a harpoon into this invincible ship next round, and it remained on the board alive.

**Comment by jamorbal** [comment]
The same for me. It seems like harpoon condition were propagated to other ships.

**Comment by sirlee** [comment]
I also get those 0 Hitpoints ships often, with "Harpooned". When Harpooned deals splash damage, and a ship dies of it, it remains on the board with 0 Hitpoints. I don't know if it matters but to be more precise: An enemy harpooned ship dealt splash damage to my ships and my ship died but remained on the board with 0 hit points.

**Comment by Sandrem** [comment]
> Got a bug report. Harpooned condition applied by Dalan Oberos (in the Kimogila) dealt splash damage beyond range 1 when triggered. In this case, at least at range 3 (splashed onto Dalan at R3). I had no ships at range 2 or beyond range 3.

**Comment by Sandrem** [comment]
Already fixed
