### ISSUE TITLE
Palpatine bug

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#833]
Had Omega Leader locked with Scum Nym, fired Harpoon.
Used TL to re-roll 3/4 dice, then chips.
Threw error as I guess the AI tried to use Palp on the evade roll?
![palp bug](https://user-images.githubusercontent.com/33504209/38933016-2931e97e-435b-11e8-9d30-9f267020078c.jpg)

**Comment by Sandrem** [comment]
Fixed
