### ISSUE TITLE
Lightweight Frame Can be Used Repeatedly

### ISSUE THREAD

**Issue by Juanflaco** [Sandrem/FlyCasual#840]
Just downloaded 0.4.4 Hotfix 1 and noticed that Lightweight Frame (on Quickdraw in this instance) can be used repeatedly in the same round (this was in a match against AI). I was able to keep clicking it and adding dice indefinitely.

**Comment by Sandrem** [comment]
Will be fixed in "0.4.4 Hotfix 2".
Bug: If dice modification doesn't spend a token - it can be used many times instead of only one.

**Comment by Juanflaco** [comment]
Thank you!

**Comment by Sandrem** [comment]
Fixed
