### ISSUE TITLE
0.4.4 hf 2 -- Dengar (Jumpmaster 5000) error

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#845]
![4 2 2 hotfix 2 1-1](https://user-images.githubusercontent.com/38116924/39099245-e1abe6ce-463c-11e8-957d-a063b09ac928.png)
![4 2 2 hotfix 2 1-2](https://user-images.githubusercontent.com/38116924/39099246-e4fb99be-463c-11e8-94b5-f27ad2f69daa.png)
As far as upgrades go, I had Dengar and Manaroo (both Jumpmaster 5000s) with Attani Mindlink on both ships, plus a PS1 Z-95 Headhunter as my list.

On the First round Dengar moved within Range 3 of two of the Y-Wings. Dengar fired with no issues, then the first Y-Wing attacked back. Before taking damage, the error screen popped up *however* it still allowed me to roll & modify defense dice.
I typed "close" the get rid of the error screen in order to see if I finish the defense dice phase, and it worked. I took damage Dengar triggering his ability to attack back. I did so, but the Y-Wing took no damage.

I did not take a second screen shot, but the second Y-Wing also attacked at Dengar and before I could defend again, it triggered the same error screen.

**Comment by Sandrem** [comment]
Thank you for detailed information.

Was this the first match after launch of game, or second+ ?

**Comment by qasur** [comment]
This was the first match after upgrading to 0.4.4 hotfix 2.

Fwiw, it also just caused the same error against the scum Z-95 Headhunter in second game I just started.

**Comment by qasur** [comment]
Is there a way to generate the "red" text plus the preceding say 20 lines into a "crash.txt" file to upload easier?

**Comment by Sandrem** [comment]
Use command "copy" in the console to copy all text in it.

**Comment by Sandrem** [comment]
Fixed
