### ISSUE TITLE
Adavance slam on shuttle Crashes game

### ISSUE THREAD

**Issue by Pretywargirl** [Sandrem/FlyCasual#846]
HI me and my friend are playing mulit online and every time hes done adavance slam on the first movement phase with alpha class star wing major vynder game crashes ty. 
![screenshot 7](https://user-images.githubusercontent.com/38636141/39100915-c436be16-4646-11e8-9ce8-086f90f70679.png)
![screenshot 8](https://user-images.githubusercontent.com/38636141/39100916-c7bbe930-4646-11e8-8ade-8a0c2118e1c7.png)

**Comment by Sandrem** [comment]
Seems that SLAM is broken in online games. I will check.

**Comment by Pretywargirl** [comment]
okay thank you so much, your amazing!

**Comment by Sandrem** [comment]
Fixed
