### ISSUE TITLE
Too many dice shown while attacking (sometimes 10 or more dice) 

### ISSUE THREAD

**Issue by Sandrem** [Sandrem/FlyCasual#850]
> https://i.imgur.com/VZ6VnfY.jpg

**Comment by nunatak-jb** [comment]
I have also seen this with Evade dice - usually after an error with Tarn or Intensity (will log those separately).

**Comment by Sandrem** [comment]
> usually after an error with Tarn or Intensity

You get an error (console with red text), then close console to continue game, am I right?

**Comment by Sandrem** [comment]
Problem with dice happens when players try to ignore some bug and continue game - but current match is already broken, only more bugs are caused.
