### ISSUE TITLE
Fenn Rau coordinate action doesn't work in Internet Game

### ISSUE THREAD

**Issue by andrelpgoncalves** [Sandrem/FlyCasual#852]
Hello,
We tried to use coordinate action and it didn't work in Internet Game. The game still in function, but we have to choose another action.

**Comment by Sandrem** [comment]
Seems that is fixed.
If problem will be present in 0.4.6 - inform me.

**Comment by andrelpgoncalves** [comment]
Thanks, Sandrem.

We'll be check in 0.4.6 update.

Regards,

*ANDRÉ GONÇALVES*

2018-04-30 16:47 GMT-03:00 Sandrem <notifications@github.com>:
