### ISSUE TITLE
NulllReferenceException with specific setup

### ISSUE THREAD

**Issue by xenoxsis** [Sandrem/FlyCasual#869]
Twitce now I have had the following exception using the same setup:

> NullReferenceException: Object reference not set to an instance of an object
> 
> Combat.CompareResultsAndDealDamageClient ()
> GameModes.LocalGame.CompareResultsAndDealDamage ()
> Combat.CompareResultsAndDealDamage ()
> GameManagerScript+<WaitCoroutine>c_Iterator0.MoveNext ()
> UnityEngine.SetupCoroutine.InvokeMoveNext (IEnumerator enumerator, IntPtr returnValueAddress)

Like I said it happened twice. On two different computers but using the exact same setup.

Steps to reproduce:
1. Rebel Ships: X-Wing: Luke Skywalker + Proton Torpedoes
2. Empire Ships: Tie Fighter: "Mauler Mithel" and Tie Fighter: "Night Beast"
3. Player is Luke Skywalker
4. Head for the nearest tie fighter. To get within combat range (doesn't seem to matter which one)
5. Complete a combat phase (first time I destroyed 1 tie fighter, second time Luke missed, and the tie fired back and missed)
6. After fight: NullReferenceException

**Comment by xenoxsis** [comment]
Note: Battle can continue after console is closed

**Comment by bcutlerGC** [comment]
I have been seeing this issue a lot during various games (Player Vs AI) Windows machine - seen in 0.4.5 and previous version

The error occurs at the point when Damage is dealt to a players ship (Shield or Hull)
It does not appear to matter which ship is attacking or defending (seen with various combinations
It does not appear to matter which weapon was used in the attack (Def happens with TLT and Harpoon, Think it also happens with regular attack but not 100% sure i remember)

![nullref](https://user-images.githubusercontent.com/37866837/39360738-5874d080-4a17-11e8-87cc-5701eb8ff843.png)

Should be easy enough to replicate using this squad against one of the random opponents

{"name":"Final Form","faction":"rebel","points":99,"version":"0.3.0","pilots":[{"name":"captainnym","points":49,"ship":"scurrgh6bomber","upgrades":{"title":["havoc"],"mod":["longrangescanners"],"turret":["twinlaserturret"],"torpedo":["extramunitions"],"missile":["harpoonmissiles"],"bomb":["thermaldetonators","ionbombs"],"ept":["veteraninstincts"],"system":["trajectorysimulator"],"samd":["genius"]},"vendor":{"Sandrem.FlyCasual":{"skin":"Captain Nym (Rebel)"}}},{"name":"mirandadoni","points":50,"ship":"kwing","upgrades":{"mod":["longrangescanners"],"turret":["twinlaserturret"],"torpedo":["extramunitions"],"missile":["harpoonmissiles"],"crew":["sabinewren"],"bomb":["clustermines","bombletgenerator"]},"vendor":{"Sandrem.FlyCasual":{"skin":"White"}}}],"description":"Captain Nym (Scurrg H-6 Bomber) + Havoc + Long-Range Scanners + Twin Laser Turret + Extra Munitions + Harpoon Missiles + Thermal Detonators + Ion Bombs + Veteran Instincts + Trajectory Simulator + \"Genius\"
Miranda Doni + Long-Range Scanners + Twin Laser Turret + Extra Munitions + Harpoon Missiles + Sabine Wren + Cluster Mines + Bomblet Generator"}

**Comment by Sandrem** [comment]
Fixed in dev branch.
