### ISSUE TITLE
Renegade Refit not reducing EPT squad points granted by R2-D6

### ISSUE THREAD

**Issue by zdravkotatic** [Sandrem/FlyCasual#870]
Occurred with Garven:
![image](https://user-images.githubusercontent.com/35771439/39316882-8cf09c24-497a-11e8-98ee-73bb81e9c9e0.png)
![image](https://user-images.githubusercontent.com/35771439/39316893-931b0c92-497a-11e8-9764-f20d6ca2ec68.png)

**Comment by bcutlerGC** [comment]
I think you had some other problem when you were building that ship. Your first screen shot shows a point cost of 29 for some reason but it should have been **28** (26 pilot + 1, astro + 1 ept) which you can see in my screenshot.

![image](https://user-images.githubusercontent.com/37866837/39357006-6972756c-4a09-11e8-8af1-467a985d7c67.png)

When Adding the Renegade Refit (26 pilot + 1, astro + 1 ept - 2 refit) I see a total cost of **25** this is actually incorrect as it should be **26**. So there is a problem here when using R2-D6 as I have not seen this problem when using the other x-wings which have a native EPT. 

![image](https://user-images.githubusercontent.com/37866837/39360593-d5cf63b6-4a16-11e8-8756-56b27c7ceebb.png)

**Comment by Sandrem** [comment]
Fixed.
@Azrapse Please, test a bit.
