### ISSUE TITLE
Red manoeuvres not registering stress

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#880]
Hi Sandrem and co,

I've noticed on a few AI controlled ships when they do a K-Turn or a Talon, the move shows as red, and they don't get an action, however no stress is assigned. 
Is this a token display issue or is the move not being processed properly?
I can screenshot if needed.

**Comment by Sandrem** [comment]
AI uses rules of "Heroes of Aturi Cluster" AI. After red maneuvers it just skips action, without any stress token.

Bot a bug.
