### ISSUE TITLE
Decloak doesn't allow positioning 

### ISSUE THREAD

**Issue by zehkaiser** [Sandrem/FlyCasual#888]
Only tested with Whisper. When selecting to decloak the direction is not selectable.

When in the bottom left corner I could not decloak because the board edge was to the left and another ship was to the right. I was told decloak cannot overlap another ship. Decloaking straight 2 was open, but not an option. 

I then attempted to decloak and was told I cannot overlap obstacles. An asteroid was to my left, but decloaking forward or right was available. 

Next I attempted a decloak with obstacles on both sides and my ship decloaked forward.

**Comment by Sandrem** [comment]
Fixed
