### ISSUE TITLE
On Linux - Double Key Stroke

### ISSUE THREAD

**Issue by Conzar** [Sandrem/FlyCasual#892]
Typing text on Linux causes the key to be repeated.  So if typing the key '1', the text field will show '11'.

**Comment by Sandrem** [comment]
Problem of some distos of Linux, please, report to Linux developers instead.

**Comment by Sandrem** [comment]
I see that problem is already reported on Unity forums:
https://issuetracker.unity3d.com/issues/linux-keystrokes-recorded-twice

**Comment by Sandrem** [comment]
Anyway, I don't plan to try fix this.

**Comment by Conzar** [comment]
2018.1.0b13 works and does not have this problem.  I just tried it on the development branch.  So I think you just need to use a newer version of unity.

**Comment by Sandrem** [comment]
Thank you for this information. I will update my Unity and build 0.4.6 in the latest version of it.
