### ISSUE TITLE
Can we have the option for the drop-down squad builder? The image based one requires images to work, as opposed to having red question marks like this:

### ISSUE THREAD

**Issue by madeaccountspecificallyforthisbug** [Sandrem/FlyCasual#894]
![glitch bomb](https://user-images.githubusercontent.com/38886111/39476521-3af2fd32-4d2a-11e8-9671-02a266728007.png)
![glitch mod](https://user-images.githubusercontent.com/38886111/39476522-3b298a3c-4d2a-11e8-9c8e-a6f25ae3a382.png)
![glitch rocket](https://user-images.githubusercontent.com/38886111/39476523-3b3f3184-4d2a-11e8-96ff-f672be96acbb.png)
![glitch torpedo](https://user-images.githubusercontent.com/38886111/39476524-3b54d020-4d2a-11e8-9d00-4f42dab7d914.png)

Most slots actually work, but the lack of kitting out a bomber of any sort/faction without trial or error is a little bit of a let-down.

**Comment by madeaccountspecificallyforthisbug** [comment]
Forgot to mention that this is an issue with pilots as well.
![punisher glitch](https://user-images.githubusercontent.com/38886111/39476626-a5235d5a-4d2a-11e8-9288-0ddddd89e5bf.png)

**Comment by Sandrem** [comment]
Hi. Usually if Internet is not availalbe - white rectangles are shown only with name and cost of card.
Seems that you had unknown errors during download of images, so game thinks that images are downloaded and use broken images from cashe.
As a temporary solution, go to "%userprofile%\AppData\LocalLow\Sandrem\Fly Casual_ X-Wing TMG Simulator\ImageCache" and delete all images (or only images with size 0). This will remove cached images and they will be re-downloaded.

**Comment by madeaccountspecificallyforthisbug** [comment]
Thanks man! The errors were my fault: began to play the game with certain upgrades after I was no longer connected to the internet.

**Comment by Sandrem** [comment]
Fixed in 0.4.6
