### ISSUE TITLE
Colonel Jendon ability break the game if skipped

### ISSUE THREAD

**Issue by sandro1337** [Sandrem/FlyCasual#900]
In versus mode (0.4.5), when Colonel Jendon ask for using his ability (giving a blue targer lock at range 1) if you select yes but do not have a friendly ship at range 1, the skip button does not work. The game remains blocked in that phase and you can't select anything.
 
![jendoncrash](https://user-images.githubusercontent.com/37774975/39525735-25202edc-4e1d-11e8-8212-b835f1a2f9c1.png)

**Comment by rune-b** [comment]
I get the same bug. I will look into this
