### ISSUE TITLE
X-Wing 2.0

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#901]
Not sure if this has been mentioned anywhere here, but is the plan to still just complete Fly Casual 100% with all Version 1.0 cards? Then start on a 2.0 option in the game?

Just curious.

Thanks!

Also, keep up the excellent work guys (all of you).

**Comment by Sandrem** [comment]
I don't have all information about rules so far. But seems that I can support both editions of rules in single game.
