### ISSUE TITLE
0.4.6 - Stealth Device becomes cumulative/stacked

### ISSUE THREAD

**Issue by ekulnesro** [Sandrem/FlyCasual#902]
Unfortunately I don't have any screenshots, but when I was running 3 TIE-Interceptors each with Stealth Device, each hit on each TIE would result in a cumulative decrease in agility for all hit ships. I believe this happened as well on an E-Wing, where a hit each hit would stack the decrease in agility (similar to what was happening with decloaking before it was fixed, and thanks for that!)

Keep up the great work!

**Comment by ekulnesro** [comment]
I'll grab screens tomorrow if I can.

**Comment by rune-b** [comment]
I tried to reproduce this, but I only got decreased agility for the ships that were actually hit. Do you remember exactly what ships and upgrades you were using?

**Comment by rune-b** [comment]
Possibly related to #910

**Comment by ekulnesro** [comment]
Yes, this is correct, I was incorrect that it was across all ships, #910 displays the same problem. It's not just interceptors though, I've seen it on other ships using Stealth Device. But it is ship per ship, not across the game as I originally thought. Thanks for the correction.

**Comment by rune-b** [comment]
OK. It should work again in the next release.
