### ISSUE TITLE
Malwarebytes identifying the game as a malware

### ISSUE THREAD

**Issue by Vazkman** [Sandrem/FlyCasual#903]
It's just happening with 0.4.6. Has this happened before with someone else? Can I put it in my whitelist with no problems?

![mwb 0 4 6](https://user-images.githubusercontent.com/1640572/39609458-770a4d9c-4f1f-11e8-8cfa-7b185d7ffb63.PNG)

**Comment by Sandrem** [comment]
Some antiviruses (in most of cases - free antiviruses like Avira and AVG) think that file is suspicious because it is too new.
But it is safe: https://www.virustotal.com/ru/file/b253769ad69ce8688d1ac98c87272159889d51a9b9f4c2173e0903c822693a6e/analysis/1525412627/

So you can add it to whitelist.
