### ISSUE TITLE
Different Critical Damage cards drawn during network game

### ISSUE THREAD

**Issue by Azrapse** [Sandrem/FlyCasual#918]
During a network game, in my computer, the A-wing suffered a critical damage as result of an attack, and drew this card:
![image](https://user-images.githubusercontent.com/6807260/39844829-eaa63bc8-53fa-11e8-8e2e-17539e78368a.png)
The other player instead saw that the card drawn was a Direct Hit. Since the A-wing had 1 hull left after getting the card, it survived in my computer with 1 hull because it didn't draw a Direct Hit in my computer. But it was destroyed on the other player's computer because there it drew a Direct Hit.
![image](https://user-images.githubusercontent.com/6807260/39844867-2aedb526-53fb-11e8-9600-adeb4226c3fd.png)
That is the exact same moment after getting the Direct Hit in the other player's computer. The A-wing blew up and is gone, while it still lives in mine.

The game couldn't resynch from there and after another round, the A-wing didn't get the Perform Action panel in my computer and got stuck.

**Comment by Sandrem** [comment]
Closed due to network mode rework
