### ISSUE TITLE
Discarded Stealth Device keeps "discarding" and reducing agility

### ISSUE THREAD

**Issue by mdublade** [Sandrem/FlyCasual#925]
Notice this happen when Firefly is equip with Stealth Device upgrade. First time hit during attack, Stealth Device is discarded and agility reduced by 1, as expected. When hit by subsequent attacks, keeps discarding the discarded Stealth Device, and agility is reduced by 1 again. After 3 attack that hit, the Firefly had no agility. Saw this happen when AI controlling ship, and when player controls ship. Checked with other ships, same thing happens. Every time you hit a ship that had already discarded the Stealth Device, the agility keeps getting reduced.

**Comment by Sandrem** [comment]
Already fixed in development branch. Fix will be in the next update.
