### ISSUE TITLE
Autothrusters not Firing

### ISSUE THREAD

**Issue by Juanflaco** [Sandrem/FlyCasual#926]
![autothrusters_issue](https://user-images.githubusercontent.com/38587032/39968482-93dfc312-568a-11e8-99f9-a0281ac3e74b.png)
Autothrusters don't appear to be firing (tested with both Kylo Ren and the Inquisitor). As seen in the attached screenshot Kylo only has "Focus" and "First Order Vanguard" as options when being attacked by Rey outside her firing arc. This issue appears to be new with version 0.4.6

Thank you for the great work!

**Comment by Sandrem** [comment]
Already fixed in development branch. Fix will be in the next update.
