### ISSUE TITLE
Thane Kyrell's ability locks up the game

### ISSUE THREAD

**Issue by WillKennerley** [Sandrem/FlyCasual#927]
When his ability is triggered, the game locks up without being able to choose an action (the ability)

**Comment by Sandrem** [comment]
I cannot reproduce this problem.
Please, try to find steps how you can reproduce this. Then, open console (CTLR + ~) and send here screenshot.

**Comment by WillKennerley** [comment]
<img width="1440" alt="screen shot 2018-05-14 at 11 35 37" src="https://user-images.githubusercontent.com/770985/39992537-0a9e745e-576b-11e8-81a2-01127404b7e4.png">

This isn't the only squad where I have had it fail; it was just easier to reproduce with more ships.

**Comment by Sandrem** [comment]
Thank you for the details, I will check.

**Comment by Sandrem** [comment]
Cannot reproduce in current version
