### ISSUE TITLE
Launching bombs with "Trajectory Simulator" and "Genius"

### ISSUE THREAD

**Issue by Bo-Shek** [Sandrem/FlyCasual#928]
A bit of a convoluted bug, but:
"Genius" allows bomb drops (of bombs without "Action:" headers, like "Proton Bombs") to be performed *after* you reveal and execute a maneuver.  "Trajectory Simulator" allows you to launch bombs using the 'straight 5' template rather than dropping them. However, even when "Trajectory Simulator" is equipped, it would seem that Genius' ability does not allow you to use the 'straight 5' template to launch bombs (it automatically drops them using the 'straight 1' template).

**Comment by Sandrem** [comment]
FAQ, Page 22:

Trajectory Simulator:
Trajectory Simulator can be used only when the ship  would drop a bomb via the means printed on an equipped (bomb) Upgrade card. It cannot be used while using "Genius" to drop a bomb after performing a maneuver, or in conjunction with any other effects that override the manner in which the bomb is dropped, such as "Crimson Specialist."

Not a bug.
