### ISSUE TITLE
Add support of ultra wide screens (21:9)

### ISSUE THREAD

**Issue by kellengreen** [Sandrem/FlyCasual#929]
I'm unable to scroll down to ships _below-the-fold_ on the ship selection screen.

**Version:** 0.4.6
**OS:** Ubuntu 18.04
**Hardware:** Lenovo 25th anniversary.

**Comment by Sandrem** [comment]
Please, send me screenshot of that screen.

**Comment by kellengreen** [comment]
![image](https://user-images.githubusercontent.com/1750507/40024676-035fd622-57c7-11e8-9bfa-970a6e626fea.png)

**Comment by Sandrem** [comment]
This screen was designed for usual aspect ratio, where all ships fit.
I will add scroll for this situation in one of nearest versions.

Do you have problems on another screens? If yes, send more screenshots.

**Comment by Sandrem** [comment]
Moved to https://github.com/Sandrem/FlyCasual/wiki/Requested-Features
