### ISSUE TITLE
Receive a script error...

### ISSUE THREAD

**Issue by Hedric3248** [Sandrem/FlyCasual#930]
New Game Vs AI - seems to be a script error that always happens on round 2 - happens every time.

![screen-1](https://user-images.githubusercontent.com/16512152/40036941-6ca01102-5802-11e8-99f3-48b4bf58cea4.png)

![screen-2](https://user-images.githubusercontent.com/16512152/40037023-d5d64bf0-5802-11e8-9e56-f9d98e550322.png)

**Comment by Sandrem** [comment]
Fixed
