### ISSUE TITLE
Quickdraw AI and ion pulse missles

### ISSUE THREAD

**Issue by Vindigo19** [Sandrem/FlyCasual#941]
1. First issue I've noticed when I played against AI quickdraw shoot first and then console was showing up.
2. When Kilamogila shoots from ion pulse missles, second time using the extra munitions, damage is incorrect. Enemy ships suffer normal damage without ions tokens.
3. Scyk hasn't 5-manouver on its dial.

Kindly regards and thanks for this project from Poland.

Chris

**Comment by Vindigo19** [comment]
Now, when I play this ships anyone shoots first primary weapon causes this bug.
<img width="960" alt="error 1" src="https://user-images.githubusercontent.com/39444568/40273075-c117bad6-5bb9-11e8-9c8b-80051617b782.png">

**Comment by rune-b** [comment]
I have fixed the Scyk dial, see pull request #945

**Comment by Sandrem** [comment]
Was fixed
