### ISSUE TITLE
Advanced Ailerons + zero maneuver

### ISSUE THREAD

**Issue by Bo-Shek** [Sandrem/FlyCasual#953]
Hey, when "Advanced Ailerons" is equipped on a TIE Reaper, and you aren't stressed- if you set your dial to the red 'zero maneuver', after the mandatory white straight-1 or turn-1 is executed, there is an error and the game can't continue to the next ship in the Activation phase.

**Comment by Sandrem** [comment]
Network or Local mode?

**Comment by Bo-Shek** [comment]
Local mode - might also be a Network issue, but I haven't tried.

**Comment by Sandrem** [comment]
Fixed
