### ISSUE TITLE
Hobbie Klivian's ability

### ISSUE THREAD

**Issue by jasoncohn** [Sandrem/FlyCasual#955]
When I have Targeting Astromech equipped to Hobbie and I perform a red maneuver (either 4K or 3 talon-roll with S-foils) it does allow me to aquire a target lock and clear my stress with Hobbie's ability, but it won't then allow me to perform an action. I should be able to perform an action with Hobbie as his stress is cleared immediately after acquiring a target lock with his pilot ability.

**Comment by rune-b** [comment]
Currently the game skips the action step altogether after doing a red maneuver. I have submitted a fix for this.
