### ISSUE TITLE
uncontrolled screen scrolling in map

### ISSUE THREAD

**Issue by buckowens74** [Sandrem/FlyCasual#961]
.0.4.6 I all of a sudden have issues with the game map uncontrolabley scrolling on its own without me touching the mouse or keyboard. Also looks like I can't pick any moves or actions on my ship

**Comment by Sandrem** [comment]
Seems that you have some gamepad or joystick connected to your PC - so it sends input signal to the game.
Or you have some complex drivers for mouse / graphics pad etc.

I don't plan to fix this issue in the nearest updates (Only few players reported it).
You can open console (CTRL + ~) and enter command to turn off movement of camera by mouse input:
input mouse
