### ISSUE TITLE
Multiple Issues: Outside Firing Arc (when not), Autothrusters not working, and Measuring Range Incorrectly (all same game w/screenshots)

### ISSUE THREAD

**Issue by qasur** [Sandrem/FlyCasual#963]
![outside firing arc](https://user-images.githubusercontent.com/38116924/40579208-00330062-60e8-11e8-9b65-e44f51707fe9.png)
There have been a few close calls when I've been told I'm "outside the firing arc", but this time I took a screen shot because it's pretty clear the arc would touch any portion of the Y-Wings base.

Which leads me to asking, can we get an option to see draw a line from the edge of the firing arc to the target ship as we shoot it? Kinda like how me see the measuring tool when a ship is outside the arc?

**Comment by qasur** [comment]
![autothrusters](https://user-images.githubusercontent.com/38116924/40579275-50d8098a-60e9-11e8-8e97-0f5f64b6f330.png)
In the same game, the Y-Wings are firing Twin Laser Turrets (TLTs) and I have never been given the option to use Autothrusters to add an [Evade] result when defending.

4x Scum Y-Wings random list VS 2x IG-2000s (both with title cards), Heavy Laser Cannons, Fire Control Systems, Engine Upgrades, and Autothrusters.

**Comment by qasur** [comment]
![measuring](https://user-images.githubusercontent.com/38116924/40579303-1a501c26-60ea-11e8-87bf-1220b4b3a67d.png)
Back again, in the same game haha
So, after the Y-Wing here defended the first attack from Heavy Laser Cannon (which I though I was not close enough to use), I was able to fire a second time via the IG-88's ability. This time it showed a measuring stick, and I notice that it just did not make sense as you can see from the screenshot.

The measuring template is not even on the firing arc line. The corner of the template is under the large base.

**Comment by Sandrem** [comment]
Arc/distance measurement is completely rewritten in 0.5.0 due to similiar bugs.
This update will be released in few days. Please, inform me if you will see similiar bugs in 0.5.0+
