### ISSUE TITLE
SE: Cluster Missiles' second attack

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#971]
When doing the second cluster missiles attack I got the option to shoot with primary weapon

**Comment by Sandrem** [comment]
Did you tried to shoot with primary weapon?

**Comment by rune-b** [comment]
No. Will try that too

**Comment by rune-b** [comment]
Also, when killing a ship with the first cluster missile, the second attack doesn't happen. Possibly related to my bugfix on twin attacks against the same ship

**Comment by rune-b** [comment]
Tried it again, but did not get a second attack this time either

**Comment by TNG-Wing** [comment]
Just a bump. In SE, Cluster Missiles stop the game on trying to do the 2nd Cluster Missile attack. You can't do anything, only select things. 

Thanks again!

**Comment by falconett** [comment]
Another bump. This is still an issue. 
When I perform a cluster missile attack, the first one works fine. When prompted to perform the second attack, the only option is to use primary weapon - which I shouldn't be able to use. 2nd attack option should only be with cluster missiles. 

Error I'm getting: "Wrong conditions, Target is not legal"... 

So, it seems like two things are wrong here. 1) I'm selecting another target, so "Target not legal" is in correct. and 2) When I'm performing the second attack only weapon option should be cluster missiles, not primary or turret.

Only option is to skip to move forward.

I've uploaded a video of it here: https://photos.app.goo.gl/f2R8rpQMjKK1MiR88

**Comment by starjoe4** [comment]
Hi, I saw a note somewhere that the cluster missile issue was fixed, but I still can't get the second attack to function.

It seems to be trying to fire the primary weapon (I'm using the Falcon) instead of making the bonus cluster missile attack.

**Comment by Unclebaby** [comment]
I'm seeing this issue also.

**Comment by DarwinW13** [comment]
Definitely still an issue. Every possible target for second attack gets "Wrong conditions, target is not legal" even though they should be completely valid targets. Version 0.7.6 on Mac.

**Comment by romakarol** [comment]
Still an issue as described, windows latest version

**Comment by Sandrem** [comment]
Fixed

**Comment by pakirby1** [comment]
Which build is this fixed in?
