### ISSUE TITLE
SE: Ionized ship was able to perform maneuver

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#972]
A player controlled TIE Fighter was ionized by an AI Y-Wing. It was able to do a regular maneuver the round after (K-Turn) and the token was not removed. The round after, the Ion token took effect and forced a straight maneuver and focus action

**Comment by Itchy218** [comment]
Same issue, but the AI y wing was able to continue picking manuevers even with multiple ion tokens.  Meanwhile, if I used pulse ray shield to ionize myself, ion token worked properly on my ship.

**Comment by Sandrem** [comment]
Fixed
