### ISSUE TITLE
0.5.0 FE Problem with PTL

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#974]
I saw that someone already reported the problem with linked actions in SE.

The same thing happens in FE with PTL. In my case Fenn Rau with PTL wasn't prompted for a second action, instead it just focused as a second action. 
When i selected Focus as my first action, the ship took a random target lock too, but i will need to see if i can reproduce this.

I was however always properly stressed by the second action.

**Comment by Sandrem** [comment]
Same problem: https://github.com/Sandrem/FlyCasual/issues/970

Will be fixed in hotfix soon.

**Comment by Sandrem** [comment]
Fixed
