### ISSUE TITLE
0.5.0 - SE - Null Ref Crash at start of Combat phase

### ISSUE THREAD

**Issue by houseofcutler** [Sandrem/FlyCasual#978]
This has happened to me a few times in a row.

Player vs AI
Rebel List (Player) - Luke, Wedge, Gold
Imp List (AI) - Vader - Tie Swarm
Random Rock Placement

We perform our opening moves
Combat Phase starts
  - Null ref Exception is thrown
  - Not able to select a ship for combat
  -  If manually selecting a ship a message says 'Need Player 1 and Pilot skill 13'

Windows 10 machine
 
![image](https://user-images.githubusercontent.com/34140446/40716040-90401ee6-63ff-11e8-92c8-3dd2b4980824.png)

**Comment by rune-b** [comment]
There are references to Console Fire crit in the game log, but none of the ships look damaged. Could be related to #817 
'
@houseofcutler - Is it correct that no ships had received critical damage in this game? Do you remember if you had played a game right before, where you did get a Console Fire crit?

**Comment by Sandrem** [comment]
Fixed
