### ISSUE TITLE
FE Barrel roll/decloak problem

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#982]
When playing in FE, after a failed barrel roll (overlapping) i didn't get prompted an option for another action, but i could skip.

After a failed decloak overlapping an asteroid, the same thing happened, but it was impossible to skip too, hanging up the game like that.

**Comment by Jartis9** [comment]
I've had the same issues. That decloak problem has stalled out 3 or 4 games.

**Comment by Sandrem** [comment]
Fixed
