### ISSUE TITLE
Adaptability Bonus doubled with second Flip EPT

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#983]
When i have Adaptability and Intensity equipped on a Green Squadron A-Wing, Adaptability gives it +1 PS when i select Adaptability +1 and then another +1 PS when i select the first flip side on Intensity

I know its a very minor bug since its a pretty wild combo, but nonetheless funny to see.
![2018-05-30](https://user-images.githubusercontent.com/39746661/40749869-bb163d7e-6465-11e8-99e6-ef69bff39bc3.png)

**Comment by Sandrem** [comment]
Fixed
