### ISSUE TITLE
Cannot assign optimised prototype to Whisper

### ISSUE THREAD

**Issue by TooheysN00b** [Sandrem/FlyCasual#988]
Krennic is crew on the Phantom (with RAC, the other ship) at place forces it throws the following error screen when I try and choose the Phantom. 
Has worked in previous versions.
![opt-prop](https://user-images.githubusercontent.com/33504209/40872173-4c910f80-668d-11e8-9ed0-db48de801282.jpg)

**Comment by Sandrem** [comment]
Fixed
