### ISSUE TITLE
0.5.0 HF1, FE: Ship is alive with 0 hull

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#989]
A protectorate starfighter was killed by a gunship with same PS. But after attacking back it was not destroyed.

The crit is a Direct Hit.

![image](https://user-images.githubusercontent.com/11047987/40879400-72df735e-669f-11e8-8c87-48c4ec926f25.png)

**Comment by rune-b** [comment]
The ship was allowed to make a maneuver the next round, and then was removed after combat

**Comment by rune-b** [comment]
Happened again with another ship right after

![image](https://user-images.githubusercontent.com/11047987/40879467-73111084-66a0-11e8-932e-c0705837aa50.png)

**Comment by Sandrem** [comment]
Fixed
