### ISSUE TITLE
0.5.0 HF 1 SE console holdup

### ISSUE THREAD

**Issue by Jartis9** [Sandrem/FlyCasual#994]
![image](https://user-images.githubusercontent.com/39911972/40920383-5ef13fe4-67da-11e8-9ca9-104c5a21eb0a.png)

I've experienced this issue a lot tonight. I'm not sure if it's an issue caused by the end of the E-Wing's maneuver, or the start of the Y-Wing's maneuver. It doesn't crash the game, just freezes it for a few seconds and then the console pops up, Typing "close" in the console takes care of that, but to get the game to continue I have to left click on one of my ships, which then shows the range between one of the AI ships and whichever of my ships I clicked on briefly before the Y-Wing starts to move. At first I thought the issue was caused by the Y-Wing being ioned, but sometimes it happens anyway, multiple times a game.

**Comment by Sandrem** [comment]
Fixed.

Next time, please, scroll error message up - I need to see first lines of error.
