### ISSUE TITLE
0.5.0 HF1 SE: Boba Fett gets a bonus focus when using reinforce.

### ISSUE THREAD

**Issue by CaptainJaguarShark** [Sandrem/FlyCasual#995]
At a guess, I think it's adding the extra focus from perceptive copilot.

**Comment by Sandrem** [comment]
Cannot reproduce.

Boba Fett was controlled by human or AI?
Please, provide screenshot where I can see both focus and reinforce tokens.

**Comment by CaptainJaguarShark** [comment]
So far, I've only been able to reproduce it when AI is controlling. 

![log for reinforce and focus](https://user-images.githubusercontent.com/2208847/41504037-8a5a0ad0-71a8-11e8-90b0-fc2c8d0f0c31.PNG)

![reinforce and focus](https://user-images.githubusercontent.com/2208847/41504001-7bedb1fa-71a7-11e8-8fb8-d6017a5fb706.PNG)

**Comment by Sandrem** [comment]
Thank you, now I know where to search =)

**Comment by Sandrem** [comment]
Fixed
