### ISSUE TITLE
FE: Dice modified with Concord Dawn Protector are not shown

### ISSUE THREAD

**Issue by rune-b** [Sandrem/FlyCasual#997]
In the roll in the screenshot below, one of the defense dice was turned into an evade with Concord Dawn Protector. None of the attack dice were greyed out, but the ship only took 2 damage (as it should)

![image](https://user-images.githubusercontent.com/11047987/40997183-0fdcd744-6904-11e8-85d3-cbac0f00da4a.png)

**Comment by Sandrem** [comment]
Fixed
